### ISSUE TITLE
Error in plugin event listener

### ISSUE THREAD

**Issue by brainstorm** [NationalSecurityAgency/ghidra#1023]
```
Error in plugin event listener
java.lang.NullPointerException
	at ghidra.app.plugin.debug.DbViewerComponent.closeDatabase(DbViewerComponent.java:100)
	at ghidra.app.plugin.debug.DbViewerProvider.closeDatabase(DbViewerProvider.java:46)
	at ghidra.app.plugin.debug.DbViewerPlugin.deactivateViewer(DbViewerPlugin.java:93)
	at ghidra.app.plugin.debug.DbViewerPlugin.processEvent(DbViewerPlugin.java:100)
	at ghidra.framework.plugintool.Plugin.eventSent(Plugin.java:324)
	at ghidra.framework.plugintool.mgr.EventManager.sendEvents(EventManager.java:263)
	at ghidra.framework.plugintool.mgr.EventManager.fireEvent(EventManager.java:208)
	at ghidra.framework.plugintool.PluginTool.firePluginEvent(PluginTool.java:464)
	at ghidra.framework.plugintool.Plugin.firePluginEvent(Plugin.java:476)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.fireActivatedEvent(MultiProgramManager.java:278)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.setCurrentProgram(MultiProgramManager.java:251)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.setCurrentProgram(MultiProgramManager.java:193)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.lambda$setCurrentProgram$5(ProgramManagerPlugin.java:455)
	at ghidra.util.Swing.doRun(Swing.java:295)
	at ghidra.util.Swing.runNow(Swing.java:211)
	at ghidra.util.Swing.runNow(Swing.java:166)
	at ghidra.util.SystemUtilities.runSwingNow(SystemUtilities.java:253)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.setCurrentProgram(ProgramManagerPlugin.java:458)
	at ghidra.app.plugin.core.progmgr.MultiTabPlugin.programSelected(MultiTabPlugin.java:265)
	at ghidra.app.plugin.core.progmgr.MultiTabPanel.setSelectedProgram(MultiTabPanel.java:193)
	at ghidra.app.plugin.core.progmgr.MultiTabPanel$3.mousePressed(MultiTabPanel.java:323)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6629)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2019-sep.-16 2329 AEST
Ghidra Version: 9.1
Java Home: /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
JVM Version: Amazon.com Inc. 11.0.3
OS: Mac OS X 10.14.6 x86_64
Workstation: brainstorm.lan
```

**Comment by ryanmkurtz** [comment]
[Fixed](https://github.com/NationalSecurityAgency/ghidra/commit/af8f1e6484dea64357fead818d8f5d30847d75e4)
