### ISSUE TITLE
IllegalArgumentException - Width (0) and height (0) cannot be <= 0

### ISSUE THREAD

**Issue by brainstorm** [NationalSecurityAgency/ghidra#1037]
```
Uncaught Exception! 
IllegalArgumentException - Width (0) and height (0) cannot be <= 0
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.desktop/sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:75)
	at java.desktop/sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:122)
	at java.desktop/java.awt.GraphicsConfiguration.createCompatibleVolatileImage(GraphicsConfiguration.java:307)
	at java.desktop/java.awt.GraphicsConfiguration.createCompatibleVolatileImage(GraphicsConfiguration.java:241)
	at java.desktop/javax.swing.RepaintManager.getVolatileOffscreenBuffer(RepaintManager.java:1098)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1543)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1060)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:78)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:115)
	at java.desktop/java.awt.Container.paint(Container.java:2002)
	at java.desktop/java.awt.Window.paint(Window.java:3940)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:876)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1890)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at java.desktop/java.awt.Component.show(Component.java:1716)
	at java.desktop/java.awt.Component.setVisible(Component.java:1663)
	at java.desktop/java.awt.Window.setVisible(Window.java:1031)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005)
	at docking.DockingDialog.setVisible(DockingDialog.java:317)
	at docking.DockingWindowManager.lambda$doShowDialog$6(DockingWindowManager.java:1720)
	at ghidra.util.Swing.doRun(Swing.java:295)
	at ghidra.util.Swing.runNow(Swing.java:211)
	at ghidra.util.Swing.runNow(Swing.java:166)
	at ghidra.util.SystemUtilities.runSwingNow(SystemUtilities.java:253)
	at docking.DockingWindowManager.doShowDialog(DockingWindowManager.java:1724)
	at docking.DockingWindowManager.showDialog(DockingWindowManager.java:1756)
	at docking.DockingErrorDisplay.doShowDialog(DockingErrorDisplay.java:103)
	at docking.DockingErrorDisplay.lambda$showDialog$0(DockingErrorDisplay.java:91)
	at ghidra.util.Swing.runIfSwingOrRunLater(Swing.java:127)
	at ghidra.util.SystemUtilities.runIfSwingOrPostSwingLater(SystemUtilities.java:267)
	at docking.DockingErrorDisplay.showDialog(DockingErrorDisplay.java:90)
	at docking.DockingErrorDisplay.displayMessage(DockingErrorDisplay.java:78)
	at docking.DockingErrorDisplay.displayErrorMessage(DockingErrorDisplay.java:42)
	at ghidra.util.Msg.showError(Msg.java:333)
	at ghidra.SwingExceptionHandler.handleUncaughtException(SwingExceptionHandler.java:81)
	at ghidra.GhidraThreadGroup.handleUncaughtException(GhidraThreadGroup.java:68)
	at ghidra.GhidraThreadGroup.uncaughtException(GhidraThreadGroup.java:38)
	at java.desktop/java.awt.EventDispatchThread.processException(EventDispatchThread.java:222)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:214)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2019-sep.-19 0826 AEST
Ghidra Version: 9.1
Java Home: /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
JVM Version: Amazon.com Inc. 11.0.3
OS: Mac OS X 10.14.6 x86_64
Workstation: brainstorm.lan
```

**Comment by ryanmkurtz** [comment]
Do you remember what you were doing or clicked on when this happened?

**Comment by ryanmkurtz** [comment]
Probably this: https://bugs.openjdk.java.net/browse/JDK-8229821

Since this is a Java problem, I'm going to go ahead and close it.

**Comment by dev747368** [comment]
For anyone else that lands here if searching for this error, please leave a comment with your details.

I personally have this error on an Ubuntu 22.04 machine when any java application is visible on the screen and I disconnect and reconnect the monitor.  When reported to upstream bugs.java.com, they marked it as unable to reproduce.

**Comment by brainstorm** [comment]
@dev747368 They solved that for me at Amazon's Corretto JRE here: https://github.com/corretto/corretto-11/issues/46

But I suspect that more recent versions of OpenJDK JREs (and others like zulu, etc...) already include this patch since I've not had this bothering me again.

Hope this helps!

**Comment by aadityacool06** [comment]
I have also faced the same issue while running Jmeter whole night and it seems Dev747368 is correct. I have also off and on the screen multiple times. This may be the cause but what is the solution or is it known issue, pls help.

2022-11-15 18:15:43,360 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:75) ~[?:?]
	at sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:122) ~[?:?]
	at java.awt.GraphicsConfiguration.createCompatibleVolatileImage(GraphicsConfiguration.java:307) ~[?:?]
	at java.awt.GraphicsConfiguration.createCompatibleVolatileImage(GraphicsConfiguration.java:241) ~[?:?]
	at javax.swing.RepaintManager.getVolatileOffscreenBuffer(RepaintManager.java:1098) ~[?:?]
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1543) ~[?:?]

**Comment by sliedes** [comment]
This happens to me reliably on OpenJDK 21 whenever I switch off my two monitors on Linux/Wayland and switch them on back later. Switching to OpenJDK 23 seems to have fixed it completely for me, or at least it doesn't happen anything resembling 100% of the time, to my surprise after reading the OpenJDK bug reports.

If it's in any way helpful for either Ghidra or OpenJDK I can try to figure out what the difference here is or even bisect an OpenJDK commit, but someone will have to tell me first it's helpful, otherwise I will just live happily on with it now working for me. :)

**Comment by cuimanman12** [comment]
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
        at java.desktop/sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:75)
        at java.desktop/sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:122)
        at java.desktop/java.awt.GraphicsConfiguration.createCompatibleVolatileImage(GraphicsConfiguration.java:307)
        at java.desktop/java.awt.GraphicsConfiguration.createCompatibleVolatileImage(GraphicsConfiguration.java:241)
        at java.desktop/javax.swing.RepaintManager.getVolatileOffscreenBuffer(RepaintManager.java:1098)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1543)
        at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:271)
        at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
        at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
        at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
        at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
        at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1890)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
