### ISSUE TITLE
NPE when loading a PDB file/xml

### ISSUE THREAD

**Issue by d0sboots** [NationalSecurityAgency/ghidra#1041]
**Describe the bug**
When loading PDB XML, if Ghidra can't resolve certain data types, it throws NullPointerException and aborts the load.

**To Reproduce**
Load the following minimal repro:

```
<pdb file="c:\test.pdb" exe="test" guid="{C6C79321-94CA-4D6B-9079-7140B53FCB3D}" age="1">
	<functions>
		<function name="Foo" address="0x1230" length="0x8">
			<stack_variable name="this" kind="ObjectPointer" offset="0x40" datatype="DoesNotExist *" length="0x0" />
		</function>
	</functions>
</pdb>
```

**Expected behavior**
There is a warning about the inability to resolve "DoesNotExist *", without aborting.

**Screenshots**
No screenshot, but here's the error dialog:

```
Problem parsing or applying PDB information: NullPointerException
java.io.IOException: Problem parsing or applying PDB information: NullPointerException
	at ghidra.app.util.bin.format.pdb.PdbParserNEW.applyTo(PdbParserNEW.java:406)
	at pdb.LoadPdbTask$1.analysisWorkerCallback(LoadPdbTask.java:61)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1683)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:685)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:785)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:664)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:629)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:62)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:101)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException

---------------------------------------------------
Build Date: 2019-May-16 1545 EDT
Ghidra Version: 9.0.4
Java Home: C:\Program Files\Java\jdk-11
JVM Version: Oracle Corporation 11
OS: Windows 7 6.1 amd64
Workstation: 192.168.0.3
```

**Attachments**
The minimal repro is obvious missing the type, but this was observed from a real pdb.xml that it couldn't find cross references for (even though they existed). I'm attaching the original pdb.xml.
[SimDLL.pdb.broken.xml.zip](https://github.com/NationalSecurityAgency/ghidra/files/3640571/SimDLL.pdb.broken.xml.zip)

**Environment (please complete the following information):**
See above

**Comment by ryanmkurtz** [comment]
9.1-BETA has just been released.  It would be very helpful to us if you could retest with that version.

**Comment by d0sboots** [comment]
Interesting. The cache headers on https://ghidra-sre.org are wrong; I knew it was updated, but I had to force-reload (ctrl-F5) in order to get a version that showed the new release.

Works just as I'd hope, both with the minimal example and the real file. There are thousands of unmatched symbols (1766 messages truncated), which is a separate problem, but no exceptions thrown.

**Comment by ryanmkurtz** [comment]
Yea we've been seeing something similar with the website.  Thanks for testing this!
