### ISSUE TITLE
NPE on Swing Update Manager

### ISSUE THREAD

**Issue by brainstorm** [NationalSecurityAgency/ghidra#1076]
I was just analyzing a ~2MB SH4 ELF and this came up:

```
Unexpected exception in Swing Update Manager
java.lang.NullPointerException
	at db.Table.getName(Table.java:556)
	at ghidra.app.plugin.debug.DbViewerComponent$TableItem.<init>(DbViewerComponent.java:250)
	at ghidra.app.plugin.debug.DbViewerComponent.updateTableChoices(DbViewerComponent.java:171)
	at ghidra.app.plugin.debug.DbViewerComponent.refresh(DbViewerComponent.java:119)
	at ghidra.app.plugin.debug.DbViewerComponent$3.run(DbViewerComponent.java:82)
	at ghidra.util.task.SwingUpdateManager.doWork(SwingUpdateManager.java:309)
	at ghidra.util.task.SwingUpdateManager.checkForWork(SwingUpdateManager.java:263)
	at ghidra.util.task.SwingUpdateManager.lambda$new$0(SwingUpdateManager.java:146)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2019-sep.-19 0826 AEST
Ghidra Version: 9.1
Java Home: /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
JVM Version: Amazon.com Inc. 11.0.3
OS: Mac OS X 10.14.6 x86_64
Workstation: brainstorm.lan
```

**Comment by ryanmkurtz** [comment]
[Fixed](https://github.com/NationalSecurityAgency/ghidra/commit/83f84d9ad2f7ad662d2f50c25ecef0cd10955e17)
