### ISSUE TITLE
Emulation Test Framework Exception Logging Error

### ISSUE THREAD

**Issue by VGKintsugi** [NationalSecurityAgency/ghidra#1089]
While running ./build in /ghidra/Ghidra/Extensions/SleighDevTools/pcodetest I got the following traceback:

`Traceback (most recent call last):
  File "./build", line 86, in <module>
    PCodeTestBuild.factory(PCodeTest).main()
  File "/home/poberoi/ghidra/Ghidra/Extensions/SleighDevTools/pcodetest/pcodetest.py", line 197, in main
    self.compile(input_files, opt_cflag, out_name)
  File "/home/poberoi/ghidra/Ghidra/Extensions/SleighDevTools/pcodetest/pcodetest.py", line 430, in compile
    self.associated_info(output_file, output_base)
  File "/home/poberoi/ghidra/Ghidra/Extensions/SleighDevTools/pcodetest/pcodetest.py", line 353, in associated_info
    stdout=('%s.nm' % base))
  File "/home/poberoi/ghidra/Ghidra/Extensions/SleighDevTools/pcodetest/build.py", line 38, in run
    self.log_err(cmd)
  File "/home/poberoi/ghidra/Ghidra/Extensions/SleighDevTools/pcodetest/build.py", line 197, in log_err
    self.log_pr('# ERROR: ' + what)
TypeError: cannot concatenate 'str' and 'list' objects
`

Clearly the try/except logic on line 35 of build.py needs to be reviewed.

**Comment by mumbel** [comment]
i think i came across this as well, but once I got the params right for my setup it went away.  Could you change that to `('# ERROR: %r ' % what)` and see what list gets printed?

**Comment by VGKintsugi** [comment]
# ERROR: ['/home/user/sh2compiler/Saturn-SDK-GCC-SH2/toolchain//SuperH/saturn-sh2-elf/bin/nm', '-a', u'SH2_GCC_O0_pcodetest.out'] 
# ERROR: OSError(2, 'No such file or directory')

**Comment by astrelsky** [comment]
The // may be the issue.

**Comment by VGKintsugi** [comment]
I deleted nm to cause the error. However there is an issue with how build.py is logging errors that is itself causing an exception and then a traceback. The error should be handled properly be build.py.

**Comment by ryanmkurtz** [comment]
Fixed by 74281c745d2df4f23699825406a0c094c592d8d6
