### ISSUE TITLE
ELF binary causes Out of Bounds Exception 

### ISSUE THREAD

**Issue by ryancor** [NationalSecurityAgency/ghidra#1119]
**Describe the bug**
Loading a ELF binary causes 
```Error importing file: keygenme
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at ghidra.app.util.opinion.ElfProgramBuilder.markupSectionHeaders(ElfProgramBuilder.java:890)
	at ghidra.app.util.opinion.ElfProgramBuilder.load(ElfProgramBuilder.java:151)
	at ghidra.app.util.opinion.ElfProgramBuilder.loadElf(ElfProgramBuilder.java:100)
	at ghidra.app.util.opinion.ElfLoader.load(ElfLoader.java:151)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:346)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:401)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

---------------------------------------------------
Build Date: 2019-Sep-23 1119 EDT
Ghidra Version: 9.1-BETA
Java Home: /Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home
JVM Version: Oracle Corporation 11.0.2
OS: Mac OS X 10.14.6 x86_64
Workstation: macbook-pro-5.lan1```
```

**To Reproduce**
1. Go to Import File
2. Select the ELF binary i have provided

**Expected behavior**
To start analyzing the binary 

**Environment (please complete the following information):**
 - OS: Mac 10.14.2
 - Java Version: 11.0.2
 - Ghidra Version: 9.1

**Comment by ryancor** [comment]
[keygenme.zip](https://github.com/NationalSecurityAgency/ghidra/files/3698715/keygenme.zip)

**Comment by dev747368** [comment]
Were there any previous exceptions logged?

**Comment by ryancor** [comment]
@dev747368 nope :/ this was the only exception I saw

**Comment by ryanmkurtz** [comment]
Looks like it's reporting the number of section headers as -1, which we don't handle well.  Possibly caused by something like this:

http://em386.blogspot.com/2006/10/elf-no-section-header-no-problem.html

**Comment by ryanmkurtz** [comment]
The author of the crackme put something in to trip up analysis tools like Ghidra.  I deleted my prior post explaining what the problem is because getting past it is probably part of the exercise.  It's an easy fix though.
