### ISSUE TITLE
NPE on ListingModelAdapter.java:100 analyzing a DEX

### ISSUE THREAD

**Issue by brainstorm** [NationalSecurityAgency/ghidra#1128]
While analyzing an APK (DEX) I got this:

```
Unexpected exception in Swing Update Manager
java.lang.NullPointerException
	at ghidra.app.util.viewer.listingpanel.ListingModelAdapter.getIndexBefore(ListingModelAdapter.java:100)
	at docking.widgets.fieldpanel.internal.AnchoredLayoutHandler.getPreviousLayout(AnchoredLayoutHandler.java:194)
	at docking.widgets.fieldpanel.internal.AnchoredLayoutHandler.getClosestLayout(AnchoredLayoutHandler.java:222)
	at docking.widgets.fieldpanel.internal.AnchoredLayoutHandler.positionLayoutsAroundAnchor(AnchoredLayoutHandler.java:40)
	at docking.widgets.fieldpanel.FieldPanel.modelSizeChanged(FieldPanel.java:976)
	at ghidra.app.util.viewer.listingpanel.ListingModelAdapter.resetIndexMap(ListingModelAdapter.java:456)
	at ghidra.app.util.viewer.listingpanel.ListingModelAdapter.lambda$new$0(ListingModelAdapter.java:60)
	at ghidra.util.task.SwingUpdateManager.doWork(SwingUpdateManager.java:309)
	at ghidra.util.task.SwingUpdateManager.checkForWork(SwingUpdateManager.java:263)
	at ghidra.util.task.SwingUpdateManager.lambda$new$0(SwingUpdateManager.java:146)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2019-okt.-07 0029 AEDT
Ghidra Version: 9.1
Java Home: /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
JVM Version: Amazon.com Inc. 11.0.3
OS: Mac OS X 10.14.6 x86_64
Workstation: 10.1.1.253
```

Also the following analysis summary window popped up:

![Skärmavbild 2019-10-10 kl  08 39 55](https://user-images.githubusercontent.com/175587/66522643-a119da00-eb39-11e9-9dab-af486b3ffbd0.png)

**Comment by brainstorm** [comment]
More out of bounds with [another, similar, APK](https://www.apkmonk.com/app/com.stationdm.bluelink/), no NPE's this time though:

![Skärmavbild 2019-10-10 kl  10 46 13](https://user-images.githubusercontent.com/175587/66528387-6456de80-eb4b-11e9-86c4-129e277ef546.png)

**Comment by ryanmkurtz** [comment]
Can you provide a sample?

**Comment by brainstorm** [comment]
Sure, @ryanmkurtz, here's a public sample I was looking at:

https://apkpure.com/hyundai-auto-link/com.hyundai.autolink

**Comment by ryanmkurtz** [comment]
I could not reproduce this in Ghidra 12.2-DEV
