### ISSUE TITLE
Analysis Task Exception

### ISSUE THREAD

**Issue by mendax47** [NationalSecurityAgency/ghidra#117]
Analysis Task: Stack - Unique space id must be between 0 and 32767 inclusive
java.lang.IllegalArgumentException: Unique space id must be between 0 and 32767 inclusive
	at ghidra.program.model.address.AbstractAddressSpace.<init>(AbstractAddressSpace.java:69)
	at ghidra.program.model.address.GenericAddressSpace.<init>(GenericAddressSpace.java:80)
	at ghidra.program.model.address.GenericAddressSpace.<init>(GenericAddressSpace.java:38)
	at ghidra.program.util.OffsetAddressFactory.createNewOffsetSpace(VarnodeContext.java:1403)
	at ghidra.program.util.VarnodeContext.getAddressSpace(VarnodeContext.java:1177)
	at ghidra.program.util.VarnodeContext.clearRegister(VarnodeContext.java:1285)
	at ghidra.program.util.VarnodeContext.propogateResults(VarnodeContext.java:730)
	at ghidra.program.util.SymbolicPropogator.applyPcode(SymbolicPropogator.java:1427)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:491)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:389)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:188)
	at ghidra.app.cmd.function.NewFunctionStackAnalysisCmd.createStackPointerVariables(NewFunctionStackAnalysisCmd.java:340)
	at ghidra.app.cmd.function.NewFunctionStackAnalysisCmd.analyzeFunction(NewFunctionStackAnalysisCmd.java:191)
	at ghidra.app.cmd.function.NewFunctionStackAnalysisCmd.applyTo(NewFunctionStackAnalysisCmd.java:118)
	at ghidra.app.plugin.core.function.StackVariableAnalyzer.added(StackVariableAnalyzer.java:54)
	at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:185)
	at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:685)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:785)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:664)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:629)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:62)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:101)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:834)

---------------------------------------------------
Build Date: 2019-Feb-28 1236 EST
Ghidra Version: 9.0
Java Home: C:\Program Files\Java\jdk-11.0.2
JVM Version: Oracle Corporation 11.0.2
OS: Windows 10 10.0 amd64
Workstation: DESKTOP-AJDGC4K

**Comment by ctubbsii** [comment]
Hint: you can format a block of pasted content as a block of text by using three backticks https://help.github.com/en/articles/creating-and-highlighting-code-blocks

This is particularly useful for preformatted pasted content like stack traces.

**Comment by dragonmacher** [comment]
This seems as though you have run into an extremely large function. 

As a workaround, you can disable the **Stack** analyzer from the **Analysis Options Dialog**
