### ISSUE TITLE
GhidraDev "Link Ghidra" fails, Unhandled Event Loop Exception

### ISSUE THREAD

**Issue by philpem** [NationalSecurityAgency/ghidra#1249]
**Describe the bug**
GhidraDev's Link Ghidra option does nothing.

**To Reproduce**
1. Right click Ghidra plugin project
2. Click GhidraDev -> Link Ghidra
3. See error

**Expected behavior**
GhidraDev links to the installed Ghidra instance

**Eclipse error log**

```
Message: Unhandled event loop exception

Stack trace:
java.lang.Error: Unresolved compilation problems: 
	IInterpreterManager cannot be resolved to a type
	InterpreterManagersAPI cannot be resolved
	IInterpreterInfo cannot be resolved to a type
	IPythonNature cannot be resolved to a variable

	at ghidradev.ghidraprojectcreator.utils.PyDevUtilsInternal.getJython27InterpreterNames(PyDevUtilsInternal.java:75)
	at ghidradev.ghidraprojectcreator.utils.PyDevUtils.getJython27InterpreterNames(PyDevUtils.java:64)
	at ghidradev.ghidraprojectcreator.wizards.pages.EnablePythonWizardPage.populateJythonCombo(EnablePythonWizardPage.java:198)
	at ghidradev.ghidraprojectcreator.wizards.pages.EnablePythonWizardPage.createControl(EnablePythonWizardPage.java:94)
	at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:179)
	at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:685)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:577)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1099)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at ghidradev.ghidraprojectcreator.commands.LinkGhidraCommand.execute(LinkGhidraCommand.java:37)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5783)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1411)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5051)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4579)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1449)


Session data:
eclipse.buildId=4.11.0.I20190307-0500
java.version=11.0.4
java.vendor=Ubuntu
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

```

**Comment by ryanmkurtz** [comment]
Can you describe your PyDev setup?  What version are you using?  Did you uninstall it or upgrade it at any time?

**Comment by philpem** [comment]
> Can you describe your PyDev setup? What version are you using? Did you uninstall it or upgrade it at any time?

I didn't have PyDev installed - it's listed as an optional requirement in the GhidraDev instructions.

I've installed version 7.4.0 and still get the same error backtrace.

**Comment by philpem** [comment]
Update: I've just reinstalled the GhidraDev plugin from the 9.1-PUBLIC distribution archive and GhidraDev now runs fine.
