### ISSUE TITLE
PE import error: Specified length extends beyond file bytes length

### ISSUE THREAD

**Issue by ChrisDietrich** [NationalSecurityAgency/ghidra#1266]
[c876a332d7dd8da331cb8eee7ab7bf32752834d4b2b54eaa362674a2a48f64a6.zip](https://github.com/NationalSecurityAgency/ghidra/files/3868334/c876a332d7dd8da331cb8eee7ab7bf32752834d4b2b54eaa362674a2a48f64a6.zip)

**Describe the bug**
Ghidra is unable to import the file with SHA256 hashsum c876a332d7dd8da331cb8eee7ab7bf32752834d4b2b54eaa362674a2a48f64a6, triggering a java.lang.IndexOutOfBoundsException.

**To Reproduce**
1. Drag the sample with SHA256 into a project

**Expected behavior**
Ghidra is expected to import the file and proceed to disassemble.

**Screenshots**
```
Error importing file: Lab01-02.exe
java.lang.IndexOutOfBoundsException: Specified length extends beyond file bytes length
    at ghidra.program.database.mem.MemoryMapDB.checkFileBytesRange(MemoryMapDB.java:583)
    at ghidra.program.database.mem.MemoryMapDB.createInitializedBlock(MemoryMapDB.java:546)
    at ghidra.app.util.MemoryBlockUtils.createInitializedBlock(MemoryBlockUtils.java:225)
    at ghidra.app.util.opinion.PeLoader.processMemoryBlocks(PeLoader.java:622)
    at ghidra.app.util.opinion.PeLoader.load(PeLoader.java:121)
    at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:346)
    at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
    at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
    at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:401)
    at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
    at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
    at ghidra.util.task.Task.monitoredRun(Task.java:126)
    at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)

---------------------------------------------------
Build Date: 2019-Oct-23 1737 EDT
Ghidra Version: 9.1
Java Home: C:\java\jdk-11.0.2
JVM Version: Oracle Corporation 11.0.2
OS: Windows 7 6.1 amd64
```

**Attachments**
File with SHA256 hashsum c876a332d7dd8da331cb8eee7ab7bf32752834d4b2b54eaa362674a2a48f64a6 is attached (password: infected).

**Environment (please complete the following information):**
 - OS: Windows 7 (6.1) amd64
 - Java Version: 11.0.2
 - Ghidra Version: 9.1

**Comment by astrelsky** [comment]
Just a question regarding the password . Is the binary in question actually infected with something?

**Comment by ryanmkurtz** [comment]
Also, can you give some background on the binary?  Is it intentionally malformed?  Is it a crackme?

**Comment by ChrisDietrich** [comment]
The binary is from the labs of the Practical Malware Analysis book by Mike Sikorski and Andrew Honig (Lab01-02.exe). It seems to be an artificial sample (UPX packed) that mimics typical malware installer behavior by added a service and opening a URL (http://www.malwareanalysisbook.com). As far as I can see for now, it does not seem to be infected with further malware, but care should be taken until we can analyze it in Ghidra I guess ;)

It looks a bit odd (the import directory is in the .UPX2) but I haven't analyzed in depth what may cause the loading/parsing issue in Ghidra.

**Comment by ryanmkurtz** [comment]
I see the problem, we'll get a fix in.

It is working in 9.0.4 if you need a solution right now.

**Comment by ChrisDietrich** [comment]
@ryanmkurtz, perfect. Thank you very much!
