### ISSUE TITLE
Auto Create Structure fails with "Database support not provided for HighConstant"

### ISSUE THREAD

**Issue by wrffrz** [NationalSecurityAgency/ghidra#130]
**Describe the bug**
In the Decompile window, there is a context menu option for "Auto Create Structure" when right-clicking on numeric values added to variables, such as the 0x38 part of "pcVar3 = *(char **)(lVar2 + 0x38);"  

However, when this function is used, I always get a java stack backtrace stating "java.lang.UnsupportedOperationException: Database support not provided for HighConstant".

I haven't found any instances where this functionality works without this error.

**To Reproduce**
1. Open any application with the CodeBrowser tool.
2. Find an operation that looks like a structure member dereference in the decompiler.
3. Right-click on the offset from the variable to the member field and select "Auto Create Structure".

Failed to create Structure variable
java.lang.UnsupportedOperationException: Database support not provided for HighConstant
	at ghidra.program.model.pcode.HighFunctionDBUtil.updateDBVariable(HighFunctionDBUtil.java:513)
	at ghidra.app.plugin.core.decompile.actions.FillOutStructureCmd.createStructure(FillOutStructureCmd.java:563)
	at ghidra.app.plugin.core.decompile.actions.FillOutStructureCmd.applyTo(FillOutStructureCmd.java:142)
	at ghidra.framework.cmd.BackgroundCommand.applyTo(BackgroundCommand.java:59)
	at ghidra.app.plugin.core.decompile.actions.CreateStructureVariableAction.actionPerformed(CreateStructureVariableAction.java:122)
	at docking.PopupMenuHandler$1.run(PopupMenuHandler.java:62)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Expected behavior**
Expected to have a new structure added to the Data Types library for this project based on the variable references found in this function.

**Environment (please complete the following information):**
Build Date: 2019-Feb-28 1236 EST
Ghidra Version: 9.0
Java Home: C:\Program Files\Oracle\OpenJDK\jdk-11.0.2
JVM Version: Oracle Corporation 11.0.2
OS: Windows 7 6.1 amd64

**Comment by caheckman** [comment]
Thanks for reporting this. "Auto Create Structure" is designed to work from variable tokens, not constant tokens, in the decompiler window. You should get the expected behavior by right-clicking on 'lVar2' rather than '0x38' in your example. I'm putting in a patch to remove the menu action from constant tokens.
