### ISSUE TITLE
COFF loader breaking for i960

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#1336]
Working on an i960 processor (https://github.com/mumbel/ghidra_i960) and trying to get SleighDevTools going, but ran into an issue with the COFF loader when I built the pcode test.  This is happening  before my relocate() gets called, but canRelocate() does get called and returns true (that code is only stubs w/ prints, no relocations implemented yet).  It has loaded COFF, so maybe its a bad prebuilt gcc I'm using or maybe this binary has a section/type other than the file I tested with (vmlinux).

I've yet to dive into the Java, but just reporting since its independent of my code looks like.  Any thoughts? 

```
DEBUG Exception appended to MessageLog java.lang.IndexOutOfBoundsException: Offset must be in range [0,335346], got 1920234338
	at ghidra.program.database.mem.MemoryMapDB.checkFileBytesRange(MemoryMapDB.java:564)
	at ghidra.program.database.mem.MemoryMapDB.createInitializedBlock(MemoryMapDB.java:531)
	at ghidra.app.util.MemoryBlockUtils.createInitializedBlock(MemoryBlockUtils.java:224)
	at ghidra.app.util.opinion.CoffLoader.createInitializedBlock(CoffLoader.java:537)
	at ghidra.app.util.opinion.CoffLoader.processSectionHeaders(CoffLoader.java:481)
	at ghidra.app.util.opinion.CoffLoader.load(CoffLoader.java:201)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:346)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:401)
	at ghidra.plugin.importer.ImporterDialog.lambda$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
  (MessageLog.java:102) 
DEBUG:  canRelocate() i960:  352 == 352 or 353?
ERROR Error Importing File: Error importing file: i960_GCC_O3_pcodetest.out ghidra.program.model.address.AddressOutOfBoundsException: Address Overflow in subtract: 00000010 - 0x5f150000
	at ghidra.program.model.address.AbstractAddressSpace.add(AbstractAddressSpace.java:434)
	at ghidra.program.model.address.GenericAddressSpace.add(GenericAddressSpace.java:1)
	at ghidra.program.model.address.GenericAddress.add(GenericAddress.java:237)
	at ghidra.app.util.opinion.CoffLoader.processRelocations(CoffLoader.java:666)
	at ghidra.app.util.opinion.CoffLoader.load(CoffLoader.java:205)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:346)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:401)
	at ghidra.plugin.importer.ImporterDialog.lambda$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
  (ImporterUtilities.java:414) 
```

**Comment by ryanmkurtz** [comment]
Can you provide your binary?

**Comment by mumbel** [comment]
[i960_GCC_O3_pcodetest.txt](https://github.com/NationalSecurityAgency/ghidra/files/3958482/i960_GCC_O3_pcodetest.txt)

Shoulda checked email before going into work.  txt is an out due to github limitations

**Comment by ryanmkurtz** [comment]
Does this processor have just 1 address space?

**Comment by ryanmkurtz** [comment]
The first thing I see is that we aren't parsing the section headers correctly.  We have a couple of different  `CoffSectionHeader` variations, but this binary has section headers of size `0x2c`, which we don't have an implementation for.  Have you come across an COFF specification documents for this processor?

**Comment by ryanmkurtz** [comment]
I found a [header file](https://chromium.googlesource.com/chromiumos/third_party/binutils/+/refs/heads/release-R47-7520.B/include/coff/i960.h) that will help.  I'll implement this, but I expect other errors to pop up too.

**Comment by mumbel** [comment]
Thanks for looking/helping.  Is that that code be abstracted out to my coff code by implementing some other class or it needs to be in ghidra? (I'd guess that's significant api/class changes if the latter to instead be the former).

There might be a second space, a private 1k RAM @ 0x0  Have not touched it yet.

**Comment by ryanmkurtz** [comment]
Unfortunately right now we'd have to add it to core Ghidra here:

https://github.com/NationalSecurityAgency/ghidra/blob/3eb130123bfec55ed2aef82d2bfeb985cd8121f6/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/coff/CoffSectionHeaderFactory.java#L22-L34

Ideally the COFF section header classes would be extension points so if someone is writing a new processor in a standalone extension, they could provide their own implementation that would get discovered at runtime.

For now I'll just add in another version for your case to get you going.

**Comment by mumbel** [comment]
Definitely gets further, and points out the places that are different, thanks again for taking a look.

Yeah, that gets gross quickly.  The CoffSymbol and the CoffSymbolAux* parsing changes as well (additional/changed fields and more padding)... notably:

external.h
```
#define	SYMENT	struct external_syment
#define	SYMESZ	18
#define	AUXENT	union external_auxent
#define	AUXESZ	18
```
i960.h
```
#define	SYMENT	struct external_syment
#define	SYMESZ	24
#define	AUXENT	union external_auxent
#define	AUXESZ	24
```

I think for now my best action would be to see if I can get my build chain to output ELF instead.
