### ISSUE TITLE
PE import error, Vol 2: Specified length extends beyond file bytes length

### ISSUE THREAD

**Issue by NexusMaximus** [NationalSecurityAgency/ghidra#1371]
**Describe the bug**
Ghidra is unable to import the file Lab05-01.dll, md5 hash 1A9FD80174AAFECD9A52FD908CB82637, from the practical malware analysis textbook malware suite.

**To Reproduce**
1. File->import
2. direct import window path to Lab05-01.dll wherever it is; import it
3. encounter error; be sad

**Expected behavior**
Ghidra is expected to import the file and proceed to disassemble it.

**Screenshots/attachments**

Error output:
```
Error importing file: Lab05-01.dll
java.lang.IndexOutOfBoundsException: Specified length extends beyond file bytes length
	at ghidra.program.database.mem.MemoryMapDB.checkFileBytesRange(MemoryMapDB.java:589)
	at ghidra.program.database.mem.MemoryMapDB.createInitializedBlock(MemoryMapDB.java:552)
	at ghidra.app.util.MemoryBlockUtils.createInitializedBlock(MemoryBlockUtils.java:225)
	at ghidra.app.util.opinion.PeLoader.processMemoryBlocks(PeLoader.java:657)
	at ghidra.app.util.opinion.PeLoader.load(PeLoader.java:121)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:346)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:401)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

---------------------------------------------------
Build Date: 2019-Dec-18 1306 EST
Ghidra Version: 9.1.1
Java Home: C:\Program Files\Java\jdk-13.0.1
JVM Version: Oracle Corporation 13.0.1
OS: Windows 7 6.1 amd64
```

**Environment (please complete the following information):**
 - OS: Windows 7 6.1 amd64
 - Java Version: Oracle Corporation 13.0.1
 - Ghidra Version: 9.1.1

**Additional context**
To the best of my knowledge, the file isn't a crackme or otherwise obfuscated. The original goal of this lab is to use Ida to be able to answer simple questions about a DLL, which further makes me believe this particular file isn't supposed to be obfuscated or otherwise infected with something. My purposes were to rework the lab using Ghidra to try to learn how to use it instead.

See issue 1266 for what looks like basically the exact same error but with an .exe: https://github.com/NationalSecurityAgency/ghidra/issues/1266

Labs are available for download here: https://practicalmalwareanalysis.com/labs/

EDIT: Interestingly, like in the linked issue, 9.0.4 does not suffer from this import issue either. 9.1 and 9.1.1 both do.

**Comment by NexusMaximus** [comment]
@ryanmkurtz Deja vu? ;)

**Comment by ryanmkurtz** [comment]
Can you please copy/paste in a hexdump of the PE headers (you can stop after the section headers).  Can you also provide the file size?  Thanks!

**Comment by NexusMaximus** [comment]
Sure thing!

The .text section begins at 0x400. I believe the section headers stop after 0x2FF, but the data included between 0x300 and 0x3FF are all unaccounted for (as far as I understand) and nulled out. I included it just in case, so here's everything up to that point. I used HxD to grab this raw data;

```
4D 5A 90 00 03 00 00 00 04 00 00 00 FF FF 00 00 B8 00 00 00 00 00 00 00 40 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 10 01 00 00 0E 1F BA 0E 00 B4 09 CD 21 B8 01 4C CD 21 54 68 69 73 20 70 72 6F 67 72 61 6D 20 63 61 6E 6E 6F 74 20 62 65 20 72 75 6E 20 69 6E 20 44 4F 53 20 6D 6F 64 65 2E 0D 0D 0A 24 00 00 00 00 00 00 00 A9 2E 9A 31 ED 4F F4 62 ED 4F F4 62 ED 4F F4 62 96 53 F8 62 E9 4F F4 62 6E 53 FA 62 E9 4F F4 62 82 50 FF 62 EC 4F F4 62 82 50 FE 62 E9 4F F4 62 82 50 F0 62 EF 4F F4 62 05 50 FE 62 F4 4F F4 62 37 6C E8 62 EC 4F F4 62 B3 6D FF 62 EE 4F F4 62 ED 4F F5 62 FE 4E F4 62 6E 47 A9 62 F4 4F F4 62 63 47 AB 62 EF 4F F4 62 05 50 FF 62 EC 4F F4 62 2A 49 F2 62 EC 4F F4 62 05 50 F0 62 EC 4F F4 62 52 69 63 68 ED 4F F4 62 00 00 00 00 00 00 00 00 50 45 00 00 4C 01 06 00 D9 26 4D 48 00 00 00 00 00 00 00 00 E0 00 0E 21 0B 01 06 00 00 44 01 00 00 1A 08 00 00 00 00 00 6D 51 01 00 00 10 00 00 00 60 01 00 00 00 00 10 00 10 00 00 00 02 00 00 04 00 00 00 00 00 00 00 04 00 00 00 00 00 00 00 A8 94 09 00 00 04 00 00 00 00 00 00 02 00 00 00 00 00 10 00 00 10 00 00 00 00 10 00 00 10 00 00 00 00 00 00 10 00 00 00 50 7F 01 00 E9 00 00 00 58 6A 01 00 04 01 00 00 00 60 09 00 B0 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 70 09 00 50 18 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 60 01 00 24 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2E 74 65 78 74 00 00 00 06 43 01 00 00 10 00 00 00 44 01 00 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 20 00 00 60 2E 72 64 61 74 61 00 00 39 20 00 00 00 60 01 00 00 22 00 00 00 48 01 00 00 00 00 00 00 00 00 00 00 00 00 00 40 00 00 40 2E 64 61 74 61 00 00 00 64 9E 07 00 00 90 01 00 00 4A 00 00 00 6A 01 00 00 00 00 00 00 00 00 00 00 00 00 00 40 00 00 C0 78 64 6F 6F 72 73 5F 64 5E 2C 00 00 00 30 09 00 00 2E 00 00 00 B4 01 00 00 00 00 00 00 00 00 00 00 00 00 00 40 00 00 D0 2E 72 73 72 63 00 00 00 B0 03 00 00 00 60 09 00 00 04 00 00 00 E2 01 00 00 00 00 00 00 00 00 00 00 00 00 00 40 00 00 40 2E 72 65 6C 6F 63 00 00 A8 24 00 00 00 70 09 00 00 26 00 00 00 E6 01 00 00 00 00 00 00 00 00 00 00 00 00 00 40 00 00 42 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```
if you're looking for the linux command hexdump data, the terminal output of that (up to 0x400) is right here:

```
00000000  4d 5a 90 00 03 00 00 00  04 00 00 00 ff ff 00 00  |MZ..............|
00000010  b8 00 00 00 00 00 00 00  40 00 00 00 00 00 00 00  |........@.......|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 10 01 00 00  |................|
00000040  0e 1f ba 0e 00 b4 09 cd  21 b8 01 4c cd 21 54 68  |........!..L.!Th|
00000050  69 73 20 70 72 6f 67 72  61 6d 20 63 61 6e 6e 6f  |is program canno|
00000060  74 20 62 65 20 72 75 6e  20 69 6e 20 44 4f 53 20  |t be run in DOS |
00000070  6d 6f 64 65 2e 0d 0d 0a  24 00 00 00 00 00 00 00  |mode....$.......|
00000080  a9 2e 9a 31 ed 4f f4 62  ed 4f f4 62 ed 4f f4 62  |...1.O.b.O.b.O.b|
00000090  96 53 f8 62 e9 4f f4 62  6e 53 fa 62 e9 4f f4 62  |.S.b.O.bnS.b.O.b|
000000a0  82 50 ff 62 ec 4f f4 62  82 50 fe 62 e9 4f f4 62  |.P.b.O.b.P.b.O.b|
000000b0  82 50 f0 62 ef 4f f4 62  05 50 fe 62 f4 4f f4 62  |.P.b.O.b.P.b.O.b|
000000c0  37 6c e8 62 ec 4f f4 62  b3 6d ff 62 ee 4f f4 62  |7l.b.O.b.m.b.O.b|
000000d0  ed 4f f5 62 fe 4e f4 62  6e 47 a9 62 f4 4f f4 62  |.O.b.N.bnG.b.O.b|
000000e0  63 47 ab 62 ef 4f f4 62  05 50 ff 62 ec 4f f4 62  |cG.b.O.b.P.b.O.b|
000000f0  2a 49 f2 62 ec 4f f4 62  05 50 f0 62 ec 4f f4 62  |*I.b.O.b.P.b.O.b|
00000100  52 69 63 68 ed 4f f4 62  00 00 00 00 00 00 00 00  |Rich.O.b........|
00000110  50 45 00 00 4c 01 06 00  d9 26 4d 48 00 00 00 00  |PE..L....&MH....|
00000120  00 00 00 00 e0 00 0e 21  0b 01 06 00 00 44 01 00  |.......!.....D..|
00000130  00 1a 08 00 00 00 00 00  6d 51 01 00 00 10 00 00  |........mQ......|
00000140  00 60 01 00 00 00 00 10  00 10 00 00 00 02 00 00  |.`..............|
00000150  04 00 00 00 00 00 00 00  04 00 00 00 00 00 00 00  |................|
00000160  a8 94 09 00 00 04 00 00  00 00 00 00 02 00 00 00  |................|
00000170  00 00 10 00 00 10 00 00  00 00 10 00 00 10 00 00  |................|
00000180  00 00 00 00 10 00 00 00  50 7f 01 00 e9 00 00 00  |........P.......|
00000190  58 6a 01 00 04 01 00 00  00 60 09 00 b0 03 00 00  |Xj.......`......|
000001a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000001b0  00 70 09 00 50 18 00 00  00 00 00 00 00 00 00 00  |.p..P...........|
000001c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000001e0  00 00 00 00 00 00 00 00  00 60 01 00 24 04 00 00  |.........`..$...|
000001f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000200  00 00 00 00 00 00 00 00  2e 74 65 78 74 00 00 00  |.........text...|
00000210  06 43 01 00 00 10 00 00  00 44 01 00 00 04 00 00  |.C.......D......|
00000220  00 00 00 00 00 00 00 00  00 00 00 00 20 00 00 60  |............ ..`|
00000230  2e 72 64 61 74 61 00 00  39 20 00 00 00 60 01 00  |.rdata..9 ...`..|
00000240  00 22 00 00 00 48 01 00  00 00 00 00 00 00 00 00  |."...H..........|
00000250  00 00 00 00 40 00 00 40  2e 64 61 74 61 00 00 00  |....@..@.data...|
00000260  64 9e 07 00 00 90 01 00  00 4a 00 00 00 6a 01 00  |d........J...j..|
00000270  00 00 00 00 00 00 00 00  00 00 00 00 40 00 00 c0  |............@...|
00000280  78 64 6f 6f 72 73 5f 64  5e 2c 00 00 00 30 09 00  |xdoors_d^,...0..|
00000290  00 2e 00 00 00 b4 01 00  00 00 00 00 00 00 00 00  |................|
000002a0  00 00 00 00 40 00 00 d0  2e 72 73 72 63 00 00 00  |....@....rsrc...|
000002b0  b0 03 00 00 00 60 09 00  00 04 00 00 00 e2 01 00  |.....`..........|
000002c0  00 00 00 00 00 00 00 00  00 00 00 00 40 00 00 40  |............@..@|
000002d0  2e 72 65 6c 6f 63 00 00  a8 24 00 00 00 70 09 00  |.reloc...$...p..|
000002e0  00 26 00 00 00 e6 01 00  00 00 00 00 00 00 00 00  |.&..............|
000002f0  00 00 00 00 40 00 00 42  00 00 00 00 00 00 00 00  |....@..B........|
00000300  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
```

Here's a snip of the metadata courtesy of CFFExplorer, which includes the file size (134085 bytes), the PE size (134144 bytes) and some other information.

![image](https://user-images.githubusercontent.com/41649224/71382583-d6a95d80-2595-11ea-9d63-c0f0dc498081.png)

Thanks for looking into this!

**Comment by ryanmkurtz** [comment]
Thanks for the detailed info...I'm looking into it now.

**Comment by ryanmkurtz** [comment]
The .reloc section's PointerToRawData + SizeOfRawData extends past the end of the file, which we aren't handling.  I guess we haven't seen a PE that does this before.  It will be an easy fix.

**Comment by NexusMaximus** [comment]
Thanks for looking into that, Ryan! I appreciate it.

**Comment by Allevon412** [comment]
@ryanmkurtz I have having this same issue. Doing malware analysis, I have dumped a stage 2 loader that is packed. Since I am dynamically unpacking it I don't know the exact byte at which the PE file ends at. Ghidra does not handle this error gracefully and will not let me import the file.

**Comment by ryanmkurtz** [comment]
This case is a little differently...the PeLoader expects you to import a PE that is runnable by the OS.

**Comment by Allevon412** [comment]
The executable is runnable by the OS. I was able to solve the issue by opening up the executable in PE bear and changing some values a bit. If I run into any issues I'll open a new ticket.

**Comment by ryanmkurtz** [comment]
Ok, i was picturing you dumping unpacked memory to a file and it possibly not being a valid PE that could launch from disk without additional fixups.  Yes, a new ticket if you run into issues sounds good (ideally with the sample attached).
