### ISSUE TITLE
How to force endianness on sleigh table parameters?

### ISSUE THREAD

**Issue by agatti** [NationalSecurityAgency/ghidra#1422]
I've got an architecture I'm writing the Sleigh description for, which still encodes opcodes in big-endian format regardless of the effective target endianness (it can also change its endianness at runtime but that's another matter).  One way I could get instruction decoding to work was to set the processor as big endian so pattern matching would work, but then values would be decoded improperly.

Is there a way to get this to work without implementing changes to Sleigh or should this be thought as a possible extension to the #1409 PR?

**Comment by GhidorahRex** [comment]
Are you saying that the instructions are decoded as big-endian but the memory is still interpreted as little-endian? If so, you can set the "instructionEndian" parameter to be "big" and the "endian" parameter to be "little" and it should work correctly. See the ARM.ldefs file for examples.

**Comment by agatti** [comment]
Thanks!  How about adding the `instructionEndian` attribute in the processor module templates too to give it a bit more visibility?  I can submit a PR if needed.

**Comment by agatti** [comment]
Spoke too soon actually.  If I have `endian` set as `little` in .ldefs, `define endian=little` in .slaspec, and `instructionEndian` set as `big` in .ldefs I get an error:

```
ghidra.app.plugin.processors.sleigh.SleighException: .ldefs says AndesCoreV3:LE:32:default is big but .sla says false
	at ghidra.app.plugin.processors.sleigh.SleighLanguage.restoreXml(SleighLanguage.java:855)
	at ghidra.app.plugin.processors.sleigh.SleighLanguage.readSpecification(SleighLanguage.java:842)
	at ghidra.app.plugin.processors.sleigh.SleighLanguage.initialize(SleighLanguage.java:133)
	at ghidra.app.plugin.processors.sleigh.SleighLanguage.<init>(SleighLanguage.java:101)
	at ghidra.app.plugin.processors.sleigh.SleighLanguageProvider.getNewSleigh(SleighLanguageProvider.java:112)
	at ghidra.app.plugin.processors.sleigh.SleighLanguageProvider.getLanguage(SleighLanguageProvider.java:99)
	at ghidra.program.util.DefaultLanguageService$LanguageInfo.lambda$0(DefaultLanguageService.java:385)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:303)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

however if I set `instructionEnding` as `little` and `ending` as `big` in the .ldefs and leaving `define endian=little` in .slaspec it wouldn't trigger said error (which is how it's used in ARM.ldefs).

**Comment by GhidorahRex** [comment]
If you would like to submit a PR for adding the `instructionEndian` attribute to the templates, you are more than welcome to.

In regards to the error, yes, it has to match that ordering unfortunately.

**Comment by agatti** [comment]
Fair enough - is there any other way to achieve the intended result then or is this an intrinsic limitation of Ghidra at this point in time?

**Comment by GhidorahRex** [comment]
This is a limitation on sleigh at this point. Particularly for languages that can swap endianness.

**Comment by agatti** [comment]
Can we turn this into a bug report for the limitation mentioned above or is it better if I create a new bug report to track the issue?
