### ISSUE TITLE
Preventing test timeout while debugging

### ISSUE THREAD

**Issue by astrelsky** [NationalSecurityAgency/ghidra#1424]
I'm currently writing and debugging tests for a StabsParser. However, while I'm debugging the tests it appears to be timing out and I have to restart. I'm extending AbstractGhidraHeadlessIntegrationTest. I'm not even sure if this is something in ghidras test classes or if it is my debugger setup, but how may I go about preventing this?

Below is the console log.
<details>
<summary>log</summary>

```
Java HotSpot(TM) 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "ghidra.GhidraClassLoader"). To use archived non-system classes, this property must not be set
INFO  Using log config file: jar:file:/C:/Users/astre/Documents/ghidra_9.2_DEV/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)
INFO  Using log file: C:\Users\astre\AppData\Local\Temp\DocumentsTemp\application.log (LoggingInitialization)
INFO  Loading user preferences: C:\Users\astre\AppData\Local\Temp\DocumentsTemp\preferences (Preferences)
INFO  Class search complete (2080 ms) (ClassSearcher)
INFO  Initializing SSL Context (SSLContextInitializer)
INFO  Initializing Random Number Generator... (SecureRandomFactory)
INFO  Random Number Generator initialization complete: SHA1PRNG (SecureRandomFactory)
INFO  Trust manager disabled, cacerts have not been set (ApplicationTrustManagerFactory)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sf.cglib.core.ReflectUtils$2 (file:/C:/Users/astre/Documents/ghidra_9.2_DEV/Ghidra/Framework/Generic/lib/cglib-nodep-2.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of net.sf.cglib.core.ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
ERROR

Threads at time of interrupt:
Thread: Test-Thread-1
	at app//ghidra.app.util.bin.format.stabs.types.StabCompositeTypeDescriptor.tokenize(StabCompositeTypeDescriptor.java:137)
	at app//ghidra.app.util.bin.format.stabs.types.StabCompositeTypeDescriptor.parseComposite(Unknown Source)
	at app//ghidra.app.util.bin.format.stabs.types.StabCompositeTypeDescriptor.parseToken(Unknown Source)
	at app//ghidra.app.util.bin.format.stabs.types.StabCompositeTypeDescriptor.<init>(Unknown Source)
	at app//ghidra.app.util.bin.format.stabs.types.StabTypeDescriptorFactory.getTypeDescriptor(StabTypeDescriptorFactory.java:59)
	at app//ghidra.app.util.bin.format.stabs.AbstractStabToken.doGetTypeInformation(AbstractStabToken.java:56)
	at app//ghidra.app.util.bin.format.stabs.AbstractStabToken.<init>(AbstractStabToken.java:39)
	at app//ghidra.app.util.bin.format.stabs.StabVariableToken.<init>(StabVariableToken.java:10)
	at app//ghidra.app.util.bin.format.stabs.StabCompositeToken.getCompositeTokens(StabCompositeToken.java:92)
	at app//ghidra.app.util.bin.format.stabs.types.StabCompositeTypeDescriptor.parseComposite(Unknown Source)
	at app//ghidra.app.util.bin.format.stabs.types.StabCompositeTypeDescriptor.parseToken(Unknown Source)
	at app//ghidra.app.util.bin.format.stabs.types.StabCompositeTypeDescriptor.<init>(Unknown Source)
	at app//ghidra.app.util.bin.format.stabs.types.StabTypeDescriptorFactory.getTypeDescriptor(StabTypeDescriptorFactory.java:59)
	at app//ghidra.app.util.bin.format.stabs.types.StabTypeReferenceTypeDescriptor.doGetSubType(StabTypeReferenceTypeDescriptor.java:28)
	at app//ghidra.app.util.bin.format.stabs.types.StabTypeReferenceTypeDescriptor.<init>(StabTypeReferenceTypeDescriptor.java:18)
	at app//ghidra.app.util.bin.format.stabs.types.StabTypeDescriptorFactory.getTypeDescriptor(StabTypeDescriptorFactory.java:32)
	at app//ghidra.app.util.bin.format.stabs.AbstractStabToken.doGetTypeInformation(AbstractStabToken.java:56)
	at app//ghidra.app.util.bin.format.stabs.AbstractStabToken.<init>(AbstractStabToken.java:39)
	at app//ghidra.app.util.bin.format.stabs.StabTypeDefToken.<init>(StabTypeDefToken.java:15)
	at app//ghidra.app.util.bin.format.stabs.StabsParser.parse(StabsParser.java:122)
	at app//ghidra.app.util.bin.format.stabs.StabsParser.parse(StabsParser.java:74)
	at app//ghidra.app.util.bin.format.stabs.AbstractStabsTest.setup(AbstractStabsTest.java:53)
	at java.base@13.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@13.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@13.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@13.0.1/java.lang.reflect.Method.invoke(Method.java:567)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//generic.test.TestThread.run(TestThread.java:106)
Thread: Log4j2-TF-3-Scheduled-1
	at java.base@13.0.1/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@13.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:235)
	at java.base@13.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
	at java.base@13.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
	at java.base@13.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
	at java.base@13.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
	at java.base@13.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
	at java.base@13.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base@13.0.1/java.lang.Thread.run(Thread.java:830)
Thread: Reference Handler
	at java.base@13.0.1/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
	at java.base@13.0.1/java.lang.ref.Reference.processPendingReferences(Reference.java:241)
	at java.base@13.0.1/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:213)
Thread: Finalizer
	at java.base@13.0.1/java.lang.Object.wait(Native Method)
	at java.base@13.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at java.base@13.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
	at java.base@13.0.1/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:170)
Thread: ReaderThread
	at java.base@13.0.1/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base@13.0.1/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:46)
	at java.base@13.0.1/sun.nio.ch.NioSocketImpl.tryRead(NioSocketImpl.java:262)
	at java.base@13.0.1/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:313)
	at java.base@13.0.1/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:351)
	at java.base@13.0.1/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:802)
	at java.base@13.0.1/java.net.Socket$SocketInputStream.read(Socket.java:937)
	at java.base@13.0.1/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:297)
	at java.base@13.0.1/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at java.base@13.0.1/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
	at java.base@13.0.1/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base@13.0.1/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base@13.0.1/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base@13.0.1/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at app//org.eclipse.jdt.internal.junit.runner.RemoteTestRunner$ReaderThread.run(RemoteTestRunner.java:152)
Thread: Signal Dispatcher
Thread: Attach Listener
Thread: main
	at java.base@13.0.1/java.lang.Thread.dumpThreads(Native Method)
	at java.base@13.0.1/java.lang.Thread.getAllStackTraces(Thread.java:1649)
	at app//utilities.util.reflection.ReflectionUtilities.createStackTraceForAllThreads(ReflectionUtilities.java:404)
	at app//generic.test.TestUtils.createStackTraceForAllThreads(TestUtils.java:47)
	at app//generic.test.AbstractGenericTest.createStackTraceForAllThreads(AbstractGenericTest.java:1450)
	at app//generic.test.ConcurrentTestExceptionStatement.checkForTestTimeout(ConcurrentTestExceptionStatement.java:166)
	at app//generic.test.ConcurrentTestExceptionStatement.waitForTestUnlessExceptions(ConcurrentTestExceptionStatement.java:137)
	at app//generic.test.ConcurrentTestExceptionStatement.evaluate(ConcurrentTestExceptionStatement.java:68)
	at app//org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at app//org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at app//org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at app//org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at app//org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at app//org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at app//org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at app//org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at app//org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at app//org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at app//org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Thread: Common-Cleaner
	at java.base@13.0.1/java.lang.Object.wait(Native Method)
	at java.base@13.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at java.base@13.0.1/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
	at java.base@13.0.1/java.lang.Thread.run(Thread.java:830)
	at java.base@13.0.1/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)
Thread: GTimer
	at java.base@13.0.1/java.lang.Object.wait(Native Method)
	at java.base@13.0.1/java.lang.Object.wait(Object.java:326)
	at java.base@13.0.1/java.util.TimerThread.mainLoop(Timer.java:527)
	at java.base@13.0.1/java.util.TimerThread.run(Timer.java:506)
 (ConcurrentTestExceptionStatement)
```
</details>

**Comment by dragonmacher** [comment]
The code responsible for the timeout is in `ConcurrentTestExceptionStatement`.   If you are running from within Eclipse, then the code should not be using the timeout at all.   If you are debugging externally, the you are currently restricted to a 10 minute timeout.

There is no current way of changing this timeout value (e.g., like from a system property).   We could certainly add a way of changing or disabling this feature.  What is your setup?

**Comment by astrelsky** [comment]
> The code responsible for the timeout is in `ConcurrentTestExceptionStatement`. If you are running from within Eclipse, then the code should not be using the timeout at all. If you are debugging externally, the you are currently restricted to a 10 minute timeout.
> 
> There is no current way of changing this timeout value (e.g., like from a system property). We could certainly add a way of changing or disabling this feature. What is your setup?

I see. I'm using vscode. Is ghidra telling Eclipse to disable the timeout or does Eclipse do it automatically? If it's the latter then I'll report this to [vscode-java-test](https://github.com/Microsoft/vscode-java-test)

If it's an eclipse setting then it may be available for me to change since vscode-java is using eclipse jdt.ls.

**Comment by dragonmacher** [comment]
It is a bit hacky, but here is a peek behind the curtain:

```
	public ConcurrentTestExceptionStatement(Statement originalStatement) {
		testStatement = originalStatement;
		ConcurrentTestExceptionHandler.clear();

		// enable timeout monitor except when running from eclipse to permit extended debugging
		timoutMonitor =
			isRunningFromEclipse() ? null : GTimer.scheduleRunnable(TIMEOUT_MILLIS, () -> {
				// no-op; we will use the monitor directly
			});
	}

	private static boolean isRunningFromEclipse() {
		// TODO: this may need adjustment for other Eclipse platforms/versions
		return System.getProperty("java.class.path").endsWith(".cp");
	}
```

It seems like you have run into the 'TODO' statement.   We could always add support for a system property and then change the name of that method.

**Comment by astrelsky** [comment]
> It is a bit hacky, but here is a peek behind the curtain:
> 
> ```
> 	public ConcurrentTestExceptionStatement(Statement originalStatement) {
> 		testStatement = originalStatement;
> 		ConcurrentTestExceptionHandler.clear();
> 
> 		// enable timeout monitor except when running from eclipse to permit extended debugging
> 		timoutMonitor =
> 			isRunningFromEclipse() ? null : GTimer.scheduleRunnable(TIMEOUT_MILLIS, () -> {
> 				// no-op; we will use the monitor directly
> 			});
> 	}
> 
> 	private static boolean isRunningFromEclipse() {
> 		// TODO: this may need adjustment for other Eclipse platforms/versions
> 		return System.getProperty("java.class.path").endsWith(".cp");
> 	}
> ```
> 
> It seems like you have run into the 'TODO' statement. We could always add support for a system property and then change the name of that method.

Ah. I set a breakpoint in `isRunningFromEclipse` to check the classpath. These are the last few items after the ghidra jars
```
C:\Users\astre\.vscode-insiders\extensions\redhat.java-0.55.1\server\config_win\org.eclipse.osgi\346\0\.cp;C:\Users\astre\.vscode-insiders\extensions\redhat.java-0.55.1\server\config_win\org.eclipse.osgi\45\0\.cp;C:\Users\astre\AppData\Local\Temp\DocumentsTemp\plugins"
```

I'm not sure if it would be sufficient to check each classpath entry individually and return true on `endsWith(".cp")`, or maybe or it with `System.getProperty("java.class.path").contains(".cp;")`. I'm not sure what the entries look like when coming from Eclipse though.

**Comment by dragonmacher** [comment]
If it would be sufficient for your needs, I think adding a system property is the way to go.   You would then have to set the system property inside of your test harness.   Would this work for you?

**Comment by astrelsky** [comment]
> If it would be sufficient for your needs, I think adding a system property is the way to go. You would then have to set the system property inside of your test harness. Would this work for you?

It would and is likely best. I'll modify it locally to work for my needs in the meantime. Thank you!
