### ISSUE TITLE
RepositoryServerHandle.isReadOnly() throws java.io.IOException

### ISSUE THREAD

**Issue by xorhex** [NationalSecurityAgency/ghidra#1440]
Stood up ghidra as a server and set up PKI auth.  Looks like I'm able to authenticate but then this error occurs before the login process finishes.  I'm guessing the issue is file/folder permissions.  The user that is running the ghidra server is the owner of both the ghidra home and the ghidra project repository folders so I'm kind of at a lost.

```
An error occured on the server (<redacted>:13100).
Method is not Remote: interface ghidra.framework.remote.RepositoryServerHandle::public abstract boolean ghidra.framework.remote.RepositoryServerHandle.isReadOnly() throws java.io.IOException
java.rmi.RemoteException: Method is not Remote: interface ghidra.framework.remote.RepositoryServerHandle::public abstract boolean ghidra.framework.remote.RepositoryServerHandle.isReadOnly() throws java.io.IOException
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:214)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:162)
	at com.sun.proxy.$Proxy22.isReadOnly(Unknown Source)
	at ghidra.framework.client.ServerConnectTask.getRepositoryServerHandle(ServerConnectTask.java:290)
	at ghidra.framework.client.ServerConnectTask.run(ServerConnectTask.java:72)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

---------------------------------------------------
Build Date: 2019-Dec-18 1306 EST
Ghidra Version: 9.1.1
Java Home: /Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home
JVM Version: Oracle Corporation 13.0.2
OS: Mac OS X <redacted>
Workstation: <redacted>
```

**Comment by xorhex** [comment]
Steps to reproduce (not using PKI):

1. Download zip from https://ghidra-sre.org/
2. Extract
3. Modify server.conf with the following options

```
wrapper.app.parameter.1=-i 192.168.56.101
wrapper.app.parameter.2=-a0
wrapper.app.parameter.3=-u
wrapper.app.parameter.4=-autoProvision
wrapper.app.parameter.5=${ghidra.repositories.dir}

```

4. Started up the server
5. In another console window ran `./svrAdmin -add test`
6. Then tried to login.  Received the same error message.

The server instance is running on ubuntu installed on a VM and the client instance is on the local machine.

**Comment by jmamma** [comment]
Having the same issue.

I can connect from macos. but my win10 install is not working.

**Comment by jmamma** [comment]
I installed ghidra using window's chocolatey package manager and the problem is resolved.

These are the files it downloaded:

https://ghidra-sre.org/ghidra_9.1.1_PUBLIC_20191218.zip

And 

https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.5%2B10/OpenJDK11U-jdk_x64_windows_11.0.5_10.zip

--

My mac version is 2019-oct-23 1737 release with the built in 12.0.1 jdk. and works fine.

**Comment by dev747368** [comment]
@xorhex - could you also paste what the server is logging?  I suggest running the server as "./ghidraSvr console".  Are you getting prompted for login credentials on the client?  Can you describe with a little more detail the steps you are following?
Are you sure you don't have something else sharing the same ports?

**Comment by xorhex** [comment]
@jmamma, changing my OpenJDK install from 13.0.2 to 12.0.1 on the client (Mac) machine did the trick for both -a0 and -a2.  Thank you for the tip!

@dev747368 when putting OpenJDK 13.0.2 back on the client, this is the log from the server when using -a2.  
```
Using service wrapper: yajsw-stable-12.12
Running Ghidra Server...
YAJSW: yajsw-stable-12.12
OS   : Linux/5.3.0-26-generic/amd64
JVM  : Private Build/11.0.5//usr/lib/jvm/java-11-openjdk-amd64/64
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Features/GhidraServer/data/yajsw-stable-12.12/./lib/extended/groovy/groovy-all-2.4.11.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Jan 21, 2020 11:52:18 AM org.apache.commons.vfs2.VfsLog info
INFO: Using "/tmp/vfs_cache" as temporary files store.
wrapper|YAJSW: yajsw-stable-12.12
wrapper|OS   : Linux/5.3.0-26-generic/amd64
wrapper|JVM  : Private Build/11.0.5//usr/lib/jvm/java-11-openjdk-amd64/64
system.env 24
env result 24
wrapper|exec:/usr/lib/jvm/java-11-openjdk-amd64/bin/java -classpath /opt/ghidra_9.1.1_PUBLIC/Ghidra/Features/GhidraServer/data/yajsw-stable-12.12/wrapperApp.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Features/GhidraServer/lib/GhidraServer.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/FileSystem/lib/FileSystem.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/DB/lib/DB.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Docking/lib/Docking.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/Generic.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/FileSystem/lib/ganymed-ssh2-262.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Utility/lib/Utility.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/cglib-nodep-2.2.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/guava-19.0.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/jdom-legacy-1.1.3.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/log4j-core-2.8.2.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/log4j-api-2.8.2.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/commons-collections4-4.1.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/commons-lang3-3.9.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/commons-io-2.6.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Docking/lib/timingframework-1.0.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Docking/lib/javahelp-2.0.05.jar -Djava.net.preferIPv4Stack=true -DApplicationRollingFileAppender.maxBackupIndex=10 -Dclasspath_frag=/opt/ghidra_9.1.1_PUBLIC/server/../Ghidra/Features/GhidraServer/data/classpath.frag -Dghidra.cacerts=./Ghidra/cacerts -Ddb.buffers.DataBuffer.compressedOutput=true -Djava.library.path=/opt/ghidra_9.1.1_PUBLIC/server/../Ghidra/Features/GhidraServer/os/linux64 -Xms396m -Xmx2048m -Djava=/usr/lib/jvm/java-11-openjdk-amd64/bin/java -Dos_dir=/opt/ghidra_9.1.1_PUBLIC/server/../Ghidra/Features/GhidraServer/os/linux64 -Dghidra_home=/opt/ghidra_9.1.1_PUBLIC/server/.. -Dwrapper.port=15003 -Dwrapper.key=8535979915466022908 -Dwrapper.tmp.path=/tmp -Djna_tmpdir=/tmp -Dwrapper.config=/opt/ghidra_9.1.1_PUBLIC/server/server.conf org.rzo.yajsw.app.WrapperJVMMain 
wrapper|posix_spawn pid 26811
post start true null
setting fd
wrapper|started process 26811
wrapper|started process with pid 26811
26811/0|switch group ghidra2 -> ghidra2
26811/0|switch user ghidra2 -> ghidra2
26811/0|/usr/lib/jvm/java-11-openjdk-amd64/bin/java
26811/0|-classpath
26811/0|/opt/ghidra_9.1.1_PUBLIC/Ghidra/Features/GhidraServer/data/yajsw-stable-12.12/wrapperApp.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Features/GhidraServer/lib/GhidraServer.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/FileSystem/lib/FileSystem.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/DB/lib/DB.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Docking/lib/Docking.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/Generic.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/FileSystem/lib/ganymed-ssh2-262.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Utility/lib/Utility.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/cglib-nodep-2.2.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/guava-19.0.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/jdom-legacy-1.1.3.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/log4j-core-2.8.2.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/log4j-api-2.8.2.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/commons-collections4-4.1.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/commons-lang3-3.9.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/commons-io-2.6.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Docking/lib/timingframework-1.0.jar:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Docking/lib/javahelp-2.0.05.jar
26811/0|-Djava.net.preferIPv4Stack=true
26811/0|-DApplicationRollingFileAppender.maxBackupIndex=10
26811/0|-Dclasspath_frag=/opt/ghidra_9.1.1_PUBLIC/server/../Ghidra/Features/GhidraServer/data/classpath.frag
26811/0|-Dghidra.cacerts=./Ghidra/cacerts
26811/0|-Ddb.buffers.DataBuffer.compressedOutput=true
26811/0|-Djava.library.path=/opt/ghidra_9.1.1_PUBLIC/server/../Ghidra/Features/GhidraServer/os/linux64
26811/0|-Xms396m
26811/0|-Xmx2048m
26811/0|-Djava=/usr/lib/jvm/java-11-openjdk-amd64/bin/java
26811/0|-Dos_dir=/opt/ghidra_9.1.1_PUBLIC/server/../Ghidra/Features/GhidraServer/os/linux64
26811/0|-Dghidra_home=/opt/ghidra_9.1.1_PUBLIC/server/..
26811/0|-Dwrapper.port=15003
26811/0|-Dwrapper.key=8535979915466022908
26811/0|-Dwrapper.tmp.path=/tmp
26811/0|-Djna_tmpdir=/tmp
26811/0|-Dwrapper.config=/opt/ghidra_9.1.1_PUBLIC/server/server.conf
26811/0|org.rzo.yajsw.app.WrapperJVMMain
26811/0|java.lang.NullPointerException
26811/0|	at java.base/java.io.File.<init>(File.java:276)
26811/0|	at org.rzo.yajsw.boot.WrapperLoader.getWrapperClasspath(WrapperLoader.java:235)
26811/0|	at org.rzo.yajsw.app.WrapperManagerProxy.getWrapperClassLoader(WrapperManagerProxy.java:101)
26811/0|	at org.rzo.yajsw.app.WrapperManagerProxy.getWrapperManager(WrapperManagerProxy.java:44)
26811/0|	at org.rzo.yajsw.app.AbstractWrapperJVMMain$1.run(AbstractWrapperJVMMain.java:64)
26811/0|	at java.base/java.security.AccessController.doPrivileged(Native Method)
26811/0|	at org.rzo.yajsw.app.AbstractWrapperJVMMain.preExecute(AbstractWrapperJVMMain.java:56)
26811/0|	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:41)
26811/0|YAJSW: yajsw-stable-12.12
26811/0|OS   : Linux/5.3.0-26-generic/amd64
26811/0|JVM  : Private Build/11.0.5//usr/lib/jvm/java-11-openjdk-amd64/64
26811/0|WARNING: An illegal reflective access operation has occurred
26811/0|WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Features/GhidraServer/data/yajsw-stable-12.12/./lib/extended/groovy/groovy-all-2.4.11.jar) to method java.lang.Object.finalize()
26811/0|WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
26811/0|WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
26811/0|WARNING: All illegal access operations will be denied in a future release
26811/0|[INFO] StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
26811/0|INFO  Using log config file: jar:file:/opt/ghidra_9.1.1_PUBLIC/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)  
26811/0|INFO  Using log file: /opt/ghidra_9.1.1_PUBLIC/repositories/server.log (LoggingInitialization)  
26811/0|INFO  Initializing SSL Context (SSLContextInitializer)  
26811/0|INFO  Initializing Random Number Generator... (SecureRandomFactory)  
26811/0|INFO  Random Number Generator initialization complete: NativePRNGNonBlocking (SecureRandomFactory)  
26811/0|INFO  Trust manager initializing with cacerts: ./Ghidra/cacerts (ApplicationTrustManagerFactory)  
26811/0|INFO     <redacted>, <redacted>, S/N <redacted>, expires Wed Apr 15 20:18:38 EDT 2020 (ApplicationKeyStore)  
26811/0|INFO  Using self-signed certificate: CN=GhidraServer (ApplicationKeyManagerFactory$ApplicationKeyManager)  
26811/0|INFO     defaultsigkey: GhidraServer, issued by GhidraServer, S/N <redacted>, expires Thu Jan 20 11:52:21 EST 2022 (ApplicationKeyStore)  
26811/0|INFO  Ghidra Server 9.1.1 (GhidraServer)  
26811/0|INFO     Server remote access address: 192.168.56.101 (GhidraServer)  
26811/0|INFO     Server listening on interface: 192.168.56.101 (GhidraServer)  
26811/0|INFO     RMI Registry port: 13100 (GhidraServer)  
26811/0|INFO     RMI SSL port: 13101 (GhidraServer)  
26811/0|INFO     Block Stream port: 13102 (GhidraServer)  
26811/0|INFO     Block Stream compression: enabled (GhidraServer)  
26811/0|INFO     Root: ./repositories (GhidraServer)  
26811/0|INFO     Auth: PKI (GhidraServer)  
26811/0|INFO     Anonymous server access: disabled (GhidraServer)  
26811/0|INFO  ghidra2 starting Ghidra Server... (GhidraServer)  
26811/0|INFO  Instantiating Repository Manager for /opt/ghidra_9.1.1_PUBLIC/repositories (RepositoryManager)  
26811/0|INFO  Instantiating User Manager  (UserManager)  
26811/0|INFO  User file contains 2 entries (UserManager)  
26811/0|INFO  Known Users: (UserManager)  
26811/0|INFO     client DN={<redacted>} (UserManager)  
26811/0|INFO  Known Repositories: (RepositoryManager)  
26811/0|INFO     <redacted> (RepositoryManager)  
26811/0|INFO  Loading <redacted> ... (Repository)  
26811/0|INFO     ... loading 0 files ... (Repository)  
26811/0|INFO     <redacted> load complete.  (Repository)  
26811/0|INFO  Starting Block Stream Server... (BlockStreamServer)  
26811/0|INFO  Registering Ghidra Server... (GhidraServer)  
26811/0|INFO  Registered Ghidra Server. (GhidraServer)  
26811/0|INFO  Authentication callbacks requested by 192.168.56.1 (GhidraServer)  
26811/0|INFO  Repository server handle requested (<redacted>@192.168.56.1) (RepositoryManager)  
26811/0|INFO  User 'client' authenticated (<redacted>@192.168.56.1) (RepositoryManager)  
```
That's the full stout when running the server as `./ghidraSvr console` and on the client I did:
File -> New Project
Shared Project

Server Name: 192.168.56.101
Port: 13100

Next (waited a few seconds and then that error message appears) and the above log is displayed to the console.  I also imported the pki cert prior to trying to login.

**Comment by dev747368** [comment]
Ok, thanks for the logs.  For your usage though, it sounds like changing your client JVM fixed it for you?

General tip: move the repository directory to somewhere outside of the install path.

**Comment by xorhex** [comment]
Yes, changing the client JVM fixed it for me. 

Thanks for the tip.

**Comment by tick-rick** [comment]
another data point (debian linux). it appears to be due to mismatch of jvm version between client server, and could probably have an improved error message.

server: jdk 11.0.5, client: jdk 11.0.6 - ERROR
server: jdk 11.0.5, client: jdk 11.0.5 - OK
server: jdk 11.0.5, client: jdk 11.0.2 - OK

**Comment by tilver** [comment]
Is downgrading the jdk really the resolution for this?  It's a workaround, but not a solution.

**Comment by saruman9** [comment]
> Is downgrading the jdk really the resolution for this? It's a workaround, but not a solution.

I agree with @tilver, I think we should reopen issue.
Also don't work:
server: jdk 11.0.5, client: jdk 13.0.2.

**Comment by xorhex** [comment]
Sorry, been away for awhile.  Happy to re-open it.

**Comment by ChrisDietrich** [comment]
I'm experiencing the same exception when running java openjdk version "11.0.5" 2019-10-15 LTS on the server (linux) and adoptopenjdk11 11.0.6 on the client (macos). Solved by using adoptopenjdk12 on the client (java 12).

datapoints:
server: jdk 11.0.5 (linux), client: jdk 11.0.6 (macos) - ERROR
server: jdk 11.0.5 (linux), client: jdk 12.0.2 (macos) - OK

**Comment by dev747368** [comment]
The fix for this should be rolling out soon.  FYI, the jdk major version number isn't the issue, but the minor numbers would be a better indicator, as it was a change in the RMI logic that was committed in the jdk source tree just a few months ago (in October).  I'm guessing that change was then incorporated into the different major number builds (11, 12, 13, etc) as one of the minor-ver-number updates.

**Comment by ghidra1** [comment]
The issue appears to be client-side with the Java version.  For Java 11 it appears the check was introduced with 11.0.6.

**Comment by saruman9** [comment]
I built Ghidra from upstream (0914d476), but the problem has not been resolved. Which commit solves the problem?

**Comment by ghizard** [comment]
Sorry.  It's in patch, which hasn't been update here on GitHub yet and also not merged with master.

**Comment by ghidra1** [comment]
Master and patch have both been pushed to GitHub with the relevant fix.
