### ISSUE TITLE
Error connecting to server. Method is not remote.

### ISSUE THREAD

**Issue by jmamma** [NationalSecurityAgency/ghidra#1443]
I've got a server working. Can connect fine from MacOS

But my windows machine is struggling to connect (shares same IP as the mac)

Server logs are not showing anything unusual. Authentication succeeds. 

Suggestions?

```

An error occured on the server (REDACTED_SERVER_HOSTNAME:13100).

Method is not Remote: interface ghidra.framework.remote.RepositoryServerHandle::public abstract boolean ghidra.framework.remote.RepositoryServerHandle.isReadOnly() throws java.io.IOException
java.rmi.RemoteException: Method is not Remote: interface ghidra.framework.remote.RepositoryServerHandle::public abstract boolean ghidra.framework.remote.RepositoryServerHandle.isReadOnly() throws java.io.IOException
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:214)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:162)
	at com.sun.proxy.$Proxy22.isReadOnly(Unknown Source)
	at ghidra.framework.client.ServerConnectTask.getRepositoryServerHandle(ServerConnectTask.java:290)
	at ghidra.framework.client.ServerConnectTask.run(ServerConnectTask.java:72)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

---------------------------------------------------
Build Date: 2019-Dec-18 1306 EST
Ghidra Version: 9.1.1
Java Home: C:\Program Files\Java\jdk-11.0.6
JVM Version: Oracle Corporation 11.0.6
OS: Windows 10 10.0 amd64
Workstation: DESKTOP-DCRTMLQ
```

**Comment by jmamma** [comment]
Duplicate of #1440
