### ISSUE TITLE
could not find decompiler executable decompile

### ISSUE THREAD

**Issue by ghost** [NationalSecurityAgency/ghidra#1495]
hello, just found out about ghidra but am hitting a roadblock. I installed and ran ghidra, imported a file, analyzed the file but am receiving a "could not find decompiler executable decompile" error message.

i am not sure what i did wrong in setting it up. could anyone help me out? :)

additionally, another window displays "Demangle Symbol> Unable to demangle symbol: _ITM_registerTMCloneTable. Message: java.io.FileNotFoundException: os/linux32/demangler_gnu does not exist"...

![ghidraerror1](https://user-images.githubusercontent.com/37387567/73511010-0bea6c00-43dc-11ea-9519-ec703baa738a.png)
![ghidraerror2](https://user-images.githubusercontent.com/37387567/73511011-0bea6c00-43dc-11ea-80f8-d95c7636524c.png)

**Comment by astrelsky** [comment]
Are you on a 32 bit operating system? 32 bit operating systems are not supported.

https://www.ghidra-sre.org/InstallationGuide.html

**Comment by ryanmkurtz** [comment]
Or, you are on a 64-bit OS but your Java is 32-bits, like in #882.

Can you run this from your broken Ghidra's python interpreter (under Window --> Python) and report the output?
```
Python Interpreter for Ghidra
Based on Jython version 2.7.1 (default:0df7adb1b397, Jun 30 2017, 19:02:43) 
[OpenJDK 64-Bit Server VM (Amazon.com Inc.)]
Press 'F1' for usage instructions
>>> from java.lang import System
>>> System.getProperty("os.arch")
u'amd64'
```

**Comment by d-ingbat** [comment]
my output of 'uname -a' to show i have 64bit: Linux kali 4.19.93-Re4son-v8l+ #1 SMP PREEMPT Tue Jan 7 22:53:24 UTC 2020 aarch64 GNU/Linux
not sure why it shows os/linux32?

and output of jython: 
![image](https://user-images.githubusercontent.com/37387567/73585569-41558f00-449a-11ea-8aa3-fa608ca26a00.png)

i am not sure if it has anything to do with the arm architecture? do i have to set anything up differently for arm? 

thank you for your help!

**Comment by astrelsky** [comment]
> i am not sure if it has anything to do with the arm architecture? do i have to set anything up differently for arm?
> 
> thank you for your help!

It is indeed due to the arm architecture.
I'm going to submit a pr to both include ARM and to help avoid this for an "unknown" architecture in the future.

**Comment by d-ingbat** [comment]
doesn't look like it is emulated? also, not sure how to emulate it? this is all very new to me. 

![image](https://user-images.githubusercontent.com/37387567/73595955-d053bd00-4515-11ea-8e5b-875fd9cafc95.png)

**Comment by astrelsky** [comment]
> doesn't look like it is emulated? also, not sure how to emulate it? this is all very new to me.
> 
> ![image](https://user-images.githubusercontent.com/37387567/73595955-d053bd00-4515-11ea-8e5b-875fd9cafc95.png)

Ok so you will need to compile the native executables for your platform. If you'd like I could probably do this for you as I already have an aarch64-linux compiler installed.

You can download the source for 9.1.1 and follow the dev guide below. The only necessary commands would be `gradle --init-script gradle/support/fetchDependencies.gradle init` and `gradle buildNatives_linux64`. However, you will need to change their locations from `os/linux64` to `os/linux32` in the ghidra installation for the time being.
https://github.com/NationalSecurityAgency/ghidra/releases/tag/Ghidra_9.1.1_build

**Comment by swapplays31** [comment]
> > doesn't look like it is emulated? also, not sure how to emulate it? this is all very new to me.
> > ![image](https://user-images.githubusercontent.com/37387567/73595955-d053bd00-4515-11ea-8e5b-875fd9cafc95.png)
> 
> Ok so you will need to compile the native executables for your platform. If you'd like I could probably do this for you as I already have an aarch64-linux compiler installed.
> 
> You can download the source for 9.1.1 and follow the dev guide below. The only necessary commands would be `gradle --init-script gradle/support/fetchDependencies.gradle init` and `gradle buildNatives_linux64`. However, you will need to change their locations from `os/linux64` to `os/linux32` in the ghidra installation for the time being.
> https://github.com/NationalSecurityAgency/ghidra/releases/tag/Ghidra_9.1.1_build

I have same issue....ghidra trying for 32 bit demangle_gnu whem I have 64bit java

**Comment by ryanmkurtz** [comment]
Are you on an ARM system?

**Comment by swapplays31** [comment]
Yes

**Comment by ryanmkurtz** [comment]
The 32-bit error is misleading.  Ghidra's native binaries (demangler, decompiler) will only run on 64-bit x86.

**Comment by niqdev** [comment]
Hello! I'm having a similar issue on Alpine - I can open a separate issue if you prefer

```
Python Interpreter for Ghidra
Based on Jython version 2.7.2 (v2.7.2:925a3cc3b49d, Mar 21 2020, 10:03:58)
[OpenJDK 64-Bit Server VM (Alpine)]
Press 'F1' for usage instructions
>>> from java.lang import System
>>> System.getProperty("os.arch")
u'amd64'
```

Main error
```
Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/Features/Decompiler/os/linux64/decompile": error=2, No such file or directory
java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/Features/Decompiler/os/linux64/decompile": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at java.base/java.lang.Runtime.exec(Runtime.java:451)
	at ghidra.app.decompiler.DecompileProcess.setup(DecompileProcess.java:127)
	at ghidra.app.decompiler.DecompileProcess.registerProgram(DecompileProcess.java:444)
	at ghidra.app.decompiler.DecompInterface.initializeProcess(DecompInterface.java:228)
	at ghidra.app.decompiler.DecompInterface.openProgram(DecompInterface.java:318)
	at ghidra.app.decompiler.parallel.DecompilerCallback$DecompilerFactory.doCreate(DecompilerCallback.java:117)
	at ghidra.app.decompiler.parallel.DecompilerCallback$DecompilerFactory.doCreate(DecompilerCallback.java:101)
	at generic.cache.CountingBasicFactory.create(CountingBasicFactory.java:30)
	at generic.cache.CachingPool.get(CachingPool.java:79)
	at ghidra.app.decompiler.parallel.DecompilerCallback.process(DecompilerCallback.java:70)
	at ghidra.app.decompiler.parallel.DecompilerCallback.process(DecompilerCallback.java:41)
	at generic.concurrent.ConcurrentQ$CallbackCallable.call(ConcurrentQ.java:658)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 19 more

---------------------------------------------------
Build Date: 2020-Dec-29 1701 EST
Ghidra Version: 9.2.2
Java Home: /usr/lib/jvm/java-11-openjdk
JVM Version: Alpine 11.0.9
OS: Linux 5.8.0-45-generic amd64
Workstation: 3d67f2f508b2
```

From the *Auto Analysis Summary*
```
(These messages are also written to the application log file)

Demangler GNU> Unable to demangle symbol: __libc_start_main at EXTERNAL:00000004.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: __cxa_finalize at EXTERNAL:00000005.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: __deregister_frame_info at EXTERNAL:00000006.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: __register_frame_info at EXTERNAL:00000007.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: _ITM_deregisterTMCloneTable at EXTERNAL:00000008.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: _ITM_registerTMCloneTable at EXTERNAL:00000009.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: __DT_GNU_HASH at 00100290.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: __DT_SYMTAB at 001002c0.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: __DT_STRTAB at 001003e0.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: __DT_RELA at 001004a0.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: __DT_JMPREL at 00100530.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: entry at 00101080.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: deregister_tm_clones at 001010c0.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: register_tm_clones at 001010f0.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: __do_global_dtors_aux at 00101130.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: frame_dummy at 001011e0.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: main at 00101215.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: __do_global_ctors_aux at 001012a0.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: _fini at 001012e1.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: __GNU_EH_FRAME_HDR at 0010204c.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: cie at 00102070.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: fde at 00102088.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: fde at 001020b0.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: fde at 001020c8.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: __FRAME_END__ at 001020e8.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: __CTOR_LIST__ at 00103e00.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: __CTOR_END__ at 00103e08.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: __DTOR_LIST__ at 00103e10.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: __DTOR_END__ at 00103e18.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: _DYNAMIC at 00103e20.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: _GLOBAL_OFFSET_TABLE_ at 00103fa0.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: __dso_handle at 00104000.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: completed.2 at 00104020.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: dtor_idx.1 at 00104028.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: object.0 at 00104040.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: __deregister_frame_info at 00105010.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: _ITM_registerTMCloneTable at 00105018.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: _ITM_deregisterTMCloneTable at 00105020.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: __register_frame_info at 00105038.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: cie_.debug_frame::00000000 at .debug_frame::00000000.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
Demangler GNU> Unable to demangle symbol: fde_.debug_frame::00000018 at .debug_frame::00000018.  Message: java.io.IOException: Cannot run program "/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
```

The error looks legitimate, that file doesn't exist :sweat: but I've simply extracted the zip files and that file is not there!
```
ls -la /opt/ghidra/ghidra_PUBLIC/Ghidra/Features/Decompiler/os/linux64/
total 3416
drwxr-xr-x    2 root     root          4096 Mar 17 13:21 .
drwxr-xr-x    5 root     root          4096 Mar 17 13:21 ..
-rwxr-x--x    1 root     root       2699043 Mar 17 13:21 decompile
-rwxr-x--x    1 root     root        789005 Mar 17 13:21 sleigh
```

Any suggestion other than build it from sources? Is it normal that is looking for a file that doesn't exist?

**Comment by astrelsky** [comment]
It exists in the output of `ls -la` you are showing there.

**Comment by niqdev** [comment]
I think the first error taken from the main popup is confusing, my bad! Because in the detailed logs below it says that it's actually looking for this file `demangler_gnu_v2_33_1`, which is actually missing.
```
"/opt/ghidra/ghidra_PUBLIC/Ghidra/../GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1": error=2, No such file or directory
```

**Comment by astrelsky** [comment]
Try running it on its own. Specifically the demangler since its easier to know if it is working.

`{path to demangler} _ZTIi` should print `typeinfo for int`

**Comment by ryanmkurtz** [comment]
@niqdev where did you get your distribution of Ghidra from?

**Comment by niqdev** [comment]
Thanks for the feedback, I'm pretty sure it's something related to the installation on Alpine, I have no issue on ubuntu/mac of course! It's just that the error is a bit confusing

@astrelsky to your question this is the output I get
```
bash-5.1# ls -la /opt/ghidra/ghidra_PUBLIC/GPL/DemanglerGnu/os/linux64/
total 248
drwxr-xr-x    2 root     root          4096 Mar 22 14:14 .
drwxr-xr-x    5 root     root          4096 Mar 22 14:14 ..
-rwxr-x--x    1 root     root        129458 Mar 22 14:14 demangler_gnu_v2_24
-rwxr-x--x    1 root     root        110787 Mar 22 14:14 demangler_gnu_v2_33_1
bash-5.1# /opt/ghidra/ghidra_PUBLIC/GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1 _ZTIi
bash: /opt/ghidra/ghidra_PUBLIC/GPL/DemanglerGnu/os/linux64/demangler_gnu_v2_33_1: No such file or directory
```
which is the same error I have in the ui. Actually, this error is very suspicious even if `musl` is installed :thinking: 
```
[libc.musl-x86_64.so.1] -> not found
```
![ghidra-error](https://user-images.githubusercontent.com/9458643/112006538-b6ab7580-8b1b-11eb-9985-a2d579e66e76.png)

@ryanmkurtz I'm building my own docker images, but I pulled the distro from the official site, see [here](https://github.com/niqdev/strawhatsec/blob/main/docker/reverse/Dockerfile#L53)

I'm not sure what dependency I'm actually missing :pensive: If you have any hints in what exactly look for or how to figure out what lib I need to install, that would be much appreciated! I haven't tried yet, but I'm suspect that if I try to build it from sources I would get a similar error

If you have any interests in reproducing the error by yourself, here all the steps I just did
```bash
# clone the repo or just copy the Dockerfile with the ghidra install step only
git clone git@github.com:niqdev/strawhatsec.git
docker build -t strawhatsec/reverse ./docker/reverse
docker run --rm --name reverse -p 5900:5900 strawhatsec/reverse

docker exec -it reverse bash
# binary sample
echo -e "#include <stdio.h>\nint main(int argc,char *argv[]){printf(\"hello\");return 0;}" > test.c
gcc test.c -o test && chmod +x test
./test

# starts ghidra
ghidra

# open ui and import the binary
vncviewer localhost:5900
```

**Comment by ryanmkurtz** [comment]
@niqdev I came across this today:  https://openjdk.java.net/jeps/386

Are you using java 16?

**Comment by niqdev** [comment]
Interesting! Nope I'm on `openjdk11-jdk`... Have you tested ghidra on the jdk-16 already?

Adding this just for reference
```
To build a musl variant of the JDK on Alpine Linux, the following packages are required:

    alpine-sdk alsa-lib alsa-lib-dev autoconf bash cups-dev cups-libs fontconfig fontconfig-dev freetype freetype-dev grep libx11 libx11-dev libxext libxext-dev libxrandr libxrandr-dev libxrender libxrender-dev libxt libxt-dev libxtst libxtst-dev linux-headers zip
```

**Comment by ryanmkurtz** [comment]
Ghidra only officially supports the latest LTS version of the JDK, which is Java 11, but it won't stop you from running on later versions.  I know a lot of people use newer versions with success.  If you want to test it, you can download an Alpine version of AdoptOpenJDK [here](https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/download/jdk-16%2B36/OpenJDK16-jdk_x64_alpine-linux_hotspot_16_36.tar.gz).

**Comment by niqdev** [comment]
Well, at this point i might try first to build it from sources and see if i get a more specific error. Do you have a "how to" guide step-by-step to follow, to build the project?

**Comment by ryanmkurtz** [comment]
https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md

**Comment by niqdev** [comment]
Thanks! I'll look into it and give you a feedback as soon as I get a chance to test it

**Comment by ryanmkurtz** [comment]
Sure thing!  I'm going to close this ticket because it's changed direction a lot from the initial poster's problem.  If you are still having issues, feel free to make a new ticket where we can talk about your more specific issue.  Thanks!

**Comment by niqdev** [comment]
@ryanmkurtz just for reference, I managed to solve the issue on alpine adding this package
* https://github.com/sgerrand/alpine-pkg-glibc
* https://github.com/Docker-Hub-frolvlad/docker-alpine-glibc

**Comment by ryanmkurtz** [comment]
Ah ok, thanks for following up
