### ISSUE TITLE
NoSuchMethodError - 'java.lang.ClassLoader[] org.apache.logging.log4j.util.LoaderUtil.getClassLoaders()'

### ISSUE THREAD

**Issue by brainstorm** [NationalSecurityAgency/ghidra#1523]
**Describe the bug**

On previous GHidra releases, I could `gradle buildGhidra`, unzip, ghidraRun and off you go.

Today I repeated this process and ended up with log4j errors instead, looks vaguely similar to issue https://github.com/NationalSecurityAgency/ghidra/issues/658, but log4j classes are involved instead:

```java
$ ./support/launch.sh fg Ghidra 2G "" ghidra.GhidraRun
openjdk version "11.0.5" 2019-10-15 LTS
OpenJDK Runtime Environment Corretto-11.0.5.10.2 (build 11.0.5+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.5.10.2 (build 11.0.5+10-LTS, mixed mode)
Error: Uncaught Exception!
NoSuchMethodError - 'java.lang.ClassLoader[] org.apache.logging.log4j.util.LoaderUtil.getClassLoaders()'
java.lang.NoSuchMethodError: 'java.lang.ClassLoader[] org.apache.logging.log4j.util.LoaderUtil.getClassLoaders()'
	at org.apache.logging.log4j.core.util.WatchManager.getEventServices(WatchManager.java:278)
	at org.apache.logging.log4j.core.util.WatchManager.<init>(WatchManager.java:57)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:135)
	at org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:32)
	at org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:85)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:179)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:153)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:82)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:228)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
	at ghidra.framework.LoggingInitialization.initializeLoggingSystem(LoggingInitialization.java:48)
	at ghidra.framework.Application.initializeLogging(Application.java:180)
	at ghidra.framework.Application.initializeLogging(Application.java:146)
	at ghidra.framework.Application.initialize(Application.java:94)
	at ghidra.framework.Application.initializeApplication(Application.java:114)
	at ghidra.GhidraRun.lambda$launch$1(GhidraRun.java:78)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**To Reproduce**
1. `git clone https://github.com/nationalsecurityagency/ghidra && cd ghidra`
2. `gradle prepDev && gradle buildGhidra`
3. `cd build/dist && unzip ghidra_9.2_DEV_20200209_osx64.zip && cd ghidra_9.2_DEV`
4. `ghidraRun`, tweak to `fg` to see error. Kaboom.

**Expected behavior**

After `gradle buildGhidra`, `ghidraRun` should spawn a ghidra instance as it did in previous releases, namely the following ones (my own local builds) work well:

```
ghidra_9.1_DEV_20190916_osx64.zip
ghidra_9.1_DEV_20191007_osx64.zip
ghidra_9.2_DEV_20191031_osx64.zip
ghidra_9.1_DEV_20190919_osx64.zip
```

**Environment (please complete the following information):**
 - OS: macOS 10.15.2
 - Java Version: OpenJDK Runtime Environment Corretto-11.0.5.10.2 (build 11.0.5+10-LTS)
 - Ghidra Version: 9.2_DEV_20200209_osx64

**Comment by ryanmkurtz** [comment]
Did you do:

`gradle --init-script gradle/support/fetchDependencies.gradle init`

**Comment by brainstorm** [comment]
Thanks @ryanmkurtz, that did not work either. I had to resort to `gradle clean` and start over with the build from scratch, **then** all went fine :)
