### ISSUE TITLE
PCode disassembly fails during emulation of x86 MOV Instructions

### ISSUE THREAD

**Issue by broosa** [NationalSecurityAgency/ghidra#1579]
Hello all!

I'm attempting to do some emulation of x86 instructions in ghidra using the Java API. At the moment, calls to `EmulatorHelper.run()` are failing with the following stack trace:

```
ERROR Pseudo block disassembly failure at 00401c2e: null (Disassembler) java.lang.UnsupportedOperationException
	at ghidra.pcode.emulate.EmulateMemoryStateBuffer.getMemory(EmulateMemoryStateBuffer.java:115)
	at ghidra.program.disassemble.Disassembler.disassembleInstructionBlock(Disassembler.java:925)
	at ghidra.program.disassemble.Disassembler.pseudoDisassembleBlock(Disassembler.java:800)
	at ghidra.pcode.emulate.Emulate.emitPcode(Emulate.java:219)
	at ghidra.pcode.emulate.Emulate.executeInstruction(Emulate.java:399)
	at ghidra.app.emulator.Emulator.executeInstruction(Emulator.java:334)
	at ghidra.app.emulator.EmulatorHelper.executeInstruction(EmulatorHelper.java:518)
	at ghidra.app.emulator.EmulatorHelper.continueExecution(EmulatorHelper.java:499)
	at ghidra.app.emulator.EmulatorHelper.run(EmulatorHelper.java:470)
	at UnhideMovString.run(UnhideMovString.java:60)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:365)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:220)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:198)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:57)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)`
```

It appears that the error is being triggered in the following sequence:
- `ghidra.pcode.emulate.Emulate.emitPcode()` passes an `EmulateMemoryStateBuffer` to `ghidra.program.disassemble.Disassembler.pseudoDisassembleBlock()`
- This function then calls `ghidra.program.disassemble.Disassembler.disassembleInstructionBlock()` which attempts to call `getMemory()` on the passed `EmulateMemoryStateBuffer`

Looking at the definition of `getMemory()`, this simply throws an `UnsupportedOperationException`:
```
       @Override
	public Memory getMemory() {
		// Make sure Sleigh language provider does not call this method
		throw new UnsupportedOperationException();
	}
````

Is this intended behavior, or is it functionality that has yet to be implemented? Or is there some other way of emulating code that does not use `EmulateMemoryStateBuffer`? Any insight would be much appreciated!

Regards,

@broosa

**Comment by emteere** [comment]
That was an inadvertent side-effect of a speed improvement.  We will address as soon as possible.
In the interim, change line 925 in Disassembler.java to:
```
MemBuffer instrMemBuffer = new WrappedMemBuffer(blockMemBuffer,
			(int) addr.subtract(blockMemBuffer.getAddress()));
```

**Comment by emteere** [comment]
Fixed in master
