### ISSUE TITLE
Error importing: "RuntimeException: NE - Resource - unknown id - 0000"

### ISSUE THREAD

**Issue by sopoforic** [NationalSecurityAgency/ghidra#1596]
**Describe the bug**
When importing a Windows executable in NE format, compiled from Visual Basic 3 (which correctly uses the NeLoader), the import fails with the following error:

```
java.lang.RuntimeException: NE - Resource - unknown id - 0000
	at ghidra.app.util.bin.format.ne.Resource.toString(Resource.java:168)
	at java.base/java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:439)
	at ghidra.app.util.opinion.NeLoader.processResourceTable(NeLoader.java:361)
	at ghidra.app.util.opinion.NeLoader.load(NeLoader.java:137)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:346)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:401)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

**Attachments**
The executable in question: [THINKFST.zip](https://github.com/NationalSecurityAgency/ghidra/files/4289674/THINKFST.zip)

**Environment (please complete the following information):**
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
JVM Version: Oracle Corporation 13.0.2
OS: Windows 10 10.0 amd64

**Additional context**
The same error occurs in both 9.0 and 9.1.1.

**Comment by emteere** [comment]
will be fixed in master/9.2
