### ISSUE TITLE
Jython Uncaught Exception Fail

### ISSUE THREAD

**Issue by leurnkim** [NationalSecurityAgency/ghidra#1602]
When trying to start Python interpreter it fails.

To reproduce this failure i start Python in Window menu of CodeBrowser.

Task Error window pollutes after that. When closing this window typing any command have no interpreter reply.

Environment info (details):

Resetting Python... - Uncaught Exception: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
	at org.python.core.PyString.<init>(PyString.java:57)
	at org.python.core.PyString.<init>(PyString.java:70)
	at org.python.core.PyString.<init>(PyString.java:74)
	at org.python.core.Py.newString(Py.java:647)
	at ghidra.python.GhidraPythonInterpreter.<init>(GhidraPythonInterpreter.java:103)
	at ghidra.python.GhidraPythonInterpreter.get(GhidraPythonInterpreter.java:89)
	at ghidra.python.PythonPlugin.resetInterpreterInBackground(PythonPlugin.java:198)
	at ghidra.python.PythonPlugin.lambda$resetInterpreter$1(PythonPlugin.java:181)
	at ghidra.util.task.TaskLauncher$3.run(TaskLauncher.java:150)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: C:\Program Files\Amazon Corretto\jdk11.0.6_10
JVM Version: Amazon.com Inc. 11.0.6
OS: Windows 7 6.1 amd64

Also is it Jython bug?

**Comment by ryanmkurtz** [comment]
What happens if you run:

`support/pythonRun.bat`

**Comment by leurnkim** [comment]
Interpreter starts with some warnings, replies python commands.
No Ghidra imports at all.

**Comment by ryanmkurtz** [comment]
Do you have any non-ascii characters in your %PATH% environment variable?
