### ISSUE TITLE
Uncaught Exception when attempting a type change

### ISSUE THREAD

**Issue by ubitux** [NationalSecurityAgency/ghidra#1603]
Happened while changing a local variable type (`byte` → `ulong`) for which Ghidra had set an automatic `_` prefix:

```
Uncaught Exception! 
IllegalArgumentException - Specified size does not match storage size
java.lang.IllegalArgumentException: Specified size does not match storage size
	at ghidra.program.model.pcode.MappedSymbol.<init>(MappedSymbol.java:41)
	at ghidra.program.model.pcode.LocalSymbolMap.newMappedSymbol(LocalSymbolMap.java:321)
	at ghidra.program.model.pcode.HighFunction.splitOutMergeGroup(HighFunction.java:472)
	at ghidra.app.plugin.core.decompile.actions.RetypeVariableAction.retypeVariable(RetypeVariableAction.java:144)
	at ghidra.app.plugin.core.decompile.actions.RetypeVariableAction.decompilerActionPerformed(RetypeVariableAction.java:429)
	at ghidra.app.plugin.core.decompile.actions.AbstractDecompilerAction.lambda$actionPerformed$1(AbstractDecompilerAction.java:58)
	at ghidra.app.plugin.core.decompile.DecompilerActionContext.performAction(DecompilerActionContext.java:74)
	at ghidra.app.plugin.core.decompile.actions.AbstractDecompilerAction.actionPerformed(AbstractDecompilerAction.java:57)
	at docking.ExecutableKeyActionAdapter.execute(ExecutableKeyActionAdapter.java:40)
	at docking.action.MultipleKeyAction.actionPerformed(MultipleKeyAction.java:150)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at docking.KeyBindingOverrideKeyEventDispatcher.actionInProgress(KeyBindingOverrideKeyEventDispatcher.java:204)
	at docking.KeyBindingOverrideKeyEventDispatcher.dispatchKeyEvent(KeyBindingOverrideKeyEventDispatcher.java:116)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1133)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4893)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: /usr/lib/jvm/java-13-openjdk
JVM Version: N/A 13.0.2
OS: Linux 5.5.7-arch1-1 amd64
Workstation: localhost.localdomain
```

I'm not sure how to reproduce it, but I was jungling between removing stuff from the Symbol tree, changing the variable types from the declarations in the decompiler, as well as on their usage in the decompiler view.

**Comment by dragonmacher** [comment]
Closing this due to its age.  We can always reopen if the issue is still reproducible.
