### ISSUE TITLE
Unable to open GUI with more than 2 Monitors

### ISSUE THREAD

**Issue by red667** [NationalSecurityAgency/ghidra#161]
**Describe the bug**
Starting Ghidra is not possible with more than 2 monitors. 
It is possible to start with 2 Monitors and then enable the 3rd one afterwards. So I suspect that the "loading banner" is causing the problem.

**To Reproduce**
1. Go to 'Ghidra-Directory/support/'
2. Run ./ghidraDebug
3. Wait for Errors and terminate with CTRC-C
4. See error:
ERROR Error: Uncaught Exception! 
IllegalArgumentException - Window must not be zero  (SwingExceptionHandler.java:81) 
java.lang.IllegalArgumentException: Window must not be zero
        at sun.awt.X11.XAtom.checkWindow(XAtom.java:774) ~[?:?]
        at sun.awt.X11.XAtom.getAtomData(XAtom.java:465) ~[?:?]
        at sun.awt.X11.XToolkit.getWorkArea(XToolkit.java:805) ~[?:?]
        at sun.awt.X11.XToolkit.getInsets(XToolkit.java:881) ~[?:?]
        at sun.awt.X11.XToolkit.getScreenInsets(XToolkit.java:869) ~[?:?]
        at sun.java2d.SunGraphicsEnvironment.getUsableBounds(SunGraphicsEnvironment.java:260) ~[?:?]
        at sun.awt.X11GraphicsEnvironment.getXineramaWindowBounds(X11GraphicsEnvironment.java:390) ~[?:?]
        at sun.awt.X11GraphicsEnvironment.getMaximumWindowBounds(X11GraphicsEnvironment.java:314) ~[?:?]
        at generic.util.WindowUtilities.getScreenBounds(WindowUtilities.java:82) ~[Generic.jar:?]
        at generic.util.WindowUtilities.centerOnScreen(WindowUtilities.java:123) ~[Generic.jar:?]
        at docking.DockingDialog.setCenteredOnScreen(DockingDialog.java:308) ~[Docking.jar:?]
        at docking.DockingDialog.setCenteredOnComponent(DockingDialog.java:277) ~[Docking.jar:?]
        at docking.DockingDialog.initializeLocationAndSize(DockingDialog.java:122) ~[Docking.jar:?]
        at docking.DockingDialog.<init>(DockingDialog.java:100) ~[Docking.jar:?]
        at docking.DockingDialog.createDialog(DockingDialog.java:78) ~[Docking.jar:?]
        at docking.DockingWindowManager.lambda$doShowDialog$4(DockingWindowManager.java:1700) ~[Docking.jar:?]
        at ghidra.util.SystemUtilities.runSwing(SystemUtilities.java:295) ~[Utility.jar:?]
        at ghidra.util.SystemUtilities.runSwingNow(SystemUtilities.java:260) ~[Utility.jar:?]
        at docking.DockingWindowManager.doShowDialog(DockingWindowManager.java:1705) ~[Docking.jar:?]
        at docking.DockingWindowManager.showDialog(DockingWindowManager.java:1737) ~[Docking.jar:?]
        at docking.DockingErrorDisplay.doShowDialog(DockingErrorDisplay.java:102) ~[Docking.jar:?]
        at docking.DockingErrorDisplay.lambda$showDialog$0(DockingErrorDisplay.java:90) ~[Docking.jar:?]
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) ~[?:?]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) ~[?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
        at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) ~[?:?]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]

**Expected behavior**
Ghidra should start with more that 2 Monitors attached.

**Environment:**
 - OS: Fedora 29 with KDE Plasma 5.14.5
 - Java Version: openjdk version "11.0.2"
 - Ghidra Version: 9.0

**Comment by ryanmkurtz** [comment]
This is probably Java issue [JDK-8204646](https://bugs.openjdk.java.net/browse/JDK-8204646)

**Comment by red667** [comment]
Maybe, but other Java software like BurpSuite does not have the same issue.

**Comment by red667** [comment]
@ryanmkurtz I just tested with Oracle JDK 11.0.2 and the bug does not occur.

**Comment by ryanmkurtz** [comment]
Interesting, thanks for doing additional testing!  So if you bounce back and forth between the OpenJDK and the Oracle JDK, the bad and good behavior is repeatable?

**Comment by karaface** [comment]
I ran into the same issue. The bug only occurs on OpenJDK with multiple monitors/X displays. 

OpenJDK 11 with 1 monitor/X display = OK
OpenJDK 11 with multiple montiors/X displays = Fail
Oracle JDK 11 with 1 or multiple monitors = OK
Oracle/OpenJDK 8 = Fail

**Comment by d-millar** [comment]
Also, may be Linux-specific, i.e. doesn't happen on macOS.  (Caveated with the fact that I'm VDI'ed through a Windows thin-client.)

**Comment by karaface** [comment]
@d-millar macOS doesn't use X11 or Wayland as its display server. So it wouldn't be relevant.

**Comment by d-millar** [comment]
@karaface check - missed that!  should have paid more attention to the stack...

**Comment by red667** [comment]
Issue is still the same on Version 9.0.2

OpenJDK 11 with 2 monitor/X display = OK
OpenJDK 11 with 3+ montiors/X displays = Fail
Oracle JDK 11 with 1 or multiple monitors = OK

**Comment by ryanmkurtz** [comment]
Yea, we are currently at the mercy of OpenJDK fixing it at the moment.

**Comment by colbin8r** [comment]
`openjdk 11.0.2 2019-01-15` on macOS Mojave (10.14.3) with an external monitor and I ran into the issue. Disconnecting the monitor before starting allowed me to run Ghidra.

**Comment by ryanmkurtz** [comment]
I've seen some obscure references to this type of problem in the OpenJDK 11.0.3 change logs.  Has anyone had any luck with it?

**Comment by ryanmkurtz** [comment]
Closing since this seems to be a problem with OpenJDK.
