### ISSUE TITLE
Issues Running Server on Windows Server

### ISSUE THREAD

**Issue by Gillagorilla** [NationalSecurityAgency/ghidra#167]
Running on Windows Server 2016 Version 1607 Build 14393.2828
Using OpenJDK 11
`c:\>java -version`
`openjdk version "11.0.2" 2019-01-15`
`OpenJDK Runtime Environment 18.9 (build 11.0.2+9)`
`OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)`

Env variables set
`c:\>echo %path%`
`C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files (x86)\openjdk-11.0.2_windows-x64_bin\jdk-11.0.2\bin;C:\Users\username\AppData\Local\Microsoft\WindowsApps`

`c:\>echo %java_home%`
`C:\Program Files (x86)\openjdk-11.0.2_windows-x64_bin\jdk-11.0.2`.

At this point the client seems to work without issue using the GhidraRub.bat.  My issues all revolve around the Server component. 
I get the following when i try to just start the server on console.

`c:\Program Files (x86)\ghidra_9.0_PUBLIC_20190228\ghidra_9.0>server\ghidraSvr.bat console`
`\ghidra_9.0_PUBLIC_20190228\ghidra_9.0\server\..\Ghidra\Features\GhidraServer\data\yajsw-stable-12.12 was unexpected at this time.`

I am able to get past this by commenting out several lines in the Ghidrasvr.bat.  Specifically these between lines 37 and 61:
`rem if not exist "%WRAPPER_HOME%\" (`
`rem 	set ERROR_MSG=%WRAPPER_HOME% not found`
`rem 	echo !ERROR_MSG!`
`rem 	echo !ERROR_MSG! >> %GHIDRA_HOME%\wrapper.log`
`rem 	exit /B 1`
`rem )`

`:: Make sure some kind of java is on the path.  It's required to run the LaunchSupport program.`
`java -version >nul 2>nul`
`rem if not %ERRORLEVEL% == 0 (`
`rem 	set ERROR_MSG=Java runtime not found.  Please refer to the Ghidra Installation Guide's Troubleshooting section.`
`rem 	echo !ERROR_MSG!`
`rem 	echo !ERROR_MSG! >> %GHIDRA_HOME%\wrapper.log`
`rem 	exit /B 1`
`rem )`

`:: Get the java that will be used to launch GhidraServer`
`rem set JAVA_HOME=`
`for /f "delims=*" %%i in ('java -cp "%LS_CPATH%" LaunchSupport "%GHIDRA_HOME%" -java_home') do set JAVA_HOME=%%i`
`rem if "%JAVA_HOME%" == "" (`
`rem 	set ERROR_MSG=Failed to find a supported Java runtime.  Please refer to the Ghidra Installation Guide's Troubleshooting section.`
`rem 	echo !ERROR_MSG!`
`rem 	echo !ERROR_MSG! >> %GHIDRA_HOME%\wrapper.log`
`rem 	exit /B 1`
`rem )`

After doing this, the server appears to run. I am able to do "ghidrasvr.bat install" and the service does appear to install and auto-run at startup.  However, I cannot get the server to stay alive if i use Windows auth "-a1".  I can do the local auth "-a0" without much issue.  

When I switch the auth to:
`#wrapper.app.parameter.1=-a0`
`wrapper.app.parameter.1=-a1`
`#wrapper.app.parameter.2=-u`
`wrapper.app.parameter.3=-dRPG`

I get a error in the client and the app server crashes.

> An error occured while connecting to the server (RPG-GHS01.RPG.LAB:13100).
Connection reset
javax.net.ssl.SSLProtocolException: Connection reset
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:126)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1314)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:839)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:222)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:161)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:209)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:161)
	at com.sun.proxy.$Proxy21.getRepositoryServer(Unknown Source)
	at ghidra.framework.client.ServerConnectTask.getRepositoryServerHandle(ServerConnectTask.java:292)
	at ghidra.framework.client.ServerConnectTask.run(ServerConnectTask.java:73)
	at ghidra.util.task.Task.monitoredRun(Task.java:128)
	at ghidra.util.task.TaskLauncher.lambda$startBackgroundThread$2(TaskLauncher.java:315)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1104)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
	... 13 more

> ---------------------------------------------------
>Build Date: 2019-Feb-28 1236 EST
>Ghidra Version: 9.0
>Java Home: C:\Program Files (x86)\openjdk-11.0.2_windows-x64_bin\jdk-11.0.2
>JVM Version: Oracle Corporation 11.0.2
>OS: Windows Server 2016 10.0 amd64
>Workstation: RPG-GHS01.RPG.LAB

The Wrapper crash log points to perhaps ntsystem.dll
> A fatal error has been detected by the Java Runtime Environment:
> EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff8a751039, pid=92, tid=3576
> JRE version: OpenJDK Runtime Environment (11.0.2+9) (build 11.0.2+9)
> Java VM: OpenJDK 64-Bit Server VM (11.0.2+9, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
> Problematic frame:
> C  [NTSystem.dll+0x1039]

> Core dump will be written. Default location: c:\Program Files (x86)\ghidra_9.0_PUBLIC_20190228\ghidra_9.0\hs_err_pid92.mdmp

[hs_err_pid92.log](https://github.com/NationalSecurityAgency/ghidra/files/2954201/hs_err_pid92.log)

**Comment by ghidra1** [comment]
The ghidraSvr.bat file has been revised for 9.0.1 but unclear if it will resolve your launch issue.

Due to the incompatibility of the native Windows authentication mode (-a1 and -a3) with newer Windows versions this authentication mode has been dropped for 9.0.1 pending further review. 
  
See [Issue #101](https://github.com/NationalSecurityAgency/ghidra/issues/101) regarding networking issue within EC2 cloud.
