### ISSUE TITLE
Ghidra file import issue

### ISSUE THREAD

**Issue by noob2020-alt** [NationalSecurityAgency/ghidra#1711]
**Describe the bug**
A clear and concise description of the bug.

**To Reproduce**
1. Go to 'File'
2. Click on 'Import File'
3. Scroll down to 'Selected File'
Uncaught Exception! 
java.lang.NullPointerException
	at ghidra.plugin.importer.ImporterDialog.lambda$buildLoaderChooser$3(ImporterDialog.java:266)
	at docking.widgets.list.GListCellRenderer$1.getItemText(GListCellRenderer.java:49)
	at docking.widgets.list.GListCellRenderer.getListCellRendererComponent(GListCellRenderer.java:85)
	at java.desktop/javax.swing.plaf.synth.SynthComboBoxUI.paintCurrentValue(SynthComboBoxUI.java:374)
	at java.desktop/javax.swing.plaf.synth.SynthComboBoxUI.paint(SynthComboBoxUI.java:353)
	at java.desktop/javax.swing.plaf.synth.SynthComboBoxUI.update(SynthComboBoxUI.java:323)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:797)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1884)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at java.desktop/java.awt.Component.show(Component.java:1717)
	at java.desktop/java.awt.Component.setVisible(Component.java:1664)
	at java.desktop/java.awt.Window.setVisible(Window.java:1023)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005)
	at docking.DockingDialog.setVisible(DockingDialog.java:317)
	at docking.DockingWindowManager.lambda$doShowDialog$6(DockingWindowManager.java:1720)
	at ghidra.util.Swing.doRun(Swing.java:295)
	at ghidra.util.Swing.runNow(Swing.java:211)
	at ghidra.util.Swing.runNow(Swing.java:166)
	at ghidra.util.SystemUtilities.runSwingNow(SystemUtilities.java:253)
	at docking.DockingWindowManager.doShowDialog(DockingWindowManager.java:1724)
	at docking.DockingWindowManager.showDialog(DockingWindowManager.java:1756)
	at docking.AbstractDockingTool.showDialog(AbstractDockingTool.java:155)
	at ghidra.plugin.importer.ImporterUtilities.lambda$importSingleFile$3(ImporterUtilities.java:322)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at java.desktop/java.awt.Component.show(Component.java:1717)
	at java.desktop/java.awt.Component.setVisible(Component.java:1664)
	at java.desktop/java.awt.Window.setVisible(Window.java:1023)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005)
	at docking.DockingDialog.setVisible(DockingDialog.java:317)
	at docking.DockingWindowManager.lambda$doShowDialog$6(DockingWindowManager.java:1720)
	at ghidra.util.Swing.doRun(Swing.java:295)
	at ghidra.util.Swing.runNow(Swing.java:211)
	at ghidra.util.Swing.runNow(Swing.java:166)
	at ghidra.util.SystemUtilities.runSwingNow(SystemUtilities.java:253)
	at docking.DockingWindowManager.doShowDialog(DockingWindowManager.java:1724)
	at docking.DockingWindowManager.showDialog(DockingWindowManager.java:1756)
	at ghidra.util.task.TaskDialog.lambda$doShow$7(TaskDialog.java:277)
	at ghidra.util.Swing.runIfSwingOrRunLater(Swing.java:127)
	at ghidra.util.SystemUtilities.runIfSwingOrPostSwingLater(SystemUtilities.java:267)
	at ghidra.util.task.TaskDialog.doShow(TaskDialog.java:276)
	at ghidra.util.task.TaskDialog.doShowModal(TaskDialog.java:258)
	at ghidra.util.task.TaskDialog.show(TaskDialog.java:239)
	at ghidra.util.task.TaskRunner.showTaskDialog(TaskRunner.java:131)
	at ghidra.util.task.TaskRunner.lambda$run$0(TaskRunner.java:53)
	at ghidra.util.Swing.runIfSwingOrRunLater(Swing.java:127)
	at ghidra.util.task.TaskRunner.run(TaskRunner.java:53)
	at ghidra.util.task.TaskLauncher.<init>(TaskLauncher.java:223)
	at ghidra.util.task.TaskLauncher.<init>(TaskLauncher.java:205)
	at ghidra.util.task.TaskLauncher.launchModal(TaskLauncher.java:116)
	at ghidra.plugin.importer.ImporterUtilities.showImportDialog(ImporterUtilities.java:137)
	at ghidra.plugin.importer.ImporterPlugin.importFile(ImporterPlugin.java:171)
	at ghidra.plugin.importer.ImporterPlugin.doSingleImportAction(ImporterPlugin.java:338)
	at ghidra.plugin.importer.ImporterPlugin$1.actionPerformed(ImporterPlugin.java:208)
	at docking.DockingActionProxy.actionPerformed(DockingActionProxy.java:47)
	at docking.MenuBarMenuHandler$1.run(MenuBarMenuHandler.java:78)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: /usr/lib/jvm/jdk-14
JVM Version: Oracle Corporation 14
OS: Linux 5.3.0-kali2-amd64 amd64
Workstation: kali

**Expected behavior**
Once I click the file to import, I get the aforementioned dialog and cannot seem to close the windows. Multiple error windows popup. By the time I close the last one, another two to three pop up. 

**Screenshots**

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: [e.g. Kali 2019.4]
 - Java Version: [e.g. 11.0]
 - Ghidra Version: [e.g. 9.1.2]

**Additional context**

**Comment by dev747368** [comment]
From your log dump, it says "JVM Version: Oracle Corporation 14", but lower you specified a java version of (or just left the example) "11.0".  You can see the current jvm used in the Ghidra Help | About dialog.

Anyway, we don't support java 14.  I suggest trying the current jdk 11 build.

**Comment by astrelsky** [comment]
> From your log dump, it says "JVM Version: Oracle Corporation 14", but lower you specified a java version of (or just left the example) "11.0". You can see the current jvm used in the Ghidra Help | About dialog.
> 
> Anyway, we don't support java 14. I suggest trying the current jdk 11 build.

I'm able to run the ghidra 9.1.2 distribution using jdk 14 without an issue on windows. The problem may lie elsewhere.

**Comment by saruman9** [comment]
> Unless it's specific to jdk 14 on Linux.

I use Ghidra from `master` branch on ArchLinux with jdk14-openjdk without any problems.

**Comment by noob2020-alt** [comment]
I installed the new Java. I did have to remove it though and it is working.
Must've been a conflict. THank you very much for the speedy reply.

**Comment by noob2020-alt** [comment]
I think there was a conflict between the java 11 and the newest jdk-14
download. I may have to remove it. Thank you. I will try that. I did get it
to work with jdk-11 but still having some issues with pulling some files
from crackme. I will retry the process. I did get it to read some of the
files though. Thanks a bunch.

**Comment by ryanmkurtz** [comment]
Duplicate of #1989
