### ISSUE TITLE
Ghidra fails to import NE executable: "RuntimeException: NE - ResourceType - name lookup required - 1838"

### ISSUE THREAD

**Issue by xplt** [NationalSecurityAgency/ghidra#1713]
**Describe the bug**
I'm trying to take a look at an old (Win3.1/Win95) game called "Stars!" (which was successfully installed in wine), but Ghidra cannot import it's executable (in wine, it at least runs).

**To Reproduce**
1. Install the game from the CD
2. Try to import file "STARS!.EXE"
3. An error dialog will appear:
```
Error importing file: STARS!.EXE
java.lang.RuntimeException: NE - ResourceType - name lookup required - 1838
	at ghidra.app.util.bin.format.ne.ResourceType.toString(ResourceType.java:129)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at ghidra.app.util.opinion.NeLoader.processResourceTable(NeLoader.java:344)
	at ghidra.app.util.opinion.NeLoader.load(NeLoader.java:137)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:346)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:401)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Screenshots**
Stars! under wine: ![stars_retail_wine](https://user-images.githubusercontent.com/6225402/78462868-11677980-76df-11ea-89ff-bd1a5f045662.png)
Stars! in Ghidra:
![ghidra_importing_stars](https://user-images.githubusercontent.com/6225402/78462890-673c2180-76df-11ea-9a95-ceef508dcbe1.png)

**Expected behavior**
Ghidra should be able to import the file and start analyzing it, without any error dialogs

**Environment (please complete the following information):**
 - Build Date: 2020-Feb-12 1149 EST
 - Ghidra Version: 9.1.2
 - Java Home: /home/desktop/.sdkman/candidates/java/11.0.5.hs-adpt
 - JVM Version: AdoptOpenJDK 11.0.5
 - OS: Linux 4.19.0-0.steamos2.3-amd64 amd64
 - Workstation: steamos

**Additional context**
Probably, it is the same/similar issue as  #1596

**Comment by emteere** [comment]
will be fixed in master/9.2
