### ISSUE TITLE
Copy/Cut --> Paste uncaught exception

### ISSUE THREAD

**Issue by ryanmkurtz** [NationalSecurityAgency/ghidra#1796]
In the Front End Tree View, copy or cut a file in a folder.  Now move or rename that folder.  Finally, paste the file somewhere.  You get an uncaught exception.

```
folder /lib not found
java.io.FileNotFoundException: folder /lib not found
	at ghidra.framework.data.GhidraFolder.getFolderData(GhidraFolder.java:104)
	at ghidra.framework.data.GhidraFolder.getFileData(GhidraFolder.java:79)
	at ghidra.framework.data.GhidraFile.getFileData(GhidraFile.java:60)
	at ghidra.framework.data.GhidraFile.copyTo(GhidraFile.java:489)
	at ghidra.framework.main.datatree.PasteFileTask.copyFile(PasteFileTask.java:132)
	at ghidra.framework.main.datatree.PasteFileTask.pasteFile(PasteFileTask.java:104)
	at ghidra.framework.main.datatree.PasteFileTask.run(PasteFileTask.java:80)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by dragonmacher** [comment]
I was unable to reproduce this.   Maybe it has been fixed.

**Comment by ryanmkurtz** [comment]
I just reproduced the exception in the latest master.  I made a folder, dragged a program into it, copied that program, renamed the folder, then pasted to the top level project tree.
