### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Specified length extends beyond file bytes length 	at ghidra.program.database.mem.MemoryMapDB.checkFileBytesRange(MemoryMapDB.java:589)

### ISSUE THREAD

**Issue by tthtlc** [NationalSecurityAgency/ghidra#1869]
A clear and concise description of the bug.

I openup wanacry.exe with Ghidra 9.1.2:

Error importing file: wannacry.exe
java.lang.IndexOutOfBoundsException: Specified length extends beyond file bytes length
	at ghidra.program.database.mem.MemoryMapDB.checkFileBytesRange(MemoryMapDB.java:589)
	at ghidra.program.database.mem.MemoryMapDB.createInitializedBlock(MemoryMapDB.java:552)
	at ghidra.app.util.MemoryBlockUtils.createInitializedBlock(MemoryBlockUtils.java:225)
	at ghidra.app.util.opinion.PeLoader.processMemoryBlocks(PeLoader.java:657)
	at ghidra.app.util.opinion.PeLoader.load(PeLoader.java:121)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:346)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:401)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: /home/tthtlc/ghidra_9.1.2_PUBLIC/jdk-11.0.7+10
JVM Version: AdoptOpenJDK 11.0.7
OS: Linux 5.3.0-51-generic amd64
Workstation: mymamapapa

But if I use The Ubuntu (18.04) own system Java JDK, then I will get the following errors:

Error importing file: wannacry.exe
java.lang.IndexOutOfBoundsException: Specified length extends beyond file bytes length
	at ghidra.program.database.mem.MemoryMapDB.checkFileBytesRange(MemoryMapDB.java:589)
	at ghidra.program.database.mem.MemoryMapDB.createInitializedBlock(MemoryMapDB.java:552)
	at ghidra.app.util.MemoryBlockUtils.createInitializedBlock(MemoryBlockUtils.java:225)
	at ghidra.app.util.opinion.PeLoader.processMemoryBlocks(PeLoader.java:657)
	at ghidra.app.util.opinion.PeLoader.load(PeLoader.java:121)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:346)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:401)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: /usr/lib/jvm/java-11-openjdk-amd64
JVM Version: Ubuntu 11.0.7
OS: Linux 5.3.0-51-generic amd64
Workstation: mymamapapa

 - OS: Ubuntu 18.04
 - Java Version: Ubuntu or OpenJDK 11
 - Ghidra Version: 9.1.2

**Comment by tthtlc** [comment]
The bug happened here:

![image](https://user-images.githubusercontent.com/179509/82137874-67871b00-984e-11ea-9582-ca92aa4e226b.png)

Now my question is:   if the binary is able to trigger any of these exception handler in Ghidra - is that not a possible scenario of "anti-debugging", if the normal windows is able to load the binary without encountering these problem?

**Comment by tthtlc** [comment]
Cross ref:  https://github.com/NationalSecurityAgency/ghidra/issues/1266

I used IDA 7.2 to load the same binary, and it gives this warning:

![image](https://user-images.githubusercontent.com/179509/82139169-92766c80-9858-11ea-8fcc-a46d7eef82e8.png)

But it has not problem disassembling the binary.   Ghidra should not have thrown this as a show-stopper exception - there is no way to continue the use of Ghidra at all, which is what the malware wants to achieve.   It should be some kind of a warning instead.    What you think?

**Comment by ryanmkurtz** [comment]
This is working in 9.2 (master).  Probably fixed by #1371.

**Comment by emteere** [comment]
Fixed in master, future 9.2 release.
