### ISSUE TITLE
NPE during loading PDB file

### ISSUE THREAD

**Issue by kant2002** [NationalSecurityAgency/ghidra#188]
**Describe the bug**

**To Reproduce**
1. Create C++ executable using VS2019 Prevew 4.2 from code above
```
#include <iostream>
#include <windows.h>

_LARGE_INTEGER x;

int main()
{
	x.QuadPart = 0;
    std::cout << x.QuadPart; 
}
```
2. Import ConsoleApplication1.exe
3. Double-click to enter open file for analysis
4. Agree to autoanalysis and do not change anything in the settings
5. Press Analyze

**Expected behavior**
PDB loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/4257079/54310994-e3a82200-45fd-11e9-86f0-47f0f2d4b6ba.png)

![image](https://user-images.githubusercontent.com/4257079/54311036-f7538880-45fd-11e9-9a20-8454155a028b.png)

```
Problem parsing or applying PDB information: NullPointerException
java.io.IOException: Problem parsing or applying PDB information: NullPointerException
	at ghidra.app.util.bin.format.pdb.PdbParserNEW.applyTo(PdbParserNEW.java:395)
	at ghidra.app.plugin.core.analysis.PdbAnalyzer.parsePdb(PdbAnalyzer.java:140)
	at ghidra.app.plugin.core.analysis.PdbAnalyzer.added(PdbAnalyzer.java:70)
	at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:185)
	at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:685)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:785)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:664)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:629)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:62)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:101)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at ghidra.app.util.bin.format.pdb.PdbParserNEW.completeDefferedTypeParsing(PdbParserNEW.java:281)
	at ghidra.app.util.bin.format.pdb.PdbParserNEW.applyTo(PdbParserNEW.java:368)
	... 12 more

---------------------------------------------------
Build Date: 2019-Feb-28 1236 EST
Ghidra Version: 9.0
JVM Version: Oracle Corporation 11.0.2
OS: Windows 10 10.0 amd64

```

Likely related to issue posted by @hacksysteam in #94

**Comment by kant2002** [comment]
In the file `Ghidra/Features/PDB/src/main/java/ghidra/app/util/bin/format/pdb/PdbParserNEW.java`

In the `completeDefferedTypeParsing` method
```
-               applyDataTypes.buildDataTypes(monitor);
-               applyClasses.buildDataTypes(monitor);
-               applyTypeDefs.buildTypeDefs(monitor);
+               if (applyDataTypes != null) {
+                       applyDataTypes.buildDataTypes(monitor);
+               }
+
+               if (applyClasses != null) {
+                       applyClasses.buildDataTypes(monitor);
+               }
+
+               if (applyTypeDefs != null) {
+                       applyTypeDefs.buildTypeDefs(monitor);
+               }

```

**Comment by ghidra1** [comment]
This will be corrected for 9.0.1.   

Newer PDBs omit unused sections.  A work around is to add the missing XML sections to the top of the PDB xml file until 9.0.1 is available.  Do not add if corresponding section already exists in file.

```
<pdb ....>
     <classes/>
     <functions/>
     <datatypes/>

...snip...

</pdb>

```

**Comment by ghidra1** [comment]
Duplicate of #138

**Comment by v-p-b** [comment]
Based on the code linked by @kant2002 and local experiments the workaround should be more like

```xml
	<classes/>
	<!--functions/-->
	<datatypes/>
	<typedefs/>
```

right?
