### ISSUE TITLE
When loading PDB with incorrect age, misleading error produced.

### ISSUE THREAD

**Issue by kant2002** [NationalSecurityAgency/ghidra#198]
**Describe the bug**
I have a PDB which is has root elment like this `<pdb file="ConsoleApplication1.pdb" exe="ConsoleApplication1" guid="{2D0C13AA-D03A-44C2-B13A-3C9077EEC622}" age="4">`

Somehow Ghidra execute `.\Features\PDB\os\win64\pdb.exe ConsoleApplication1.pdb 2d0c13aa-d03a-44c2-b13a-3c9077eec622  00000002` which produce 
```
WARNING:
PDB age does not match.
```

Which does not parsed correctly inside PDB  loading process.
Instead of that produced error message with indication that PDB.exe should be recompiled, which is misleading at best.

```
PDB Execution failure of pdb.exe.
This was likely caused by severe execution failure which can occur if executed
on an unsupported platform. It may be neccessary to rebuild the PDB executable
for your platform (see Ghidra/Features/PDB/src).

- ghidra.app.util.bin.format.pdb.PdbException:

 PDB Execution failure of pdb.exe.
This was likely caused by severe execution failure which can occur if executed
on an unsupported platform. It may be neccessary to rebuild the PDB executable
for your platform (see Ghidra/Features/PDB/src).
	at ghidra.app.util.bin.format.pdb.PdbParserNEW.verifyPdbSignature(PdbParserNEW.java:578)
	at ghidra.app.util.bin.format.pdb.PdbParserNEW.processPdbContents(PdbParserNEW.java:555)
	at ghidra.app.util.bin.format.pdb.PdbParserNEW.parse(PdbParserNEW.java:147)
	at pdb.LoadPdbTask$1.analysisWorkerCallback(LoadPdbTask.java:59)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1683)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:685)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:785)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:664)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:629)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:62)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:101)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**To Reproduce**
1. Create small app
2. Load it into Ghidra
3. Build again
4. Only now open executable for loading. It will pickup more recent PDB.

**Expected behavior**
Report message from PDB.exe in the exception.

**Comment by ghizard** [comment]
This seems to one of the issues also presented in an internal ticket (GT-1696). I am investigating further.

**Comment by ghizard** [comment]
GT-1696 is slightly different.  It was more focused on not having Ghidra error out by choosing a PDB file with the wrong age (when one with the right age exists) and then failing without ever trying the one with the correct age.
Your issue here seems odd.  The pdb.exe should be writing the WARNING message to stderr, but it seems that stderr is being redirected to stdout and being read by the input stream that tries to parse the XML. Do you recall if you might have done anything to redirect stderr on your platform?
Also, someone might have changed the exec processing that redirects stderr... I'm not familiar with it, and it also seems that we are deficient on some tests here too.

**Comment by ghizard** [comment]
@kant2002 I believe I have a simple fix for this in the works. Validation logic had an issue, which caused a different/bigger issue, masking the trigger.  The fix should now allow the original logic to take place, giving the user a choice to apply the mismatched PDB to the target, even though it might not be the best thing to do. In the future, I hope that in the future we will be able to apply data types without apply symbols (symbols most likely would be at the wrong addresses).
