### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by imring** [NationalSecurityAgency/ghidra#1989]
**Describe the bug**
When importing a file throws "Uncaught Exception".

**To Reproduce**
1. Open project.
2. File -> "Import File..."
3. Select a file.
4. "Uncaught Exception".

**Expected behavior**
Had to add the file to the project.

**Screenshots**
![image](https://user-images.githubusercontent.com/35897995/84591899-9cd15980-ae4a-11ea-8600-9625295a21b0.png)
![image](https://user-images.githubusercontent.com/35897995/84591903-a6f35800-ae4a-11ea-9aa9-cb00c6f63af8.png)

**Attachments**
```
Uncaught Exception! 
java.lang.NullPointerException
	at ghidra.plugin.importer.ImporterDialog.lambda$buildLoaderChooser$3(ImporterDialog.java:266)
	at docking.widgets.list.GListCellRenderer$1.getItemText(GListCellRenderer.java:49)
	at docking.widgets.list.GListCellRenderer.getListCellRendererComponent(GListCellRenderer.java:85)
	at java.desktop/javax.swing.plaf.synth.SynthComboBoxUI.paintCurrentValue(SynthComboBoxUI.java:374)
	at java.desktop/javax.swing.plaf.synth.SynthComboBoxUI.paint(SynthComboBoxUI.java:353)
	at java.desktop/javax.swing.plaf.synth.SynthComboBoxUI.update(SynthComboBoxUI.java:323)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:797)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5262)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1060)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:78)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:115)
	at java.desktop/java.awt.Container.paint(Container.java:2002)
	at java.desktop/java.awt.Window.paint(Window.java:3940)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:876)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1890)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at java.desktop/java.awt.Component.show(Component.java:1716)
	at java.desktop/java.awt.Component.setVisible(Component.java:1663)
	at java.desktop/java.awt.Window.setVisible(Window.java:1031)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005)
	at docking.DockingDialog.setVisible(DockingDialog.java:317)
	at docking.DockingWindowManager.lambda$doShowDialog$6(DockingWindowManager.java:1720)
	at ghidra.util.Swing.doRun(Swing.java:295)
	at ghidra.util.Swing.runNow(Swing.java:211)
	at ghidra.util.Swing.runNow(Swing.java:166)
	at ghidra.util.SystemUtilities.runSwingNow(SystemUtilities.java:253)
	at docking.DockingWindowManager.doShowDialog(DockingWindowManager.java:1724)
	at docking.DockingWindowManager.showDialog(DockingWindowManager.java:1756)
	at docking.AbstractDockingTool.showDialog(AbstractDockingTool.java:155)
	at ghidra.plugin.importer.ImporterUtilities.lambda$importSingleFile$3(ImporterUtilities.java:322)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Environment (please complete the following information):**
- Build Date: 2020-Feb-12 1149 EST
- Ghidra Version: 9.1.2
- Java Home: /usr/lib/jvm/java-11-openjdk-amd64
- JVM Version: Ubuntu 11.0.7
- OS: Linux 5.4.0-37-generic amd64 (Kubuntu 20.04 LTS)

**Additional context**
Tried Oracle JDK 14 - same thing

**Comment by mumbel** [comment]
dup to #1711 (or at least same stacktrace)

**Comment by ryanmkurtz** [comment]
I'm stumped.  I can't see how a null loader can get introduced.  Does it do this with every binary you import?  If not, can you share this binary?

**Comment by imring** [comment]
reinstalled ghidra and openjdk 11 - helped
![image](https://user-images.githubusercontent.com/35897995/84880014-abab4c80-b094-11ea-8c16-969a28b184d4.png)
