### ISSUE TITLE
Error java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by NavpreetDevpuri** [NationalSecurityAgency/ghidra#1997]
**Describe the bug**
As i metioned at [this](https://github.com/threatrack/ghidra-patchdiff-correlator/issues/2) issue
I am using extention [ghidra-patchdiff-correlator](https://github.com/threatrack/ghidra-patchdiff-correlator)
I am trying to find patch in a cracked **vector magic** software.
Using Ghidra's **version tracking** on windows 10 with 32gb ram.
you can download **vector magic** from [this](https://vectormagic.com/desktop/download) link 
And i have cracked [vmde.exe](https://github.com/threatrack/ghidra-patchdiff-correlator/files/4794943/vmde.zip) file for that software that works fine.
I tried to change **Minimum similarity threshold (score)** to **0.999** but it also show same error.
![javaw_KbvROmv9ph](https://user-images.githubusercontent.com/30471072/84946684-b43c6b00-b106-11ea-87d7-43b357e4f5a8.png)

i tried following methods but don't work 
1. [Set default heap size in Windows](https://stackoverflow.com/questions/17369522/set-default-heap-size-in-windows)
2. [Increase Java Memory in Windows](https://www.wikihow.com/Increase-Java-Memory-in-Windows-7)

It shows Following error just at 97% (113167044 functions) **[2/3] Counting diff set(For all functions)**

```
Merge Version Tracking Session - Uncaught Exception: java.lang.OutOfMemoryError: Java heap space java.lang.OutOfMemoryError: Java heap space
--------------------------------------------------- 
Build Date: 2020-Feb-12 1149 EST Ghidra Version: 9.1.2 Java Home: C:\Program Files\AdoptOpenJDK\jdk-14.0.1.7-hotspot JVM 
Version: AdoptOpenJDK 14.0.1 
OS: Windows 10 10.0 amd64 
Workstation: DESKTOP-3DAR26Q
```
And sometimes shows details
```
Merge Version Tracking Session - Uncaught Exception: java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.HashMap.resize(HashMap.java:705)
	at java.base/java.util.HashMap.putVal(HashMap.java:664)
	at java.base/java.util.HashMap.put(HashMap.java:613)
	at java.base/java.util.HashSet.add(HashSet.java:221)
	at patchdiffcorrelator.BulkProgramCorrelator.doCorrelate(BulkProgramCorrelator.java:135)
	at ghidra.feature.vt.api.util.VTAbstractProgramCorrelator.correlate(VTAbstractProgramCorrelator.java:77)
	at ghidra.feature.vt.gui.wizard.AddToSessionTask.run(AddToSessionTask.java:119)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at ghidra.util.task.TaskRunner$$Lambda$345/0x0000000801188840.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: C:\Program Files\AdoptOpenJDK\jdk-14.0.1.7-hotspot
JVM Version: AdoptOpenJDK 14.0.1
OS: Windows 10 10.0 amd64
Workstation: DESKTOP-3DAR26Q

```

**Environment (please complete the following information):**
 - OS: Windows 10 64bit
 - Java Version: 14.0.1
 - Ghidra Version: 9.2

**Comment by NavpreetDevpuri** [comment]
I edited **ghidraRun.bat** file and add **set MAXMEM=13000M** and now it works fine.

```bat
:: Ghidra launch

@echo off
setlocal

:: Maximum heap memory size
:: Default for Windows 32-bit is 768M and 64-bit is 1024M
:: Raising the value too high may cause a silent failure where
:: Ghidra fails to launch.
:: Uncomment MAXMEM setting if non-default value is needed

set MAXMEM=13000M

call "%~dp0support\launch.bat" bg Ghidra "%MAXMEM%" "" ghidra.GhidraRun %*

```
