### ISSUE TITLE
Allow Mouse Button binds in Tool Options

### ISSUE THREAD

**Issue by LWSS** [NationalSecurityAgency/ghidra#208]
**Is your feature request related to a problem? Please describe.**
I like to go forward and back with the forward/back mouse buttons.

**Describe the solution you'd like**
To be able to bind mouse buttons in the keybinding section

**Comment by quosego** [comment]
Hey @LWSS ,

You can create keybindings by creating a new object that implements DockingAction, for example, NavigatableContextAction. 

then set key binding to it
```
// Mouse Left: BUTTON1_DOWN_MASK 
// Mouse Right: BUTTON3_DOWN_MASK 
action.setKeyBindingData(new KeyBindingData(InputEvent.BUTTON1_DOWN_MASK, 0)));
```
and then add it to your existing PluginTool. Hope that helps.

**Comment by BhaaLseN** [comment]
Particularly "Go to previous location" and "Go to next location" would be hot candidates to be configured in that dialog, so I can put them on my thumb buttons on the mouse (as other applications such as Web browsers or Visual Studio recognize as Back/Forward).

**Comment by dragonmacher** [comment]
Java does not make application-level mouse handling easy.  This is too much effort for us to do right now, considering the given demand.   If there is much excitement for this in the future, then we can revisit this request.

For now, I am attaching a Ghidra Script that *should* provide the functionality you desire.   The script will use a known Java testing mechanism to install a global mouse  listener.   When triggered, the listener will execute the back or forward button, depending on the mouse button pressed.   You may have to modify this script to get it to work with your hardware.

The downside to this script is that it must be run each time you start Ghidra.

- Rename the script by removing the .txt extension
- Drop the renamed script into `<user home>/ghidra_scripts`
[MouseToAndFroScript.java.txt](https://github.com/NationalSecurityAgency/ghidra/files/3283463/MouseToAndFroScript.java.txt)

**Comment by LWSS** [comment]
Can you guys just add Forward/Back buttons like a normal program? Why do I have try and use this jank ass script?

![image](https://user-images.githubusercontent.com/8827133/193358278-fd40dfd6-4f7b-44b6-8414-dea23f6042c5.png)

ghidra sucks, the only reason I came back is because IDA failed to decompile 1 function and I thought it'd be easier to just open it real quick (lol) in ghidra.

This is like the first thing I notice when using the program, I don't understand what other things are more important than actually being able to go forward/back without moving the mouse all the way to the top left or moving both my hands to press ALT+LEFT. I guess you NSA goons are paid by the hour and don't care.

**Comment by sad-dev** [comment]
Maybe you should learn how to read error messages first?

**Comment by LWSS** [comment]
> Maybe you should learn how to read error messages first?

Yeah u know what I did? I clicked new script and a Java editor popped up, pasted some code in there, saved, and clicked the play button. Nothing works, and this was after I tried to place it in the proper directory. Big waste of time, not worth more than 5 minutes of troubleshooting. Uninstalled.

**Comment by mrexodia** [comment]
If you're on macOS you can use [Karabiner Elements](https://karabiner-elements.pqrs.org/) and add the following in `~/.config/karabiner/karabiner.json`:

```json
                    {
                        "description": "Ghidra Mouse Navigation",
                        "manipulators": [
                            {
                                "conditions": [
                                    {
                                        "file_paths": [
                                            "^/Applications/Ghidra.+$"
                                        ],
                                        "type": "frontmost_application_if"
                                    }
                                ],
                                "description": "Button 4 to Alt+Right Arrow",
                                "from": {
                                    "pointing_button": "button4"
                                },
                                "to": [
                                    {
                                        "key_code": "left_arrow",
                                        "modifiers": [
                                            "left_option"
                                        ]
                                    }
                                ],
                                "type": "basic"
                            },
                            {
                                "conditions": [
                                    {
                                        "file_paths": [
                                            "^/Applications/Ghidra.+$"
                                        ],
                                        "type": "frontmost_application_if"
                                    }
                                ],
                                "description": "Button 5 to Alt+Right Arrow",
                                "from": {
                                    "pointing_button": "button5"
                                },
                                "to": [
                                    {
                                        "key_code": "right_arrow",
                                        "modifiers": [
                                            "left_option"
                                        ]
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    },
```

Just beware that this only works if you're using something like [Ghidra-App-Bundle with an embedded OpenJDK](https://github.com/TorgoTorgo/Ghidra-App-Bundle/pull/10). This is because the running process is `java` and Karabiner detects the topmost application like this:

```
net.java.openjdk.java
/Applications/Ghidra.app/Contents/Resources/jdk/bin/java
```

**Comment by DorianRudolph** [comment]
On my Linux setup the script provided by @dragonmacher did not work. I  changed it to use keys 6/7 and the PRESS event.

https://gist.github.com/DorianRudolph/31ffd3d216dda33e80713138a20ad007

**Comment by Toizi** [comment]
For ghidra 10.4 the script didn't compile for me. I had to replace all occurrences of `ActionContext` with `DefaultActionContext`.

**Comment by dragonmacher** [comment]
@Toizi Thanks for pointing that out.  I uploaded an edited version of the script.

**Comment by utkonos** [comment]
On macOS, using `MouseEvent.MOUSE_PRESSED` works much better than `MouseEvent. MOUSE_CLICKED `.

Other than that, the script works as expected.

Is there a way to run one or more scripts automatically when the CodeBrowser Tool opens?

This feature would be a valuable addition to Ghidra so a script is not needed.

**Comment by dragonmacher** [comment]
> Is there a way to run one or more scripts automatically when the CodeBrowser Tool opens?

Interesting suggestion.   There is nothing like this scheduled.

**Comment by kfilbrun** [comment]
Just wanted to add another vote for this getting added correctly...it's a feature I use a lot in other programs and it's quite bothersome to not have it for navigation in Ghidra. I've tried to use the provided script, but with the latest version of Ghidra on Windows I keep getting errors about the `back` variable being null. `getNavigationAction` returns a valid `DockingActionIf` but somehow it's `null` by the time `actionPerformed` is invoked. 

I also found that `MOUSE_CLICKED` is very unreliably generated for fwd/back on my system...so I was going down the path with improving the forward/back detection. I've attached that effort to this comment. I just can't sort out the `null` bug and unfortunately 
[MouseToAndFroScriptBetterDetection.java.txt](https://github.com/NationalSecurityAgency/ghidra/files/14574847/MouseToAndFroScriptBetterDetection.java.txt)
don't have time to understand the code base more at present.

```
Cannot invoke "docking.action.DockingActionIf.actionPerformed(docking.ActionContext)" because "back" is null
java.lang.NullPointerException: Cannot invoke "docking.action.DockingActionIf.actionPerformed(docking.ActionContext)" because "back" is null
	at MouseToAndFroScript.lambda$createListener$1(MouseToAndFroScript.java:81)
	at java.desktop/java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2193)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2085)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2084)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2084)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2084)
	at java.desktop/java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2041)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4902)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2024-Jan-30 1212 EST
Ghidra Version: 11.0.1
Java Home: C:\Program Files\Eclipse Adoptium\jdk-21.0.2.13-hotspot
JVM Version: Eclipse Adoptium 21.0.2
OS: Windows 11 10.0 amd64
Workstation: LC-LTP-79QZFY3
```

**Comment by dragonmacher** [comment]
> Just wanted to add another vote for this getting added correctly...it's a feature I use a lot in other programs and it's quite bothersome to not have it for navigation in Ghidra. I've tried to use the provided script, but with the latest version of Ghidra on Windows I keep getting errors about the `back` variable being null. `getNavigationAction` returns a valid `DockingActionIf` but somehow it's `null` by the time `actionPerformed` is invoked.
> 
> 

I took a peek at this.  The line number in the stack trace does not appear to match the script that you attached.  If the action is null when `Swing.runLater()` is called, then some sort of programming error is implied.  Do you have a version of the script with line numbers that match the stack trace?

**Comment by kfilbrun** [comment]
> > Just wanted to add another vote for this getting added correctly...it's a feature I use a lot in other programs and it's quite bothersome to not have it for navigation in Ghidra. I've tried to use the provided script, but with the latest version of Ghidra on Windows I keep getting errors about the `back` variable being null. `getNavigationAction` returns a valid `DockingActionIf` but somehow it's `null` by the time `actionPerformed` is invoked.
> 
> I took a peek at this. The line number in the stack trace does not appear to match the script that you attached. If the action is null when `Swing.runLater()` is called, then some sort of programming error is implied. Do you have a version of the script with line numbers that match the stack trace?

Hey! Sorry about this, I attempted to delete the comment because I found my issue - I was running too new a version of the JDK. Switching to LTS 17 solved the issues I had running the script. I did find that it seems like the main click handler in the listing window also responds to the forward/back buttons as if it were a left mouse click, so it seems like the forward/back navigation fights with an attempt to select the hovered line. However, the script works reasonably well if you have the mouse outside the window the navigation takes place in. I would still love to see this integrated natively! I think a lot of people would use it, and it could work better.

Here's my version of the script in case someone else wants it...I found the click handlers performed really poorly with my hardware and the click events were rarely generated, but press events were...although at times multiple times over.

[MouseToAndFroScript.java.txt](https://github.com/NationalSecurityAgency/ghidra/files/14606275/MouseToAndFroScript.java.txt)

**Comment by dragonmacher** [comment]
>  I would still love to see this integrated natively! I think a lot of people would use it, and it could work better.

I'm exploring some ideas that may allows us to get a better solution for this in place.

**Comment by kfilbrun** [comment]
Awesome, thanks so much!
