### ISSUE TITLE
Version Tracking plugin fails to initialize (number format issue)

### ISSUE THREAD

**Issue by szymski** [NationalSecurityAgency/ghidra#209]
**Describe the bug**
Whenever I run the Version Tracking tool, I get the following message: ``Error constructing plugin: class ghidra.feature.vt.gui.plugin.VTPlugin``. The tool window appears, but it is empty - there are no plugins loaded.

**To Reproduce**
1. Create a project
2. Open the Version Tracking tool

**Attachments**
Stack trace:
```
2019-03-15 23:41:28 ERROR (PluginUtils) Unexpected Exception: For input string: "0,000" java.lang.NumberFormatException: For input string: "0,000"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:543)
	at java.base/java.lang.Double.valueOf(Double.java:506)
	at ghidra.feature.vt.gui.provider.matchtable.AbstractDoubleRangeFilter.isDefaultFilterState(AbstractDoubleRangeFilter.java:203)
	at ghidra.feature.vt.gui.provider.matchtable.AbstractDoubleRangeFilter.getFilterShortcutState(AbstractDoubleRangeFilter.java:194)
	at ghidra.feature.vt.gui.util.AbstractVTMatchTableModel.getFilters(AbstractVTMatchTableModel.java:102)
	at ghidra.feature.vt.gui.util.AbstractVTMatchTableModel.rebuildFilter(AbstractVTMatchTableModel.java:131)
	at ghidra.feature.vt.gui.util.AbstractVTMatchTableModel.addFilter(AbstractVTMatchTableModel.java:127)
	at ghidra.feature.vt.gui.provider.matchtable.VTMatchTableProvider.addFilter(VTMatchTableProvider.java:728)
	at ghidra.feature.vt.gui.provider.matchtable.VTMatchTableProvider.createScoreFilterPanel(VTMatchTableProvider.java:388)
	at ghidra.feature.vt.gui.provider.matchtable.VTMatchTableProvider.createFilterArea(VTMatchTableProvider.java:346)
	at ghidra.feature.vt.gui.provider.matchtable.VTMatchTableProvider.createComponent(VTMatchTableProvider.java:220)
	at ghidra.feature.vt.gui.provider.matchtable.VTMatchTableProvider.<init>(VTMatchTableProvider.java:101)
	at ghidra.feature.vt.gui.plugin.VTPlugin.<init>(VTPlugin.java:116)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at ghidra.framework.plugintool.util.PluginUtils.instantiatePlugin(PluginUtils.java:184)
	at ghidra.framework.plugintool.PluginManager.addPlugins(PluginManager.java:104)
	at ghidra.framework.plugintool.PluginManager.restorePluginsFromXml(PluginManager.java:275)
	at ghidra.framework.plugintool.PluginTool.restoreFromXml(PluginTool.java:712)
	at ghidra.framework.plugintool.PluginTool.<init>(PluginTool.java:122)
	at ghidra.framework.project.tool.GhidraTool.<init>(GhidraTool.java:80)
	at ghidra.framework.project.tool.GhidraToolTemplate.createTool(GhidraToolTemplate.java:211)
	at ghidra.framework.project.tool.ToolManagerImpl.getTool(ToolManagerImpl.java:689)
	at ghidra.framework.project.tool.WorkspaceImpl.runTool(WorkspaceImpl.java:75)
	at ghidra.framework.main.ToolButton$2.end(ToolButton.java:622)
	at ghidra.framework.main.ZoomImageRunner$1.end(ZoomImageRunner.java:54)
	at org.jdesktop.animation.timing.Animator.end(Animator.java:755)
	at org.jdesktop.animation.timing.Animator.stop(Animator.java:660)
	at org.jdesktop.animation.timing.Animator.timingEvent(Animator.java:732)
	at org.jdesktop.animation.timing.Animator.access$200(Animator.java:75)
	at org.jdesktop.animation.timing.Animator$TimerTarget.actionPerformed(Animator.java:1041)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
 
2019-03-15 23:41:28 ERROR (GhidraTool) Error Restoring Plugins: Error constructing plugin: class ghidra.feature.vt.gui.plugin.VTPlugin  
2019-03-15 23:41:28 ERROR (LoadJob) Unexpected Exception: null java.lang.NullPointerException
	at ghidra.feature.vt.gui.provider.matchtable.VTMatchTableModel.getMatchCount(VTMatchTableModel.java:103)
	at ghidra.feature.vt.gui.provider.matchtable.VTMatchTableModel.doLoad(VTMatchTableModel.java:87)
	at docking.widgets.table.threaded.ThreadedTableModel.load(ThreadedTableModel.java:173)
	at docking.widgets.table.threaded.TableUpdateJob.loadData(TableUpdateJob.java:355)
	at docking.widgets.table.threaded.TableUpdateJob.processState(TableUpdateJob.java:328)
	at docking.widgets.table.threaded.TableUpdateJob.run(TableUpdateJob.java:129)
	at docking.widgets.table.threaded.ThreadedTableModelUpdateMgr$ThreadRunnable.run(ThreadedTableModelUpdateMgr.java:401)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Environment:**
 - OS: Windows 10
 - Java Version: 11.0.2
 - Ghidra Version: 9.0
- OS region: Polish (Poland)

**Comment by szymski** [comment]
Changing the region in OS settings to English (United States) seems to fix the problem.

**Comment by ryanmkurtz** [comment]
This exception will be fixed in the next release.
