### ISSUE TITLE
commit introducing unexpected exception, 0d2df489ced76bc890d884564199735754e3bf7c

### ISSUE THREAD

**Issue by binjo** [NationalSecurityAgency/ghidra#2093]
**Describe the bug**
It appears this [commit](https://github.com/NationalSecurityAgency/ghidra/commit/0d2df489ced76bc890d884564199735754e3bf7c) introduce following exceptions which prevents opening the codebrowser window, might be related to refactoring of "namespaceStrategy" options?

2020-07-14 12:09:51 ERROR (PluginUtils) Unexpected Exception: class java.lang.Boolean cannot be cast to class java.lang.Enum (java.lang.Boolean and java.lang.Enum are in module java.base of loader 'bootstrap') java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.lang.Enum (java.lang.Boolean and java.lang.Enum are in module java.base of loader 'bootstrap')
	at ghidra.framework.options.AbstractOptions.getEnum(AbstractOptions.java:378)
	at ghidra.app.decompiler.DecompileOptions.grabFromToolAndProgram(DecompileOptions.java:443)
	at ghidra.app.decompiler.DecompileOptions.registerOptions(DecompileOptions.java:610)
	at ghidra.app.plugin.core.decompile.DecompilerProvider.initializeDecompilerOptions(DecompilerProvider.java:712)
	at ghidra.app.plugin.core.decompile.DecompilerProvider.<init>(DecompilerProvider.java:150)
	at ghidra.app.plugin.core.decompile.PrimaryDecompilerProvider.<init>(PrimaryDecompilerProvider.java:21)
	at ghidra.app.plugin.core.decompile.DecompilePlugin.<init>(DecompilePlugin.java:83)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at ghidra.framework.plugintool.util.PluginUtils.instantiatePlugin(PluginUtils.java:184)
	at ghidra.framework.plugintool.PluginManager.addPlugins(PluginManager.java:100)
	at ghidra.framework.plugintool.PluginManager.restorePluginsFromXml(PluginManager.java:271)
	at ghidra.framework.plugintool.PluginTool.restoreFromXml(PluginTool.java:561)
	at ghidra.framework.plugintool.PluginTool.<init>(PluginTool.java:138)
	at ghidra.framework.project.tool.GhidraTool.<init>(GhidraTool.java:81)
	at ghidra.framework.project.tool.GhidraToolTemplate.createTool(GhidraToolTemplate.java:215)
	at ghidra.framework.project.tool.ToolManagerImpl.getTool(ToolManagerImpl.java:661)
	at ghidra.framework.project.tool.WorkspaceImpl.runTool(WorkspaceImpl.java:77)
	at ghidra.framework.main.ToolButton$2.end(ToolButton.java:624)
	at ghidra.framework.main.ZoomImageRunner$1.end(ZoomImageRunner.java:54)
	at org.jdesktop.animation.timing.Animator.end(Animator.java:755)
	at org.jdesktop.animation.timing.Animator.stop(Animator.java:660)
	at org.jdesktop.animation.timing.Animator.timingEvent(Animator.java:732)
	at org.jdesktop.animation.timing.Animator.access$200(Animator.java:75)
	at org.jdesktop.animation.timing.Animator$TimerTarget.actionPerformed(Animator.java:1041)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
 
2020-07-14 12:09:51 ERROR (SwingExceptionHandler) Error: Uncaught Exception!  java.lang.NullPointerException
	at ghidra.app.plugin.core.decompile.DecompilePlugin.serviceAdded(DecompilePlugin.java:275)
	at ghidra.framework.plugintool.mgr.ServiceManager.notifyServiceAdded(ServiceManager.java:89)
	at ghidra.framework.plugintool.mgr.ServiceManager.setServiceAddedNotificationsOn(ServiceManager.java:80)
	at ghidra.framework.plugintool.PluginManager.addPlugins(PluginManager.java:201)
	at ghidra.framework.plugintool.PluginManager.addPlugins(PluginManager.java:111)
	at ghidra.framework.plugintool.PluginManager.restorePluginsFromXml(PluginManager.java:271)
	at ghidra.framework.plugintool.PluginTool.restoreFromXml(PluginTool.java:561)
	at ghidra.framework.plugintool.PluginTool.<init>(PluginTool.java:138)
	at ghidra.framework.project.tool.GhidraTool.<init>(GhidraTool.java:81)
	at ghidra.framework.project.tool.GhidraToolTemplate.createTool(GhidraToolTemplate.java:215)
	at ghidra.framework.project.tool.ToolManagerImpl.getTool(ToolManagerImpl.java:661)
	at ghidra.framework.project.tool.WorkspaceImpl.runTool(WorkspaceImpl.java:77)
	at ghidra.framework.main.ToolButton$2.end(ToolButton.java:624)
	at ghidra.framework.main.ZoomImageRunner$1.end(ZoomImageRunner.java:54)
	at org.jdesktop.animation.timing.Animator.end(Animator.java:755)
	at org.jdesktop.animation.timing.Animator.stop(Animator.java:660)
	at org.jdesktop.animation.timing.Animator.timingEvent(Animator.java:732)
	at org.jdesktop.animation.timing.Animator.access$200(Animator.java:75)
	at org.jdesktop.animation.timing.Animator$TimerTarget.actionPerformed(Animator.java:1041)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**To Reproduce**
1. git reset --hard 0d2df48
2. gradle buildGhidra
3. open existing project using new build, and open/import file

**Expected behavior**
Open analysis window without error.

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Mac OS X 10.15.5 x86_64
 - Java Version: 14.0.1
 - Ghidra Version: 9.2-dev

**Comment by astrelsky** [comment]
What sleigh language is the file using?

**Comment by binjo** [comment]
Windows PE file, you may try load this one: d8933063e264bd659a943acb6ba1f13a
I tried another time, it looks opening existing project will throw these two exceptions:
```
2020-07-15 08:58:13 INFO  (FileActionManager) Opened project: dev_test  
2020-07-15 08:58:16 ERROR (PluginUtils) Unexpected Exception: class java.lang.Boolean cannot be cast to class java.lang.Enum (java.lang.Boolean and java.lang.Enum are in module java.base of loader 'bootstrap') java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.lang.Enum (java.lang.Boolean and java.lang.Enum are in module java.base of loader 'bootstrap')
	at ghidra.framework.options.AbstractOptions.getEnum(AbstractOptions.java:378)
	at ghidra.app.decompiler.DecompileOptions.grabFromToolAndProgram(DecompileOptions.java:443)

2020-07-15 08:58:16 ERROR (SwingExceptionHandler) Error: Uncaught Exception!  java.lang.NullPointerException
	at ghidra.app.plugin.core.decompile.DecompilePlugin.serviceAdded(DecompilePlugin.java:275)
```

**Comment by astrelsky** [comment]
I cannot reproduce this.

**Comment by ghidra1** [comment]
Option class was changed and existing saved value in incompatible.  Code fixed to revert to default option value when this occurs.
