### ISSUE TITLE
Function Graph randomly freezes Ghidra

### ISSUE THREAD

**Issue by tomalla5120x** [NationalSecurityAgency/ghidra#2114]
**Describe the bug**
Occasionally when using the Function Graph window it freezes entire Ghidra and the CPU usage of a single core of my processor stays at 100%. Seems like it's stuck busy in an infinite loop of sorts. All window frames are responsive, just not their contents - you can freely move all the opened windows but you are unable to interact with contained controls. I believe it occurs randomly when panning the view, but I can't bet my head on it.

In the "attachments" section below there are three thread stack dumps (`jstack <pid>`) I've managed to collect during each freeze (2020-07-03, 2020-07-04 and 2020-07-18). They all seem to point to the same single function "pointCrossings", related to graph rendering. Here's the sample of the call stack:

```
"AWT-EventQueue-0" #21 prio=6 os_prio=0 cpu=779131.39ms elapsed=50531.20s tid=0x0000000024104800 nid=0x1a3c runnable  [0x0000000026b4c000]
   java.lang.Thread.State: RUNNABLE
        at java.awt.geom.Path2D$Double.pointCrossings(java.desktop@12.0.1/Path2D.java:1338)
        at java.awt.geom.Path2D.contains(java.desktop@12.0.1/Path2D.java:2159)
        at java.awt.geom.Path2D.contains(java.desktop@12.0.1/Path2D.java:2175)
        at edu.uci.ics.jung.visualization.renderers.BasicEdgeArrowRenderingSupport.getLastOutsideSegment(BasicEdgeArrowRenderingSupport.java:144)
        at edu.uci.ics.jung.visualization.renderers.BasicEdgeArrowRenderingSupport.getArrowTransform(BasicEdgeArrowRenderingSupport.java:85)
        at edu.uci.ics.jung.visualization.renderers.BasicEdgeArrowRenderingSupport.getArrowTransform(BasicEdgeArrowRenderingSupport.java:39)
        at ghidra.graph.viewer.edge.VisualEdgeRenderer.drawSimpleEdge(VisualEdgeRenderer.java:341)
        at ghidra.graph.viewer.edge.VisualEdgeRenderer.drawSimpleEdge(VisualEdgeRenderer.java:81)
        at edu.uci.ics.jung.visualization.renderers.BasicEdgeRenderer.paintEdge(BasicEdgeRenderer.java:62)
        at edu.uci.ics.jung.visualization.renderers.BasicRenderer.renderEdge(BasicRenderer.java:78)
        at ghidra.graph.viewer.renderer.VisualGraphRenderer.mimickSuperPaintingWithoutPaintingSelectedVertices(VisualGraphRenderer.java:76)
        at ghidra.graph.viewer.renderer.VisualGraphRenderer.render(VisualGraphRenderer.java:58)
        at edu.uci.ics.jung.visualization.BasicVisualizationServer.renderGraph(BasicVisualizationServer.java:346)
        at edu.uci.ics.jung.visualization.BasicVisualizationServer.paintComponent(BasicVisualizationServer.java:301)
        at ghidra.graph.viewer.GraphViewer.paintComponent(GraphViewer.java:251)
        at javax.swing.JComponent.paint(java.desktop@12.0.1/JComponent.java:1074)
        at javax.swing.JComponent.paintChildren(java.desktop@12.0.1/JComponent.java:907)
        - locked <0x0000000080bbfe90> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(java.desktop@12.0.1/JComponent.java:1083)
        at javax.swing.JLayeredPane.paint(java.desktop@12.0.1/JLayeredPane.java:590)
        at javax.swing.JComponent.paintChildren(java.desktop@12.0.1/JComponent.java:907)
        - locked <0x0000000080bbfe90> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(java.desktop@12.0.1/JComponent.java:1083)
        at javax.swing.JComponent.paintChildren(java.desktop@12.0.1/JComponent.java:907)
        - locked <0x0000000080bbfe90> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(java.desktop@12.0.1/JComponent.java:1083)
        at javax.swing.JComponent.paintChildren(java.desktop@12.0.1/JComponent.java:907)
        - locked <0x0000000080bbfe90> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(java.desktop@12.0.1/JComponent.java:1083)
        at javax.swing.JComponent.paintChildren(java.desktop@12.0.1/JComponent.java:907)
        - locked <0x0000000080bbfe90> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(java.desktop@12.0.1/JComponent.java:1083)
        at javax.swing.JComponent.paintChildren(java.desktop@12.0.1/JComponent.java:907)
        - locked <0x0000000080bbfe90> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(java.desktop@12.0.1/JComponent.java:1083)
        at javax.swing.JComponent.paintChildren(java.desktop@12.0.1/JComponent.java:907)
        - locked <0x0000000080bbfe90> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(java.desktop@12.0.1/JComponent.java:1083)
        at javax.swing.JComponent.paintChildren(java.desktop@12.0.1/JComponent.java:907)
        - locked <0x0000000080bbfe90> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(java.desktop@12.0.1/JComponent.java:1083)
        at javax.swing.JComponent.paintChildren(java.desktop@12.0.1/JComponent.java:907)
        - locked <0x0000000080bbfe90> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(java.desktop@12.0.1/JComponent.java:1083)
        at javax.swing.JLayeredPane.paint(java.desktop@12.0.1/JLayeredPane.java:590)
        at javax.swing.JComponent.paintChildren(java.desktop@12.0.1/JComponent.java:907)
        - locked <0x0000000080bbfe90> (a java.awt.Component$AWTTreeLock)
        at javax.swing.JComponent.paint(java.desktop@12.0.1/JComponent.java:1083)
        at javax.swing.JComponent.paintToOffscreen(java.desktop@12.0.1/JComponent.java:5255)
        at javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(java.desktop@12.0.1/RepaintManager.java:1643)
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(java.desktop@12.0.1/RepaintManager.java:1618)
        at javax.swing.RepaintManager$PaintManager.paint(java.desktop@12.0.1/RepaintManager.java:1556)
        at javax.swing.RepaintManager.paint(java.desktop@12.0.1/RepaintManager.java:1323)
        at javax.swing.JComponent._paintImmediately(java.desktop@12.0.1/JComponent.java:5203)
        at javax.swing.JComponent.paintImmediately(java.desktop@12.0.1/JComponent.java:5013)
        at javax.swing.RepaintManager$4.run(java.desktop@12.0.1/RepaintManager.java:865)
        at javax.swing.RepaintManager$4.run(java.desktop@12.0.1/RepaintManager.java:848)
        at java.security.AccessController.executePrivileged(java.base@12.0.1/AccessController.java:750)
        at java.security.AccessController.doPrivileged(java.base@12.0.1/AccessController.java:389)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@12.0.1/ProtectionDomain.java:85)
        at javax.swing.RepaintManager.paintDirtyRegions(java.desktop@12.0.1/RepaintManager.java:848)
        at javax.swing.RepaintManager.paintDirtyRegions(java.desktop@12.0.1/RepaintManager.java:823)
        at javax.swing.RepaintManager.prePaintDirtyRegions(java.desktop@12.0.1/RepaintManager.java:772)
        at javax.swing.RepaintManager$ProcessingRunnable.run(java.desktop@12.0.1/RepaintManager.java:1884)
        at java.awt.event.InvocationEvent.dispatch(java.desktop@12.0.1/InvocationEvent.java:313)
        at java.awt.EventQueue.dispatchEventImpl(java.desktop@12.0.1/EventQueue.java:770)
        at java.awt.EventQueue$4.run(java.desktop@12.0.1/EventQueue.java:721)
        at java.awt.EventQueue$4.run(java.desktop@12.0.1/EventQueue.java:715)
        at java.security.AccessController.executePrivileged(java.base@12.0.1/AccessController.java:750)
        at java.security.AccessController.doPrivileged(java.base@12.0.1/AccessController.java:389)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@12.0.1/ProtectionDomain.java:85)
        at java.awt.EventQueue.dispatchEvent(java.desktop@12.0.1/EventQueue.java:740)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@12.0.1/EventDispatchThread.java:203)
        at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@12.0.1/EventDispatchThread.java:124)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@12.0.1/EventDispatchThread.java:113)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@12.0.1/EventDispatchThread.java:109)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@12.0.1/EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.run(java.desktop@12.0.1/EventDispatchThread.java:90)
```

**To Reproduce**
It occurs randomly when using Function Graph (probably when panning the view).

**Attachments**
Java thread stack dumps, collected with the "`jstack <pid>`" utility:
[javadump.txt](https://github.com/NationalSecurityAgency/ghidra/files/4941498/javadump.txt)
[javadump2.txt](https://github.com/NationalSecurityAgency/ghidra/files/4941499/javadump2.txt)
[javadump3.txt](https://github.com/NationalSecurityAgency/ghidra/files/4941500/javadump3.txt)

**Environment**
 - OS: Windows 7
 - Java Version: 12.0.1
 - Ghidra Version: 9.1.2

**Comment by dragonmacher** [comment]
The traces that you have provided imply that the issue is function that has so many blocks, it cannot be painted without locking the UI.   **It would be helpful to verify whether it is the same set of functions that cause the issue, or if it is indeed sporadic and independent of the function being rendered.**

(Also, I see that you are using Java 12.  We have not tested Ghidra under Java 12.)

**Comment by pabx06** [comment]
I have the same issue after disassembling a very large state machine in ARM.  But Was able to have a graph in IDA but way to large to navigate easily ...

**Comment by dragonmacher** [comment]
> I have the same issue after disassembling a very large state machine in ARM. But Was able to have a graph in IDA but way to large to navigate easily ...

This is a good point to bring up.   For a graph to lock-up Ghidra, it is usually so large that it makes the Function Graph useless, having too many nodes with which to interact and understand.   That being said, if this happens frequently, then Ghidra probably needs to have a size cutoff that prevents graph rendering when the function is too large.   We would like to know the size/makeup of the functions being rendered in the case(s) where the UI becomes unresponsive.

**Comment by tomalla5120x** [comment]
@dragonmacher 
Thank you for your insight. The next time Ghidra freezes on me I will take note of the function I was inspecting at that moment.

However here's what my gut tells me: the functions I was then inspecting may not have been necessarily large and the freeze happened only after some time of inspection when panning. It didn't seem consistent - moreover when coming back to the same function the freeze most likely wouldn't happen again.

I will verify it the next time it happens.

**Comment by pabx06** [comment]
1878 nodes in IDA pro.
today graphing did worked. however it didnt produce as much nodes as in IDA. may be because previously dissassembly was partial and bad.

IDA: 
![image](https://user-images.githubusercontent.com/4013370/88175219-db1a1f80-cc25-11ea-9568-d1f3601301e3.png)

ghidra:
Exception while decompiling 40cba0b8: Decompiler results exceeded payload limit of 50 MBytes
pretty sluggish to zoom in and blocks much longer and 
![image](https://user-images.githubusercontent.com/4013370/88175388-14528f80-cc26-11ea-985b-bc51126ba8cb.png)

**Comment by dragonmacher** [comment]
That is quite a beautiful graph.  Ghidra's version implies, as you said, that the code was not correctly recovered.

**Comment by tomalla5120x** [comment]
Below is the screenshot of the Function Graph window the moment it froze.

As you can see on the satellite view the function is not big by any means. I was inspecting it and moving some nodes around. The froze happened when panning the whole view. Obviously restarting Ghidra and getting back to this very function didn't trigger the freeze ever again.

![image](https://user-images.githubusercontent.com/15930205/88328311-890df280-cd28-11ea-8fb2-191a983987a2.png)

**Comment by dragonmacher** [comment]
Thanks for the info.   It is helpful to see that it is not the size of the function in this case causing the issue.

The various stack traces you provided all seem to get stuck in the same spot.  This implies there is a bug in the library that we call that allows the code to get stuck in an infinite loop.  Since this is a 3rd-party library, we will have to devise a work-around to prevent this from happening.

**Comment by tomnelson** [comment]
I'm the author (many years ago) of the code in that 3rd party library that computes the arrow positions. I've learned since then that computing the arrow positions while the graph is being manipulated (zooming/panning) is not a good use of compute cycles. 
I would prefer to  draw arrows only when the graph elements are not being transformed, switching the arrows off/on as needed.
