### ISSUE TITLE
concurrency exception in ghidraScript

### ISSUE THREAD

**Issue by pabx06** [NationalSecurityAgency/ghidra#2115]
**Describe the bug**
A clear and concise description of the bug.
i am not sure but it seems that _CreateFunctionCmd_ class asyncly triger some analyzer.
i wonder if CodeAnalysis can be disabled on _CreateFunctionCmd_ like  _DisassembleCommand.enableCodeAnalysis(false)_
```
ERROR caught exception (ArmAnalyzer) java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at generic.concurrent.QResult.<init>(QResult.java:40)
	at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:77)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.NullPointerException
	at ghidra.program.util.RegisterValueStore.getValue(RegisterValueStore.java:242)
	at ghidra.program.util.AbstractStoredProgramContext.getRegisterValue(AbstractStoredProgramContext.java:151)
	at ghidra.program.util.AbstractStoredProgramContext.getDisassemblyContext(AbstractStoredProgramContext.java:340)
	at ghidra.program.disassemble.Disassembler$DisassemblerProgramContext.getDisassemblyContext(Disassembler.java:1668)
	at ghidra.program.disassemble.DisassemblerContextImpl.getNextContextInFlow(DisassemblerContextImpl.java:511)
	at ghidra.program.disassemble.DisassemblerContextImpl.flowStart(DisassemblerContextImpl.java:250)
	at ghidra.program.disassemble.DisassemblerContextImpl.flowStart(DisassemblerContextImpl.java:217)
	at ghidra.program.disassemble.Disassembler.disassembleNextInstructionSet(Disassembler.java:658)
	at ghidra.program.disassemble.Disassembler.disassemble(Disassembler.java:602)
	at ghidra.program.disassemble.Disassembler.disassemble(Disassembler.java:514)
	at ghidra.program.disassemble.Disassembler.disassemble(Disassembler.java:499)
	at ghidra.app.plugin.core.analysis.ArmAnalyzer.doArmThumbDisassembly(ArmAnalyzer.java:818)
	at ghidra.app.plugin.core.analysis.ArmAnalyzer$1.evaluateReference(ArmAnalyzer.java:190)
	at ghidra.program.util.SymbolicPropogator.makeReference(SymbolicPropogator.java:2264)
	at ghidra.program.util.SymbolicPropogator.applyPcode(SymbolicPropogator.java:888)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:491)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:389)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:188)
	at ghidra.app.plugin.core.analysis.ArmAnalyzer.flowConstants(ArmAnalyzer.java:216)
	at ghidra.app.plugin.core.analysis.ArmAnalyzer.flowConstants(ArmAnalyzer.java:42)
	at ghidra.app.plugin.core.analysis.ConstantPropagationAnalyzer.analyzeLocation(ConstantPropagationAnalyzer.java:383)
	at ghidra.app.plugin.core.analysis.ConstantPropagationAnalyzer$1.process(ConstantPropagationAnalyzer.java:274)
	at ghidra.app.plugin.core.analysis.ConstantPropagationAnalyzer$1.process(ConstantPropagationAnalyzer.java:263)
	at generic.concurrent.ConcurrentQ$CallbackCallable.call(ConcurrentQ.java:655)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:75)
	... 3 more
 
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at generic.concurrent.QResult.<init>(QResult.java:40)
	at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:77)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.NullPointerException
	at ghidra.program.util.RegisterValueStore.getValue(RegisterValueStore.java:242)
	at ghidra.program.util.AbstractStoredProgramContext.getRegisterValue(AbstractStoredProgramContext.java:151)
	at ghidra.program.util.AbstractStoredProgramContext.getDisassemblyContext(AbstractStoredProgramContext.java:340)
	at ghidra.program.disassemble.Disassembler$DisassemblerProgramContext.getDisassemblyContext(Disassembler.java:1668)
	at ghidra.program.disassemble.DisassemblerContextImpl.getNextContextInFlow(DisassemblerContextImpl.java:511)
	at ghidra.program.disassemble.DisassemblerContextImpl.flowStart(DisassemblerContextImpl.java:250)
	at ghidra.program.disassemble.DisassemblerContextImpl.flowStart(DisassemblerContextImpl.java:217)
	at ghidra.program.disassemble.Disassembler.disassembleNextInstructionSet(Disassembler.java:658)
	at ghidra.program.disassemble.Disassembler.disassemble(Disassembler.java:602)
	at ghidra.program.disassemble.Disassembler.disassemble(Disassembler.java:514)
	at ghidra.program.disassemble.Disassembler.disassemble(Disassembler.java:499)
	at ghidra.app.plugin.core.analysis.ArmAnalyzer.doArmThumbDisassembly(ArmAnalyzer.java:818)
	at ghidra.app.plugin.core.analysis.ArmAnalyzer$1.evaluateReference(ArmAnalyzer.java:190)
	at ghidra.program.util.SymbolicPropogator.makeReference(SymbolicPropogator.java:2264)
	at ghidra.program.util.SymbolicPropogator.applyPcode(SymbolicPropogator.java:888)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:491)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:389)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:188)
	at ghidra.app.plugin.core.analysis.ArmAnalyzer.flowConstants(ArmAnalyzer.java:216)
	at ghidra.app.plugin.core.analysis.ArmAnalyzer.flowConstants(ArmAnalyzer.java:42)
	at ghidra.app.plugin.core.analysis.ConstantPropagationAnalyzer.analyzeLocation(ConstantPropagationAnalyzer.java:383)
	at ghidra.app.plugin.core.analysis.ConstantPropagationAnalyzer$1.process(ConstantPropagationAnalyzer.java:274)
	at ghidra.app.plugin.core.analysis.ConstantPropagationAnalyzer$1.process(ConstantPropagationAnalyzer.java:263)
	at generic.concurrent.ConcurrentQ$CallbackCallable.call(ConcurrentQ.java:655)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:75)
	... 3 more
```

**Screenshots**
![image](https://user-images.githubusercontent.com/4013370/87867592-dee04480-c98e-11ea-9d26-d1187e344ee3.png)
![image](https://user-images.githubusercontent.com/4013370/87867602-f28bab00-c98e-11ea-8c30-ae4b9ae40fde.png)

**Attachments**
```

public class CreateFunctionScript extends GhidraScript {

    private static final String IDA_REGISTER_THUMBMODE_TXT = "/home/user/thumbmode.txt";
	private static final String FUN_POS_TXT = "/home/user/fun.-pos.txt";
	private FlatProgramAPI api;
	public void run() throws Exception {
		this.api = new FlatProgramAPI(currentProgram);
		importTMode();
		
		List<String> allLines = Files.readAllLines(Paths.get(FUN_POS_TXT));
    	for(String line:allLines) {
    		String[] data = line.split(":");
    		String name=data[0];
    		String start=data[1];
    		String end=data[2];
    		if(!makefunction(name, api.toAddr(start), api.toAddr(end))) {
    			//break;
    		}
    		if(monitor.isCancelled())
    			break;
    	}	
    }
	
    public boolean makefunction(String name, Address startAddress,Address endAddressExcluded) throws Exception {		
    	
    	AddressSet bodySet = new AddressSet(startAddress, endAddressExcluded.add(-1));
    	
    	AddressSet entries = new AddressSet();
    	entries.add(startAddress);
    	
    	state.setCurrentAddress(startAddress);
    	state.setCurrentSelection(new ProgramSelection(bodySet));
    	setupPlateComment(startAddress, String.format("-------START %s [{@address 0x%s} - {@address 0x%s}]--------", name, startAddress.toString(), endAddressExcluded.add(-1).toString()));
    	setupPlateComment(endAddressExcluded.add(-1), "-------END--------");
    	//Thread.sleep(4000);
    	//ArmDisassembleCommand disassembleCMD = new ArmDisassembleCommand(startAddress, bodySet, true);
    	DisassembleCommand disassembleCMD = new DisassembleCommand(startAddress, bodySet,true);
    	disassembleCMD.enableCodeAnalysis(false);    	
    	boolean disassembledWell = disassembleCMD.applyTo(currentProgram, monitor);    	
    	//Thread.sleep(4000);
    	if(disassembledWell) {
    		CreateFunctionCmd cmd = new CreateFunctionCmd(name, startAddress,bodySet,SourceType.USER_DEFINED);
    		boolean funCreation= cmd.applyTo(currentProgram, monitor);
    		if(!funCreation) {
    			String comment = "function ["+startAddress+" - "+endAddressExcluded.add(-1)+"] disassembled well but fun creation not! :"+cmd.getStatusMsg(); 
    			getCurrentProgram().getBookmarkManager().setBookmark(startAddress, "Function creation failed", "function", comment);
    			println(comment);
    		}
    		return funCreation;
    	}		
		String comment = "function ["+startAddress+" - "+endAddressExcluded.add(-1)+"] not disassembled well!: "+disassembleCMD.getStatusMsg(); 
		getCurrentProgram().getBookmarkManager().setBookmark(startAddress, "Function creation failed", "function", comment);
		println(comment);
		return false;
    }
    
    public void importTMode() throws Exception {
    	Register tmodeReg = getCurrentProgram().getProgramContext().getRegister("TMode");
    	
    	println("export IDA thumb mode register see: https://reverseengineering.stackexchange.com/a/12701/33310");
    	println(tmodeReg.toString());
    	
    	boolean firstLineSkip = true;
    	List<String> allLines = Files.readAllLines(Paths.get(IDA_REGISTER_THUMBMODE_TXT));
    	for(String line:allLines) {
    		String tmp[] = line.split("\t");
    		String start = tmp[0];
    		String end = tmp[1];
    		String value = tmp[3];
    		if(firstLineSkip) {
    			firstLineSkip = false;
    			continue;
    		}

    		SetRegisterCmd cmd = new SetRegisterCmd(tmodeReg, api.toAddr(start), api.toAddr(end).add(-1), new BigInteger(value));
    		if(cmd.applyTo(state.getCurrentProgram())!=true) {
    			String comment = String.format("Tmode Register Not Set Properly start= %s end= %s value= %s", api.toAddr(start).toString(),api.toAddr(end),value);
    			getCurrentProgram().getBookmarkManager().setBookmark(api.toAddr(start), "TMode failed", "Register", comment);
    			setupPlateComment(api.toAddr(start),comment);
    			println(comment);
    			//break;
    		}
    	}    	
    }
    public void setupPlateComment(Address ad, String comment) {
    	String prevComment = api.getPlateComment(ad);
    	String finalComment = comment;
    	if(prevComment!=null) {
    		finalComment = prevComment +"\n" +comment;
    	}
    	 api.setPlateComment(ad, finalComment);
    }

}
```

**Environment (please complete the following information):**
 - OS:  ubuntu 18
 - Java Version:oracle 13
 - Ghidra Version: 9.1.2

**Additional context**

**Comment by pabx06** [comment]
after running this script i had few strange error in the listing:
i dont know if it is related:

**Unable to resolve constructor at 40c69cf8**
i didnt manualy change this offset from code to data:
![image](https://user-images.githubusercontent.com/4013370/87879290-07e1f300-c9ea-11ea-9e6a-8cfe66360862.png)

**Comment by astrelsky** [comment]
I cannot say for sure but it may be related to this

```
private FlatProgramAPI api;
	public void run() throws Exception {
		this.api = new FlatProgramAPI(currentProgram);
        ...
       }
...
```

GhidraScript extends FlatProgramAPI so you do not need the api field. You're using the currentProgram field of a FlatProgramAPI instance to create another FlatProgramAPI which just doesn't make sense.

GhidraScript has many things setup in accordance with the current GhidraState. Using the inherited fields and methods instead of a new FlatProgramAPI's may solve your problem.

**Comment by pabx06** [comment]
thanks very much. it is good to know.
Do you know by chance if DisassembleCommand is supposed to have a side effect contextreg? because it messing up with Register TMode (ranges&values) tuples => and subsequent function disassembly get in unexpected/wrong  TMode

**Comment by astrelsky** [comment]
> thanks very much. it is good to know.
> Do you know by chance if DisassembleCommand is supposed to have a side effect contextreg? because it messing up with Register TMode (ranges&values) tuples => and subsequent function disassembly get in unexpected/wrong TMode

I'm not sure. However there is a `disassemble` convenience method in FlatProgramAPI. Try giving that a shot.

**Comment by dragonmacher** [comment]
@astrelsky is correct in that you do not need to create a new `FlatProgramAPI`.   I cannot see anything else in your script that would produce these exceptions.   I will close this for now.  Let us know if the problem perisists.
