### ISSUE TITLE
Java RMI Error: no such object in table

### ISSUE THREAD

**Issue by moloch--** [NationalSecurityAgency/ghidra#2137]
**Describe the bug**

```
An error occured on the server (foobar.exmaple.com:13100).
no such object in table
java.rmi.NoSuchObjectException: no such object in table
	at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:161)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:209)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:161)
	at com.sun.proxy.$Proxy21.checkCompatibility(Unknown Source)
	at ghidra.framework.client.ServerConnectTask.getGhidraServerHandle(ServerConnectTask.java:171)
	at ghidra.framework.client.ServerConnectTask.getRepositoryServerHandle(ServerConnectTask.java:207)
	at ghidra.framework.client.ServerConnectTask.run(ServerConnectTask.java:72)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: /Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home
JVM Version: Oracle Corporation 13.0.1
OS: Mac OS X 10.15.5 x86_64
Workstation: mbp

```

**To Reproduce**

1. Setup Ghidra server
2. Add a user
3. Attempt to login

**Expected behavior**
Login is successful.

**Environment (please complete the following information):**
 - OS: Ubuntu/Docker 
 - Ghidra Version: 9.1.2

```
ghidra_1  | YAJSW: yajsw-stable-12.12
ghidra_1  | OS   : Linux/4.15.0-1065-aws/amd64
ghidra_1  | JVM  : N/A/11.0.8//usr/local/openjdk-11/64
```

**Comment by ghidra1** [comment]
I suspect the is a local configuration issue as this does not occur with a properly configured Ghidra Server and network with Java 11.  

You may want to use a supported Java version (11.x) as I see you are using version 13.x.

**Comment by larsw** [comment]
Hi,

I'm experiencing the same problem when connecting from a Ghidra 10.0.4 client against a Ghidra 10.0.4 server, both running under Ubuntu 20.04 / OpenJDK 11 (11.0.11).

Client says:

```
no such object in table
java.rmi.NoSuchObjectException: no such object in table
	at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:217)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:162)
	at com.sun.proxy.$Proxy29.checkCompatibility(Unknown Source)
	at ghidra.framework.client.ServerConnectTask.getGhidraServerHandle(ServerConnectTask.java:171)
	at ghidra.framework.client.ServerConnectTask.getRepositoryServerHandle(ServerConnectTask.java:207)
	at ghidra.framework.client.ServerConnectTask.run(ServerConnectTask.java:72)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

---------------------------------------------------
Build Date: 2021-Sep-28 1538 EDT
Ghidra Version: 10.0.4
Java Home: /usr/lib/jvm/java-11-openjdk-amd64
JVM Version: Ubuntu 11.0.11
OS: Linux 5.11.0-38-generic amd64
Workstation: my-workstation
```

server.log
```
Running Ghidra Server...
YAJSW: yajsw-stable-12.12
OS   : Linux/5.11.0-1020-azure/amd64
JVM  : Ubuntu/11.0.11//usr/lib/jvm/java-11-openjdk-amd64/64
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Features/GhidraServer/data/yajsw-stable-12.12/./lib/extended/groovy/groovy-all-2.4.11.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Nov 10, 2021 4:56:10 PM org.apache.commons.vfs2.VfsLog info
INFO: Using "/tmp/vfs_cache" as temporary files store.
wrapper|YAJSW: yajsw-stable-12.12
wrapper|OS   : Linux/5.11.0-1020-azure/amd64
wrapper|JVM  : Ubuntu/11.0.11//usr/lib/jvm/java-11-openjdk-amd64/64
system.env 32
env result 32
wrapper|exec:/usr/lib/jvm/java-11-openjdk-amd64/bin/java -classpath /opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Features/GhidraServer/data/yajsw-stable-12.12/wrapperApp.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Features/GhidraServer/lib/GhidraServer.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/FileSystem/lib/FileSystem.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/DB/lib/DB.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Docking/lib/Docking.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/Generic.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/FileSystem/lib/ganymed-ssh2-262.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Utility/lib/Utility.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/cglib-nodep-2.2.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/guava-19.0.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/jdom-legacy-1.1.3.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/log4j-core-2.12.1.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/log4j-api-2.12.1.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/commons-collections4-4.1.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/commons-lang3-3.9.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/commons-text-1.6.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/commons-io-2.6.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/gson-2.8.6.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Docking/lib/timingframework-1.0.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Docking/lib/javahelp-2.0.05.jar -Djava.net.preferIPv4Stack=true -DApplicationRollingFileAppender.maxBackupIndex=10 -Dclasspath_frag=/opt/ghidra/ghidra_10.0.4_PUBLIC/server/../Ghidra/Features/GhidraServer/data/classpath.frag -Dghidra.tls.server.protocols=TLSv1.2;TLSv1.3 -Ddb.buffers.DataBuffer.compressedOutput=true -Djava.library.path=/opt/ghidra/ghidra_10.0.4_PUBLIC/server/../Ghidra/Features/GhidraServer/os/linux64 -Xms396m -Xmx768m -Djava=/usr/lib/jvm/java-11-openjdk-amd64/bin/java -Dos_dir=/opt/ghidra/ghidra_10.0.4_PUBLIC/server/../Ghidra/Features/GhidraServer/os/linux64 -Dghidra_home=/opt/ghidra/ghidra_10.0.4_PUBLIC/server/.. -Dwrapper.port=15003 -Dwrapper.key=-3670174783828669400 -Dwrapper.tmp.path=/tmp -Djna_tmpdir=/tmp -Dwrapper.config=/opt/ghidra/ghidra_10.0.4_PUBLIC/server/server.conf org.rzo.yajsw.app.WrapperJVMMain 
wrapper|posix_spawn pid 64631
post start true null
setting fd
wrapper|started process 64631
wrapper|started process with pid 64631
64631/0|/usr/lib/jvm/java-11-openjdk-amd64/bin/java
64631/0|-classpath
64631/0|/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Features/GhidraServer/data/yajsw-stable-12.12/wrapperApp.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Features/GhidraServer/lib/GhidraServer.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/FileSystem/lib/FileSystem.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/DB/lib/DB.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Docking/lib/Docking.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/Generic.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/FileSystem/lib/ganymed-ssh2-262.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Utility/lib/Utility.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/cglib-nodep-2.2.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/guava-19.0.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/jdom-legacy-1.1.3.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/log4j-core-2.12.1.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/log4j-api-2.12.1.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/commons-collections4-4.1.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/commons-lang3-3.9.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/commons-text-1.6.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/commons-io-2.6.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/gson-2.8.6.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Docking/lib/timingframework-1.0.jar:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Docking/lib/javahelp-2.0.05.jar
64631/0|-Djava.net.preferIPv4Stack=true
64631/0|-DApplicationRollingFileAppender.maxBackupIndex=10
64631/0|-Dclasspath_frag=/opt/ghidra/ghidra_10.0.4_PUBLIC/server/../Ghidra/Features/GhidraServer/data/classpath.frag
64631/0|-Dghidra.tls.server.protocols=TLSv1.2;TLSv1.3
64631/0|-Ddb.buffers.DataBuffer.compressedOutput=true
64631/0|-Djava.library.path=/opt/ghidra/ghidra_10.0.4_PUBLIC/server/../Ghidra/Features/GhidraServer/os/linux64
64631/0|-Xms396m
64631/0|-Xmx768m
64631/0|-Djava=/usr/lib/jvm/java-11-openjdk-amd64/bin/java
64631/0|-Dos_dir=/opt/ghidra/ghidra_10.0.4_PUBLIC/server/../Ghidra/Features/GhidraServer/os/linux64
64631/0|-Dghidra_home=/opt/ghidra/ghidra_10.0.4_PUBLIC/server/..
64631/0|-Dwrapper.port=15003
64631/0|-Dwrapper.key=-3670174783828669400
64631/0|-Dwrapper.tmp.path=/tmp
64631/0|-Djna_tmpdir=/tmp
64631/0|-Dwrapper.config=/opt/ghidra/ghidra_10.0.4_PUBLIC/server/server.conf
64631/0|org.rzo.yajsw.app.WrapperJVMMain
64631/0|java.lang.NullPointerException
64631/0|	at java.base/java.io.File.<init>(File.java:278)
64631/0|	at org.rzo.yajsw.boot.WrapperLoader.getWrapperClasspath(WrapperLoader.java:235)
64631/0|	at org.rzo.yajsw.app.WrapperManagerProxy.getWrapperClassLoader(WrapperManagerProxy.java:101)
64631/0|	at org.rzo.yajsw.app.WrapperManagerProxy.getWrapperManager(WrapperManagerProxy.java:44)
64631/0|	at org.rzo.yajsw.app.AbstractWrapperJVMMain$1.run(AbstractWrapperJVMMain.java:64)
64631/0|	at java.base/java.security.AccessController.doPrivileged(Native Method)
64631/0|	at org.rzo.yajsw.app.AbstractWrapperJVMMain.preExecute(AbstractWrapperJVMMain.java:56)
64631/0|	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:41)
64631/0|YAJSW: yajsw-stable-12.12
64631/0|OS   : Linux/5.11.0-1020-azure/amd64
64631/0|JVM  : Ubuntu/11.0.11//usr/lib/jvm/java-11-openjdk-amd64/64
64631/0|WARNING: An illegal reflective access operation has occurred
64631/0|WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Features/GhidraServer/data/yajsw-stable-12.12/./lib/extended/groovy/groovy-all-2.4.11.jar) to method java.lang.Object.finalize()
64631/0|WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
64631/0|WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
64631/0|WARNING: All illegal access operations will be denied in a future release
64631/0|[INFO] StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
64631/0|INFO  Using log config file: jar:file:/opt/ghidra/ghidra_10.0.4_PUBLIC/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)  
64631/0|INFO  Using log file: /data/ghidra_repos/server.log (LoggingInitialization)  
64631/0|INFO  Initializing SSL Context (SSLContextInitializer)  
64631/0|INFO  Initializing Random Number Generator... (SecureRandomFactory)  
64631/0|INFO  Random Number Generator initialization complete: NativePRNGNonBlocking (SecureRandomFactory)  
64631/0|INFO  Trust manager disabled, cacerts have not been set (ApplicationTrustManagerFactory)  
64631/0|INFO  Using self-signed certificate: CN=GhidraServer (ApplicationKeyManager)  
64631/0|INFO     defaultsigkey: GhidraServer, issued by GhidraServer, S/N 1569d5fd, expires Fri Nov 10 16:56:14 UTC 2023 (ApplicationKeyStore)  
64631/0|INFO  Ghidra Server 10.0.4 (GhidraServer)  
64631/0|INFO     Server remote access address: 0.0.0.0 (GhidraServer)  
64631/0|INFO     Server listening on interface: 0.0.0.0 (GhidraServer)  
64631/0|INFO     RMI Registry port: 13100 (GhidraServer)  
64631/0|INFO     RMI SSL port: 13101 (GhidraServer)  
64631/0|INFO     Block Stream port: 13102 (GhidraServer)  
64631/0|INFO     Block Stream compression: enabled (GhidraServer)  
64631/0|INFO     Root: /data/ghidra_repos (GhidraServer)  
64631/0|INFO     Auth: Password File (GhidraServer)  
64631/0|INFO     Prompt for user ID: yes (GhidraServer)  
64631/0|INFO     Anonymous server access: disabled (GhidraServer)  
64631/0|INFO     Enabled protocols: TLSv1.2;TLSv1.3 (GhidraServer)  
64631/0|INFO  root starting Ghidra Server... (GhidraServer)  
64631/0|INFO  Instantiating Repository Manager for /data/ghidra_repos (RepositoryManager)  
64631/0|INFO  Instantiating User Manager (w/password management) (UserManager)  
64631/0|INFO  User file contains 1 entries (UserManager)  
64631/0|INFO  Known Users: (UserManager)  
64631/0|INFO     larsw (UserManager)  
64631/0|INFO  Known Repositories: (RepositoryManager)  
64631/0|INFO     <none> (RepositoryManager)  
64631/0|INFO  Starting Block Stream Server... (BlockStreamServer)  
64631/0|INFO  Registering Ghidra Server... (GhidraServer)  
64631/0|INFO  Registered Ghidra Server. (GhidraServer)  
```



--larsw

**Comment by larsw** [comment]
Update: strange this is, if I run both the server and client on the same machine, it works ok (same server.conf file).

Both machines running:
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```

**Comment by ghidra1** [comment]
Your log showing the following is very suspicious.  Could you please attached your server.conf file.
```
Server remote access address: 0.0.0.0 (GhidraServer)  
Server listening on interface: 0.0.0.0 (GhidraServer)  
```
