### ISSUE TITLE
ClassNotFoundException in Headless mode w/ jdk11

### ISSUE THREAD

**Issue by hedgeberg** [NationalSecurityAgency/ghidra#2187]
**Describe the bug**
Attempting to run a headless mode script results in the following backtrace:
```
ERROR REPORT SCRIPT ERROR: DWARF_Extractor_custom.java :  (HeadlessAnalyzer) java.lang.ClassNotFoundException: 
        at ghidra.app.script.JavaScriptProvider.getScriptInstance(JavaScriptProvider.java:101)
        at ghidra.app.util.headless.HeadlessAnalyzer.runScriptsList(HeadlessAnalyzer.java:877)
        at ghidra.app.util.headless.HeadlessAnalyzer.analyzeProgram(HeadlessAnalyzer.java:958)
        at ghidra.app.util.headless.HeadlessAnalyzer.processFileNoImport(HeadlessAnalyzer.java:1128)
        at ghidra.app.util.headless.HeadlessAnalyzer.processFolderNoImport(HeadlessAnalyzer.java:1294)
        at ghidra.app.util.headless.HeadlessAnalyzer.processNoImport(HeadlessAnalyzer.java:1323)
        at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:440)
        at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:121)
        at ghidra.GhidraLauncher.main(GhidraLauncher.java:82)
Caused by: java.lang.NullPointerException
        at org.jgrapht.graph.AbstractBaseGraph.addVertex(AbstractBaseGraph.java:290)
        at ghidra.app.plugin.core.osgi.BundleHost$BundleDependencyGraph.addFront(BundleHost.java:979)
        at ghidra.app.plugin.core.osgi.BundleHost$BundleDependencyGraph.<init>(BundleHost.java:944)
        at ghidra.app.plugin.core.osgi.BundleHost.activateAll(BundleHost.java:698)
        at ghidra.app.script.JavaScriptProvider.loadClass(JavaScriptProvider.java:116)
        at ghidra.app.script.JavaScriptProvider.getScriptInstance(JavaScriptProvider.java:81)
        ... 8 more
 ```

**To Reproduce**
1. Build newest version of Ghidra Dev
2. Place a .java script that extends HeadlessScript into $USER_HOME/ghidra_scripts
3. `cd` to `$GHIDRA_INSTALL_DIR\support` 
4. run `./analyzeHeadless $USER_HOME/ghidra_work <project_name> -process <binary_name> -preScript <script_name> -noanalysis
5. See error

**Expected behavior**
Script runs in headless mode, as it has on prior builds. 

**Attachments**
I've attached a modified version of the script in question that I'm attempting to use. I don't think it should matter too much but is included in case it becomes relevant.

[DWARF_Extractor_custom.java.txt](https://github.com/NationalSecurityAgency/ghidra/files/5038814/DWARF_Extractor_custom.java.txt)

**Environment (please complete the following information):**
 - OS: Custom Linux build for parallel computing based on kernel 4.14.182
 - Java Version: 11.0.2
 - Ghidra Version: 9.2 DEV, commit 73c5fb1

**Additional context** 
Running the master commit (c1095fe) on a different machine did not produce this issue, so I suspect it's either something to do with this specific kernel, or the setup needed for the computing environment (the filesystem in this environment does not support unix locks, so anything that's run that relies on locks has to be run out of `/tmp`, and I had to also change java's user.home variable to `/tmp/<username>`)

I'm going to try testing an old commit and the most recent commit on this target, as I know that scripting was broken and then subsequently fixed for jdk14, and if the issue is resolved I'll mark this as closed, but since this was with jdk11 I figured it was worth it to make an issue now before I drop into debugging.

**Comment by jpleasu** [comment]
I couldn't reproduce in my more typical linux environment here I've got locks.

Not having locks might cause an issue with Apache Felix, the OSGi framework that Java scripts now runs on.   It keeps a cache under `user.home` (the path assigned is computed wtih `Application.getUserSettingsDirectory()`).

`lslocks` showed me two locks due to Ghidra, the lockfile in the project I had open and `$HOME/.ghidra_9.2_DEV/osgi/felixcache/cache.lock`.  If you've already set `user.home` to somewhere in `/tmp` where you have locks, seems you should be gtg.

Are there any errors in `application.log` i.e. `<user.home>/.ghidra/.ghidra_<version>/application.log`)?

**Comment by hedgeberg** [comment]
I'll take a look when the cluster comes back online. It's down for maintenance over the weekend.

**Comment by jpleasu** [comment]
@hedgeberg  Have you resolved this issue?

**Comment by jpleasu** [comment]
as described above https://github.com/NationalSecurityAgency/ghidra/commit/25fda75bfacdf77b4cc3f66ad2f48cb09ec475ca

**Comment by emteere** [comment]
This should be resolved in master.  Good catch on the new OSGI use in scripting before a general release.
Closing.  If it re-occurs, we will reopen.

**Comment by hedgeberg** [comment]
Thanks guys, sorry for disappearing on this. Been a tough couple months. I'll see what I can do about verifying that this resolves the issue on my end.
