### ISSUE TITLE
ImageCor20Header NullPointerException

### ISSUE THREAD

**Issue by recvfrom** [NationalSecurityAgency/ghidra#2246]
**Describe the bug**
Importing a certain malicious executable using default options results in the following log messages:
```
2020-09-03  16:01:57    INFO    (DataTypeConflictHandler$1) Conflict with existing type IMAGE_DATA_DIRECTORY(), new type will be renamed with .conflict suffix
2020-09-03  16:01:57    ERROR   (MessageLog) Exception appended to MessageLog java.lang.NullPointerException
            at ghidra.app.util.bin.format.pe.ImageCor20Header.markup(ImageCor20Header.java:160)
            at ghidra.app.util.bin.format.pe.ImageCor20Header$$EnhancerByCGLIB$$41483a6f.CGLIB$markup$14(<generated>)
            at ghidra.app.util.bin.format.pe.ImageCor20Header$$EnhancerByCGLIB$$41483a6f$$FastClassByCGLIB$$d76452aa.invoke(<generated>)
            at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:215)
            at generic.continues.ContinuesInterceptor.intercept(ContinuesInterceptor.java:39)
            at ghidra.app.util.bin.format.pe.ImageCor20Header$$EnhancerByCGLIB$$41483a6f.markup(<generated>)
            at ghidra.app.util.bin.format.pe.COMDescriptorDataDirectory.markup(COMDescriptorDataDirectory.java:99)
            at ghidra.app.util.bin.format.pe.COMDescriptorDataDirectory$$EnhancerByCGLIB$$35db96be.CGLIB$markup$4(<generated>)
            at ghidra.app.util.bin.format.pe.COMDescriptorDataDirectory$$EnhancerByCGLIB$$35db96be$$FastClassByCGLIB$$983d9bae.invoke(<generated>)
            at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:215)
            at generic.continues.ContinuesInterceptor.intercept(ContinuesInterceptor.java:39)
            at ghidra.app.util.bin.format.pe.COMDescriptorDataDirectory$$EnhancerByCGLIB$$35db96be.markup(<generated>)
            at ghidra.app.util.opinion.PeLoader.load(PeLoader.java:135)
            at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:346)
            at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
            at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
            at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:401)
            at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
            at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
            at ghidra.util.task.Task.monitoredRun(Task.java:126)
            at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:834)
```

Executable: https://www.virustotal.com/gui/file/dbe2be2fefd2bfa66646cc0a4086cdff59dba295b8f4b7c0ec8bb683a65dd172/detection

**To Reproduce**

Import dbe2be2fefd2bfa66646cc0a4086cdff59dba295b8f4b7c0ec8bb683a65dd172 via the UI

**Expected behavior**

No NPE

**Screenshots**

N/A

**Attachments**

[dbe2be2fefd2bfa66646cc0a4086cdff59dba295b8f4b7c0ec8bb683a65dd172.malware.zip](https://github.com/NationalSecurityAgency/ghidra/files/5170940/dbe2be2fefd2bfa66646cc0a4086cdff59dba295b8f4b7c0ec8bb683a65dd172.malware.zip)

^^^ The password is `malware`. Handle with care, since the encrypted zip contains a malicious executable (LuminosityLink RAT)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Java Version: openjdk 11.0.8 2020-07-14
 - Ghidra Version: 9.1.2

**Additional context**
N/A

**Comment by astrelsky** [comment]
This isn't related to the exception, but the use of `(` and `)` is illegal in a type name so shouldn't this have failed sooner?
