### ISSUE TITLE
Batch Import: Continue through exceptions

### ISSUE THREAD

**Issue by ryanmkurtz** [NationalSecurityAgency/ghidra#2328]
It would be great if the Batch Importer would not stop if one of the files threw an exception during load.  Perhaps it could just list which file(s) didn't import at the end.

**Comment by dev747368** [comment]
What does the exception and stack trace look like?  Is it at ImportBatchTask:149'ish?

**Comment by ryanmkurtz** [comment]
Yep:

```
ERROR Task Error: Batch Import Task - Uncaught Exception: java.lang.IllegalArgumentException: Invalid block name:  java.lang.IllegalArgumentException: Invalid block name: 
	at ghidra.program.database.mem.MemoryMapDB.checkBlockName(MemoryMapDB.java:821)
	at ghidra.program.database.mem.MemoryMapDB.createInitializedBlock(MemoryMapDB.java:646)
	at ghidra.app.util.MemoryBlockUtils.createInitializedBlock(MemoryBlockUtils.java:227)
	at ghidra.app.util.opinion.PeLoader.processMemoryBlocks(PeLoader.java:658)
	at ghidra.app.util.opinion.PeLoader.load(PeLoader.java:121)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugins.importer.tasks.ImportBatchTask.doImportApp(ImportBatchTask.java:149)
	at ghidra.plugins.importer.tasks.ImportBatchTask.doImportBatchGroup(ImportBatchTask.java:127)
	at ghidra.plugins.importer.tasks.ImportBatchTask.doBatchImport(ImportBatchTask.java:116)
	at ghidra.plugins.importer.tasks.ImportBatchTask.run(ImportBatchTask.java:91)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ryanmkurtz** [comment]
I just tried it and it worked, thanks.  It would be nice if the dialog at the end showed some indication that they did not all import.  Either something like Imported x of y or an additional line that said how many failed.  Showing the failed files would be really nice too.

**Comment by ryanmkurtz** [comment]
Also, I have another PE sample that ends up throwing a NullPointerException.  You might want to just catch everything.

**Comment by dev747368** [comment]
catch everything?  thats just crazy talk.
