### ISSUE TITLE
[V850]: Seed context register does not match disassembler's context register: null

### ISSUE THREAD

**Issue by brainstorm** [NationalSecurityAgency/ghidra#2330]
**Describe the bug**

When analyzing a V850 firmware, the following exception occurs:

```
Seed context register does not match disassembler's context register: null
java.lang.IllegalArgumentException: Seed context register does not match disassembler's context register: null
	at ghidra.program.disassemble.Disassembler.setSeedContext(Disassembler.java:308)
	at ghidra.app.cmd.disassemble.DisassembleCommand.doDisassembly(DisassembleCommand.java:182)
	at ghidra.app.cmd.disassemble.DisassembleCommand.applyTo(DisassembleCommand.java:150)
	at ghidra.app.plugin.core.clear.ClearFlowAndRepairCmd.repairFlowsInto(ClearFlowAndRepairCmd.java:455)
	at ghidra.app.plugin.core.clear.ClearFlowAndRepairCmd.applyTo(ClearFlowAndRepairCmd.java:209)
	at ghidra.app.plugin.core.analysis.FindNoReturnFunctionsAnalyzer.repairDamagedLocations(FindNoReturnFunctionsAnalyzer.java:170)
	at ghidra.app.plugin.core.analysis.FindNoReturnFunctionsAnalyzer.added(FindNoReturnFunctionsAnalyzer.java:141)
	at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:190)
	at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:686)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:786)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:665)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:630)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:834)

---------------------------------------------------
Build Date: 2020-sep.-19 1355 AEST
Ghidra Version: 9.2
Java Home: /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
JVM Version: Amazon.com Inc. 11.0.7
OS: Mac OS X 10.15.7 x86_64
Workstation: romanlaptop.lan
```

**To Reproduce**

Load a specific V850 firmware I cannot share. Analyze with all the flags enabled. The exception occurs.

**Screenshots**

<img width="980" alt="Skärmavbild 2020-10-03 kl  19 15 36" src="https://user-images.githubusercontent.com/175587/94987881-d6220680-05ac-11eb-8a77-516c8cd4c1ae.png">

**Comment by emteere** [comment]
That particular processor doesn't have a context register defined which is normally not a problem.  I don't see the bug right off-hand, but we can try to duplicate.

You may be able to get around this issue temporarily, you can add the following lines to the Ghidra/Processors/V850/data/languages/Helpers/Register.sinc file.  Or for now turn off the Discover NonReturning functions analyzer.

```
define register offset=0x200 size=4 contextreg;
define context contextreg
        dummy=(0,0)
;
```

**Comment by brainstorm** [comment]
I've not observed this issue reappearing on newer Ghidra versions (0.9.3DEV20201126) for the same binaries.
