### ISSUE TITLE
StackOverflowError exception in "Objective-C 2 Class" auto analysis

### ISSUE THREAD

**Issue by ronhass** [NationalSecurityAgency/ghidra#2378]
**Describe the bug**
`java.lang.StackOverflowError` exception occurs when trying to auto-analysis specific Mach-O file (`Foundation` from macOS 10.15.4, MD5: 054a9997479d271f196396250e0bc91a).

**To Reproduce**
Just run auto analysis (specifically "Objective-C 2 Class") on the attached archived file:
[Foundation.zip](https://github.com/NationalSecurityAgency/ghidra/files/5402256/Foundation.zip)

I guess the bug would reproduce on different modern versions of the `Foundation` binary, which is located in `/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation`.

**Expected behavior**
I expect the auto analysis to work instead of crash :)

**Screenshots**
![image](https://user-images.githubusercontent.com/28830987/96460532-f77d2680-122b-11eb-99b8-ed16db7ca240.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 12.0.2
 - Ghidra Version: 9.1.2

**Additional context**
I tried to locate to bug, so first I added `-XX:MaxJavaStackTraceDepth=1000000` to the java command line in order to examine the full stack trace:

```An unexpected error occurred while processing the command: Auto Analysis
java.lang.StackOverflowError
	at db.ChainedBuffer.getBytes(ChainedBuffer.java:892)
	at db.ChainedBuffer.get(ChainedBuffer.java:922)
	at db.DBBuffer.get(DBBuffer.java:148)
	at ghidra.program.database.mem.FileBytes.getBytes(FileBytes.java:345)
	at ghidra.program.database.mem.FileBytes.getModifiedBytes(FileBytes.java:172)
	at ghidra.program.database.mem.FileBytesSubMemoryBlock.getBytes(FileBytesSubMemoryBlock.java:54)
	at ghidra.program.database.mem.MemoryBlockDB.getBytes(MemoryBlockDB.java:430)
	at ghidra.program.database.mem.MemoryBlockDB.getBytes(MemoryBlockDB.java:308)
	at ghidra.program.database.mem.MemoryMapDB.getBytes(MemoryMapDB.java:1253)
	at ghidra.program.database.mem.MemoryMapDB.getBytes(MemoryMapDB.java:1234)
	at ghidra.app.util.bin.MemoryByteProvider.readBytes(MemoryByteProvider.java:103)
	at ghidra.app.util.bin.BinaryReader.readLong(BinaryReader.java:673)
	at ghidra.app.util.bin.BinaryReader.readNextLong(BinaryReader.java:293)
	at ghidra.app.util.bin.format.objectiveC.ObjectiveC1_Utilities.readNextIndex(ObjectiveC1_Utilities.java:63)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Protocol.<init>(ObjectiveC2_Protocol.java:51)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_ProtocolList.<init>(ObjectiveC2_ProtocolList.java:50)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Protocol.readProtocols(ObjectiveC2_Protocol.java:119)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Protocol.<init>(ObjectiveC2_Protocol.java:53)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_ProtocolList.<init>(ObjectiveC2_ProtocolList.java:50)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Protocol.readProtocols(ObjectiveC2_Protocol.java:119)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Protocol.<init>(ObjectiveC2_Protocol.java:53)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_ProtocolList.<init>(ObjectiveC2_ProtocolList.java:50)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Protocol.readProtocols(ObjectiveC2_Protocol.java:119)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Protocol.<init>(ObjectiveC2_Protocol.java:53)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_ProtocolList.<init>(ObjectiveC2_ProtocolList.java:50)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Protocol.readProtocols(ObjectiveC2_Protocol.java:119)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Protocol.<init>(ObjectiveC2_Protocol.java:53)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_ProtocolList.<init>(ObjectiveC2_ProtocolList.java:50)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Protocol.readProtocols(ObjectiveC2_Protocol.java:119)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Protocol.<init>(ObjectiveC2_Protocol.java:53)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_ProtocolList.<init>(ObjectiveC2_ProtocolList.java:50)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Protocol.readProtocols(ObjectiveC2_Protocol.java:119)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Protocol.<init>(ObjectiveC2_Protocol.java:53)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_ProtocolList.<init>(ObjectiveC2_ProtocolList.java:50)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Protocol.readProtocols(ObjectiveC2_Protocol.java:119)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Protocol.<init>(ObjectiveC2_Protocol.java:53)
.....
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_ProtocolList.<init>(ObjectiveC2_ProtocolList.java:50)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Protocol.readProtocols(ObjectiveC2_Protocol.java:119)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Protocol.<init>(ObjectiveC2_Protocol.java:53)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_ProtocolList.<init>(ObjectiveC2_ProtocolList.java:50)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Protocol.readProtocols(ObjectiveC2_Protocol.java:119)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Protocol.<init>(ObjectiveC2_Protocol.java:53)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_ProtocolList.<init>(ObjectiveC2_ProtocolList.java:50)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_ClassRW.readBaseProtocols(ObjectiveC2_ClassRW.java:149)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_ClassRW.<init>(ObjectiveC2_ClassRW.java:68)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Class.readData(ObjectiveC2_Class.java:109)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Class.<init>(ObjectiveC2_Class.java:52)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Class.readSuperClass(ObjectiveC2_Class.java:150)
	at ghidra.app.util.bin.format.objc2.ObjectiveC2_Class.<init>(ObjectiveC2_Class.java:49)
	at ghidra.app.plugin.core.analysis.ObjectiveC2_ClassAnalyzer.processClassList(ObjectiveC2_ClassAnalyzer.java:358)
	at ghidra.app.plugin.core.analysis.ObjectiveC2_ClassAnalyzer.processObjectiveC2(ObjectiveC2_ClassAnalyzer.java:74)
	at ghidra.app.plugin.core.analysis.ObjectiveC2_ClassAnalyzer.added(ObjectiveC2_ClassAnalyzer.java:52)
	at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:185)
	at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:685)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:785)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:664)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:629)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:62)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:101)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

Then I tried to mimic the analysis of `processClassList` in a python script. The bug reproduced in the script so I added prints in order to follow the analysis until I found (hopefully) the source of the bug. Look at this class:
![image](https://user-images.githubusercontent.com/28830987/96461748-7030b280-122d-11eb-917e-77564a209f28.png)

According to the parsing code of `ObjectiveC2_Class` (in `ghidra/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/objc2/ObjectiveC2_Class.java`), the second member should be a pointer to the super class. In this case, we have a pointer to a GOT entry (`__got::_OBJC_CLASS_$_NSObject`). The parsing code then proceeds to parse the pointer as another `ObjectiveC2_Class`, which evidently isn't the case here:

![image](https://user-images.githubusercontent.com/28830987/96462362-285e5b00-122e-11eb-913a-c8baaa008098.png)

In my python script I fixed the bug by ignoring "classes" which resides in the `__got` section, and I guess it would solve the bug in the auto analysis as well.

**Comment by dpoggi** [comment]
Bumping with a naïve fix I've applied for the issue against the `Ghidra_9.2_build` tag, made based on your description of your Python script. Disclaimer: I have _no idea_ what I'm doing in this codebase, but I spent about an hour figuring this out, and it does keep me from getting `StackOverflowError`s.

```diff
diff --git a/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/objc2/ObjectiveC2_Class.java b/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/objc2/ObjectiveC2_Class.java
index 97950e629..5008b79ea 100644
--- a/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/objc2/ObjectiveC2_Class.java
+++ b/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/objc2/ObjectiveC2_Class.java
@@ -23,6 +23,7 @@ import ghidra.app.util.bin.format.objectiveC.ObjectiveC1_Constants;
 import ghidra.app.util.bin.format.objectiveC.ObjectiveC1_Utilities;
 import ghidra.program.model.address.Address;
 import ghidra.program.model.data.*;
+import ghidra.program.model.mem.MemoryBlock;
 import ghidra.program.model.symbol.Namespace;
 import ghidra.util.exception.DuplicateNameException;
 
@@ -146,8 +147,21 @@ public class ObjectiveC2_Class implements StructConverter {
 
 		if (index != 0 && reader.isValidIndex(index)) {
 			long originalIndex = reader.getPointerIndex();
+
+			MemoryBlock gotBlock = _state.program.getMemory().getBlock("__got");
+			if (gotBlock != null) {
+				long gotStartIndex = gotBlock.getStart().getOffset();
+				long gotEndIndex = gotBlock.getEnd().getOffset();
+
+				if (index >= gotStartIndex && index <= gotEndIndex) {
+					reader.setPointerIndex(originalIndex);
+					return;
+				}
+			}
+
 			reader.setPointerIndex(index);
 			superclass = new ObjectiveC2_Class(_state, reader);
+
 			reader.setPointerIndex(originalIndex);
 		}
 	}
diff --git a/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/objc2/ObjectiveC2_Constants.java b/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/objc2/ObjectiveC2_Constants.java
index e722d9a7c..3d0878e97 100644
--- a/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/objc2/ObjectiveC2_Constants.java
+++ b/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/objc2/ObjectiveC2_Constants.java
@@ -75,6 +75,7 @@ public final class ObjectiveC2_Constants {
 			}
 		}
 		sectionNames.add("__data");//not really an Objective-C 2.0 section, but it contains structures used by Objective-C 2.0
+		sectionNames.add("__got");
 		return sectionNames;
 	}
 	/**
```
