### ISSUE TITLE
Problem parsing or applying PDB information

### ISSUE THREAD

**Issue by spacehamster** [NationalSecurityAgency/ghidra#2395]
**Describe the bug**
Loading a PDB fails with the error: 

```
Problem parsing or applying PDB information: org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 3; The element type "tables" must be terminated by the matching end-tag "</tables>".
java.io.IOException: Problem parsing or applying PDB information: org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 3; The element type "tables" must be terminated by the matching end-tag "</tables>".
	at ghidra.app.util.bin.format.pdb.PdbParser.applyTo(PdbParser.java:410)
	at pdb.LoadPdbTask$1.analysisWorkerCallback(LoadPdbTask.java:68)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1677)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:685)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:785)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:664)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:629)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:62)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:101)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 3; The element type "tables" must be terminated by the matching end-tag "</tables>".
	at ghidra.xml.ThreadedXmlPullParserImpl.checkForException(ThreadedXmlPullParserImpl.java:122)
	at ghidra.xml.ThreadedXmlPullParserImpl.waitForNextElement(ThreadedXmlPullParserImpl.java:159)
	at ghidra.xml.ThreadedXmlPullParserImpl.hasNext(ThreadedXmlPullParserImpl.java:154)
	at ghidra.app.util.bin.format.pdb.PdbParser.applyTo(PdbParser.java:325)
	... 10 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 3; The element type "tables" must be terminated by the matching end-tag "</tables>".
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1243)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at ghidra.xml.ThreadedXmlPullParserImpl$ContentHandlerRunnable.run(ThreadedXmlPullParserImpl.java:267)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
```

**To Reproduce**
1. Create new project
2. Import file Lua.dll (see attached)
3. Confirm ok with default import settings
4. Open with default tool
5. Do not auto analyze
6. Select File->Load PDB file... and choose Lua.pdb (see attached)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/3821056/96943450-e67e2f00-1523-11eb-85a0-2d1095866e8e.png)

**Attachments**

[Lua.dll.zip](https://github.com/NationalSecurityAgency/ghidra/files/5426612/Lua.dll.zip)
[Lua.pdb.zip](https://github.com/NationalSecurityAgency/ghidra/files/5426613/Lua.pdb.zip)

**Environment (please complete the following information):**
 - OS: Windows 7 6.1 amd64
 - Java Version: Oracle Corporation 11.0.2
 - Ghidra Version: 9.1.2

**Additional context**
If the library is built with /DEBUG:FULL instead of /DEBUG or /DEBUG:FASTLINK, the error does not occur

**Comment by ghizard** [comment]
@spacehamster

The error you are indicating, is symptomatic of the XML-converted PDB file having been terminated improperly.  This can happen if pdb.exe crashes.  Can you manually convert the pdb file and look at the xml output to see that it seems to have not been truncated.  When I've manually converted the file, I saw no issues.

There is chance that when your pdb.exe runs, there could be an environment difference, such as a space the path, or a non-escaped character place in a string in the xml file.

I've downloaded the ghidra9.1.2 distribution and ran it on a Windows system, not being able to reproduce the error.
I then put the distribution in a path that has a space its name and also did the same for the *.dll and *.pdb files, and still was not able to reproduce the error.

I've also tried other combinations of loading the xml on a Linux-based version of our patch branch.

Let me know if you see that the xml file is not complete or if there is anything else that might have contributed to the error.

**Comment by spacehamster** [comment]
@ghizard I no longer have access to the machine this error originally occurred on, and I am unable to reproduce the error on my current machine (which is windows 10) or a windows 7 install running in a virtual machine. Sorry for the inconvenience.

**Comment by dev747368** [comment]
Closing per user's last comment.
