### ISSUE TITLE
NPE if edit function data type in a data type archive without an open program

### ISSUE THREAD

**Issue by ChrisMGeiger** [NationalSecurityAgency/ghidra#2407]
**Describe the bug**
Functions generated from parsing header files using the CParser when "Parse to File" is used can't be used and are invalid. Parsing into an existing database does work.

**To Reproduce**
1. Copy `parser_test.prf` to `%USERPROFILE%/.ghidra/.ghidra_9.1.2_PUBLIC/parserprofiles` 
1. Edit `parser_test.prf` to point to the correct location of `parser_test.h`
1. Launch an empty CodeBrowser window
1. Close all open data type libraries
1. File->Parse C Source...
1. Select parser_test.prf profile
1. Select "Parse to File..."
1. Select a name/location for the resultant gdt file (e.g. `test.gdt`)
1. In the Data Type Manager open the resultant gdt Type Library file
1. Expand the Type Library file
1. Try to view/edit the `my_func` function definition
1. NullPointerException

**Expected behavior**
Valid function pointers

**Attachments**
1. `parser_test.h`
1. `parser_test.prf`
[parser_test.zip](https://github.com/NationalSecurityAgency/ghidra/files/5445775/parser_test.zip)

**Environment (please complete the following information):**
 - OS: Windows 10.0.18363 N/A Build 18363
 - Java Version: 11.0.4
 - Ghidra Version: 9.1.2 PUBLIC

**Exception**
```
Uncaught Exception! 
java.lang.NullPointerException
	at ghidra.app.plugin.core.datamgr.editor.DataTypeEditorManager.editFunctionSignature(DataTypeEditorManager.java:499)
	at ghidra.app.plugin.core.datamgr.editor.DataTypeEditorManager.editFunctionSignature(DataTypeEditorManager.java:492)
	at ghidra.app.plugin.core.datamgr.editor.DataTypeEditorManager.edit(DataTypeEditorManager.java:132)
	at ghidra.app.plugin.core.datamgr.DataTypesProvider.editNode(DataTypesProvider.java:627)
	at ghidra.app.plugin.core.datamgr.DataTypesProvider$1.mouseClicked(DataTypesProvider.java:371)
	at docking.widgets.JTreeMouseListenerDelegate.fireMouseClicked(JTreeMouseListenerDelegate.java:131)
	at docking.widgets.JTreeMouseListenerDelegate.mouseClicked(JTreeMouseListenerDelegate.java:109)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: C:\Program Files\AdoptOpenJDK\jdk-11.0.4.11-hotspot

JVM Version: AdoptOpenJDK 11.0.4
OS: Windows 10 10.0 amd64
Workstation: 
```

**Comment by mumbel** [comment]
Cannot repro with b605ad03274edaa20c83107d30f681850848ff84

**Comment by ChrisMGeiger** [comment]
Further testing shows that this only manifests itself when using an empty CodeBrowser window. If there is a binary present, then function types can be viewed/edited.

**Comment by ghidra1** [comment]
Fixed in master branch for next major release
