### ISSUE TITLE
Deleting a function that have a Tag Uncaught Exception!  java.lang.NullPointerException

### ISSUE THREAD

**Issue by pabx06** [NationalSecurityAgency/ghidra#2412]
**Describe the bug**
A clear and concise description of the bug.

**To Reproduce**
1. Go to function in the listing, clear byte
2. Right Click ,  'Function' > 'Delete Function'

**Expected behavior**
no error

**Attachments**
```
2020-10-30 10:34:37 INFO  OverideKnowVariadicSite.java> callsite= 4071215a r1= 0x4071262c dataAt r1 = null  
2020-10-30 10:35:58 DEBUG (ToolTaskManager) Exec Task Clear with Options  
2020-10-30 10:35:58 DEBUG (ToolTaskManager)   task finish (0.073 secs)  
2020-10-30 10:34:35:58 DEBUG (ToolTaskManager)   task complete (0.109 secs)  
2020-10-30 10:36:09 DEBUG (ToolTaskManager) Exec Task Auto Analysis  
2020-10-30 10:36:09 ERROR (SwingExceptionHandler) Error: Uncaught Exception!  java.lang.NullPointerException
        at ghidra.app.plugin.core.function.tags.FunctionTagsComponentProvider.lambda$reload$0(FunctionTagsComponentProvider.java:105)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
 
2020-10-30 10:36:09 DEBUG (ToolTaskManager)   task finish (0.272 secs)  
2020-10-30 10:36:10 DEBUG (ToolTaskManager)   task complete (0.487 secs)  
2020-10-30 10:36:37 INFO  (DbViewerComponent) Updating dbViewer...  
2020-10-30 10:36:50 DEBUG (ToolTaskManager) Exec Task Auto Analysis  
2020-10-30 10:36:50 ERROR (SwingExceptionHandler) Error: Uncaught Exception!  java.lang.NullPointerException
        at ghidra.app.plugin.core.function.tags.FunctionTagsComponentProvider.lambda$reload$0(FunctionTagsComponentProvider.java:105)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
 
2020-10-30 10:36:50 DEBUG (SaveState) Two different types for option name: CUSTOM_OPTION_CLASS  
2020-10-30 10:36:50 DEBUG (ToolTaskManager)   task finish (0.284 secs)  
2020-10-30 10:36:50 DEBUG (ToolTaskManager)   task complete (0.538 secs)  
2020-10-30 10:36:57 INFO  (DbViewerComponent) Updating dbViewer...  

```

**Environment (please complete the following information):**
 - OS: linux 4
 - Java Version: 11
 - Ghidra Version: master branch

**Additional context**
i had function entry-point to delete to create a null terminated string instead

**Comment by dragonmacher** [comment]
This is fixed in 77ee6987

**Comment by pabx06** [comment]
> This is fixed in [77ee698](https://github.com/NationalSecurityAgency/ghidra/commit/77ee698797b2ac6184e3bb017bc7a7cb4fc1d2d3)

t think we have a regression i am using this :

commit 027ba3884a805f6736232e2ad399c3cea4ca5aa5 (upstream/master, upstream/HEAD)
Merge: d201830d5 49736ceb0
Author: ghidra1 <ghidra1@users.noreply.github.com>
Date:   Wed Oct 28 16:41:22 2020 -0400

    Merge remote-tracking branch 'origin/Ghidra_9.2'


![image](https://user-images.githubusercontent.com/4013370/97790124-32853f80-1bc6-11eb-95b8-32594c3c81ef.png)

**Comment by pabx06** [comment]
not sure but doesn't look critical to data at first sight

**Comment by pabx06** [comment]
and now clearing bytes :

```java.lang.NullPointerException
	at ghidra.app.plugin.core.function.tags.FunctionTagsComponentProvider.lambda$reload$0(FunctionTagsComponentProvider.java:105)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at java.desktop/java.awt.Component.show(Component.java:1716)
	at java.desktop/java.awt.Component.setVisible(Component.java:1663)
	at java.desktop/java.awt.Window.setVisible(Window.java:1031)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005)
	at docking.DockingDialog.setVisible(DockingDialog.java:354)
	at docking.DockingWindowManager.lambda$doShowDialog$6(DockingWindowManager.java:1699)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at docking.DockingWindowManager.doShowDialog(DockingWindowManager.java:1703)
	at docking.DockingWindowManager.showDialog(DockingWindowManager.java:1724)
	at ghidra.util.task.TaskDialog.lambda$doShow$7(TaskDialog.java:275)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2020-Oct-31 2020 CET
Ghidra Version: 9.2
Java Home: /usr/lib/jvm/java-11-amazon-corretto
JVM Version: Amazon.com Inc. 11.0.8
OS: Linux 4.15.0-99-generic amd64
Workstation: localhost
```

**Comment by dragonmacher** [comment]
You are correct.  This was changed in master to remove the null check.  We will put a fix in shortly.
