### ISSUE TITLE
Support importing MacOS 11 MH_FILESET kernelcaches

### ISSUE THREAD

**Issue by uint63t** [NationalSecurityAgency/ghidra#2487]
Support importing MacOS 11 MH_FILESET kernelcaches
macOS 11 implements a new format for kernelcaches, which introduces the LC_FILESET_ENTRY load commands that point to specific Mach-O headers within the cache.  

When I try to import one of the files in /System/Library/KernelCollections with Ghidra 9.2 in Single File mode, I get

Error on line 2: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
java.io.IOException: Error on line 2: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
	at ghidra.app.util.opinion.MachoLoader.load(MachoLoader.java:101)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:400)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:349)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:93)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

and in Batch, it initially looks like it works, but then no actual kexts are found when trying to open files inside the kernelcache in the project view.

**Comment by ryanmkurtz** [comment]
I have some simple fixes to get it past the exception so it loads and analyzes, but this new format definitely needs some work put into it.

**Comment by jmpews** [comment]
```
java.lang.IllegalArgumentException: Start address must be less than or equal to end address:  Start fffffe000708c000   end = fffffe0007007fff
java.io.IOException: java.lang.IllegalArgumentException: Start address must be less than or equal to end address:  Start fffffe000708c000   end = fffffe0007007fff
	at ghidra.app.util.opinion.MachoLoader.load(MachoLoader.java:113)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:404)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:350)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Start address must be less than or equal to end address:  Start fffffe000708c000   end = fffffe0007007fff
	at ghidra.program.model.address.AddressSet.checkValidRange(AddressSet.java:1206)
	at ghidra.program.model.address.AddressSet.add(AddressSet.java:170)
	at ghidra.program.model.address.AddressSet.addRange(AddressSet.java:231)
	at ghidra.program.model.address.AddressSet.<init>(AddressSet.java:79)
	at ghidra.program.model.address.DefaultAddressFactory.getAddressSet(DefaultAddressFactory.java:359)
	at ghidra.program.database.map.AddressKeyRecordIterator.<init>(AddressKeyRecordIterator.java:85)
	at ghidra.program.database.util.AddressRangeMapDB$RangeIterator.<init>(AddressRangeMapDB.java:656)
	at ghidra.program.database.util.AddressRangeMapDB.getAddressRanges(AddressRangeMapDB.java:493)
	at ghidra.program.database.module.ModuleManager.move(ModuleManager.java:571)
	at ghidra.program.database.module.FragmentDB.move(FragmentDB.java:145)
	at ghidra.app.util.opinion.MachoPrelinkProgramBuilder$PrelinkMachoInfo.addToProgramTree(MachoPrelinkProgramBuilder.java:609)
	at ghidra.app.util.opinion.MachoPrelinkProgramBuilder.processPreLinkMachoInfo(MachoPrelinkProgramBuilder.java:195)
	at ghidra.app.util.opinion.MachoPrelinkProgramBuilder.fixPreLinkAddresses(MachoPrelinkProgramBuilder.java:120)
	at ghidra.app.util.opinion.MachoPrelinkProgramBuilder.build(MachoPrelinkProgramBuilder.java:99)
	at ghidra.app.util.opinion.MachoPrelinkProgramBuilder.buildProgram(MachoPrelinkProgramBuilder.java:89)
	at ghidra.app.util.opinion.MachoLoader.load(MachoLoader.java:93)
	... 11 more

---------------------------------------------------
Build Date: 2021-Dec-21 1319 EST
Ghidra Version: 10.1.1
Java Home: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
JVM Version: Azul Systems, Inc. 11.0.12
OS: Mac OS X 11.4 aarch64
Workstation: localhost
```

it seems still not working for macos 11 kernelcache? @ryanmkurtz

**Comment by ryanmkurtz** [comment]
What version of the kernelcache are you using?

**Comment by ryanmkurtz** [comment]
Thanks. I won't be able to get to this for a couple of weeks but I'll reopen the ticket as a reminder to investigate.  @emteere might also be interested.

**Comment by ryanmkurtz** [comment]
I believe I have a fix for this.  The change is in internal review.
