### ISSUE TITLE
Uncaught Exception, AddressOutOfBoundsException: Address Overflow in add: ffffefff + 0xefff

### ISSUE THREAD

**Issue by brainstorm** [NationalSecurityAgency/ghidra#2530]
**Describe the bug**

Given the following partially defined memory map:

<img width="1268" alt="Skärmavbild 2020-11-28 kl  16 15 18" src="https://user-images.githubusercontent.com/175587/100494339-ec0b0c80-3194-11eb-96da-a9fb08871678.png">

I'm trying to define the peripherals/IO section in Ghidra as spec'd on the IC's datasheet:

<img width="538" alt="Skärmavbild 2020-11-28 kl  16 12 56" src="https://user-images.githubusercontent.com/175587/100494302-946ca100-3194-11eb-8d7b-ef0f4d91d567.png">

I'm getting the following unhandled exception:

<img width="1219" alt="Skärmavbild 2020-11-28 kl  16 12 35" src="https://user-images.githubusercontent.com/175587/100494297-8a4aa280-3194-11eb-8e47-06c97ea5b2f7.png">

In textual form, for reference:

```
Address Overflow in add: ffffefff + 0xefff
ghidra.program.model.address.AddressOutOfBoundsException: Address Overflow in add: ffffefff + 0xefff
	at ghidra.program.model.address.AbstractAddressSpace.add(AbstractAddressSpace.java:438)
	at ghidra.program.model.address.GenericAddressSpace.add(GenericAddressSpace.java:21)
	at ghidra.program.model.address.GenericAddress.add(GenericAddress.java:237)
	at ghidra.app.plugin.core.memory.AddBlockModel.hasNoMemoryConflicts(AddBlockModel.java:393)
	at ghidra.app.plugin.core.memory.AddBlockModel.validateInfo(AddBlockModel.java:297)
	at ghidra.app.plugin.core.memory.AddBlockModel.execute(AddBlockModel.java:240)
	at ghidra.app.plugin.core.memory.AddBlockDialog.okCallback(AddBlockDialog.java:338)
	at docking.DialogComponentProvider.lambda$addOKButton$0(DialogComponentProvider.java:447)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6631)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6396)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5007)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4839)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4839)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at java.desktop/java.awt.Component.show(Component.java:1716)
	at java.desktop/java.awt.Component.setVisible(Component.java:1663)
	at java.desktop/java.awt.Window.setVisible(Window.java:1031)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005)
	at docking.DockingDialog.setVisible(DockingDialog.java:354)
	at docking.DockingWindowManager.lambda$doShowDialog$6(DockingWindowManager.java:1701)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at docking.DockingWindowManager.doShowDialog(DockingWindowManager.java:1705)
	at docking.DockingWindowManager.showDialog(DockingWindowManager.java:1739)
	at docking.DockingWindowManager.showDialog(DockingWindowManager.java:1680)
	at ghidra.framework.plugintool.PluginTool.showDialog(PluginTool.java:1438)
	at ghidra.app.plugin.core.memory.AddBlockDialog.showDialog(AddBlockDialog.java:325)
	at ghidra.app.plugin.core.memory.MemoryMapProvider.showAddBlockDialog(MemoryMapProvider.java:663)
	at ghidra.app.plugin.core.memory.MemoryMapProvider$1.actionPerformed(MemoryMapProvider.java:194)
	at docking.menu.ToolBarItemManager.lambda$actionPerformed$0(ToolBarItemManager.java:128)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2020-nov.-24 1908 AEDT
Ghidra Version: 9.3
Java Home: /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
JVM Version: Amazon.com Inc. 11.0.7
OS: Mac OS X 10.15.7 x86_64
Workstation: localhost
```

**Comment by ghidra1** [comment]
The stack trace appears to be a problem in the error detection (which I will correct), however based upon your dialog it appears you attempted to create a block larger than the available space.  With a start of 0xFFFFF000 (and a 32-bit address space) the largest block would be 0x1000 in length.  A length 0xF000 would extend beyond the bounds of the address space.  The block you are attempting to define (based on the graphic map you specified) should have a start address of 0xFFFFF000 with a length of 0x1000

**Comment by ghidra1** [comment]
Error checking fix will be included in 9.2.2

**Comment by brainstorm** [comment]
Thanks @ghidra1!

I suspect that what confused me were the negative addresses and how to properly defined them in Ghidra's memory mapper (those below the ROM region)?

In principle the figure 3-14 shown above should be possible to define in Ghidra, right? I've heard that certain microcontroller memory arrangements/mappings are still not possible in Ghidra, but I'm not fully aware of the current limitations and specific corner cases where that's not possible?

**Comment by ghidra1** [comment]
Mapping memory regions may help in the listing view but frequently have issues with pointer de-referencing and decompiler results.  In addition, such architectures also present challenges for the image Loaders which may not properly handle the virtual vs. physical memory distinction and the various processor variants which may have an altered memory arrangement.

**Comment by brainstorm** [comment]
Thanks @ghidra1, what you write makes sense and I think I understand what you are alluding to w.r.t to pointer de-ref & co (related to decompiling).

But my issue is before reaching analysis stage.

For instance, given this alternative linear address space for the same processor (without the "weird" wrap-around I mentioned above):

<img width="342" alt="Skärmavbild 2021-02-24 kl  22 17 36" src="https://user-images.githubusercontent.com/175587/108993061-27629c00-76ee-11eb-8fb9-72f8dbb7f8ca.png">

It's not easily definable as-is on the memory manager, see:

```python
>>> memory = currentProgram.getMemory()
>>> fb = memory.getAllFileBytes()	
>>> blk = memory.getBlock(toAddr(0x0))
>>> memory.removeBlock(blk, monitor)
>>> 
>>> memory.createUninitializedBlock("internal_ram",toAddr(0x3ff8000),0x2fff,False)
>>> memory.createUninitializedBlock("peripherals", toAddr(0x3ffefff),0xfff, False)
>>> memory.createInitializedBlock("rom", toAddr(0x0), fb[0], 0, 0x1000000, False)
Traceback (most recent call last):
  File "python", line 1, in <module>
	at ghidra.program.database.mem.MemoryMapDB.checkBlock(MemoryMapDB.java:1043)
	at ghidra.program.database.mem.MemoryMapDB.removeBlock(MemoryMapDB.java:1850)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Blocks do not belong to this program
ghidra.program.database.mem.MemoryBlockDB@6f03ae13
ghidra.program.database.mem.MemoryBlockDB@38d5ac1c
ghidra.program.database.mem.MemoryBlockDB@6ad8b9ac
```

What would be the correct sequence of arguments/flags/(instruction ordering?) to have a correct representation of a loaded V850 16MB firmware (size 0x1000000) on Ghidra?

**Comment by ghidra1** [comment]
I suspect `blk` is null and is the cause of the error above.

I am rather confused by what you are attempting to achieve with your script and what your initial state is before running the script.  You will really need to debug your script.

**Comment by brainstorm** [comment]
Argh, true, thanks @ghidra1. The script assumes the memory map has the initial default mapping, but when it's empty it obviously goes that that way.

Now, I'll carry on and script the rewrite of instruction opcodes so they reference to the new remapped mem regions, yay :)
