### ISSUE TITLE
EOFException importing .exe file: PE bug?

### ISSUE THREAD

**Issue by gynt** [NationalSecurityAgency/ghidra#2572]
**Describe the bug**
Specifying an .exe in the Import File menu leads to an EOFException.

**To Reproduce**
1. Go to a repository
2. Click on File -> Import File
3. Select your .exe file and import it

**Screenshots**
```
2020-12-19 15:42:37 WARN  (SecurityDataDirectory$$EnhancerByCGLIB$$e338a74d) Certificate address is not valid.  
2020-12-19 15:42:37 ERROR (ImporterUtilities) Error Importing File: Error importing file: my program.exe java.io.EOFException
	at ghidra.app.util.bin.GhidraRandomAccessFile.ensure(GhidraRandomAccessFile.java:298)
	at ghidra.app.util.bin.GhidraRandomAccessFile.readByte(GhidraRandomAccessFile.java:180)
	at ghidra.app.util.bin.RandomAccessByteProvider.readByte(RandomAccessByteProvider.java:132)
	at ghidra.app.util.bin.BinaryReader.readAsciiString(BinaryReader.java:440)
	at ghidra.app.util.bin.format.pe.debug.DebugCOFFSymbol.initDebugCOFFSymbol(DebugCOFFSymbol.java:164)
	at ghidra.app.util.bin.format.pe.debug.DebugCOFFSymbol.createDebugCOFFSymbol(DebugCOFFSymbol.java:142)
	at ghidra.app.util.bin.format.pe.FileHeader.processSymbols(FileHeader.java:373)
	at ghidra.app.util.bin.format.pe.FileHeader$$EnhancerByCGLIB$$37dea7fd.CGLIB$processSymbols$8(<generated>)
	at ghidra.app.util.bin.format.pe.FileHeader$$EnhancerByCGLIB$$37dea7fd$$FastClassByCGLIB$$b60b88d1.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:215)
	at generic.continues.ContinuesInterceptor.intercept(ContinuesInterceptor.java:39)
	at ghidra.app.util.bin.format.pe.FileHeader$$EnhancerByCGLIB$$37dea7fd.processSymbols(<generated>)
	at ghidra.app.util.bin.format.pe.NTHeader.parse(NTHeader.java:272)
	at ghidra.app.util.bin.format.pe.NTHeader.initNTHeader(NTHeader.java:94)
	at ghidra.app.util.bin.format.pe.NTHeader.createNTHeader(NTHeader.java:75)
	at ghidra.app.util.bin.format.pe.PortableExecutable.initPortableExecutable(PortableExecutable.java:110)
	at ghidra.app.util.bin.format.pe.PortableExecutable.createPortableExecutable(PortableExecutable.java:86)
	at ghidra.app.util.opinion.PeLoader.findSupportedLoadSpecs(PeLoader.java:79)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.getLoadSpec(AbstractLibrarySupportLoader.java:737)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.importLibrary(AbstractLibrarySupportLoader.java:667)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.importLibrary(AbstractLibrarySupportLoader.java:635)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadLibraries(AbstractLibrarySupportLoader.java:259)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:97)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:400)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:349)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 14.0.2
 - Ghidra Version: 9.2

**Comment by ryanmkurtz** [comment]
I am assuming this error is specific to a particular sample.  Can you attach it?

**Comment by gynt** [comment]
Github did not allow me to upload an .exe, so here is a wetransfer link: https://we.tl/t-kRnGHgfaVi

**Comment by dev747368** [comment]
@gynt I could not duplicate the error you posted.  Could you verify that the version of Ghidra you listed in the problem report is correct and double check the problem yourself?  Also, 9.2.1 was just recently released, please try with that version.

**Comment by gynt** [comment]
I tried the 9.3 dev build, and the issue still persists. Same stacktrace too. Shall I send you another file via email? Or upload it?

**Comment by dev747368** [comment]
Ah.  Looking more closely at the stack trace, you may be also importing at the same time the binary's external libraries (dlls), and one of those may be the culprit.
You can turn off that option and see if you can import the base binary by itself (which should give you a list of external libraries that it wants), and then import each library manually to see which one is the problem.  Once we know the file causing the problem, we can fix it.

**Comment by ryanmkurtz** [comment]
Can you re-upload the binary?

**Comment by gynt** [comment]
@dev747368 You are close!
With all import options off, except Load External Libraries, I get stacktrace 1
With all import options off, except Create Export Symbol Files, I get stacktrace 2

Stacktrace 1
```
java.io.EOFException
	at ghidra.app.util.bin.GhidraRandomAccessFile.ensure(GhidraRandomAccessFile.java:298)
	at ghidra.app.util.bin.GhidraRandomAccessFile.readByte(GhidraRandomAccessFile.java:180)
	at ghidra.app.util.bin.RandomAccessByteProvider.readByte(RandomAccessByteProvider.java:132)
	at ghidra.app.util.bin.BinaryReader.readAsciiString(BinaryReader.java:449)
	at ghidra.app.util.bin.format.pe.debug.DebugCOFFSymbol.initDebugCOFFSymbol(DebugCOFFSymbol.java:164)
	at ghidra.app.util.bin.format.pe.debug.DebugCOFFSymbol.createDebugCOFFSymbol(DebugCOFFSymbol.java:142)
	at ghidra.app.util.bin.format.pe.FileHeader.processSymbols(FileHeader.java:373)
	at ghidra.app.util.bin.format.pe.FileHeader$$EnhancerByCGLIB$$c2578869.CGLIB$processSymbols$8(<generated>)
	at ghidra.app.util.bin.format.pe.FileHeader$$EnhancerByCGLIB$$c2578869$$FastClassByCGLIB$$d4f6268c.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:215)
	at generic.continues.ContinuesInterceptor.intercept(ContinuesInterceptor.java:39)
	at ghidra.app.util.bin.format.pe.FileHeader$$EnhancerByCGLIB$$c2578869.processSymbols(<generated>)
	at ghidra.app.util.bin.format.pe.NTHeader.parse(NTHeader.java:272)
	at ghidra.app.util.bin.format.pe.NTHeader.initNTHeader(NTHeader.java:94)
	at ghidra.app.util.bin.format.pe.NTHeader.createNTHeader(NTHeader.java:75)
	at ghidra.app.util.bin.format.pe.PortableExecutable.initPortableExecutable(PortableExecutable.java:110)
	at ghidra.app.util.bin.format.pe.PortableExecutable.createPortableExecutable(PortableExecutable.java:86)
	at ghidra.app.util.opinion.PeLoader.findSupportedLoadSpecs(PeLoader.java:79)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.getLoadSpec(AbstractLibrarySupportLoader.java:737)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.importLibrary(AbstractLibrarySupportLoader.java:667)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.importLibrary(AbstractLibrarySupportLoader.java:635)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadLibraries(AbstractLibrarySupportLoader.java:259)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:97)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:400)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:303)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

---------------------------------------------------
Build Date: 2021-Jan-20 1631 CET
Ghidra Version: 9.3
Java Home: C:\Program Files\Java\jdk-14.0.2
JVM Version: Oracle Corporation 14.0.2
OS: Windows 10 10.0 amd64
Workstation: 129.125.153.191
```
Stacktrace 2
```
java.io.EOFException
	at ghidra.app.util.bin.GhidraRandomAccessFile.ensure(GhidraRandomAccessFile.java:298)
	at ghidra.app.util.bin.GhidraRandomAccessFile.readByte(GhidraRandomAccessFile.java:180)
	at ghidra.app.util.bin.RandomAccessByteProvider.readByte(RandomAccessByteProvider.java:132)
	at ghidra.app.util.bin.BinaryReader.readAsciiString(BinaryReader.java:449)
	at ghidra.app.util.bin.format.pe.debug.DebugCOFFSymbol.initDebugCOFFSymbol(DebugCOFFSymbol.java:164)
	at ghidra.app.util.bin.format.pe.debug.DebugCOFFSymbol.createDebugCOFFSymbol(DebugCOFFSymbol.java:142)
	at ghidra.app.util.bin.format.pe.FileHeader.processSymbols(FileHeader.java:373)
	at ghidra.app.util.bin.format.pe.FileHeader$$EnhancerByCGLIB$$c2578869.CGLIB$processSymbols$8(<generated>)
	at ghidra.app.util.bin.format.pe.FileHeader$$EnhancerByCGLIB$$c2578869$$FastClassByCGLIB$$d4f6268c.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:215)
	at generic.continues.ContinuesInterceptor.intercept(ContinuesInterceptor.java:39)
	at ghidra.app.util.bin.format.pe.FileHeader$$EnhancerByCGLIB$$c2578869.processSymbols(<generated>)
	at ghidra.app.util.bin.format.pe.NTHeader.parse(NTHeader.java:272)
	at ghidra.app.util.bin.format.pe.NTHeader.initNTHeader(NTHeader.java:94)
	at ghidra.app.util.bin.format.pe.NTHeader.createNTHeader(NTHeader.java:75)
	at ghidra.app.util.bin.format.pe.PortableExecutable.initPortableExecutable(PortableExecutable.java:110)
	at ghidra.app.util.bin.format.pe.PortableExecutable.createPortableExecutable(PortableExecutable.java:86)
	at ghidra.app.util.opinion.PeLoader.findSupportedLoadSpecs(PeLoader.java:79)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.getLoadSpec(AbstractLibrarySupportLoader.java:737)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.importLibrary(AbstractLibrarySupportLoader.java:667)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.importLibrary(AbstractLibrarySupportLoader.java:635)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadLibraries(AbstractLibrarySupportLoader.java:259)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:97)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:400)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:303)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

---------------------------------------------------
Build Date: 2021-Jan-20 1631 CET
Ghidra Version: 9.3
Java Home: C:\Program Files\Java\jdk-14.0.2
JVM Version: Oracle Corporation 14.0.2
OS: Windows 10 10.0 amd64
Workstation: 129.125.153.191
```

File: https://we.tl/t-4lWJBoCYiX

**Comment by ryanmkurtz** [comment]
I just imported this file with the latest master with no issues.  I did it on linux so it failed to find all of the external libraries (which was what I wanted to happen for debugging purposes).

**Comment by ryanmkurtz** [comment]
It sounds like we'll need you to isolate which DLL is causing the exception and upload that.  There isn't an issue with the attached binary.

**Comment by ryanmkurtz** [comment]
Closing due to inactivity.  We can reopen if you can provide more information on the DLL that was causing the issue.

**Comment by gynt** [comment]
> Closing due to inactivity. We can reopen if you can provide more information on the DLL that was causing the issue.

@ryanmkurtz Yes I will revisit this when I get to downloading ghidra 10
