### ISSUE TITLE
Debugger Branch Build did not have UI Components populate on Kali Linux

### ISSUE THREAD

**Issue by archcloudlabs** [NationalSecurityAgency/ghidra#2575]
**Describe the bug**
When building the debugger branch on Kali Linux some UI components (threads/stack/registers/etc...) do not populate. However, when building on Ubuntu 20.04 they do.

**To Reproduce**
1. Download the latest version of Kali.
2. Install appropriate depedencies (openjdk-11 & Gradle)
3. Execute build steps documented in Ghidra's [build guide](https://github.com/NationalSecurityAgency/ghidra/blob/master/DevGuide.md).
4. Load a test program to debug (/bin/ls)
5. Notice the UI components not become populated

**Expected behavior**
I expected the registers/stack/thread window to populate.

**Screenshots**
Screenshots below show the bug when building on Kali but not on Ubuntu.

![kali-debugger-debugger-registers-not-shown](https://user-images.githubusercontent.com/1250113/102735263-f17cf200-430f-11eb-968b-6d64f81c58bf.png)
*Kali 2020.04*

![ubuntu-20-debugger-registers-shown](https://user-images.githubusercontent.com/1250113/102735283-fcd01d80-430f-11eb-9842-8b3724f746be.png)
*Ubuntu 20.04*

**Attachments**
* No error output was identified.

**Environment (please complete the following information):**
 - OS: Kali 2020.4
 - Java Version: 
     - OpenJDK 11.0.9.1 2020-11-04
    - OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1)
    - OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1, mixed mode, sharing)

 - Ghidra Version: 9.3  Dev - debugger branch

**Additional context**
* Full video documenting exactly how I built on Kali can be found [here](https://www.youtube.com/watch?v=RDmqfjM7ZBo).

**Comment by d-millar** [comment]
Interesting - as you probably know, only the Object Provider and the Interpreter windows respond directly to the target being debugged.  All of the other windows (except the Breakpoints Provider, which is an sort of mixed case) are only populated if there is an active trace.  So, one immediate thing to check is whether the Autorecord setting in the pull-down menu of the Objects Provider accidentally got toggled off.  Assuming that isn't it, I would also try highlighting the process/inferior in the Object Provider and turning recording on by hand (R).  Any chance you're running these out of Eclipse and/or using the support ghidraDebug script to start up?  If Autorecord is actually on and the trace is failing for some reason, there might be a stack trace in the console in either case.  If so, we would really like to know!  In any case, I have a Kali VM so will take a shot at re-creating the error tomorrow and post back.  Thanks for the submission!

**Comment by saruman9** [comment]
Same error for ArchLinux OS: debugger works well on a laptop with ArchLinux, debugger could not record the trace on a desktop (with ArchLinux too).

<details>
  <summary>Error from desktop's ArchLinux OS</summary>

```
2020-12-21 11:21:37 ERROR (DebuggerModelServicePlugin) Could not query trace-recording opinions java.util.concurrent.CompletionException: java.util.NoSuchElementException: No mapper for target: <Local GdbModelTargetInferior: [Inferiors, [1]] in agent.gdb.model.impl.GdbModelImpl@4a013c93>
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:683)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
        at ghidra.app.plugin.core.debug.service.model.DebuggerModelServicePlugin.recordTargetBestOffer(DebuggerModelServicePlugin.java:363)
        at ghidra.app.plugin.core.debug.service.model.DebuggerModelServiceProxyPlugin.recordTargetBestOffer(DebuggerModelServiceProxyPlugin.java:367)
        at ghidra.app.plugin.core.debug.gui.objects.DebuggerObjectsProvider.startRecording(DebuggerObjectsProvider.java:1324)
        at ghidra.app.plugin.core.debug.gui.objects.ObjectContainer.checkAutoRecord(ObjectContainer.java:203)
        at ghidra.app.plugin.core.debug.gui.objects.ObjectContainer.propagateProvider(ObjectContainer.java:359)
        at ghidra.app.plugin.core.debug.gui.objects.ObjectContainer.lambda$getOffspring$4(ObjectContainer.java:194)
        at ghidra.async.seq.AsyncSequenceWithoutTemp.lambda$then$4(AsyncSequenceWithoutTemp.java:150)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
        at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
        at ghidra.async.seq.AsyncSequenceWithoutTemp.then(AsyncSequenceWithoutTemp.java:147)
        at ghidra.app.plugin.core.debug.gui.objects.ObjectContainer.getOffspring(ObjectContainer.java:192)
        at ghidra.app.plugin.core.debug.gui.objects.components.ObjectNode.generateChildren(ObjectNode.java:83)
        at docking.widgets.tree.GTreeSlowLoadingNode.generateChildrenNow(GTreeSlowLoadingNode.java:71)
        at docking.widgets.tree.GTreeSlowLoadingNode.generateChildren(GTreeSlowLoadingNode.java:56)
        at docking.widgets.tree.CoreGTreeNode.children(CoreGTreeNode.java:106)
        at docking.widgets.tree.GTreeNode.getChildren(GTreeNode.java:162)
        at docking.widgets.tree.tasks.GTreeSelectNodeByNameTask.findNodeByName(GTreeSelectNodeByNameTask.java:70)
        at docking.widgets.tree.tasks.GTreeSelectNodeByNameTask.run(GTreeSelectNodeByNameTask.java:57)
        at ghidra.util.worker.AbstractWorker$JobCallback.process(AbstractWorker.java:133)
        at ghidra.util.worker.AbstractWorker$JobCallback.process(AbstractWorker.java:123)
        at generic.concurrent.ConcurrentQ$CallbackCallable.call(ConcurrentQ.java:658)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.NoSuchElementException: No mapper for target: <Local GdbModelTargetInferior: [Inferiors, [1]] in agent.gdb.model.impl.GdbModelImpl@4a013c93>
        at ghidra.app.plugin.core.debug.service.model.DebuggerModelServicePlugin.lambda$recordTargetBestOffer$2(DebuggerModelServicePlugin.java:366)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
        ... 28 more
```

</details>

**Comment by d-millar** [comment]
@saruman9 that helps - looking at it now

**Comment by nsadeveloper789** [comment]
Looks like later versions of GDB print the auto-detected architecture *slightly* differently. Should be an easy fix.
