### ISSUE TITLE
Address in different spaces.

### ISSUE THREAD

**Issue by oziphantom** [NationalSecurityAgency/ghidra#2577]
**Describe the bug**
![image](https://user-images.githubusercontent.com/7146763/102869872-5bbca080-4490-11eb-83b3-3aeeaf90179d.png)

**To Reproduce**
Sorry I have no idea how it got into this state. But I can get out of it, if I bring up the reference editor to try and "fix" it I get this

```
Unexpected exception in Swing Update Manager
java.lang.IllegalArgumentException: Address are in different spaces FixedBank != Bank6
	at ghidra.program.model.address.OverlayAddressSpace.subtract(OverlayAddressSpace.java:103)
	at ghidra.program.model.address.GenericAddress.subtract(GenericAddress.java:144)
	at ghidra.program.database.function.FunctionManagerDB.getReferencedVariable(FunctionManagerDB.java:1273)
	at ghidra.program.database.references.ReferenceDBManager.getReferencedVariable(ReferenceDBManager.java:635)
	at ghidra.program.model.listing.CodeUnitFormat.getOperandRepresentationList(CodeUnitFormat.java:237)
	at ghidra.program.model.listing.CodeUnitFormat.getOperandRepresentationString(CodeUnitFormat.java:179)
	at ghidra.app.plugin.core.references.InstructionPanel.updateLabels(InstructionPanel.java:316)
	at ghidra.app.plugin.core.references.InstructionPanel.setCodeUnitLocation(InstructionPanel.java:194)
	at ghidra.app.plugin.core.references.EditReferencesProvider.init(EditReferencesProvider.java:556)
	at ghidra.app.plugin.core.references.EditReferencesProvider.getComponent(EditReferencesProvider.java:717)
	at docking.ComponentPlaceholder.getProviderComponent(ComponentPlaceholder.java:353)
	at docking.DockableComponent.initializeComponentPlaceholder(DockableComponent.java:108)
	at docking.DockableComponent.<init>(DockableComponent.java:93)
	at docking.ComponentPlaceholder.getComponent(ComponentPlaceholder.java:288)
	at docking.ComponentNode.getComponent(ComponentNode.java:273)
	at docking.DetachedWindowNode.update(DetachedWindowNode.java:430)
	at docking.RootNode.update(RootNode.java:317)
	at docking.DockingWindowManager.doUpdate(DockingWindowManager.java:1263)
	at ghidra.util.task.SwingUpdateManager.doWork(SwingUpdateManager.java:309)
	at ghidra.util.task.SwingUpdateManager.checkForWork(SwingUpdateManager.java:263)
	at ghidra.util.task.SwingUpdateManager.lambda$new$0(SwingUpdateManager.java:146)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at java.desktop/java.awt.Component.show(Component.java:1716)
	at java.desktop/java.awt.Component.setVisible(Component.java:1663)
	at java.desktop/java.awt.Window.setVisible(Window.java:1031)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005)
	at docking.DockingDialog.setVisible(DockingDialog.java:317)
	at docking.DockingWindowManager.lambda$doShowDialog$6(DockingWindowManager.java:1720)
	at ghidra.util.Swing.doRun(Swing.java:295)
	at ghidra.util.Swing.runNow(Swing.java:211)
	at ghidra.util.Swing.runNow(Swing.java:166)
	at ghidra.util.SystemUtilities.runSwingNow(SystemUtilities.java:253)
	at docking.DockingWindowManager.doShowDialog(DockingWindowManager.java:1724)
	at docking.DockingWindowManager.showDialog(DockingWindowManager.java:1756)
	at docking.DockingErrorDisplay.doShowDialog(DockingErrorDisplay.java:103)
	at docking.DockingErrorDisplay.lambda$showDialog$0(DockingErrorDisplay.java:91)
	at ghidra.util.Swing.runIfSwingOrRunLater(Swing.java:127)
	at ghidra.util.SystemUtilities.runIfSwingOrPostSwingLater(SystemUtilities.java:267)
	at docking.DockingErrorDisplay.showDialog(DockingErrorDisplay.java:90)
	at docking.DockingErrorDisplay.displayMessage(DockingErrorDisplay.java:78)
	at docking.DockingErrorDisplay.displayErrorMessage(DockingErrorDisplay.java:42)
	at ghidra.util.Msg.showError(Msg.java:333)
	at ghidra.SwingExceptionHandler.handleUncaughtException(SwingExceptionHandler.java:81)
	at ghidra.GhidraThreadGroup.handleUncaughtException(GhidraThreadGroup.java:68)
	at ghidra.GhidraThreadGroup.uncaughtException(GhidraThreadGroup.java:38)
	at java.desktop/java.awt.EventDispatchThread.processException(EventDispatchThread.java:222)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:214)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: C:\Program Files\Amazon Corretto\jdk11.0.6_10
JVM Version: Amazon.com Inc. 11.0.6
OS: Windows 10 10.0 amd64
Workstation: DESKTOP-0L7LS10

```
**Expected behavior**
let me open up references and fix it. Also I tried using C to clear the code bytes and then using D again but it goes straight back to the error.

**Screenshots**
see above

**Attachments**
sorry

**Environment (please complete the following information):**
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: C:\Program Files\Amazon Corretto\jdk11.0.6_10
JVM Version: Amazon.com Inc. 11.0.6
OS: Windows 10 10.0 amd64
Workstation: DESKTOP-0L7LS10

**Additional context**
this is a 6502 disassembly.

**Comment by dragonmacher** [comment]
It looks like the code does not handle the case where the function body is in multiple address spaces.   Perhaps this has to do with memory overlays?

**Comment by emteere** [comment]
It is possible there is a bug in the address lookup having to do with overlays.  Your overlay is in high memory, but I don't think that is quite the issue.

What does your memory map look like?
Do you have a real memory block, not an overlay in the default address space (are all your blocks in overlay spaces)?
Did you change the memory base address?

What is the exception log if you click on one of the *Error* Address... fields in the codebrowser?

**Comment by emteere** [comment]
@dragonmacher interesting question.
Is your function defined in one overlay memory space, and then flow into another?

**Comment by oziphantom** [comment]
My Memory map is 
![image](https://user-images.githubusercontent.com/7146763/102963026-35ecd580-453c-11eb-97fd-e9b651ddd5a1.png)

Bank 6 and Fixed Bank are the two banks it thinks the code that is in the Fixed Bank is in. 

I did as I continued to try everything discover that adding a Function to the FixedBank code did "fix it". 

Other fun issues with the memory map. You can't have somewhere that is read  and execute only and another bank in the same spot that is Write only. It will complain, so I had to make the Fixed Bank an overlay. Also the code analyzer won't see that when you write it writes to the write only bank and complains that you are writing to the read only bank. 

Not from that one as it no longer has the issue, but from another area that has the same problem I get when I click on the Red error area. 
```
2020-12-23 03:54:32 INFO  (FileCache) Starting cache cleanup: <snip>AppData\Local\Ghidra\fscache
2020-12-23 03:54:32 INFO  (FileCache) Finished cache cleanup, estimated storage used: 0  
2020-12-23 16:26:55 INFO  (LoggingInitialization) Using log config file: jar:file:/F:/ghidra_9.1.2_PUBLIC_20200212/ghidra_9.1.2_PUBLIC/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml  
2020-12-23 16:26:55 INFO  (LoggingInitialization) Using log file: <snip>.ghidra\.ghidra_9.1.2_PUBLIC\application.log
2020-12-23 16:26:55 INFO  (Preferences) Loading user preferences: <snip>.ghidra\.ghidra_9.1.2_PUBLIC\preferences
2020-12-23 16:26:57 INFO  (ClassSearcher) Class search complete (885 ms)
2020-12-23 16:26:57 INFO  (SSLContextInitializer) Initializing SSL Context
2020-12-23 16:26:57 INFO  (SecureRandomFactory) Initializing Random Number Generator...
2020-12-23 16:26:57 INFO  (SecureRandomFactory) Random Number Generator initialization complete: SHA1PRNG
2020-12-23 16:26:57 INFO  (ApplicationTrustManagerFactory) Trust manager disabled, cacerts have not been set
2020-12-23 16:26:57 INFO  (GhidraRun) User <snip> started Ghidra.
2020-12-23 16:26:58 DEBUG (RecoverySnapshotMgrPlugin) Recovery snapshot timer set to 5 minute(s)
2020-12-23 16:26:58 INFO  (DefaultProject) Opening project: F:\GhidraProjects\FE1
2020-12-23 16:27:23 INFO  (PackedDatabaseCache) Packed database cache: <snip>AppData\Local\Ghidra\packed-db-cache
2020-12-23 16:27:23 DEBUG (PackedDatabaseCache) Using cached packed database: F:\ghidra_9.1.2_PUBLIC_20200212\ghidra_9.1.2_PUBLIC\Ghidra\Features\Base\data\typeinfo\generic\generic_clib.gdt  
2020-12-23 16:34:06 DEBUG (ToolTaskManager) Exec Task Auto Analysis  
2020-12-23 16:34:06 DEBUG (ToolTaskManager)   task finish (0.019 secs)  
2020-12-23 16:34:06 DEBUG (ToolTaskManager)   task complete (0.021 secs)  
2020-12-23 16:34:07 WARN  (DecompileCallback) Decompiling Bank6::8b95, pcode error at e759: Disassembly not permitted within uninitialized memory block  
2020-12-23 16:34:49 WARN  (DecompileCallback) Decompiling Bank6::84f6, pcode error at c225: Disassembly not permitted within uninitialized memory block
2020-12-23 16:34:55 ERROR (ErrorFieldMouseHandler) Listing Field Exception:Exception occured while rendering 'Operands' field
java.lang.IllegalArgumentException: Address are in different spaces FixedBank != Bank6
	at ghidra.program.model.address.OverlayAddressSpace.subtract(OverlayAddressSpace.java:103)
	at ghidra.program.model.address.GenericAddress.subtract(GenericAddress.java:144)
	at ghidra.program.database.function.FunctionManagerDB.getReferencedVariable(FunctionManagerDB.java:1273)
	at ghidra.program.database.references.ReferenceDBManager.getReferencedVariable(ReferenceDBManager.java:635)
	at ghidra.program.model.listing.CodeUnitFormat.getOperandRepresentationList(CodeUnitFormat.java:237)
	at ghidra.app.util.viewer.field.OperandFieldHelper.getFieldForInstruction(OperandFieldHelper.java:403)
	at ghidra.app.util.viewer.field.OperandFieldHelper.getField(OperandFieldHelper.java:196)
	at ghidra.app.util.viewer.field.OperandFieldFactory.getField(OperandFieldFactory.java:59)
	at ghidra.app.util.viewer.format.Row.getLayout(FieldFormatModel.java:502)
	at ghidra.app.util.viewer.format.FieldFormatModel.addLayouts(FieldFormatModel.java:102)
	at ghidra.app.util.viewer.listingpanel.ProgramBigListingModel.doGetLayout(ProgramBigListingModel.java:189)
	at ghidra.app.util.viewer.listingpanel.ProgramBigListingModel.getLayout(ProgramBigListingModel.java:124)
	at ghidra.app.util.viewer.listingpanel.ListingModelAdapter.getLayout(ListingModelAdapter.java:131)
	at docking.widgets.fieldpanel.internal.AnchoredLayoutHandler.getNextLayout(AnchoredLayoutHandler.java:205)
	at docking.widgets.fieldpanel.internal.AnchoredLayoutHandler.fillLayoutsForward(AnchoredLayoutHandler.java:170)
	at docking.widgets.fieldpanel.internal.AnchoredLayoutHandler.fillOutLayouts(AnchoredLayoutHandler.java:130)
	at docking.widgets.fieldpanel.internal.AnchoredLayoutHandler.shiftView(AnchoredLayoutHandler.java:112)
	at docking.widgets.fieldpanel.FieldPanel.scrollView(FieldPanel.java:115)
	at docking.widgets.fieldpanel.FieldPanel.goTo(FieldPanel.java:792)
	at docking.widgets.fieldpanel.FieldPanel.goTo(FieldPanel.java:776)
	at ghidra.app.util.viewer.listingpanel.ListingPanel.goTo(ListingPanel.java:547)
	at ghidra.app.plugin.core.codebrowser.CodeViewerProvider.setLocation(CodeViewerProvider.java:669)
	at ghidra.app.plugin.core.codebrowser.CodeBrowserPlugin.processEvent(CodeBrowserPlugin.java:399)
	at ghidra.framework.plugintool.Plugin.eventSent(Plugin.java:324)
	at ghidra.framework.plugintool.mgr.EventManager.sendEvents(EventManager.java:263)
	at ghidra.framework.plugintool.mgr.EventManager.fireEvent(EventManager.java:208)
	at ghidra.framework.plugintool.PluginTool.firePluginEvent(PluginTool.java:462)
	at ghidra.framework.plugintool.Plugin.firePluginEvent(Plugin.java:476)
	at ghidra.app.plugin.core.gotoquery.GoToServicePlugin$DefaultNavigatable.goTo(GoToServicePlugin.java:115)
	at ghidra.app.plugin.core.navigation.NavigationHistoryPlugin.navigate(NavigationHistoryPlugin.java:265)
	at ghidra.app.plugin.core.navigation.NavigationHistoryPlugin.previous(NavigationHistoryPlugin.java:237)
	at ghidra.app.plugin.core.navigation.NextPrevAddressPlugin$NextPreviousAction.actionPerformed(NextPrevAddressPlugin.java:341)
	at docking.DockingActionProxy.actionPerformed(DockingActionProxy.java:47)
	at docking.menu.ToolBarItemManager.lambda$actionPerformed$0(ToolBarItemManager.java:219)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: C:\Program Files\Amazon Corretto\jdk11.0.6_10
JVM Version: Amazon.com Inc. 11.0.6
OS: Windows 10 10.0 amd64
Workstation: DESKTOP-0L7LS10
```

**Comment by ghidra1** [comment]
A Function and its entry point must reside within a single memory block.  We may not have checks that catch this unsupported condition.

**Comment by oziphantom** [comment]
They are. The function above is e759 to e827 which is wholly contained within the fixed bank. No part of it is in another bank, overlay or code section. 

I think what the issue might be is Ghidra doesn't understand you can "jump" to a function. So it thinks because things in Bank6 "jmp $e759" that e759 is now part of "its function". When they are not, they are completely in separate banks and its an trivial optimisation. 

ie. 

jsr $e759
rts

just

jmp $e759 ; this function will rts and return for me

thus you save 8 clocks and a byte.

Ghidra should have checks in its logic that force separate functions along memory map boundaries. i.e if two lines of code even if they Jump or Branch to each other are in different sections of a memory map they are not part of the same function. 
Probably an edge case of where the PC naturally flows through across a boundary thus making them the same "function", but I think slotting a label or function header at the start and treating them as two separate functions would be fine in the very rare case.

**Comment by ghidra1** [comment]
I would guess that the function's entry point is not contained within the body (based upon address space).  It would require debugging to understand how the entry point was establish separate from the body.  Do you recall how the function and its body was established?  Overlays are not used extensively so you indicated we should improve function body discovery to:

- Do not traverse memory block boundaries when computing function body and do not permit an explicitly specified body (e.g., selection based) to span such boundaries. 

I believe there is already a restriction that the entry point reside within the function body.

**Comment by oziphantom** [comment]
I'm trying to narrow down and make a test file so I can be sure what is the actual cause.
