### ISSUE TITLE
OOME loading macOS 11 dyld shared cache

### ISSUE THREAD

**Issue by tellowkrinkle** [NationalSecurityAgency/ghidra#2587]
**Describe the bug**
Loading macOS 11's DYLD shared cache results in an OOME (Required array length too large)

**To Reproduce**
1. Launch ghidra with a large heap size like 8GB (or you'll get an out of heap error instead)
2. Get the `dyld_shared_cache_x86_64` from `/System/Library/dyld` on macOS 11.0.1 build 20B29 (SHA: 787e69e256bbe195d2f977b33371c8cab03e3f06)
3. Try to add it to your project
4. The loader throws an OOME (Required array length too large) and fails to import

**Expected behavior**
Ghidra loads the (2.26gb) shared cache

**Attachments**
<details><summary>Stack Trace</summary>

```
Required array length too large
java.lang.OutOfMemoryError: Required array length too large
	at java.base/jdk.internal.util.ArraysSupport.hugeLength(ArraysSupport.java:619)
	at java.base/jdk.internal.util.ArraysSupport.newLength(ArraysSupport.java:613)
	at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:100)
	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:130)
	at java.base/java.io.OutputStream.write(OutputStream.java:127)
	at ghidra.file.formats.ios.dyldcache.FixupMacho32bitArmOffsets.fix(FixupMacho32bitArmOffsets.java:163)
	at ghidra.file.formats.ios.dyldcache.DyldCacheFileSystem.getData(DyldCacheFileSystem.java:72)
	at ghidra.formats.gfilesystem.GFileSystemBase.getInputStream(GFileSystemBase.java:149)
	at ghidra.formats.gfilesystem.FileSystemService.getCacheFile(FileSystemService.java:267)
	at ghidra.formats.gfilesystem.FileSystemService.getMD5(FileSystemService.java:418)
	at ghidra.formats.gfilesystem.FileSystemService.getFullyQualifiedFSRL(FileSystemService.java:796)
	at ghidra.plugins.importer.batch.BatchInfo.processFS(BatchInfo.java:337)
	at ghidra.plugins.importer.batch.BatchInfo.processAsFS(BatchInfo.java:312)
	at ghidra.plugins.importer.batch.BatchInfo.doAddFile(BatchInfo.java:226)
	at ghidra.plugins.importer.batch.BatchInfo.addFile(BatchInfo.java:194)
	at ghidra.plugins.importer.batch.BatchInfo.doAddFiles(BatchInfo.java:491)
	at ghidra.plugins.importer.batch.BatchInfo$AddFilesRunnable.monitoredRun(BatchInfo.java:528)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:303)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

---------------------------------------------------
Build Date: 2020-Dec-15 1409 EST
Ghidra Version: 9.2.1
Java Home: /Library/Java/JavaVirtualMachines/jdk-14.jdk/Contents/Home
JVM Version: Oracle Corporation 14
OS: Mac OS X 10.16 x86_64
Workstation: localhost
```
</details>

**Environment (please complete the following information):**
 - OS: macOS 11.0.1 build 20B29
 - Java Version: 14+36-1461
 - Ghidra Version: 9.2.1

**Comment by ryanmkurtz** [comment]
Fixed by 147e6b8f136363a5adf40ba64d6b400304954bf1
