### ISSUE TITLE
Uncaught exception when Edit Function Sigature of thiscall functions

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#2601]
**Describe the bug**
When I click "Edit Function Signature" on `__thiscall` functions of a Windows exe or dll, Ghidra throws an uncaught exception: "AssertException - Attempted to remove parameters when not allowed".

**To Reproduce**
1. Download https://msdl.microsoft.com/download/symbols/kernelbase.dll/E6477CCE214000/kernelbase.dll, and then rename the downloaded file to kernelbase.dll
2. Analyze this file in Ghidra (don't load the PDB file)
3. Go to function FUN_1010023e
4. On the Decompile panel, right click on the function signature, and then click "Edit Function Signature"
5. See error

**Expected behavior**
Function signature editor should show up.

**Screenshots**
![error](https://user-images.githubusercontent.com/16713498/103413453-90c5a300-4bb4-11eb-958d-7aa03ef14bb6.png)

**Attachments**
You can download the binary file from https://msdl.microsoft.com/download/symbols/kernelbase.dll/E6477CCE214000/kernelbase.dll (sha256: 8f82da5fa78814ab230928d5b5611222190df58688ba76ec24ac7e100cf551aa)

**Environment (please complete the following information):**
 - OS: Linux 5.9.0-kali5-amd64 amd64
 - Java Version: Debian 11.0.9.1
 - Ghidra Version: 9.3 (master branch, 881282d96a1712e94958de3f2820497a55c045c7), and 9.2.1 PUBLIC

**Stack trace**
```
Attempted to remove parameters when not allowed.
ghidra.util.exception.AssertException: Attempted to remove parameters when not allowed.
	at ghidra.app.plugin.core.function.editor.FunctionEditorModel.removeParameters(FunctionEditorModel.java:698)
	at ghidra.app.plugin.core.decompile.actions.SpecifyCPrototypeAction.verifyDynamicEditorModel(SpecifyCPrototypeAction.java:82)
	at ghidra.app.plugin.core.decompile.actions.SpecifyCPrototypeAction.decompilerActionPerformed(SpecifyCPrototypeAction.java:181)
	at ghidra.app.plugin.core.decompile.actions.AbstractDecompilerAction.lambda$actionPerformed$1(AbstractDecompilerAction.java:66)
	at ghidra.app.plugin.core.decompile.DecompilerActionContext.performAction(DecompilerActionContext.java:116)
	at ghidra.app.plugin.core.decompile.actions.AbstractDecompilerAction.actionPerformed(AbstractDecompilerAction.java:65)
	at docking.PopupMenuHandler$1.run(PopupMenuHandler.java:61)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by dev747368** [comment]
In this case, it the function in the listing has no parameter info, and the function signature in the decompiler has a richer signature (this call and 2 parameters).

**Comment by ghidra1** [comment]
There is a bug in the editor model manipulation performed by the `SpecifyCPrototypeAction`.  I was able to reproduce with any __thiscall method which had not locked in its parameters.

**Comment by xiaoyinl** [comment]
This has been fixed in master. Thank you!
