### ISSUE TITLE
headless script path resolution in Ghidra 9.2+

### ISSUE THREAD

**Issue by jstucke** [NationalSecurityAgency/ghidra#2663]
### **Describe the bug**

In Ghidra >= 9.2 I get errors when trying to run scripts with `analyzeHeadless`, lying in any of the script directories. The Errors do not occur when stating the absolute path of the script, with older versions (e.g. 9.1.2) or when running the script through the GUI. There seems to be a problem with path resolution (?)

### **To Reproduce**

Running a script in headless mode (i.e. `analyzeHeadless -postScript <name-of-script>`, the input binary does not matter):

e.g. the demo script [ `external_module_callee.py` ](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Python/ghidra_scripts/external_module_callee.py)

```
> analyzeHeadless test_project_dir test_project -import ./hello_world.elf -postScript external_module_callee.py -deleteProject
(...)
ERROR Abort due to Headless analyzer error: Invalid script: external_module_callee.py (HeadlessAnalyzer) java.lang.IllegalArgumentException: Invalid script: external_module_callee.py
	at ghidra.app.util.headless.HeadlessAnalyzer.checkScript(HeadlessAnalyzer.java:770)
	at ghidra.app.util.headless.HeadlessAnalyzer.checkScriptsList(HeadlessAnalyzer.java:783)
	at ghidra.app.util.headless.HeadlessAnalyzer.compileScripts(HeadlessAnalyzer.java:817)
	at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:406)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:121)
	at ghidra.GhidraLauncher.main(GhidraLauncher.java:82)
```

Full log: <details>

```
> /opt/ghidra_9.2.1_PUBLIC/support/analyzeHeadless test_project_dir test_project -import ./hello_world.elf -postScript external_module_callee.py -deleteProject
openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS, mixed mode)
INFO  Using log config file: jar:file:/opt/ghidra_9.2.1_PUBLIC/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)  
INFO  Using log file: /home/jstucke/.ghidra/.ghidra_9.2.1_PUBLIC/application.log (LoggingInitialization)  
INFO  Loading user preferences: /home/jstucke/.ghidra/.ghidra_9.2.1_PUBLIC/preferences (Preferences)  
INFO  Loading previous preferences: /home/jstucke/.ghidra/.ghidra_9.1.2_PUBLIC/preferences (Preferences)  
INFO  Class search complete (537 ms) (ClassSearcher)  
INFO  Initializing SSL Context (SSLContextInitializer)  
INFO  Initializing Random Number Generator... (SecureRandomFactory)  
INFO  Random Number Generator initialization complete: NativePRNGNonBlocking (SecureRandomFactory)  
INFO  Trust manager disabled, cacerts have not been set (ApplicationTrustManagerFactory)  
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender (file:/opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/Base/lib/org.apache.felix.framework-6.0.3.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  HEADLESS Script Paths:
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/FileFormats/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/Python/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Processors/DATA/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/FunctionID/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/Decompiler/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/BytePatterns/ghidra_scripts
    /home/jstucke/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/VersionTracking/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Processors/PIC/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/GnuDemangler/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/Base/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Processors/8051/ghidra_scripts (HeadlessAnalyzer)  
ERROR REPORT SCRIPT ERROR: external_module_callee.py : Script not found: external_module_callee.py (HeadlessAnalyzer)  
ERROR Abort due to Headless analyzer error: Invalid script: external_module_callee.py (HeadlessAnalyzer) java.lang.IllegalArgumentException: Invalid script: external_module_callee.py
	at ghidra.app.util.headless.HeadlessAnalyzer.checkScript(HeadlessAnalyzer.java:770)
	at ghidra.app.util.headless.HeadlessAnalyzer.checkScriptsList(HeadlessAnalyzer.java:783)
	at ghidra.app.util.headless.HeadlessAnalyzer.compileScripts(HeadlessAnalyzer.java:817)
	at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:406)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:121)
	at ghidra.GhidraLauncher.main(GhidraLauncher.java:82)

```

</details>

### **Expected behavior**

I would expect the script to work just like in the GUI, Ghidra 9.1.2 or when using the absolute path:

Full log 9.1.2: <details>

```
/opt/ghidra_9.1.2_PUBLIC/support/analyzeHeadless test_project_dir test_project -import ./hello_world.elf -postScript external_module_callee.py -deleteProject
openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS, mixed mode)
INFO  Using log config file: jar:file:/opt/ghidra_9.1.2_PUBLIC/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)  
INFO  Using log file: /home/jstucke/.ghidra/.ghidra_9.1.2_PUBLIC/application.log (LoggingInitialization)  
INFO  Loading user preferences: /home/jstucke/.ghidra/.ghidra_9.1.2_PUBLIC/preferences (Preferences)  
INFO  Loading previous preferences: /home/jstucke/.ghidra/.ghidra_9.2.1_PUBLIC/preferences (Preferences)  
INFO  Class search complete (510 ms) (ClassSearcher)  
INFO  Initializing SSL Context (SSLContextInitializer)  
INFO  Initializing Random Number Generator... (SecureRandomFactory)  
INFO  Random Number Generator initialization complete: NativePRNGNonBlocking (SecureRandomFactory)  
INFO  Trust manager disabled, cacerts have not been set (ApplicationTrustManagerFactory)  
INFO  HEADLESS Script Paths:
    /home/jstucke/ghidra_scripts
    /opt/ghidra_9.1.2_PUBLIC/Ghidra/Features/Base/ghidra_scripts
    /opt/ghidra_9.1.2_PUBLIC/Ghidra/Features/BytePatterns/ghidra_scripts
    /opt/ghidra_9.1.2_PUBLIC/Ghidra/Features/Decompiler/ghidra_scripts
    /opt/ghidra_9.1.2_PUBLIC/Ghidra/Features/FileFormats/ghidra_scripts
    /opt/ghidra_9.1.2_PUBLIC/Ghidra/Features/FunctionID/ghidra_scripts
    /opt/ghidra_9.1.2_PUBLIC/Ghidra/Features/GnuDemangler/ghidra_scripts
    /opt/ghidra_9.1.2_PUBLIC/Ghidra/Features/Python/ghidra_scripts
    /opt/ghidra_9.1.2_PUBLIC/Ghidra/Features/VersionTracking/ghidra_scripts
    /opt/ghidra_9.1.2_PUBLIC/Ghidra/Processors/8051/ghidra_scripts
    /opt/ghidra_9.1.2_PUBLIC/Ghidra/Processors/DATA/ghidra_scripts
    /opt/ghidra_9.1.2_PUBLIC/Ghidra/Processors/PIC/ghidra_scripts (HeadlessAnalyzer)  
INFO  HEADLESS: execution starts (HeadlessAnalyzer)  
INFO  Creating temporary project: /home/jstucke/test/ghidra/test_project_dir/test_project (HeadlessAnalyzer)  
INFO  Creating project: /home/jstucke/test/ghidra/test_project_dir/test_project (DefaultProject)  
INFO  REPORT: Processing input files:  (HeadlessAnalyzer)  
INFO       project: /home/jstucke/test/ghidra/test_project_dir/test_project (HeadlessAnalyzer)  
INFO  IMPORTING: /home/jstucke/test/ghidra/./hello_world.elf (HeadlessAnalyzer)  
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sf.cglib.core.ReflectUtils$2 (file:/opt/ghidra_9.1.2_PUBLIC/Ghidra/Framework/Generic/lib/cglib-nodep-2.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of net.sf.cglib.core.ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  REPORT: Import succeeded with language "ARM:LE:32:v8" and cspec "default" for file: /home/jstucke/test/ghidra/./hello_world.elf (HeadlessAnalyzer)  
INFO  ANALYZING all memory and code: /home/jstucke/test/ghidra/./hello_world.elf (HeadlessAnalyzer)  
INFO  Packed database cache: /tmp/jstucke-Ghidra/packed-db-cache (PackedDatabaseCache)  
INFO  REPORT: Analysis succeeded for file: /home/jstucke/test/ghidra/./hello_world.elf (HeadlessAnalyzer)  
INFO  SCRIPT: /opt/ghidra_9.1.2_PUBLIC/Ghidra/Features/Python/ghidra_scripts/external_module_callee.py (HeadlessAnalyzer)  
hello_world.elf
hello_world.elf
INFO  ANALYZING changes made by post scripts: /home/jstucke/test/ghidra/./hello_world.elf (HeadlessAnalyzer)  
INFO  REPORT: Post-analysis succeeded for file: /home/jstucke/test/ghidra/./hello_world.elf (HeadlessAnalyzer)  
INFO  REPORT: Save succeeded for file: /hello_world.elf (HeadlessAnalyzer) 
```

</details>

Full log absolute path: <details>

```
/opt/ghidra_9.2.1_PUBLIC/support/analyzeHeadless test_project_dir test_project -import ./hello_world.elf -postScript /opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/Python/ghidra_scripts/external_module_callee.py -deleteProject
openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS, mixed mode)
INFO  Using log config file: jar:file:/opt/ghidra_9.2.1_PUBLIC/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)  
INFO  Using log file: /home/jstucke/.ghidra/.ghidra_9.2.1_PUBLIC/application.log (LoggingInitialization)  
INFO  Loading user preferences: /home/jstucke/.ghidra/.ghidra_9.2.1_PUBLIC/preferences (Preferences)  
INFO  Loading previous preferences: /home/jstucke/.ghidra/.ghidra_9.1.2_PUBLIC/preferences (Preferences)  
INFO  Class search complete (536 ms) (ClassSearcher)  
INFO  Initializing SSL Context (SSLContextInitializer)  
INFO  Initializing Random Number Generator... (SecureRandomFactory)  
INFO  Random Number Generator initialization complete: NativePRNGNonBlocking (SecureRandomFactory)  
INFO  Trust manager disabled, cacerts have not been set (ApplicationTrustManagerFactory)  
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender (file:/opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/Base/lib/org.apache.felix.framework-6.0.3.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  HEADLESS Script Paths:
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/FileFormats/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/Python/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Processors/DATA/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/FunctionID/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/Decompiler/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/BytePatterns/ghidra_scripts
    /home/jstucke/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/VersionTracking/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Processors/PIC/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/GnuDemangler/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/Base/ghidra_scripts
    /opt/ghidra_9.2.1_PUBLIC/Ghidra/Processors/8051/ghidra_scripts (HeadlessAnalyzer)  
INFO  HEADLESS: execution starts (HeadlessAnalyzer)  
INFO  Creating temporary project: /home/jstucke/test/ghidra/test_project_dir/test_project (HeadlessAnalyzer)  
INFO  Creating project: /home/jstucke/test/ghidra/test_project_dir/test_project (DefaultProject)  
INFO  REPORT: Processing input files:  (HeadlessAnalyzer)  
INFO       project: /home/jstucke/test/ghidra/test_project_dir/test_project (HeadlessAnalyzer)  
INFO  IMPORTING: /home/jstucke/test/ghidra/./hello_world.elf (HeadlessAnalyzer)  
INFO  REPORT: Import succeeded with language "ARM:LE:32:v8" and cspec "default" for file: /home/jstucke/test/ghidra/./hello_world.elf (HeadlessAnalyzer)  
INFO  ANALYZING all memory and code: /home/jstucke/test/ghidra/./hello_world.elf (HeadlessAnalyzer)  
INFO  Packed database cache: /tmp/jstucke-Ghidra/packed-db-cache (PackedDatabaseCache)  
INFO  REPORT: Analysis succeeded for file: /home/jstucke/test/ghidra/./hello_world.elf (HeadlessAnalyzer)  
INFO  SCRIPT: /opt/ghidra_9.2.1_PUBLIC/Ghidra/Features/Python/ghidra_scripts/external_module_callee.py (HeadlessAnalyzer)  
hello_world.elf
hello_world.elf
INFO  ANALYZING changes made by post scripts: /home/jstucke/test/ghidra/./hello_world.elf (HeadlessAnalyzer)  
INFO  REPORT: Post-analysis succeeded for file: /home/jstucke/test/ghidra/./hello_world.elf (HeadlessAnalyzer)  
INFO  REPORT: Save succeeded for file: /hello_world.elf (HeadlessAnalyzer)
```

</details>

### **Environment:**
 - OS: Linux Mint 20
 - Java Version: OpenJDK Runtime Environment Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS)
 - Ghidra Version: 9.2.1 (the pre-compiled release from the official website)

### **Additional context**
Maybe I'm doing something wrong? Could it be some old configuration from an older Ghidra version?

**Comment by ryanmkurtz** [comment]
Duplicate of #2561

**Comment by jstucke** [comment]
> Duplicate of #2561

You're absolutely right. I tried to search the issues but must have missed it -> closing
