### ISSUE TITLE
NPE when importing a .NET executable on Windows

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#2699]
**Describe the bug**
When I import the attached .NET executable on Windows 10, it fails with a Null Pointer Exception. This is only reproducible with the latest master branch, running on Windows. It works fine on Linux.

**To Reproduce**
1. Download the attached file.
2. Go to File -> Import File ...
3. Choose the downloaded SecureDNS.exe

**Expected behavior**
The file should be imported without errors.

**Screenshots**
![err importing](https://user-images.githubusercontent.com/16713498/106262052-64f21780-625d-11eb-8c74-b44d3c4fe587.png)

**Attachments**
[SecureDNS.zip](https://github.com/NationalSecurityAgency/ghidra/files/5893090/SecureDNS.zip)

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - Java Version: Oracle Corporation 11.0.10
 - Ghidra Version: 9.3 DEV master 4798052

**Additional context**
stack:
```
java.lang.NullPointerException
	at ghidra.app.util.opinion.PeLoader.getILEntryPoint(PeLoader.java:813)
	at ghidra.app.util.opinion.PeLoader.processEntryPoints(PeLoader.java:761)
	at ghidra.app.util.opinion.PeLoader.load(PeLoader.java:150)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.importLibrary(AbstractLibrarySupportLoader.java:685)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.importLibrary(AbstractLibrarySupportLoader.java:635)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadLibraries(AbstractLibrarySupportLoader.java:259)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:97)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:400)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:353)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:303)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by xiaoyinl** [comment]
Fixed by abcbe74086917d2a5e1e2a5a09b2fcb05543c33a. Thank you!
