### ISSUE TITLE
Error importing PE file IndexOutOfBoundsException: Specified length extends beyond file bytes length

### ISSUE THREAD

**Issue by 0xBEEEF** [NationalSecurityAgency/ghidra#2737]
**Describe the bug**
When importing one of the exe files contained in the following [archive](https://web.archive.org/web/20180612140159/http://pod.nicode.net/patches/gs2_dx5.zip), I get the following error message. It does not matter which exe file I use it does not work. I always get the following error.

But what is interesting: In the very old version 9.0 the file can be imported without problems. But in all newer versions the error comes immediately, as soon as one imports the file.

**To Reproduce**
1. simply import one of the exe files from the linked zip archive
2. confirm the appearing processor / compiler dialog with OK
3. the following error is displayed.

**Expected behavior**
The files must be importable without errors, like in the old version 9.0.

**Attachments**
Enclosed is the detailed error log:

Error Importing File: Error importing file:  java.lang.IndexOutOfBoundsException: Specified length extends beyond file bytes length
	at ghidra.program.database.mem.MemoryMapDB.checkFileBytesRange(MemoryMapDB.java:678)
	at ghidra.program.database.mem.MemoryMapDB.createInitializedBlock(MemoryMapDB.java:641)
	at ghidra.app.util.MemoryBlockUtils.createInitializedBlock(MemoryBlockUtils.java:227)
	at ghidra.app.util.opinion.PeLoader.processMemoryBlocks(PeLoader.java:662)
	at ghidra.app.util.opinion.PeLoader.load(PeLoader.java:121)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:400)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:349)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:88)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Environment (please complete the following information):**
Build Date: 2020-Dec-29 1701 EST
Ghidra Version: 9.2.2
Java Home: C:\Program Files\Amazon Corretto\jdk11.0.9_12
JVM Version: Amazon.com Inc. 11.0.9.1
OS: Windows 10 10.0 amd64

**Comment by ryanmkurtz** [comment]
I could not reproduce this in 9.3-DEV.  Are you able to build the master branch of the Ghidra repo and try again?

**Comment by ryanmkurtz** [comment]
Confirmed duplicate of #2496.

**Comment by 0xBEEEF** [comment]
True indeed. In the 9.3 Dev version it works. Then everything is good! Sorry, I could have checked that before of course.
