### ISSUE TITLE
[Debugger?] AbstractRStarConstraintsTree raises ClassCastException after ~2000 new nodes

### ISSUE THREAD

**Issue by Tim---** [NationalSecurityAgency/ghidra#2760]
**Describe the bug**
I am working on a Java script to create Traces. So I create a Thread object, then start writing the Register values at each tick when a change occurs. This works well for small traces but for bigger traces, I get an exception after the first few register writes.

The problem seems related to `ghidra.util.database.spatial.AbstractRStarConstraintsTree`, and how it handles the overflows.

I attached a minimal example with the exception below.

**To Reproduce**
Run the following script:
```java
import java.math.BigInteger;
import com.google.common.collect.Range;
import ghidra.app.script.GhidraScript;
import ghidra.app.services.DebuggerTraceManagerService;
import ghidra.program.model.lang.*;
import ghidra.program.util.DefaultLanguageService;
import ghidra.trace.database.DBTrace;
import ghidra.trace.model.Trace;
import ghidra.trace.model.memory.*;
import ghidra.trace.model.thread.TraceThread;
import ghidra.trace.model.thread.TraceThreadManager;
import ghidra.util.database.UndoableTransaction;

public class PopulateTraceLocal3 extends GhidraScript {
	@Override
	protected void run() throws Exception {
		// Some setup to create a new Trace
		LanguageService langServ = DefaultLanguageService.getLanguageService();
		Language lang = langServ.getLanguage(new LanguageID("x86:LE:64:default"));
		CompilerSpec cspec = lang.getDefaultCompilerSpec();
		Trace trace = new DBTrace("mytrace", cspec, this);
		TraceMemoryManager memory = trace.getMemoryManager();
		TraceThreadManager threads = trace.getThreadManager();
		DebuggerTraceManagerService manager = state.getTool().getService(DebuggerTraceManagerService.class);

		try (UndoableTransaction tid = UndoableTransaction.start(trace, "Doing things", true)) {
			// Create a thread with lifetime 1 -> 10000
			TraceThread th = threads.addThread("t0", Range.closed(1L, 10000L));
			TraceMemoryRegisterSpace regspace = memory.getMemoryRegisterSpace(th, true);
			Register rip = lang.getRegister("RIP");
			
			// For each tick, write RIP with a dummy value
			for(int tick = 1; tick < 2000; tick++) {
				println("RIP@" + tick);
				RegisterValue value = new RegisterValue(rip, BigInteger.valueOf(tick));
				regspace.setValue(tick, value); // CRASH HERE
			}
		}

		manager.openTrace(trace);
		manager.activateTrace(trace);
		return;
	}
}
```

The first 1942 writes go well, then:
```
ERROR PopulateTraceLocal3.java: Error running script: PopulateTraceLocal3.java
java.lang.ClassCastException: class ghidra.trace.database.memory.DBTraceMemoryStateEntry cannot be cast to class ghidra.util.database.spatial.DBTreeNodeRecord (ghidra.trace.database.memory.DBTraceMemoryStateEntry and ghidra.util.database.spatial.DBTreeNodeRecord are in unnamed module of loader ghidra.GhidraClassLoader @5caf905d) java.lang.ClassCastException: class ghidra.trace.database.memory.DBTraceMemoryStateEntry cannot be cast to class ghidra.util.database.spatial.DBTreeNodeRecord (ghidra.trace.database.memory.DBTraceMemoryStateEntry and ghidra.util.database.spatial.DBTreeNodeRecord are in unnamed module of loader ghidra.GhidraClassLoader @5caf905d)
	at ghidra.util.database.spatial.AbstractRStarConstraintsTree.doInsert(AbstractRStarConstraintsTree.java:432)
	at ghidra.util.database.spatial.AbstractRStarConstraintsTree.doReInsert(AbstractRStarConstraintsTree.java:540)
	at ghidra.util.database.spatial.AbstractRStarConstraintsTree.doOverflowTreatment(AbstractRStarConstraintsTree.java:489)
	at ghidra.util.database.spatial.AbstractRStarConstraintsTree.doInsert(AbstractRStarConstraintsTree.java:456)
	at ghidra.util.database.spatial.AbstractRStarConstraintsTree.doInsertData(AbstractRStarConstraintsTree.java:414)
	at ghidra.util.database.spatial.AbstractConstraintsTreeSpatialMap.put(AbstractConstraintsTreeSpatialMap.java:49)
	at ghidra.trace.database.map.DBTraceAddressSnapRangePropertyMapSpace.put(DBTraceAddressSnapRangePropertyMapSpace.java:105)
	at ghidra.trace.database.map.DBTraceAddressSnapRangePropertyMapSpace.put(DBTraceAddressSnapRangePropertyMapSpace.java:1)
	at ghidra.trace.model.map.TraceAddressSnapRangePropertyMapOperations.put(TraceAddressSnapRangePropertyMapOperations.java:42)
	at ghidra.trace.database.memory.DBTraceMemorySpace.doSetState(DBTraceMemorySpace.java:320)
	at ghidra.trace.database.memory.DBTraceMemorySpace.putBytes(DBTraceMemorySpace.java:601)
	at ghidra.trace.model.memory.TraceMemoryRegisterSpace.setValue(TraceMemoryRegisterSpace.java:61)
	at PopulateTraceLocal3.run(PopulateTraceLocal3.java:35)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:379)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:234)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:212)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:47)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$0(TaskRunner.java:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
  (RunScriptTask.java:55) 
```

**Expected behavior**
Not crash, unless I'm doing something wrong.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Java Version: openjdk 11.0.10 2021-01-19
 - Ghidra Version: debugger branch

**Comment by nsadeveloper789** [comment]
Oh nice. I had been seeing this with the Modules/Sections manager in manual testing, but had not been able to reproduce it in unit testing. Your example should get me there. Thanks!

**Comment by nsadeveloper789** [comment]
I've got it fixed. Assuming tests go well, it should be pushed soon.

**Comment by Tim---** [comment]
Well that was quick, thanks ! 

I'll wait for the fix and close if it works.
