### ISSUE TITLE
Cannot invoke "ghidra.program.model.data.DataType.getLength()" because "componentDt" is null

### ISSUE THREAD

**Issue by RenaKunisaki** [NationalSecurityAgency/ghidra#2781]
**Describe the bug**
Attempting to expand items in the Data Type Viewer causes an error message popup.

**To Reproduce**
1. Open attached project
2. In Data Type Manager, expand "main.dol"
3. Expand SFA
4. Try to expand Audio or any category after it

I'm not sure exactly what led to this; it happened while I was dragging and dropping categories to reorganize them.

**Expected behavior**
Open the category.

**Screenshots**
The error message:
```
Cannot invoke "ghidra.program.model.data.DataType.getLength()" because "componentDt" is null
java.lang.NullPointerException: Cannot invoke "ghidra.program.model.data.DataType.getLength()" because "componentDt" is null
	at ghidra.program.model.data.AlignedComponentPacker.alignAndPackNonBitfieldComponent(AlignedComponentPacker.java:310)
	at ghidra.program.model.data.AlignedComponentPacker.packComponent(AlignedComponentPacker.java:302)
	at ghidra.program.model.data.AlignedComponentPacker.addComponent(AlignedComponentPacker.java:65)
	at ghidra.program.model.data.AlignedStructurePacker.pack(AlignedStructurePacker.java:95)
	at ghidra.program.model.data.AlignedStructureInspector.packComponents(AlignedStructureInspector.java:173)
	at ghidra.program.database.data.StructureDB.getAlignment(StructureDB.java:734)
	at ghidra.app.util.html.CompositeDataTypeHTMLRepresentation.buildAlignmentValueText(CompositeDataTypeHTMLRepresentation.java:130)
	at ghidra.app.util.html.CompositeDataTypeHTMLRepresentation.<init>(CompositeDataTypeHTMLRepresentation.java:73)
	at ghidra.app.util.ToolTipUtils.getHTMLRepresentation(ToolTipUtils.java:78)
	at ghidra.app.util.ToolTipUtils.getToolTipText(ToolTipUtils.java:64)
	at ghidra.app.plugin.core.datamgr.tree.DataTypeNode.getToolTip(DataTypeNode.java:109)
	at docking.widgets.tree.support.GTreeRenderer.getTreeCellRendererComponent(GTreeRenderer.java:66)
	at ghidra.app.plugin.core.datamgr.tree.DataTypeArchiveGTree$DataTypeTreeRenderer.getTreeCellRendererComponent(DataTypeArchiveGTree.java:324)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:3183)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:493)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1465)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1272)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.ensurePathIsExpanded(VariableHeightLayoutCache.java:967)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.setExpandedState(VariableHeightLayoutCache.java:181)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.updateExpandedDescendants(BasicTreeUI.java:2003)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.treeExpanded(BasicTreeUI.java:4240)
	at java.desktop/javax.swing.JTree.fireTreeExpanded(JTree.java:2801)
	at java.desktop/javax.swing.JTree.setExpandedState(JTree.java:3702)
	at java.desktop/javax.swing.JTree.expandPath(JTree.java:2244)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.toggleExpandState(BasicTreeUI.java:2644)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.handleExpandControlClick(BasicTreeUI.java:2629)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.checkForClickInExpandControl(BasicTreeUI.java:2577)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:4035)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:3983)
	at docking.widgets.JTreeMouseListenerDelegate.fireMousePressed(JTreeMouseListenerDelegate.java:125)
	at docking.widgets.JTreeMouseListenerDelegate.mousePressed(JTreeMouseListenerDelegate.java:97)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6611)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6379)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4545)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2021-Jan-23 2158 UTC
Ghidra Version: 9.2.2
Java Home: /usr/lib/jvm/java-15-openjdk
JVM Version: N/A 15.0.2
OS: Linux 5.4.94-1-lts amd64
Workstation: lopmon
```

**Attachments**
Project file: http://segment6.net/b/SFA.rep.7z (83 MB)

**Environment (please complete the following information):**
 - OS: Artix x64
 - Java Version: openjdk version "15.0.2" 2021-01-19
 - Ghidra Version: 9.2.2

**Comment by ghidra1** [comment]
Not sure why the datatype is null.  This condition is not expected or permitted.

**Comment by RenaKunisaki** [comment]
Somehow this has completely broken Ghidra. Even after restoring the project files from a backup from last month, I'm getting the same error.

**Comment by RenaKunisaki** [comment]
Okay, now I'm getting an error every time I try to access parts of the SFA archive:
```
Input/output error
java.io.IOException: Input/output error
	at java.base/java.io.RandomAccessFile.read0(Native Method)
	at java.base/java.io.RandomAccessFile.read(RandomAccessFile.java:368)
	at java.base/java.io.RandomAccessFile.readByte(RandomAccessFile.java:710)
	at db.buffers.LocalBufferFile.get(LocalBufferFile.java:663)
	at db.buffers.LocalManagedBufferFile.get(LocalManagedBufferFile.java:311)
	at db.buffers.BufferMgr.getBufferNode(BufferMgr.java:803)
	at db.buffers.BufferMgr.getBuffer(BufferMgr.java:957)
	at db.NodeMgr.getVarKeyNode(NodeMgr.java:218)
	at db.VarKeyInteriorNode.getLeafNode(VarKeyInteriorNode.java:610)
	at db.Table$VarKeyIterator2.initialize(Table.java:3820)
	at db.Table$VarKeyIterator2.<init>(Table.java:3779)
	at db.Table$VarKeyIterator.<init>(Table.java:3331)
	at db.Table.fieldKeyIterator(Table.java:1912)
	at db.FieldIndexTable.findPrimaryKeys(FieldIndexTable.java:68)
	at db.Table.findRecords(Table.java:1373)
	at ghidra.program.database.data.FunctionDefinitionDBAdapterV1.getRecordWithIDs(FunctionDefinitionDBAdapterV1.java:165)
	at ghidra.program.database.data.DataTypeManagerDB.findDataTypeForIDs(DataTypeManagerDB.java:3717)
	at ghidra.program.database.data.DataTypeManagerDB$IdsToDataTypeMap.lambda$getDataType$1(DataTypeManagerDB.java:4155)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at ghidra.program.database.data.DataTypeManagerDB$IdsToDataTypeMap.getDataType(DataTypeManagerDB.java:4154)
	at ghidra.program.database.data.DataTypeManagerDB.getDataType(DataTypeManagerDB.java:3687)
	at ghidra.program.database.data.DataTypeManagerDB.findDataTypeForID(DataTypeManagerDB.java:3693)
	at ghidra.app.util.datatype.DataTypeUrl.getDataType(DataTypeUrl.java:115)
	at ghidra.app.plugin.core.datamgr.NextPreviousDataTypeAction.createNavigationActions(NextPreviousDataTypeAction.java:96)
	at ghidra.app.plugin.core.datamgr.NextPreviousDataTypeAction.getActionList(NextPreviousDataTypeAction.java:84)
	at ghidra.app.plugin.core.datamgr.NextPreviousDataTypeAction.isEnabledForContext(NextPreviousDataTypeAction.java:79)
	at docking.ComponentPlaceholder.contextChanged(ComponentPlaceholder.java:501)
	at docking.DockingWindowManager.contextChanged(DockingWindowManager.java:2118)
	at docking.AbstractDockingTool.contextChanged(AbstractDockingTool.java:208)
	at ghidra.framework.plugintool.PluginTool.contextChanged(PluginTool.java:1486)
	at docking.ComponentProvider.contextChanged(ComponentProvider.java:445)
	at ghidra.app.plugin.core.datamgr.DataTypesProvider.dataTypeSelected(DataTypesProvider.java:899)
	at ghidra.app.plugin.core.datamgr.DataTypesProvider.lambda$buildComponent$3(DataTypesProvider.java:416)
	at docking.widgets.tree.internal.GTreeSelectionModel.fireValueChanged(GTreeSelectionModel.java:118)
	at docking.widgets.tree.internal.GTreeSelectionModel.fireValueChanged(GTreeSelectionModel.java:75)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1111)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:297)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:191)
	at java.desktop/javax.swing.JTree.setSelectionPath(JTree.java:1656)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(BasicTreeUI.java:2764)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:4044)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:3983)
	at docking.widgets.JTreeMouseListenerDelegate.fireMousePressed(JTreeMouseListenerDelegate.java:125)
	at docking.widgets.JTreeMouseListenerDelegate.mousePressed(JTreeMouseListenerDelegate.java:97)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6611)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6379)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4545)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2021-Jan-23 2158 UTC
Ghidra Version: 9.2.2
Java Home: /usr/lib/jvm/java-15-openjdk
JVM Version: N/A 15.0.2
OS: Linux 5.10.16-1-lts amd64
Workstation: lopmon
```

Typing `objseqfn` into the filter field of the Data Type Manager, or trying to change a struct field's type to `ObjSeqFn*` in any program with this archive open, causes this error. Even just scrolling the DTM after having typed that. It's making progress on this project nearly impossible. Many functions such as `init` now fail to decompile, only saying "Low-level Error: Bad structure definition".

**Comment by dragonmacher** [comment]
The stack trace implies that you are having trouble reading the database from the filesystem.    It is not clear if it is related to the previous exceptions you were getting.    Based upon what you have shown in this ticket, I am assuming you have some sort of database corruption.

**Comment by ghidra1** [comment]
Assuming you are not low on disk space (tmp and project storage), the database may be corrupt somehow and has bad buffer IDs which compute to file offsets.

**Comment by ghidra1** [comment]
Have you see this with more than one project file?  If isolated to this one file have you tried re-importing and starting from scratch to see if it reoccurs?

**Comment by RenaKunisaki** [comment]
I've checked disk space, all seems fine there (1.6GB in /tmp, 815GB in /home). Since I tend to access the project file over a network mount, there probably was some kind of corruption. How do I re-import and/or view the logs?

**Comment by ghidra1** [comment]
I assume you imported the first time from the binary file.  Just a matter of repeating your steps and see if all goes well.  Hopefully the problem will not repeat itself.

There is a log viewer which can be displayed via the main project windows (small terminal icon button, lower-right corner).  However, it may be easier to view and search logs by opening the log files in an editor of your choosing.  The log files are store in a Ghidra version-specific `.ghidra` directory within your home directory (e.g., ~/.ghidra/.ghidra_9.2_PUBLIC/application.log).

**Comment by RenaKunisaki** [comment]
Won't that wipe out all my work? Labels and functions and such?

I've really only been working on one project file, so I haven't seen it on any others.

I'm not sure what to look for in the logs, but here's everything from the date the corruption happened (and a bit before):

```2021-02-17 17:45:10 INFO  (GhidraRun) User rena started Ghidra.  
2021-02-17 17:45:11 DEBUG (RecoverySnapshotMgrPlugin) Recovery snapshot timer set to 5 minute(s)  
2021-02-17 17:45:12 INFO  (DefaultProject) Opening project: /mnt/guilmon/home/rena/projects/games/hax/sfa/SFA  
2021-02-17 17:45:15 INFO  (PackedDatabaseCache) Packed database cache: /tmp/rena-Ghidra/packed-db-cache  
2021-02-17 17:45:15 DEBUG (PackedDatabaseCache) Using cached packed database: /opt/ghidra/Ghidra/Features/Base/data/typeinfo/generic/generic_clib.gdt  
2021-02-18 17:25:15 ERROR (SyncTask) Task Error: Data Type Sync - Commit - Uncaught Exception: ghidra.framework.model.DomainObjectException caused by: java.io.IOException: Input/output error java.io.IOException: Input/output error
	at java.base/java.io.RandomAccessFile.read0(Native Method)
	at java.base/java.io.RandomAccessFile.read(RandomAccessFile.java:368)
	at java.base/java.io.RandomAccessFile.readByte(RandomAccessFile.java:710)
	at db.buffers.LocalBufferFile.get(LocalBufferFile.java:663)
	at db.buffers.LocalManagedBufferFile.get(LocalManagedBufferFile.java:311)
	at db.buffers.BufferMgr.getBufferNode(BufferMgr.java:803)
	at db.buffers.BufferMgr.getBuffer(BufferMgr.java:957)
	at db.NodeMgr.getVarKeyNode(NodeMgr.java:218)
	at db.VarKeyInteriorNode.getLeafNode(VarKeyInteriorNode.java:610)
	at db.Table$VarKeyIterator2.initialize(Table.java:3820)
	at db.Table$VarKeyIterator2.<init>(Table.java:3779)
	at db.Table$VarKeyIterator.<init>(Table.java:3331)
	at db.Table.fieldKeyIterator(Table.java:1912)
	at db.FieldIndexTable.findPrimaryKeys(FieldIndexTable.java:68)
	at db.Table.findRecords(Table.java:1373)
	at ghidra.program.database.data.FunctionDefinitionDBAdapterV1.getRecordWithIDs(FunctionDefinitionDBAdapterV1.java:165)
	at ghidra.program.database.data.DataTypeManagerDB.findDataTypeForIDs(DataTypeManagerDB.java:3717)
	at ghidra.program.database.data.DataTypeManagerDB$IdsToDataTypeMap.lambda$getDataType$1(DataTypeManagerDB.java:4155)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at ghidra.program.database.data.DataTypeManagerDB$IdsToDataTypeMap.getDataType(DataTypeManagerDB.java:4154)
	at ghidra.program.database.data.DataTypeManagerDB.getDataType(DataTypeManagerDB.java:3687)
	at ghidra.app.plugin.core.datamgr.DataTypeSyncInfo.<init>(DataTypeSyncInfo.java:39)
	at ghidra.app.plugin.core.datamgr.DataTypeSynchronizer.findOutOfSynchDataTypes(DataTypeSynchronizer.java:77)
	at ghidra.app.plugin.core.datamgr.actions.SyncAction.doSync(SyncAction.java:132)
	at ghidra.app.plugin.core.datamgr.actions.SyncAction$SyncTask.run(SyncAction.java:382)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:303)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
 
2021-02-18 17:25:20 ERROR (SyncTask) Task Error: Data Type Sync - Commit - Uncaught Exception: ghidra.framework.model.DomainObjectException caused by: java.io.IOException: Input/output error java.io.IOException: Input/output error
	at java.base/java.io.RandomAccessFile.read0(Native Method)
	at java.base/java.io.RandomAccessFile.read(RandomAccessFile.java:368)
	at java.base/java.io.RandomAccessFile.readByte(RandomAccessFile.java:710)
	at db.buffers.LocalBufferFile.get(LocalBufferFile.java:663)
	at db.buffers.LocalManagedBufferFile.get(LocalManagedBufferFile.java:311)
	at db.buffers.BufferMgr.getBufferNode(BufferMgr.java:803)
	at db.buffers.BufferMgr.getBuffer(BufferMgr.java:957)
	at db.NodeMgr.getVarKeyNode(NodeMgr.java:218)
	at db.VarKeyInteriorNode.getLeafNode(VarKeyInteriorNode.java:610)
	at db.Table$VarKeyIterator2.initialize(Table.java:3820)
	at db.Table$VarKeyIterator2.<init>(Table.java:3779)
	at db.Table$VarKeyIterator.<init>(Table.java:3331)
	at db.Table.fieldKeyIterator(Table.java:1912)
	at db.FieldIndexTable.findPrimaryKeys(FieldIndexTable.java:68)
	at db.Table.findRecords(Table.java:1373)
	at ghidra.program.database.data.FunctionDefinitionDBAdapterV1.getRecordWithIDs(FunctionDefinitionDBAdapterV1.java:165)
	at ghidra.program.database.data.DataTypeManagerDB.findDataTypeForIDs(DataTypeManagerDB.java:3717)
	at ghidra.program.database.data.DataTypeManagerDB$IdsToDataTypeMap.lambda$getDataType$1(DataTypeManagerDB.java:4155)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at ghidra.program.database.data.DataTypeManagerDB$IdsToDataTypeMap.getDataType(DataTypeManagerDB.java:4154)
	at ghidra.program.database.data.DataTypeManagerDB.getDataType(DataTypeManagerDB.java:3687)
	at ghidra.app.plugin.core.datamgr.DataTypeSyncInfo.<init>(DataTypeSyncInfo.java:39)
	at ghidra.app.plugin.core.datamgr.DataTypeSynchronizer.findOutOfSynchDataTypes(DataTypeSynchronizer.java:77)
	at ghidra.app.plugin.core.datamgr.actions.SyncAction.doSync(SyncAction.java:132)
	at ghidra.app.plugin.core.datamgr.actions.SyncAction$SyncTask.run(SyncAction.java:382)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:303)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
 
2021-02-18 17:25:33 ERROR (LocalManagedBufferFile) java.io.IOException: Input/output error  
2021-02-18 17:25:33 ERROR (LocalManagedBufferFile) java.io.IOException: Input/output error  
2021-02-18 17:25:33 ERROR (LocalManagedBufferFile) java.io.IOException: Input/output error  
2021-02-18 17:25:40 INFO  (LoggingInitialization) Using log config file: jar:file:/opt/ghidra/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml  
2021-02-18 17:25:40 INFO  (LoggingInitialization) Using log file: /home/rena/.ghidra/.ghidra_9.2.2_DEV/application.log  
2021-02-18 17:25:40 INFO  (Preferences) Loading user preferences: /home/rena/.ghidra/.ghidra_9.2.2_DEV/preferences  
2021-02-18 17:25:40 INFO  (Preferences) Loading previous preferences: /home/rena/.ghidra/.ghidra_9.2_DEV/preferences  
2021-02-18 17:25:42 INFO  (ClassSearcher) Class search complete (1153 ms)  
2021-02-18 17:25:42 INFO  (SSLContextInitializer) Initializing SSL Context  
2021-02-18 17:25:42 INFO  (SecureRandomFactory) Initializing Random Number Generator...  
2021-02-18 17:25:42 INFO  (SecureRandomFactory) Random Number Generator initialization complete: NativePRNGNonBlocking  
2021-02-18 17:25:42 INFO  (ApplicationTrustManagerFactory) Trust manager disabled, cacerts have not been set  
2021-02-18 17:25:42 INFO  (GhidraRun) User rena started Ghidra.  ```

**Comment by dragonmacher** [comment]
You can fully re-import and auto-analyze the binary while keeping the original around.   Assuming this works, then you should be able to copy your markup from the original to the new program by using Version Tracking.   Version Tracking allows you to point to both programs in your Ghidra project and then shows the similar data and functions.   The VT interface is a bit clunky, but you can do all of this work without losing your original work, as long as you do not delete the original program from your project.

**Comment by RenaKunisaki** [comment]
I can still open the existing program, and was able to re-import, but version tracking doesn't show any matches.

**Comment by ghidra1** [comment]
With a corrupt database you may be in bad shape to recover.  You can attempt a Ghidra Diff with ability to apply differences, but I suspect you will encounter your database error preventing this from working.  When I have time will look more closely at your attached project file to see what hope it holds.

**Comment by RenaKunisaki** [comment]
I have incremental backups, so I could try to restore a non-corrupted version. But I'm not sure how to tell where the corruption starts. Restoring to before the problem appeared didn't fix it, so I suspect the corruption has been there for a while and only now caused a problem.

**Comment by pj1234678** [comment]
I was able to reproduce this on the latest edition 11.2.1




using this script -  https://github.com/toor-de-force/Ghidra-to-LLVM/blob/master/src/GhidraToXML.java


produces the following.
java.lang.NullPointerException: Cannot invoke "ghidra.program.model.pcode.PcodeDataTypeManager.clearTemporaryIds()" because "this.dtmanage" is null
	at ghidra.app.decompiler.DecompInterface.decompileFunction(DecompInterface.java:779)
	at GhidraToXML.run(GhidraToXML.java:80)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:405)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:260)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:238)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:47)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)

**Comment by ghidra1** [comment]
This is unrelated to the original issue which has been closed.

In your script you must invoke `DecompilerInterface.openProgram` before you attempt to decompile a function.  The program supplied must correspond to the function being decompiled.  Be sure to dispose the decompiler interface when done using the instance to ensure that related processes are properly terminated.

**Comment by pj1234678** [comment]
Firstly ghidra1, I would like to thank you for your prompt response.

My goal is to lift a C++ executable to LLVM IR then compile back. (hello world example)

This is more of a learning exercise for me.

The script states that it just requires calling the script with the exe and using headless mode it activate ghidra and imports the exe. Then it runs this script to translate the Higher Level representation to XML. 
Then after it should lift it to llvm IR.

Maybe you have a better method I can be taking a look at?

**Comment by ghidra1** [comment]
Conceptually you could still leverage the decompiler, you just have to initialize and launch properly.  Given the result objects (e.g., HighFunction) you could roll your own XML schema, as it appears you have, or try to leverage the `encode` methods(s) on the results using the `XmlEncode` implementation.  Much of this depends on what data you need and what will be consuming the XML.  If consuming outside of Ghidra it may make sense to use your own schema.  Either way you will likely have to cope with API changes over time.
