### ISSUE TITLE
Performance issues with batch decompilation

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#2791]
**Is your feature request related to a problem? Please describe.**
Some of my scripts and plugins rely on decompiling large numbers of functions. I noticed that in particular, decompiling multiple functions at once does not scale past roughly 12 concurrent threads, even when not limited by the processor/memory. To test this, I repurposed the FindPotentialDecompilerProblems.java script to just decompile all functions in a medium sized binary (25k functions), and adjusted the core.override.

My best guess is that the decompiler I/O is being the bottleneck here, but any help diagnosing/increasing performance would be most welcome

**Additional context**
Ghidra 9.2.2

**Comment by dragonmacher** [comment]
Assuming you are using the decompilation to markup a program, then the program database lock will become the bottleneck.  If you are using the decompilation without reading/writing the program, then you are likely bumping into the natural limitations of the JVM running on your particular machine.   If you have access, you could try running your scripts on a server-grade machine to separate hardware from Ghidra software limitations.

**Comment by sad-dev** [comment]
My machine isn't quite server grade, but it is close. 

My scripts do not write to the program while analysis is ongoing (decompiling all functions accounts for > 95% of runtime), so this script has very similar performance. Do you think the program database lock is the bottleneck here, or simply the JVM?

```
import java.util.*;

import ghidra.app.decompiler.*;
import ghidra.app.decompiler.parallel.*;
import ghidra.app.script.GhidraScript;
import ghidra.app.tablechooser.*;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.*;
import ghidra.program.model.pcode.*;
import ghidra.program.model.symbol.Reference;
import ghidra.program.model.symbol.ReferenceIterator;
import ghidra.util.task.TaskMonitor;
import util.CollectionUtils;

public class ModifiedFindPotentialDecompilerProblems extends GhidraScript {

	@Override
	public void run() throws Exception {

		if (isRunningHeadless()) {
			printf("This script cannot be run in headless mode.\n");
			return;
		}

		DecompilerCallback<Void> callback =
			new DecompilerCallback<Void>(currentProgram, new BasicConfigurer(currentProgram)) {
				@Override
				public Void process(DecompileResults results, TaskMonitor tMonitor)
						throws Exception {
					return null;
				}
			};

		Set<Function> funcsToDecompile = new HashSet<>();
		FunctionIterator fIter = currentProgram.getFunctionManager().getFunctionsNoStubs(true);
		fIter.forEach(e -> funcsToDecompile.add(e));

		ParallelDecompiler.decompileFunctions(callback, funcsToDecompile, monitor);
		monitor.checkCanceled();
	}

	static class BasicConfigurer implements DecompileConfigurer {
		private Program p;

		public BasicConfigurer(Program prog) {
			p = prog;
		}

		@Override
		public void configure(DecompInterface decompiler) {
			decompiler.toggleCCode(true);
			decompiler.toggleSyntaxTree(true);
			decompiler.setSimplificationStyle("decompile");
			DecompileOptions opts = new DecompileOptions();
			opts.grabFromProgram(p);
			decompiler.setOptions(opts);
		}
	}
}
```

**Comment by dragonmacher** [comment]
Based on this code, I'd say you are not running into program lock limitations.    You would have to profile the app to find the bottleneck, as it could be any part of your machine.

**Comment by sad-dev** [comment]
I have barely touched the decompiler internals, but my first guess would be ``ArchitectureGhidra``, where the Ghidra client gets overloaded. Looks like I'll have to compile it after all ...

**Comment by dragonmacher** [comment]
(See my updated comment above.)


We have a hard-coded limit of 10 for the option you are using).   There is no way to override this without changing the source code, whether the `SystemUtilities` class that parses the property you are updating or the `ParallelDecopmiler`, which is what your script ends up calling into.

**Comment by sad-dev** [comment]
The simple 

```
println("CpuCoreOverride + "System.getProperty("cpu.core.override"));
```

returns whatever I set ``VMARGS=-Dcpu.core.override=`` to.

https://github.com/NationalSecurityAgency/ghidra/blob/45927bb9c33330d8dad3597eb459e2e9a35c3323/Ghidra/Framework/Utility/src/main/java/ghidra/util/SystemUtilities.java#L433

and 

https://github.com/NationalSecurityAgency/ghidra/blob/45927bb9c33330d8dad3597eb459e2e9a35c3323/Ghidra/Framework/Utility/src/main/java/ghidra/util/SystemUtilities.java#L470

seem to imply my option will be respected

**Comment by dragonmacher** [comment]
Ghidra does not change the value of the system property.   Rather, it calls the method `getCPUOverride()` and then will cap the value returned to a limit of 10.   This is the code that I liked above.

**Comment by sad-dev** [comment]
https://github.com/NationalSecurityAgency/ghidra/blob/45927bb9c33330d8dad3597eb459e2e9a35c3323/Ghidra/Framework/Utility/src/main/java/ghidra/util/SystemUtilities.java#L433-L436

Doesn't it get returned right away without being capped here?

**Comment by dragonmacher** [comment]
Haha.   I knew one of us was mistaken.   Clearly I am still suffering from brain fog today.    

Yes, you are correct.

**Comment by sad-dev** [comment]
Yeah, that's what I was dreading - hopefully my solution won't involve some nonsense involving multiple clients/programs

**Comment by dragonmacher** [comment]
Please keep us updated with what you find.  We would like to fix any clear algorithmic mistakes.  It will obviously be more difficult to make architecture-level changes.

**Comment by sad-dev** [comment]
I replaced the decompilation with an expensive math calculation with a roughly similar distribution of time per task. The resulting runtime scales almost linearly with number of threads in the pool up to 64.

My suspicion is that some (instance?) component of the Ghidra (Java) client is getting bottlenecked, either:

1.) Reading the database
2.) Sending data to the decompilers
3.) Receiving and parsing data from the decompilers

**Comment by sad-dev** [comment]
Based on a dump when running 64 parallel decompilers, I am pretty sure the bottlenecks are in program.database; a snapshot shows 35 of them waiting at various locks on the database records @dragonmacher 

```
      2 	at ghidra.program.database.code.CodeManager.getDefinedDataAt(CodeManager.java:1319)
      4 	at ghidra.program.database.code.CodeManager.getInstructionAt(CodeManager.java:1283)
      9 	at ghidra.program.database.code.CodeUnitDB.getBytes(CodeUnitDB.java:648)
      5 	at ghidra.program.database.code.InstructionDB.getDefaultFallThrough(InstructionDB.java:718)
     10 	at ghidra.program.database.function.FunctionDB.getEntryPoint(FunctionDB.java:314)
      2 	at ghidra.program.database.function.FunctionDB.isFunctionFlagSet(FunctionDB.java:2396)
      1 	at ghidra.program.database.references.ReferenceDBManager.getReferencesFrom(ReferenceDBManager.java:796)
      1 	at ghidra.program.database.symbol.NamespaceManager.getAddressSet(NamespaceManager.java:265)
      1 	at ghidra.program.database.symbol.SymbolDB.getSymbolData1(SymbolDB.java:804)
```

**Comment by sad-dev** [comment]
A list of locks that I observed:

```
      8 	at ghidra.program.database.code.CodeManager.getCodeUnitContaining(CodeManager.java:1006)
     23 	at ghidra.program.database.code.CodeManager.getDefinedDataAt(CodeManager.java:1319)
     74 	at ghidra.program.database.code.CodeManager.getInstructionAt(CodeManager.java:1283)
     82 	at ghidra.program.database.code.CodeUnitDB.getBytes(CodeUnitDB.java:648)
      1 	at ghidra.program.database.code.DataDB.getNumComponents(DataDB.java:740)
      5 	at ghidra.program.database.code.DataDB.hasMutability(DataDB.java:359)
     52 	at ghidra.program.database.code.InstructionDB.getDefaultFallThrough(InstructionDB.java:718)
      9 	at ghidra.program.database.code.InstructionDB.getFallThrough(InstructionDB.java:193)
      7 	at ghidra.program.database.data.ArrayDB.getDataType(ArrayDB.java:124)
      1 	at ghidra.program.database.data.DataTypeManagerDB.getArrayDataType(DataTypeManagerDB.java:2194)
      1 	at ghidra.program.database.data.DataTypeManagerDB.getBuiltInDataType(DataTypeManagerDB.java:2053)
      2 	at ghidra.program.database.data.DataTypeManagerDB.getCompositeDataType(DataTypeManagerDB.java:2141)
      1 	at ghidra.program.database.data.DataTypeManagerDB.getTypedefDataType(DataTypeManagerDB.java:2171)
      1 	at ghidra.program.database.data.FunctionDefinitionDB.getGenericCallingConvention(FunctionDefinitionDB.java:567)
      6 	at ghidra.program.database.data.PointerDB.getLength(PointerDB.java:188)
      5 	at ghidra.program.database.data.StructureDB.getLength(StructureDB.java:742)
      8 	at ghidra.program.database.function.FunctionDB.getCallFixup(FunctionDB.java:2668)
     12 	at ghidra.program.database.function.FunctionDB.getCallingConventionName(FunctionDB.java:2528)
     86 	at ghidra.program.database.function.FunctionDB.getEntryPoint(FunctionDB.java:314)
      1 	at ghidra.program.database.function.FunctionDB.getLocalVariables(FunctionDB.java:1168)
     11 	at ghidra.program.database.function.FunctionDB.getName(FunctionDB.java:220)
      2 	at ghidra.program.database.function.FunctionDB.getParameters(FunctionDB.java:1130)
      1 	at ghidra.program.database.function.FunctionDB.getReturn(FunctionDB.java:350)
      3 	at ghidra.program.database.function.FunctionDB.getSignatureSource(FunctionDB.java:2442)
     19 	at ghidra.program.database.function.FunctionDB.isFunctionFlagSet(FunctionDB.java:2396)
      2 	at ghidra.program.database.function.FunctionDB.isThunk(FunctionDB.java:110)
      6 	at ghidra.program.database.function.FunctionManagerDB.getFunctionAt(FunctionManagerDB.java:621)
      1 	at ghidra.program.database.function.FunctionManagerDB.getFunctionContaining(FunctionManagerDB.java:647)
     22 	at ghidra.program.database.references.ReferenceDBManager.getReferencesFrom(ReferenceDBManager.java:796)
      2 	at ghidra.program.database.symbol.NamespaceManager.getAddressSet(NamespaceManager.java:265)
      1 	at ghidra.program.database.symbol.SymbolDB.getAddress(SymbolDB.java:116)
      1 	at ghidra.program.database.symbol.SymbolDB.getName(SymbolDB.java:169)
      9 	at ghidra.program.database.symbol.SymbolDB.getParentSymbol(SymbolDB.java:716)
     18 	at ghidra.program.database.symbol.SymbolDB.getSymbolData1(SymbolDB.java:804)
      2 	at ghidra.program.database.symbol.SymbolManager.getPrimarySymbol(SymbolManager.java:1103)
      2 	at ghidra.program.database.symbol.SymbolManager.getSymbols(SymbolManager.java:987)
      2 	at ghidra.program.database.symbol.SymbolManager.getSymbol(SymbolManager.java:752)
     44 	at ghidra.program.database.util.AddressRangeMapDB.getValue(AddressRangeMapDB.java:167)

```

**Comment by dragonmacher** [comment]
This makes sense.    We have discussed the idea of moving away from using a single db locking mechanism to use  a read/write locking scheme that allows the reads to be non-blocking.   It is hard to say without testing, but that should be quite beneficial as the number of threads on the system grows.

**Comment by sad-dev** [comment]
As an experiment, I refactored ghidra.util.Lock to java.util.concurrent.locks.ReentrantReadWriteLock; for now, all ``lock.acquire()`` calls have been refactored to ``lock.writeLock().lock()``

Interestingly, this leads to a roughly 30% speedup when performing batch decompilation. I will slowly change some uses of the ``writeLock`` to reads and see how much speed I get from it.

**Comment by ghidra1** [comment]
Introducing read locks can get complicated due to the need to synchronize the cache and lazy initialization.  This will force additional `synchronized` protections.  It is not as simple as just using a different lock on the read methods if they can change internal state (e.g., DB objects).

**Comment by dragonmacher** [comment]
> Interestingly, this leads to a roughly 30% speedup when performing batch decompilation (150s -> 115s on a 25k function binary) with just the refactor. I will slowly change some uses of the writeLock to reads and see how much speed I get from it.

I am interested in seeing what you find.

**Comment by sad-dev** [comment]
> Introducing read locks can get complicated due to the need to synchronize the cache and lazy initialization. This will force additional `synchronized` protections. It is not as simple as just using a different lock on the read methods if they can change internal state (e.g., DB objects).

That's definitely true, I quickly found that naively replacing writelock with readlock on 'getters' led to deadlocks of all sorts. Not being able to upgrade the lock makes it pretty tough; I might have to consider ``ReentrantReadWriteUpdateLock`` or ``StampedLock``.

**Comment by ghidra1** [comment]
I had a few years back had a failed attempt to implement a concurrent read/write lock scheme and had refactored all of the the internal synchronization which was quite extensive and invasive.  At the time I was unable to get a read lock in the same thread that held a write lock (deadlock).  This seemed to contradict the documentation.  This is a necessary capability of the read/write locking since write-lock methods need to invoke public read-lock methods.

**Comment by sad-dev** [comment]
It has been slow going. I tried refactoring `` ghidra.program.database.code.CodeUnitDB.getBytes(CodeUnitDB.java:648)`` to use a ReadLock, but quickly found out that ``CodeManager`` uses a ``DbObjectCache`` which is lazily created, meaning even innocuous sounding functions in it like ``getCodeUnitAt`` must be treated carefully. 

I'm pretty much compiling, running, and fixing deadlocks as I go. Is there a way to rebuild ghidra without having to recompile the slaspec and javadocs? A typical ``gradle buildGhidra`` takes 3 minutes or so, mostly spent on these two tasks.

**Comment by ryanmkurtz** [comment]
> Is there a way to rebuild ghidra without having to recompile the slaspec and javadocs?

`gradle buildGhidra -x zipJavadocs -x sleighCompile`

**Comment by ghidra1** [comment]
As I indicated above, I have been through this exercise once before and a significant amount of refactoring with synchronization was required.

You should not need to build Ghidra in order to test and you should be fine testing from Eclipse.

**Comment by sad-dev** [comment]
The refactors needed to make ReadWrite locks work go all the way down and I've basically given up, sadly.

**Comment by dragonmacher** [comment]
This is certainly one of the most difficult areas to navigate and change.  Thanks for the effort and the info you have provided.

**Comment by sad-dev** [comment]
I couldn't quite leave this alone and made one last moonshot:

1.) Replace ``ghidra.util.Lock`` to use a ``ReentrantReadWriteLock``, with ``acquire`` and ``release``
2.) Add static boolean  ``noLock`` to the ``Lock``. When ``noLock`` is true, calls to acquire will just pass through. From the GhidraScript, set noLock while batch decompiling and unset after.
3.) Disable writes to DBObjectCache when ``noLock`` is active
As a side note, ``LinkedList<T> hardCache`` looks weird here - there is an explicit constructor call which sets this size to 1000, which sounds extremely non-performant.

I then noticed I was deadlocked on ``DBHandle`` in ``Table.java``, usually calling ``getRecord*`` functions

4.) Added a ``ReentrantReadWriteLock`` to ``DBHandle`` and replaced all synchronized blocks with read or write locks, appropriately
5.) ``NodeMgr and BufferMgr`` throw up frequent exceptions,  due to concurrently calling ``NodeMgr.releaseNodes``.

**Comment by tavianator** [comment]
In case it's helpful to anyone, I worked around this issue by caching the decompiler output on disk: https://github.com/rcslab/AutoCPA/blob/master/scripts/bcpi/BcpiDecompiler.java

It works for me because I frequently re-run my analysis.  Doesn't help on the first run when it has to decompile everything, of course.
