### ISSUE TITLE
Add category in DTM with text in filter

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#2799]
9.2.2 / windows 10 / 11.0.2
master / ubuntu 18.04 / 11.0.10

Was adding a new struct and wanted to categorize it.

I typed in a filter to see if i had already made the category, which I hadn't.
I left my filter string there.
Right clicked my program's archive and did new->category

I'm not sure on the timing, maybe its when I went to go delete the filter, but this raises an exception

```
java.lang.NullPointerException
	at docking.widgets.tree.internal.GTreeModel.valueForPathChanged(GTreeModel.java:115)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.completeEditing(BasicTreeUI.java:2408)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.editingStopped(BasicTreeUI.java:4117)
	at java.desktop/javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:147)
	at java.desktop/javax.swing.DefaultCellEditor$EditorDelegate.stopCellEditing(DefaultCellEditor.java:370)
	at java.desktop/javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:234)
	at java.desktop/javax.swing.tree.DefaultTreeCellEditor.stopCellEditing(DefaultTreeCellEditor.java:302)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.completeEditing(BasicTreeUI.java:2356)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.valueChanged(BasicTreeUI.java:4133)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:641)
	at docking.widgets.tree.internal.GTreeSelectionModel.fireValueChanged(GTreeSelectionModel.java:74)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1111)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.removeSelectionPaths(DefaultTreeSelectionModel.java:505)
	at docking.widgets.tree.internal.GTreeSelectionModel.removeSelectionPaths(GTreeSelectionModel.java:90)
	at java.desktop/javax.swing.JTree.removeDescendantSelectedPaths(JTree.java:3804)
	at java.desktop/javax.swing.JTree$TreeModelHandler.treeStructureChanged(JTree.java:3911)
	at docking.widgets.tree.internal.GTreeModel.swingFireRootChanged(GTreeModel.java:150)
	at docking.widgets.tree.internal.GTreeModel.privateSwingSetRootNode(GTreeModel.java:54)
	at docking.widgets.tree.GTree.swingSetModelRootNode(GTree.java:765)
	at docking.widgets.tree.GTree.swingSetFilteredRootNode(GTree.java:749)
	at docking.widgets.tree.GTreeFilterTask.lambda$1(GTreeFilterTask.java:57)
	at docking.widgets.tree.GTreeTask$CheckCancelledRunnable.run(GTreeTask.java:85)
	at ghidra.util.Swing.lambda$2(Swing.java:227)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by dragonmacher** [comment]
There has been work in the tree node area fairly recently.   This sounds like an edge case that was not tested or  worse, it may be timing related.

**Comment by mumbel** [comment]
Followup issue, I can open a new ticket if that's easier to track or if seemed separate enough.

In the failure case it looks like a new category `New Category` is created.  I guess you could go either way with that, but I'd lean towards no side effect artifacts

**Comment by dragonmacher** [comment]
I think this has been fixed in master.  Is it possible for you to test?

**Comment by mumbel** [comment]
Sweet, I can test tonight, and I'll follow up if it's still happening

**Comment by ghidra1** [comment]
FYI - there is another pending fix which has not yet been pushed-out.
