### ISSUE TITLE
GhidraDev Eclipse sources export

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#283]
For now GhidraDev allows to export only compiled module, which is not possible to import then to Eclipse workspace etc.
It would be great to add such functionality.

**Comment by lab313ru** [comment]
It is also related to this:
I tried to export some minimal required files (without local `.gradle` directory) and after importing to workspace and trying to build it, GhidraDev tells me NullPointerException at the Gradle selection step.

**Comment by ryanmkurtz** [comment]
Can you post that stack trace please?

**Comment by lab313ru** [comment]
Where is it located? Pressing Finish just shows me Exception windows and there is no any stacktrace log.

**Comment by ryanmkurtz** [comment]
In Eclipse, if you go up to Window -> Show View -> Error Log, you should be able to get to the stack trace from there.  If the error happened internal to the Eclipse Gradle/Buildship task we might not be able to get it.

**Comment by lab313ru** [comment]
> java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:401)
	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:977)
	at ghidradev.ghidraprojectcreator.wizards.ExportGhidraModuleWizard.performFinish(ExportGhidraModuleWizard.java:82)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:775)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:414)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:622)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:822)
	at org.eclipse.jface.window.Window.open(Window.java:798)
	at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:315)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:164)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
Caused by: java.lang.NullPointerException
	at ghidradev.ghidraprojectcreator.wizards.ExportGhidraModuleWizard.export(ExportGhidraModuleWizard.java:129)
	at ghidradev.ghidraprojectcreator.wizards.ExportGhidraModuleWizard.lambda$0(ExportGhidraModuleWizard.java:82)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Root exception:
java.lang.NullPointerException
	at ghidradev.ghidraprojectcreator.wizards.ExportGhidraModuleWizard.export(ExportGhidraModuleWizard.java:129)
	at ghidradev.ghidraprojectcreator.wizards.ExportGhidraModuleWizard.lambda$0(ExportGhidraModuleWizard.java:82)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by ryanmkurtz** [comment]
This is the problematic line in GhidraDev:

`String workingDir = project.getRawLocation().toOSString();`

For some reason we can't get the location of your Eclipse project.  Is this a project you created through GhidraDev or did you create it some other way?

**Comment by lab313ru** [comment]
Yes, it was created by GhidraDev. Then I just exported it, skipping `.gradle` dir, and then imported it back to workspace.

**Comment by ryanmkurtz** [comment]
When you say you imported it back, do you mean you went to File -> Import -> Existing Projects into Workspace?  Did you delete the project at some point that you needed to re-import it?

**Comment by lab313ru** [comment]
Yes, I used that way. And I deleted everything before importing.

Try to do it with this source code: https://github.com/lab313ru/ghidra_sega_ldr

**Comment by ryanmkurtz** [comment]
I could not reproduce.  Here is what I did:

1. Create Module project
2. Export extension
3. Delete Module project from Eclipse (I didn't check to box that would have deleted all files on disk)
4. Move Module project to some other location on disk
5. Import existing Module project back into Eclipse workspace.
6. Export extension (which worked)

**Comment by lab313ru** [comment]
> (I didn't check to box that would have deleted all files on disk)

Try with deleting.

**Comment by lab313ru** [comment]
Moving all files (including `.gradle` dir) will help. But its size is ~25 MB.

**Comment by ryanmkurtz** [comment]
If you delete the whole thing from Eclipse, how are you preserving the .project file which is required to import an existing project back into Eclipse?  That shouldn't end up in the extension's zip bundle.

**Comment by lab313ru** [comment]
I mean when you don't check the box about deleting files they are still there and you cannot import back your project. Did you try my project?

**Comment by lab313ru** [comment]
I don't want to export whole gradle things because they are not related to source code.

**Comment by lab313ru** [comment]
> If you delete the whole thing from Eclipse, how are you preserving the .project file which is required to import an existing project back into Eclipse? That shouldn't end up in the extension's zip bundle.

And this file still exist in my exported source code.

**Comment by lab313ru** [comment]
That what I found: gradle is the source of problem. Calling build.gradle doesn't work too.

**Comment by lab313ru** [comment]
`Caused by: org.gradle.api.GradleException: GHIDRA_INSTALL_DIR is not defined!
	at build_77kxvu0my55vghufpmfb19yem.run(D:\eclipse-workspace\Sega\build.gradle:31)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
	... 102 more`

**Comment by ryanmkurtz** [comment]
That is our output...you need to set the GHIDRA_INSTALL_DIR variable when you call gradle so it knows where Ghidra is installed.  There are instructions in your project's build.gradle file.

**Comment by lab313ru** [comment]
I mean, I didn't remove anything about GHIDRA_INSTALL_DIR.

**Comment by lab313ru** [comment]
I'm calling a script using Eclipse

**Comment by ryanmkurtz** [comment]
Does your Eclipse project have an externally linked Ghidra directory?  That's the GhidraDev knows what Ghidra to use.  When you used the wizard to create the module project....it should have created that for you.

**Comment by lab313ru** [comment]
![изображение](https://user-images.githubusercontent.com/7189309/55170632-f1c27a80-5187-11e9-88fd-ee13dce99b24.png)

**Comment by ryanmkurtz** [comment]
The only thing that looks unexpected about that file is that it has the gradle nature added.  Did you do that manually?  Not sure if that would cause the problems.

**Comment by lab313ru** [comment]
I tried to fix NullPointerException problem using adding Gradle nature.

**Comment by lab313ru** [comment]
Did you try my github project to build by yourself?

**Comment by ryanmkurtz** [comment]
No, unfortunately I am not going to be able to try your project.

**Comment by lab313ru** [comment]
![изображение](https://user-images.githubusercontent.com/7189309/55171358-41557600-5189-11e9-915e-52a25e3176a5.png)

![изображение](https://user-images.githubusercontent.com/7189309/55171433-6813ac80-5189-11e9-8ea9-90fac5446d79.png)

![изображение](https://user-images.githubusercontent.com/7189309/55171480-79f54f80-5189-11e9-9fc9-f12d30ca834f.png)

![изображение](https://user-images.githubusercontent.com/7189309/55171517-88436b80-5189-11e9-9d07-41ba09b100fc.png)

Null Pointer Exception.

**Comment by ryanmkurtz** [comment]
Thanks, I am getting the exception now.  I didn't realize you were exporting the project as Archive File.  I thought you were just exporting it as an extension.

**Comment by ryanmkurtz** [comment]
Looks like project.getRawLocation() is returning null only after the project is reimported.  Using project.getLocation() seems to be the correct method to call.  

Until this is fixed, you can use GhidraDev to create a new module project and then manually copy your source files back into it.  Thanks for reporting this and helping to get it sorted out!

**Comment by lab313ru** [comment]
Ok, thank you!

**Comment by ryanmkurtz** [comment]
Sure thing!

**Comment by ryanmkurtz** [comment]
Relates to #284

**Comment by lab313ru** [comment]
Temporary solution:
Fixed classes (`getRawLocation()` -> `getLocation()`). Update them in your ghidradev's jar-file: [GhidraDevFixedClasses.zip](https://github.com/NationalSecurityAgency/ghidra/files/3024802/GhidraDevFixedClasses.zip)

Or use updated `GhidraDev-2.0.0.zip`: [GhidraDev-2.0.0.zip](https://github.com/NationalSecurityAgency/ghidra/files/3024803/GhidraDev-2.0.0.zip)

**Comment by lab313ru** [comment]
Also, it is required to uninstall, then remove: `~/.p2/pool/plugins/ghidra.ghidradev_2.0.0.*.jar`, and install plugin again.

**Comment by lab313ru** [comment]
Is it fixed in 9.0.2?

**Comment by ryanmkurtz** [comment]
No, I didn't have time to sufficiently test it for 9.0.2.  I will use your pull request for this if possible...thanks!

**Comment by lab313ru** [comment]
Yes, pull request is ok. It just uses getLocation instead of getRawLocation (it works for me)
