### ISSUE TITLE
[Debugger]: Windows Launch Fails via "Exec" (but works with "Quick Launch")

### ISSUE THREAD

**Issue by chezwicker** [NationalSecurityAgency/ghidra#2841]
**Describe the bug**

Trying to debug a program under Windows works using "Quick Launch", but fails when started using "Exec".

**To Reproduce**

1. Open the *Ghidra* debugger tool for a program
2. Use "Quick Launch" -> works
3. Re-use the created debugger object and try the "Exec" button
4. Provide the location of the program
   * the goal is to launch with a command line argument, but it doesn't work without one either
   * if the selected node is "Connectors" > "Launch process", the behavior is different than otherwise
5. Be frustrated by the error message

**Expected behavior**

**Attachments**

Stack trace for launch from e.g. "Debugger":

```
ghidra.dbg.error.DebuggerUserException: Launch failed for {CommandLine=x:\ex1-win.exe secret}
java.util.concurrent.CompletionException: ghidra.dbg.error.DebuggerUserException: Launch failed for {CommandLine=x:\ex1-win.exe secret}
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at ghidra.async.AsyncPairingCache.fulfill(AsyncPairingCache.java:166)
	at ghidra.dbg.gadp.client.GadpClient.lambda$receiveLoop$8(GadpClient.java:392)
	at ghidra.async.loop.AsyncLoop$1.consume(AsyncLoop.java:53)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at ghidra.async.seq.AsyncSequenceWithTemp$AbstractHandler.exit(AsyncSequenceWithTemp.java:52)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at ghidra.async.loop.AsyncLoop$1.exit(AsyncLoop.java:68)
	at ghidra.async.AsyncHandlerCanExit.exit(AsyncHandlerCanExit.java:49)
	at ghidra.dbg.gadp.util.AsyncProtobufMessageChannel.lambda$read$4(AsyncProtobufMessageChannel.java:154)
	at ghidra.async.loop.AsyncLoop$2.lambda$repeat$0(AsyncLoop.java:87)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: ghidra.dbg.error.DebuggerUserException: Launch failed for {CommandLine=x:\ex1-win.exe secret}
	at ghidra.dbg.gadp.client.GadpClient.checkError(GadpClient.java:166)
	at ghidra.dbg.gadp.client.GadpClient.lambda$sendChecked$6(GadpClient.java:372)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 24 more
```

Stack trace for launch from "Debugger" > "Connectors" > "Launch process":

```
ghidra.dbg.error.DebuggerIllegalArgumentException: Missing required parameter args
java.util.concurrent.CompletionException: ghidra.dbg.error.DebuggerIllegalArgumentException: Missing required parameter args
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at ghidra.async.AsyncPairingCache.fulfill(AsyncPairingCache.java:166)
	at ghidra.dbg.gadp.client.GadpClient.lambda$receiveLoop$8(GadpClient.java:392)
	at ghidra.async.loop.AsyncLoop$1.consume(AsyncLoop.java:53)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at ghidra.async.seq.AsyncSequenceWithTemp$AbstractHandler.exit(AsyncSequenceWithTemp.java:52)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at ghidra.async.loop.AsyncLoop$1.exit(AsyncLoop.java:68)
	at ghidra.async.AsyncHandlerCanExit.exit(AsyncHandlerCanExit.java:49)
	at ghidra.dbg.gadp.util.AsyncProtobufMessageChannel.lambda$read$4(AsyncProtobufMessageChannel.java:154)
	at ghidra.async.loop.AsyncLoop$2.lambda$repeat$0(AsyncLoop.java:87)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: ghidra.dbg.error.DebuggerIllegalArgumentException: Missing required parameter args
	at ghidra.dbg.gadp.client.GadpClient.checkError(GadpClient.java:150)
	at ghidra.dbg.gadp.client.GadpClient.lambda$sendChecked$6(GadpClient.java:372)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 24 more
```

**Environment (please complete the following information):**
 - OS: Windows 10 10.0 amd64 (VM)
 - Java Version: AdoptOpenJDK 11.0.10
 - Ghidra Version: 9.3 DEV, commit b69c3d6
 - Ghidra Origin: locally built

**Comment by nsadeveloper789** [comment]
Looks like this is an issue in the parameter descriptions for dbgeng's process launcher. We're in the middle of a refactor of our connector API, including some test suites, which should cover this. In the meantime, a workaround you can try, if you need to pass command-line parameters to the target process, is to use the "Interpreter" window. It should appear automatically once you're connected to dbgeng, but if it doesn't, there should be a console-looking button in the "Objects" window that should pop it up. You may need to select the Session node first. It takes the usual WinDbg commands.

**Comment by d-millar** [comment]
@chezwicker yeah, that was a type on my part - if you'd prefer not to wait for the fix, change "CommandLine" to "Command line" on line 61 of DbgModelTargetProcessLaunchConnectorImpl.  Apologies!

**Comment by chezwicker** [comment]
@nsadeveloper789: thank you for the feedback, I can indeed work that way. Any idea when the refactored code will hit the repo? I'm teaching RE using *Ghidra* and it's already challenging ;-)

@d-millar: thanks for the hint, unfortunately

* we seem to be looking at different sources, for me (in [c81a174](https://github.com/NationalSecurityAgency/ghidra/commit/c81a17405da4b568d3a8b25f3c88094f2da22483)), "CommandLine" is on line 64
* changing to "Command line" doesn't seem to fix the problem, I get exactly the same output

Am I missing something?

**Comment by d-millar** [comment]
Apologies again - looking at the wrong version.  Try "Command Line" on line 64.   *sigh*

**Comment by chezwicker** [comment]
@d-millar : I guessed that and tried all other kinds of variations as well ;-) But unfortunately didn't work either ;-(

Since the only place outside this source I found was "Command Line", I also tried setting both L64 &L65 to that, but to no avail. Does it just have to match the map entry or something else?

Sorry, I would normally debug myself, but unfortunately can't atm ;-(

**Comment by d-millar** [comment]
@chezwicker  huh, ok, I'm kind of stumped.  I thought the "create" parameter in DbgModelTargetProcessLauncherImpl just had to match the PARAMETER_CMDLINE_ARGS in TargetLauncher.  Just so we're comparing apples to apples, my test was to connect using the IN-VM dbgeng connection, to open Connectors, highlight the Launch connector, hit the Launch button, and enter "notepad.exe junk.txt".  Close to yours?

**Comment by chezwicker** [comment]
@d-millar: Ok, we're getting closer, and I now found a way that works (but it strangely isn't the one you described, if I do that, I get the error "ghidra.dbg.error.DebuggerIllegalArgumentException: Missing required parameter args". The "Launch" dialog in that case shows "Cmd" instead of "Command Line")

If I select the "Debugger" or "Connectors" node instead, I get "Command Line", and it suddenly works!

My previous approach was to do what I believe quick launch does: connect using "MS dbgeng.dll (WinDbg) local agent via GADP/TCP)". That still doesn't work - I think there's another connector used since it shows "CMD" as well. Maybe the in-memory connector should be the one quick launch uses as well?

Fantastic, I have a working approach - thank you very much!

**Comment by d-millar** [comment]
Ah, excellent - for me too, as I can now reproduce the error.  Will take a look at this tomorrow.  Definitely a little lack of consistency in our interfaces!  FYI, the reason we default to "MS dbgeng" versus the "IN-VM" version is that, if something goes wrong with the debugger in the latter case, there's a chance it'll take Ghidra with it.  We try not to default to linking in native code that can potentially crash the main Java VM.  So, caveat emptor, although I must admit I've never seen it do this.  One other difference:  right now, the GADP versions have a better caching story, so the IN-VM version, while probably faster, may be doing a lot of extra work.

**Comment by chezwicker** [comment]
By the way, since you're refactoring, wouldn't it make sense to enhance the "Quick Launch" action to accept parameters to be passed to the program launched? I would assume the typical use case is to work with an imported program. If the goal is to save a second click in the default-default case (assuming that's a no-param launch), maybe a second "Parameterized Quick Launch" would be possible, which would allow users to pass parameters and to decide whether to launch "IN-VM" or in a separate process? I could imagine that'd be nice especially for more casual users.

**Comment by d-millar** [comment]
@chezwicker Not a bad idea - will add a ticket!

**Comment by nsadeveloper789** [comment]
Yeah, and it wouldn't be too terrible to implement either. A more pluggable "quick launch" system has been on my list. At the moment, it selects the 1 offer with the highest priority. I think it'd just be a matter of using a "drop-down" button. The button could invoke the one with highest priority, but the drop-down could let the user invoke any qualifying offer, also re-assigning it to the highest priority.

**Comment by nsadeveloper789** [comment]
I believe this issue has been resolved. I've also gone ahead an implemented the drop-down launcher thing, but I haven't pushed it quite yet.
