### ISSUE TITLE
Used to be able to open project; can't now (Mac OS X 11.2.3 Apple M1)

### ISSUE THREAD

**Issue by brandonros** [NationalSecurityAgency/ghidra#2888]
**Describe the bug**

```
Could not initialize class org.apache.felix.framework.URLHandlersStreamHandlerProxy
java.lang.NoClassDefFoundError: Could not initialize class org.apache.felix.framework.URLHandlersStreamHandlerProxy
	at org.apache.felix.framework.URLHandlers.createURLStreamHandler(URLHandlers.java:513)
	at java.base/java.net.URL.getURLStreamHandler(URL.java:1440)
	at java.base/java.net.URL.<init>(URL.java:678)
	at java.base/java.net.URL.<init>(URL.java:568)
	at java.base/java.net.URL.<init>(URL.java:515)
	at ghidra.framework.protocol.ghidra.GhidraURL.makeURL(GhidraURL.java:281)
	at ghidra.framework.model.ProjectLocator.<init>(ProjectLocator.java:51)
	at ghidra.framework.main.FrontEndPlugin.chooseProject(FrontEndPlugin.java:517)
	at ghidra.framework.main.FileActionManager.openProject(FileActionManager.java:246)
	at ghidra.framework.main.FileActionManager$2.actionPerformed(FileActionManager.java:100)
	at docking.DockingActionProxy.actionPerformed(DockingActionProxy.java:47)
	at docking.MenuBarMenuHandler.lambda$processMenuAction$0(MenuBarMenuHandler.java:64)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2020-Dec-29 1701 EST
Ghidra Version: 9.2.2
Java Home: /Users/brandonros/Desktop/jdk-16+36/Contents/Home
JVM Version: AdoptOpenJDK 16
OS: Mac OS X 10.16 x86_64
Workstation: 192.168.64.1

```

**To Reproduce**

1. Try to open project that used to work.

**Expected behavior**

1. Project to open again how it used to.

**Screenshots**
![image](https://user-images.githubusercontent.com/8949910/113224190-e44d9880-9258-11eb-9991-56d3790492d5.png)

**Environment (please complete the following information):**
 - OS: Mac OS X 11.2.3
 - Java Version:
```
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 16+36, mixed mode, sharing)
```
 - Ghidra Version: 9.2.2
 - Ghidra Origin: official ghidra-sre.org distro

**Comment by brandonros** [comment]
I haven't changed the `AdoptOpenJDK` version I was on, no.

**Comment by ryanmkurtz** [comment]
Can you try this: https://github.com/NationalSecurityAgency/ghidra/issues/2879#issuecomment-810161137

**Comment by brandonros** [comment]
Trying now.

I also get this error intermittently:

```
java.lang.ExceptionInInitializerError
	at org.apache.felix.framework.URLHandlers.createURLStreamHandler(URLHandlers.java:513)
	at java.base/java.net.URL.getURLStreamHandler(URL.java:1431)
	at java.base/java.net.URL.<init>(URL.java:678)
	at java.base/java.net.URL.<init>(URL.java:568)
	at java.base/java.net.URL.<init>(URL.java:515)
	at ghidra.framework.protocol.ghidra.GhidraURL.makeURL(GhidraURL.java:281)
	at ghidra.framework.model.ProjectLocator.<init>(ProjectLocator.java:51)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.getDomainFile(ProgramManagerPlugin.java:956)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.loadPrograms(ProgramManagerPlugin.java:911)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.readDataState(ProgramManagerPlugin.java:846)
	at ghidra.framework.plugintool.PluginManager.restoreDataStateFromXml(PluginManager.java:343)
	at ghidra.framework.plugintool.PluginTool.restoreDataStateFromXml(PluginTool.java:537)
	at ghidra.framework.project.tool.WorkspaceImpl.restoreFromXml(WorkspaceImpl.java:188)
	at ghidra.framework.project.tool.ToolManagerImpl.restoreFromXml(ToolManagerImpl.java:324)
	at ghidra.framework.project.DefaultProject.restore(DefaultProject.java:473)
	at ghidra.framework.project.DefaultProjectManager.openProject(DefaultProjectManager.java:142)
	at ghidra.GhidraRun.doOpenProject(GhidraRun.java:195)
	at ghidra.GhidraRun.lambda$openProject$3(GhidraRun.java:186)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1079)
	at java.desktop/java.awt.Component.show(Component.java:1722)
	at java.desktop/java.awt.Component.setVisible(Component.java:1669)
	at java.desktop/java.awt.Window.setVisible(Window.java:1034)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1016)
	at docking.DockingDialog.setVisible(DockingDialog.java:354)
	at docking.DockingWindowManager.lambda$doShowDialog$6(DockingWindowManager.java:1732)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at docking.DockingWindowManager.doShowDialog(DockingWindowManager.java:1736)
	at docking.DockingWindowManager.showDialog(DockingWindowManager.java:1768)
	at ghidra.util.task.TaskDialog.lambda$doShow$7(TaskDialog.java:291)
	at ghidra.util.Swing.runIfSwingOrRunLater(Swing.java:124)
	at ghidra.util.task.TaskDialog.doShow(TaskDialog.java:288)
	at ghidra.util.task.TaskDialog.doShowModal(TaskDialog.java:269)
	at ghidra.util.task.TaskDialog.show(TaskDialog.java:243)
	at ghidra.util.task.TaskRunner.lambda$showTaskDialog$1(TaskRunner.java:117)
	at ghidra.util.Swing.runIfSwingOrRunLater(Swing.java:124)
	at ghidra.util.task.TaskRunner.showTaskDialog(TaskRunner.java:114)
	at ghidra.util.task.TaskRunner.run(TaskRunner.java:52)
	at ghidra.util.task.TaskLauncher.<init>(TaskLauncher.java:221)
	at ghidra.util.task.TaskLauncher.<init>(TaskLauncher.java:203)
	at ghidra.GhidraRun.openProject(GhidraRun.java:189)
	at ghidra.GhidraRun.openProject(GhidraRun.java:178)
	at ghidra.GhidraRun.lambda$launch$0(GhidraRun.java:96)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.RuntimeException: Unable to make protected boolean java.net.URLStreamHandler.equals(java.net.URL,java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @7a2f154c
	at org.apache.felix.framework.URLHandlersStreamHandlerProxy.<clinit>(URLHandlersStreamHandlerProxy.java:104)
	... 72 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected boolean java.net.URLStreamHandler.equals(java.net.URL,java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @7a2f154c
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.apache.felix.framework.util.SecureAction.setAccesssible(SecureAction.java:871)
	at org.apache.felix.framework.URLHandlersStreamHandlerProxy.<clinit>(URLHandlersStreamHandlerProxy.java:79)
	... 72 more

---------------------------------------------------
Build Date: 2020-Dec-29 1701 EST
Ghidra Version: 9.2.2
Java Home: /Users/brandonros/Desktop/jdk-17.jdk/Contents/Home
JVM Version: Oracle Corporation 17-ea
OS: Mac OS X 11.2 x86_64
Workstation: 192.168.64.1
```

**Comment by brandonros** [comment]
That fixed it, thanks.
