### ISSUE TITLE
Restoring/Importing Ghidra Archive in Headless Mode? 

### ISSUE THREAD

**Issue by robertzak133** [NationalSecurityAgency/ghidra#2936]
Does Ghidra headless mode allow me to import an archived (.gar) Ghidra project?  Is there some other CLI utility which will restore a ghidra project from a .gar archive that headless mode does recognize? 

I'd like to be able to run program-dependent script files in headless mode from a program in a project which has been archived

(this to avoid userid issues when running in headless mode in Google Colab, vs. in GUI mode on my PC -- which prevents me from just using the raw Ghidra project file)

The headless README doesn't seem to address this case, and simply specifying the .gar file as the existing project doesn't seem to work (see below) .  Obviously, running my program-dependent script doesn't work without a program :(

Colab command and output below: 
```
! analyzeHeadless $REPOSITORY_BASE/ghidra btc-7a-8a-reverse_2021_04_13.gar -process
OpenJDK 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "ghidra.GhidraClassLoader"). To use archived non-system classes, this property must be not be set
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)
INFO  Using log config file: jar:file:/content/ghidra_9.2.2_PUBLIC/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)  
INFO  Using log file: /root/.ghidra/.ghidra_9.2.2_PUBLIC/application.log (LoggingInitialization)  
INFO  Loading user preferences: /root/.ghidra/.ghidra_9.2.2_PUBLIC/preferences (Preferences)  
INFO  Class search complete (1829 ms) (ClassSearcher)  
INFO  Initializing SSL Context (SSLContextInitializer)  
INFO  Initializing Random Number Generator... (SecureRandomFactory)  
INFO  Random Number Generator initialization complete: NativePRNGNonBlocking (SecureRandomFactory)  
INFO  Trust manager disabled, cacerts have not been set (ApplicationTrustManagerFactory)  
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender (file:/content/ghidra_9.2.2_PUBLIC/Ghidra/Features/Base/lib/org.apache.felix.framework-6.0.3.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  HEADLESS Script Paths:
    /content/ghidra_9.2.2_PUBLIC/Ghidra/Features/Decompiler/ghidra_scripts
    /content/ghidra_9.2.2_PUBLIC/Ghidra/Processors/DATA/ghidra_scripts
    /content/ghidra_9.2.2_PUBLIC/Ghidra/Features/VersionTracking/ghidra_scripts
    /content/ghidra_9.2.2_PUBLIC/Ghidra/Features/FunctionID/ghidra_scripts
    /content/ghidra_9.2.2_PUBLIC/Ghidra/Features/FileFormats/ghidra_scripts
    /content/ghidra_9.2.2_PUBLIC/Ghidra/Processors/8051/ghidra_scripts
    /content/ghidra_9.2.2_PUBLIC/Ghidra/Features/BytePatterns/ghidra_scripts
    /content/ghidra_9.2.2_PUBLIC/Ghidra/Processors/PIC/ghidra_scripts
    /content/ghidra_9.2.2_PUBLIC/Ghidra/Features/GnuDemangler/ghidra_scripts
    /content/ghidra_9.2.2_PUBLIC/Ghidra/Features/Python/ghidra_scripts
    /content/ghidra_9.2.2_PUBLIC/Ghidra/Features/Base/ghidra_scripts (HeadlessAnalyzer)  
INFO  HEADLESS: execution starts (HeadlessAnalyzer)  
ERROR Could not find project: /content/drive/MyDrive/local_repositories/BTC-Reverse/ghidra/btc-7a-8a-reverse_2021_04_13.gar -- should already exist in -process mode. (HeadlessAnalyzer)  
ERROR Abort due to Headless analyzer error: Could not find project: /content/drive/MyDrive/local_repositories/BTC-Reverse/ghidra/btc-7a-8a-reverse_2021_04_13.gar (HeadlessAnalyzer) java.io.IOException: Could not find project: /content/drive/MyDrive/local_repositories/BTC-Reverse/ghidra/btc-7a-8a-reverse_2021_04_13.gar
	at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:420)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:121)
	at ghidra.GhidraLauncher.main(GhidraLauncher.java:82)
```

**Comment by ryanmkurtz** [comment]
No, headless does not allow this.
