### ISSUE TITLE
ghidra server: stop using SHA1withRSA for certificate validation

### ISSUE THREAD

**Issue by draeath** [NationalSecurityAgency/ghidra#2955]
**Describe the bug**
On OpenSUSE Tumbleweed (and presumably other distributions) crypto algorithms known to be weak have started being disabled. This causes connection failures to ghidra servers unless local java security configuration is overridden to re-enable this algorithm.

**To Reproduce**
1. Launch ghidra on OpenSUSE Tumbleweed /w java-11-openjdk packages
2. Connect to a ghidra server

**Expected behavior**
Normal connectivity with ghidra server, using a modern certificate signing algorithm, or in the case that this is due to an older repository, regeneration of the server certificate /w a correct algorithm

**Screenshots**
N/A

**Attachments**
    Certificates do not conform to algorithm constraints
    javax.net.ssl.SSLHandshakeException: Certificates do not conform to algorithm constraints
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1408)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1314)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
        at ghidra.framework.client.ServerConnectTask.testServerSSLConnection(ServerConnectTask.java:332)
        at ghidra.framework.client.ServerConnectTask.getGhidraServerHandle(ServerConnectTask.java:156)
        at ghidra.framework.client.ServerConnectTask.getRepositoryServerHandle(ServerConnectTask.java:207)
        at ghidra.framework.client.ServerConnectTask.run(ServerConnectTask.java:72)
        at ghidra.util.task.Task.monitoredRun(Task.java:124)
        at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:104)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: java.security.cert.CertificateException: Certificates do not conform to algorithm constraints
        at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAlgorithmConstraints(SSLContextImpl.java:1642)
        at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:1567)
        at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1511)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
        ... 20 more
    Caused by: java.security.cert.CertPathValidatorException: Algorithm constraints check failed on signature algorithm: SHA1withRSA
        at java.base/sun.security.provider.certpath.AlgorithmChecker.check(AlgorithmChecker.java:278)
        at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAlgorithmConstraints(SSLContextImpl.java:1638)
        ... 23 more

    ---------------------------------------------------
    Build Date: 2020-Dec-29 1701 EST
    Ghidra Version: 9.2.2
    Java Home: /usr/lib64/jvm/java-11-openjdk-11
    JVM Version: Oracle Corporation 11.0.10
    OS: Linux 5.11.12-1-default amd64
    Workstation: redacted

    redacted:/tmp # cat /etc/crypto-policies/back-ends/java.config 
    jdk.tls.ephemeralDHKeySize=2048
    jdk.certpath.disabledAlgorithms=MD2, SHA1, MD5, DSA, RSA keySize < 2048
    jdk.tls.disabledAlgorithms=DH keySize < 2048, SSLv2, SSLv3, TLSv1, TLSv1.1, DHE_DSS, RSA_EXPORT, DHE_DSS_EXPORT, DHE_RSA_EXPORT, DH_DSS_EXPORT, DH_RSA_EXPORT, DH_anon, ECDH_anon, DH_RSA, DH_DSS, ECDH, 3DES_EDE_CBC, DES_CBC, RC4_40, RC4_128, DES40_CBC, RC2, HmacMD5
    jdk.tls.legacyAlgorithms=
        
    redacted:/tmp # rpm -ql crypto-policies | grep /etc/crypto-policies/back-ends/java.config
    /etc/crypto-policies/back-ends/java.config
        
    redacted:/tmp # zypper info crypto-policies
    Loading repository data...
    Reading installed packages...
        
        
    Information for package crypto-policies:
    ----------------------------------------
    Repository     : Main Repository (OSS)
    Name           : crypto-policies
    Version        : 20210225.05203d2-1.2
    Arch           : noarch
    Vendor         : openSUSE
    Installed Size : 84.8 KiB
    Installed      : Yes (automatically)
    Status         : up-to-date
    Source package : crypto-policies-20210225.05203d2-1.2.src
    Summary        : System-wide crypto policies
    Description    : 
        This package provides pre-built configuration files with
        cryptographic policies for various cryptographic back-ends,
        such as SSL/TLS libraries.

**Environment (please complete the following information):**
 - OS: OpenSUSE Tumbleweed x86_64 20210417
 - Java Version: OpenJDK 64-Bit Server VM (build 11.0.10+9-suse-2.1-x8664, mixed mode)
 - Ghidra Version: 9.2.2 (test on 9.2.3 pending)
 - Ghidra Origin: official ghidra-sre.org

**Additional context**
I am running the server in a container, you can see this [here](https://github.com/draeath/ghidraSvr-in-a-box/blob/master/ghidraSvr-in-a-box/Dockerfile) if it is informative.

**Comment by draeath** [comment]
This might have been fixed by GP-622 in 9.2.3, I'm verifying and will update or close this issue shortly.

**Comment by draeath** [comment]
Confirmed GP-622 did **not** resolve this, it also occurs when both client/server are running 9.2.3.

**Comment by ghidra1** [comment]
Ghidra relies entirely on the installed Java for client/server crypto negotiation, which may be influenced by certificate data.  Ghidra does not attempt to restrict crypto algorithm use other than facilitating TLS version restriction.
