### ISSUE TITLE
Plugin Event Error

### ISSUE THREAD

**Issue by theclub654** [NationalSecurityAgency/ghidra#2999]
ever time i try to open a exe i get this 
java.lang.NoClassDefFoundError: Could not initialize class net.sf.cglib.proxy.Enhancer
java.lang.RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class net.sf.cglib.proxy.Enhancer
	at generic.continues.ContinuesFactory.create(ContinuesFactory.java:61)
	at ghidra.app.util.bin.format.mz.DOSHeader.createDOSHeader(DOSHeader.java:100)
	at ghidra.app.plugin.prototype.MicrosoftCodeAnalyzerPlugin.PEUtil.canAnalyze(PEUtil.java:51)
	at ghidra.app.plugin.prototype.MicrosoftCodeAnalyzerPlugin.PropagateExternalParametersAnalyzer.canAnalyze(PropagateExternalParametersAnalyzer.java:236)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.initializeAnalyzers(AutoAnalysisManager.java:165)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.<init>(AutoAnalysisManager.java:147)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.getAnalysisManager(AutoAnalysisManager.java:983)
	at ghidra.app.plugin.core.analysis.AutoAnalysisPlugin.programOpened(AutoAnalysisPlugin.java:261)
	at ghidra.app.plugin.core.analysis.AutoAnalysisPlugin.processEvent(AutoAnalysisPlugin.java:245)
	at ghidra.framework.plugintool.Plugin.eventSent(Plugin.java:329)
	at ghidra.framework.plugintool.mgr.EventManager.sendEvents(EventManager.java:263)
	at ghidra.framework.plugintool.mgr.EventManager.lambda$new$3(EventManager.java:49)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.framework.plugintool.mgr.EventManager.fireEvent(EventManager.java:206)
	at ghidra.framework.plugintool.PluginTool.firePluginEvent(PluginTool.java:475)
	at ghidra.framework.plugintool.Plugin.firePluginEvent(Plugin.java:481)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.fireOpenEvents(MultiProgramManager.java:261)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.addProgram(MultiProgramManager.java:81)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.lambda$openProgram$6(ProgramManagerPlugin.java:489)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.util.SystemUtilities.runSwingNow(SystemUtilities.java:225)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.openProgram(ProgramManagerPlugin.java:495)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.openPrograms(ProgramManagerPlugin.java:761)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.acceptData(ProgramManagerPlugin.java:139)
	at ghidra.framework.plugintool.PluginManager.acceptData(PluginManager.java:48)
	at ghidra.framework.plugintool.PluginTool.acceptDomainFiles(PluginTool.java:414)
	at ghidra.framework.main.ToolButton.openDomainFiles(ToolButton.java:647)
	at ghidra.framework.main.ToolButton$2.end(ToolButton.java:625)
	at ghidra.framework.main.ZoomImageRunner$1.end(ZoomImageRunner.java:54)
	at org.jdesktop.animation.timing.Animator.end(Animator.java:755)
	at org.jdesktop.animation.timing.Animator.stop(Animator.java:660)
	at org.jdesktop.animation.timing.Animator.timingEvent(Animator.java:732)
	at org.jdesktop.animation.timing.Animator.access$200(Animator.java:75)
	at org.jdesktop.animation.timing.Animator$TimerTarget.actionPerformed(Animator.java:1041)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:310)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:242)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.sf.cglib.proxy.Enhancer
	at generic.continues.ContinuesFactory.create(ContinuesFactory.java:45)
	... 52 more

---------------------------------------------------
Build Date: 2021-Mar-25 1203 EDT
Ghidra Version: 9.2.3
Java Home: C:\Program Files\Java\jdk-16
JVM Version: Oracle Corporation 16
OS: Windows 10 10.0 amd64
Workstation: 10.0.0.65

**Comment by dev747368** [comment]
Could you try again using java 11?

**Comment by ryanmkurtz** [comment]
To get Ghidra 9.2.3 working with java 16, you need to add the following line to your `support/launch.properties` file:
```
VMARGS=--illegal-access=permit
```

This will be fixed in 9.2.4 when it's released.
