### ISSUE TITLE
Debugger show exception

### ISSUE THREAD

**Issue by xNxExOx** [NationalSecurityAgency/ghidra#3048]
**Describe the bug**
`class java.util.Date cannot be cast to class ghidra.app.plugin.core.debug.gui.console.DebuggerConsoleProvider$ActionList`
when trying to debug simple console application.
I think it pop up on Launch, continue, interupt, and close of the application.

**To Reproduce**
1. Go to 'Debugger'
2. Click on 'Launch (X)'
3. Enter path to C++ aplication (exe file)

**Expected behavior**
No error

**Attachments**
```
class java.util.Date cannot be cast to class ghidra.app.plugin.core.debug.gui.console.DebuggerConsoleProvider$ActionList (java.util.Date is in module java.base of loader 'bootstrap'; ghidra.app.plugin.core.debug.gui.console.DebuggerConsoleProvider$ActionList is in unnamed module of loader ghidra.GhidraClassLoader @4ca8195f)
java.lang.ClassCastException: class java.util.Date cannot be cast to class ghidra.app.plugin.core.debug.gui.console.DebuggerConsoleProvider$ActionList (java.util.Date is in module java.base of loader 'bootstrap'; ghidra.app.plugin.core.debug.gui.console.DebuggerConsoleProvider$ActionList is in unnamed module of loader ghidra.GhidraClassLoader @4ca8195f)
	at ghidra.app.plugin.core.debug.gui.console.DebuggerConsoleProvider$LogTable.computePreferredHeight(DebuggerConsoleProvider.java:238)
	at ghidra.app.plugin.core.debug.gui.console.DebuggerConsoleProvider$LogTable.updateRowHeights(DebuggerConsoleProvider.java:229)
	at ghidra.app.plugin.core.debug.gui.console.DebuggerConsoleProvider$LogTable.lambda$tableChanged$0(DebuggerConsoleProvider.java:209)
	at ghidra.util.Swing.runIfSwingOrRunLater(Swing.java:124)
	at ghidra.app.plugin.core.debug.gui.console.DebuggerConsoleProvider$LogTable.tableChanged(DebuggerConsoleProvider.java:209)
	at docking.widgets.table.TableModelWrapper.fireTableDataChanged(TableModelWrapper.java:107)
	at docking.widgets.table.GTableFilterPanel$TranslatingTableModelListener.tableChanged(GTableFilterPanel.java:849)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:297)
	at docking.widgets.table.AbstractSortedTableModel.fireTableChanged(AbstractSortedTableModel.java:113)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableDataChanged(AbstractTableModel.java:199)
	at ghidra.app.plugin.core.debug.utils.DebouncedRowWrappedEnumeratedColumnTableModel.lambda$settled$0(DebouncedRowWrappedEnumeratedColumnTableModel.java:67)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2021-kvì-19 1040 SELÈ
Ghidra Version: 10.0
Java Home: C:\Program Files\AdoptOpenJDK\jdk-11.0.9.101-hotspot
JVM Version: AdoptOpenJDK 11.0.9.1
OS: Windows 10 10.0 amd64
Workstation: DESKTOP-ITVHNK7
```

**Environment (please complete the following information):**
 - OS: Windows 10.0.19042
 - Java Version: openjdk 11.0.9.1 2020-11-04
 - Ghidra Version: 10.0 master (https://github.com/NationalSecurityAgency/ghidra/commit/296360eb3479e70eb734a2abf2eded06b84e3d69)
 - Ghidra Origin: locally built

**Additional context**
I switched to very simple C++ application, because I want to eliminate all other problems I have with the debugger
```cpp
#include <iostream>
#include <thread>

int main()
{
    std::cout << "Hello World!\n";
    auto i = 1;
    while (true)
    {
        std::this_thread::sleep_for(std::chrono::seconds(1));
        std::cout << i++ << "\n";
    }
}
```

**Comment by d-millar** [comment]
Not seeing this on the current internal build - perhaps fixed by next push?

**Comment by xNxExOx** [comment]
https://github.com/NationalSecurityAgency/ghidra/commit/296360eb3479e70eb734a2abf2eded06b84e3d69 this one does not seem to have any actual effect on any code, I can upload the binary if that would help, or update to newer version, if you really think it might help

**Comment by d-millar** [comment]
Sorry, apologies wasn't terribly clear....  I built and tested your binary with our development version of the "debugger" branch, which is ahead slightly of the public "debugger" branch, which in turn is ahead of the "master" branch.  So, I think the problem has been fixed, but, of course, that doesn't help you out very much.  Have you tried the same experiment with the "debugger" branch?

**Comment by d-millar** [comment]
@xNxExOx Ah, we have it - able to reproduce your bug.  THANK YOU!

Apparently, our tables aren't handling column re-ordering correctly!  For the moment, the stupid solution for you problem is put the columns on the Console back in the order:  Level, Message, Actions, Time.  That said, am putting in a ticket as I type.

**Comment by xNxExOx** [comment]
https://github.com/NationalSecurityAgency/ghidra/branches public debugger branch is 70 commits behind the master and 0 ahead, so I assumed, someone just forget to delete it after merge.
😮 yes I reordered columns, to have actions last.
So tomorrow I will try to reproduce my other problems on something that is smaller, than whole game, and report another bug(s).

**Comment by d-millar** [comment]
OK, well, we're working on that one - keep them coming!   We appreciate your willingness to test drive!

**Comment by xNxExOx** [comment]
I just need debugger, because of lazy loading stuff, and it was originally promissed quite some time back (not blaming), so I decided to build it, instead of more waiting. I am still deciding if it is worth the effort learning it over IDA.
