### ISSUE TITLE
Closing Debug console Exception

### ISSUE THREAD

**Issue by xNxExOx** [NationalSecurityAgency/ghidra#3053]
**Describe the bug**
Closing Debug console throws Exception during debugging

**To Reproduce**
1. Go to 'Debugger'
2. Close 'Debug console'
3. Launch, or probably anything that generate event to Debug console

**Expected behavior**
No error.

**Attachments**
```
java.lang.NullPointerException
	at ghidra.app.plugin.core.debug.gui.console.DebuggerConsoleProvider$LogTable.computePreferredHeight(DebuggerConsoleProvider.java:239)
	at ghidra.app.plugin.core.debug.gui.console.DebuggerConsoleProvider$LogTable.updateRowHeights(DebuggerConsoleProvider.java:229)
	at ghidra.app.plugin.core.debug.gui.console.DebuggerConsoleProvider$LogTable.lambda$tableChanged$0(DebuggerConsoleProvider.java:209)
	at ghidra.util.Swing.runIfSwingOrRunLater(Swing.java:124)
	at ghidra.app.plugin.core.debug.gui.console.DebuggerConsoleProvider$LogTable.tableChanged(DebuggerConsoleProvider.java:209)
	at docking.widgets.table.TableModelWrapper.fireTableDataChanged(TableModelWrapper.java:107)
	at docking.widgets.table.GTableFilterPanel$TranslatingTableModelListener.tableChanged(GTableFilterPanel.java:849)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:297)
	at docking.widgets.table.AbstractSortedTableModel.fireTableChanged(AbstractSortedTableModel.java:113)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableDataChanged(AbstractTableModel.java:199)
	at ghidra.app.plugin.core.debug.utils.DebouncedRowWrappedEnumeratedColumnTableModel.lambda$settled$0(DebouncedRowWrappedEnumeratedColumnTableModel.java:67)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2021-kvì-20 1752 SELÈ
Ghidra Version: 10.0
Java Home: C:\Program Files\AdoptOpenJDK\jdk-11.0.9.101-hotspot
JVM Version: AdoptOpenJDK 11.0.9.1
OS: Windows 10 10.0 amd64
Workstation: DESKTOP-ITVHNK7
```

**Environment (please complete the following information):**
 - OS: Windows 10.0.19042
 - Java Version: openjdk 11.0.9.1 2020-11-04
 - Ghidra Version: 10.0 master (https://github.com/NationalSecurityAgency/ghidra/commit/296360eb3479e70eb734a2abf2eded06b84e3d69)
 - Ghidra Origin: locally built

**Comment by nsadeveloper789** [comment]
I cannot reproduce this. Please re-open if it's still an issue for you.
