### ISSUE TITLE
exception in bookmarks window

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#3066]
Was cleaning up the auto-analysis bookmarks.  As I fixed/deleted error bookmarks in the listing window I noticed the lines went blank instead of disappearing, when I clicked back in the bookmarks window I got:

```
Null address passed to ProgramLocation
java.lang.NullPointerException: Null address passed to ProgramLocation
	at ghidra.program.util.ProgramLocation.getCodeUnitAddress(ProgramLocation.java:413)
	at ghidra.program.util.ProgramLocation.<init>(ProgramLocation.java:146)
	at ghidra.program.util.CodeUnitLocation.<init>(CodeUnitLocation.java:78)
	at ghidra.program.util.AddressFieldLocation.<init>(AddressFieldLocation.java:59)
	at ghidra.util.table.field.AddressTableColumn.getProgramLocation(AddressTableColumn.java:50)
	at ghidra.util.table.field.AddressTableColumn.getProgramLocation(AddressTableColumn.java:1)
	at ghidra.util.table.MappedProgramLocationTableColumn.getProgramLocation(MappedProgramLocationTableColumn.java:54)
	at ghidra.util.table.AddressBasedTableModel.getProgramLocation(AddressBasedTableModel.java:73)
	at ghidra.util.table.GhidraTable.navigate(GhidraTable.java:200)
	at ghidra.util.table.GhidraTable.navigateOnCurrentSelection(GhidraTable.java:226)
	at ghidra.util.table.GhidraTable$SelectionListener.valueChanged(GhidraTable.java:298)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:219)
	at docking.widgets.table.RowObjectSelectionManager.superFireValueChanged(RowObjectSelectionManager.java:189)
	at docking.widgets.table.RowObjectSelectionManager.fireValueChanged(RowObjectSelectionManager.java:175)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:186)
	at java.desktop/javax.swing.DefaultListSelectionModel.setValueIsAdjusting(DefaultListSelectionModel.java:723)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.setValueIsAdjusting(BasicTableUI.java:972)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(BasicTableUI.java:1185)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2021-May-22
Ghidra Version: 10.0
Java Home: /usr/lib/jvm/java-11-openjdk-amd64
JVM Version: Ubuntu 11.0.11
OS: Linux 5.8.0-53-generic amd64
Workstation: glenlivet
```

**Comment by mumbel** [comment]
Don't know if its accurate or I did it correctly, but bisected from 9.2.4 and 9.2.1 tags and got 607c8ba8e43e8929725b60d89d43429adcacdfe0 both times.

**Comment by dev747368** [comment]
Can duplicate to some extent.
