### ISSUE TITLE
How to rebase binary after the binary has been loaded using API？

### ISSUE THREAD

**Issue by dark-lbp** [NationalSecurityAgency/ghidra#310]
I want to rebase an binary using API, but got follows errors.
```python
>>> target_block = currentProgram.memory.blocks[0]
>>> target_block
ram[00000000:00123456]
>>> currentProgram.memory.moveBlock(target_block, 0x10000, None)
Traceback (most recent call last):
  File "python", line 1, in <module>
TypeError: moveBlock(): 2nd arg can't be coerced to ghidra.program.model.address.Address
```
What is the correct method to rebase an binary?

**Comment by saruman9** [comment]
[`moveBlock`](http://ghidra.re/ghidra_docs/api/ghidra/program/model/mem/Memory.html#moveBlock(ghidra.program.model.mem.MemoryBlock,ghidra.program.model.address.Address,ghidra.util.task.TaskMonitor)) is right method, but type of second argument should be [`Address`](http://ghidra.re/ghidra_docs/api/ghidra/program/model/address/Address.html).

**Comment by dark-lbp** [comment]
@saruman9 Yes, but How to use Address type? Is there any python example?

**Comment by dark-lbp** [comment]
Tried [Address](http://ghidra.re/ghidra_docs/api/ghidra/program/model/address/Address.html) and got new error.
```python
>>> target_block = currentProgram.memory.blocks[0]
>>> target_address = target_block.getStart()
>>> target_address = target_address.add(0x1000)
>>> type(target_address)
<type 'ghidra.program.model.address.GenericAddress'>
>>> currentProgram.memory.moveBlock(target_block, target_address, None)
Traceback (most recent call last):
  File "python", line 1, in <module>
	at ghidra.program.database.module.TreeManager.moveAddressRange(TreeManager.java:500)
	at ghidra.program.database.ProgramDB.moveAddressRange(ProgramDB.java:2199)
	at ghidra.program.database.mem.MemoryMapDB.moveBlock(MemoryMapDB.java:680)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
java.lang.NullPointerException: java.lang.NullPointerException
```

**Comment by saruman9** [comment]
You should set `monitor` parameter. You can use:
1. [dummy monitor](http://ghidra.re/ghidra_docs/api/ghidra/util/task/TaskMonitor.html#DUMMY);
2. current monitor.

For first case:
```
from ghidra.util.task import TaskMonitor
currentProgram.getMemory().moveBlock(target_block, target_address, TaskMonitor.DUMMY)
```
For second case:
```
currentProgram.getMemory().moveBlock(target_block, target_address, monitor)
```

**Comment by dark-lbp** [comment]
@saruman9 Thanks! It's work.
