### ISSUE TITLE
Uncaught exception on connecting to gdb local debugger

### ISSUE THREAD

**Issue by aspieln3r** [NationalSecurityAgency/ghidra#3218]
**Describe the bug**
When I connect to gdb using IN-VM GNU gdb local debugger, I get an uncaught exception
**To Reproduce**
1. From debugger targets, create a new connection 
2. select IN-VM GNU gdb local debugger and make sure path is correct
3. get error

**Expected behavior**
connection works 

Error message: 
```
Could not initialize class agent.gdb.manager.impl.GdbManagerImpl
java.lang.NoClassDefFoundError: Could not initialize class agent.gdb.manager.impl.GdbManagerImpl
	at agent.gdb.manager.GdbManager.newInstance(GdbManager.java:107)
	at agent.gdb.model.impl.GdbModelImpl.<init>(GdbModelImpl.java:72)
	at agent.gdb.GdbInJvmDebuggerModelFactory.build(GdbInJvmDebuggerModelFactory.java:50)
	at ghidra.app.plugin.core.debug.service.model.DebuggerConnectDialog.connect(DebuggerConnectDialog.java:238)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1079)
	at java.desktop/java.awt.Component.show(Component.java:1720)
	at java.desktop/java.awt.Component.setVisible(Component.java:1667)
	at java.desktop/java.awt.Window.setVisible(Window.java:1032)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1014)
	at docking.DockingDialog.setVisible(DockingDialog.java:353)
	at docking.DockingWindowManager.lambda$doShowDialog$6(DockingWindowManager.java:1750)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at docking.DockingWindowManager.doShowDialog(DockingWindowManager.java:1754)
	at docking.DockingWindowManager.showDialog(DockingWindowManager.java:1703)
	at docking.AbstractDockingTool.showDialog(AbstractDockingTool.java:154)
	at ghidra.app.plugin.core.debug.service.model.DebuggerModelServicePlugin.doShowConnectDialog(DebuggerModelServicePlugin.java:686)
	at ghidra.app.plugin.core.debug.service.model.DebuggerModelServiceProxyPlugin.showConnectDialog(DebuggerModelServiceProxyPlugin.java:270)
	at ghidra.app.services.DebuggerModelService.showConnectDialog(DebuggerModelService.java:356)
	at ghidra.app.plugin.core.debug.gui.target.DebuggerTargetsProvider$ConnectAction.actionPerformed(DebuggerTargetsProvider.java:110)
	at docking.menu.ToolBarItemManager.lambda$actionPerformed$0(ToolBarItemManager.java:128)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2021-Jul-08 1512 EDT
Ghidra Version: 10.0.1
Java Home: /usr/lib/jvm/java-16-openjdk
JVM Version: N/A 16.0.1
OS: Linux 5.10.47-1-lts amd64
Workstation: s510u.localdomain
```

**Comment by d-millar** [comment]
Hmmm, we definitely need better error messages....  

@aspieln3r What version of gdb do you have?  In particular, is it 8 or better.  (Technically, by the by, we don't support jdk 16, but maybe @ryanmkurtz can weigh in on that - I don't think that's the issue.)  Also, are you using the default in the Connect window or have you modified them?

**Comment by d-millar** [comment]
@ryanmkurtz, @aspieln3r  Ah, OK - never mind!  (I need to pay more attention to where we are.)

**Comment by aspieln3r** [comment]
> @aspieln3r What version of gdb do you have? In particular, is it 8 or better? (Technically, by the by, we don't support jdk 16, but maybe @ryanmkurtz can weigh in on that - I don't think that's the issue.) Also, are you using the default in the Connect window or have you modified them?

```
>> gdb --version           
GNU gdb (GDB) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Actually, when I try to connect for the first time, the error message is this
```
java.io.FileNotFoundException: GDB.log (Permission denied)
java.lang.AssertionError: java.io.FileNotFoundException: GDB.log (Permission denied)
	at agent.gdb.manager.impl.GdbManagerImpl.<clinit>(GdbManagerImpl.java:83)
	at agent.gdb.manager.GdbManager.newInstance(GdbManager.java:107)
	at agent.gdb.model.impl.GdbModelImpl.<init>(GdbModelImpl.java:72)
	at agent.gdb.GdbInJvmDebuggerModelFactory.build(GdbInJvmDebuggerModelFactory.java:50)
	at ghidra.app.plugin.core.debug.service.model.DebuggerConnectDialog.connect(DebuggerConnectDialog.java:238)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1079)
	at java.desktop/java.awt.Component.show(Component.java:1720)
	at java.desktop/java.awt.Component.setVisible(Component.java:1667)
	at java.desktop/java.awt.Window.setVisible(Window.java:1032)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1014)
	at docking.DockingDialog.setVisible(DockingDialog.java:353)
	at docking.DockingWindowManager.lambda$doShowDialog$6(DockingWindowManager.java:1750)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at docking.DockingWindowManager.doShowDialog(DockingWindowManager.java:1754)
	at docking.DockingWindowManager.showDialog(DockingWindowManager.java:1703)
	at docking.AbstractDockingTool.showDialog(AbstractDockingTool.java:154)
	at ghidra.app.plugin.core.debug.service.model.DebuggerModelServicePlugin.doShowConnectDialog(DebuggerModelServicePlugin.java:686)
	at ghidra.app.plugin.core.debug.service.model.DebuggerModelServiceProxyPlugin.showConnectDialog(DebuggerModelServiceProxyPlugin.java:270)
	at ghidra.app.services.DebuggerModelService.showConnectDialog(DebuggerModelService.java:356)
	at ghidra.app.plugin.core.debug.gui.target.DebuggerTargetsProvider$ConnectAction.actionPerformed(DebuggerTargetsProvider.java:110)
	at docking.menu.ToolBarItemManager.lambda$actionPerformed$0(ToolBarItemManager.java:128)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.io.FileNotFoundException: GDB.log (Permission denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
	at agent.gdb.manager.impl.GdbManagerImpl.<clinit>(GdbManagerImpl.java:80)
	... 72 more

---------------------------------------------------
Build Date: 2021-Jul-08 1512 EDT
Ghidra Version: 10.0.1
Java Home: /usr/lib/jvm/java-16-openjdk
JVM Version: N/A 16.0.1
OS: Linux 5.10.47-1-lts amd64
Workstation: s510u.localdomain
```
If I try to connect one more time, the error message changes to the one in the problem description above.
Hope this will shed some light into the issue. I'm not sure where is this GDB.log file is located to check permissions
@d-millar

**Comment by d-millar** [comment]
OH, EXCELLENT - I think you've found the problem!  The debugger attempts to write that file in the root directory where ghidra is installed, i.e. ghidra_10.0.1_PUBLIC if you just downloaded and unzipped everything.  If you're running out of Eclipse, I think it's a few directories down - maybe ghidra/Ghidra/Framework/Utility.  Any chance you don't have write permission to either that directory or the file?  I get the same behavior if I change the permissions to 400 on GDB.log (including the odd change in message on second launch), so am hopeful!

**Comment by ryanmkurtz** [comment]
It would be nice if the logs would get written into the `~/.ghidra` directory (`Application.getUserSettingsDirectory()`)

**Comment by aspieln3r** [comment]
I installed ghidra from [aur](https://aur.archlinux.org/packages/ghidra-bin/) which installs ghidra to /opt/ghidra/ which is a read only directory for normal users. In linux, usually applications dont touch anything on their install locations and create files on appropriate locations on the user home. So I'm not sure if its a packaging issue of the distribution I use or something that needs to change in ghidra itself.

**Comment by d-millar** [comment]
Oh, wow, interesting - I had not even seen the aur site - but, per @ryanmkurtz's comment, definitely a screw-up on our part.  I think @nsadeveloper789 added that log to help diagnose some problems other folks were having without thinking about it too much and inadvertently created a new issue.  We definitely need to change this.

**Comment by aspieln3r** [comment]
Any workarounds to fix this issue temporarily? I tried creating a file with write permissions for my user at /opt/ghidra/Ghidra/Framework/Utility/GDB.log

**Comment by d-millar** [comment]
Are you working from source?  and/or running out of Eclipse?  I can give you the fixes if you are.  If not, the GDB.log will be written to the base install directory, I think /opt/ghidra in your case, so that would need to be writable.

**Comment by aspieln3r** [comment]
yesss creating GDB.log write permissions for my user at /opt/ghidra/ worked. I'm not using Eclipse.

**Comment by d-millar** [comment]
oh, sweet!  so are you hitting any other errors now?

**Comment by aspieln3r** [comment]
Nope. Setting breakpoints etc work in the debugger

**Comment by d-millar** [comment]
Excellent - well, I'm sure something will come up.  :)  Let us know when it does!

**Comment by micsthepick** [comment]
I get the same error on windows, however this time, it's trying to write the log to `C:\Windows\System32`

**Comment by d-millar** [comment]
@micsthepick Just to confirm, you were running gdb on Windows and it attempted to write to System32?  Where is Ghidra installed on your machine?

**Comment by micsthepick** [comment]
@d-millar yes, gdb on Windows, Ghidra is installed to `%USERPROFILE%\Applications`.

**Comment by micsthepick** [comment]
(There are no funny characters in my username, just alphanumeric characters)

**Comment by dev747368** [comment]
@micsthepick how are you running ghidra?  I suspect that clicking the ghidraRun.bat file via the gui file explorer might leave your current working directory as the location where cmd.exe is (c:\windows\system32).  Try opening a cmd prompt and cd'ing into the ghidra install directory and running ghidraRun.bat there.

**Comment by micsthepick** [comment]
That seems to have worked. There is a possibility that it's only when running the bat file from the start menu triggers the issue, as I've done that in the past.

**Comment by dev747368** [comment]
Check the properties of the shortcut / launch icon in your start menu and see if the system32 directory is manually specified there, and then tweak it.

**Comment by micsthepick** [comment]
there are no properties, it's an indexed directory on my machine.
