### ISSUE TITLE
Invalid length 0 for DWARF Compilation Unit at 0x0 with MIPSPro binaries

### ISSUE THREAD

**Issue by jrmuizel** [NationalSecurityAgency/ghidra#3223]
**Describe the bug**
I get the following error when auto-analyzing the attached binary from MIPSPro 7.4.4m, -64 
[test2.o.gz](https://github.com/NationalSecurityAgency/ghidra/files/6825786/test2.o.gz)
```
Error during DWARFAnalyzer import
Invalid length 0 for DWARF Compilation Unit at 0x0
ghidra.app.util.bin.format.dwarf4.DWARFException: Invalid length 0 for DWARF Compilation Unit at 0x0
	at ghidra.app.util.bin.format.dwarf4.DWARFCompilationUnit.readCompilationUnit(DWARFCompilationUnit.java:146)
	at ghidra.app.util.bin.format.dwarf4.next.DWARFProgram.bootstrapCompilationUnits(DWARFProgram.java:515)
	at ghidra.app.util.bin.format.dwarf4.next.DWARFProgram.<init>(DWARFProgram.java:214)
	at ghidra.app.plugin.core.analysis.DWARFAnalyzer.added(DWARFAnalyzer.java:133)
	at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:186)
	at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:688)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:788)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:667)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:632)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

1. Auto-analyze attached binary

**Expected behavior**
No dwarf errors. `dwarf-dump` is able to dump this file without issue.

**Environment (please complete the following information):**
 - OS: macOS
 - Ghidra Version: 10.0 Beta

**Comment by dev747368** [comment]
While dwarfdump seems to handle it okay, my go-to tool to display dwarf info, readelf, is not happy with that binary.

Do you have any info about what the toolchain is doing different w.r.t DWARF?

**Comment by jrmuizel** [comment]
I don't. The toolchain is old so it could be that the dwarf data doesn't follow the spec. Interestingly 32bit binaries with the same toolchain seem fine.

**Comment by dev747368** [comment]
Digging deeper into dwarfdump, that example binary is DWARF v2, which we don't handle.

dwarfdump -ivv test2.o

**Comment by jrmuizel** [comment]
Here's the 32bit version which does analyze without errors:
[test.o.gz](https://github.com/NationalSecurityAgency/ghidra/files/6826234/test.o.gz)

**Comment by dev747368** [comment]
Looking at the raw bytes, the 64bit one is using a 64bit long for the initial length field, which is wrong.  The dwarf spec lays out a scheme for specifying a 64bit value for the length, and its backwards compatible with 32 bit by using a 0xFFFFFFFF length value as a flag and then putting the real 64bit value following that.

**Comment by jrmuizel** [comment]
Makes sense. It looks like libdwarf has special casing to handle the IRIX 64 bit stuff:
https://github.com/landfound/libdwarf/blob/0fed4afaa74161700df7392f04600745dddd3ad8/libdwarf/dwarf_util.h#L200

**Comment by dev747368** [comment]
Good find.  The special-casing of this situation doesn't seem very fragile, so maybe I'll incorporate that.
