### ISSUE TITLE
Attempting to launch GDB session fails

### ISSUE THREAD

**Issue by jtuu** [NationalSecurityAgency/ghidra#3231]
1. Open a file with the Ghidra debugger
2. Click the debug button
3. It fails immediately with an error

**The error:**
```
An unexpected error occurred while processing the command: Debug grep in GDB locally IN-VM
Error while starting GDB
ghidra.dbg.error.DebuggerModelTerminatingException: Error while starting GDB
	at agent.gdb.model.impl.GdbModelImpl.startGDB(GdbModelImpl.java:141)
	at agent.gdb.GdbInJvmDebuggerModelFactory.build(GdbInJvmDebuggerModelFactory.java:51)
	at ghidra.app.plugin.core.debug.service.model.launch.AbstractDebuggerProgramLaunchOffer.connect(AbstractDebuggerProgramLaunchOffer.java:260)
	at ghidra.app.plugin.core.debug.service.model.launch.AbstractDebuggerProgramLaunchOffer.launchProgram(AbstractDebuggerProgramLaunchOffer.java:270)
	at ghidra.app.plugin.core.debug.service.model.DebuggerModelServiceProxyPlugin.lambda$debugProgram$6(DebuggerModelServiceProxyPlugin.java:342)
	at ghidra.app.plugin.core.debug.utils.BackgroundUtils$AsyncBackgroundCommand.applyTo(BackgroundUtils.java:53)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:311)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: GDB terminated before first prompt
	at agent.gdb.manager.impl.GdbManagerImpl.start(GdbManagerImpl.java:580)
	at agent.gdb.model.impl.GdbModelImpl.startGDB(GdbModelImpl.java:137)
	... 8 more
```

**Output of gdb --version:**
```
~ $ /usr/bin/gdb --version
GNU gdb (GDB) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Environment**
 - OS: Linux 5.12.15-arch1-1 amd64
 - Java Version: 11.0.11
 - Ghidra Version: 10.0.1
 - Ghidra Origin: AUR ghidra-bin

**Comment by d-millar** [comment]
Duplicates #3218 - installations from “aur” repository install in read-only directories, but the debugger attempts to write GDB.log in install base dir.  Short-term fix: change the file permissions;  long-term fix:  10.0.2.

**Comment by jtuu** [comment]
Actually I just figured out what is causing this and it is not a duplicate of #3218. I found this in Ghidra's stdout:
`Exception in thread "main" java.lang.UnsupportedClassVersionError: agent/gdb/pty/linux/LinuxPtySessionLeader has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

It seems that it is using my machine's default Java installation which is version 8 even though I have JAVA_HOME_OVERRIDE set to Java 11 and it displays the Java version as 11 when I check the "About ghidra" window.

**Comment by d-millar** [comment]
Wow, ok - thanks for figuring that out.  You may have solved a similar bug another user is having.   I owe you one!
