### ISSUE TITLE
Ghidra 10.0.1 HeadlessScript -scriptPath not working

### ISSUE THREAD

**Issue by totoR13** [NationalSecurityAgency/ghidra#3272]
**Describe the bug**
When I run the command:
```
./analyzeHeadless "/tmp/" "tmpProject" -scriptPath "<path_to_script>" -import "<target_file>" -postScript "Test.java" "<input_of_test_script>" -readOnly -deleteProject
```
I continuously receive the following error:
```
ERROR REPORT SCRIPT ERROR: TestHeadless.java :  (HeadlessAnalyzer) java.lang.ClassNotFoundException: 
	at ghidra.app.script.JavaScriptProvider.getScriptInstance(JavaScriptProvider.java:105)
	at ghidra.app.util.headless.HeadlessAnalyzer.runScriptsList(HeadlessAnalyzer.java:895)
	at ghidra.app.util.headless.HeadlessAnalyzer.analyzeProgram(HeadlessAnalyzer.java:1057)
	at ghidra.app.util.headless.HeadlessAnalyzer.processFileWithImport(HeadlessAnalyzer.java:1550)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1688)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1753)
	at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:445)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:121)
	at ghidra.GhidraLauncher.main(GhidraLauncher.java:82)
Caused by: java.lang.NullPointerException
	at ghidra.app.script.JavaScriptProvider.loadClass(JavaScriptProvider.java:127)
	at ghidra.app.script.JavaScriptProvider.getScriptInstance(JavaScriptProvider.java:85)
	... 8 more
```
 
I receive the above error indipendently the content of Test.java script.
For example, I receive the error with the following Test class:
```
public class Test extends HeadlessScript {
    public void run() throws Exception {
        if (this.analysisTimeoutOccurred()) {
            System.out.println("Analysis timeout!");
            return;
        }

        System.out.println("Test OK");
    }
}
```

**To Reproduce**
1. Go to '$GHIDRA_HOME/support'
2. Run './analyzeHeadless "/tmp/" "tmpProject" -scriptPath "<path_to_script>" -import "<target_file>" -postScript "Test.java" "<input_of_test_script>" -readOnly -deleteProject'
3. See error

**Expected behavior**
The script runs without exceptions

**Environment (please complete the following information):**
 - Ubuntu 20.04
 - Java Version: openjdk 11.0.11 2021-04-20
 - Ghidra Version: 10.0.1
 - Ghidra Origin: (Github webpages)[https://github.com/NationalSecurityAgency/ghidra/releases] 

Thank you in advace!

**Comment by totoR13** [comment]
I close this issue because I fixed it leveraging past issues (e.g., (5)[https://github.com/Martyx00/ghinja/issues/5], (2562)[https://github.com/NationalSecurityAgency/ghidra/issues/2562])
