### ISSUE TITLE
DWARF DW_FORM_ref_sig8 not supported

### ISSUE THREAD

**Issue by bdemick** [NationalSecurityAgency/ghidra#3283]
**Describe the bug**
DWARF analysis does not handle `DW_FORM_ref_sig8` attribute. Getting the error `Analysis Task: DWARF - One Time - DW_FORM_ref_sig8 is currently not implemented`. This appears to block the DWARF analysis from completing.

**To Reproduce**
Initial DWARF analysis failed, Ghidra suggested setting the `Preload all DIEs` option. Set this option and re-ran, now getting the error described above. I unfortunately don't have a sample I can share at the moment.

**Expected behavior**
DWARF analysis completes, able to view DWARF info in program trees.

**Screenshots**
N/A

**Attachments**
```
DW_FORM_ref_sig8 is currently not implemented
java.lang.UnsupportedOperationException: DW_FORM_ref_sig8 is currently not implemented
	at ghidra.app.util.bin.format.dwarf4.attribs.DWARFAttributeFactory.read(DWARFAttributeFactory.java:155)
	at ghidra.app.util.bin.format.dwarf4.DebugInfoEntry.read(DebugInfoEntry.java:82)
	at ghidra.app.util.bin.format.dwarf4.DWARFCompilationUnit.readDIEs(DWARFCompilationUnit.java:335)
	at ghidra.app.util.bin.format.dwarf4.next.DWARFProgram.checkPreconditions(DWARFProgram.java:895)
	at ghidra.app.util.bin.format.dwarf4.next.DWARFProgram.<init>(DWARFProgram.java:215)
	at ghidra.app.plugin.core.analysis.DWARFAnalyzer.added(DWARFAnalyzer.java:133)
	at ghidra.app.plugin.core.analysis.OneShotAnalysisCommand.applyTo(OneShotAnalysisCommand.java:48)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:688)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:788)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:667)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:632)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:834)

---------------------------------------------------
```

**Environment:**
- Build Date: 2021-Jul-08 1512 EDT
- Ghidra Version: 10.0.1
- Java Home: /Users/user/work/jdk/jdk-11.0.7+10/Contents/Home
- JVM Version: AdoptOpenJDK 11.0.7
- OS: Mac OS X 11.2.3 x86_64 (Interestingly, Ghidra reports OS version as 10.16)
- Ghidra Origin: official ghidra-sre.org distro

**Additional context**
N/A

**Comment by dev747368** [comment]
There may be a larger issue for this binary if it is using other DWARF features that Ghidra doesn't implement yet.  DW_FORM_ref_sig8 is typically used when the DWARF info is split or compressed. 

What toolchain & version produced the binary?  

If you run "readelf -wi your_binary" you should be able to dump the raw DWARF info into a readable format.  What does the DW_AT_producer value say?  It will typically include the name of the toolchain and the compile flags.

**Comment by bdemick** [comment]
Looks to be `IAR V8.30.1.114`. Ended up using `pyelftools` to grab some high-level info for now, but would definitely be awesome for it to parse out-of-the-gate.

**Comment by dshilobod** [comment]
This issue still seems to be present in 10.1.5 and the latest 10.3 DEV build I tested this week.  

Specifically, the analysis portion fails at DWARF portion of my 32-bit ARM ELF file with the error....

_"Skipping DWARF import because a precondition was not met:
Found cross-compilation unit references between DIE records, but 'preload' is not turned on
Manually re-run the DWARF analyzer after adjusting the options or start it via Dwarf_ExtractorScript"_

Going into the DWARF options and setting the preload option, then re-running DWARF from the One Shot menu fails with the same error originally reported last year.... 

_"DW_FORM_ref_sig8 is currently not implemented
java.lang.UnsupportedOperationException: DW_FORM_ref_sig8 is currently not implemented"_

**Comment by dev747368** [comment]
Support for handling the DW_FORM_ref_sig8 attribute will be part of a future DWARF5 implementation.

I'm going to reference issue #4088 as that will be the canonical issue for DWARF5 stuff.
