### ISSUE TITLE
Loading PDB failed with `java.lang.IllegalArgumentException`

### ISSUE THREAD

**Issue by 0x5ECF4ULT** [NationalSecurityAgency/ghidra#3289]
**Describe the bug**
Ghidra is unable to load symbols from Microsoft's Symbol Server.

**To Reproduce**
1. Click on "File"
2. Click on "Load PDB File"
3. Click on "Config"
4. Add Microsoft's Symbol Server
5. Click on "OK" to go to the previous screen
6. Click on "Advanced"
7. Click on "Search All"

**Expected behavior**
I expect Ghidra to find symbols for the loaded PE executable.

**Screenshots**
![Stacktrace screenshot](https://user-images.githubusercontent.com/17967646/127743409-ba12db96-875a-41de-9a23-13666656e58f.png)

**Attachments**
Stacktrace
```
Illegal character in path at index 0: <unknown>/000000000/<unknown>
java.lang.IllegalArgumentException: Illegal character in path at index 0: <unknown>/000000000/<unknown>
	at java.base/java.net.URI.create(URI.java:906)
	at java.base/java.net.URI.resolve(URI.java:1089)
	at pdb.symbolserver.HttpSymbolServer.request(HttpSymbolServer.java:83)
	at pdb.symbolserver.HttpSymbolServer.exists(HttpSymbolServer.java:91)
	at pdb.symbolserver.AbstractSymbolServer.getFirstExists(AbstractSymbolServer.java:111)
	at pdb.symbolserver.AbstractSymbolServer.find(AbstractSymbolServer.java:48)
	at pdb.symbolserver.SymbolServerService.find(SymbolServerService.java:156)
	at pdb.symbolserver.ui.LoadPdbDialog.lambda$searchForPdbs$2(LoadPdbDialog.java:298)
	at pdb.symbolserver.ui.LoadPdbDialog$2.run(LoadPdbDialog.java:813)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at docking.TaskScheduler.run(TaskScheduler.java:73)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.net.URISyntaxException: Illegal character in path at index 0: <unknown>/000000000/<unknown>
	at java.base/java.net.URI$Parser.fail(URI.java:2938)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3109)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3191)
	at java.base/java.net.URI$Parser.parse(URI.java:3150)
	at java.base/java.net.URI.<init>(URI.java:623)
	at java.base/java.net.URI.create(URI.java:904)
	... 11 more
```

**Environment (please complete the following information):**
 - OS: Ubuntu 21.04 (Linux 5.11.0-25-generic amd64)
 - Java Version: 14.0.2
 - Ghidra Version: 10.0.1
 - Ghidra Origin: ghidra-sre.org

**Additional context**
I suspect that Microsoft changed things running under the hood.

**Comment by dev747368** [comment]
I suspect that string "\<unknown\>" used to indicate a binary with missing or bad PE debug info is leaking into the search:

https://github.com/NationalSecurityAgency/ghidra/blob/df50264a372b0fa39a244ed703c66cf30359ab08/Ghidra/Features/PDB/src/main/java/pdb/symbolserver/SymbolFileInfo.java#L66

So, you probably aren't missing anything with this binary, but could be a bug with the pdb searching.
