### ISSUE TITLE
"Not a valid Address on instruction at" error referring to indirect jump pcode with fixed address

### ISSUE THREAD

**Issue by hwrobel** [NationalSecurityAgency/ghidra#3298]
**Describe the bug**
Doing a right click on an equate in a function context fails after a multi second pause with a "Not a valid Address on instruction at" if the function ends with pcode implementing an indirect jump to a different function using a well known constant address.
The normal right click context menu starting with "Bookmark..." does not appear.

Please see the first screenshot.
Note how the instruction at 8b6c loads the 16b register "X" with a constant value (2nd screenshot)
Then an indirect jump is done in pcode at 8b6f based on the now well known X register
ghidra complains about the pcode at 8b6f when right clicking on any equate in the same function. In this case, I right clicked on the equate at 8b68

Note also that the LDX/JMP sequence of 8b6c is repeated in identical fashion at 8b71. The JMP at 8b74 however does not decode the expected "X=>Main_Part1" after the LDX disassemble, but only "X".

Function attributes like NoReturn or calling convention don't seem to affect this issue.

Is this an obvious user error on my side in the pcode use or slaspec definition, or is there more to this? Thank you!

**To Reproduce**
Not sure how to generate an easily reproducible case outside my environment.
The pcode is generated based on a home grown M6802 slaspec (Motorola M6800 family) file in a complex project. I could share the 6802 slaspec if that helps but not the project itself.

**Expected behavior**

I am expecting the normal right mouse click context menu to pop up right away when doing a right clock on an equate in such a function.

**Screenshots**
![image](https://user-images.githubusercontent.com/88279392/127773991-152e54b3-acd3-451e-b4b8-47e303944b8b.png)
![image](https://user-images.githubusercontent.com/88279392/127774224-b26d20b6-7dfb-4395-9a0f-a8e3d98edda7.png)
![image](https://user-images.githubusercontent.com/88279392/127774239-6a321955-5547-406d-84c2-2537bd51bd06.png)

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
Ghidra Version: 10.0.1
Java Home: C:\Program Files\Amazon Corretto\jdk11.0.8_10
JVM Version: Amazon.com Inc. 11.0.8
OS: Windows 10 10.0 amd64
official ghidra-sre.org distro, only modification is copying in the home grown 6802 processor directory

**Additional context**

These are the exception details shown:
----
Not a valid Address on instruction at 8b6f
ghidra.util.exception.AssertException: Not a valid Address on instruction at 8b6f
	at ghidra.program.util.SymbolicPropogator.applyPcode(SymbolicPropogator.java:988)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:496)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:393)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:191)
	at ghidra.app.cmd.function.CallDepthChangeInfo.followFlows(CallDepthChangeInfo.java:733)
	at ghidra.app.cmd.function.CallDepthChangeInfo.initialize(CallDepthChangeInfo.java:170)
	at ghidra.app.cmd.function.CallDepthChangeInfo.<init>(CallDepthChangeInfo.java:91)
	at ghidra.app.plugin.core.references.CreateDefaultReferenceAction.isEnabledForContext(CreateDefaultReferenceAction.java:151)
	at ghidra.app.context.ListingContextAction.isEnabledForContext(ListingContextAction.java:37)
	at docking.PopupActionManager.populatePopupMenuActions(PopupActionManager.java:143)
	at docking.PopupActionManager.createPopupMenu(PopupActionManager.java:104)
	at docking.PopupActionManager.popupMenu(PopupActionManager.java:84)
	at docking.ActionToGuiMapper.showPopupMenu(ActionToGuiMapper.java:137)
	at docking.DockableComponent.showContextMenu(DockableComponent.java:173)
	at docking.DockableComponent$1.mouseReleased(DockableComponent.java:75)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2021-Jul-08 1512 EDT
Ghidra Version: 10.0.1
Java Home: C:\Program Files\Amazon Corretto\jdk11.0.8_10
JVM Version: Amazon.com Inc. 11.0.8
OS: Windows 10 10.0 amd64
----

**Comment by ghidra1** [comment]
The BRANCH pcodeop on 8b6f looks like it should be an indirect branch instead (BRANCHIND).  It is unexpected to have a BRANCH refer to a unique/temp variable.   It should only refer to a constant or memory address.   It would appear to be either a Sleigh compile or language issue.  If you wrote the processor spec yourself, could you please attach.  I suspect your sub-constructor is returning a unique/local while the instruction is using an immediate branch instead of an indirect branch.

**Comment by hwrobel** [comment]
[6802.zip](https://github.com/NationalSecurityAgency/ghidra/files/6943363/6802.zip)
Hi, attached is my 6802 spec as I use it currently. I had shuffled the slaspec content back and forth a bit, but really couldn't effect a change.
Even if not using direct branch with the prior load is inefficient, shouldn't the existing pcode work after all?

**Comment by ghidra1** [comment]
Your IMM8X pcode is not suitable for a direct jump and must use an indirect/computed jump.  In addition, since it is a unique/local varnode it will force a memory load when exported which I believe was also unintended.
```
IMM8X: imm8,X   is X; imm8    { local tmp:2 = (imm8 + X); export *:2 tmp; }
IMM16: imm16   is imm16   	{ export *:2 imm16; }
```
Suggested changes (less renaming which is also suggested):
```
IMM8X: imm8,X   is X; imm8    { local tmp:2 = (imm8 + X); export tmp; }

:JMP IMM8X  is op=0x6e ; IMM8X
{
  goto [IMM8X];
}
```
Suggestions: I would rename your IMM8X since it is not an immediate export - although neither is the IMM16 which exports a sized memory location.  Ideally, the subconstructor naming reflects the nature of the export when applicable.

**Comment by hwrobel** [comment]
Thank you. Your comments provided the solution. The sleigh docs appear to be a bit terse on this topic.
