### ISSUE TITLE
Jython Memory Overflow Hangs Ghidra

### ISSUE THREAD

**Issue by TheMatt2** [NationalSecurityAgency/ghidra#3326]
**Describe the bug**
If a Jython script, or interactive prompt, were to allocate to much memory, and therefore crash, Ghidra hangs as a well.

When the Jython crash occurs, Ghidra goes to 100% cpu usage on all threads, and stays there for about 20 seconds. During this time, Ghidra is completely unresponsive.

After 20 seconds, the cpu usage goes back to ~0%, but Ghidra remains hung, and the java process must be killed manually.

The crash occurs after ~2.7GB of data are allocated.
This can easily lead to information loss, as nothing can be saved when Ghidra is hung. 

**To Reproduce**
1. Open a file to analyze
2. Open the Python Interpreter
3. Allocate a lot of memory in Python
For example:

    x = []
    while 1: x.append(0xdeadbeef)

4. Wait a few seconds
5. Observe Ghidra freezes, and remains unresponsive.

**Expected behavior**
Preferably, Ghidra detects the crash of the Python Interpreter, and can reset it.

Alternatively, Ghidra should detect the error condition, and exist by itself. Hopefully a crash save can be generated.

**Environment:**
 - OS: Ubuntu 20.04.2 LTS
 - Java Version: 11.0.11
 - Ghidra Version: 10.0.1 PUBLIC 2021-Jul-8 1512 EDT
 - Ghidra Origin: Github releases page

**Additional context**
While the sample uses an infinite loop to trigger the crash. This crashing behavior has been observed using scripts that allocate a finite amount of memory that exceeds 3GB.

**Comment by TheMatt2** [comment]
Sort of disagree with this being a "Performance" issue.

This issue can lead to the _loss of data_ and requires manually killing the Ghidra process.
Forgive me if I was unclear, this is not a "hang" Ghidra will recover from, but indeed a soft crash.

The concept that a script can not use more than 2GB of ram is not the problem here.

**Comment by astrelsky** [comment]
Couldn't reproduce. After about 2 minutes or so I got the following. I suspect that even if it can occur it is a Jython issue and not a Ghidra issue.
```
Python Interpreter for Ghidra
Based on Jython version 2.7.2 (v2.7.2:925a3cc3b49d, Mar 21 2020, 10:03:58)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)]
Press 'F1' for usage instructions
>>> x = []
>>> while True:
...  monitor.checkCanceled()
...  x.append(0xdeadbeef)
... 
... 
__main__:3: RuntimeWarning: PyTableCode.call caught a Throwable that is not an Exception:
java.lang.OutOfMemoryError: Java heap space
Jython internals might be in a bad state now that can cause deadlocks later on.
See http://bugs.jython.org/issue2536 for details.
Traceback (most recent call last):
  File "python", line 3, in <module>
java.lang.OutOfMemoryError: Java heap space

	at java.base/java.util.Arrays.copyOf(Arrays.java:3480)

	at java.base/java.util.ArrayList.grow(ArrayList.java:237)

	at java.base/java.util.ArrayList.grow(ArrayList.java:244)

	at java.base/java.util.ArrayList.add(ArrayList.java:454)

	at java.base/java.util.ArrayList.add(ArrayList.java:467)

	at org.python.core.PyList.pyadd(PyList.java:1188)

	at org.python.core.PyList.list_append(PyList.java:535)

	at org.python.core.PyList$list_append_exposer.__call__(Unknown Source)

	at org.python.core.PyObject.__call__(PyObject.java:465)

	at org.python.pycode._pyx7.f$0(python:1)

	at org.python.pycode._pyx7.call_function(python)

	at org.python.core.PyTableCode.call(PyTableCode.java:173)

	at org.python.core.PyCode.call(PyCode.java:18)

	at org.python.core.Py.runCode(Py.java:1687)

	at org.python.core.Py.exec(Py.java:1731)

	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:277)

	at org.python.util.InteractiveInterpreter.runcode(InteractiveInterpreter.java:130)

	at org.python.util.InteractiveInterpreter.runsource(InteractiveInterpreter.java:115)

	at org.python.util.InteractiveInterpreter.runsource(InteractiveInterpreter.java:62)

	at ghidra.python.GhidraPythonInterpreter.push(GhidraPythonInterpreter.java:181)

	at ghidra.python.PythonPluginExecutionThread.run(PythonPluginExecutionThread.java:80)

java.lang.OutOfMemoryError: java.lang.OutOfMemoryError: Java heap space
```

**Comment by TheMatt2** [comment]
I'm surprised the problem is not reproduce able. It happens each and every time.

On closer examination, it seems this definitely seems strange.

More Details of my setup:
VM OS: Ubuntu 20.04.2 LTS
Host OS: Win10
Java Version: 11.0.11
Ghidra Version: 10.0.1 PUBLIC 2021-Jul-8 1512 EDT
Ghidra Origin: Github releases page
Virtual Machine: VirtualBox 6.1.22 (Qt5.6.2)

The virtual machine has 6 threads, and 8GB of memory.

Java Heap size is the default, which I believe to be 2GB.

When I run the code, here is what I see

![ghidra_soft_crash](https://user-images.githubusercontent.com/22862051/129201689-2373f89b-80df-49b6-9e41-335c9cc2c479.PNG)

CPU usage goes to 90%. Note: Since this is a hex core, a single threaded Python script should only show up as 20%. From this point on, Ghidra is completely unresponsive.

After about two minutes, the CPU usage drops to 0%.

![ghidra_soft_crash2](https://user-images.githubusercontent.com/22862051/129201937-1bd9eb30-63c2-4e4e-908d-48f5fac71488.PNG)

Having triggered this a number of times now: I must admit _exactly once_, after I waited two minutes, I clicked on a section under Program Trees. The section showed up blue, like you would expect from Ghidra. _Then_, CPU usage cranked back to 90% and Ghidra was no longer responsive to anything.

**Comment by TheMatt2** [comment]
While Jython may be a likely suspect, I'm not sure how it would be causing cpu usage above a single core. I would be guessing there is a deadlock condition in Ghidra causing this.

**Comment by TheMatt2** [comment]
Tested in Ghidra 10.0.2. Behavior is the same, except now there is an error message, instead of it being blank.

![ghidra_soft_crash3](https://user-images.githubusercontent.com/22862051/129204879-48f30054-6ee1-4c88-81e2-fb33cac45703.PNG)

**Comment by dragonmacher** [comment]
> Except, have tried this a few time, and on one attempt on trying to import a file after having triggered this overflow in Python, I got the cpu usage to go back to 0%.

Just to be clear, once this exception happens, Ghidra is unusable and will have to be restarted.

**Comment by dragonmacher** [comment]
Once an `OutOfMemoryError` happens we cannot be certain of the application state.   For this reason we do not make any attempts to recover from this error, which leaves Ghidra unresponsive.

Ghidra's architecture, which runs client code (scripts, extensions, plugins) in the same VM as the application, does not easily allow for us to stop these types of errors.    Thus, without a major architectural change, we will be unable to fix this issue.  On the other hand, if Ghidra code is found to cause an `OutOfMemoryError`, then this is something we will attempt to fix.

**Comment by TheMatt2** [comment]
Is it possible to make Ghidra exit by itself in this case?

That's what I would want for expected behavior.

**Comment by TheMatt2** [comment]
#884 May be a report of this same behavior

**Comment by dragonmacher** [comment]
> Is it possible to make Ghidra exit by itself in this case?

It is certainly *possible*.  However, considering that we ultimately cannot know the state of the application, it would be potentially dangerous to attempt a normal shutdown.

**Comment by astrelsky** [comment]
> > Is it possible to make Ghidra exit by itself in this case?
> 
> It is certainly _possible_. However, considering that we ultimately cannot know the state of the application, it would be potentially dangerous to attempt a normal shutdown.

What about notifying the user that they need to kill the jvm?
