### ISSUE TITLE
dsPIC33E analyze not working

### ISSUE THREAD

**Issue by avadana** [NationalSecurityAgency/ghidra#3386]
**Describe the bug**
```
java.lang.reflect.InvocationTargetException
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1713)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyToWithTransaction(AutoAnalysisManager.java:1655)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.scheduleWorker(AutoAnalysisManager.java:1364)
	at ghidra.app.cmd.formats.CoffBinaryAnalysisCommand.applyTo(CoffBinaryAnalysisCommand.java:90)
	at ghidra.app.analyzers.AbstractBinaryFormatAnalyzer.added(AbstractBinaryFormatAnalyzer.java:39)
	at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:186)
	at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:688)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:788)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:667)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:632)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Unable to read bytes at rom:100770
	at ghidra.app.util.bin.MemoryByteProvider.readBytes(MemoryByteProvider.java:129)
	at ghidra.app.util.bin.BinaryReader.readInt(BinaryReader.java:682)
	at ghidra.app.util.bin.BinaryReader.readNextInt(BinaryReader.java:316)
	at ghidra.app.util.bin.format.coff.CoffLineNumber.<init>(CoffLineNumber.java:32)
	at ghidra.app.util.bin.format.coff.CoffSectionHeader.parseLineNumbers(CoffSectionHeader.java:280)
	at ghidra.app.util.bin.format.coff.CoffSectionHeader.parse(CoffSectionHeader.java:267)
	at ghidra.app.util.bin.format.coff.CoffFileHeader.parse(CoffFileHeader.java:207)
	at ghidra.app.cmd.formats.CoffBinaryAnalysisCommand.analysisWorkerCallback(CoffBinaryAnalysisCommand.java:71)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1707)
	... 14 more
```
**Environment (please complete the following information):**
 - OS: [e.g. Linux, Windows]
 - Java Version: [e.g. 11.0.12]
 - Ghidra Version: [e.g. 10.0.2]
 - Ghidra Origin: [e.g. official ghidra-sre.org distro, third party distro, locally built]

**Comment by ryanmkurtz** [comment]
Can you share your binary?

**Comment by avadana** [comment]
https://drive.google.com/file/d/1k-GKBpfyu6YY45ROZJUC-VbuOZMiG6PA/view?usp=sharing

**Comment by ryanmkurtz** [comment]
It looks like this is just an unfortunate false positive match as a COFF file.  You can just disable the `COFF Header Annotation` analyzer to avoid the issue.

**Comment by avadana** [comment]
> Can you share your binary?

**Comment by avadana** [comment]
> It looks like this is just an unfortunate false positive match as a COFF file. You can just disable the `COFF Header Annotation` analyzer to avoid the issue.

But nothing shown up

**Comment by ryanmkurtz** [comment]
For this .hex file, you need to manually tell it where to start disassembling.  Try selecting address `rom:000200` and press `d` on your keyboard.

**Comment by avadana** [comment]
Thanks

**Comment by ryanmkurtz** [comment]
I am getting the same error on a PIC ELF file.
