### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter

### ISSUE THREAD

**Issue by marcomafcorp** [NationalSecurityAgency/ghidra#339]
**Describe the bug**
I'm Importing a python file via the interpreter and I continue to get the error below under expected behavior
>>>import mypythonfile
#whats in the file
GUIDs = {
'Some_GUID':[0xeb9d2d30, 0x2d88, 0x11d3, 0x9a, 0x16, 0x0, 0x90, 0x27, 0x3f, 0xc1, 0x4d],
'Some_GUID':[0x2ea9743a, 0x23d9, 0x425e, 0x87, 0x2c, 0xf6, 0x15, 0xaa, 0x19, 0x57, 0x88],
}
**To Reproduce**
1. map the folder in the scripts manager, open python interpreter in ghidra
2. create mypythonfile.py {Copy the lines below #whats in the file}
3. go to the interpreter: import mypythonfile

**Expected behavior**
Traceback (most recent call last):
  File "python", line 1, in <module>
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at org.python.compiler.Module.serializePyBytecode(Module.java:867)
	at org.python.compiler.Module.compile(Module.java:989)
	at org.python.core.imp.compileSource(imp.java:370)
	at org.python.core.imp.createFromSource(imp.java:388)
	at org.python.core.imp.loadFromSource(imp.java:667)
	at org.python.core.imp.find_module(imp.java:551)
	at org.python.core.imp.import_next(imp.java:838)
	at org.python.core.imp.import_module_level(imp.java:957)
	at org.python.core.imp.importName(imp.java:1057)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:450)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1076)
	at org.python.pycode._pyx14.f$0(python:1)
	at org.python.pycode._pyx14.call_function(python)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.Py.exec(Py.java:1658)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:276)
	at org.python.util.InteractiveInterpreter.runcode(InteractiveInterpreter.java:131)
	at org.python.util.InteractiveInterpreter.runsource(InteractiveInterpreter.java:116)
	at org.python.util.InteractiveInterpreter.runsource(InteractiveInterpreter.java:62)
	at ghidra.python.GhidraPythonInterpreter.push(GhidraPythonInterpreter.java:181)
	at ghidra.python.PythonPluginExecutionThread.run(PythonPluginExecutionThread.java:80)
java.lang.NoClassDefFoundError: java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter

**Screenshots**
![image](https://user-images.githubusercontent.com/4383090/55576298-03070c00-56df-11e9-8816-ce3cc8e3c881.png)

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: [e.g. windows 7]
 - Java Version: [e.g. 11.0]
 - Ghidra Version: [e.g. 9.0]

**Comment by ryanmkurtz** [comment]
I wasn't able to reproduce the problem.  What version of Java is Ghidra using?

**Comment by marcomafcorp** [comment]
jdk-11.0.2

![Uploading Screen Shot 2019-04-04 at 2.19.12 PM.png…]()

**Comment by rjzak** [comment]
Java 11 removed `javax.xml.bind`. See https://stackoverflow.com/questions/52502189/java-11-package-javax-xml-bind-does-not-exist. Seems the build needs to be modified.

**Comment by marcomafcorp** [comment]
Yeah I read that already, are you recommending to modify the build... Yikes, I guess I'm on my own on this one. Any tips or guidance? I'm not a java dev or have ever wrote a single line of Java code :(

**Comment by ryanmkurtz** [comment]
Is this in our 9.0.2 build or is it in your own build?

**Comment by marcomafcorp** [comment]
This is the 9.0.1

**Comment by ryanmkurtz** [comment]
> jdk-11.0.2
> <img alt="Screen Shot 2019-04-04 at 2 19 12 PM" width="651" src="https://user-images.githubusercontent.com/4383090/55578798-be7e6f00-56e4-11e9-9b7e-b6702c8e0d57.png">

The version of java on the path is not necessarily the version of java Ghidra launched with.  Ghidra should only launch with java 11 or later, yet you are showing java 8 on the path.  If you look at ~/.ghidra/.ghidra-9.0.1/java_home.save, you will see what version of java Ghidra launched with.  Can you include the output of that version's `java -version `command?

**Comment by marcomafcorp** [comment]
In that file I'm using the correct file ~/.ghidra/.ghidra-9.0.1/java_home.save. it has C:\Program Files\Java\jdk-11.0.2 list... Thanks for the follow up Ryan

**Comment by marcomafcorp** [comment]
I've upgraded to 9.0.2 and I'm still having the same issues. The txt is .py that is giving me the errorl 
Any recommendations will help.

[efiguids.txt](https://github.com/NationalSecurityAgency/ghidra/files/3045687/efiguids.txt)

**Comment by ryanmkurtz** [comment]
I'm glad you got it working, but I'd still like to understand this issue.  What jar did you import?
