### ISSUE TITLE
Using the debugger on files without a symbol table?

### ISSUE THREAD

**Issue by b-naber** [NationalSecurityAgency/ghidra#3430]
I cannot debug a file that doesn't have any symbol table information. Is there a way to debug those binaries in ghidra? I get the following error:

```
<GDB/MI2 -exec-run --start> caused '{msg=[No symbol table loaded.  Use the "file" command.]}'
agent.gdb.manager.impl.cmd.GdbCommandError: <GDB/MI2 -exec-run --start> caused '{msg=[No symbol table loaded.  Use the "file" command.]}'
	at agent.gdb.manager.impl.GdbPendingCommand.checkCompletion(GdbPendingCommand.java:226)
	at agent.gdb.manager.impl.cmd.AbstractLaunchGdbCommand.complete(AbstractLaunchGdbCommand.java:52)
	at agent.gdb.manager.impl.cmd.AbstractLaunchGdbCommand.complete(AbstractLaunchGdbCommand.java:22)
	at agent.gdb.manager.impl.GdbPendingCommand.finish(GdbPendingCommand.java:71)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

---------------------------------------------------
Build Date: 2021-Sep-08 1259 EDT
Ghidra Version: 10.0.3
Java Home: /usr/java/jdk-17
JVM Version: Oracle Corporation 17
OS: Linux 5.10.0-kali7-amd64 amd64
Workstation: kali
```

**Comment by d-millar** [comment]
Hmmm, that error suggests you somehow don’t have an executable.  How were you trying to launch it?  I.e.  did you hit the debug button from the top toolbar, or launch the agent and then hit debug from inside the Objects view, or launch the agent and then use the launch via command line button?  Also, did you have the executable loaded in the debugger’s Static Listing window?

**Comment by b-naber** [comment]
@d-millar Thanks for the response. I launched it using the `Debug in GDB locally IN-VM` option. I did have the executable loaded in the static listing window. This is what the `Import Results Summary` looks like:

![VirtualBox_Kali-Linux-2021 2-virtualbox-amd64_18_09_2021_15_24_32](https://user-images.githubusercontent.com/71934879/133890611-034da036-ec4c-4e64-a529-2d52ebd292c0.png)
e 

This is after the error was thrown:

![VirtualBox_Kali-Linux-2021 2-virtualbox-amd64_18_09_2021_15_36_39](https://user-images.githubusercontent.com/71934879/133890792-3a3e9979-6b04-49a3-896b-a4a7c2e67626.png)

Also if I try to run the debugger using the ssh option I get the following error (might be realted to running ghidra in a VM?):

![VirtualBox_Kali-Linux-2021 2-virtualbox-amd64_18_09_2021_15_26_43](https://user-images.githubusercontent.com/71934879/133890657-df6e3355-0f7b-4ae6-8837-b108fd92e843.png)

**Comment by b-naber** [comment]
When I manually create a connection in the debugger `targets window` the debugger works.

**Comment by d-millar** [comment]
Hey b-naber,

So does your last comment mean that it's up and running for you?

Just in case the answer is no, let me clarify a few things, which may not be obvious from the GUI.  If you launch using the Debug button in the Toolbar (the one right below Tools | Windows), the debugger is going to try to do everything for you, i.e. launch an agent and run the executable in the Static Listing.  It may not make the best choice for you if multiple options are available.  The little pull-down arrow next to the button will show you the various options.  I typically use IN-VM as it's the easiest for me to debug in case of problems, but usually we suggest using the GADP option because, if you crash the debugger in this scenario, it doesn't take Ghidra with it.

The second option is to launch the agent via the Targets window and then run the executable either using the Debug button which picks the executable in the listing or the Launch button which prompts you for the command line.  In your screen snapshot, it looks like you have the agent running, but haven't launched the target.  I say this because you have a null Inferior.  This is what things look like before a process is launched.  Sadly, it's also what things look like if the launch crashed and burned sometimes, so admittedly I'm not sure which state you are in.

Regarding the ssh option, you really really really want to try ssh'ing into the target machine before you use this option.  If you haven't, the stupid message-of-the-day comes across the line, and, well, we don't handle that very well.  The message box you include above has a stack trace that matches this problem, but it could also mean you encountered some other problem while connecting.  Unfortunately, the message produced aren't very informative - we're trying to improve that.

I did download your target program and test it on Ubuntu 20.  It started up without any issues for me.  That said, I was running the 10.1 DEV build out of eclipse, which might behave very differently than your set-up.  I think 10.0.3 should be very close, but I've been wrong before.  I used the pull-down from the main Toolbar and selected the IN-VM option.

Let me know if you're still stuck - and thanks for trying the debugger out!

**Comment by b-naber** [comment]
Yes I got it to run. Thanks a lot for the help.
