### ISSUE TITLE
Apache Felix Framework class loading failures

### ISSUE THREAD

**Issue by goatshriek** [NationalSecurityAgency/ghidra#3450]
**Describe the bug**
A plugin built for Ghidra 10.0.3 is failing in some aspects of its functionality, raising exceptions that library classes cannot be found. This occurs under JDK 16, but not JDK 11. These classes are present in one of the jars included with the plugin, and this same plugin functions without issue when built for/installed in 10.0.2. Here is the error that appears:

```
NameError: cannot load Java class org.jruby.ext.readline.Readline
      load_ext at org/jruby/ext/jruby/JRubyUtilLibrary.java:201
        <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/readline.rb:9
       require at org/jruby/RubyKernel.java:974
       require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:83
  <module:IRB> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb/input-method.rb:130
        <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb/input-method.rb:15
       require at org/jruby/RubyKernel.java:974
       require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:83
        <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb.rb:19
       require at org/jruby/RubyKernel.java:974
       require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:83
        <main> at <script>:1
```

I found that error mostly unhelpful, and after reverting to the 10.0.2 `launch.properties` (which fixes it) I captured this more relevant illegal access warning that reveals the culprit as the felix framework included within Ghidra:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender (file:/C:/Users/reall/code/ghidra/ghidra_10.0.3_PUBLIC/Ghidra/Features/Base/lib/org.apache.felix.framework-6.0.3.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

This led me to the changes I submitted in a pull request which add `--add-opens` statements for each illegal access I ended up encountering. These line up nicely with those listed on the [Apache Felix Jira project](https://issues.apache.org/jira/browse/FELIX-5765) about this problem. Other Ghidra plugins might be affected by this as well, but I haven't been able to find any existing issues that mention it. 

**To Reproduce**
I don't know of a way to trigger this without a plugin. That doesn't mean there isn't one, I just haven't looked very hard for it. To reproduce the specific instance of the issue that I see, you would need to download the plugin build for 10.0.3 and try to open an interactive Ruby scripting window.
1. Download and install the RubyDragon 1.0.0 [build for Ghidra 10.0.3](https://github.com/goatshriek/ruby-dragon/releases/download/v1.0.0/ghidra_10.0.3_PUBLIC_RubyDragon_1.0.0.zip) from the project's release page.
2. Open Ghidra with a project.
3. Open a file from the project in the CodeBrowser tool.
4. Configure the CodeBrowser tool to enable the RubyDragon plugin. Whether or not ClojureDragon is enabled does not appear to make a difference.
5. Open the Ruby window via Window->Ruby.
6. You will be greeted with an error. The thread of execution for that window of course is gone at this point, rendering it unusable. The rest of Ghidra appears to be unaffected.

**Expected behavior**
I would expect Ghidra to be able to find classes that are in the lib jars, of course! Really though, I'm just looking for a resolution that doesn't involve manually modifying `launch.properties` every time someone wants to use this plugin in newer JDK environments. I briefly played with the classloaders used in my plugin, but I wasn't successful in resolving it with that technique.

**Environment**
 - OS: Windows 10.0.19043, Debian 11.0 (kernel 5.10.0-8)
 - Java Version: problem occurs with Adopt OpenJDK 16.0.1, problem does _not_ occur with Adopt OpenJDK 11.0.11
 - Ghidra Version: 10.0.3
 - Ghidra Origin: Downloaded from the github releases page

**Additional context**
The Felix page linked above says that this is fixed in 7.0.0. I didn't try that out as a fix, but just wanted to mention it as an alternate path to my proposed patch.

I do realize that JDK 11 is the supported version of Ghidra and not 16 where the error happens. But I think this is still worth at least reporting and proposing a patch for, given that it was previously working until the recent "illegal reflective access" changes. Fixing this also seems inline with the changes from #3355 currently pinned on the issue list. At a minimum, perhaps it will at least help others with the same issue.

**Comment by ryanmkurtz** [comment]
I am going to try go upgrade Felix the latest 7.x version which should address this issue.

**Comment by mumbel** [comment]
@ryanmkurtz  looking like this broke my build, cannot open browser only front end.  I removed my eclipse workspace and tried a fresh one along with redoing the gradle commands (init/prepDev/eclipse).  Cannot say 100% its not some env issue on my end (20.04 / 11.0.11), but nothing looks different.  Among the stack traces the only string I saw was felix

```
2021-10-07 20:50:28 ERROR (GhidraScriptUtil) Failed to initialize BundleHost ghidra.app.plugin.core.osgi.OSGiException: initializing felix OSGi framework
        at ghidra.app.plugin.core.osgi.BundleHost.startFramework(BundleHost.java:471)
        at ghidra.app.script.GhidraScriptUtil.setBundleHost(GhidraScriptUtil.java:78)
        at ghidra.app.script.GhidraScriptUtil.initialize(GhidraScriptUtil.java:93)
        at ghidra.app.script.GhidraScriptUtil.acquireBundleHostReference(GhidraScriptUtil.java:411)
        at ghidra.app.plugin.core.script.GhidraScriptMgrPlugin.<init>(GhidraScriptMgrPlugin.java:65)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at ghidra.framework.plugintool.util.PluginUtils.instantiatePlugin(PluginUtils.java:184)
        at ghidra.framework.plugintool.PluginManager.addPlugins(PluginManager.java:100)
        at ghidra.framework.plugintool.PluginManager.restorePluginsFromXml(PluginManager.java:271)
        at ghidra.framework.plugintool.PluginTool.restoreFromXml(PluginTool.java:561)
        at ghidra.framework.plugintool.PluginTool.<init>(PluginTool.java:138)
        at ghidra.framework.project.tool.GhidraTool.<init>(GhidraTool.java:81)
        at ghidra.framework.project.tool.GhidraToolTemplate.createTool(GhidraToolTemplate.java:215)
        at ghidra.framework.project.tool.ToolManagerImpl.getTool(ToolManagerImpl.java:661)
        at ghidra.framework.project.tool.WorkspaceImpl.runTool(WorkspaceImpl.java:77)
        at ghidra.framework.main.ToolButton$2.end(ToolButton.java:624)
        at ghidra.framework.main.ZoomImageRunner$1.end(ZoomImageRunner.java:54)
        at org.jdesktop.animation.timing.Animator.end(Animator.java:755)
        at org.jdesktop.animation.timing.Animator.stop(Animator.java:660)
        at org.jdesktop.animation.timing.Animator.timingEvent(Animator.java:732)
        at org.jdesktop.animation.timing.Animator.access$200(Animator.java:75)
        at org.jdesktop.animation.timing.Animator$TimerTarget.actionPerformed(Animator.java:1041)
        at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
        at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.osgi.framework.BundleException: Activator stop error in bundle org.apache.felix.framework [0].
        at org.apache.felix.framework.Felix.stopBundle(Felix.java:2878)
        at org.apache.felix.framework.Felix.init(Felix.java:969)
        at org.apache.felix.framework.Felix.init(Felix.java:648)
        at ghidra.app.plugin.core.osgi.BundleHost.startFramework(BundleHost.java:468)
        ... 39 more
Caused by: java.lang.NullPointerException
        at org.apache.felix.framework.Felix$SystemBundleActivator.stop(Felix.java:5284)
        at org.apache.felix.framework.util.SecureAction.stopActivator(SecureAction.java:871)
        at org.apache.felix.framework.Felix.stopBundle(Felix.java:2822)
        ... 42 more
```

**Comment by ryanmkurtz** [comment]
This is the second report of this but I am having trouble reproducing it.  I'll keep trying.

**Comment by ryanmkurtz** [comment]
Thanks.  I'll likely roll back to the older version on Monday until I can figure out what is going wrong.

**Comment by ryanmkurtz** [comment]
It's looking a classpath ordering issue with the jars.  I've reverted the change locally, which will soon be mirrored up to GitHub.  I'll re-close this issue when I have the proper solution in place.

**Comment by ryanmkurtz** [comment]
I saw that behavior too.  It happens when `biz.aQute.bndlib-5.1.2.jar` comes before `org.apache.felix.framework-7.0.1.jar` on the classpath. They both have `org.osgi.framework.FrameworkUtil`, and when felix goes to call into its version, it ends up calling into bndlib's, which is incompatible with felix 7.x.  Upgrading bndlib to the latest didn't fix the compatibility, so I have to do some more research into how to get those 2 things to place nicely together.  

Having to rely on a certain classpath ordering should be avoided at all costs.  Having said that, I couldn't reproduce this at first because my classpath was ordered differently.  We should put some more work into having a deterministic classpath to at least make problems like this more consistent.

**Comment by ryanmkurtz** [comment]
This classpath issue was fixed in `biz.aQute.bndlib-6.1.0.jar` ([release notes](https://github.com/bndtools/bnd/wiki/Changes-in-6.1.0#bnd)).  I am going to continue trying to get this upgrade working.

**Comment by jpleasu** [comment]
Yeah - `bndLib` is  really making an OSGi bundle of a script directory - the manifest being the configuration file for a bundle.

You could probably cover most script directories with a simpler manifest generator?  Fallback to an external call to `bnd` might work?

**Comment by ryanmkurtz** [comment]
Thanks for feedback.  Yes, I'll experiment with a simpler manifest generator.
