### ISSUE TITLE
'Defined Strings' view causes Ghidra to hang / 100% CPU for one thread forever

### ISSUE THREAD

**Issue by patric-r** [NationalSecurityAgency/ghidra#3498]
**Describe the bug**
I analyzed a large binary (unfortunately, I cannot share it) without having the "defined strings" view open.
I saved the project, closed ghidra and after restarting it I reopened the file. After displaying the "Defined Strings" view, Ghidra tries to load the Strings, by showing a small status bar at the bottom of the view.

I makes quickly progress but at 34% it gets reproducibly stuck forever (endless loop)
The thread responsible for loading the view consumes 100% cpu. Closing Ghidra will not stop the problem, the process stays alive.
Stack traces for **the same thread** (acquired multiple times):

```
"Threaded Table Model Update Manager: Defined String Table" #70 prio=6 os_prio=0 cpu=290078.13ms elapsed=295.04s tid=0x000001aacd229000 nid=0x2254 runnable  [0x0000005784afe000]
   java.lang.Thread.State: RUNNABLE
        at db.LongKeyRecordNode.getNextLeaf(LongKeyRecordNode.java:142)
        at db.Table$LongKeyRecordIterator.hasNext(Table.java:2218)
        - locked <0x00000005c3352248> (a db.DBHandle)
        at ghidra.program.database.map.AddressKeyRecordIterator.hasNext(AddressKeyRecordIterator.java:181)
        at ghidra.program.database.map.AddressKeyRecordIterator.next(AddressKeyRecordIterator.java:226)
        at ghidra.program.database.code.InstDBAdapterV1.getRecordAfter(InstDBAdapterV1.java:115)
        at ghidra.program.database.code.CodeManager.getDefinedAddressAfter(CodeManager.java:2832)
        at ghidra.program.database.code.DataDB.computeLength(DataDB.java:169)
        at ghidra.program.database.code.DataDB.<init>(DataDB.java:75)
        at ghidra.program.database.code.DataComponent.<init>(DataComponent.java:80)
        at ghidra.program.database.code.DataDB.getComponent(DataDB.java:225)
        at ghidra.program.util.DefinedDataIterator$DataComponentIterator.next(DefinedDataIterator.java:251)
        at ghidra.program.util.DefinedDataIterator.findNext(DefinedDataIterator.java:173)
        at ghidra.program.util.DefinedDataIterator.hasNext(DefinedDataIterator.java:147)
        at ghidra.app.plugin.core.strings.ViewStringsTableModel.doLoad(ViewStringsTableModel.java:117)
        at docking.widgets.table.threaded.ThreadedTableModel.load(ThreadedTableModel.java:182)
        at docking.widgets.table.threaded.TableUpdateJob.loadData(TableUpdateJob.java:357)
        at docking.widgets.table.threaded.TableUpdateJob.processState(TableUpdateJob.java:330)
        at docking.widgets.table.threaded.TableUpdateJob.run(TableUpdateJob.java:129)
        at docking.widgets.table.threaded.ThreadedTableModelUpdateMgr$ThreadRunnable.run(ThreadedTableModelUpdateMgr.java:415)
        at java.lang.Thread.run(java.base@11.0.2/Thread.java:834)



"Threaded Table Model Update Manager: Defined String Table" #70 prio=6 os_prio=0 cpu=373937.50ms elapsed=380.14s tid=0x000001aacd229000 nid=0x2254 runnable  [0x0000005784afe000]
   java.lang.Thread.State: RUNNABLE
        at db.Table$LongKeyRecordIterator.hasPrevious(Table.java:2253)
        - locked <0x00000005c3352248> (a db.DBHandle)
        at ghidra.program.database.map.AddressKeyRecordIterator.hasNext(AddressKeyRecordIterator.java:185)
        at ghidra.program.database.map.AddressKeyRecordIterator.next(AddressKeyRecordIterator.java:226)
        at ghidra.program.database.code.InstDBAdapterV1.getRecordAfter(InstDBAdapterV1.java:115)
        at ghidra.program.database.code.CodeManager.getDefinedAddressAfter(CodeManager.java:2832)
        at ghidra.program.database.code.DataDB.computeLength(DataDB.java:169)
        at ghidra.program.database.code.DataDB.<init>(DataDB.java:75)
        at ghidra.program.database.code.DataComponent.<init>(DataComponent.java:80)
        at ghidra.program.database.code.DataDB.getComponent(DataDB.java:225)
        at ghidra.program.util.DefinedDataIterator$DataComponentIterator.next(DefinedDataIterator.java:251)
        at ghidra.program.util.DefinedDataIterator.findNext(DefinedDataIterator.java:173)
        at ghidra.program.util.DefinedDataIterator.hasNext(DefinedDataIterator.java:147)
        at ghidra.app.plugin.core.strings.ViewStringsTableModel.doLoad(ViewStringsTableModel.java:117)
        at docking.widgets.table.threaded.ThreadedTableModel.load(ThreadedTableModel.java:182)
        at docking.widgets.table.threaded.TableUpdateJob.loadData(TableUpdateJob.java:357)
        at docking.widgets.table.threaded.TableUpdateJob.processState(TableUpdateJob.java:330)
        at docking.widgets.table.threaded.TableUpdateJob.run(TableUpdateJob.java:129)
        at docking.widgets.table.threaded.ThreadedTableModelUpdateMgr$ThreadRunnable.run(ThreadedTableModelUpdateMgr.java:415)
        at java.lang.Thread.run(java.base@11.0.2/Thread.java:834)

"Threaded Table Model Update Manager: Defined String Table" #70 prio=6 os_prio=0 cpu=396937.50ms elapsed=403.44s tid=0x000001aacd229000 nid=0x2254 runnable  [0x0000005784afd000]
   java.lang.Thread.State: RUNNABLE
        at db.NodeMgr.getLongKeyNode(NodeMgr.java:257)
        at db.LongKeyInteriorNode.getLeafNode(LongKeyInteriorNode.java:414)
        at db.Table$LongKeyRecordIterator.<init>(Table.java:2079)
        at db.Table.iterator(Table.java:1863)
        - locked <0x00000005c3352248> (a db.DBHandle)
        at ghidra.program.database.map.AddressKeyRecordIterator.hasNext(AddressKeyRecordIterator.java:184)
        at ghidra.program.database.map.AddressKeyRecordIterator.next(AddressKeyRecordIterator.java:226)
        at ghidra.program.database.code.InstDBAdapterV1.getRecordAfter(InstDBAdapterV1.java:115)
        at ghidra.program.database.code.CodeManager.getDefinedAddressAfter(CodeManager.java:2832)
        at ghidra.program.database.code.DataDB.computeLength(DataDB.java:169)
        at ghidra.program.database.code.DataDB.<init>(DataDB.java:75)
        at ghidra.program.database.code.DataComponent.<init>(DataComponent.java:80)
        at ghidra.program.database.code.DataDB.getComponent(DataDB.java:225)
        at ghidra.program.util.DefinedDataIterator$DataComponentIterator.next(DefinedDataIterator.java:251)
        at ghidra.program.util.DefinedDataIterator.findNext(DefinedDataIterator.java:173)
        at ghidra.program.util.DefinedDataIterator.hasNext(DefinedDataIterator.java:147)
        at ghidra.app.plugin.core.strings.ViewStringsTableModel.doLoad(ViewStringsTableModel.java:117)
        at docking.widgets.table.threaded.ThreadedTableModel.load(ThreadedTableModel.java:182)
        at docking.widgets.table.threaded.TableUpdateJob.loadData(TableUpdateJob.java:357)
        at docking.widgets.table.threaded.TableUpdateJob.processState(TableUpdateJob.java:330)
        at docking.widgets.table.threaded.TableUpdateJob.run(TableUpdateJob.java:129)
        at docking.widgets.table.threaded.ThreadedTableModelUpdateMgr$ThreadRunnable.run(ThreadedTableModelUpdateMgr.java:415)
        at java.lang.Thread.run(java.base@11.0.2/Thread.java:834)
```

**Environment (please complete the following information):**

 - OS: Windows 10
 - Java Version: 11.0.2
 - Ghidra Version: 10.0.4
 - Ghidra Origin:  official ghidra-sre.org distro

**Comment by astrelsky** [comment]
> -snip-
> In lieu of a binary, assuming you are amenable, we should be able to work with you to use logging to have you debug the issue.  If you are running from a build of Ghidra, then this will require a patch jar file.  If running from a forked repo, then you would be able to add the debug statements yourself. 

You can override the log configuration by setting the following in the launch configuration. `VMARGS=-Dlog4j.configuration=%GHIDRA_INSTALL_DIR%\support\debug.log4j.xml` to ensure it works I recommend hard coding the path instead of using an environment variable.  You will see which settings get used in the resulting log file.

**Comment by dev747368** [comment]
A troubleshooting method that might work is doing a bisect on the memory in your binary... selecting 50% of the addresses and clearing them so they are undefined, and then checking what the Defined Strings table does, lather rinse repeat.

**Comment by ghidra007** [comment]
@patric-r Are you still seeing this issue since the above mentioned fixes were made?
