### ISSUE TITLE
NullPointerExceptions when importing specification extensions

### ISSUE THREAD

**Issue by goatshriek** [NationalSecurityAgency/ghidra#3502]
**Describe the bug**
The new `Specification Extension` option within the Decompiler Options menu for a specific program has problems when importing a new `callotherfixup` extension. Upon importing one, NullPointerExceptions are thrown constantly.

**To Reproduce**
1. Open a project/file in the CodeBrowser.
2. Go to the `Edit->Options for <filename>...` menu
3. Go to the `Specification Extensions` page
4. Import a `callotherfixup` xml file. I used this one just for testing:
```xml
<callotherfixup targetop="bad_CMPXCHG8B">
  <pcode>
    <body><![CDATA[
      EAX = EAX;
    ]]></body>
  </pcode>
</callotherfixup>
```
5. Click `Apply`
6. Ye olde NullPointerException:
```
Cannot invoke "ghidra.program.model.lang.InjectPayload.isErrorPlaceholder()" because the return value of "ghidra.program.model.lang.PcodeInjectLibrary.getPayload(int, java.lang.String)" is null
java.lang.NullPointerException: Cannot invoke "ghidra.program.model.lang.InjectPayload.isErrorPlaceholder()" because the return value of "ghidra.program.model.lang.PcodeInjectLibrary.getPayload(int, java.lang.String)" is null
	at ghidra.app.plugin.processors.sleigh.SpecExtensionPanel.populateElementTable(SpecExtensionPanel.java:327)
	at ghidra.app.plugin.processors.sleigh.SpecExtensionPanel.apply(SpecExtensionPanel.java:355)
	at ghidra.app.plugin.processors.sleigh.SpecExtensionEditor.apply(SpecExtensionEditor.java:40)
	at docking.options.editor.OptionsPanel.apply(OptionsPanel.java:210)
	at docking.options.editor.OptionsDialog.applyChanges(OptionsDialog.java:125)
	at docking.options.editor.OptionsDialog.applyCallback(OptionsDialog.java:117)
	at docking.DialogComponentProvider.lambda$addApplyButton$3(DialogComponentProvider.java:490)
	at docking.DialogComponentProvider$$Lambda$474/0x000000000c865af0.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:708)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:708)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:682)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1079)
	at java.desktop/java.awt.Component.show(Component.java:1720)
	at java.desktop/java.awt.Component.setVisible(Component.java:1667)
	at java.desktop/java.awt.Window.setVisible(Window.java:1032)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1014)
	at docking.DockingDialog.setVisible(DockingDialog.java:353)
	at docking.DockingWindowManager.lambda$doShowDialog$6(DockingWindowManager.java:1751)
	at docking.DockingWindowManager$$Lambda$397/0x000000000c63be08.run(Unknown Source)
	at app//ghidra.util.Swing.doRun(Swing.java:292)
	at app//ghidra.util.Swing.runNow(Swing.java:208)
	at app//ghidra.util.Swing.runNow(Swing.java:163)
	at docking.DockingWindowManager.doShowDialog(DockingWindowManager.java:1755)
	at docking.DockingWindowManager.showDialog(DockingWindowManager.java:1704)
	at docking.AbstractDockingTool.showDialog(AbstractDockingTool.java:154)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.showProgramOptions(ProgramManagerPlugin.java:633)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.lambda$createActions$15(ProgramManagerPlugin.java:600)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin$$Lambda$521/0x000000000c9fd6b8.accept(Unknown Source)
	at docking.action.builder.ActionBuilder$1.actionPerformed(ActionBuilder.java:48)
	at docking.DockingActionProxy.actionPerformed(DockingActionProxy.java:47)
	at docking.MenuBarMenuHandler.lambda$processMenuAction$0(MenuBarMenuHandler.java:64)
	at docking.MenuBarMenuHandler$$Lambda$972/0x000000000e0a9fc8.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:708)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2021-Oct-13 1618 EDT
Ghidra Version: 10.1
Java Home: .sdkman/candidates/java/16.0.1.j9-adpt
JVM Version: AdoptOpenJDK 16.0.1
OS: Linux 4.19.0-16-amd64 amd64
```

**Expected behavior**
While I love a good NPE as much as the next person, it would be nice if importing a fixup didn't result in an error message.

**Environment:**
 - OS: Debian 10, Linux 4.19.0
 - Java Version: 16.0.1
 - Ghidra Version: `10.1_DEV`
 - Ghidra Origin: locally built from master branch of official github repo

**Additional context**
I'll create a pull request shortly with a simple fix.

**Comment by astrelsky** [comment]
Is this a recent issue? I have used this without a problem in 10.1_DEV without a problem.

**Comment by caheckman** [comment]
I'm reproducing this. Thank you.
