### ISSUE TITLE
Error in plugin event listener

### ISSUE THREAD

**Issue by Shadorain** [NationalSecurityAgency/ghidra#3604]
**Describe the bug**
When trying to open code browser I get a slew of errors (that I have to click through) about Ghidra failing to compute hashes then a large error at the end. Code browser opens fine after I click through all that, no noticeable hiccups once it is open but it is annoying to click through a bunch of error message boxes.

**To Reproduce**
1. I installed the Kaiju plugin to get the OOanalyzer functionality.
2. Open any project, new or old I believe, and then open codebrowser
3. It will open quite a number or error message boxes saying: `Error computing hashes` or similar which I have to go through and close each (pain on a tiling window manager)

**Expected behavior**
I only expect it to load the codebrowser normally, not make me click through a bunch of errors and then the main error (described below).

**Screenshots**
![image](https://user-images.githubusercontent.com/35006332/140763048-85c541ec-2726-4cdc-b3fc-78309863620c.png)

**Environment:**
 - OS: Void Linux x86_64
 - Java Version: 11.0.12
 - Ghidra Version: 10.0.4_PUBLIC
 - Ghidra Origin: official ghidra-sre.org

**Additional context**
Here is the error:
```
no libz3java in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
java.lang.UnsatisfiedLinkError: no libz3java in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at com.microsoft.z3.Native.<clinit>(Native.java:17)
	at com.microsoft.z3.Version.getFullVersion(Version.java:71)
	at kaiju.tools.ghihorn.GhiHornProvider.buildAnalysisControlPanel(GhiHornProvider.java:292)
	at kaiju.tools.ghihorn.GhiHornProvider.buildMainPanel(GhiHornProvider.java:572)
	at kaiju.tools.ghihorn.GhiHornProvider.<init>(GhiHornProvider.java:157)
	at kaiju.tools.ghihorn.GhiHornPlugin.programActivated(GhiHornPlugin.java:172)
	at ghidra.app.plugin.ProgramPlugin.processEvent(ProgramPlugin.java:138)
	at ghidra.framework.plugintool.Plugin.eventSent(Plugin.java:329)
	at ghidra.framework.plugintool.mgr.EventManager.sendEvents(EventManager.java:286)
	at ghidra.framework.plugintool.mgr.EventManager.lambda$new$3(EventManager.java:49)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.framework.plugintool.mgr.EventManager.fireEvent(EventManager.java:216)
	at ghidra.framework.plugintool.PluginTool.firePluginEvent(PluginTool.java:475)
	at ghidra.framework.plugintool.Plugin.firePluginEvent(Plugin.java:481)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.fireActivatedEvent(MultiProgramManager.java:278)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.setCurrentProgram(MultiProgramManager.java:251)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.setCurrentProgram(MultiProgramManager.java:193)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.addProgram(MultiProgramManager.java:93)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.lambda$openProgram$6(ProgramManagerPlugin.java:489)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.util.SystemUtilities.runSwingNow(SystemUtilities.java:232)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.openProgram(ProgramManagerPlugin.java:495)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.openPrograms(ProgramManagerPlugin.java:781)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.acceptData(ProgramManagerPlugin.java:139)
	at ghidra.framework.plugintool.PluginManager.acceptData(PluginManager.java:48)
	at ghidra.framework.plugintool.PluginTool.acceptDomainFiles(PluginTool.java:414)
	at ghidra.framework.project.tool.ToolServicesImpl.launchDefaultTool(ToolServicesImpl.java:195)
	at ghidra.framework.main.projectdata.actions.ProjectDataOpenDefaultToolAction.actionPerformed(ProjectDataOpenDefaultToolAction.java:40)
	at ghidra.framework.main.projectdata.actions.ProjectDataOpenDefaultToolAction.actionPerformed(ProjectDataOpenDefaultToolAction.java:28)
	at docking.action.ContextSpecificAction.actionPerformed(ContextSpecificAction.java:71)
	at docking.ExecutableAction.execute(ExecutableAction.java:40)
	at docking.action.MultipleKeyAction.actionPerformed(MultipleKeyAction.java:142)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at docking.KeyBindingOverrideKeyEventDispatcher.actionInProgress(KeyBindingOverrideKeyEventDispatcher.java:214)
	at docking.KeyBindingOverrideKeyEventDispatcher.dispatchKeyEvent(KeyBindingOverrideKeyEventDispatcher.java:116)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1133)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4892)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2021-Sep-28 1538 EDT
Ghidra Version: 10.0.4
Java Home: /usr/lib/jvm/openjdk11
JVM Version: Void 11.0.12
OS: Linux 5.13.10_1 amd64
Workstation: <unknown>
```

Thanks!

**Comment by dragonmacher** [comment]
This appears to be an issue with the 3rd-party plugin and its library dependencies.   We suggest you reach out to that plugin creator for help with this issue.

**Comment by Shadorain** [comment]
> This appears to be an issue with the 3rd-party plugin and its library dependencies. We suggest you reach out to that plugin creator for help with this issue.

Can do thank you!

**Comment by Raijinili** [comment]
For reference: @Shadorain opened an issue at CERTCC/kaiju#8
