### ISSUE TITLE
SLEIGH error reporting is broken

### ISSUE THREAD

**Issue by achan1989** [NationalSecurityAgency/ghidra#364]
**Describe the bug**
When parsing a spec that contains certain kinds of errors in a semantic section, no useful error message is reported.

**To Reproduce**
With Ghidra 9.0.2, using the attached spec file:
`sleigh.bat -x -u -l -n -t -e -f mistake.txt`

    ERROR Unrecoverable error(s), halting compilation (SleighCompile) java.lang.NullPointerException
            at ghidra.sleigh.grammar.AbstractSleighParser.getErrorHeader(AbstractSleighParser.java:45)
            at org.antlr.runtime.BaseRecognizer.displayRecognitionError(BaseRecognizer.java:192)
            at org.antlr.runtime.BaseRecognizer.reportError(BaseRecognizer.java:186)
            at org.antlr.runtime.BaseRecognizer.recoverFromMismatchedToken(BaseRecognizer.java:613)
            at org.antlr.runtime.BaseRecognizer.match(BaseRecognizer.java:115)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.expr_term(SleighParser_SemanticParser.java:12172)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.expr_func(SleighParser_SemanticParser.java:11071)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.expr_unary(SleighParser_SemanticParser.java:9968)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.expr_mult(SleighParser_SemanticParser.java:9540)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.expr_add(SleighParser_SemanticParser.java:9248)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.expr_shift(SleighParser_SemanticParser.java:8995)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.expr_comp(SleighParser_SemanticParser.java:8391)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.expr_eq(SleighParser_SemanticParser.java:8099)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.expr_and(SleighParser_SemanticParser.java:7940)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.expr_xor(SleighParser_SemanticParser.java:7781)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.expr_or(SleighParser_SemanticParser.java:7622)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.expr_booland(SleighParser_SemanticParser.java:7410)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.expr_boolor(SleighParser_SemanticParser.java:7251)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.expr(SleighParser_SemanticParser.java:7197)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.cond_stmt(SleighParser_SemanticParser.java:6725)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.statement(SleighParser_SemanticParser.java:1007)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.statements(SleighParser_SemanticParser.java:579)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.code_block(SleighParser_SemanticParser.java:481)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.semantic(SleighParser_SemanticParser.java:387)
            at ghidra.sleigh.grammar.SleighParser_SemanticParser.semanticbody(SleighParser_SemanticParser.java:315)
            at ghidra.sleigh.grammar.SleighParser.semanticbody(SleighParser.java:17388)
            at ghidra.sleigh.grammar.SleighParser.ctorsemantic(SleighParser.java:6469)
            at ghidra.sleigh.grammar.SleighParser.constructor(SleighParser.java:6367)
            at ghidra.sleigh.grammar.SleighParser.constructorlike(SleighParser.java:5360)
            at ghidra.sleigh.grammar.SleighParser.spec(SleighParser.java:465)
            at ghidra.pcodeCPort.slgh_compile.SleighCompileLauncher.run_compilation(SleighCompileLauncher.java:354)
            at ghidra.pcodeCPort.slgh_compile.SleighCompileLauncher.runMain(SleighCompileLauncher.java:268)
            at ghidra.pcodeCPort.slgh_compile.SleighCompileLauncher.launch(SleighCompileLauncher.java:72)
            at ghidra.GhidraLauncher.main(GhidraLauncher.java:78)

**Expected behavior**
A useful error message, eg "missing parenthesis at..."

**Environment:**
 - Windows 7 x64
 - Java: openjdk 11.0.2
 - Ghidra Version: 9.0.2

[mistake.txt](https://github.com/NationalSecurityAgency/ghidra/files/3050586/mistake.txt)

**Comment by achan1989** [comment]
I have a patch for this, will open a pull request shortly.
