### ISSUE TITLE
Ghidra Check-In: File Update not permitted

### ISSUE THREAD

**Issue by GuaGithub** [NationalSecurityAgency/ghidra#3699]
**Describe the bug**
```
File update not permitted
java.io.IOException: File update not permitted
    at db.buffers.LocalManagedBufferFile.createNewVersion(LocalManagedBufferFile.java:554)
    at ghidra.framework.data.GhidraFileData.quickCheckin(GhidraFileData.java:956)
    at ghidra.framework.data.GhidraFileData.checkin(GhidraFileData.java:1030)
    at ghidra.framework.data.GhidraFile.checkin(GhidraFile.java:438)
    at ghidra.framework.main.datatree.CheckInTask.run(CheckInTask.java:102)
    at ghidra.util.task.Task.monitoredRun(Task.java:124)
    at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)

---------------------------------------------------
Build Date: 2021-Sep-28 1538 EDT
Ghidra Version: 10.0.4
Java Home: /Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home
JVM Version: Oracle Corporation 17.0.1
OS: Mac OS X 12.0 aarch64
Workstation: Gua-mbp

```
**To Reproduce**
I saved a new Ghidra binary change to my Ghidra server several times with admin rights before, now I just try to checkout the same saved binary and make a minor change like a function name change, then to check-in on Ghidra, so I enter the change description for this new commit, and all of a sudden the Error During Check-In process described above pops up.

At first thoughts, I expected it to be just maybe an permission error, but the user is already an admin, and I succeeded to update the binary with the same username several times before. Then when looking it up in the source code it's not what you expect, it's "outFile == null", but I have no idea why this happens as I just try to save a file change normally with Ghidra.

```
ManagedBufferFile outFile = destFile.getSaveFile();
if (outFile == null) {
    throw new IOException("File update not permitted");
}

```

**Expected behavior**
It should just check-in the new version perfectly as always

**Screenshots**
https://imgur.com/4GdN17K

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: macOS 12
 - Java Version: 
Java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

 - Ghidra Version: 10.04
 - Ghidra Origin: official ghidra-sre.org distro

**Additional context**

**Comment by ghidra1** [comment]
Could you please examine (or provide) your server-side log file for errors that coincide with this checkin.  The implication is that the server-side buffer file pre-save failed and was unavailable to complete the checkin.  Possibly out of disk space to complete pre-save or server-side disk access permission failure.

**Comment by ghidra1** [comment]
After review of your original post it would seem the server process owner when repository files were initially created now differs from the current process owner.  The repository file ownership should match the process owner.  If you change the server process owner you must migrate the file ownership of all repository files managed by the process.  The issue you describe is expected in light of this process owner switch.
