### ISSUE TITLE
Class cast exception on enum types

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#3740]
**Describe the bug**
![image](https://user-images.githubusercontent.com/67698927/145602606-74284547-16d3-4c77-8419-d5cc90a87126.png)

**To Reproduce**
1. Go to a function in the Decompile View where you have a variable declared as an `enum` type
2. Click on the `enum` type
3. See error

**Expected behavior**
No such errors.

**Screenshots**
As above.

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0.2 / 16.0,.1
 - Ghidra Version: 10.2-DEV
 - Ghidra Origin: locally built

**Additional context**
The problem is in class FindReferencesToDataTypeAction, method `protected String getDataTypeField(DataType dataType)` line  [ClangVariableToken vt = (ClangVariableToken) tokenAtCursor;](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Decompiler/src/main/java/ghidra/app/plugin/core/decompile/actions/FindReferencesToDataTypeAction.java#L62) doesn't check to see if indeed `vt` is a `ClangVariableToken`.  In this situation it is actually a `ClangTypeToken`.

**Comment by dragonmacher** [comment]
Do you happen to have the full stack trace?

**Comment by Wall-AF** [comment]
```
class ghidra.app.decompiler.ClangTypeToken cannot be cast to class ghidra.app.decompiler.ClangVariableToken (ghidra.app.decompiler.ClangTypeToken and ghidra.app.decompiler.ClangVariableToken are in unnamed module of loader ghidra.GhidraClassLoader @33e5ccce)
java.lang.ClassCastException: class ghidra.app.decompiler.ClangTypeToken cannot be cast to class ghidra.app.decompiler.ClangVariableToken (ghidra.app.decompiler.ClangTypeToken and ghidra.app.decompiler.ClangVariableToken are in unnamed module of loader ghidra.GhidraClassLoader @33e5ccce)
	at ghidra.app.plugin.core.decompile.actions.FindReferencesToDataTypeAction.getDataTypeField(FindReferencesToDataTypeAction.java:64)
	at ghidra.app.plugin.core.decompile.actions.FindReferencesToDataTypeAction.updateMenuName(FindReferencesToDataTypeAction.java:125)
	at ghidra.app.plugin.core.decompile.actions.FindReferencesToDataTypeAction.lambda$0(FindReferencesToDataTypeAction.java:102)
	at ghidra.app.plugin.core.decompile.DecompilerActionContext.checkActionEnablement(DecompilerActionContext.java:147)
	at ghidra.app.plugin.core.decompile.actions.FindReferencesToDataTypeAction.isEnabledForContext(FindReferencesToDataTypeAction.java:99)
	at docking.ComponentPlaceholder.contextChanged(ComponentPlaceholder.java:532)
	at docking.DockingWindowManager.contextChanged(DockingWindowManager.java:2232)
	at docking.AbstractDockingTool.contextChanged(AbstractDockingTool.java:208)
	at ghidra.framework.plugintool.PluginTool.contextChanged(PluginTool.java:1433)
	at ghidra.app.plugin.core.decompile.DecompilerProvider.contextChanged(DecompilerProvider.java:689)
	at ghidra.app.plugin.core.decompile.DecompilerProvider.locationChanged(DecompilerProvider.java:531)
	at ghidra.app.decompiler.component.DecompilerController.locationChanged(DecompilerController.java:262)
	at ghidra.app.decompiler.component.DecompilerPanel.fieldLocationChanged(DecompilerPanel.java:931)
	at docking.widgets.fieldpanel.FieldPanel$CursorHandler.notifyCursorChanged(FieldPanel.java:2133)
	at docking.widgets.fieldpanel.FieldPanel$CursorHandler.setCursorPos(FieldPanel.java:1928)
	at docking.widgets.fieldpanel.FieldPanel$FieldPanelMouseAdapter.mousePressed(FieldPanel.java:1316)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6614)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4560)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2021-Dec-10
Ghidra Version: 10.2
Java Home: C:\Program Files\Java\jdk-16.0.1
JVM Version: Oracle Corporation 16.0.1
OS: Windows 10 10.0 amd64
Workstation: xxxxxxxx
```

**Comment by Wall-AF** [comment]
My temporary solution surrounds the cast (and next 9 lines) with:
```
			if (tokenAtCursor instanceof ClangVariableToken) {

			}
```
