### ISSUE TITLE
Java reflection exception in headless mode disassembling Dalvik bytecode.

### ISSUE THREAD

**Issue by inreverse-sec** [NationalSecurityAgency/ghidra#3765]
Has anyone had this issue? The following is an exception dump from Ghidra in headless mode running in a container.

WARN  Analyzer 'Call-Fixup Installer' for classes.dex disabled by PSPEC file override (AnalysisScheduler)
WARN  Analyzer 'Disassemble Entry Points' for classes.dex disabled by PSPEC file override (AnalysisScheduler)
WARN  Analyzer 'Subroutine References' for classes.dex disabled by PSPEC file override (AnalysisScheduler)
WARN  Analyzer 'External Entry References' for classes.dex disabled by PSPEC file override (AnalysisScheduler)
WARN  Analyzer 'Subroutine References' for classes.dex disabled by PSPEC file override (AnalysisScheduler)
WARN  Analyzer 'Shared Return Calls' for classes.dex disabled by PSPEC file override (AnalysisScheduler)
WARN  Analyzer 'Shared Return Calls' for classes.dex disabled by PSPEC file override (AnalysisScheduler)
WARN  Analyzer 'Stack' for classes.dex disabled by PSPEC file override (AnalysisScheduler)
WARN  Analyzer 'ASCII Strings' for classes.dex disabled by PSPEC file override (AnalysisScheduler)
ERROR Abort due to Headless analyzer error: java.lang.reflect.InvocationTargetException (HeadlessAnalyzer) java.lang.InternalError: java.lang.reflect.InvocationTargetException
        at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
        at java.desktop/sun.font.SunFontManager.getInstance(SunFontManager.java:247)
        at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:265)
        at java.desktop/sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1243)
        at java.desktop/javax.swing.JComponent.getFontMetrics(JComponent.java:1646)
        at java.desktop/javax.swing.plaf.basic.BasicLabelUI.getPreferredSize(BasicLabelUI.java:246)
        at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1680)
        at java.desktop/javax.swing.plaf.basic.BasicComboBoxRenderer.getPreferredSize(BasicComboBoxRenderer.java:88)
        at java.desktop/javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1441)
        at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1389)
        at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2785)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:219)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:199)
        at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:246)
        at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:443)
        at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:453)
        at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:497)
        at java.desktop/javax.swing.JList.setSelectedIndex(JList.java:2205)
        at java.desktop/javax.swing.plaf.basic.BasicComboPopup.setListSelection(BasicComboPopup.java:1234)
        at java.desktop/javax.swing.plaf.basic.BasicComboPopup$Handler.itemStateChanged(BasicComboPopup.java:1058)
        at java.desktop/javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1227)
        at java.desktop/javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1288)
        at java.desktop/javax.swing.JComboBox.contentsChanged(JComboBox.java:1335)
        at java.desktop/javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:123)
        at java.desktop/javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:94)
        at java.desktop/javax.swing.DefaultComboBoxModel.addElement(DefaultComboBoxModel.java:132)
        at java.desktop/javax.swing.JComboBox.addItem(JComboBox.java:716)
        at ghidra.framework.options.PropertySelector.<init>(PropertySelector.java:43)
        at ghidra.app.plugin.core.analysis.GnuDemanglerAnalyzer$FormatSelector.<init>(GnuDemanglerAnalyzer.java:184)
        at ghidra.app.plugin.core.analysis.GnuDemanglerAnalyzer$FormatEditor.<init>(GnuDemanglerAnalyzer.java:131)
        at ghidra.app.plugin.core.analysis.GnuDemanglerAnalyzer.registerOptions(GnuDemanglerAnalyzer.java:80)
        at ghidra.app.plugin.core.analysis.AnalysisScheduler.registerOptions(AnalysisScheduler.java:139)
        at ghidra.app.plugin.core.analysis.AnalysisTaskList.registerOptions(AnalysisTaskList.java:131)
        at ghidra.app.plugin.core.analysis.AutoAnalysisManager.registerOptions(AutoAnalysisManager.java:1077)
        at ghidra.app.plugin.core.analysis.AutoAnalysisManager.registerOptions(AutoAnalysisManager.java:1050)
        at ghidra.app.plugin.core.analysis.AutoAnalysisManager.initializeAnalyzers(AutoAnalysisManager.java:192)
        at ghidra.app.plugin.core.analysis.AutoAnalysisManager.<init>(AutoAnalysisManager.java:147)
        at ghidra.app.plugin.core.analysis.AutoAnalysisManager.getAnalysisManager(AutoAnalysisManager.java:983)
        at ghidra.app.util.headless.HeadlessAnalyzer.processFileWithImport(HeadlessAnalyzer.java:1611)
        at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1688)
        at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1753)
        at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:445)
        at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:121)
        at ghidra.GhidraLauncher.launch(GhidraLauncher.java:59)
        at ghidra.Ghidra.main(Ghidra.java:47)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84)
        ... 46 more
Caused by: java.lang.NullPointerException
        at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
        at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225)
        at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:107)
        at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:719)
        at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:367)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:312)
        at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
        at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
        ... 51 more

**Comment by dragonmacher** [comment]
The implication is that GUI code is getting initialized in a headless environment.  If so, this is a bug that needs to be fixed.

**Comment by astrelsky** [comment]
> The implication is that GUI code is getting initialized in a headless environment. If so, this is a bug that needs to be fixed.

Looks like it was my fault. This should either be something else to listen to it in headless mode or nothing at all.
https://github.com/NationalSecurityAgency/ghidra/blob/e0cb6a78faaf3c700b9478fd46192258fef9b545/Ghidra/Features/GnuDemangler/src/main/java/ghidra/app/plugin/core/analysis/GnuDemanglerAnalyzer.java#L80

**Comment by dragonmacher** [comment]
> Looks like it was my fault. This should either be something else to listen to it in headless mode or nothing at all.

We built this code as a team, so we can share blame as a team :dragon:

**Comment by inreverse-sec** [comment]
Thank you gentlemen for your quick feedback on this question. I fixed the issue for my specific use case on my end, Ill leave this open until its gets fixed in a future release.
