### ISSUE TITLE
Uncaught exception error while viewing help ("this.lastAnimator" is null)

### ISSUE THREAD

**Issue by M-a-r-k** [NationalSecurityAgency/ghidra#3767]
Ghidra 10.1 on Windows 10 with Java 17.0.1.

I was able to trigger an uncaught exception error while viewing Ghidra help. Not sure of what specifically I did, but clicking around a lot in the tree view eventually causes it.

Maybe worth noting, I had previously unchecked the "Use Notification Animation" setting.
```
Uncaught Exception!

Cannot invoke "org.jdesktop.animation.timing.Animator.addTarget(org.jdesktop.animation.timing.TimingTarget)" because "this.lastAnimator" is null
java.lang.NullPointerException: Cannot invoke "org.jdesktop.animation.timing.Animator.addTarget(org.jdesktop.animation.timing.TimingTarget)" because "this.lastAnimator" is null
	at docking.help.GHelpBroker.doCalloutReference(GHelpBroker.java:501)
	at docking.help.GHelpBroker.calloutReference(GHelpBroker.java:415)
	at docking.help.GHelpBroker.lambda$calloutReferenceLater$2(GHelpBroker.java:401)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2021-Dec-10 1523 EST
Ghidra Version: 10.1
Java Home: C:\Program Files\Microsoft\jdk-17.0.1.12-hotspot
JVM Version: Microsoft 17.0.1
```

**Comment by dragonmacher** [comment]
If you disable animation in the main tool then this can happen.   We will fix this, but until then, re-enabling animation should prevent the issue.
