### ISSUE TITLE
Ability to load/decompress ZIP files with passwords

### ISSUE THREAD

**Issue by agnosticlines** [NationalSecurityAgency/ghidra#377]
**Is your feature request related to a problem? Please describe.**
Ghidra has already made using archives in analysis a lot easier which is an awesome step, but one feature I'd really like to see is the ability to enter a password to decompress the archive, for bonus points also potentially specify a list of paswords such as "infected" etc and ghidra would try to auto decompress?

Just would speed up analysis workflow :-)

**Comment by 0x6d696368** [comment]
I just ran into the same problem. Trying to `"Extract and Import"` a encrypted ZIP embedded as a resource in a binary I get:
```
Error opening filesystem for .rsrc_[004100f0,00759724]_5611302014014238546.tmp
java.util.zip.ZipException: invalid CEN header (encrypted entry)
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1529)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1495)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1268)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1231)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:726)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:843)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:246)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:176)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:190)
	at ghidra.file.formats.zip.ZipFileSystem.mount(ZipFileSystem.java:72)
	at ghidra.file.formats.zip.ZipFileSystemFactory.create(ZipFileSystemFactory.java:39)
	at ghidra.file.formats.zip.ZipFileSystemFactory.create(ZipFileSystemFactory.java:27)
	at ghidra.formats.gfilesystem.factory.FileSystemFactoryMgr.mountUsingFactory(FileSystemFactoryMgr.java:180)
	at ghidra.formats.gfilesystem.factory.FileSystemFactoryMgr.probe(FileSystemFactoryMgr.java:345)
	at ghidra.formats.gfilesystem.FileSystemService.probeFileForFilesystem(FileSystemService.java:626)
	at ghidra.formats.gfilesystem.FileSystemService.probeFileForFilesystem(FileSystemService.java:565)
	at ghidra.plugins.fsbrowser.FileSystemBrowserPlugin.doOpenFilesystem(FileSystemBrowserPlugin.java:255)
	at ghidra.plugins.fsbrowser.FileSystemBrowserPlugin.lambda$openFileSystem$0(FileSystemBrowserPlugin.java:117)
	at ghidra.util.task.TaskLauncher$2.run(TaskLauncher.java:122)
	at ghidra.util.task.Task.monitoredRun(Task.java:128)
	at ghidra.util.task.TaskLauncher.lambda$startBackgroundThread$2(TaskLauncher.java:315)
	at java.base/java.lang.Thread.run(Thread.java:834)

---------------------------------------------------
Build Date: 2019-Apr-03 1342 EDT
Ghidra Version: 9.0.2
Java Home: /usr/lib/jvm/java-11-openjdk-11.0.2.7-0.el7_6.x86_64
JVM Version: Oracle Corporation 11.0.2
OS: Linux 3.10.0-957.10.1.el7.x86_64 amd64
Workstation: localhost
```
`java.util.zip` simply does not support encrypted ZIP's. It could potentially be replaced with something like e.g. TrueZIP (https://christian-schlichtherle.bitbucket.io/truezip/).
However, given that `java.util.zip` is imported 32 times (https://github.com/NationalSecurityAgency/ghidra/search?p=4&q=%22java.util.zip%22&unscoped_q=%22java.util.zip%22) this is a rather bigger change to properly replace `java.util.zip` with something supporting encrypted ZIPs.

But I would also like to see that feature.

**Comment by tatarize** [comment]
His suggestion is also to do a basic dictionary attack on the zip too. I'm not sure TrueZip has that.

**Comment by slw07g** [comment]
Haven't tested this code, but this might be useful https://github.com/r331/memzipenc
