### ISSUE TITLE
Importing file fails on latest version

### ISSUE THREAD

**Issue by martmists-gh** [NationalSecurityAgency/ghidra#3781]
**Describe the bug**
```
Could not initialize class ghidra.formats.gfilesystem.factory.FileSystemFactoryMgr$Singleton
java.lang.NoClassDefFoundError: Could not initialize class ghidra.formats.gfilesystem.factory.FileSystemFactoryMgr$Singleton
	at ghidra.formats.gfilesystem.factory.FileSystemFactoryMgr.getInstance(FileSystemFactoryMgr.java:46)
	at ghidra.formats.gfilesystem.FileSystemService.<init>(FileSystemService.java:144)
	at ghidra.formats.gfilesystem.FileSystemService.<init>(FileSystemService.java:159)
	at ghidra.formats.gfilesystem.FileSystemService.getInstance(FileSystemService.java:63)
	at ghidra.plugin.importer.ImporterPlugin.importFile(ImporterPlugin.java:177)
	at ghidra.plugin.importer.ImporterPlugin.doSingleImportAction(ImporterPlugin.java:346)
	at ghidra.plugin.importer.ImporterPlugin$1.actionPerformed(ImporterPlugin.java:216)
	at docking.DockingActionProxy.actionPerformed(DockingActionProxy.java:47)
	at docking.MenuBarMenuHandler.lambda$processMenuAction$0(MenuBarMenuHandler.java:64)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2021-Dec-11 0226 CET
Ghidra Version: 10.1
Java Home: /usr/lib/jvm/java-11-openjdk
JVM Version: Oracle Corporation 11.0.13
OS: Linux 5.15.10-arch1-1 amd64
Workstation: baryon
```

**To Reproduce**
1. Create a new project
2. Attempt to import a file

**Expected behavior**
I get a prompt for configuring the file import

**Screenshots**
![Screenshot_20211219_203628](https://user-images.githubusercontent.com/16361449/146688400-ac78c94c-0e9a-4b30-8021-e362ab176222.png)

**Environment (please complete the following information):**
 - OS: Arch Linux x64
 - Java Version: OpenJDK 11.0.13
 - Ghidra Version: 10.1
 - Ghidra Origin: Arch Community Repository (<https://archlinux.org/packages/community/x86_64/ghidra/>)

**Comment by martmists-gh** [comment]
Related error earlier when clicking "Import File" (swapped to adoptopenjdk 16 to see if that worked, same error occurred on openjdk 11):
```
java.lang.ExceptionInInitializerError
	at ghidra.formats.gfilesystem.factory.FileSystemFactoryMgr.getInstance(FileSystemFactoryMgr.java:46)
	at ghidra.formats.gfilesystem.FileSystemService.<init>(FileSystemService.java:144)
	at ghidra.formats.gfilesystem.FileSystemService.<init>(FileSystemService.java:159)
	at ghidra.formats.gfilesystem.FileSystemService.getInstance(FileSystemService.java:63)
	at ghidra.plugin.importer.ImporterUtilities.<clinit>(ImporterUtilities.java:76)
	at ghidra.plugin.importer.ImporterPlugin.initializeChooser(ImporterPlugin.java:315)
	at ghidra.plugin.importer.ImporterPlugin.doSingleImportAction(ImporterPlugin.java:331)
	at ghidra.plugin.importer.ImporterPlugin$1.actionPerformed(ImporterPlugin.java:216)
	at docking.DockingActionProxy.actionPerformed(DockingActionProxy.java:47)
	at docking.MenuBarMenuHandler.lambda$processMenuAction$0(MenuBarMenuHandler.java:64)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.TypeNotPresentException: Type [unknown] not present
	at java.base/sun.reflect.annotation.TypeNotPresentExceptionProxy.generateException(TypeNotPresentExceptionProxy.java:47)
	at java.base/sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:88)
	at jdk.proxy2/jdk.proxy2.$Proxy19.factory(Unknown Source)
	at ghidra.formats.gfilesystem.factory.FileSystemInfoRec.fromClass(FileSystemInfoRec.java:70)
	at ghidra.formats.gfilesystem.factory.FileSystemFactoryMgr.addFactory(FileSystemFactoryMgr.java:74)
	at ghidra.formats.gfilesystem.factory.FileSystemFactoryMgr.<init>(FileSystemFactoryMgr.java:68)
	at ghidra.formats.gfilesystem.factory.FileSystemFactoryMgr$Singleton.<clinit>(FileSystemFactoryMgr.java:53)
	... 23 more
Caused by: java.lang.NoClassDefFoundError: ghidra/formats/gfilesystem/factory/GFileSystemFactoryFull
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:512)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:420)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:414)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:413)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at java.base/sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:440)
	at java.base/sun.reflect.annotation.AnnotationParser.parseClassValue(AnnotationParser.java:421)
	at java.base/sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:350)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:287)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:121)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73)
	at java.base/java.lang.Class.createAnnotationData(Class.java:3997)
	at java.base/java.lang.Class.annotationData(Class.java:3986)
	at java.base/java.lang.Class.getAnnotation(Class.java:3869)
	at ghidra.util.classfinder.ExtensionPointProperties$Util.isExcluded(ExtensionPointProperties.java:64)
	at ghidra.util.classfinder.ClassFinder.isClassOfInterest(ClassFinder.java:202)
	at ghidra.util.classfinder.ClassFinder.loadExtensionPoint(ClassFinder.java:122)
	at ghidra.util.classfinder.ClassJar.processClassFiles(ClassJar.java:177)
	at ghidra.util.classfinder.ClassJar.scanJar(ClassJar.java:83)
	at ghidra.util.classfinder.ClassJar.<init>(ClassJar.java:60)
	at ghidra.util.classfinder.ClassFinder.initialize(ClassFinder.java:66)
	at ghidra.util.classfinder.ClassFinder.<init>(ClassFinder.java:44)
	at ghidra.util.classfinder.ClassSearcher.search(ClassSearcher.java:259)
	at ghidra.framework.HeadlessGhidraApplicationConfiguration.performClassSearching(HeadlessGhidraApplicationConfiguration.java:76)
	at ghidra.framework.HeadlessGhidraApplicationConfiguration.initializeApplication(HeadlessGhidraApplicationConfiguration.java:40)
	at ghidra.framework.GhidraApplicationConfiguration.initializeApplication(GhidraApplicationConfiguration.java:59)
	at ghidra.framework.Application.initializeApplication(Application.java:115)
	at ghidra.GhidraRun.lambda$launch$1(GhidraRun.java:77)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.ClassNotFoundException: ghidra.formats.gfilesystem.factory.GFileSystemFactoryFull
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 39 more

---------------------------------------------------
Build Date: 2021-Dec-11 0226 CET
Ghidra Version: 10.1
Java Home: /usr/lib/jvm/java-16-adoptopenjdk
JVM Version: Eclipse Foundation 16.0.2
OS: Linux 5.15.10-arch1-1 amd64
Workstation: baryon
```

**Comment by dev747368** [comment]
You probably have a non-standard GFileSystem (from a custom extension or plugin) installed that is built against the previous version of Ghidra.

**Comment by martmists-gh** [comment]
It seems to only exist in Base.jar:
```
$ cd /opt/ghidra
$ grep -i "ghidra/formats/gfilesystem" **/*.jar
grep: Ghidra/Features/Base/lib/Base.jar: binary file matches
$
```

**Comment by dev747368** [comment]
I'm not sure what you were explaining there, but the "GFileSystemFactoryFull" interface was deleted between 10.0 and 10.1.

Try installing/unpacking a fresh copy of ghidra / removing any extensions trying your test again.

**Comment by astrelsky** [comment]
> You probably have a non-standard GFileSystem (from a custom extension or plugin) installed that is built against the previous version of Ghidra.
> 

Any pointers on upgrading things that were using those? I was caught off guard by their removal haven't wrapped my head around it yet. I don't remember what I used as an example the first time.

**Comment by dev747368** [comment]
Sure.  GFileSystemFactoryByteProvider is the newer interface.  There are a few methods on the base GFileSystem interface that have changed as well, to remove File / InputStreams from method signatures and replace them with ByteProviders.

If the file system that you are having an issue with is hosted on github, drop me a pointer to it and I can eye ball it.

**Comment by astrelsky** [comment]
> GFileSystemFactoryByteProvider

That little bit seems to have been enough to push me in the right direction. Only thing I'm left with is what to use for `GFileSystem::getName` since `GFileSystemFactoryByteProvider::create` doesn't receive the `containerFSRL` parameter anymore.

**Comment by dev747368** [comment]
@astrelsky - I wouldn't recommend casting the ByteProvider to anything.  Typically you would get the name from the FSRL of the file system itself.

https://github.com/NationalSecurityAgency/ghidra/blob/436bb4873e8571b87a4d785bb828d9bf772b4867/Ghidra/Features/FileFormats/src/main/java/ghidra/file/formats/coff/CoffArchiveFileSystem.java#L69-L71

or if there is more info you want to include:

https://github.com/NationalSecurityAgency/ghidra/blob/436bb4873e8571b87a4d785bb828d9bf772b4867/Ghidra/Features/FileFormats/src/main/java/ghidra/file/formats/ext4/Ext4FileSystem.java#L368-L371

**Comment by astrelsky** [comment]
> @astrelsky - I wouldn't recommend casting the ByteProvider to anything. Typically you would get the name from the FSRL of the file system itself.
> 
> https://github.com/NationalSecurityAgency/ghidra/blob/436bb4873e8571b87a4d785bb828d9bf772b4867/Ghidra/Features/FileFormats/src/main/java/ghidra/file/formats/coff/CoffArchiveFileSystem.java#L69-L71
> 
> or if there is more info you want to include:
> 
> https://github.com/NationalSecurityAgency/ghidra/blob/436bb4873e8571b87a4d785bb828d9bf772b4867/Ghidra/Features/FileFormats/src/main/java/ghidra/file/formats/ext4/Ext4FileSystem.java#L368-L371

I did not realize that would provide what I was looking for. I had tried `fsrl.getName()` but it returns null. Thank you!
