### ISSUE TITLE
Uncaught Exception on right-click

### ISSUE THREAD

**Issue by jibaer-izw** [NationalSecurityAgency/ghidra#3825]
On right-click into the listing view i get an uncaught exception. 

Everything worked fine until i added additional memory references. 

Error Details:

Not a valid Address on instruction at 8cb6
ghidra.util.exception.AssertException: Not a valid Address on instruction at 8cb6
	at ghidra.program.util.SymbolicPropogator.applyPcode(SymbolicPropogator.java:1006)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:515)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:411)
	at ghidra.program.util.SymbolicPropogator.flowConstants(SymbolicPropogator.java:204)
	at ghidra.app.cmd.function.CallDepthChangeInfo.followFlows(CallDepthChangeInfo.java:733)
	at ghidra.app.cmd.function.CallDepthChangeInfo.initialize(CallDepthChangeInfo.java:170)
	at ghidra.app.cmd.function.CallDepthChangeInfo.<init>(CallDepthChangeInfo.java:91)
	at ghidra.app.plugin.core.references.CreateDefaultReferenceAction.isEnabledForContext(CreateDefaultReferenceAction.java:151)
	at ghidra.app.context.ListingContextAction.isEnabledForContext(ListingContextAction.java:37)
	at docking.PopupActionManager.populatePopupMenuActions(PopupActionManager.java:143)
	at docking.PopupActionManager.createPopupMenu(PopupActionManager.java:104)
	at docking.PopupActionManager.popupMenu(PopupActionManager.java:84)
	at docking.ActionToGuiMapper.showPopupMenu(ActionToGuiMapper.java:133)
	at docking.DockableComponent.showContextMenu(DockableComponent.java:173)
	at docking.DockableComponent$1.mouseReleased(DockableComponent.java:75)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6614)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6379)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4990)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2769)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4822)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2021-Dec-21 1319 EST
Ghidra Version: 10.1.1
Java Home: C:\Java\bellsoft-jdk-15.0.1-full-x64
JVM Version: BellSoft 15.0.1
OS: Windows 10 10.0 amd64
Workstation: DESKTOP-E2QS3BD

**Comment by emteere** [comment]
What type of memory reference did you add to the branch at 0x8cb6?
Could it have been a reference to memory mapped register space, or a register space?

**Comment by jibaer-izw** [comment]
My project is a disassemble of 6809 code. The error happens on multiple locations that uses the indexed addressing mode of the 6809.

**Comment by jibaer-izw** [comment]
All Refences are put on by Ghidra by the disassemble command. and most is Garbage. All instructions use the 'indexed' addressing mode of the 6809-porcessor. In Detail:

`8c70 ad 9f 00 25             JSR                        [MIDI-Tx-Func-Call-2]`
The label MIDI-Tx-Func-Call-2 is at 8c74. With this Ghidra produces the disassemble JSR [0x8c74], that is wrong. Right would be JSR [0x0025] : Call subroutine with the address stored in 0x0025

`8cb6 6e 9f 00 1c             JMP                        [LAB_8cba]`
In this also the the referenced address is wrong. Ghidra write JMP [0x8cba], right would be JMP [0x001c]: Jump to address stored in 0x001c

`ROM-LO-0::74a5 6e 95                   JMP                        [B,X]`
This means jump to address stored in address B+X (B and X are registers. The disassemble is right, but i get the uncaught exception.

`a46e 6e c4                   JMP                        ,U`
This means jump to address stored in U (U is a are registers. The disassemble is right, but i get the uncaught exception.

`f309 6e b8 92                JMP                        [-0x6e,Y]`
This means, jump to address stored in address Y-0x6e (Y is a register). The disassemble is right, but i get the uncaught exception.

All the exception did not come instantly, but after some time of working (creating references, naming labels, etc ) on the project. And they come not all at one time. After 'fixing' one, i could work some time before the next exception happend.

It was not possible to work further without converting the failing instructions to 'data'.

**Comment by emteere** [comment]
Great info, that gets me to problem.  The exception was a symptom of the disease.  Will take a closer look at this and also make the exception a warning instead of an Assert Exception so it is easier to diagnose in the future.

**Comment by emteere** [comment]
We didn't change the error from an assert, however the issue should be solved for the 6809 with a fix in patch going into the next release.
Both JSR/JUMP instructions were jumping directly to the address of the unique variable instead of indirectly to the value in the unique variable.

**Comment by emteere** [comment]
Fixed in upcoming 10.1.2

**Comment by ryanmkurtz** [comment]
Fixed by 97f6dd1313dc9289cf563dc3c45304ea6efbb583
