### ISSUE TITLE
Ghidra cannot import binary with exotic section names

### ISSUE THREAD

**Issue by 0reilly** [NationalSecurityAgency/ghidra#3876]
**Describe the bug**
While analyzing the DRM circumvention employed by a cracker of a clients application, Ghidra rejected opening the respective program when trying to verify its block names.

The program is read properly by `objdump -d` and `objdump -s`, even though the block names are garbled in the output.

Example output in `objdump -d`:

```
Disassembly of section 
???
???
???
???,
???
???
???
???:

0000000000001160 <
???
???
???
???>:
    1160: 59                           	popq	%rcx
    1161: 44 85 e9                     	testl	%r13d, %ecx
    1164: e4 8b                        	inb	$139, %al
    1166: 24 0c                        	andb	$12, %al
    1168: 0c 51                        	orb	$81, %al
    116a: cf                           	iretl
...
```

hopper disassembler reports the respective section names to be:

`0x0A, -16, -5, -10, 0x0A, -3, -7, -1, 0x0A, -3, -14, -1, 0x0A, -11, -9, -15,`
`0x0A, -4, -4, -2, 0x0A, -10, -7, -10, 0x0A, -13, -11, -15, 0x0A, -7, -13, -12,`
`0x0A, -13, -16, -3, 0x0A, -7, -15, -13, 0x0A, -4, -15, -2, 0x0A, -14, -2, -9,`
`0x0A, -10, -9, -5, 0x0A, -9, -16, -2, 0x0A, -5, -13, -1, 0x0A, -8, -4, -16,`

etc.

Based on the values displayed in hopper I assume the individual bytes are wrapped and thus are displayed as negative values. The names are either Chinese or deliberately malformed to prevent disassembly.

**To Reproduce**
1. Attempt to import this binary.

**Expected behavior**
Should correctly import the binary, even with garbled names.

**Screenshots**
<img width="612" alt="Screen Shot 2022-01-17 at 11 57 52 AM" src="https://user-images.githubusercontent.com/16636934/149810698-4335f535-1d51-477a-945c-8c3cd2eb9dc8.png">
<img width="942" alt="Screen Shot 2022-01-17 at 11 58 39 AM" src="https://user-images.githubusercontent.com/16636934/149810709-dc0797fa-f0b4-4a2e-8d62-92f383bbfa3b.png">

**Attachments**
Displayed log:

```
java.io.IOException: java.lang.IllegalArgumentException: Invalid block name: ���
���
���
���
	at ghidra.app.util.opinion.MachoLoader.load(MachoLoader.java:113)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:404)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:350)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Invalid block name: ���
���
���
���
	at ghidra.program.database.mem.MemoryMapDB.checkBlockName(MemoryMapDB.java:814)
	at ghidra.program.database.mem.MemoryBlockDB.setName(MemoryBlockDB.java:175)
	at ghidra.app.util.opinion.MachoProgramBuilder.createMemoryBlock(MachoProgramBuilder.java:368)
	at ghidra.app.util.opinion.MachoProgramBuilder.processMemoryBlocks(MachoProgramBuilder.java:272)
	at ghidra.app.util.opinion.MachoProgramBuilder.build(MachoProgramBuilder.java:117)
	at ghidra.app.util.opinion.MachoProgramBuilder.buildProgram(MachoProgramBuilder.java:102)
	at ghidra.app.util.opinion.MachoLoader.load(MachoLoader.java:107)
	... 11 more
```

The binary in question: [libConfigurer64.dylib.zip](https://github.com/NationalSecurityAgency/ghidra/files/7883616/libConfigurer64.dylib.zip).

**Environment (please complete the following information):**
 - OS: macOS 12.1
 - Java Version: openjdk 17.0.1 2021-10-19
 - Ghidra Version: Ghidra 10.1.1 PUBLIC
 - Ghidra Origin: official distro

**Comment by ryanmkurtz** [comment]
It should be an easy fix to sanitize the block names in the MachoLoader, prior to creating the memory blocks.

**Comment by ryanmkurtz** [comment]
Getting past the section names issue reveals other problems though.

**Comment by 19h** [comment]
This has been really painful for us. We have been seeing more and more samples in the wild using this to prevent disassembly. IDA can disassemble this, but it replaces the function names with rather meaningless ASCII characters. Since we don't know if these characters were added intentionally to mitigate disassembly, or whether these are legit function names by Chinese programmers, replacing the characters with ASCII characters seems suboptimal.

**Comment by M-a-r-k** [comment]
I seem to have come across this issue, though in my case the block name shown is a plain ASCII string.

The executable is inside this .pkg file:
https://www.mediafire.com/file/fuusfex6d3l0nny/OnLive_Setup.pkg/file

To unpack it on Windows, 7-Zip can unpack the outer archive, then in the onlive.pkg subdirectory, "Payload" is a gzip-compressed CPIO archive which 7-Zip can also unpack. The executable is in OnLive.app/Contents/MacOS/OnLive

Ghidra detects format Mac OS X Mach-O, x86:LE:32:default:gcc. Then it reports

Error importing file: OnLive
```
java.lang.IllegalArgumentException: Invalid block name: __DATA5LI3O
java.io.IOException: java.lang.IllegalArgumentException: Invalid block name: __DATA5LI3O
	at ghidra.app.util.opinion.MachoLoader.load(MachoLoader.java:109)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:724)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:98)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:126)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:368)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Invalid block name: __DATA5LI3O
	at ghidra.program.database.mem.MemoryMapDB.checkBlockName(MemoryMapDB.java:826)
	at ghidra.program.database.mem.MemoryMapDB.createInitializedBlock(MemoryMapDB.java:655)
	at ghidra.app.util.MemoryBlockUtils.createInitializedBlock(MemoryBlockUtils.java:227)
	at ghidra.app.util.opinion.MachoProgramBuilder.createMemoryBlock(MachoProgramBuilder.java:353)
	at ghidra.app.util.opinion.MachoProgramBuilder.processMemoryBlocks(MachoProgramBuilder.java:266)
	at ghidra.app.util.opinion.MachoProgramBuilder.build(MachoProgramBuilder.java:127)
	at ghidra.app.util.opinion.MachoProgramBuilder.buildProgram(MachoProgramBuilder.java:113)
	at ghidra.app.util.opinion.MachoLoader.load(MachoLoader.java:98)
	... 11 more
```

**Comment by M-a-r-k** [comment]
Based on strings inside it, the executable I looked at could be protected/obfuscated by a protection system called InterLok.

**Comment by M-a-r-k** [comment]
Regarding the OnLive example above, Ghidra can now load it, showing an entry `__INVALID.6` in the Program Trees window. I wonder though, was `__DATA5LI3O` actually an invalid block name?

**Comment by ryanmkurtz** [comment]
Can you post the bytes of the `__DATA5LI3O` string from both the `SegmentCommand` as well as the `Section`?

**Comment by M-a-r-k** [comment]
I'm not sure if there's a Windows program to parse Mach-O file structure, but I loaded the Mac OS X OnLive program into a hex editor. It turns out that string has a zero byte in the middle: so `__DATA` then a zero byte then `5LI3O`. In hex:
`5F 5F 44 41 54 41 00 35 4C 49 33 4F 00 00 00 00`

Maybe the Mac OS X loader just treats that as a C string, i.e. ignores the trailing 5LI3O characters?

The bytes surrounding that string are (based on what Wikipedia says about Mach-O):
```
Raw		As int32		Comment
01000000	0x1		Command type (segment load)
38000000	0x38		Command size
5F5F4441 54410035 4C49334F 00000000	Segment name : "__DATA" 0x00 "5LI3O"
00B06600	0x66B000	Address
00402100	0x214000	Address size
00206500	0x652000	File offset
00402100	0x214000	Size (bytes from file offset)
07000000	0x7		Maximum virtual memory protections
07000000	0x7		Initial virtual memory protections
00000000	0		Number of sections
00000000	0		Flag32
```

**Comment by ryanmkurtz** [comment]
> Maybe the Mac OS X loader just treats that as a C string, i.e. ignores the trailing 5LI3O characters?

That's possible.  Our Program Tree won't like duplicate section names though, so I think I'll just replace `\0` with `_`.  Could be useful to see the hidden bit.

Thanks for the bytes.

**Comment by M-a-r-k** [comment]
If anyone ever feels like investigating that further, the download link for OnLive_Setup.pkg in [my comment above](https://github.com/NationalSecurityAgency/ghidra/issues/3876#issuecomment-1386035258) still works.

**Comment by ryanmkurtz** [comment]
@M-a-r-k Your binary should now load in `master`.
