### ISSUE TITLE
error importing file ("Cannot read past EOF")

### ISSUE THREAD

**Issue by blackgamma7** [NationalSecurityAgency/ghidra#3911]
**Describe the bug**
Trying to load a certain file gives the following error message: "Unable to read past EOF: 1155072, 272
```
java.io.IOException: Unable to read past EOF: 1155072, 272
	at ghidra.app.util.bin.FileByteProvider.ensureBounds(FileByteProvider.java:267)
	at ghidra.app.util.bin.FileByteProvider.readBytes(FileByteProvider.java:121)
	at ghidra.formats.gfilesystem.RefdByteProvider.readBytes(RefdByteProvider.java:91)
	at ghidra.app.util.bin.BinaryReader.readByteArray(BinaryReader.java:743)
	at ghidra.app.util.bin.format.pe.debug.DebugDirectory.initDebugDirectory(DebugDirectory.java:118)
	at ghidra.app.util.bin.format.pe.debug.DebugDirectory.createDebugDirectory(DebugDirectory.java:81)
	at ghidra.app.util.bin.format.pe.debug.DebugDirectoryParser.initDebugDirectoryParser(DebugDirectoryParser.java:113)
	at ghidra.app.util.bin.format.pe.debug.DebugDirectoryParser.createDebugDirectoryParser(DebugDirectoryParser.java:98)
	at ghidra.app.util.bin.format.pe.DebugDataDirectory.parse(DebugDataDirectory.java:73)
	at ghidra.app.util.bin.format.pe.DataDirectory.processDataDirectory(DataDirectory.java:80)
	at ghidra.app.util.bin.format.pe.DebugDataDirectory.initDebugDataDirectory(DebugDataDirectory.java:58)
	at ghidra.app.util.bin.format.pe.DebugDataDirectory.createDebugDataDirectory(DebugDataDirectory.java:48)
	at ghidra.app.util.bin.format.pe.OptionalHeaderImpl.processDataDirectories(OptionalHeaderImpl.java:377)
	at ghidra.app.util.opinion.PeLoader.load(PeLoader.java:127)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:404)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:350)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)"
```
**To Reproduce**
1 Import File
2. Select File to import (in this case, one that is otherwise functioning and intact)
3. ok

**Expected behavior**
The item would load into the project as normal -there is no issue with the drive or file.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 13.0.1
 - Ghidra Version: 10.1.1
 - Ghidra Origin: Github releases

**Additional context**

**Comment by ryanmkurtz** [comment]
Can you provide the binary please?

**Comment by ryanmkurtz** [comment]
Will reopen if I get the binary.

**Comment by SID37** [comment]
I got the same error for the file CleanSlate_AMDfix.exe

https://conspiracy.hu/get/67/cns!cns-AMDfix.zip

Environment:

- OS: Windows 11
- Java Version: 19.0.1
- Ghidra Version: 10.2
- Ghidra Origin: Github releases

**Comment by ryanmkurtz** [comment]
@SID37 can you please make a new ticket?

**Comment by SID37** [comment]
https://github.com/NationalSecurityAgency/ghidra/issues/4733
