### ISSUE TITLE
Ghidra 10.1 No longer supports wsl drive mounts

### ISSUE THREAD

**Issue by cwgreene** [NationalSecurityAgency/ghidra#3912]
**Describe the bug**
Until version 10.0 ghidra was able to load files on wsl mounts with paths like:

\\wsl.localhost\Ubuntu-18.04\home\froeb\ctfs\ctfarchive\realworldctf2022

Version 10.1 no longer supports this.

**To Reproduce**
1. Open a wsl directory using explorer.exe. Copy the path
1. Go to 'Import File'
3. Paste the path into the file. Select a binary in this directory.

**Expected behavior**
The binary is loaded by ghidra.

**Actual**
An error dialog appears.
```
\wsl.localhost\Ubuntu-18.04\home\froeb\ctfs\ctfarchive\realworldctf2022\embryoio_level79 (The system cannot find the path specified)
java.io.FileNotFoundException: \wsl.localhost\Ubuntu-18.04\home\froeb\ctfs\ctfarchive\realworldctf2022\embryoio_level79 (The system cannot find the path specified)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at ghidra.app.util.bin.FileByteProvider.<init>(FileByteProvider.java:57)
	at ghidra.formats.gfilesystem.LocalFileSystem.getByteProvider(LocalFileSystem.java:258)
	at ghidra.formats.gfilesystem.LocalFileSystem.getByteProvider(LocalFileSystem.java:253)
	at ghidra.formats.gfilesystem.FileSystemService.getByteProvider(FileSystemService.java:364)
	at ghidra.formats.gfilesystem.FileSystemService.isFileFilesystemContainer(FileSystemService.java:603)
	at ghidra.plugin.importer.ImporterUtilities.showImportDialog(ImporterUtilities.java:176)
	at ghidra.plugin.importer.ImporterUtilities.lambda$showImportDialog$0(ImporterUtilities.java:143)
	at ghidra.util.task.TaskLauncher$2.run(TaskLauncher.java:117)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

---------------------------------------------------
Build Date: 2021-Dec-10 1523 EST
Ghidra Version: 10.1
Java Home: C:\Program Files\Amazon Corretto\jdk11.0.10_9
JVM Version: Amazon.com Inc. 11.0.10
OS: Windows 10 10.0 amd64
```

**Screenshots**
![image](https://user-images.githubusercontent.com/135558/150744037-d55da3eb-3406-4693-b29f-831f66d1603f.png)

**Environment (please complete the following information):**
 - OS:Windows 10 10.0 amd64
 - Java Version: 11.0.10
 - Ghidra Version: 10.1
 - Ghidra Origin Github

**Comment by cwgreene** [comment]
Possibly relevant: The path should be

`\\wsl.localhost\Ubuntu-18.04\home\froeb\ctfs\ctfarchive\realworldctf2022`

But the path in the error only leads with a single backslash:

`\wsl.localhost\Ubuntu-18.04\home\froeb\ctfs\ctfarchive\realworldctf2022`

**Comment by dev747368** [comment]
how is the file being selected in Ghidra?  File browser, drag-n-drop, ???

**Comment by dev747368** [comment]
doh, you specified pasting the path.  Did the pasted path have the double leading backslash?

Can you try drag-and-drop from the explorer to the project window to start the import?
