### ISSUE TITLE
headlessAnalysis fails with jar file built from ./support/buildGhidraJar in 10.1.2

### ISSUE THREAD

**Issue by erhlee-bird** [NationalSecurityAgency/ghidra#3961]
**Describe the bug**
A clear and concise description of the bug.

I typically build a single jar file using `support/buildGhidraJar` and have done so for previous versions of Ghidra.
I think around the time the Debugger was introduced this stopped working and I see crashes when running headless analysis.

**To Reproduce**

1. I downloaded the 10.1.2 release jar file from GitHub
2. I unzip the archive and run `./support/buildGhidraJar`
3. I run `java -jar ghidra.jar ... -import /bin/sh` and get a crash.

```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
INFO  Using log config file: jar:file:/tmp/ghidra_10.1.2_PUBLIC/ghidra.jar!/generic.log4j.xml (LoggingInitialization)  
INFO  Using log file: /home/user/.ghidra/.ghidra_10.1.2_PUBLIC/application.log (LoggingInitialization)  
Exception in thread "main" java.lang.NoClassDefFoundError: ghidra/app/plugin/core/byteviewer/AbstractByteViewerPlugin
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at ghidra.util.classfinder.ClassSearcher.loadExtensionClassesFromJar(ClassSearcher.java:329)
	at ghidra.util.classfinder.ClassSearcher.search(ClassSearcher.java:245)
	at ghidra.framework.HeadlessGhidraApplicationConfiguration.performClassSearching(HeadlessGhidraApplicationConfiguration.java:76)
	at ghidra.framework.HeadlessGhidraApplicationConfiguration.initializeApplication(HeadlessGhidraApplicationConfiguration.java:40)
	at ghidra.framework.Application.initializeApplication(Application.java:115)
	at ghidra.app.util.headless.HeadlessAnalyzer.getLoggableInstance(HeadlessAnalyzer.java:128)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:111)
	at ghidra.JarRun.main(JarRun.java:32)
Caused by: java.lang.ClassNotFoundException: ghidra.app.plugin.core.byteviewer.AbstractByteViewerPlugin
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 19 more
```

It looks like some class is dependent on the `AbstractByteViewerPlugin` class and being included in the default jar build while the ByteViewer is not.

```
$ cat Ghidra/Features/ByteViewer/Module.manifest
EXCLUDE FROM GHIDRA JAR: true
```

**Expected behavior**

I would expect the headless analyzer to work using the created jar file.

**Screenshots**

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: 11.0.13
 - Ghidra Version: 10.1.2
 - Ghidra Origin: GitHub release from this repository

**Additional context**

**Comment by dev747368** [comment]
I'm thinking its the Debugger modules that don't have the ```EXCLUDE FROM GHIDRA JAR: true``` in their Module.manifest that is causing the problem.

**Comment by ryanmkurtz** [comment]
We should really have some dependency checking when building the single jar.

**Comment by erhlee-bird** [comment]
@dev747368, adding that to the Debugger Module.manifest files gets my builds working again for now, thank you
