### ISSUE TITLE
when decompiling  chrome.dll, going to load pdb , process crashed 

### ISSUE THREAD

**Issue by avboy1337** [NationalSecurityAgency/ghidra#3987]
**Describe the bug**
A clear and concise description of the bug.
when loading pdb of chrome , such errors showed:
```
java.lang.reflect.InvocationTargetException
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1713)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:688)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:788)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:667)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:632)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:319)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.ArrayList.grow(ArrayList.java:239)
	at java.base/java.util.ArrayList.grow(ArrayList.java:244)
	at java.base/java.util.ArrayList.add(ArrayList.java:454)
	at java.base/java.util.ArrayList.add(ArrayList.java:467)
	at ghidra.app.util.bin.format.pdb2.pdbreader.symbol.InlinedFunctionCallsiteMsSymbol.<init>(InlinedFunctionCallsiteMsSymbol.java:55)
	at ghidra.app.util.bin.format.pdb2.pdbreader.SymbolParser.parseRecord(SymbolParser.java:595)
	at ghidra.app.util.bin.format.pdb2.pdbreader.SymbolParser.parse(SymbolParser.java:57)
	at ghidra.app.util.bin.format.pdb2.pdbreader.SymbolRecords.deserializeSymbolRecords(SymbolRecords.java:132)
	at ghidra.app.util.bin.format.pdb2.pdbreader.SymbolRecords.deserialize(SymbolRecords.java:93)
	at ghidra.app.util.bin.format.pdb2.pdbreader.PdbNewDebugInfo.deserializeAdditionalSubstreams(PdbNewDebugInfo.java:154)
	at ghidra.app.util.bin.format.pdb2.pdbreader.PdbDebugInfo.deserialize(PdbDebugInfo.java:124)
	at ghidra.app.util.bin.format.pdb2.pdbreader.AbstractPdb.deserializeSubstreams(AbstractPdb.java:534)
	at ghidra.app.util.bin.format.pdb2.pdbreader.AbstractPdb.deserialize(AbstractPdb.java:192)
	at pdb.LoadPdbTask.parseWithNewParser(LoadPdbTask.java:147)
	at pdb.LoadPdbTask$2.analysisWorkerCallback(LoadPdbTask.java:84)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1707)
	... 8 more
```

---------------------------------------------------
Build Date: 2022-Jan-25 1526 EST
Ghidra Version: 10.1.2
Java Home: C:\Program Files\Java\jdk-16
JVM Version: Oracle Corporation 16
OS: Windows Server 2019 10.0 amd64
Workstation: WIN-IO14N2MUHJD

**To Reproduce**
1. download chrome.dll.pdb from symbol server of chrome using windbg;
command is:
.sympath SRV*C:\symbols*https://msdl.microsoft.com/download/symbols;SRV*C:\symbols*https://chromium-browser-symsrv.commondatastorage.googleapis.com;
ld chrome*

2. use ghidra to open chrome.dll and not need to auto analysis
3. load pdb 

**Expected behavior**
no error

 - OS:win10 Server
 - Java Version: 1.16
 - Ghidra Version: latest download
 - Ghidra Origin: [e.g. official ghidra-sre.org distro, third party distro, locally built]

**Comment by dev747368** [comment]
Since the exception was ```java.lang.OutOfMemoryError: Java heap space```, could you include info about your pc, and how much memory Ghidra has available?  See Help -> Show VM Memory.

**Comment by avboy1337** [comment]
![image](https://user-images.githubusercontent.com/5463104/153745239-603f3338-4a6e-4276-addd-e2ad0522667d.png)

![image](https://user-images.githubusercontent.com/5463104/153745284-2730fbf9-0518-4b7d-95a0-644210207114.png)

I use the phisical Machine directly

**Comment by ghizard** [comment]
It seems that you have a decent machine.

At this time, it is difficult to process such large programs/PDBs.  The fundamental issue is the method we chose for this initial implementation of PDB Universal processing.  It will take a bit of work to change the processing model is on my list to evaluate how best to do this.

There have been a number of other issues generated regarding processing time and memory usage and some improvements have been made.  For example:
https://github.com/NationalSecurityAgency/ghidra/issues/2485
https://github.com/NationalSecurityAgency/ghidra/issues/3497

But the main issue is going to have to employ being more selective as to what gets loaded into memory and will likley need to resort to to using random access to the on-disc PDB.
