### ISSUE TITLE
ssh connect will fail with exception if user has ed25519 identities in ssh_config

### ISSUE THREAD

**Issue by mcr-ksh** [NationalSecurityAgency/ghidra#4006]
**Describe the bug**
cant connect to remote host when having ed25519 keys due to bug in jsch.

**To Reproduce**
1. add a ssh ed25519 key and "IdentityFile ~/.ssh/id_ed25519" to your ssh config.
2. open debugger and "GNU gdb via ssh"
3. ssh connection will fail will the following exception:

Caused by: com.jcraft.jsch.JSchException: invalid privatekey: [B@e4487af
    at com.jcraft.jsch.KeyPair.load(KeyPair.java:664)
    at com.jcraft.jsch.KeyPair.load(KeyPair.java:561)
    at com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:40)
    at com.jcraft.jsch.JSch.addIdentity(JSch.java:407)
    at com.jcraft.jsch.JSch.addIdentity(JSch.java:367)
    at org.eclipse.jgit.transport.JschConfigSessionFactory.getJSch(JschConfigSessionFactory.java:276)
    at org.eclipse.jgit.transport.JschConfigSessionFactory.createSession(JschConfigSessionFactory.java:220)
    at org.eclipse.jgit.transport.JschConfigSessionFactory.createSession(JschConfigSessionFactory.java:176)
    at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:110)

**Expected behavior**
can connect to remote host.

**Workaround**
use /etc/ssh/ssh_config and/or remove ed25519 keys.

**Screenshots**
see attachment.
![Screenshot 2022-02-17 at 10 40 03](https://user-images.githubusercontent.com/710460/154448852-3f211fac-7091-4225-8f1f-f4bf632ff316.png)

**Attachments**
https://stackoverflow.com/questions/53134212/invalid-privatekey-when-using-jsch

**Environment (please complete the following information):**
 - OS: macOS 12.2.1
Build Date: 2022-Jan-25 1526 EST
Ghidra Version: 10.1.2
Java Home: /Library/Java/JavaVirtualMachines/openjdk17-temurin/Contents/Home
JVM Version: Eclipse Adoptium 17.0.1
OS: Mac OS X 11.2 x86_64

**Comment by ucasqsl** [comment]
> Apologies for the slow response - is there a version of JSch that supports ed25519? I was under the impression that wasn't supported yet.

One is mentioned here https://github.com/gradle/gradle/issues/19028

**Comment by d-millar** [comment]
This looks promising - we’re considering it.
