### ISSUE TITLE
NullPointerException in DecompilerVariable.getOutputDataType() when using DecompilerDataTypeReferenceFinder

### ISSUE THREAD

**Issue by NeedsMoreFlux** [NationalSecurityAgency/ghidra#407]
When searching for references to a struct field in the decompiler, which runs `DecompilerDataTypeReferenceFinder`, a `NullPointerException` is thrown at https://github.com/NationalSecurityAgency/ghidra/blob/49c2010b63b56c8f20845f3970fedd95d003b1e9/Ghidra/Features/DecompilerDependent/src/main/java/ghidra/app/extension/datatype/finder/DecompilerVariable.java#L107 because the return value from `op.getOutput()` in the preceding line is `null`. Once this happens in a function, it appears to cancel reference finding for the rest of function, potentially resulting in references not being reported.

I've only been testing this on an ARM project, so I do not know if this exception is specific to the ARM decompiler or if it occurs on other processors as well. From what I could see debugging the issue, this seems to consistently happen on lines that involve a `volatile_write_4` of a constant value to a variable in memory. I'll try to trace out the call flow that leads to this exception with an example.

`DecompilerDataTypeReferenceFinder$DecompilerDataTypeFinder.matchUsage(DecompilerReference reference, List<DataTypeReference> results)` is called with a `VariableAccessDR` instance as the `reference` argument.

`reference.line` is a `ClangLine` instance for `19: write_volatile_4(REG_E0000000,1);`.

`reference.variable` is a `DecompilerVariableType` instance
 and `reference.variable.variable` is a `ClangVariableToken` for `REG_E0000000`, where `REG_E0000000` is the label for variable in memory at address `0xe0000000` marked as volatile.

`reference.variable.variable.op` is a `PcodeOpAST` with string representation `---  CALLOTHER (const, 0xa3, 4) , (ram, 0xe0000000, 1) , (const, 0x1, 4)`. I'm assuming that this is how the the `write_volatile_4` pseudo-function call is represented in P-code, but I'm not sure.

At this point, `reference.variable.variable.op.output` is `null`. The call stack from here proceeds like this: 
```	
DecompilerVariableType(DecompilerVariable).getOutputDataType(PcodeOp) line: 107
DecompilerVariableType(DecompilerVariable).getDataType() line: 84	
VariableAccessDR.matchesType(DecompilerVariable, DataType) line: 177	
VariableAccessDR.getMatchingVarialbe(DataType, DecompilerVariable, DecompilerVariable) line: 138	
VariableAccessDR.getMatch(DataType, String, DecompilerVariable, DecompilerVariable) line: 106	
VariableAccessDR.accumulateMatches(DataType, String, List<DataTypeReference>) line: 59
DecompilerDataTypeReferenceFinder$DecompilerDataTypeFinder.matchUsage(DecompilerReference, List<DataTypeReference>) line: 325
```

Now in `DecompilerVariableType.getOutputDataType(PcodeOp op)`, `op.getOutput()` returns `null`, so `Varnode output` is `null` and the attempt to call `output.getHigh()` throws the `NullPointerException`.

As a test, I tried adding a simple check of `if (output == null || output.getHigh() == null) { return null; }` before the `return output.getHigh().getDataType();` line in `DecompilerVariableType.getOutputDataType(PcodeOp op)`, and this seemed to help in that more references were found and no exception was thrown. However, I'm not sure if this is an appropriate solution or if there is a deeper problem causing `op.getOutput()` to return `null`.

Here's the full stack trace that gets logged to the console when I try searching for references to a struct field:

```
ERROR Encountered an exception decompiling functions java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at generic.concurrent.QResult.<init>(QResult.java:40)
	at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at ghidra.app.extension.datatype.finder.DecompilerVariable.getOutputDataType(DecompilerVariable.java:107)
	at ghidra.app.extension.datatype.finder.DecompilerVariable.getDataType(DecompilerVariable.java:84)
	at ghidra.app.extension.datatype.finder.VariableAccessDR.matchesType(VariableAccessDR.java:177)
	at ghidra.app.extension.datatype.finder.VariableAccessDR.getMatchingVarialbe(VariableAccessDR.java:138)
	at ghidra.app.extension.datatype.finder.VariableAccessDR.getMatch(VariableAccessDR.java:106)
	at ghidra.app.extension.datatype.finder.VariableAccessDR.accumulateMatches(VariableAccessDR.java:59)
	at ghidra.app.extension.datatype.finder.DecompilerDataTypeReferenceFinder$DecompilerDataTypeFinder.matchUsage(DecompilerDataTypeReferenceFinder.java:325)
	at ghidra.app.extension.datatype.finder.DecompilerDataTypeReferenceFinder$DecompilerDataTypeFinder.lambda$0(DecompilerDataTypeReferenceFinder.java:320)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at ghidra.app.extension.datatype.finder.DecompilerDataTypeReferenceFinder$DecompilerDataTypeFinder.searchDecompilation(DecompilerDataTypeReferenceFinder.java:320)
	at ghidra.app.extension.datatype.finder.DecompilerDataTypeReferenceFinder$DecompilerDataTypeFinder.findUsage(DecompilerDataTypeReferenceFinder.java:301)
	at ghidra.app.extension.datatype.finder.DecompilerDataTypeReferenceFinder$DecompilerDataTypeFinderQCallback.process(DecompilerDataTypeReferenceFinder.java:256)
	at ghidra.app.extension.datatype.finder.DecompilerDataTypeReferenceFinder$DecompilerDataTypeFinderQCallback.process(DecompilerDataTypeReferenceFinder.java:1)
	at ghidra.app.decompiler.parallel.DecompilerCallback.process(DecompilerCallback.java:80)
	at ghidra.app.decompiler.parallel.DecompilerCallback.process(DecompilerCallback.java:1)
	at generic.concurrent.ConcurrentQ$CallbackCallable.call(ConcurrentQ.java:655)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:70)
	... 3 more
```

Curiously, if I change the memory variable that causes the exception to non-volatile, I get the following different stack trace:

```
ERROR Encountered an exception decompiling functions java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at generic.concurrent.QResult.<init>(QResult.java:40)
	at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:72)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at ghidra.app.extension.datatype.finder.DecompilerReference.isEqual(DecompilerReference.java:108)
	at ghidra.app.extension.datatype.finder.VariableDR.accumulateMatches(VariableDR.java:62)
	at ghidra.app.extension.datatype.finder.DecompilerDataTypeReferenceFinder$DecompilerDataTypeFinder.matchUsage(DecompilerDataTypeReferenceFinder.java:325)
	at ghidra.app.extension.datatype.finder.DecompilerDataTypeReferenceFinder$DecompilerDataTypeFinder.lambda$0(DecompilerDataTypeReferenceFinder.java:320)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at ghidra.app.extension.datatype.finder.DecompilerDataTypeReferenceFinder$DecompilerDataTypeFinder.searchDecompilation(DecompilerDataTypeReferenceFinder.java:320)
	at ghidra.app.extension.datatype.finder.DecompilerDataTypeReferenceFinder$DecompilerDataTypeFinder.findUsage(DecompilerDataTypeReferenceFinder.java:301)
	at ghidra.app.extension.datatype.finder.DecompilerDataTypeReferenceFinder$DecompilerDataTypeFinderQCallback.process(DecompilerDataTypeReferenceFinder.java:256)
	at ghidra.app.extension.datatype.finder.DecompilerDataTypeReferenceFinder$DecompilerDataTypeFinderQCallback.process(DecompilerDataTypeReferenceFinder.java:1)
	at ghidra.app.decompiler.parallel.DecompilerCallback.process(DecompilerCallback.java:80)
	at ghidra.app.decompiler.parallel.DecompilerCallback.process(DecompilerCallback.java:1)
	at generic.concurrent.ConcurrentQ$CallbackCallable.call(ConcurrentQ.java:655)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:70)
	... 3 more
  (DecompilerDataTypeReferenceFinder.java:91)
```

And if I add the aforementioned `if (output == null || output.getHigh() == null) { return null; }` check to `DecompilerVariableType.getOutputDataType(PcodeOp op)`, no exception is thrown.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 x86_64
 - Java Version: 11.0.1
 - Ghidra Version: 9.0.1 and 9.0.2

**Comment by dragonmacher** [comment]
Thanks for the debug help.

The 'output' Varnode of the PcodeOp can be null when used with the 'write_volatile' pseudo operation, as is the case when writing to volatile memory.
