### ISSUE TITLE
Java Class Analyzer fails to import java class file

### ISSUE THREAD

**Issue by DspHack** [NationalSecurityAgency/ghidra#4089]
I have attempted to import a valid .class file. However, Ghidra does not detecting it as Java, and shows it as Raw binary, which prevents me from using the Java Class Analyzer on the file. 

To reproduce: 
1. Import included file: log4jLogEvent.class
2. Perform Auto analysis

**Expected behavior**
Class file should be loaded and functions found.

**Attachments**
[Log4jLogEvent.zip](https://github.com/NationalSecurityAgency/ghidra/files/8292573/Log4jLogEvent.zip)

**Environment (please complete the following information):**
 - OS: MS Windows 10
 - Java Version:   openjdk 11.0.14.1 2022-02-08 LTS
                           OpenJDK Runtime Environment Corretto-11.0.14.10.1 (build 11.0.14.1+10-LTS)
                           OpenJDK 64-Bit Server VM Corretto-11.0.14.10.1 (build 11.0.14.1+10-LTS, mixed mode)
 - Ghidra Version: 10.1.1 PUBLIC
 - Ghidra Origin: official ghidra-sre.org distro

Log file Snippet:
2022-03-17 15:55:41 DEBUG (ToolTaskManager) Thu Mar 17 15:55:41 EDT 2022 Background processing started...  
2022-03-17 15:55:41 DEBUG (ToolTaskManager) Thu Mar 17 15:55:41 EDT 2022 Exec Task Auto Analysis  
2022-03-17 15:55:41 DEBUG (AnalysisWorkerCommand) Invoking analysis worker (Java Class Analyzer): class ghidra.javaclass.analyzers.JavaAnalyzer  
2022-03-17 15:55:41 DEBUG (AutoAnalysisManager) Analysis worker completed (Java Class Analyzer): class ghidra.javaclass.analyzers.JavaAnalyzer  
2022-03-17 15:55:41 DEBUG (ToolTaskManager) Thu Mar 17 15:55:41 EDT 2022 Auto Analysis task finish (0.523 secs)  
2022-03-17 15:55:41 DEBUG (ToolTaskManager) Thu Mar 17 15:55:41 EDT 2022  Queue - Auto Analysis  
2022-03-17 15:55:41 DEBUG (ToolTaskManager) Thu Mar 17 15:55:41 EDT 2022  (0.0 secs)  
2022-03-17 15:55:41 DEBUG (ToolTaskManager) Thu Mar 17 15:55:41 EDT 2022 Auto Analysis task complete (0.545 secs)  
2022-03-17 15:55:41 DEBUG (ToolTaskManager) Thu Mar 17 15:55:41 EDT 2022 Background processing complete (0.545 secs)  
2022-03-17 15:56:06 INFO  (RecoveryMgr) Thu Mar 17 15:56:06 EDT 2022 Recovery snapshot created: C:\Users\xxxxx\xxxxx.rep\idata\09\~0000009b.db\snapshotA.grf  
2022-03-17 15:56:06 INFO  (RecoveryMgr) Thu Mar 17 15:56:06 EDT 2022 Recovery snapshot created: C:\Users\xxxxx\xxxxx.rep\idata\09\~0000009c.db\snapshotA.grf  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'Apply Data Archives' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'Basic Constant Reference Analyzer' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'Data Reference' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'Call Convention ID' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'Decompiler Switch Analysis' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'Embedded Media' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'Non-Returning Functions - Discovered' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'Demangler GNU' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'Reference' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'Create Address Tables' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'Call-Fixup Installer' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'Call-Fixup Installer' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'Disassemble Entry Points' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'Subroutine References' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'External Entry References' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'Subroutine References' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'Shared Return Calls' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'Shared Return Calls' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'Stack' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 WARN  (AnalysisScheduler) Analyzer 'ASCII Strings' for Log4jLogEvent.class disabled by PSPEC file override  
2022-03-17 16:03:13 ERROR (JavaClassUtil) Exception reading program bytes: Unable to read bytes at constantPool:00000000 ghidra.program.model.mem.MemoryAccessException: Unable to read bytes at constantPool:00000000
	at ghidra.program.database.mem.MemoryMapDB.getBytes(MemoryMapDB.java:1396)
	at ghidra.program.database.mem.MemoryMapDB.getBytes(MemoryMapDB.java:1365)
	at ghidra.javaclass.format.JavaClassUtil.isClassFile(JavaClassUtil.java:39)
	at ghidra.javaclass.analyzers.JavaAnalyzer.canAnalyze(JavaAnalyzer.java:90)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.initializeAnalyzers(AutoAnalysisManager.java:165)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.<init>(AutoAnalysisManager.java:147)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.getAnalysisManager(AutoAnalysisManager.java:983)
	at ghidra.app.plugin.core.analysis.AutoAnalysisPlugin.programOpened(AutoAnalysisPlugin.java:267)
	at ghidra.app.plugin.core.analysis.AutoAnalysisPlugin.processEvent(AutoAnalysisPlugin.java:251)
	at ghidra.framework.plugintool.Plugin.eventSent(Plugin.java:329)
	at ghidra.framework.plugintool.mgr.EventManager.sendEvents(EventManager.java:286)
	at ghidra.framework.plugintool.mgr.EventManager.lambda$new$3(EventManager.java:49)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.framework.plugintool.mgr.EventManager.fireEvent(EventManager.java:216)
	at ghidra.framework.plugintool.PluginTool.firePluginEvent(PluginTool.java:475)
	at ghidra.framework.plugintool.Plugin.firePluginEvent(Plugin.java:481)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.fireOpenEvents(MultiProgramManager.java:264)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.addProgram(MultiProgramManager.java:84)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.lambda$openProgram$6(ProgramManagerPlugin.java:473)
	at ghidra.util.Swing.lambda$runNow$2(Swing.java:227)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
 
2022-03-17 16:03:13 ERROR (JavaClassUtil) Exception reading program bytes: Unable to read bytes at constantPool:00000000 ghidra.program.model.mem.MemoryAccessException: Unable to read bytes at constantPool:00000000
	at ghidra.program.database.mem.MemoryMapDB.getBytes(MemoryMapDB.java:1396)
	at ghidra.program.database.mem.MemoryMapDB.getBytes(MemoryMapDB.java:1365)
	at ghidra.javaclass.format.JavaClassUtil.isClassFile(JavaClassUtil.java:39)
	at ghidra.javaclass.analyzers.JvmSwitchAnalyzer.canAnalyze(JvmSwitchAnalyzer.java:81)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.initializeAnalyzers(AutoAnalysisManager.java:165)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.<init>(AutoAnalysisManager.java:147)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.getAnalysisManager(AutoAnalysisManager.java:983)
	at ghidra.app.plugin.core.analysis.AutoAnalysisPlugin.programOpened(AutoAnalysisPlugin.java:267)
	at ghidra.app.plugin.core.analysis.AutoAnalysisPlugin.processEvent(AutoAnalysisPlugin.java:251)
	at ghidra.framework.plugintool.Plugin.eventSent(Plugin.java:329)
	at ghidra.framework.plugintool.mgr.EventManager.sendEvents(EventManager.java:286)
	at ghidra.framework.plugintool.mgr.EventManager.lambda$new$3(EventManager.java:49)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.framework.plugintool.mgr.EventManager.fireEvent(EventManager.java:216)
	at ghidra.framework.plugintool.PluginTool.firePluginEvent(PluginTool.java:475)
	at ghidra.framework.plugintool.Plugin.firePluginEvent(Plugin.java:481)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.fireOpenEvents(MultiProgramManager.java:264)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.addProgram(MultiProgramManager.java:84)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.lambda$openProgram$6(ProgramManagerPlugin.java:473)
	at ghidra.util.Swing.lambda$runNow$2(Swing.java:227)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
 
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'Apply Data Archives' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'Basic Constant Reference Analyzer' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'Data Reference' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'Call Convention ID' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'Decompiler Switch Analysis' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'Embedded Media' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'Non-Returning Functions - Discovered' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'Demangler GNU' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'Reference' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'Create Address Tables' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'Call-Fixup Installer' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'Call-Fixup Installer' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'Disassemble Entry Points' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'Subroutine References' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'External Entry References' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'Subroutine References' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'Shared Return Calls' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'Shared Return Calls' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'Stack' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 WARN  (AnalysisScheduler) Analyzer 'ASCII Strings' for Log4jLogEvent.class2 disabled by PSPEC file override  
2022-03-17 16:04:41 ERROR (JavaClassUtil) Exception reading program bytes: Unable to read bytes at constantPool:00000000 ghidra.program.model.mem.MemoryAccessException: Unable to read bytes at constantPool:00000000
	at ghidra.program.database.mem.MemoryMapDB.getBytes(MemoryMapDB.java:1396)
	at ghidra.program.database.mem.MemoryMapDB.getBytes(MemoryMapDB.java:1365)
	at ghidra.javaclass.format.JavaClassUtil.isClassFile(JavaClassUtil.java:39)
	at ghidra.javaclass.analyzers.JavaAnalyzer.canAnalyze(JavaAnalyzer.java:90)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.initializeAnalyzers(AutoAnalysisManager.java:165)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.<init>(AutoAnalysisManager.java:147)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.getAnalysisManager(AutoAnalysisManager.java:983)
	at ghidra.app.plugin.core.analysis.AutoAnalysisPlugin.programOpened(AutoAnalysisPlugin.java:267)
	at ghidra.app.plugin.core.analysis.AutoAnalysisPlugin.processEvent(AutoAnalysisPlugin.java:251)
	at ghidra.framework.plugintool.Plugin.eventSent(Plugin.java:329)
	at ghidra.framework.plugintool.mgr.EventManager.sendEvents(EventManager.java:286)
	at ghidra.framework.plugintool.mgr.EventManager.lambda$new$3(EventManager.java:49)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.framework.plugintool.mgr.EventManager.fireEvent(EventManager.java:216)
	at ghidra.framework.plugintool.PluginTool.firePluginEvent(PluginTool.java:475)
	at ghidra.framework.plugintool.Plugin.firePluginEvent(Plugin.java:481)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.fireOpenEvents(MultiProgramManager.java:264)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.addProgram(MultiProgramManager.java:84)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.lambda$openProgram$6(ProgramManagerPlugin.java:473)
	at ghidra.util.Swing.lambda$runNow$2(Swing.java:227)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
 
2022-03-17 16:04:41 ERROR (JavaClassUtil) Exception reading program bytes: Unable to read bytes at constantPool:00000000 ghidra.program.model.mem.MemoryAccessException: Unable to read bytes at constantPool:00000000
	at ghidra.program.database.mem.MemoryMapDB.getBytes(MemoryMapDB.java:1396)
	at ghidra.program.database.mem.MemoryMapDB.getBytes(MemoryMapDB.java:1365)
	at ghidra.javaclass.format.JavaClassUtil.isClassFile(JavaClassUtil.java:39)
	at ghidra.javaclass.analyzers.JvmSwitchAnalyzer.canAnalyze(JvmSwitchAnalyzer.java:81)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.initializeAnalyzers(AutoAnalysisManager.java:165)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.<init>(AutoAnalysisManager.java:147)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.getAnalysisManager(AutoAnalysisManager.java:983)
	at ghidra.app.plugin.core.analysis.AutoAnalysisPlugin.programOpened(AutoAnalysisPlugin.java:267)
	at ghidra.app.plugin.core.analysis.AutoAnalysisPlugin.processEvent(AutoAnalysisPlugin.java:251)
	at ghidra.framework.plugintool.Plugin.eventSent(Plugin.java:329)
	at ghidra.framework.plugintool.mgr.EventManager.sendEvents(EventManager.java:286)
	at ghidra.framework.plugintool.mgr.EventManager.lambda$new$3(EventManager.java:49)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.framework.plugintool.mgr.EventManager.fireEvent(EventManager.java:216)
	at ghidra.framework.plugintool.PluginTool.firePluginEvent(PluginTool.java:475)
	at ghidra.framework.plugintool.Plugin.firePluginEvent(Plugin.java:481)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.fireOpenEvents(MultiProgramManager.java:264)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.addProgram(MultiProgramManager.java:84)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.lambda$openProgram$6(ProgramManagerPlugin.java:473)
	at ghidra.util.Swing.lambda$runNow$2(Swing.java:227)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
 
2022-03-17 16:05:01 DEBUG (ToolTaskManager) Thu Mar 17 16:05:01 EDT 2022 Background processing started...  
2022-03-17 16:05:01 DEBUG (ToolTaskManager) Thu Mar 17 16:05:01 EDT 2022 Exec Task Auto Analysis  
2022-03-17 16:05:01 DEBUG (PackedDatabaseCache) Using cached packed database: C:\Users\xxxxx\ghidra_10.1.1_PUBLIC_20211221\ghidra_10.1.1_PUBLIC\Ghidra\Features\Base\data\typeinfo\generic\generic_clib.gdt  
2022-03-17 16:05:02 INFO  (AutoAnalysisManager) Analysis Log Messages
AggressiveInstructionFinder> Aggressive Instruction Finder Not Run.  Too few functions defined for proper analysis!
  
2022-03-17 16:05:02 DEBUG (ToolTaskManager) Thu Mar 17 16:05:02 EDT 2022 Auto Analysis task finish (0.225 secs)  
2022-03-17 16:05:02 DEBUG (ToolTaskManager) Thu Mar 17 16:05:02 EDT 2022  Queue - Auto Analysis  
2022-03-17 16:05:02 DEBUG (ToolTaskManager) Thu Mar 17 16:05:02 EDT 2022  (0.016 secs)  
2022-03-17 16:05:02 DEBUG (ToolTaskManager) Thu Mar 17 16:05:02 EDT 2022 Auto Analysis task complete (0.312 secs)  
2022-03-17 16:05:02 DEBUG (ToolTaskManager) Thu Mar 17 16:05:02 EDT 2022 Background processing complete (0.312 secs)  
2022-03-17 16:06:06 INFO  (RecoveryMgr) Thu Mar 17 16:06:06 EDT 2022 Recovery snapshot created: C:\Users\xxxxx\xxxxx.rep\idata\09\~0000009e.db\snapshotA.grf

**Comment by ryanmkurtz** [comment]
I did some preliminary debugging and the initial problem with the `JavaLoader` is here, where we don't recognize `MethodParameters`:

https://github.com/NationalSecurityAgency/ghidra/blob/2d7c8d50552884d4218ba3436f5640bab4995a1b/Ghidra/Processors/JVM/src/main/java/ghidra/javaclass/format/attributes/AttributeFactory.java#L41-L93

**Comment by DspHack** [comment]
Thanks for looking into this.  I think someone else ran into it too:
[Force Format/Analyser on obfuscated/anti-disassembly file](https://reverseengineering.stackexchange.com/questions/24757/force-format-analyser-on-obfuscated-anti-disassembly-file)]

**Comment by ryanmkurtz** [comment]
Do you know if your sample is obfuscated?
