### ISSUE TITLE
GDB: Error when right clicking a debugger target; component must be showing on the screen to determine its location

### ISSUE THREAD

**Issue by aldelaro5** [NationalSecurityAgency/ghidra#4093]
**Describe the bug**
An error occur when I initialism a GNU GDB local debugger session, then go to the debugger targets window and right click on the one target I currently have open.

**To Reproduce**
1. Launch Ghidra and open the debugger tool.
2. Click the create connection button on the debugger targets window.
3. Select GDB local debugger (I happened to have used gdb-multiarch here) and click Connect.
4. You will be in the interpreter window, go back to the Debugger Targets window.
5. You should see one target in the list, right click on it.
6. Observe the error message.

**Expected behavior**
To not have an error message appear and see the right click menu appear such as the option to disconnect.

**Screenshots**
Here is how my Ghidra layout is configured right after step 1 above is done on my end, just in case the layout matters:
![Screenshot from 2022-03-19 22-36-52](https://user-images.githubusercontent.com/8932978/159145590-c3a7176e-5102-4bbf-8b4b-2782df9b5c5d.png)
The interpreter window appears alongside the Objects window and the Debugger Target window in the same bottom right section of the screenshot.

**Environment (please complete the following information):**
 - OS: Arch Linux kernel 5.16.15-arch1-1
 - Java Version: openjdk 11.0.15 2022-04-19
 - Ghidra Version: 10.1.1
 - Ghidra Origin: official ghidra-sre.org distro

**Additional context**
Here is the full error message:
```
component must be showing on the screen to determine its location
java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
	at java.desktop/java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2101)
	at java.desktop/java.awt.Component.getLocationOnScreen(Component.java:2075)
	at java.desktop/javax.swing.JPopupMenu.show(JPopupMenu.java:940)
	at docking.PopupActionManager.popupMenu(PopupActionManager.java:91)
	at docking.ActionToGuiMapper.showPopupMenu(ActionToGuiMapper.java:133)
	at docking.DockableComponent.showContextMenu(DockableComponent.java:173)
	at docking.DockableComponent$1.mousePressed(DockableComponent.java:70)
	at docking.widgets.JTreeMouseListenerDelegate.fireMousePressed(JTreeMouseListenerDelegate.java:125)
	at docking.widgets.JTreeMouseListenerDelegate.mousePressed(JTreeMouseListenerDelegate.java:97)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2021-Dec-21 1319 EST
Ghidra Version: 10.1.1
Java Home: /usr/lib/jvm/java-11-openjdk
JVM Version: Oracle Corporation 11.0.15
OS: Linux 5.16.15-arch1-1 amd64
Workstation: aldelaro5-PC.localdomain
```

**Comment by d-millar** [comment]
@aldelaro5 Hey, am having a hard time recreating your error....  Am testing with Ghidra 10.1.1, JVM 11.0.14, Linux 5.13.0 - not exactly the same, but I would have thought close enough.  Am assuming the screen capture you sent is NOT after you hit connect, correct?   After connecting, would assume you have something in both the Target and Objects trees.  Can you try running with support/ghidraDebug and seeing if there are additional messages in the console?

**Comment by aldelaro5** [comment]
> @aldelaro5 Hey, am having a hard time recreating your error.... Am testing with Ghidra 10.1.1, JVM 11.0.14, Linux 5.13.0 - not exactly the same, but I would have thought close enough. Am assuming the screen capture you sent is NOT after you hit connect, correct? After connecting, would assume you have something in both the Target and Objects trees. Can you try running with support/ghidraDebug and seeing if there are additional messages in the console?

doesn't seem like it, here's the full output up to me getting the error:
```Listening for transport dt_socket at address: 18001
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+3)
OpenJDK 64-Bit Server VM (build 11.0.15+3, mixed mode)
INFO  Using log config file: file:/home/aldelaro5/Documents/ghidra_10.1.1_PUBLIC/support/debug.log4j.xml  (LoggingInitialization.java:51) 
INFO  Using log file: /home/aldelaro5/.ghidra/.ghidra_10.1.1_PUBLIC/application.log  (LoggingInitialization.java:52) 
INFO  Loading user preferences: /home/aldelaro5/.ghidra/.ghidra_10.1.1_PUBLIC/preferences  (Preferences.java:117) 
INFO  Loading previous preferences: /home/aldelaro5/.ghidra/.ghidra_10.1_PUBLIC/preferences  (Preferences.java:170) 
INFO  Class search complete (944 ms)  (ClassSearcher.java:276) 
INFO  Initializing SSL Context  (SSLContextInitializer.java:76) 
INFO  Initializing Random Number Generator...  (SecureRandomFactory.java:37) 
INFO  Random Number Generator initialization complete: NativePRNGNonBlocking  (SecureRandomFactory.java:41) 
INFO  Trust manager disabled, cacerts have not been set  (ApplicationTrustManagerFactory.java:95) 
INFO  User aldelaro5 started Ghidra.  (GhidraRun.java:80) 
DEBUG Recovery snapshot timer set to 5 minute(s)  (RecoverySnapshotMgrPlugin.java:170) 
INFO  Opening project: /home/aldelaro5/Documents/Ghidra projects/dvd-gba/gba-dvd  (DefaultProject.java:134) 
INFO  Packed database cache: /tmp/aldelaro5-Ghidra/packed-db-cache  (PackedDatabaseCache.java:64) 
DEBUG Using cached packed database: /home/aldelaro5/Documents/ghidra_10.1.1_PUBLIC/Ghidra/Features/Base/data/typeinfo/generic/generic_clib.gdt  (PackedDatabaseCache.java:364) 
DEBUG Using cached packed database: /home/aldelaro5/Documents/Ghidra projects/colo/REL.gdt  (PackedDatabaseCache.java:364) 
DEBUG New Pty: /dev/pts/1 at (154,167)  (LinuxPty.java:52) 
INFO  local Pty session. PID = 144390  (LocalProcessPtySession.java:29) 
DEBUG New Pty: /dev/pts/2 at (168,169)  (LinuxPty.java:52) 
ERROR Error: Uncaught Exception! 
IllegalComponentStateException - component must be showing on the screen to determine its location  (SwingExceptionHandler.java:80) 
java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
	at java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2101) ~[?:?]
	at java.awt.Component.getLocationOnScreen(Component.java:2075) ~[?:?]
	at javax.swing.JPopupMenu.show(JPopupMenu.java:940) ~[?:?]
	at docking.PopupActionManager.popupMenu(PopupActionManager.java:91) ~[Docking.jar:?]
	at docking.ActionToGuiMapper.showPopupMenu(ActionToGuiMapper.java:133) ~[Docking.jar:?]
	at docking.DockableComponent.showContextMenu(DockableComponent.java:173) ~[Docking.jar:?]
	at docking.DockableComponent$1.mousePressed(DockableComponent.java:70) ~[Docking.jar:?]
	at docking.widgets.JTreeMouseListenerDelegate.fireMousePressed(JTreeMouseListenerDelegate.java:125) ~[Docking.jar:?]
	at docking.widgets.JTreeMouseListenerDelegate.mousePressed(JTreeMouseListenerDelegate.java:97) ~[Docking.jar:?]
	at java.awt.Component.processMouseEvent(Component.java:6632) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6400) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2263) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
```
And yes this screenshot is as I open the debugger tool in the project. After I connect I both see stuff in the objects window and the targets window. This issue is extremely consistent on my end, I can easily reproduce it.

If it helps, my DE is cinnamon 5.2.7.

**Comment by d-millar** [comment]
Might have figured this out, but you might be able to help me confirm - if you drag the Targets view somewhere else so that it’s not layered over the Objects view, do you still get the error?

**Comment by aldelaro5** [comment]
@d-millar I no longer get the error yeah. I retry placing it where it was before and I get the error back so it definitely has to do with my layouts. Good thing I put the screenshot because I kinda thought it could have been layout related, but this seems to confirm it.

**Comment by d-millar** [comment]
OK, fix should be in the next release (fingers crossed).  It appears the issue was actually more directly related to the fact that the node in the tree ends up unselected as a side effect of the layout.  When you right-clicked, there was a race condition between the selection task and the right-click action.  If the selection wins, everyone is happy;  if not, boom - error.  Thanks for helping pin this down!
