### ISSUE TITLE
I am getting error when analyzing the binary. The issue seems to be in ChkDominanceAlg.

### ISSUE THREAD

**Issue by anzosasuke** [NationalSecurityAgency/ghidra#4156]
I have a gdirected graph where I am trying to get dominance. I am getting this error on the binary.
My code snippet:

` gg = ChkDominanceAlgorithm(digraph1, monitor)\
    gr = gg.getDominanceTree()` 

My code:
[goto.zip](https://github.com/NationalSecurityAgency/ghidra/files/8493876/goto.zip)
My binary
[c-common.zip](https://github.com/NationalSecurityAgency/ghidra/files/8493879/c-common.zip)

And the output:
` File "/home/a967a038/Downloads/codes/ghidra_scripts-master/R6/goto.py", line 104, in <module>
    goto(bbm,functions)
  File "/home/a967a038/Downloads/codes/ghidra_scripts-master/R6/goto.py", line 77, in goto
    digraph1 = gdgraph(bbm,function)
  File "/home/a967a038/Downloads/codes/ghidra_scripts-master/R6/goto.py", line 47, in gdgraph
    digraph1 = addEdgeDestination(digraph, fromVertex, block)
  File "/home/a967a038/Downloads/codes/ghidra_scripts-master/R6/goto.py", line 31, in addEdgeDestination
    dom = GraphAlgorithms.findDominance(digraph, fromVertex ,monitor)
	at ghidra.graph.algo.AbstractDominanceAlgorithm.unifySources(AbstractDominanceAlgorithm.java:61)
	at ghidra.graph.algo.ChkDominanceAlgorithm.findRoot(ChkDominanceAlgorithm.java:85)
	at ghidra.graph.algo.ChkDominanceAlgorithm.<init>(ChkDominanceAlgorithm.java:77)
	at ghidra.graph.algo.ChkDominanceAlgorithm.<init>(ChkDominanceAlgorithm.java:67)
	at ghidra.graph.GraphAlgorithms.findDominance(GraphAlgorithms.java:324)
	at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: The graph does not contain at least one source node`

Can someone help me with this please? Thanks

**Comment by anzosasuke** [comment]
Is there some way to bypass this error by skipping the graph which doesn't have a source node?? Anyways to get out of this error would be great. @ryanmkurtz

**Comment by dragonmacher** [comment]
```
sources = GraphAlgorithms.getSources();
if (sources.isEmpty()) {
    // do not try to find dominance...
}
```
