### ISSUE TITLE
StringIndexOutOfBoundsException in Variadic Function Signature Override analysis

### ISSUE THREAD

**Issue by ekilmer** [NationalSecurityAgency/ghidra#4165]
**Describe the bug**
When processing `libc-2.23.so` using the Variadic Function Analysis script, I see the following `ERROR` log message:
<details>
  <summary>Click to see exception traceback</summary>

```
ERROR Unexpected exception getting Decompiler result (InternalResultListener) java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException: String index out of range: 1
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at generic.concurrent.QResult.<init>(QResult.java:40)
        at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 1
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
        at java.base/java.lang.String.charAt(String.java:693)
        at ghidra.app.plugin.core.string.variadic.FormatStringParser.parseFormatString(FormatStringParser.java:93)
        at ghidra.app.plugin.core.string.variadic.FormatStringParser.convertToFormatArgumentList(FormatStringParser.java:292)
        at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer.parseParameters(FormatStringAnalyzer.java:283)
        at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer.initSignature(FormatStringAnalyzer.java:325)
        at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer.overrideFunctionCall(FormatStringAnalyzer.java:355)
        at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer.overrideCallList(FormatStringAnalyzer.java:343)
        at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer$1.process(FormatStringAnalyzer.java:217)
        at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer$1.process(FormatStringAnalyzer.java:194)
        at ghidra.app.decompiler.parallel.DecompilerCallback.process(DecompilerCallback.java:80)
        at ghidra.app.decompiler.parallel.DecompilerCallback.process(DecompilerCallback.java:41)
        at generic.concurrent.ConcurrentQ$CallbackCallable.call(ConcurrentQ.java:658)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:76)
        ... 3 more

ERROR Error: could not decompile functions with ParallelDecompiler (FormatStringAnalyzer) java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException: String index out of range: 1
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at generic.concurrent.QResult.<init>(QResult.java:40)
        at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 1
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
        at java.base/java.lang.String.charAt(String.java:693)
        at ghidra.app.plugin.core.string.variadic.FormatStringParser.parseFormatString(FormatStringParser.java:93)
        at ghidra.app.plugin.core.string.variadic.FormatStringParser.convertToFormatArgumentList(FormatStringParser.java:292)
        at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer.parseParameters(FormatStringAnalyzer.java:283)
        at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer.initSignature(FormatStringAnalyzer.java:325)
        at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer.overrideFunctionCall(FormatStringAnalyzer.java:355)
        at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer.overrideCallList(FormatStringAnalyzer.java:343)
        at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer$1.process(FormatStringAnalyzer.java:217)
        at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer$1.process(FormatStringAnalyzer.java:194)
        at ghidra.app.decompiler.parallel.DecompilerCallback.process(DecompilerCallback.java:80)
        at ghidra.app.decompiler.parallel.DecompilerCallback.process(DecompilerCallback.java:41)
        at generic.concurrent.ConcurrentQ$CallbackCallable.call(ConcurrentQ.java:658)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:76)
        ... 3 more

INFO  -----------------------------------------------------
    Variadic Function Signature Override - One Time     1.871 secs
-----------------------------------------------------
     Total Time   1 secs
-----------------------------------------------------
 (AutoAnalysisManager)
```

</details>

**To Reproduce**

(I also see the error when running `Analysis` -> `One Shot` -> `Variadic Function Signature Override` analysis from the GUI and inspecting the log console.)

1. Create a simple Ghidra script like the following and name it something like `reproScript.java` and place it in a directory next to the attached `libc-2.23.so`:

<details>
  <summary>Click to see Ghidra Script code</summary>

```java
import ghidra.app.plugin.core.analysis.AutoAnalysisManager;
import ghidra.app.script.GhidraScript;

public class reproScript extends GhidraScript {
  @Override
  protected void run() throws Exception {
    AutoAnalysisManager analysisMgr = AutoAnalysisManager.getAnalysisManager(currentProgram);
    analysisMgr.scheduleOneTimeAnalysis(
        analysisMgr.getAnalyzer("Variadic Function Signature Override"), currentProgram.getMemory());
    analysisMgr.startAnalysis(monitor);
    analysisMgr.waitForAnalysis(null, monitor);
  }
}
```

</details>

2. Run the following within the directory containing the script and binary (setting `GHIDRA_INSTALL_DIR` to the root Ghidra directory):

```bash
"${GHIDRA_INSTALL_DIR}/support/analyzeHeadless" "$(pwd)" ghidra-variadic -import libc-2.23.so -scriptPath $(pwd) -postscript reproScript.java
```

3. Wait a bit and inspect terminal output to see the `ERROR` message with `StringIndexOutOfBoundsException`

**Expected behavior**
No errors.

**Screenshots**
N/A

**Attachments**

[libc-2.23.so.zip](https://github.com/NationalSecurityAgency/ghidra/files/8525260/libc-2.23.so.zip) - Taken from an Ubuntu 16.04 container. Unzip. MD5 of decompressed `libc-2.23.so`: `b0097c8a9284b03b412ff171c3d3c9cc`

**Environment (please complete the following information):**
 - OS: macOS 12.3.1 
 - Java Version: 
    `openjdk version "11.0.14.1" 2022-02-08`
    `OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)`
    `OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)`

 - Ghidra Version: 10.1.2
 - Ghidra Origin: official GitHub release download

**Additional context**
I haven't yet tried to track down where in the binary this exception happens.

**Comment by ghidracadabra** [comment]
I can reproduce this; thanks for reporting.
