### ISSUE TITLE
NPE exception when click Force Field for a union in Decompiler

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#4171]
**Describe the bug**
A NullPointerException occurred when I run the "Force Field" on a union variable.

**To Reproduce**
1. Save the following code as union.c
```
#include <stdio.h>
union u1
{
    int var1;
    char var2;
    void *var4;
};
int main(void)
{
    union u1 var;
    var.var2 = 'c';
    scanf("%d", &var.var1);
    return var.var2;
}
```
2. Compile it with `gcc ./union.c -o uniontest`
3. Import `uniontest` in Ghidra
4. Analyze it with default analyzer settings
5. Add a new union definition for `union u1` in Union Editor. (Alternatively, you can parse union.c to this program.)
6. Retype `local_10` to `u1`
7. The decompiled code looks like this:
```
int main(void)
{
  u1 local_10;
  
  local_10.var2 = 'c';
  __isoc99_scanf(&DAT_00102004,&local_10);
  return (int)local_10.var2;
}
```
8. Right-click the `var2` of the line `local_10.var2 = 'c';`. Click "Force Field." You can see a NPE uncaught exception.

**Expected behavior**
No uncaught exception.

**Environment (please complete the following information):**
 - OS: Kali Linux x64
 - Java Version: 17.0.2
 - Ghidra Version: 10.2 (master, 47f76c78d6b7d5c56a9256b0666620863805ff30)
 - Ghidra Origin: locally built

**Additional context**
```
Cannot invoke "ghidra.program.model.pcode.HighSymbol.getDataType()" because the return value of "ghidra.program.model.pcode.HighVariable.getSymbol()" is null
java.lang.NullPointerException: Cannot invoke "ghidra.program.model.pcode.HighSymbol.getDataType()" because the return value of "ghidra.program.model.pcode.HighVariable.getSymbol()" is null
	at ghidra.app.plugin.core.decompile.actions.ForceUnionAction.typeIsUnionRelated(ForceUnionAction.java:88)
	at ghidra.app.plugin.core.decompile.actions.ForceUnionAction.determineFacet(ForceUnionAction.java:116)
	at ghidra.app.plugin.core.decompile.actions.ForceUnionAction.decompilerActionPerformed(ForceUnionAction.java:202)
	at ghidra.app.plugin.core.decompile.actions.AbstractDecompilerAction.lambda$actionPerformed$1(AbstractDecompilerAction.java:76)
	at ghidra.app.plugin.core.decompile.DecompilerActionContext.performAction(DecompilerActionContext.java:116)
	at ghidra.app.plugin.core.decompile.actions.AbstractDecompilerAction.actionPerformed(AbstractDecompilerAction.java:75)
	at docking.PopupMenuHandler$1.run(PopupMenuHandler.java:63)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2022-Apr-21 0435 EDT
Ghidra Version: 10.2
Java Home: /usr/lib/jvm/java-17-openjdk-amd64
JVM Version: Debian 17.0.2
OS: Linux 5.16.0-kali7-amd64 amd64
Workstation: kali
```

**Comment by caheckman** [comment]
Reproducing this.  Thanks for submitting.
