### ISSUE TITLE
AssertionException spamming logs

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#4234]
**Describe the bug**
Don't recall experiencing anything obvious, but my scroll back in eclipse was full.  Worth reporting the failed assertion I guess.

```
ERROR This method must be called on the Swing thread ghidra.util.exception.AssertException: This method must be called on the Swing thread
	at ghidra.util.Swing.assertSwingThread(Swing.java:94)
	at ghidra.util.HTMLUtilities.fromHTML(HTMLUtilities.java:762)
	at ghidra.util.table.ReferencesFromTableModel$ReferenceTypeTableCellRenderer.getFilterString(ReferencesFromTableModel.java:130)
	at ghidra.util.table.ReferencesFromTableModel$ReferenceTypeTableCellRenderer.getFilterString(ReferencesFromTableModel.java:1)
	at docking.widgets.table.sort.ColumnRenderedValueBackupComparator.getRenderedColumnStringValue(ColumnRenderedValueBackupComparator.java:92)
	at docking.widgets.table.sort.ColumnRenderedValueBackupComparator.compare(ColumnRenderedValueBackupComparator.java:65)
	at docking.widgets.table.sort.RowBasedColumnComparator.compare(RowBasedColumnComparator.java:100)
	at docking.widgets.table.AbstractSortedTableModel$ComparatorLink.compare(AbstractSortedTableModel.java:468)
	at ghidra.util.datastruct.Algorithms.doBubbleSort(Algorithms.java:81)
	at ghidra.util.datastruct.Algorithms.doMergeSort(Algorithms.java:116)
	at ghidra.util.datastruct.Algorithms.doMergeSort(Algorithms.java:123)
	at ghidra.util.datastruct.Algorithms.doMergeSort(Algorithms.java:123)
	at ghidra.util.datastruct.Algorithms.mergeSort(Algorithms.java:101)
	at ghidra.util.datastruct.Algorithms.mergeSort(Algorithms.java:94)
	at docking.widgets.table.threaded.TableUpdateJob.doSortData(TableUpdateJob.java:518)
	at docking.widgets.table.threaded.TableUpdateJob.sortData(TableUpdateJob.java:498)
	at docking.widgets.table.threaded.TableUpdateJob.processState(TableUpdateJob.java:339)
	at docking.widgets.table.threaded.TableUpdateJob.run(TableUpdateJob.java:129)
	at docking.widgets.table.threaded.ThreadedTableModelUpdateMgr$ThreadRunnable.run(ThreadedTableModelUpdateMgr.java:415)
	at java.base/java.lang.Thread.run(Thread.java:829)
  (Swing.java:95) 
```

**Environment (please complete the following information):**
 - OS: 20.04
 - Java Version: 11.0.15
 - Ghidra Version: f249abfac03129bfae2f25af85b914cad312b733
 - Ghidra Origin: eclipse

**Comment by ryanmkurtz** [comment]
Closed by 2436cba12a80b533995ba3854a5e7c705ff49ca6
