### ISSUE TITLE
How i get elf header from current program?

### ISSUE THREAD

**Issue by d4em0n** [NationalSecurityAgency/ghidra#424]
ghidra docs seems not clear to me, i don't know what is the correct way to get binary header
```
>>> provider = MemoryByteProvider(memory, addressFactory.getDefaultAddressSpace())
>>> header = ElfHeader.createElfHeader(RethrowContinuesFactory.INSTANCE, provider)
Traceback (most recent call last):
  File "python", line 1, in <module>
	at ghidra.app.util.bin.format.elf.ElfHeader.determineHeaderEndianess(ElfHeader.java:1049)
	at ghidra.app.util.bin.format.elf.ElfHeader.initElfHeader(ElfHeader.java:122)
	at ghidra.app.util.bin.format.elf.ElfHeader$$EnhancerByCGLIB$$95f11f89.CGLIB$initElfHeader$12(<generated>)
	at ghidra.app.util.bin.format.elf.ElfHeader$$EnhancerByCGLIB$$95f11f89$$FastClassByCGLIB$$d34d921a.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:215)
	at generic.continues.ContinuesInterceptor.intercept(ContinuesInterceptor.java:39)
	at ghidra.app.util.bin.format.elf.ElfHeader$$EnhancerByCGLIB$$95f11f89.initElfHeader(<generated>)
	at ghidra.app.util.bin.format.elf.ElfHeader.createElfHeader(ElfHeader.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
ghidra.app.util.bin.format.elf.ElfException: ghidra.app.util.bin.format.elf.ElfException: Not enough bytes to be a valid ELF executable.
```

**Comment by GhidraKnight** [comment]
This exception is thrown because the "provider" being passed to the ElfHeader.createElfHeader() doesn't contain (provide) enough bytes to create a header.

Did you get "memory" from a program already imported as a ELF?  For example: memory = currentProgram.getMemory()?

**Comment by d4em0n** [comment]
yeah sure i did that before

**Comment by GhidraKnight** [comment]
Try making this change: "MemoryByteProvider(memory, **currentProgram.getMinAddress()**)".

**Comment by ghidra1** [comment]
Ghidra memory block placement in memory does not correspond to original file offsets which are heavily used by the various Elf Headers.   While you may be able to invoke ElfHeader.createElfHeader using a memory byte provider the parse method will not work since it requires the original file bytes at the proper offsets.   Alternatively, you can navigate the header markup (structures and references) produced by the GHIDRA ELF importer, or construct the ElfHeader from the original file.
