### ISSUE TITLE
Exception clicking an else brace

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#4242]
**Describe the bug**
Friend sent me a screenshot (sorry if transcribed a typo) and said when he clicked an else brace (a specific one, not every) it threw this error, sorry don't know more.

```
java.util.EmptyStackException                                                                                                                       
        at java.base/java.util.Stack.peek(Stack.java:102)                                                                                           
        at java.base/java.util.Stack.pop(Stack.java:84)                                                                                             
        at ghidra.app.decompiler.component.DecompilerUtils.getMatchingBrace(DecompilerUtils.java:583)                                               
        at ghidra.app.decompiler.component.ClangHighlightController.highlightBrace(ClangHighlightController.java:377)                               
        at ghidra.app.decompiler.component.ClangHighlightController.addHighlightBrace(ClangHighlightController.java:370)                            
        at ghidra.app.decompiler.component.LocationClangHighlightController.fieldLocationChange(LocationClangHighlightController.java:53)           
        at ghidra.app.decompiler.component.DecompilerPanel$PendingHighlightUpdate.doUpdate(DecompilerPanel.java:1216)                               
        at ghidra.app.decompiler.component.DecompilerPanel.lambda$new$0(DecompilerPanel.java:80)                                                    
        at ghidra.util.task.SwingUpdateManager.swingDoWork(SwingUpdateManager.java:108)                                                             
        at ghidra.util.task.AbstractSwingUpdateManager.swingExecutePendingWork(AbstractSwingUpdateManager.java:338)                                 
        at ghidra.util.task.AbstractSwingUpdateManager.checkForWork(AbstractSwingUpdateManager.java:278)                                            
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)                                                           
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)                                                                  
```

**Environment (please complete the following information):**
 - OS: win10
 - Java Version: 11
 - Ghidra Version: 10.1.3
 - Ghidra Origin: official

**Comment by dragonmacher** [comment]
I'm fairly confident this has been fixed, but did not make it into any patch release.

**Comment by mumbel** [comment]
I was able to find an example in 10.1.2 which looked like this exception.  I tried it in f672ba46b7f765a6f8fef8281fecc6c4bac7cfcc and the result is no auto relocation in decompiler window like other braces, so it knows something is wrong looks like, but doesn't throw exception
