### ISSUE TITLE
Exception in Variadic Function Signature Override analysis with offset format strings

### ISSUE THREAD

**Issue by ekilmer** [NationalSecurityAgency/ghidra#4256]
**Describe the bug**
Hello! I am getting `StringIndexOutOfBoundsException` in the variadic format string function analyzer.

<details>
  <summary>Click to see exception traceback</summary>

```
2022-05-16 16:05:46 ERROR (InternalResultListener) Unexpected exception getting Decompiler result java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException: String index out of range: 20
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at generic.concurrent.QResult.<init>(QResult.java:40)
	at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 20
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at ghidra.app.plugin.core.string.variadic.FormatStringParser.parseFormatString(FormatStringParser.java:93)
	at ghidra.app.plugin.core.string.variadic.FormatStringParser.convertToFormatArgumentList(FormatStringParser.java:292)
	at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer.parseParameters(FormatStringAnalyzer.java:276)
	at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer.initSignature(FormatStringAnalyzer.java:318)
	at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer.overrideFunctionCall(FormatStringAnalyzer.java:347)
	at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer.overrideCallList(FormatStringAnalyzer.java:336)
	at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer$1.process(FormatStringAnalyzer.java:211)
	at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer$1.process(FormatStringAnalyzer.java:188)
	at ghidra.app.decompiler.parallel.DecompilerCallback.process(DecompilerCallback.java:80)
	at ghidra.app.decompiler.parallel.DecompilerCallback.process(DecompilerCallback.java:41)
	at generic.concurrent.ConcurrentQ$CallbackCallable.call(ConcurrentQ.java:658)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:76)
	... 3 more
 
2022-05-16 16:05:46 ERROR (FormatStringAnalyzer) Error: could not decompile functions with ParallelDecompiler java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException: String index out of range: 20
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at generic.concurrent.QResult.<init>(QResult.java:40)
	at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 20
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at ghidra.app.plugin.core.string.variadic.FormatStringParser.parseFormatString(FormatStringParser.java:93)
	at ghidra.app.plugin.core.string.variadic.FormatStringParser.convertToFormatArgumentList(FormatStringParser.java:292)
	at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer.parseParameters(FormatStringAnalyzer.java:276)
	at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer.initSignature(FormatStringAnalyzer.java:318)
	at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer.overrideFunctionCall(FormatStringAnalyzer.java:347)
	at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer.overrideCallList(FormatStringAnalyzer.java:336)
	at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer$1.process(FormatStringAnalyzer.java:211)
	at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer$1.process(FormatStringAnalyzer.java:188)
	at ghidra.app.decompiler.parallel.DecompilerCallback.process(DecompilerCallback.java:80)
	at ghidra.app.decompiler.parallel.DecompilerCallback.process(DecompilerCallback.java:41)
	at generic.concurrent.ConcurrentQ$CallbackCallable.call(ConcurrentQ.java:658)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:76)
	... 3 more
```

</details>

I think I have traced the issue down to a potentially weird case where the format string itself is within a larger string data entry, so I think this means we execute down this path https://github.com/NationalSecurityAgency/ghidra/blob/0acb497263c209ac59b306ebdea8110547205058/Ghidra/Features/DecompilerDependent/src/main/java/ghidra/app/plugin/core/string/variadic/PcodeFunctionParser.java#L86-L87
because we can't find it in the mapping https://github.com/NationalSecurityAgency/ghidra/blob/0acb497263c209ac59b306ebdea8110547205058/Ghidra/Features/DecompilerDependent/src/main/java/ghidra/app/plugin/core/string/variadic/PcodeFunctionParser.java#L106
(?) and the format string entry flag (`%`) appears at the very end of the buffer cutoff length (`BUFFER_LENGTH = 20`)
https://github.com/NationalSecurityAgency/ghidra/blob/0acb497263c209ac59b306ebdea8110547205058/Ghidra/Features/DecompilerDependent/src/main/java/ghidra/app/plugin/core/string/variadic/PcodeFunctionParser.java#L174-L175
which produces `/tmp/123/456%d/part%` instead of `/tmp/123/456%d/part%d/%s` (as shown in the example below).

**To Reproduce**

1. Given the following source code:

```c
#include <stdio.h>

void main() {
  char *cmd = "ls /tmp/123/456%d/part%d/%s";
  printf(cmd, 1, 2, "repro");
  printf(cmd + 3, 1, 2, "repro"); // Error here
}
```

compiled version (`gcc repro.c -Os -o repro`) can be found in attachments section 

2. Load into Ghidra and run the Variadic Function Signature Override analysis to see the exception.

**Expected behavior**
No exception and that Ghidra looks at the _entire_ string instead of only part of it.

**Attachments**

[repro.zip](https://github.com/NationalSecurityAgency/ghidra/files/8703091/repro.zip)

**Environment (please complete the following information):**
 - OS: macOS 12.3.1
 - Java Version: 11
 - Ghidra Version: latest `master` commit `0acb497263c209ac59b306ebdea8110547205058`
 - Ghidra Origin: locally built

**Additional context**

Sort of related to #4165. Thank you for the fix with that sample! 🙂 

The example binaries are samples that I'm able to share/reproduce as opposed to the binaries I am first discovering the error(s).

This minimized example was the only way I could force the compiler to reuse the same string. However, in the real target, I think the compiler might have optimized the binary to reuse the same strings with different offsets depending on the usage. So, while my example might be weird, I think real binaries could exhibit this behavior due to compiler optimizations.

**Comment by ghidracadabra** [comment]
Thanks for reporting this.  I see the issue and it's an easy fix.
