### ISSUE TITLE
Error when importing files inside chroot env

### ISSUE THREAD

**Issue by Nooguat** [NationalSecurityAgency/ghidra#4291]
**Describe the bug**
Ghidra fails to load any file (headless or not) when running inside a chroot environnement. 

**To Reproduce**
1. Create a chroot environnement
2. Try to import file
3. Fails with `java.lang.RuntimeException: Failed to init global cache /tmp/<user>-Ghidra/fscache2`.
From research, the issue may be coming from here
`Caused by: java.io.IOException: Mount point not found sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:105)`

**Expected behavior**
File get imported in project without issue

**Environment (please complete the following information):**
 - OS: Arch Linux (chroot)
 - Java Version: openjdk-11.0.15
 - Ghidra Version: 10.2
 - Ghidra Origin: binaries from pacman

**Comment by dev747368** [comment]
Can you paste the full stack traces?

**Comment by dev747368** [comment]
and also, in the same chroot, could you try running jshell and pasting in the following and reporting what it displays:

```java
File cacheDir = new File("/tmp/username-Ghidra/fscache2");
cacheDir.mkdirs();
cacheDir.exists();
```

**Comment by Nooguat** [comment]
Hello,
Thanks for your response; here the full stack trace from this error window : 
`java.lang.ExceptionInInitializerError
	at ghidra.plugin.importer.ImporterPlugin.initializeChooser(ImporterPlugin.java:321)
	at ghidra.plugin.importer.ImporterPlugin.doSingleImportAction(ImporterPlugin.java:337)
	at ghidra.plugin.importer.ImporterPlugin$1.actionPerformed(ImporterPlugin.java:217)
	at docking.ExecutableAction.execute(ExecutableAction.java:40)
	at docking.action.MultipleKeyAction.actionPerformed(MultipleKeyAction.java:142)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at docking.KeyBindingOverrideKeyEventDispatcher.actionInProgress(KeyBindingOverrideKeyEventDispatcher.java:219)
	at docking.KeyBindingOverrideKeyEventDispatcher.dispatchKeyEvent(KeyBindingOverrideKeyEventDispatcher.java:117)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1133)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4892)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.RuntimeException: Failed to init global cache /tmp/zbaboum-Ghidra/fscache2
	at ghidra.formats.gfilesystem.FileSystemService.<init>(FileSystemService.java:180)
	at ghidra.formats.gfilesystem.FileSystemService.<init>(FileSystemService.java:160)
	at ghidra.formats.gfilesystem.FileSystemService.getInstance(FileSystemService.java:64)
	at ghidra.plugin.importer.ImporterUtilities.<clinit>(ImporterUtilities.java:75)
	... 32 more
Caused by: java.io.IOException: Mount point not found
	at java.base/sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:105)
	at java.base/sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:69)
	at java.base/sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:49)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39)
	at java.base/sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:373)
	at java.base/java.nio.file.Files.getFileStore(Files.java:1488)
	at ghidra.formats.gfilesystem.FileCache.<init>(FileCache.java:105)
	at ghidra.formats.gfilesystem.FileSystemService.<init>(FileSystemService.java:175)
	... 35 more

---------------------------------------------------
Build Date: 2022-May-27 1648 GMT
Ghidra Version: 10.2
Java Home: /usr/lib/jvm/java-11-openjdk
JVM Version: Oracle Corporation 11.0.15
OS: Linux 5.17.9-zen1-1-zen amd64
`
For the jshell commands : 
`
|  Welcome to JShell -- Version 11.0.15
|  For an introduction type: /help intro
jshell> File cacheDir = new File("/tmp/username-Ghidra/fscache2");
File cacheDir = new File("/tmp/username-Ghidra/fscache2")cacheDir ==> /tmp/username-Ghidra/fscache2

jshell> cacheDir.mkdirs();
cacheDir.mkdirs()$2 ==> true

jshell> cacheDir.exists();
cacheDir.exists()$3 ==> true

`

**Comment by colincaldwell1231-design** [comment]
Thanks for confirming this is still occurring.
