### ISSUE TITLE
Exception in when selecting text in the decompiler panel

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4309]
**Describe the bug**
Highlighting code in the decompiler window results in a crash in DecompilerUtils.addTokens. It appears that in rare cases a ``ClangTextField textline`` can span multiple lines in the decompiler window. This results in an exception due to ``startIndex > endIndex``.

```
	private static void addTokens(List<ClangToken> tokenList, Field[] lines, int lineNumber,
			FieldLocation start, FieldLocation end) {
		if (lineNumber >= lines.length) {
			return;
		}
		ClangTextField textLine = (ClangTextField) lines[lineNumber];
		int startIndex = getStartIndex(textLine, start);
		int endIndex = getEndIndex(textLine, end);
		tokenList.addAll(textLine.getTokens().subList(startIndex, endIndex));
	}
```

The stacktrace is as follows.
```
fromIndex(4) > toIndex(1)

java.lang.IllegalArgumentException: fromIndex(4) > toIndex(1)
	at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:509)
	at java.base/java.util.ArrayList.subList(ArrayList.java:1138)
	at ghidra.app.decompiler.component.DecompilerUtils.addTokens(DecompilerUtils.java:492)
	at ghidra.app.decompiler.component.DecompilerUtils.addTokensInSelectionRange(DecompilerUtils.java:467)
	at ghidra.app.decompiler.component.DecompilerUtils.getTokensInSelection(DecompilerUtils.java:452)
	at ghidra.app.decompiler.component.DecompilerPanel.getSelectedToken(DecompilerPanel.java:930)
	at ghidra.app.decompiler.component.DecompilerUtils.getDataType(DecompilerUtils.java:747)
	at ghidra.app.plugin.core.decompile.actions.EditDataTypeAction.isEnabledForDecompilerContext(EditDataTypeAction.java:59)	at ghidra.app.plugin.core.decompile.actions.AbstractDecompilerAction.lambda$isEnabledForContext$0(AbstractDecompilerAction.java:68)
	at ghidra.app.plugin.core.decompile.DecompilerActionContext.checkActionEnablement(DecompilerActionContext.java:147)
	at ghidra.app.plugin.core.decompile.actions.AbstractDecompilerAction.isEnabledForContext(AbstractDecompilerAction.java:67)
	at docking.ComponentPlaceholder.contextChanged(ComponentPlaceholder.java:532)
	at docking.DockingWindowManager.contextChanged(DockingWindowManager.java:2232)
	at docking.AbstractDockingTool.contextChanged(AbstractDockingTool.java:208)
	at ghidra.framework.plugintool.PluginTool.contextChanged(PluginTool.java:1433)
	at ghidra.app.plugin.core.decompile.DecompilerProvider.contextChanged(DecompilerProvider.java:675)
	at ghidra.app.plugin.core.decompile.DecompilerProvider.locationChanged(DecompilerProvider.java:515)
	at ghidra.app.decompiler.component.DecompilerController.locationChanged(DecompilerController.java:261)
	at ghidra.app.decompiler.component.DecompilerPanel.fieldLocationChanged(DecompilerPanel.java:773)

```

**Environment (please complete the following information):**
 Ghidra Version: 10.1.3, public release
 Windows 10

**Comment by sad-dev** [comment]
![image](https://user-images.githubusercontent.com/55233728/172312070-3b81a8a5-652d-476b-a30c-1233b023176d.png)

I was only able to replicate this on that particular system, but a (censored) screenshot of the exception is shown here. The selected code is of the form 
```
foo((somestruct *)&SomeGlobal,8,(void *)0x0
);
```
