### ISSUE TITLE
C++ calling convention for not-trivial-return-values

### ISSUE THREAD

**Issue by gipi** [NationalSecurityAgency/ghidra#4313]
As indicated [here](https://itanium-cxx-abi.github.io/cxx-abi/abi.html#this-parameters)

    Non-static member functions, including constructors and destructors,
    take an implicit this parameter of pointer type. It is passed as if it were
    the first parameter in the function prototype, except as modified for
    non-trivial return values.

Indeed in some ``C++`` binaries that I'm reversing the ``__thiscall`` erroneously set the first argument as a pointer to the class instance but in reality should use the second parameter for that and uses the first for the return value.

Is there any way of describing a call fixup for this case? moreover, what ``switch8_r0`` and similar that I see for ``ARM32`` are used for? I didn't find any information.

**Comment by gipi** [comment]
I'm sorry but I don't understand: is it the attribute ``retbeforethis`` or ``thisbeforeretpointer``? because the first doesn't exist anywhere in the ``ghidra`` source code. Moreover ``thisbeforeretpointer`` is the opposite of what I want. In theory from the return type ``ghidra`` should understand that the object returned should go as a first argument but I assumed that the decompiler is not able to do that automatically (too complicated?) this is why I talked about call fixups.

I'm working on an ARM32 binary so I don't know if it works for x86.

**Comment by astrelsky** [comment]
> I'm sorry but I don't understand: is it the attribute ``retbeforethis`` or ``thisbeforeretpointer``? because the first doesn't exist anywhere in the ``ghidra`` source code. Moreover ``thisbeforeretpointer`` is the opposite of what I want. In theory from the return type ``ghidra`` should understand that the object returned should go as a first argument but I assumed that the decompiler is not able to do that automatically (too complicated?) this is why I talked about call fixups.
> 
> I'm working on an ARM32 binary so I don't know if it works for x86.
> 
> 

Oh wow, I didn't even notice. I will confirm later but I think it is backwards. I think I have always gotten the behavior you are looking for where the return pointer came before the this pointer.

**Comment by ddkwork** [comment]
> There is an attribute for `prototype` in the cspec called `retbeforethis` that should be set to true. I think there is an example of it being used in the x86 cspecs somewhere. 
> 
> The callfixups are for things like compiler generated functions that have side effects the decompiler needs to know about that it can't see. An example is `alloca` or `chkstack` which alter the stack pointer. You can add a program specific specification extension for ones not provided with Ghidra. I personally use these all the time for functions such ass `__allmul` on 32 bit x86 to have the decompiler replace the function call with multiplication. 
> 
> https://github.com/NationalSecurityAgency/ghidra/blob/c6cb8a0d85648c2f8d9a5a0f8cf2815c14e53520/Ghidra/Processors/x86/data/languages/x86win.cspec#L155-L157

![Screenshot_20241103_122419_com.realvnc.viewer.android.jpg](https://github.com/user-attachments/assets/10f7e9f2-1bb9-40f3-94f9-8786c04ff13a)

Hi, not working

**Comment by astrelsky** [comment]
You can't have both `thisbeforeret` and `retbeforethis` set to true.

**Comment by ddkwork** [comment]
> You can't have both and set to true.`thisbeforeret``retbeforethis`

thx,i will try. and i maked a rep for test this:
https://github.com/ddkwork/asm

**Comment by ddkwork** [comment]
> You can't have both and set to true.`thisbeforeret``retbeforethis`

![image](https://github.com/user-attachments/assets/8de4c37d-f1fb-44af-be71-9f0c600848a4)

this label seems not a right label or node title ?

**Comment by Wall-AF** [comment]
The attribute you're looking for is `thisbeforeretpointer` and appears in `/Framework SoftwareModeling/data/languages/compiler_spec.rxg`, `/_Decompiler/cpp/fspec.hh` & `/_Decompiler/cpp/fspec.cc`..

**Comment by ddkwork** [comment]
> The attribute you're looking for is `thisbeforeretpointer` and appears in:
> ```
> D:\...\Ghidra\ghidra>findstr /s /n  thisbeforeretpointer *.java *.h *.hh *.hp* *.inc *.inl *.c *.cc *.cp* *.asm *.sinc *.*spec *.opinion *.sla *.rxg *.xml  | more
> Ghidra\Features\Decompiler\src\decompile\cpp\fspec.cc:35:AttributeId ATTRIB_THISBEFORERETPOINTER = AttributeId("thisbeforeretpointer",128);
> Ghidra\Features\Decompiler\src\decompile\cpp\fspec.hh:44:extern AttributeId ATTRIB_THISBEFORERETPOINTER;        ///< Marshaling attribute "thisbeforeretpointer"
> Ghidra\Features\Decompiler\src\main\doc\cspec.xml:1428:  <td><code>thisbeforeretpointer</code></td>
> Ghidra\Features\Decompiler\src\main\doc\cspec.xml:1540:The <emphasis>thisbeforeretpointer</emphasis> indicates how the two hidden parameters, the
> Ghidra\Framework\SoftwareModeling\data\languages\compiler_spec.rxg:458:        <optional> <attribute name="thisbeforeretpointer"/> </optional>
> Ghidra\Framework\SoftwareModeling\src\main\java\ghidra\program\model\lang\ParamListStandard.java:344:           attribute = mainel.getAttribute("thisbeforeretpointer");
> Ghidra\Framework\SoftwareModeling\src\main\java\ghidra\program\model\pcode\AttributeId.java:209:                new AttributeId("thisbeforeretpointer", 128);
> Ghidra\Processors\x86\data\languages\x86-64-win.cspec:126:    <input pointermax="8" thisbeforeretpointer="true">
> Ghidra\Processors\x86\data\languages\x86win.cspec:157:    <input thisbeforeretpointer="true">
> ```

To be honest I'm not sure this attribute would allow the decompiler to replace x86 multiplication and division with 64-bit /* / % and so on and so forth for these math symbols. As I understand it, removing the implementation of mul and div is just one step, it's more about combining the two high and low 32-bit integers of the passed formal parameter into a single 64-bit one, so ideally there should be a lot less upper level code to see calls to decompile mul and div.

Also, it would be great if you could make a unit test handy, thanks.

**Comment by Wall-AF** [comment]
Sorry, but I now don't understand what it is you're attempting.  I thought/understood that you were looking for the correct mechanism to place a pointer before the `this` pointer.  You would only do this if you'd already established that the code you're re'ing came from a compiler that specified that "for returned objects larger than the standard return size, this compiler creates an object of the appropriate size (somewhere) and uses a _hidden pointer placed on the stack_ to allow function calls to return them" or words to that effect.

If you're specifically asking how to replace function calls the compiler uses for mathematical operations, I'd also like to see an example please @astrelsky.

**Comment by astrelsky** [comment]
Sorry there is no `retbeforethis` you just do `thisbeforeretpointer=false`

As for the callfixup for replacing function calls with mathematical operations, it's pretty simple. This one was for arm so you'll need to change the register names and adjust the stack if applicable.

NOTE: it's an xml file but GitHub doesn't like that. Just add it in the `Specification Extensions` for in the "Options for {program}" window.
[__sdivsi3.xml.txt](https://github.com/user-attachments/files/17611755/__sdivsi3.xml.txt)

**Comment by ddkwork** [comment]
> Sorry there is no `retbeforethis` you just do `thisbeforeretpointer=false`
> 
> As for the callfixup for replacing function calls with mathematical operations, it's pretty simple. This one was for arm so you'll need to change the register names and adjust the stack if applicable.
> 
> NOTE: it's an xml file but GitHub doesn't like that. Just add it in the `Specification Extensions` for in the "Options for {program}" window.
> [__sdivsi3.xml.txt](https://github.com/user-attachments/files/17611755/__sdivsi3.xml.txt)
> 

i will try, thx

**Comment by ddkwork** [comment]
> Sorry, but I now don't understand what it is you're attempting.  I thought/understood that you were looking for the correct mechanism to place a pointer before the `this` pointer.  You would only do this if you'd already established that the code you're re'ing came from a compiler that specified that "for returned objects larger than the standard return size, this compiler creates an object of the appropriate size (somewhere) and uses a _hidden pointer placed on the stack_ to allow function calls to return them" or words to that effect.
> 
> If you're specifically asking how to replace function calls the compiler uses for mathematical operations, I'd also like to see an example please @astrelsky.

I am doing test this logic:
https://github.com/ddkwork/asm/blob/master/bigNumber%2FbigNumber_test.go#L11-L17
https://github.com/ddkwork/asm/blob/master/bigNumber%2FbigNumber.go#L14-L23

**Comment by ddkwork** [comment]
> Sorry there is no `retbeforethis` you just do `thisbeforeretpointer=false`
> 
> As for the callfixup for replacing function calls with mathematical operations, it's pretty simple. This one was for arm so you'll need to change the register names and adjust the stack if applicable.
> 
> NOTE: it's an xml file but GitHub doesn't like that. Just add it in the `Specification Extensions` for in the "Options for {program}" window.
> [__sdivsi3.xml.txt](https://github.com/user-attachments/files/17611755/__sdivsi3.xml.txt)
> 

Not working, could you please test it? Thx

```
hi, it still not working,step here:
1. msbuild x86 build ../ get ./untitled4.exe
2. fix x86win.cspec
   1.<input thisbeforeretpointer="false">
   2.
      <callfixup name="__sdivsi3">
      <target name="__sdivsi3"/>
      <pcode>
      <body> r0 = r0 s/ r1; </body>
      </pcode>
      </callfixup>
3. drop ./untitled4.exe into ghidra got this:

we can see the mul and div function is not replaced as * and / or % operator.

///////////////////////////////////
 lVar11 += CONCAT44(local_10f,local_13f);
  lVar11 = mul((uint)lVar11,(uint)((ulonglong)lVar11 >> 0x20),2,0);
  lVar12 = mul(uVar9 + 0xf366,0,0x1634,0);
  lVar12 = mul(uVar5 + 1,local_13f + CARRY4((uint)lVar12,uVar9) + (uint)(0xfffffffe < uVar5),
               (uint)local_127,local_127._4_4_);
...

  lVar11 = div((uint)local_127,local_127._4_4_,0x6381be9a,0);
///////////////////////////////////
```
https://github.com/ddkwork/asm/blob/master/bigNumber%2FbigNumber_test.go#L12-L36

**Comment by ddkwork** [comment]
This is the expected unit test data for this behavior

```
func Test_bigNumber(t *testing.T) {
        data := []byte{0x9, 0x99, 0x8a, 0x7b, 0xfe, 0x46, 0xc2, 0xf0}
        b := bigNumber(data)
        mylog.Struct(b)
        assert.Equal(t, uint64(0xCD2F21A91272EE20), b.QuadPart())
        assert.Equal(t, mylog.Check2(hex.DecodeString("CD2F21A91272EE20")), b.Bytes())
}

https://github.com/ddkwork/asm/blob/master/bigNumber%2FbigNumber_test.go#L273-L279
```

**Comment by astrelsky** [comment]
> > Sorry there is no `retbeforethis` you just do `thisbeforeretpointer=false`
> > 
> > As for the callfixup for replacing function calls with mathematical operations, it's pretty simple. This one was for arm so you'll need to change the register names and adjust the stack if applicable.
> > 
> > NOTE: it's an xml file but GitHub doesn't like that. Just add it in the `Specification Extensions` for in the "Options for {program}" window.
> > [__sdivsi3.xml.txt](https://github.com/user-attachments/files/17611755/__sdivsi3.xml.txt)
> > 
> 
> Not working, could you please test it? Thx
> 
> ```
> hi, it still not working,step here:
> 1. msbuild x86 build ../ get ./untitled4.exe
> 2. fix x86win.cspec
>    1.<input thisbeforeretpointer="false">
>    2.
>       <callfixup name="__sdivsi3">
>       <target name="__sdivsi3"/>
>       <pcode>
>       <body> r0 = r0 s/ r1; </body>
>       </pcode>
>       </callfixup>
> 3. drop ./untitled4.exe into ghidra got this:
> 
> we can see the mul and div function is not replaced as * and / or % operator.
> 
> ///////////////////////////////////
>  lVar11 += CONCAT44(local_10f,local_13f);
>   lVar11 = mul((uint)lVar11,(uint)((ulonglong)lVar11 >> 0x20),2,0);
>   lVar12 = mul(uVar9 + 0xf366,0,0x1634,0);
>   lVar12 = mul(uVar5 + 1,local_13f + CARRY4((uint)lVar12,uVar9) + (uint)(0xfffffffe < uVar5),
>                (uint)local_127,local_127._4_4_);
> ...
> 
>   lVar11 = div((uint)local_127,local_127._4_4_,0x6381be9a,0);
> ///////////////////////////////////
> ```
> https://github.com/ddkwork/asm/blob/master/bigNumber%2FbigNumber_test.go#L12-L36

1. `thisbeforeret` is not applicable here since it is not a thiscall function.
2. User error. I explicitly specified that that was for arm. Arm is not x86. Change the register names.

**Comment by ddkwork** [comment]
> > > Sorry there is no `retbeforethis` you just do `thisbeforeretpointer=false`
> > > 
> > > As for the callfixup for replacing function calls with mathematical operations, it's pretty simple. This one was for arm so you'll need to change the register names and adjust the stack if applicable.
> > > 
> > > NOTE: it's an xml file but GitHub doesn't like that. Just add it in the `Specification Extensions` for in the "Options for {program}" window.
> > > [__sdivsi3.xml.txt](https://github.com/user-attachments/files/17611755/__sdivsi3.xml.txt)
> > > 
> > 
> > Not working, could you please test it? Thx
> > 
> > ```
> > hi, it still not working,step here:
> > 1. msbuild x86 build ../ get ./untitled4.exe
> > 2. fix x86win.cspec
> >    1.<input thisbeforeretpointer="false">
> >    2.
> >       <callfixup name="__sdivsi3">
> >       <target name="__sdivsi3"/>
> >       <pcode>
> >       <body> r0 = r0 s/ r1; </body>
> >       </pcode>
> >       </callfixup>
> > 3. drop ./untitled4.exe into ghidra got this:
> > 
> > we can see the mul and div function is not replaced as * and / or % operator.
> > 
> > ///////////////////////////////////
> >  lVar11 += CONCAT44(local_10f,local_13f);
> >   lVar11 = mul((uint)lVar11,(uint)((ulonglong)lVar11 >> 0x20),2,0);
> >   lVar12 = mul(uVar9 + 0xf366,0,0x1634,0);
> >   lVar12 = mul(uVar5 + 1,local_13f + CARRY4((uint)lVar12,uVar9) + (uint)(0xfffffffe < uVar5),
> >                (uint)local_127,local_127._4_4_);
> > ...
> > 
> >   lVar11 = div((uint)local_127,local_127._4_4_,0x6381be9a,0);
> > ///////////////////////////////////
> > ```
> > https://github.com/ddkwork/asm/blob/master/bigNumber%2FbigNumber_test.go#L12-L36
> 
> 1. `thisbeforeret` is not applicable here since it is not a thiscall function.
> 2. User error. I explicitly specified that that was for arm. Arm is not x86. Change the register names.

okay

**Comment by ddkwork** [comment]
Hi, I didn't understand you correctly the other day, are you saying that this can be achieved by modifying the registers? I can't select the callfixup I just added in the function signature edit window because it's not in the list.

```go
<callfixup name="__sdivsi3">
      <target name="__sdivsi3"/>
      <pcode>
      <body> eax = eax s/ ecx; </body>
      </pcode>
</callfixup>

<callfixup name="__mul">
      <target name="__mul"/>
      <pcode>
      <body> eax = eax s* ecx; </body>
      </pcode>
</callfixup>
```
![Screenshot_20241108_115952_com.realvnc.viewer.android.jpg](https://github.com/user-attachments/assets/3258726b-572f-4f82-b78f-12b5a820310d)

![Screenshot_20241108_120241_com.realvnc.viewer.android.jpg](https://github.com/user-attachments/assets/5a9bb1a3-2e54-4f08-9c73-649ff0c1417b)

**Comment by astrelsky** [comment]
> Hi, I didn't understand you correctly the other day, are you saying that this can be achieved by modifying the registers? I can't select the callfixup I just added in the function signature edit window because it's not in the list.
> 
> ```go
> <callfixup name="__sdivsi3">
>       <target name="__sdivsi3"/>
>       <pcode>
>       <body> eax = eax s/ ecx; </body>
>       </pcode>
> </callfixup>
> 
> <callfixup name="__mul">
>       <target name="__mul"/>
>       <pcode>
>       <body> eax = eax s* ecx; </body>
>       </pcode>
> </callfixup>
> ```
> ![Screenshot_20241108_115952_com.realvnc.viewer.android.jpg](https://github.com/user-attachments/assets/3258726b-572f-4f82-b78f-12b5a820310d)
> 
> ![Screenshot_20241108_120241_com.realvnc.viewer.android.jpg](https://github.com/user-attachments/assets/5a9bb1a3-2e54-4f08-9c73-649ff0c1417b)
> 
> 

Did you add it to the program in `edit->Options for 'program name'->Specification Extensions` in the code browser?

**Comment by ddkwork** [comment]
oh no,seems the syntax error?
![Screenshot_20241109_130256_com.realvnc.viewer.android.jpg](https://github.com/user-attachments/assets/62d63abb-d135-4c66-908e-bd43f17054b3)

```go
Unrecoverable error(s), halting compilation
ghidra.app.plugin.processors.sleigh.SleighException: Unrecoverable error(s), halting compilation
	at ghidra.program.model.lang.PcodeParser.compilePcode(PcodeParser.java:457)
	at ghidra.program.model.lang.PcodeInjectLibrary.parseInject(PcodeInjectLibrary.java:176)
	at ghidra.program.database.SpecExtension.parseExtension(SpecExtension.java:466)
	at ghidra.program.database.SpecExtension.testExtensionDocument(SpecExtension.java:646)
	at ghidra.app.plugin.processors.sleigh.SpecExtensionPanel.importExtension(SpecExtensionPanel.java:500)
	at ghidra.app.plugin.processors.sleigh.SpecExtensionPanel.lambda$createButtonPanel$0(SpecExtensionPanel.java:677)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1079)
	at java.desktop/java.awt.Component.show(Component.java:1728)
	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
	at java.desktop/java.awt.Window.setVisible(Window.java:1036)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1015)
	at docking.DockingDialog.setVisible(DockingDialog.java:351)
	at docking.DockingWindowManager.lambda$doShowDialog$6(DockingWindowManager.java:1856)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at docking.DockingWindowManager.doShowDialog(DockingWindowManager.java:1860)
	at docking.DockingWindowManager.showDialog(DockingWindowManager.java:1809)
	at docking.AbstractDockingTool.showDialog(AbstractDockingTool.java:168)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.showProgramOptions(ProgramManagerPlugin.java:595)
	at ghidra.app.plugin.core.progmgr.ProgramOptionsAction.actionPerformed(ProgramOptionsAction.java:49)
	at ghidra.app.plugin.core.progmgr.AbstractProgramNameSwitchingAction.actionPerformed(AbstractProgramNameSwitchingAction.java:71)
	at docking.DockingActionProxy.actionPerformed(DockingActionProxy.java:47)
	at docking.DockingActionPerformer.lambda$perform$0(DockingActionPerformer.java:73)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException: Cannot read field "ops" because "vn1" is null
	at ghidra.pcodeCPort.slgh_compile.PcodeCompile.createOp(PcodeCompile.java:296)
	at ghidra.sleigh.grammar.SleighCompiler.expr(SleighCompiler.java:8680)
	at ghidra.sleigh.grammar.SleighCompiler.assignment(SleighCompiler.java:6745)
	at ghidra.sleigh.grammar.SleighCompiler.statement(SleighCompiler.java:6004)
	at ghidra.sleigh.grammar.SleighCompiler.statements(SleighCompiler.java:5851)
	at ghidra.sleigh.grammar.SleighCompiler.code_block(SleighCompiler.java:5798)
	at ghidra.sleigh.grammar.SleighCompiler.semantic(SleighCompi

```

**Comment by astrelsky** [comment]
I think the x86 registers need to be uppercase. You might need to have each extension in it's own file too.

**Comment by ddkwork** [comment]
> I think the x86 registers need to be uppercase. You might need to have each extension in its own file too.

thx，working now，The pseudo-code doesn't seem to be optimized though, it's too long

ida:
```go
func asm(data []byte) []byte {
	v5 := 0
	v6 := 0
	v7 := 0
	v8 := 0
	v9 := 0
	index := 0
	i := 0
	v17 := 0
	v20 := 0
	out := 0
	elem := int(data[1])
	out = 0x71B793*(elem+0x1302*(elem+0xf366)) + 0x7CFF86
	elem = int(data[2])
	v5 = elem + 0x1634*(elem+0xf366) + 1
	out = v5*(out) + 2*((out)/0x6381BE9A+(out>>0x12)) + 0x2D1F65
	v6 = out
	elem = int(data[3])
	v7 = (elem+
		0x1968*(elem+0xf366)+1)*v6 +
		3*(v6/0x6381BE9A+(v6>>0x12)+0x21D78D)
	v17 = v7/0x6381BE9A + (v7 >> 0x12) // 0x109099DA1514
	elem = int(data[4])
	v8 = (elem + 0x1C9E*(elem+0xf366) + 1) * v7 // 0x5DE07FE3195B295A
	v9 = 4*(v17) + v8 + 0xB47D9D
	index = 7
	out = (4*v17+v8+0xB47D9D)&0xFFF0 + (v9 >> 0x13) + v9&0xFFFFFF + v9&0xFFFFFF // 0xBBC1935A1FC
	i = 7
	v20 = 0x18F
	out = 0x000010B913530849
	v6 = 0x000010B913530849
	for { // 先测试第一轮的计算
		elem = int(data[index])                                                // f0 c2 46 fe 7b 8a 99 09 逆序输入的8字节
		v17 = (out / 0x6A) + (((v6>>32)^((v6>>32)>>7))<<32|(v6^(v6>>7)))>>0x19 // 0x43F9B1AC1A
		// 16FBA94F 第二轮就错了
		out = elem*elem*elem + (elem+1)*out + (index * index * v17) // 0xB19168E94E0DC
		index = i - 1                                               // 6
		out += v17/0x14C9 + i*(int(data[i]))*(int(data[i]))*v20     // 0x3BF80DB8 000FC5F6 todo must
		i--
		v20--
		if i-1 < 0 {
			break
		}
	}
	return binary.LittleEndian.PutUint64(uint64(out))
}

```

Ghidra
```go
void __cdecl asm1(void)

{
  int iVar1;
  uint elem;
  uint uVar2;
  uint uVar3;
  uchar *puVar4;
  uint uVar5;
  uint64_t **ppuVar6;
  byte *pbVar7;
  undefined4 uStackY_2bb;
  undefined4 uStackY_2b7;
  int iStackY_2b3;
  uint uStackY_2af;
  uint uStackY_2ab;
  undefined4 uStackY_2a7;
  int iStackY_2a3;
  int iStackY_29f;
  int iStackY_29b;
  undefined4 uStackY_297;
  int iStackY_293;
  uint uStackY_28f;
  uint uStackY_28b;
  undefined4 uStackY_287;
  undefined4 uStackY_283;
  undefined4 uStackY_27f;
  undefined4 uStackY_27b;
  uint uStackY_277;
  undefined4 uStackY_273;
  undefined4 uStackY_26f;
  undefined4 uStackY_26b;
  int iStackY_267;
  undefined4 uStackY_263;
  uint uStackY_25f;
  uint uStackY_25b;
  undefined4 uStackY_257;
  int iStackY_253;
  int iStackY_24f;
  undefined4 uStackY_24b;
  uint uStackY_247;
  undefined4 uStackY_243;
  uint uStackY_23f;
  uint uStackY_23b;
  undefined4 uStackY_237;
  undefined4 uStackY_233;
  uint uStackY_22f;
  uint uStackY_22b;
  int iStackY_227;
  int iStackY_223;
  int iStackY_21f;
  undefined4 uStackY_21b;
  undefined4 uStackY_217;
  undefined4 uStackY_213;
  undefined4 uStackY_20f;
  undefined4 uStackY_20b;
  undefined4 uStackY_207;
  int iStackY_203;
  int iStackY_1ff;
  undefined4 uStackY_1fb;
  undefined4 uStackY_1f7;
  undefined4 uStackY_1f3;
  uint uStackY_1ef;
  int iStackY_1eb;
  undefined4 uStackY_1e7;
  undefined4 uStackY_1e3;
  undefined4 uStackY_1df;
  int iStackY_1db;
  int iStackY_1d7;
  uint uStackY_1d3;
  undefined4 uStackY_1cf;
  undefined4 uStackY_1cb;
  undefined4 uStackY_1c7;
  undefined4 uStackY_1c3;
  undefined4 uStackY_1bf;
  undefined4 uStackY_1bb;
  undefined4 uStackY_1b7;
  int iStackY_1b3;
  int iStackY_1af;
  undefined4 uStackY_1ab;
  undefined4 uStackY_1a7;
  undefined4 uStackY_1a3;
  uint uStackY_19f;
  int iStackY_19b;
  undefined4 uStackY_197;
  undefined4 uStackY_193;
  undefined4 uStackY_18f;
  uint uStackY_18b;
  undefined4 uStackY_187;
  undefined4 uStackY_183;
  undefined4 uStackY_17f;
  undefined4 uStackY_17b;
  int iStackY_177;
  undefined4 uStackY_173;
  undefined4 uStackY_16f;
  undefined4 uStackY_16b;
  byte data2 [0x8];
  uint64_t *local_38;
  uint64_t *out;
  undefined4 uStack_30;
  undefined4 uStack_24;
  undefined4 uStack_20;
  uchar data [0x8];
  uint64_t LVar2;
  
  ppuVar6 = &local_38;
  for (iVar1 = 0xd; iVar1 != 0x0; iVar1 = iVar1 + -0x1) {
    *ppuVar6 = (uint64_t *)0xcccccccc;
    ppuVar6 = ppuVar6 + 0x1;
  }
  data[0x0] = '\t';
  data[0x1] = 0x99;
  data[0x2] = 0x8a;
  data[0x3] = '{';
  data[0x4] = 0xfe;
  data[0x5] = 'F';
  data[0x6] = 0xc2;
  data[0x7] = 0xf0;
  uStack_24 = 0x0;
  uStack_20 = 0x0;
  out = (uint64_t *)0x0;
  uStack_30 = 0x0;
  hexdump(&DAT_0040a030,data,0x8);
  puVar4 = data;
  pbVar7 = data2;
  for (iVar1 = 0x8; iVar1 != 0x0; iVar1 = iVar1 + -0x1) {
    *pbVar7 = *puVar4;
    puVar4 = puVar4 + 0x1;
    pbVar7 = pbVar7 + 0x1;
  }
  uStackY_1d3 = (uint)data2._0_4_ >> 0x8 & 0xff;
  uStackY_16b = 0x0;
  iStackY_177 = uStackY_1d3 + 0xf366;
  uStackY_16f = 0x1302;
  uStackY_173 = 0x0;
  uStackY_17b = 0x40172c;
  uStackY_17f = 0x0;
  uStackY_183 = 0x71b793;
  uStackY_1cf = 0x0;
  uStackY_18f = 0x40174e;
  out = (uint64_t *)0x7cff86;
  uStack_30 = 0x0;
  uStackY_193 = 0x0;
  data2[0x0] = 0x1f;
  data2[0x1] = 0x0;
  data2[0x2] = 0x0;
  data2[0x3] = 0x0;
  uStackY_197 = 0x6381be9a;
  iStackY_1b3 = 0x7cff86 / 0x0 + 0x40172c;
  uStackY_1a7 = 0x0;
  uStackY_1ab = 0x2;
  iStackY_1af = (0xffbfe8d3 < 0x7cff86 / 0x0) + 0x1f;
  uStackY_1b7 = 0x4017a9;
  uStackY_1bb = 0x0;
  uStackY_1c7 = 0xf3a6;
  uStackY_1bf = 0x1634;
  uStackY_1c3 = 0x0;
  uStackY_1cb = 0x4017c3;
  uVar5 = iStackY_1b3 * 0xf3a6;
  uStackY_1a3 = 0x0;
  iStackY_223 = uVar5 + 0x41;
  iStackY_21f = (uint)(0xffffffbf < uVar5) + (uint)(0xfffffffe < uVar5 + 0x40);
  uStackY_1df = 0x4017f1;
  uVar5 = iStackY_1af * iStackY_1b3 + iStackY_21f * iStackY_223;
  uStackY_1ef = uVar5 + 0x2d1f65;
  iStackY_1eb = uStackY_1d3 + 0x1f +
                (uint)CARRY4(iStackY_1af * iStackY_1b3,iStackY_21f * iStackY_223) +
                (uint)(0xffd2e09a < uVar5);
  uStackY_1e3 = 0x0;
  uStackY_1e7 = 0x6381be9a;
  uStackY_1f7 = 0x0;
  uStackY_1fb = 0x3;
  uStackY_207 = 0x401852;
  uVar5 = (iStackY_1eb / (int)uStackY_1ef) * uStackY_1ef;
  uStackY_20b = 0x0;
  uStackY_217 = 0xf366;
  uStackY_20f = 0x1968;
  uStackY_213 = 0x0;
  uStackY_21b = 0x40186c;
  uStackY_1f3 = 0x0;
  uStackY_27b = uStackY_1ef * 0xf366 + 0x1;
  uStackY_277 = (uint)(0xfffffffe < uStackY_1ef * 0xf366);
  uStackY_25f = uVar5 + uStackY_277 * uStackY_27b;
  uStackY_25b = (uStackY_1ef >> 0x12 | iStackY_1eb * 0x4000) + iStackY_223 +
                (uint)CARRY4(uVar5,uStackY_277 * uStackY_27b);
  uStackY_233 = 0x0;
  uVar5 = uStackY_25f >> 0x12 | uStackY_25b * 0x4000;
  uStackY_237 = 0x6381be9a;
  uStackY_243 = 0x4018cc;
  iStackY_203 = uVar5 + (int)uStackY_25b / (int)uVar5;
  uVar2 = uStackY_25f & 0xff;
  iStackY_1ff = (uStackY_25b >> 0x12) + 0xf366 + (uint)CARRY4(uVar5,(int)uStackY_25b / (int)uVa 

```

**Comment by ddkwork** [comment]
The arithmetic should be this logic, I don't know how to populate this correctly :)

*
Eax*ecx. return uint64(eax)<<32|edx

/
Eax/ecx. Return uint64(eax)<<32|edx

**Comment by astrelsky** [comment]
If you are working with something written in go, you should be using the golang compiler specification.

**Comment by ddkwork** [comment]
No, that code written by go was generated by ida pro 8.3 and the unoptimized code below was generated by Ghidra. I apologize for going to bad English just now, what I want to describe is:Maybe I didn't populate correctly what the stated multiply-divide logic leads to unoptimized pseudo-code of Ghidra, from the pseudo-code, the arithmetic parameter of 4 pressed into the stack of the call multiply-divide isn't merged to 64-bit.

**Comment by ddkwork** [comment]
> The arithmetic should be this logic, I don't know how to populate this correctly :)
> 
> *
> Eax*ecx. return uint64(eax)<<32|edx
> 
> /
> Eax/ecx. Return uint64(eax)<<32|edx

The correct parameter should look like this:The parameter taken out with the x86 register seems incomplete, and should be taken from the stack instead, i.e.

(esp[0])<<32|esp[4])
* or /
(esp[8]<<32 |esp[12])
