### ISSUE TITLE
BasicCompilerSpec.java: error when handling deadcodedelay in cspec

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4323]
**Describe the bug**
The ``BasicCompilerSpec`` is initialized from an xml file by the ``restoreXml`` function.
When the ``deadcodedelay`` element with ``space="stack"`` is present, execution enters ``getAddressSpace("stack")``. At this point, the ``stackSpace`` has not been defined, unless a ``stackpointer`` element was seen earlier in the xml. This results in an error, as the ``stackSpace`` will only be initialized after the parser has iterated through all the elements.

```
	private void restoreDeadCodeDelay(XmlPullParser parser) {
...
		XmlElement el = parser.start();
		AddressSpace space = getAddressSpace(el.getAttribute("space"));
...
	}

	@Override
	public AddressSpace getAddressSpace(String spaceName) {
		AddressSpace space;
		if (SpaceNames.STACK_SPACE_NAME.equals(spaceName)) {
			space = stackSpace;
		}
...
		if (space == null) {
			throw new SleighException("Unknown address space: " + spaceName);
		}
		return space;
	}
```

**To Reproduce**
1. Add the element ``<deadcodedelay space="stack" delay="40"/>`` to a cspec file without a ``stackpointer`` element. I used x86-16.cspec
2. Open a binary with the corresponding architecture. This results in the following exception:
```
Open failed: ghidra.program.model.lang.CompilerSpecNotFoundException: Exception reading x86:LE:16:Real Mode/default(x86-16.cspec): Unknown address space: stack
java.io.IOException: Open failed: ghidra.program.model.lang.CompilerSpecNotFoundException: Exception reading x86:LE:16:Real Mode/default(x86-16.cspec): Unknown address space: stack
	at ghidra.program.database.ProgramContentHandler.getDomainObject(ProgramContentHandler.java:225)
	at ghidra.framework.data.GhidraFileData.getDomainObject(GhidraFileData.java:339)
	at ghidra.framework.data.GhidraFile.getDomainObject(GhidraFile.java:179)
	at ghidra.app.util.task.OpenProgramTask.openFileMaybeUgrade(OpenProgramTask.java:241)
	at ghidra.app.util.task.OpenProgramTask.openUnversionedFile(OpenProgramTask.java:206)
	at ghidra.app.util.task.OpenProgramTask.openDomainFile(OpenProgramTask.java:149)
	at ghidra.app.util.task.OpenProgramTask.run(OpenProgramTask.java:133)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Environment (please complete the following information):**
 - Ghidra Version: Ghidra master, commit c6cb8a0d

**Comment by caheckman** [comment]
The <stackpointer> element must be present and occur before other elements that reference the stack. There are other similar ordering requirements on the file.  With compiler specification files, as with other configuration files internal to Ghidra, its up to the developer who is creating or modifying the file to ensure that it is successfully parsed when Ghidra runs.
