### ISSUE TITLE
Listing: NPE when editing data settings

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4370]
**Describe the bug**
A Null Pointer Exception when attempting to change data settings for a selection with multiple strings
```
java.lang.NullPointerException
	at ghidra.app.plugin.core.data.AbstractSettingsDialog$1.isChangeAllowed(AbstractSettingsDialog.java:73)
	at ghidra.app.plugin.core.data.AbstractSettingsDialog.buildWorkPanel(AbstractSettingsDialog.java:216)
	at ghidra.app.plugin.core.data.AbstractSettingsDialog.buildPanel(AbstractSettingsDialog.java:131)
	at ghidra.app.plugin.core.data.AbstractSettingsDialog.<init>(AbstractSettingsDialog.java:82)
	at ghidra.app.plugin.core.data.DataSettingsDialog.<init>(DataSettingsDialog.java:45)
	at ghidra.app.plugin.core.data.DataPlugin.dataSettingsCallback(DataPlugin.java:596)
	at ghidra.app.plugin.core.data.DataPlugin.lambda$addActions$2(DataPlugin.java:162)
	at docking.action.builder.ActionBuilder$1.actionPerformed(ActionBuilder.java:48)
	at docking.PopupMenuHandler$1.run(PopupMenuHandler.java:63)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**To Reproduce**
1. Open the Defined Strings window
2. Select two strings and make selection
3. Right click the listing -> data -> settings

**Expected behavior**
It should be possible to change the data settings for a selection, given that there is a check which returns ``Common data settings were not found across selection`` for invalid selections.

**Environment (please complete the following information):**
 - Ghidra master (commit c6cb8a0d)

**Context**
Stumbled upon this thanks to @astrelsky on #4366 while trying to mark multiple strings as constant

**Comment by astrelsky** [comment]
You can just set the default settings for the string data type to constant. Since the decompiler cant directly use the dynamic string data type and will use char * instead you don't have to worry about having one written to. The first thing I do in every program is set the default settings for string and unicode.


This isn't related to the issue at hand but it's good info.
