### ISSUE TITLE
[question] ghidra + python : createData() and other issues

### ISSUE THREAD

**Issue by fenugrec** [NationalSecurityAgency/ghidra#4405]
I find it very, very difficult to try and use what I find in the builtin API docs, from a python script or the console.
Here's a typical transcript of my attempts to use createData() to create a simple pointer :

```
>>> createData(toAddr(0x10), Pointer)
Traceback (most recent call last):
  File "python", line 1, in <module>
NameError: name 'Pointer' is not defined


>>> createData(toAddr(0x10), PointerDataType)
Traceback (most recent call last):
  File "python", line 1, in <module>
NameError: name 'PointerDataType' is not defined

>>> getDataTypes("pointer")
array(ghidra.program.model.data.DataType, [pointer])

#### maybe no caps ?

>>> createData(toAddr(0x10), pointer)
Traceback (most recent call last):
  File "python", line 1, in <module>
NameError: name 'pointer' is not defined
```

Ok, I marked location 0 as a pointer via the Codebrowser. I should be able to get the type from there...

```
>>> getDataAt(toAddr(0x0)).dataType
pointer

### thanks

>>> createData(toAddr(0x10), ghidra.program.model.data.DataType.pointer)
Traceback (most recent call last):
  File "python", line 1, in <module>
AttributeError: type object 'ghidra.program.model.data.DataType' has no attribute 'pointer'
```

This is absolutely horrible
```
>>> createData(toAddr(0x10), getDataAt(toAddr(0x0)).dataType)
addr 00000104

### what if I try to import stuff ?

>>> from ghidra.program.model.data import DataType
>>> createData(toAddr(0x14), pointer)
Traceback (most recent call last):
  File "python", line 1, in <module>
NameError: name 'pointer' is not defined


>>> from ghidra.program.model.data import PointerDataType
>>> createData(toAddr(0x14), PointerDataType)
Traceback (most recent call last):
  File "python", line 1, in <module>
TypeError: createData(): 2nd arg can't be coerced to ghidra.program.model.data.DataType

### Come on, seriously ?

>>> from ghidra.program.model.data import Pointer
>>> createData(toAddr(0x14), Pointer)
Traceback (most recent call last):
  File "python", line 1, in <module>
TypeError: createData(): 2nd arg can't be coerced to ghidra.program.model.data.DataType


>>> createData(toAddr(0x14), Pointer.getDataType())
Traceback (most recent call last):
  File "python", line 1, in <module>
TypeError: getDataType(): expected 1 args; got 0
```

I don't know what else to try, and I don't understand how I'm supposed to be mapping stuff from java to python in cases like this. Can't find anything equivalent in the example scripts either.

**Comment by dev747368** [comment]
> >>> from ghidra.program.model.data import PointerDataType
> >>> createData(toAddr(0x14), PointerDataType)

What happens if you put "()" at the end of PointerDataType?

```createData(toAddr(0x14), PointerDataType())```

**Comment by mumbel** [comment]
this seems like a basic programming/REPL issue and not really ghidra/API.  

Its returning the type, you're not assigning it

```python
>>> ptr_type = getDataTypes("pointer")
>>> data = createData(toAddr(0x10), ptr_type[0])
```

**Comment by fenugrec** [comment]
> What happens if you put "()" at the end of PointerDataType?

Of course, that works...

>>> ptr_type = getDataTypes("pointer")
>>> data = createData(toAddr(0x10), ptr_type[0])

And that too.
Thanks.
