### ISSUE TITLE
Possible to handle Scalar bigger than 64 bits?

### ISSUE THREAD

**Issue by felberj** [NationalSecurityAgency/ghidra#442]
I am trying to add EVM (from Ethereum) as a processor.

EVM supports numbers up to 256 bits.

So there is for example the PUSH15 instruction, which pushes a 15 byte (120 bits) value to the stack.

I tried to implement it like this:

evm.sinc:
```
define token data120 (120)
     imm120 = (0, 119)
    ;

:PUSH imm120 is op=0x6e; imm120 {
    SP = SP - 15;
    *:15 SP = imm120;
}
```

But I get an exception from the Scalar class:

`java.lang.IllegalArgumentException: Bit length must be >= 1 and <= 64`

```
ERROR Command Failure: An unexpected error occurred while processing the command: Disassemble (BackgroundCommandTask) java.lang.IllegalArgumentException: Bit length must be >= 1 and <= 64
	at ghidra.program.model.scalar.Scalar.<init>(Scalar.java:62)
	at ghidra.app.plugin.processors.sleigh.SleighInstructionPrototype.addHandleObject(SleighInstructionPrototype.java:1474)
	at ghidra.app.plugin.processors.sleigh.SleighInstructionPrototype.getOpRepresentationList(SleighInstructionPrototype.java:718)
	at ghidra.program.database.code.CodeManager.addReferencesForInstruction(CodeManager.java:2915)
	at ghidra.program.database.code.CodeManager.addInstruction(CodeManager.java:674)
	at ghidra.program.database.code.CodeManager.addInstructions(CodeManager.java:531)
	at ghidra.program.database.ListingDB.addInstructions(ListingDB.java:412)
	at ghidra.program.disassemble.Disassembler.disassemble(Disassembler.java:610)
	at ghidra.program.disassemble.Disassembler.disassemble(Disassembler.java:473)
	at ghidra.app.cmd.disassemble.DisassembleCommand.doDisassembly(DisassembleCommand.java:223)
	at ghidra.app.cmd.disassemble.DisassembleCommand.applyTo(DisassembleCommand.java:157)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:101)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

So my question:

Is it possible to add the EVM to Ghidra or are its numbers too big?

Probably problem like #206

**Comment by Danil6969** [comment]
Only varnodes can be of any number of bytes, even more than 8. The problem is in size of literals which must be splitted into smaller parts and then copied sequentially in some temporary register, not just unique, pcode varnode. Only then perform store operation. For example, here should be two unsigned imm fields so they are expanded by zero extension. They will be displayed as imm1, imm2, lower part in the right, higher in the left. Then they are copied to any dummy register and stored this way:
tmpImm[0,64] = imm2;
tmpImm[64,56] = imm1;
SP = SP - 15;
*:15 SP = tmpImm; # or *:15 SP = tmpImm[0,120];
Where tmpImm may be defined like this:
define register offset=0x100 size=15 [tmpImm];
Or you can do some bit shifts along with bitwise or over such numbers to achieve another result which will probably produce SUBs.
