### ISSUE TITLE
Listing: OOB exception when building XRef Field when max xrefs to display is set to 1

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4445]
**Describe the bug**
Setting the Maximum Number of XREFs to display in the listing to 1 results in the following exception on some xrefs: 
```
Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at docking.widgets.fieldpanel.field.VerticalLayoutTextField.calculateHeight(VerticalLayoutTextField.java:144)
	at docking.widgets.fieldpanel.field.VerticalLayoutTextField.<init>(VerticalLayoutTextField.java:120)
	at docking.widgets.fieldpanel.field.FlowLayoutTextField.<init>(FlowLayoutTextField.java:62)
	at ghidra.app.util.viewer.field.XRefFieldFactory.createWrappingXrefRow(XRefFieldFactory.java:508)
	at ghidra.app.util.viewer.field.XRefFieldFactory.getFieldByFunction(XRefFieldFactory.java:401)
	at ghidra.app.util.viewer.field.XRefFieldFactory.getField(XRefFieldFactory.java:300)
	at ghidra.app.util.viewer.format.Row.getLayout(FieldFormatModel.java:502)
	at ghidra.app.util.viewer.format.FieldFormatModel.addLayouts(FieldFormatModel.java:102)
	at ghidra.app.util.viewer.listingpanel.ProgramBigListingModel.doGetLayout(ProgramBigListingModel.java:189)
	at ghidra.app.util.viewer.listingpanel.ProgramBigListingModel.getLayout(ProgramBigListingModel.java:124)
	at ghidra.app.util.viewer.listingpanel.ListingModelAdapter.getLayout(ListingModelAdapter.java:129)
	at docking.widgets.fieldpanel.FieldPanel$CursorHandler.doSetCursorPosition(FieldPanel.java:1984)
	at docking.widgets.fieldpanel.FieldPanel$CursorHandler.updateCursor(FieldPanel.java:2183)
	at docking.widgets.fieldpanel.FieldPanel.modelSizeChanged(FieldPanel.java:1016)
	at ghidra.app.util.viewer.listingpanel.ListingModelAdapter.modelSizeChanged(ListingModelAdapter.java:193)
	at ghidra.app.util.viewer.listingpanel.ListingModelAdapter.setAddressSet(ListingModelAdapter.java:527)
	at ghidra.app.util.viewer.listingpanel.ListingPanel.setView(ListingPanel.java:810)
	at ghidra.app.plugin.core.codebrowser.CodeViewerProvider.setView(CodeViewerProvider.java:985)
	at ghidra.app.plugin.core.codebrowser.AbstractCodeBrowserPlugin.viewChanged(AbstractCodeBrowserPlugin.java:121)
	at ghidra.app.plugin.core.codebrowser.CodeBrowserPlugin.processEvent(CodeBrowserPlugin.java:150)
```

**Environment (please complete the following information):**
Commit b8425e8

**Comment by dragonmacher** [comment]
Do you have any sense which type of xref causes this issue?  I tried the setting and am not seeing the exception.

**Comment by sad-dev** [comment]
The following are from a 10.1.4 release build of Ghidra - in general, I don't notice a pattern.
Group by Function was checked for me, which appears necessary to reproduce it.

![image](https://user-images.githubusercontent.com/55233728/179261808-5486024d-c38e-4c95-b74b-e9203895f662.png)
![image](https://user-images.githubusercontent.com/55233728/179261083-b4a7bb61-ac86-4f25-a94a-80268457284c.png)
![image](https://user-images.githubusercontent.com/55233728/179261222-583337e7-9de1-4d13-a8a9-6e4dc5a67b2b.png)

**Comment by dragonmacher** [comment]
> Group by Function was checked for me, which appears necessary to reproduce it.

That was what I needed on to get the error.  Thanks.
