### ISSUE TITLE
SLEIGH `context` example does not compile

### ISSUE THREAD

**Issue by rpitasky** [NationalSecurityAgency/ghidra#4528]
**Describe the bug**
Attempting to compile the following example code from with the provided SLEIGH compiler in `support/sleigh` of the latest release produces an error.

The code, from section 8.1 of the SLEIGH docs: https://github.com/NationalSecurityAgency/ghidra/blob/aad60ecdd319f4db6e5cbafc0516db218e56988b/GhidraDocs/languages/html/sleigh_context.html#L98-L116

I receive the following error when attempting to compile this seemingly-complete example:
```
me@my-computer MINGW64 /c/Program Files/ghidra/support
$ ./sleigh ~/path/to/test/file.slaspec
java version "18.0.2" 2022-07-19
Java(TM) SE Runtime Environment (build 18.0.2+9-61)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2+9-61, mixed mode)
INFO  Using log config file: jar:file:/<snip>/ghidra/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)
INFO  Using log file: C:\path\to\application.log (LoggingInitialization)
ERROR file.slaspec:10: unknown varnode 'statusreg' in context definition (SleighCompile)
ERROR file.slaspec:16: unknown family or operand 'mode' in pattern equation (SleighCompile)
ERROR Unrecoverable error(s), halting compilation (SleighCompile) java.lang.NullPointerException: Cannot invoke "org.antlr.runtime.tree.Tree.getText()" because "s" is null
        at ghidra.sleigh.grammar.SleighCompiler.pequation(SleighCompiler.java:4250)
        at ghidra.sleigh.grammar.SleighCompiler.pequation(SleighCompiler.java:4194)
        at ghidra.sleigh.grammar.SleighCompiler.bitpattern(SleighCompiler.java:3623)
        at ghidra.sleigh.grammar.SleighCompiler.constructor(SleighCompiler.java:3475)
        at ghidra.sleigh.grammar.SleighCompiler.constructorlike(SleighCompiler.java:3034)
        at ghidra.sleigh.grammar.SleighCompiler.root(SleighCompiler.java:482)
        at ghidra.pcodeCPort.slgh_compile.SleighCompile.run_compilation(SleighCompile.java:1810)
        at ghidra.pcodeCPort.slgh_compile.SleighCompileLauncher.runMain(SleighCompileLauncher.java:263)
        at ghidra.pcodeCPort.slgh_compile.SleighCompileLauncher.launch(SleighCompileLauncher.java:50)
        at ghidra.GhidraLauncher.launch(GhidraLauncher.java:59)
        at ghidra.Ghidra.main(Ghidra.java:47)
```

I believe the issue is that `statusreg` is not defined as a register first; inserting `define register offset=0x200 size=4 statusreg;` between lines 106 and 107 allows the example to work as intended.

**Comment by mumbel** [comment]
#1667 ?
