### ISSUE TITLE
AddressOutOfBoundsException debugging a win32 executable via GDB

### ISSUE THREAD

**Issue by jmillikin** [NationalSecurityAgency/ghidra#4534]
**Describe the bug**
I'm trying to debug a win32 executable in x86-64 Linux, via Wine and GDB. After starting the trace, Ghidra continually reports the following exception:

```
Offset must be between 0x0 and 0xffffffff, got 0x8000000000000000 instead!
ghidra.program.model.address.AddressOutOfBoundsException: Offset must be between 0x0 and 0xffffffff, got 0x8000000000000000 instead!
```

GDB is correctly reporting the architecture, so I suspect the bad offset is coming from within Ghidra:
```
(gdb) show arch
The target architecture is set automatically (currently i386)
```

**To Reproduce**
Setup of the GDB server:
```
$ sudo apt install gdb-mingw-w64 gdb-mingw-w64-target
$ wine --version
wine-7.15
$ wine /usr/share/win32/gdbserver.exe --version
GNU gdbserver (GDB) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
gdbserver is free software, covered by the GNU General Public License.
This gdbserver was configured as "i686-w64-mingw32"
$ file loganalysis.exe
loganalysis.exe: PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows
$ wine /usr/share/win32/gdbserver.exe localhost:10000 loganalysis.exe  logs/example.log 
```

In Ghidra, I create a debugger target "in GDB locally via GADP", with the GDB launch command `/usr/bin/i686-w64-mingw32-gdb`. Then I cancel the "launch process" dialog, and enter the following GDB commands to set a breakpoint shortly after the executable's entry point:

```
file ~/ghidra-projects/loganalysis.exe
target extended-remote :10000
break *0x004015fd
```

**Expected behavior**
I would have liked to be able to inspect dynamic runtime state of the process.

**Environment (please complete the following information):**
 - OS: x86-64 Linux (Ubuntu 20.04)
 - Java Version: Amazon Corretto 17 (`openjdk version "17.0.4.1" 2022-08-12 LTS`)
 - Ghidra Version: 10.2_DEV_20220818 (revision 2b959a34593dd5e3a8abfaffabdb5368123955fb)
 - Ghidra Origin: locally built

The most recent Ghidra release (10.1.5) fails with a different error about not being able to load the Visual Studio compiler spec, which is why I'm using a local build from Git HEAD.

**Additional context**
Longer snippet of the exception:

```
Offset must be between 0x0 and 0xffffffff, got 0x8000000000000000 instead!
ghidra.program.model.address.AddressOutOfBoundsException: Offset must be between 0x0 and 0xffffffff, got 0x8000000000000000 instead!
	at ghidra.program.model.address.AbstractAddressSpace.makeValidOffset(AbstractAddressSpace.java:620)
	at ghidra.program.model.address.GenericAddressSpace.makeValidOffset(GenericAddressSpace.java:21)
	at ghidra.program.model.address.GenericAddress.<init>(GenericAddress.java:55)
	at ghidra.program.model.address.GenericAddressSpace.getAddress(GenericAddressSpace.java:88)
	at ghidra.app.plugin.core.debug.mapping.DefaultDebuggerMemoryMapper.toSameNamedSpace(DefaultDebuggerMemoryMapper.java:41)
	at ghidra.app.plugin.core.debug.mapping.DefaultDebuggerMemoryMapper.targetToTrace(DefaultDebuggerMemoryMapper.java:60)
	at ghidra.app.plugin.core.debug.mapping.DebuggerMemoryMapper.targetToTrace(DebuggerMemoryMapper.java:55)
	at ghidra.app.plugin.core.debug.service.model.RecorderSimpleMemory.getAccessibleMemory(RecorderSimpleMemory.java:108)
	at ghidra.app.plugin.core.debug.service.model.DefaultProcessRecorder.getAccessibleProcessMemory(DefaultProcessRecorder.java:65)
	at ghidra.app.plugin.core.debug.service.model.DefaultTraceRecorder.getAccessibleMemory(DefaultTraceRecorder.java:526)
	at ghidra.app.plugin.core.debug.gui.action.VisibleROOnceAutoReadMemorySpec.readMemory(VisibleROOnceAutoReadMemorySpec.java:62)
	at ghidra.app.plugin.core.debug.gui.action.DebuggerReadsMemoryTrait.doAutoRead(DebuggerReadsMemoryTrait.java:253)
	at ghidra.app.plugin.core.debug.gui.action.DebuggerReadsMemoryTrait.goToCoordinates(DebuggerReadsMemoryTrait.java:248)
	at ghidra.app.plugin.core.debug.gui.listing.DebuggerListingProvider.goToCoordinates(DebuggerListingProvider.java:1057)
	at ghidra.app.plugin.core.debug.gui.listing.DebuggerListingProvider.coordinatesActivated(DebuggerListingProvider.java:1064)
	at ghidra.app.plugin.core.debug.gui.listing.DebuggerListingPlugin.lambda$processEvent$5(DebuggerListingPlugin.java:312)
	at ghidra.app.plugin.core.debug.gui.listing.DebuggerListingPlugin.allProviders(DebuggerListingPlugin.java:343)
	at ghidra.app.plugin.core.debug.gui.listing.DebuggerListingPlugin.processEvent(DebuggerListingPlugin.java:312)
```

**Comment by jmillikin** [comment]
If anyone else has the same problem, a temporary workaround is to edit `DefaultMemoryRecorder.java` and make it skip offered memory regions:

```
// in void offerProcessRegion(TargetMemoryRegion region)
if (region.getRange().getMinAddress().getOffset() == 0x8000000000000000L) {
    return;
}
```

**Comment by d-millar** [comment]
@jmillikin I think I know what's going on here, and it's definitely a bug but I need to talk to some of the other folks to see if we have an actual solution.  The basic issue is that many targets don't support "info proc mappings".  Without it, we don't have a real picture of the memory layout.  When that fails, our default action is to assume the entire address space is valid memory, which would be OK if we used that address space of the target, but (and am guessing here) we may be defaulting to the address range of the host.  An alternate workaround to the one you've described is to define "info proc mappings" in a file that you "source" on start-up.  There's a sample script to do this in Ghidra/Debug/Debugger-agent-gdb/data/scripts/define_info_proc_mappings, if you'd like to try that out.

**Comment by jmillikin** [comment]
Thanks for the quick reply!

I tried sourcing a proc_mappings file containing the following:

```
define info proc mappings
echo 0x0 0xFFFFFFFF 0x100000000 0x0 mem \n
end
```

The same error appeared, but then I found https://github.com/NationalSecurityAgency/ghidra/issues/3071 which recommended defining proc mappings before connecting to the remote GDB. That was successful!

> When that fails, our default action is to assume the entire address space is valid memory, which would be OK if we used that address space of the target, but (and am guessing here) we may be defaulting to the address range of the host.

That would match the behavior I saw.

I'm new to Ghidra so this might not be a good suggestion, but would it make sense to do one of these?
1. Infer based on the recording parameters, such that x86-32 code with no proc mappings defaults to a 32-bit address space, or
2. Alert the user in some way if the target arch is different from the host and no proc mappings could be queried.

**Comment by d-millar** [comment]
@jmillikin Yes, per your suggestion, the first option is definitely the right idea.  Just need to make sure we have a consistent way of retrieving the fact that the target OS is 32-bit that works even when “info proc mappings” does not.

**Comment by nsadeveloper789** [comment]
I believe this is a duplicate of #4345 . Different target architecture, but fundamentally the same problem. Might mean we need to move it up the queue a little :) .

**Comment by jmillikin** [comment]
I did some exploring with GDB's remote server commands and was able to put together an implementation of `info proc mappings` that works reasonably for Wine.

![wine-memory-regions](https://user-images.githubusercontent.com/646128/185780027-39e28f78-fed8-431a-acf7-07e7e6249443.png)

First, a new GDB command `remote-proc-mappings` that fetches the Linux `/proc/{pid}/maps` file from the gdbserver and applies light reformatting:
```python
import contextlib
import os
import threading

@contextlib.contextmanager
def pipe_fds():
    r_fd, w_fd = os.pipe()
    r_file = os.fdopen(r_fd, mode="rb")
    w_file = os.fdopen(w_fd, mode="wb")
    try:
        yield (r_file, w_file)
    finally:
        r_file.close()
        w_file.close()

class ReadThread(threading.Thread):
    def __init__(self, reader):
        super(ReadThread, self).__init__()
        self.__r = reader
        self.bytes = None

    def run(self):
        self.bytes = bytearray(self.__r.read())

def reformat_line(raw_line):
    split = raw_line.decode("utf-8").split(None, 5)
    # split[0] range
    # split[1] mode
    # split[2] offset
    # split[3] major_minor
    # split[4] inode
    # split[5] object name
    start_addr_s, end_addr_s = split[0].split("-")
    start_addr = int(start_addr_s, 16)
    end_addr = int(end_addr_s, 16)
    if len(split) == 6:
        objfile = split[5]
    else:
        objfile = ""
    return "0x{:X} 0x{:X} 0x{:X} 0x{:X} {} {}\n".format(
        start_addr, end_addr,
        end_addr - start_addr,
        int(split[2], 16),
        split[1],
        objfile,
    )

class RemoteProcMappings(gdb.Command):
    def __init__(self):
        super(RemoteProcMappings, self).__init__("remote-proc-mappings", gdb.COMMAND_STATUS)

    def invoke(self, arg, from_tty):
        argv = gdb.string_to_argv(arg)
        if len(argv) != 1:
            gdb.write("usage: remote-proc-mappings PID\n", gdb.STDERR)
            return

        remote_pid = int(argv[0])

        with pipe_fds() as (r_file, w_file):
            read_thread = ReadThread(reader = r_file)
            read_thread.start()
            maps_path = "/proc/{}/maps".format(remote_pid)
            pipe_writer_path = "/dev/fd/{}".format(w_file.fileno())
            gdb.execute("remote get {} {}".format(maps_path, pipe_writer_path))
            w_file.close()
            read_thread.join()
            raw_bytes = read_thread.bytes

        for raw_line in raw_bytes.split(b"\n"):
            if raw_line:
                gdb.write(reformat_line(raw_line))

RemoteProcMappings()
```

Second, since Wine does its very best to prevent looking up UNIX process IDs for a Win32 process, a command to query the inferior's PID by direct syscall:

```shell
define getpid-linux-i386
  # MOV eax,20 [SYS_getpid]
  # INT 0x80
  # RET
  set $linux_getpid = {int (void)}($esp-7)
  set {unsigned char[8]}($linux_getpid) = {\
    0xB8, 0x14, 0x00, 0x00, 0x00, \
    0xCD, 0x80, \
    0xC3 \
  }
  output $linux_getpid()
end
```

Those can then be combined to override `info proc mappings`:
```
define info proc mappings
  python
remote_pid = gdb.execute("getpid-linux-i386", to_string=True)
gdb.execute("remote-proc-mappings {}".format(remote_pid))
  end
end
```

**Comment by d-millar** [comment]
Wow - that’s an excellent piece of work.  We were just discussing options for connecting to full-system emulators, and this suggests an approach we hadn’t really considered.  Thanks so much for posting this!

**Comment by nsadeveloper789** [comment]
OK. I found the obvious. I can get the address size of the current architecture by asking GDB to `print sizeof(int*)`.

**Comment by nsadeveloper789** [comment]
@jmillikin As for the code you posted above for remote wine targets: This could probably just be included in `Debug/Debugger-agent-gdb/data/scripts` as is. Would you be willing to submit a PR for that?

**Comment by jmillikin** [comment]
@nsadeveloper789 Sure, I'd be fine with those scripts being upstreamed into the Ghidra repo.

PR https://github.com/NationalSecurityAgency/ghidra/pull/4546 sent.
