### ISSUE TITLE
Decompiler sometimes fails to highlight matching braces

### ISSUE THREAD

**Issue by Madghostek** [NationalSecurityAgency/ghidra#4549]
**Describe the bug**
In certain situations the decompiler window will fail to highlight braces and will throw an exception, however it only happens when clicking the opening one. I think it has to do with goto labels being placed inside pairs of braces (but not always).

I attach two .asm files, one that triggers the bug after viewing decompilation, and one that doesn't, which has 3 instructions removed.

I tried to make them as minimal as possible, but I was able to remove only so much lines, removing more makes decompiler realise it can simplify the code further and the broken braces disappear.

**To Reproduce**
1. Decompile provided example (function `_breaks`)
2. Go to line 24 and click on the `else` **opening** bracket, above `lab1`

**Expected behavior**
Java exception window appears with `java.util.EmptyStackException`
(Clicking on the bottom bracket works, and succesfully highlights the top one)

**Screenshots**
![example](https://user-images.githubusercontent.com/28148202/186469562-12cf20ad-2d47-49f0-bf64-22ddcb74934f.png)

**Attachments**
Here's two asm files (plus a basic .c file with weird batch script to build a complete .exe), it might be easier to just run the decompiler on the .asm file directly somehow.
[example.zip](https://github.com/NationalSecurityAgency/ghidra/files/9417859/example.zip)

Here's a final exe too if that's acceptable, it has debug information from gcc (function `_breaks` at `0x00401511`)
[program.zip](https://github.com/NationalSecurityAgency/ghidra/files/9417917/program.zip)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 17.0.2
 - Ghidra Version: 10.1.5
 - Ghidra Origin: official Github

**Additional context**
Full error log
```
java.util.EmptyStackException
	at java.base/java.util.Stack.peek(Stack.java:101)
	at java.base/java.util.Stack.pop(Stack.java:83)
	at ghidra.app.decompiler.component.DecompilerUtils.getMatchingBrace(DecompilerUtils.java:592)
	at ghidra.app.decompiler.component.ClangHighlightController.highlightBrace(ClangHighlightController.java:377)
	at ghidra.app.decompiler.component.ClangHighlightController.addHighlightBrace(ClangHighlightController.java:370)
	at ghidra.app.decompiler.component.LocationClangHighlightController.fieldLocationChanged(LocationClangHighlightController.java:53)
	at ghidra.app.decompiler.component.DecompilerPanel$PendingHighlightUpdate.doUpdate(DecompilerPanel.java:1216)
	at ghidra.app.decompiler.component.DecompilerPanel.lambda$new$0(DecompilerPanel.java:80)
	at ghidra.util.task.SwingUpdateManager.swingDoWork(SwingUpdateManager.java:108)
	at ghidra.util.task.AbstractSwingUpdateManager.swingExecutePendingWork(AbstractSwingUpdateManager.java:338)
	at ghidra.util.task.AbstractSwingUpdateManager.checkForWork(AbstractSwingUpdateManager.java:278)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by dragonmacher** [comment]
This may have something to do with the`label:` in that section of code being displayed.

**Comment by mumbel** [comment]
duplicate of #4242 ?

**Comment by dragonmacher** [comment]
> duplicate of #4242 ?

I think it has been fixed.  I will close the ticket.  If this is found again in the next release or in the current master branch, then we can reopen.

**Comment by mumbel** [comment]
@dragonmacher just checking, did you see that last comment I made in the other thread

**Comment by dragonmacher** [comment]
I did see the comment.  I was unable to reproduce the issue, so it must be very output dependent.
