### ISSUE TITLE
packFile fails when in script that executes via runScript

### ISSUE THREAD

**Issue by bdemick** [NationalSecurityAgency/ghidra#4561]
I am working on a script orchestrator in Java that uses `GhidraScript.runScript()` to execute pre and post scripts (a mix of Java and Python scripts) instead of jamming them into a long `analyzeHeadless` command. The final post script that runs exports the database as a .gzf like so:
```
    file_hash = currentProgram.getExecutableSHA256()
    gzf_path = os.path.join(out_dir, '{}.gzf'.format(file_hash))
    df = currentProgram.getDomainFile()
    outfile = File(gzf_path)
    end(True)
    df.packFile(outfile, monitor)
```

When run "directly" via `analyzeHeadless`, this works as expected. When it is executed via a call to runScript, it throws an exception:
```
Traceback (most recent call last):
  File "/Users/user/ghidra_scripts/python/export_to_gzf.py", line 43, in <module>
    df.packFile(outfile, monitor)
  File "/Users/user/ghidra_scripts/python/export_to_gzf.py", line 43, in <module>
    df.packFile(outfile, monitor)
	at db.DBHandle.saveAs(DBHandle.java:649)
	at db.DBHandle.saveAs(DBHandle.java:732)
	at ghidra.framework.store.db.PackedDatabase.packDatabase(PackedDatabase.java:625)
	at ghidra.framework.data.DomainFileProxy.packFile(DomainFileProxy.java:419)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
ghidra.util.exception.AssertException: ghidra.util.exception.AssertException: Can't save during transaction
``` 

This looks similar to https://github.com/NationalSecurityAgency/ghidra/issues/2127, but of course this code already calls `end(True)`. I added `saveProgram(currentProgram)` to the orchestrator script after runScript is called, the export seems to complete, but I also see an exception thrown (hard to determine provenance, but I think it's from the saveProgram call in the orchestrator script):
```
ghidra.util.exception.DuplicateFileException: /file_name already exists.
	at ghidra.framework.store.local.IndexedLocalFileSystem.allocateItemStorage(IndexedLocalFileSystem.java:798)
	at ghidra.framework.store.local.LocalFileSystem.createDatabase(LocalFileSystem.java:502)
	at ghidra.framework.store.local.LocalFileSystem.createDatabase(LocalFileSystem.java:49)
	at ghidra.framework.data.DBContentHandler.createFile(DBContentHandler.java:59)
	at ghidra.program.database.ProgramContentHandler.createFile(ProgramContentHandler.java:57)
	at ghidra.framework.data.GhidraFolderData.createFile(GhidraFolderData.java:923)
	at ghidra.framework.data.GhidraFolder.createFile(GhidraFolder.java:297)
	at ghidra.app.util.headless.HeadlessAnalyzer.processFileWithImport(HeadlessAnalyzer.java:1586)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1689)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1754)
	at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:445)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:121)
	at ghidra.GhidraLauncher.launch(GhidraLauncher.java:59)
	at ghidra.Ghidra.main(Ghidra.java:47)
```

If I move the saveProgram call into the gzf exporting script like so:
```
    api = FlatProgramAPI(currentProgram)
    api.saveProgram(currentProgram)
    file_hash = currentProgram.getExecutableSHA256()
    gzf_path = os.path.join(out_dir, '{}.gzf'.format(file_hash))
    df = currentProgram.getDomainFile()
    outfile = File(gzf_path)
    end(True)
    df.packFile(outfile, monitor)
```

I get an NPE:
```
Traceback (most recent call last):
  File "/Users/user/ghidra_scripts/python/export_to_gzf.py", line 43, in <module>
    api.saveProgram(currentProgram)
  File "/Users/user/ghidra_scripts/python/export_to_gzf.py", line 43, in <module>
    api.saveProgram(currentProgram)
	at ghidra.program.flatapi.FlatProgramAPI.getProjectRootFolder(FlatProgramAPI.java:2535)
	at ghidra.program.flatapi.FlatProgramAPI.saveProgram(FlatProgramAPI.java:2493)
	at ghidra.program.flatapi.FlatProgramAPI.saveProgram(FlatProgramAPI.java:2454)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
java.lang.NullPointerException: java.lang.NullPointerException
```

This is all using Ghidra 10.1.5. I figure this has to be something simple, but I'm missing something, and it appears to be some kind of side effect of invoking the script using `runScript`. Any guidance here is greatly appreciated!

**Comment by astrelsky** [comment]
From a quick peek at the implementations in `FlatProgramAPI` and `GhidraScript` I see that `getProjectRootFolder` is handled differently in `GhidraScript` in headless mode.

Instead of this:

```python
api = FlatProgramAPI(currentProgram)
api.saveProgram(currentProgram)
```

try this:

```python
saveProgram(currentProgram)
```

**Comment by bdemick** [comment]
I ended up calling `saveProgram` in the orchestrator prior to invoking the `runScript` call for the gzf-exporting script, and that appears to have at least prevented the `Can't save during transaction` error. Will also give it a shot within the gzf script itself to see if that also works. Thanks for the suggestion!
