### ISSUE TITLE
NullPointerException `ghidra.program.model.data.DataTypeManager.getUniversalID()`

### ISSUE THREAD

**Issue by FlashHit** [NationalSecurityAgency/ghidra#4578]
```
Cannot invoke "ghidra.program.model.data.DataTypeManager.getUniversalID()" because the return value of "ghidra.program.model.data.DataType.getDataTypeManager()" is null
java.lang.NullPointerException: Cannot invoke "ghidra.program.model.data.DataTypeManager.getUniversalID()" because the return value of "ghidra.program.model.data.DataType.getDataTypeManager()" is null
	at ghidra.app.plugin.core.datamgr.tree.DataTypeNode.getCurrentDisplayText(DataTypeNode.java:269)
	at ghidra.app.plugin.core.datamgr.tree.DataTypeNode.<init>(DataTypeNode.java:48)
	at ghidra.app.plugin.core.datamgr.tree.CategoryNode.generateChildren(CategoryNode.java:63)
	at docking.widgets.tree.CoreGTreeNode.children(CoreGTreeNode.java:114)
	at docking.widgets.tree.GTreeNode.getChildCount(GTreeNode.java:171)
	at docking.widgets.tree.internal.GTreeModel.getChildCount(GTreeModel.java:97)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1457)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1272)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.ensurePathIsExpanded(VariableHeightLayoutCache.java:967)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.setExpandedState(VariableHeightLayoutCache.java:181)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.updateExpandedDescendants(BasicTreeUI.java:2003)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.treeExpanded(BasicTreeUI.java:4295)
	at java.desktop/javax.swing.JTree.fireTreeExpanded(JTree.java:2853)
	at java.desktop/javax.swing.JTree.setExpandedState(JTree.java:3766)
	at java.desktop/javax.swing.JTree.expandPath(JTree.java:2296)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.toggleExpandState(BasicTreeUI.java:2644)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.handleExpandControlClick(BasicTreeUI.java:2629)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.checkForClickInExpandControl(BasicTreeUI.java:2577)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:4090)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:4038)
	at docking.widgets.JTreeMouseListenerDelegate.fireMousePressed(JTreeMouseListenerDelegate.java:125)
	at docking.widgets.JTreeMouseListenerDelegate.mousePressed(JTreeMouseListenerDelegate.java:97)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6623)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2022-Jul-26 1543 EDT
Ghidra Version: 10.1.5
Java Home: C:\Program Files\Eclipse Adoptium\jdk-17.0.4.8-hotspot
JVM Version: Eclipse Adoptium 17.0.4
OS: Windows 11 10.0 amd64
Workstation: REVISION-PC
```

**Comment by dragonmacher** [comment]
This should not be possible in the normal work flow.  The implication is that a Data Type Manager was closed off of the Swing thread or that the JTree did not get notified that the manager was closed. 

Do you recall what you were doing when this happened?

**Comment by FlashHit** [comment]
@dragonmacher I added new things to the Data Type Manager, where I had 2 folders and both contained a struct called `TypeInfoData` then one had a pointer to the other one and the other one had a pointer to itself. Something like that.

But it is still happening. Basically I can't use the Data Type Manager at all rn. Whenever I try to access anything from it, it will throw this error.

**Comment by dragonmacher** [comment]
I see. It seems like it is in a bad state.  Does the issue go away if you restart Ghidra?

**Comment by FlashHit** [comment]
@dragonmacher no, this issue doesn't go away.
The error message changes slightly depending on what I do but the issue is the same.


```
Cannot invoke "ghidra.program.model.data.DataTypeManager.getName()" because the return value of "ghidra.program.model.data.DataType.getDataTypeManager()" is null
java.lang.NullPointerException: Cannot invoke "ghidra.program.model.data.DataTypeManager.getName()" because the return value of "ghidra.program.model.data.DataType.getDataTypeManager()" is null
	at ghidra.app.plugin.core.datamgr.util.DataTypeComparator.compare(DataTypeComparator.java:40)
	at ghidra.app.plugin.core.datamgr.util.DataTypeComparator.compare(DataTypeComparator.java:23)
	at java.base/java.util.TimSort.binarySort(TimSort.java:296)
	at java.base/java.util.TimSort.sort(TimSort.java:239)
	at java.base/java.util.Arrays.sort(Arrays.java:1307)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
	at java.base/java.util.Collections.sort(Collections.java:179)
	at ghidra.app.plugin.core.datamgr.archive.DataTypeIndexer$IndexerTask.run(DataTypeIndexer.java:140)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

---------------------------------------------------
Build Date: 2022-Jul-26 1543 EDT
Ghidra Version: 10.1.5
Java Home: C:\Program Files\Eclipse Adoptium\jdk-17.0.4.8-hotspot
JVM Version: Eclipse Adoptium 17.0.4
OS: Windows 11 10.0 amd64
Workstation: REVISION-PC
```

**Comment by FlashHit** [comment]
The struct types in the functions are still labelled correct and still show all the fields btw.

**Comment by dragonmacher** [comment]
When you added the types mentioned above, did you do so via a script or through the UI?  Are you manipulating types via a script?

**Comment by FlashHit** [comment]
Edit: I can modify these structs and point to other structs except the ones that I added when it broke, but the suggestions are missing thats why I thought only the default windows ones work.

**Comment by FlashHit** [comment]
> When you added the types mentioned above, did you do so via a script or through the UI? Are you manipulating types via a script?

No, I didn't use a script. I did it through the UI. I actually never used scripts with Ghidra.

**Comment by dragonmacher** [comment]
We would like to examine your binary.  Will you export your program as a .gzf file and then post it here?

**Comment by FlashHit** [comment]
Any way to share this file not in public?

**Comment by dragonmacher** [comment]
This is the only forum we are currently using for sharing.  

You can try to isolate the offending type(s).   First, make a copy of your binary in the front end so that you can freely make changes, reverting back to the original as desired.   In the copy, start removing the types you believe caused the issue.   

If there is only one or a few offending types, then finding them should be relatively easy.   Hopefully, once those types are removed, the issue will go away.    At that point, we would like you to re-create the types to see if the issue returns.   Being able to isolate the characteristics of that type should allow us to reproduce the issue by following the steps you used to create the type.   Once we understand the issue, we may be able to offer guidance on how to fix those types in the original version of your binary.

**Comment by FlashHit** [comment]
Okay but how can I remove the types? I cannot expand the folder in Data Type Manager UI.

**Comment by dragonmacher** [comment]
I see.  Scripting may be the only way to do this then.    You can try creating this new script via the Script Manager window.   

Press the new script button on the toolbar.  Create a Java scirpt.   Name it 'FindBadTypesScript.java' and then paste these contents in the editor:
```
import java.util.Iterator;

import ghidra.app.script.GhidraScript;
import ghidra.program.model.data.DataType;
import ghidra.program.model.data.DataTypeManager;

public class FindBadTypesScript extends GhidraScript {

	@Override
	protected void run() throws Exception {

		DataTypeManager dtm = currentProgram.getDataTypeManager();
		Iterator<DataType> types = dtm.getAllDataTypes();
		while (types.hasNext()) {
			DataType dt = types.next();
			if (dt.getDataTypeManager() == null) { 
				println("found bad type: " + dt.getDataTypePath());
			}
		}

	}
}
```

Let us know if the script produces any output when you run it.

**Comment by FlashHit** [comment]
Output:
```
FindBadTypesScript.java> Running...
FindBadTypesScript.java> found bad type: /TypeInfo
FindBadTypesScript.java> Finished!
```

**Comment by dragonmacher** [comment]
Now replace the contents of the `run()` method with this code and run the script again:

```
        DataTypeManager dtm = currentProgram.getDataTypeManager();
	DataType dt = dtm.getDataType("/TypeInfo");
	boolean success = dtm.remove(dt, TaskMonitor.DUMMY);
	println("removed dt?: " + success);
```

**Comment by FlashHit** [comment]
```
FindBadTypesScript.java:14: error: cannot find symbol
		boolean success = dtm.remove(dt, TaskMonitor.DUMMY);
		                                 ^
  symbol:   variable TaskMonitor
  location: class FindBadTypesScript
skipping C:\Users\Admin\ghidra_scripts\FindBadTypesScript.java
> Unable to locate script class: FindBadTypesScript.java
```

**Comment by dragonmacher** [comment]
My mistake.  Try overwriting the complete contents with this:
```

import ghidra.app.script.GhidraScript;
import ghidra.program.model.data.DataType;
import ghidra.program.model.data.DataTypeManager;
import ghidra.util.task.TaskMonitor;

public class FindBadTypesScript extends GhidraScript {

	@Override
	protected void run() throws Exception {

		DataTypeManager dtm = currentProgram.getDataTypeManager();
		DataType dt = dtm.getDataType("/TypeInfo");
		boolean success = dtm.remove(dt, TaskMonitor.DUMMY);
		println("removed dt?: " + success);

	}
}

```

**Comment by dragonmacher** [comment]
Try this:
```
import ghidra.app.script.GhidraScript;
import ghidra.program.model.data.DataType;
import ghidra.program.model.data.DataTypeManager;

public class FindBadTypesScript extends GhidraScript {

	@Override
	protected void run() throws Exception {

		DataTypeManager dtm = currentProgram.getDataTypeManager();
		DataType dt = dtm.getDataType("/TypeInfo");
		if (dt == null) {
			println("could not retrieve dt");
			return;
		}

		println("dt: " + dt);
		println("id: " + dt.getUniversalID());
		println("manager: " + dt.getDataTypeManager());

	}
}
```

**Comment by FlashHit** [comment]
Output:
```
FindBadTypesScript.java> Running...
FindBadTypesScript.java> dt: TypeInfo
FindBadTypesScript.java> id: null
FindBadTypesScript.java> manager: null
FindBadTypesScript.java> Finished!
```

**Comment by dragonmacher** [comment]
Try this:
```
import ghidra.app.script.GhidraScript;
import ghidra.program.model.data.DataType;
import ghidra.program.model.data.DataTypeManager;

public class FindBadTypesScript extends GhidraScript {

	@Override
	protected void run() throws Exception {

		DataTypeManager dtm = currentProgram.getDataTypeManager();
		DataType dt = dtm.getDataType("/TypeInfo");
		if (dt == null) {
			println("could not retrieve dt");
			return;
		}

		println("dt class: " + dt.getClass());

	}
}
```

**Comment by FlashHit** [comment]
Output:
```
FindBadTypesScript.java> Running...
FindBadTypesScript.java> dt class: class ghidra.app.cmd.data.rtti.gcc.factory.TypeInfoFactoryDataType
FindBadTypesScript.java> Finished!
```

**Comment by FlashHit** [comment]
Okay I know how to repro this issue:
I made a struct called `TypeInfo` and in there I wanted a pointer to itself, but instead I added a pointer to TypeInfoFactoryDataType which results in this error.

**Comment by dragonmacher** [comment]
So, that is the problem.   Is `TypeInfoFactoryDataType` a type that you created yourself?  If not, where did you find this type?

**Comment by FlashHit** [comment]
No I just typed `TypeInfo *` and pressed enter and then it chose that. I guess this is sth that comes along with Ghidra itself?

**Comment by dragonmacher** [comment]
This is not a type that we provide.  It appears as though it is from this repo:  
https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/tree/master/src/main/java/ghidra/app/cmd/data/rtti/gcc/factory

Do you have this extension?  Or any other extension to Ghidra that may be using this?

**Comment by FlashHit** [comment]
Yes I have this extension. It is literally the only thing that I have and I didn't even use this ever.

**Comment by FlashHit** [comment]
Okay everything works fine if I disable this extension.

**Comment by dragonmacher** [comment]
*Buckle your seat belt...*

1. Close the Code Browser tool and your program
2. From the Front End tool, remove this extension
3. Open the Code Browser tool by clicking the green dragon icon, but do NOT open your program
4. Replace the script contents with what is below this list
5. Run the script
6. Reopen your program and see if it works.

```
import ghidra.app.script.GhidraScript;
import ghidra.util.classfinder.ClassTranslator;

public class FindBadTypesScript extends GhidraScript {

	@Override
	protected void run() throws Exception {

		ClassTranslator.put("ghidra.app.cmd.data.rtti.gcc.factory.TypeInfoFactoryDataType",
			"ghidra.program.model.data.DWordDataType");

	}
}
```

**Comment by FlashHit** [comment]
Thanks for your help!

**Comment by astrelsky** [comment]
It's all my fault, what else is new :sweat_smile:. Sorry about that.

**Comment by astrelsky** [comment]
> > It's all my fault, what else is new sweat_smile. Sorry about that.
> > 
> 
> Perhaps you can think of this as helping to bring the community together?

:thinking: Well when you put it that way, I wonder what else I can break.
