### ISSUE TITLE
NPE on MIPS 32 ELF

### ISSUE THREAD

**Issue by brainstorm** [NationalSecurityAgency/ghidra#4602]
**Describe the bug**

![Screen Shot 2022-09-17 at 12 27 18 pm](https://user-images.githubusercontent.com/175587/190836947-99d8fb40-9e85-4297-a9f1-94c1fcbbfd59.png)

The following binary extracted from an IoT camera runs on an Ingenic T10 processor (MIPS32). The binary takes care of video streaming, p2p, SSL and other TUYA SDK duties.

Text from the backtrace from the screenshot above:

```
Cannot invoke "ghidra.program.model.listing.Data.getProgram()" because "data" is null
java.lang.NullPointerException: Cannot invoke "ghidra.program.model.listing.Data.getProgram()" because "data" is null
	at ghidra.app.util.bin.format.elf.ElfDefaultGotPltMarkup.setConstant(ElfDefaultGotPltMarkup.java:592)
	at ghidra.app.util.bin.format.elf.extend.MIPS_ElfExtension.fixupMipsGot(MIPS_ElfExtension.java:843)
	at ghidra.app.util.bin.format.elf.extend.MIPS_ElfExtension.processGotPlt(MIPS_ElfExtension.java:709)
	at ghidra.app.util.opinion.ElfProgramBuilder.load(ElfProgramBuilder.java:180)
	at ghidra.app.util.opinion.ElfProgramBuilder.loadElf(ElfProgramBuilder.java:109)
	at ghidra.app.util.opinion.ElfLoader.load(ElfLoader.java:149)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:369)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:119)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:368)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

---------------------------------------------------
Build Date: 2022-Sept-17 1214 AEST
Ghidra Version: 10.2
Java Home: /opt/homebrew/Cellar/openjdk/18.0.1/libexec/openjdk.jdk/Contents/Home
JVM Version: Homebrew 18.0.1
OS: Mac OS X 12.6 aarch64
```

**To Reproduce**

1. Create a new project.
2. Import this binary.
3. Kaboom.

**Expected behavior**

Correct import/load and analysis.

**Attachments**

[encoder.zip](https://github.com/NationalSecurityAgency/ghidra/files/9590772/encoder.zip)

**Environment (please complete the following information):**
 - OS: Apple M1 with macOS 12.6
 - Java Version:
 ```% java --version
openjdk 18.0.1 2022-04-19
OpenJDK Runtime Environment Homebrew (build 18.0.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 18.0.1+0, mixed mode, sharing)```
 - Ghidra Version: 10.2, dev build for 2022-Sept-17 1214 AEST
 - Ghidra Origin: locally built, git pull

**Comment by ghidra1** [comment]
Definite bug in extension.  If you are running from a Ghidra git clone development environment you can apply a temporary work-around to allow import to complete.   This can be done by adding a null data check to the `ElfDefaultGotPltMarkup.setConstant(Data data)` method.  While this can get you past the exception it is not the correct fix.
`
public static void setConstant(Data data) {
		if (data == null) {
			return;
		}
		Memory memory = data.getProgram().getMemory();
...
`

**Comment by brainstorm** [comment]
Sure, thanks! I will git pull if you are making those changes already on
HEAD.
