### ISSUE TITLE
Cannot restore archived project on Apple M1 machine

### ISSUE THREAD

**Issue by yuv422** [NationalSecurityAgency/ghidra#4643]
**Describe the bug**
An error occurs while trying to restore an archived project from a `.gar` file. I think this is due to the underlying `sevenzipjbinding` lib not providing a binding for the arm64 platform.

The error reported is.

```
net.sf.sevenzipjbinding.SevenZipNativeInitializationException: Error loading SevenZipJBinding native library into JVM: Can't find suited platform for os.arch=aarch64, os.name=Mac... Available list of platforms: Linux-amd64, Linux-i386, Mac-x86_64, Windows-amd64, Windows-x86 [You may also try different SevenZipJBinding initialization methods 'net.sf.sevenzipjbinding.SevenZip.init*()' in order to solve this problem]
```
 

**To Reproduce**
Restore any gar file project on an apple M1 running a native java version.

**Comment by dev747368** [comment]
Could you copy/paste exact lines from the log?  

Getting an warning message about failing to load the sevenzip libraries is expected (on M1), but it should switch over to java's built-in zip file support.

Alternatively, you could add "VMARGS=-Dghidra.file.formats.zip.ZipFileSystemFactory.USE_BUILTIN_ZIP_SUPPORT=true" to support/launch.properties to skip the attempt to load sevenzip.  It would be surprising if that fixed your issue, and would warrant further troubleshooting.

**Comment by yuv422** [comment]
Here's the application log.
```
2022-10-06 10:44:34 WARN  (FileSystemFactoryMgr) Error during fs factory create: zip, class ghidra.file.formats.zip.ZipFileSystem java.io.IOException: Failed to open archive: file:///Users/REDACTED/Downloads/ski32_2022_10_06.gar?MD5=b6642580aa08b4723970242bc5e76dac|zip://
	at ghidra.file.formats.sevenzip.SevenZipFileSystem.mount(SevenZipFileSystem.java:87)
	at ghidra.file.formats.zip.ZipFileSystemFactory.create(ZipFileSystemFactory.java:47)
	at ghidra.file.formats.zip.ZipFileSystemFactory.create(ZipFileSystemFactory.java:27)
	at ghidra.formats.gfilesystem.factory.FileSystemFactoryMgr.mountUsingFactory(FileSystemFactoryMgr.java:176)
	at ghidra.formats.gfilesystem.factory.FileSystemFactoryMgr.probe(FileSystemFactoryMgr.java:338)
	at ghidra.formats.gfilesystem.FileSystemService.openFileSystemContainer(FileSystemService.java:776)
	at ghidra.app.plugin.core.archive.RestoreTask.run(RestoreTask.java:88)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: net.sf.sevenzipjbinding.SevenZipNativeInitializationException: Error loading SevenZipJBinding native library into JVM: Can't find suited platform for os.arch=aarch64, os.name=Mac... Available list of platforms: Linux-amd64, Linux-i386, Mac-x86_64, Windows-amd64, Windows-x86 [You may also try different SevenZipJBinding initialization methods 'net.sf.sevenzipjbinding.SevenZip.init*()' in order to solve this problem] 
	at net.sf.sevenzipjbinding.SevenZip.throwInitException(SevenZip.java:825)
	at net.sf.sevenzipjbinding.SevenZip.throwInitException(SevenZip.java:820)
	at net.sf.sevenzipjbinding.SevenZip.getPlatformBestMatch(SevenZip.java:895)
	at net.sf.sevenzipjbinding.SevenZip.determineAndSetUsedPlatform(SevenZip.java:466)
	at net.sf.sevenzipjbinding.SevenZip.initSevenZipFromPlatformJARIntern(SevenZip.java:451)
	at net.sf.sevenzipjbinding.SevenZip.initSevenZipFromPlatformJAR(SevenZip.java:340)
	at ghidra.file.formats.sevenzip.SevenZipFileSystem.mount(SevenZipFileSystem.java:77)
	... 11 more
 
2022-10-06 10:44:34 ERROR (RestoreTask) Task Error: Restoring Project: ski32 - Uncaught Exception: java.lang.RuntimeException: /Users/REDACTED/Projects/other/skifree/ski32.gpr
 does not exist java.lang.RuntimeException: /Users/REDACTED/Projects/other/skifree/ski32.gpr does not exist
	at ghidra.framework.project.DefaultProjectManager.deleteProject(DefaultProjectManager.java:224)
	at ghidra.app.plugin.core.archive.ArchivePlugin.cleanupRestoredProject(ArchivePlugin.java:383)
	at ghidra.app.plugin.core.archive.RestoreTask.run(RestoreTask.java:100)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
I was restoring an archive that I created on a Windows 10 machine on a older ghidra. I think 1 patch version behind. Not sure if that matters here.
