### ISSUE TITLE
java.lang.NullPointerException error when importing a DLL file into a Ghidra project

### ISSUE THREAD

**Issue by RedOctober45** [NationalSecurityAgency/ghidra#4696]
**Describe the bug**
When I am importing a DLL, I get the following error:

java.lang.NullPointerException: Cannot invoke "ghidra.program.model.address.Address.getOffset()" because "nextCallbackAddr" is null
	at ghidra.app.util.bin.format.pe.TLSDataDirectory.markup(TLSDataDirectory.java:94)
	at ghidra.app.util.opinion.PeLoader.load(PeLoader.java:138)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:404)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:350)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

This error appeared after some change to the application (DLL) file occurred.  This worked in the past using the same Ghidra/Java version but with an older build.  When I say "import" I mean creating a Ghidra project and simply dragging the DLL file into that project window.  Then hitting "ok" after Ghidra automatically detects the file type (PE) and environment.  So fails during the import into the project.

**To Reproduce**
I can't share the DLL file because it is proprietary.  This is also a very large file so it is extremely difficult to try and create a scaled down version unless I can understand more what might have caused the error.

What I am asking for is any general guidance on what could cause this error and/or what kind of change in the application could cause this since this worked on the same previous product builds.  Or if this could be a Ghidra error so any more troubleshooting advice I can do to try and narrow down the problem.  The product this DLL comes from works fine and no known issues that could signal what this error could be.

**Expected behavior**
The DLL would import with no issues and then I could proceed to open it in Ghidra and further analyze it as before.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: JDK 18.0.2, JRE 1.8.0_351
 - Ghidra Version: 10.1.5
 - Ghidra Origin: Official release

Thanks for any help/guidance

**Comment by ryanmkurtz** [comment]
This has already been fixed by #4161 and will be available in the upcoming 10.2 release.
