### ISSUE TITLE
Use DataTypeArchive in Headless Mode

### ISSUE THREAD

**Issue by anon767** [NationalSecurityAgency/ghidra#4700]
Hi there,

I have a question regarding .gdt files in headless mode. I try to load a datatype archive using following snippet:
```
from ghidra.app.script import GhidraScript
from ghidra.app.cmd.function import ApplyFunctionDataTypesCmd
from ghidra.app.plugin.core.analysis import AutoAnalysisManager
from ghidra.program.model.symbol import SourceType
from java.io import File
aam = AutoAnalysisManager.getAnalysisManager(currentProgram)
dtm = aam.getDataTypeManagerService()
datatypes = [dtm.openArchive(File("ghidra-data/typeinfo/winapi_64.gdt", "winapi"), False)]
cmd = ApplyFunctionDataTypesCmd(managers, None, SourceType.USER_DEFINED, True, True)
cmd.applyTo(currentProgram, monitor)
```

However I get following error:
```
  File "ghidra_prescript.py", line 8, in <module>
    dtm.openArchive(File("ghidra-data/typeinfo/winapi_64.gdt", "winapi"), False)
	at ghidra.app.plugin.core.analysis.DefaultDataTypeManagerService.openArchive(DefaultDataTypeManagerService.java:207)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
java.lang.UnsupportedOperationException: java.lang.UnsupportedOperationException
```

I call it with following command:

```
analyzeHeadless . project -readOnly -import sample.exe -prescript ../ghidra_prescript.py
```

Is there something Im missing or misunderstanding?

Thanks in advance and regards

**Comment by dev747368** [comment]
If you look at the source code for DefaultDataTypeManagerService, several of its methods are un-implemented stubs that throw the UnsupportedOperationException.  I think that the DataTypeManagerService may be oriented towards managing the GUI data type manager, which won't work in a headless env.

Have you tried using FileDataTypeManager directly?

```
File archiveGDT = new File(path-to-your-gdt);
DataTypeManager archiveDTM = FileDataTypeManager.openFileArchive(archiveGDT, false);
```

**Comment by anon767** [comment]
cool that worked!
