### ISSUE TITLE
core dump NPE

### ISSUE THREAD

**Issue by Sarkie** [NationalSecurityAgency/ghidra#4709]
**Describe the bug**
I have a coredump from Oracle's oidldapd process.

**To Reproduce**
1.) File open core dump

**Expected behavior**
It loads

**Screenshots**
![image](https://user-images.githubusercontent.com/283203/199494579-37875ff6-c687-4537-8503-4ebe4956bc1c.png)

**Attachments**
java.lang.NullPointerException
	at ghidra.app.util.opinion.ElfProgramBuilder.expandProgramHeaderBlocks(ElfProgramBuilder.java:2700)
	at ghidra.app.util.opinion.ElfProgramBuilder.load(ElfProgramBuilder.java:140)
	at ghidra.app.util.opinion.ElfProgramBuilder.loadElf(ElfProgramBuilder.java:103)
	at ghidra.app.util.opinion.ElfLoader.load(ElfLoader.java:153)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:113)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:404)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:350)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)

---------------------------------------------------
Build Date: 2022-Jul-26 1543 EDT
Ghidra Version: 10.1.5
Java Home: D:\tools\jdk-12.0.1
JVM Version: Oracle Corporation 12.0.1
OS: Windows 10 10.0 amd64

**Comment by ghidra1** [comment]
This issue has been resolved for 10.2 which will be released shortly.  The master branch has this fix which was made with commit ab200399a240804373a7870552ee402988201e83
