### ISSUE TITLE
Machine Learning Extension: Exception when trying to apply model twice to the same file

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#4720]
**Describe the bug**

The following exception is thrown:

```
Attempted to acquire the domain object more than once by the same consumer: ghidra.machinelearning.functionfinding.RandomForestFunctionFinderPlugin@e0fa89f1
java.lang.IllegalArgumentException: Attempted to acquire the domain object more than once by the same consumer: ghidra.machinelearning.functionfinding.RandomForestFunctionFinderPlugin@e0fa89f1
	at ghidra.framework.data.DomainObjectAdapter.addConsumer(DomainObjectAdapter.java:347)
	at ghidra.framework.data.GhidraFileData.getDomainObject(GhidraFileData.java:318)
	at ghidra.framework.data.GhidraFile.getDomainObject(GhidraFile.java:178)
	at ghidra.machinelearning.functionfinding.FunctionStartRFParamsDialog.selectProgram(FunctionStartRFParamsDialog.java:565)
	at ghidra.machinelearning.functionfinding.FunctionStartRFParamsDialog.searchOtherProgram(FunctionStartRFParamsDialog.java:490)
	at ghidra.machinelearning.functionfinding.FunctionStartRFParamsDialog.lambda$createPanel$7(FunctionStartRFParamsDialog.java:306)
	at docking.action.builder.ActionBuilder$1.actionPerformed(ActionBuilder.java:48)
	at docking.DialogComponentProviderPopupActionManager$PopupMenuHandler.lambda$processMenuAction$0(DialogComponentProviderPopupActionManager.java:140)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**To Reproduce**
1. Train a model on file A
2. Apply model on File B
3. Close File B's window, the potential functions dialog, and the Random Forest Function Dialog
4. Repeat Steps 1-2. 

**Environment (please complete the following information):**
69b0716

**Comment by ghidracadabra** [comment]
I can reproduce this; thanks for reporting it.
