### ISSUE TITLE
Ghidra Debugger stopped working in 10.2

### ISSUE THREAD

**Issue by lolwheel** [NationalSecurityAgency/ghidra#4731]
Hi, I have same exact debugging setup as I've reported in https://github.com/NationalSecurityAgency/ghidra/issues/4345

I updated to 10.2 and the Debugger tool started throwing exceptions and stopped working properly.

Here's the flow to reproduce:
1. Open the old project in the Ghidra Debugger Tool. Hit "Upgrade" when Ghidra asks if it should upgrade the old project format.
2. Witness the first exeption, unsure if this is related to the core issue I'm dealing with:
```
java.lang.ExceptionInInitializerError
	at org.apache.felix.framework.URLHandlers.createURLStreamHandler(URLHandlers.java:513)
	at java.base/java.net.URL.getURLStreamHandler(URL.java:1436)
	at java.base/java.net.URL.<init>(URL.java:680)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at ghidra.app.plugin.core.debug.utils.ProgramURLUtils.hackAddLocalDomainFilePath(ProgramURLUtils.java:52)
	at ghidra.app.plugin.core.debug.utils.ProgramURLUtils.getUrlFromProgram(ProgramURLUtils.java:47)
	at ghidra.app.plugin.core.debug.service.modules.DebuggerStaticMappingServicePlugin.programOpened(DebuggerStaticMappingServicePlugin.java:630)
	at ghidra.app.plugin.core.debug.service.modules.DebuggerStaticMappingServicePlugin.processEvent(DebuggerStaticMappingServicePlugin.java:609)
	at ghidra.framework.plugintool.Plugin.eventSent(Plugin.java:292)
	at ghidra.framework.plugintool.mgr.EventManager.sendEvents(EventManager.java:286)
	at ghidra.framework.plugintool.mgr.EventManager.lambda$new$3(EventManager.java:49)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.framework.plugintool.mgr.EventManager.fireEvent(EventManager.java:216)
	at ghidra.framework.plugintool.PluginTool.firePluginEvent(PluginTool.java:502)
	at ghidra.framework.plugintool.Plugin.firePluginEvent(Plugin.java:444)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.fireOpenEvents(MultiProgramManager.java:267)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.addProgram(MultiProgramManager.java:95)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.lambda$openProgram$6(ProgramManagerPlugin.java:469)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.openProgram(ProgramManagerPlugin.java:475)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.openPrograms(ProgramManagerPlugin.java:658)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.acceptData(ProgramManagerPlugin.java:129)
	at ghidra.framework.plugintool.PluginManager.acceptData(PluginManager.java:48)
	at ghidra.framework.plugintool.PluginTool.acceptDomainFiles(PluginTool.java:441)
	at ghidra.framework.main.projectdata.actions.ProjectDataOpenToolAction.openInTool(ProjectDataOpenToolAction.java:65)
	at ghidra.framework.main.projectdata.actions.ProjectDataOpenToolAction.actionPerformed(ProjectDataOpenToolAction.java:46)
	at ghidra.framework.main.projectdata.actions.ProjectDataOpenToolAction.actionPerformed(ProjectDataOpenToolAction.java:31)
	at docking.action.ContextSpecificAction.actionPerformed(ContextSpecificAction.java:71)
	at docking.PopupMenuHandler$1.run(PopupMenuHandler.java:63)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.RuntimeException: Unable to make protected boolean java.net.URLStreamHandler.equals(java.net.URL,java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @430617d0
	at org.apache.felix.framework.URLHandlersStreamHandlerProxy.<clinit>(URLHandlersStreamHandlerProxy.java:104)
	... 47 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected boolean java.net.URLStreamHandler.equals(java.net.URL,java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @430617d0
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.apache.felix.framework.util.SecureAction.setAccesssible(SecureAction.java:871)
	at org.apache.felix.framework.URLHandlersStreamHandlerProxy.<clinit>(URLHandlersStreamHandlerProxy.java:79)
	... 47 more

---------------------------------------------------
Build Date: 2022-Nov-01 1334 EDT
Ghidra Version: 10.2
Java Home: /usr/lib/jvm/java-17-openjdk-amd64
JVM Version: Private Build 17.0.5
OS: Linux 5.15.0-47-generic amd64
```
3. Close the exception window, connect to in-vm gdb local debugger
4. Once the gdb sesssion is established, issue commands in the gdb interpreter window and connect it to `openocd`
5. Connection is initialized fine, registers are show correctly, however the program isn't synced with the live trace yet.
6. Hit the red "<=>" button in the Modules view that maps the current program with the trace. Witness the exception:
```
Could not initialize class org.apache.felix.framework.URLHandlersStreamHandlerProxy
java.lang.NoClassDefFoundError: Could not initialize class org.apache.felix.framework.URLHandlersStreamHandlerProxy
	at org.apache.felix.framework.URLHandlers.createURLStreamHandler(URLHandlers.java:513)
	at java.base/java.net.URL.getURLStreamHandler(URL.java:1436)
	at java.base/java.net.URL.<init>(URL.java:680)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at ghidra.app.plugin.core.debug.utils.ProgramURLUtils.hackAddLocalDomainFilePath(ProgramURLUtils.java:52)
	at ghidra.app.plugin.core.debug.utils.ProgramURLUtils.getUrlFromProgram(ProgramURLUtils.java:47)
	at ghidra.app.plugin.core.debug.service.modules.DebuggerStaticMappingUtils.addMapping(DebuggerStaticMappingUtils.java:191)
	at ghidra.app.plugin.core.debug.service.modules.DebuggerStaticMappingUtils.addIdentityMapping(DebuggerStaticMappingUtils.java:262)
	at ghidra.app.plugin.core.debug.service.modules.DebuggerStaticMappingServicePlugin.addIdentityMapping(DebuggerStaticMappingServicePlugin.java:779)
	at ghidra.app.plugin.core.debug.gui.modules.DebuggerModulesProvider.activatedMapIdentically(DebuggerModulesProvider.java:991)
	at docking.action.builder.ActionBuilder$1.actionPerformed(ActionBuilder.java:48)
	at docking.menu.ToolBarItemManager.lambda$actionPerformed$0(ToolBarItemManager.java:129)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2022-Nov-01 1334 EDT
Ghidra Version: 10.2
Java Home: /usr/lib/jvm/java-17-openjdk-amd64
JVM Version: Private Build 17.0.5
OS: Linux 5.15.0-47-generic amd64
```

This is it.

My setup is a vanilla Ubuntu 22.04 x64 in Virtualbox, Ghidra 10.2 official release downloaded from Github, OpenJDK 17 (tried 18, same error)

Let me know if I can provide any further clarifications here. Thank you.

**Comment by lolwheel** [comment]
Please disregard, I extracted 10.2 installation over the old one. After retrying a clean installation the error went away.
