### ISSUE TITLE
Error importing file ("Cannot read past EOF")

### ISSUE THREAD

**Issue by SID37** [NationalSecurityAgency/ghidra#4733]
**Describe the bug**
Trying to load a file gives the following error message: "Unable to read past EOF"

```
Unable to read past EOF: 65534, 4
java.io.IOException: Unable to read past EOF: 65534, 4
	at ghidra.app.util.bin.FileByteProvider.ensureBounds(FileByteProvider.java:267)
	at ghidra.app.util.bin.FileByteProvider.readBytes(FileByteProvider.java:121)
	at ghidra.formats.gfilesystem.RefdByteProvider.readBytes(RefdByteProvider.java:95)
	at ghidra.app.util.bin.BinaryReader.readInt(BinaryReader.java:821)
	at ghidra.app.util.bin.format.pe.ImportDescriptor.<init>(ImportDescriptor.java:66)
	at ghidra.app.util.bin.format.pe.ImportDataDirectory.parse(ImportDataDirectory.java:341)
	at ghidra.app.util.bin.format.pe.DataDirectory.processDataDirectory(DataDirectory.java:80)
	at ghidra.app.util.bin.format.pe.ImportDataDirectory.<init>(ImportDataDirectory.java:46)
	at ghidra.app.util.bin.format.pe.OptionalHeaderImpl.processDataDirectories(OptionalHeaderImpl.java:295)
	at ghidra.app.util.opinion.PeLoader.load(PeLoader.java:121)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:724)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:98)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:126)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:368)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```
**To Reproduce**
1. Go to `File -> Import File.. -> <Select CleanSlate_AMDfix.exe to import>`
2. Click OK
3. An error message appears

**Expected behavior**
The file will be uploaded to the project as normal

**Attachments**
File CleanSlate_AMDfix.exe: https://conspiracy.hu/get/67/cns!cns-AMDfix.zip

**Environment:**
 - OS: Windows 11 10.0 amd64
 - Java Version: 19.0.1
 - Ghidra Version: 10.2
 - Ghidra Origin: official GitHub distro

**Comment by ryanmkurtz** [comment]
Looks like we do a decent job with it if we don't process the imports.  We need to make that part of the parsing a bit more robust to handle this file.  I'll continue to look into it.

**Comment by ryanmkurtz** [comment]
This should load now

**Comment by 0xh3xa** [comment]
@ryanmkurtz I have tried to use Ghidra `11.1.1` and I have the same issue, do you recommend trying another Ghidra version?

```
ERROR REPORT: Unable to read past EOF: 548352, 2 (HeadlessAnalyzer) java.io.IOException: Unable to read past EOF: 548352, 2
	at ghidra.app.util.bin.FileByteProvider.ensureBounds(FileByteProvider.java:267)
	at ghidra.app.util.bin.FileByteProvider.readBytes(FileByteProvider.java:121)
	at ghidra.formats.gfilesystem.RefdByteProvider.readBytes(RefdByteProvider.java:95)
	at ghidra.app.util.bin.BinaryReader.readShort(BinaryReader.java:911)
	at ghidra.app.util.bin.format.pe.resource.ResourceDirectory.<init>(ResourceDirectory.java:72)
	at ghidra.app.util.bin.format.pe.resource.ResourceDirectoryEntry.<init>(ResourceDirectoryEntry.java:114)
	at ghidra.app.util.bin.format.pe.resource.ResourceDirectory.<init>(ResourceDirectory.java:99)
	at ghidra.app.util.bin.format.pe.resource.ResourceDirectoryEntry.<init>(ResourceDirectoryEntry.java:114)
	at ghidra.app.util.bin.format.pe.resource.ResourceDirectory.<init>(ResourceDirectory.java:99)
	at ghidra.app.util.bin.format.pe.ResourceDataDirectory.parse(ResourceDataDirectory.java:519)
	at ghidra.app.util.bin.format.pe.DataDirectory.processDataDirectory(DataDirectory.java:80)
	at ghidra.app.util.bin.format.pe.ResourceDataDirectory.<init>(ResourceDataDirectory.java:176)
	at ghidra.app.util.bin.format.pe.OptionalHeaderImpl.processDataDirectories(OptionalHeaderImpl.java:285)
	at ghidra.app.util.opinion.PeLoader.load(PeLoader.java:128)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:887)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:98)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.app.util.importer.AutoImporter.importFresh(AutoImporter.java:722)
	at ghidra.app.util.importer.AutoImporter.importFresh(AutoImporter.java:634)
	at ghidra.app.util.importer.AutoImporter.importByUsingBestGuess(AutoImporter.java:126)
	at ghidra.app.util.headless.HeadlessAnalyzer.loadPrograms(HeadlessAnalyzer.java:1644)
	at ghidra.app.util.headless.HeadlessAnalyzer.processFileWithImport(HeadlessAnalyzer.java:1527)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithLoader(HeadlessAnalyzer.java:1734)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1675)
	at ghidra.app.util.headless.HeadlessAnalyzer.processFS(HeadlessAnalyzer.java:1707)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1669)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1759)
	at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:460)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:127)
	at ghidra.GhidraLauncher.launch(GhidraLauncher.java:78)
	at ghidra.Ghidra.main(Ghidra.java:54)
```

**Comment by ryanmkurtz** [comment]
@0xh3xa can you attach your binary?
