### ISSUE TITLE
Debugging fails to update Dynamic view and Registers are missing (10.2.2)

### ISSUE THREAD

**Issue by boondoggler** [NationalSecurityAgency/ghidra#4756]
**Describe the bug**

Debugging Arm with gdb-multiarch no longer works in 10.2.2 (worked fine in 10.2.1).

**To Reproduce**

0. Use QEMU to emulate arm binary (we use QEMU 7)
2. Open an Arm binary in Ghidra debugger
3. Select Debugger Targets and then 'IN VM GNU gdb local debugger' and point it at /usr/bin/gdb-multiarch
4. In interpreter window type 'target remote localhost:1234', it should connect to QEMU stub
5. Got to Objects window and right-click on Inferiors -> 1 and hit R to bring up Record dialog
6. Untick the tick and select arm v6 or v7 (another bug means v5 may not work anyhow)
7. Close dialog and click Step or Next. Registers and Dynamic view don't update.

**Expected behavior**
The Dynamic view should update and Registers tab should show registers. Worked fine in 10.2.1.

**Environment (please complete the following information):**
 - OS: [Linux Ubuntu 20]
 - Java Version: [17]
 - Ghidra Version: [e.g. 10.2.2]
 - Ghidra Origin: [official GitHub distrot]

**Comment by boondoggler** [comment]
Minor layout edit

**Comment by nsadeveloper789** [comment]
I'm not quite able to reproduce this issue. Things go as you describe until I get to step 6. Once I OK the Record dialog, I get a Dynamic listing at address 00000000, which is admittedly not great. However, once I step, things get back on track. Alternatively, instead of Step, I can click the one row in the Threads window and that'll get things on track at the first instruction.

I'm working with GDB 9.2 and QEMU 4.2.1, which are both a bit old.... I'm also using the SSH variant of the GDB connector, but that shouldn't matter. Can you check the Ghidra User Log? (Click the little computer icon in the bottom-right of the main Ghidra project window.) The only gdb-related change between 10.2.1 and 10.2.2 I see is in `GdbReadRegistersCommand`, so look for traces involving it, and if you don't mind, please post what you find here.

If none of this is helpful, I can try replicating your environment a little more closely, but I'll need to know your version of GDB. If there's a Linux distro where those GDB and QEMU versions come stock, it might help me get there faster.

**Comment by boondoggler** [comment]
Apologies for not adding all the versions:

gdb-multiarch --v: _GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2_


QEMU script with versions (for vanilla Arm v7): 

_/qemu-7.1.0/build/arm-softmmu/qemu-system-arm \
-cpu arm1176 \
-m 256 \
-M versatilepb \
-device loader,file=boot.bin,addr=0x00000,force-raw=true \
-s -S_

QEMU script with versions (for STM32): 

_/xpack-qemu-arm-7.1.0-1/bin/qemu-system-gnuarmeclipse \
-cpu cortex-m4 \
-M STM32F4-Discovery \
-kernel stm32F4.bin \
-s -S_ 

(There are backslashes on the end of those lines, but the webpage is removing them)

Ive been checking gdb works directly by adding _& gdb-multiarch_ on the end of the script.

Log output at remote connect time and stepping:

`2022-11-17 20:37:12 DEBUG (GdbModelTargetThread) Updating stack for <GdbModelTargetThread: path=Inferiors[1].Threads[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Thread>  
2022-11-17 20:37:12 ERROR (GdbModelTargetThread) Could not initialize thread info  
2022-11-17 20:37:12 ERROR (DebuggerCallbackReorderer) Listener ghidra.app.plugin.core.debug.gui.objects.DebuggerObjectsProvider$MyObjectListener@208553ec caused exception processing attributesChanged java.util.NoSuchElementException: No mapper for target: <GdbModelTargetInferior: path=Inferiors[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Inferior>
	at ghidra.app.plugin.core.debug.service.model.DebuggerModelServicePlugin.recordTargetBestOffer(DebuggerModelServicePlugin.java:367)
	at ghidra.app.plugin.core.debug.service.model.DebuggerModelServiceProxyPlugin.recordTargetBestOffer(DebuggerModelServiceProxyPlugin.java:521)
	at ghidra.app.plugin.core.debug.gui.objects.DebuggerObjectsProvider.startRecording(DebuggerObjectsProvider.java:1640)
	at ghidra.app.plugin.core.debug.gui.objects.DebuggerObjectsProvider$MyObjectListener.attributesChanged(DebuggerObjectsProvider.java:1972)
	at ghidra.dbg.util.DebuggerCallbackReorderer.lambda$attributesChanged$3(DebuggerCallbackReorderer.java:203)
	at ghidra.dbg.util.DebuggerCallbackReorderer.defensive(DebuggerCallbackReorderer.java:113)
	at ghidra.dbg.util.DebuggerCallbackReorderer.attributesChanged(DebuggerCallbackReorderer.java:203)
	at jdk.internal.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at ghidra.util.datastruct.PrivatelyQueuedListener$ListenerHandler.lambda$invoke$0(PrivatelyQueuedListener.java:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
 
2022-11-17 20:37:12 ERROR (GdbModelTargetThreadContainer) Could not update threads <GdbModelTargetThreadContainer: path=Inferiors[1].Threads model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=ThreadContainer> on STOPPED  
2022-11-17 20:37:50 DEBUG (ListenerOnRecorders) (started) Got snapAdvanced callback  
2022-11-17 20:37:50 DEBUG (ListenerOnRecorders) (3 ms) Firing SnapEvent on ghidra.app.plugin.core.debug.service.model.DebuggerModelServiceProxyPlugin@c8488ed4  
2022-11-17 20:37:50 DEBUG (ListenerOnRecorders) (24 ms) Got snapAdvanced callback  
2022-11-17 20:37:50 DEBUG (ListenerOnRecorders) (0 ms) Firing SnapEvent on ghidra.app.plugin.core.debug.service.model.DebuggerModelServiceProxyPlugin@c8488ed4  
2022-11-17 20:37:50 DEBUG (TraceEventListener) (55 ms) State STOPPED for <GdbModelTargetInferior: path=Inferiors[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Inferior>  
2022-11-17 20:37:50 DEBUG (TraceEventListener) (0 ms) State STOPPED for <GdbModelTargetThread: path=Inferiors[1].Threads[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Thread>  
2022-11-17 20:37:50 DEBUG (TraceEventListener) (178 ms) Memory updated: 00000000 (4096)  
2022-11-17 20:37:50 DEBUG (ToolTaskManager) Background processing started...  
2022-11-17 20:37:50 DEBUG (ToolTaskManager) Exec Task Map modules to open programs  
2022-11-17 20:37:50 DEBUG (ToolTaskManager) Map modules to open programs task finish (0.004 secs)  
2022-11-17 20:37:51 DEBUG (ToolTaskManager) Map modules to open programs task complete (0.322 secs)  
2022-11-17 20:37:51 DEBUG (ToolTaskManager) Background processing complete (0.323 secs)  
2022-11-17 20:37:51 DEBUG (DBTrace) Creating fixed view at snap=1  
2022-11-17 20:37:51 DEBUG (ToolTaskManager) Background processing started...  
2022-11-17 20:37:51 DEBUG (ToolTaskManager) Exec Task Auto-disassemble  
2022-11-17 20:37:51 DEBUG (ToolTaskManager) Auto-disassemble task finish (0.182 secs)  
2022-11-17 20:37:51 DEBUG (ToolTaskManager) Auto-disassemble task complete (0.182 secs)  
2022-11-17 20:37:51 DEBUG (ToolTaskManager) Exec Task Auto-disassemble  
2022-11-17 20:37:51 DEBUG (ToolTaskManager) Auto-disassemble task finish (0.0 secs)  
2022-11-17 20:37:51 DEBUG (ToolTaskManager) Auto-disassemble task complete (0.002 secs)  
2022-11-17 20:37:51 DEBUG (ToolTaskManager) Exec Task Auto-disassemble  
2022-11-17 20:37:51 DEBUG (ToolTaskManager) Auto-disassemble task finish (0.0 secs)  
2022-11-17 20:37:51 DEBUG (ToolTaskManager) Auto-disassemble task complete (0.001 secs)  
2022-11-17 20:37:51 DEBUG (ToolTaskManager) Background processing complete (0.186 secs)  
2022-11-17 20:37:51 DEBUG (ToolTaskManager) Background processing started...  
2022-11-17 20:37:51 DEBUG (ToolTaskManager) Exec Task Map modules to open programs  
2022-11-17 20:37:51 DEBUG (ToolTaskManager) Map modules to open programs task finish (0.0 secs)  
2022-11-17 20:37:51 DEBUG (ToolTaskManager) Map modules to open programs task complete (0.001 secs)  
2022-11-17 20:37:51 DEBUG (ToolTaskManager) Background processing complete (0.002 secs)  
2022-11-17 20:37:54 DEBUG (GdbManagerImpl) Target is running  
2022-11-17 20:37:54 DEBUG (TraceEventListener) (4298 ms) State RUNNING for <GdbModelTargetInferior: path=Inferiors[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Inferior>  
2022-11-17 20:37:54 DEBUG (TraceEventListener) (1 ms) Event: RUNNING thread=<GdbModelTargetThread: path=Inferiors[1].Threads[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Thread> description=Running params=[<GdbModelTargetThread: path=Inferiors[1].Threads[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Thread>]  
2022-11-17 20:37:54 DEBUG (TraceEventListener) (2 ms) State RUNNING for <GdbModelTargetThread: path=Inferiors[1].Threads[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Thread>  
2022-11-17 20:37:54 DEBUG (TraceEventListener) (0 ms) Event: STEP_COMPLETED thread=<GdbModelTargetThread: path=Inferiors[1].Threads[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Thread> description=Stepping ended params=[<GdbModelTargetThread: path=Inferiors[1].Threads[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Thread>]  
2022-11-17 20:37:54 DEBUG (GdbModelTargetThread) Updating stack for <GdbModelTargetThread: path=Inferiors[1].Threads[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Thread>  
2022-11-17 20:37:54 DEBUG (ListenerOnRecorders) (4 ms) Got snapAdvanced callback  
2022-11-17 20:37:54 DEBUG (ListenerOnRecorders) (0 ms) Firing SnapEvent on ghidra.app.plugin.core.debug.service.model.DebuggerModelServiceProxyPlugin@c8488ed4  
2022-11-17 20:37:54 DEBUG (TraceEventListener) (1 ms) State STOPPED for <GdbModelTargetThread: path=Inferiors[1].Threads[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Thread>  
2022-11-17 20:37:54 DEBUG (TraceEventListener) (1 ms) State STOPPED for <GdbModelTargetInferior: path=Inferiors[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Inferior>  
2022-11-17 20:37:54 ERROR (GdbModelTargetThreadContainer) Could not update threads <GdbModelTargetThreadContainer: path=Inferiors[1].Threads model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=ThreadContainer> on STOPPED  
2022-11-17 20:37:54 DEBUG (DefaultThreadRecorder) (42 ms) Reg values changed: [r0, r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12, sp, lr, pc, cpsr, d0, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15, fpscr, fpsid, fpexc, DUMMY, PAR, DBGDIDR, MIDR, CTR, TCMTR, TLBTR, JIDR, ID_PFR0, ID_DFR0, ID_AFR0, ID_MMFR0, ID_MMFR1, ID_MMFR2, ID_MMFR3, DACR, ID_ISAR0, ID_ISAR1, ID_ISAR2, ID_ISAR3, ID_ISAR4, ID_ISAR5, ID_MMFR4, ID_ISAR6, TTBR0_EL1, DFAR, WFAR, TTBCR, IFAR, TTBR1_EL1, JMCR, SCTLR, DFSR, ACTLR_EL1, CPACR, DLOCKDOWN, IFSR, FCSEIDR, ILOCKDOWN, CONTEXTIDR_EL1, TPIDRURW, TPIDRURO, TPIDRPRW, ACTLR_EL2, JOSCR, s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21, s22, s23, s24, s25, s26, s27, s28, s29, s30, s31]  
2022-11-17 20:37:56 DEBUG (GdbManagerImpl) Target is running  
2022-11-17 20:37:56 DEBUG (TraceEventListener) (1646 ms) State RUNNING for <GdbModelTargetInferior: path=Inferiors[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Inferior>  
2022-11-17 20:37:56 DEBUG (TraceEventListener) (1 ms) Event: RUNNING thread=<GdbModelTargetThread: path=Inferiors[1].Threads[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Thread> description=Running params=[<GdbModelTargetThread: path=Inferiors[1].Threads[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Thread>]  
2022-11-17 20:37:56 DEBUG (GdbModelTargetThread) Updating stack for <GdbModelTargetThread: path=Inferiors[1].Threads[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Thread>  
2022-11-17 20:37:56 DEBUG (TraceEventListener) (0 ms) State RUNNING for <GdbModelTargetThread: path=Inferiors[1].Threads[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Thread>  
2022-11-17 20:37:56 DEBUG (TraceEventListener) (2 ms) Event: STEP_COMPLETED thread=<GdbModelTargetThread: path=Inferiors[1].Threads[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Thread> description=Stepping ended params=[<GdbModelTargetThread: path=Inferiors[1].Threads[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Thread>]  
2022-11-17 20:37:56 DEBUG (ListenerOnRecorders) (1 ms) Got snapAdvanced callback  
2022-11-17 20:37:56 DEBUG (ListenerOnRecorders) (1 ms) Firing SnapEvent on ghidra.app.plugin.core.debug.service.model.DebuggerModelServiceProxyPlugin@c8488ed4  
2022-11-17 20:37:56 DEBUG (TraceEventListener) (0 ms) State STOPPED for <GdbModelTargetThread: path=Inferiors[1].Threads[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Thread>  
2022-11-17 20:37:56 DEBUG (TraceEventListener) (1 ms) State STOPPED for <GdbModelTargetInferior: path=Inferiors[1] model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=Inferior>  
2022-11-17 20:37:56 ERROR (GdbModelTargetThreadContainer) Could not update threads <GdbModelTargetThreadContainer: path=Inferiors[1].Threads model=agent.gdb.model.impl.GdbModelImpl@2165575e schema=ThreadContainer> on STOPPED  
2022-11-17 20:37:56 DEBUG (DefaultThreadRecorder) (22 ms) Reg values changed: [r0, r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12, sp, lr, pc, cpsr, d0, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15, fpscr, fpsid, fpexc, DUMMY, PAR, DBGDIDR, MIDR, CTR, TCMTR, TLBTR, JIDR, ID_PFR0, ID_DFR0, ID_AFR0, ID_MMFR0, ID_MMFR1, ID_MMFR2, ID_MMFR3, DACR, ID_ISAR0, ID_ISAR1, ID_ISAR2, ID_ISAR3, ID_ISAR4, ID_ISAR5, ID_MMFR4, ID_ISAR6, TTBR0_EL1, DFAR, WFAR, TTBCR, IFAR, TTBR1_EL1, JMCR, SCTLR, DFSR, ACTLR_EL1, CPACR, DLOCKDOWN, IFSR, FCSEIDR, ILOCKDOWN, CONTEXTIDR_EL1, TPIDRURW, TPIDRURO, TPIDRPRW, ACTLR_EL2, JOSCR, s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21, s22, s23, s24, s25, s26, s27, s28, s29, s30, s31]  `

**Comment by nsadeveloper789** [comment]
Thanks for the information. The message that looks like trouble is `Could not update threads ... on STOPPED.` Unfortunately, that message doesn't include any diagnostics, so unless you're willing to whip up a development environment, the remaining investigation is up to us. Looks like we match versions except for qemu, which should be easy for me to get. Also, FWIW, I tested with qemu running a user-space hello world program. I didn't try a full system image. That might be relevant....

Also worth noting is that the log shows it detected register value changes, which is promising. My suspicion; however, is that there's no way in the UI to navigate to and display them. A few things you might check: 1) I had mentioned the Threads window (the dedicated window, not the Threads node in Objects window) It contained one entry when I tried replicating. Do you have any entries at all, or is that window empty? If it's populated, try clicking an entry. 2) Check the same for the Stack window. 3) In the Objects window, try navigating to frame #0 and expanding/refreshing its Registers node. Sometimes that kicks things along. You can also try Refreshing other collections in the ancestry: i.e., Stack node, Threads node....

**Comment by boondoggler** [comment]
So I have set up a qemu-user mode version like you, still on 7.1.0 (and briefly checked on the apt installed 6.0.93 version with same result). My script:

_/qemu-7.1.0/build/qemu-arm -L /usr/arm-linux-gnueabi/ -g 4444 ./hello -n_

So switching between 10.2.1 and 10.2.2 it almost mimics if I hadn't set up the Record function. i.e. if I use 10.2.1 and don't select record and try and step I get static Dynamic view and no registers (I have of course ensured I have followed the same process to debug across 10.2.1 and 10.2.2).

If I click on Threads window entry (there is one as expected), the registers magically appear (didn't have to do this on 10.2.1). These registers have values, but stepping does not update them and the Dynamic view still doesn't work or show any disassembly.

The entry says:

null stopped at 0x...         0             stopped

Strangely threads tab "plot arrow" goes backwards each step not forwards as in 10.2.1, and I noticed the Interpreter window shows steps ok.

If I do 2) or 3) in your suggestions, nothing happens or changes. I note Stack isn't populated in 10.2.2, but is in 10.2.1.

Can you point me at instructions to set up a debug build?

**Comment by nsadeveloper789** [comment]
Oh. Thanks for the notes about the plot arrow. I think that might be the give away. There's a double-right green arrow button at the top-right of the Threads window ("Track the tool to the latest snap"). Check if that's on. Even if it appears on, toggle it off and back on just to kick it. Then try stepping again.

If that resolves the issue, close and re-open the Debugger so that the tool gets saved. One of our testers noticed this issue with 10.2, but no one else could reproduce it. My guess is it has to do with Ghidra importing the Debugger tool from an older installation.

**Comment by nsadeveloper789** [comment]
If that doesn't resolve it, and you want to debug the 10.2.2 Debugger, clone the repo, check out this tag: https://github.com/NationalSecurityAgency/ghidra/tree/Ghidra_10.2.2_build, and follow the development instructions here https://github.com/NationalSecurityAgency/ghidra/blob/Ghidra_10.2.2_build/DevGuide.md

**Comment by boondoggler** [comment]
Toggling the arrow cured. Saved, reopened. All good 

Thanks!

**Comment by nsadeveloper789** [comment]
Good deal!
