### ISSUE TITLE
[ARM/THUMB] Assembling a TBB or TBH instruction causes an exception to be thrown

### ISSUE THREAD

**Issue by mikaey** [NationalSecurityAgency/ghidra#4824]
**Describe the bug**
When using the "Patch Instruction" function to add or modify a TBB or TBH instruction, upon typing the last character of the instruction, a "Unexpected exception in Swing Update Manager" error is shown.

**To Reproduce**
1. Open a program and go to the Disassembly view.
2. Right-click on any instruction and choose "Patch Instruction".
3. Enter "tbb [0, r0]".
4. Upon entering the closing right square bracket ("]"), the error will display.

**Expected behavior**
Instruction should be correctly assembled.

**Screenshots**
![image](https://user-images.githubusercontent.com/10555491/207631391-3c07ead6-b792-4e52-aed6-a959f39c2429.png)

**Attachments**
Error log displayed by Ghidra:

```
INTERNAL: Should never be asked to solve for inst_next2
java.lang.AssertionError: INTERNAL: Should never be asked to solve for inst_next2
	at ghidra.app.plugin.assembler.sleigh.expr.Next2InstructionValueSolver.solve(Next2InstructionValueSolver.java:44)
	at ghidra.app.plugin.assembler.sleigh.expr.Next2InstructionValueSolver.solve(Next2InstructionValueSolver.java:35)
	at ghidra.app.plugin.assembler.sleigh.expr.RecursiveDescentSolver.solve(RecursiveDescentSolver.java:122)
	at ghidra.app.plugin.assembler.sleigh.expr.RecursiveDescentSolver.solve(RecursiveDescentSolver.java:158)
	at ghidra.app.plugin.assembler.sleigh.sem.AssemblyTreeResolver.solveOrBackfill(AssemblyTreeResolver.java:522)
	at ghidra.app.plugin.assembler.sleigh.sem.AssemblyTreeResolver.solveOrBackfill(AssemblyTreeResolver.java:562)
	at ghidra.app.plugin.assembler.sleigh.sem.AssemblyOperandState.solveNumeric(AssemblyOperandState.java:123)
	at ghidra.app.plugin.assembler.sleigh.sem.AssemblyOperandState.resolve(AssemblyOperandState.java:134)
	at ghidra.app.plugin.assembler.sleigh.sem.AssemblyConstructState.resolveRemainingChildren(AssemblyConstructState.java:209)
	at ghidra.app.plugin.assembler.sleigh.sem.AssemblyConstructState.resolve(AssemblyConstructState.java:127)
	at ghidra.app.plugin.assembler.sleigh.sem.AssemblyConstructState.resolveRemainingChildren(AssemblyConstructState.java:209)
	at ghidra.app.plugin.assembler.sleigh.sem.AssemblyConstructState.resolve(AssemblyConstructState.java:127)
	at ghidra.app.plugin.assembler.sleigh.sem.AssemblyTreeResolver.lambda$resolve$2(AssemblyTreeResolver.java:111)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:174)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:3215)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:3215)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:3215)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at ghidra.app.plugin.assembler.sleigh.sem.AssemblyTreeResolver.resolve(AssemblyTreeResolver.java:114)
	at ghidra.app.plugin.assembler.sleigh.SleighAssembler.resolveTree(SleighAssembler.java:205)
	at ghidra.app.plugin.core.assembler.AssemblyDualTextField.computeCompletions(AssemblyDualTextField.java:755)
	at ghidra.app.plugin.core.assembler.AssemblyDualTextField$AssemblyAutocompletionModel.computeCompletions(AssemblyDualTextField.java:239)
	at docking.widgets.autocomplete.TextFieldAutocompleter.doUpdateDisplayContents(TextFieldAutocompleter.java:311)
	at docking.widgets.autocomplete.TextFieldAutocompleter.lambda$new$0(TextFieldAutocompleter.java:127)
	at ghidra.util.task.SwingUpdateManager.swingDoWork(SwingUpdateManager.java:108)
	at ghidra.util.task.AbstractSwingUpdateManager.swingExecutePendingWork(AbstractSwingUpdateManager.java:338)
	at ghidra.util.task.AbstractSwingUpdateManager.timerCallback(AbstractSwingUpdateManager.java:287)
	at ghidra.util.task.AbstractSwingUpdateManager.lambda$new$0(AbstractSwingUpdateManager.java:131)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2022-Nov-15 1249 EST
Ghidra Version: 10.2.2
Java Home: C:\Program Files\Java\jdk-19
JVM Version: Oracle Corporation 19.0.1
OS: Windows 10 10.0 amd64
Workstation: MSI
```

**Environment (please complete the following information):**
 - OS: Windows 10 Pro v21H2 Build 19044.2364 (x64)
 - Java Version: java 19.0.1 2022-10-18 (Oracle)
 - Ghidra Version: 10.2.2
 - Ghidra Origin: official GitHub distro

**Comment by GhidorahRex** [comment]
Looking at the instruction in the manual, it should be formated as `tbb [rn, rm]` not `tbb [0,rm]`. The assembler should probably flag it as an invalid instruction format. I've tes ted `tbb [r0, r1]` for instance, and that patches correctly.

**Comment by mikaey** [comment]
> Looking at the instruction in the manual, it should be formated as `tbb [rn, rm]` not `tbb [0,rm]`. The assembler should probably flag it as an invalid instruction format. I've tested `tbb [r0, r1]` for instance, and that patches correctly.

Interesting -- when I try doing `tbb [r0,r1]`, I just get an "Invalid instruction and/or prefix" message.

**Comment by mikaey** [comment]
Hmmm -- maybe this needs to be fixed in the disassembler then -- because the disassembler disassembles it as `tbb [memLocation, rm]`.

**Comment by nsadeveloper789** [comment]
It might help to see a screenshot of the disassembly listing at this point.

If you'd rather not screenshot, at the very least, can we know what language (full ID) you imported with and the raw bytes of the one disassembled instruction, please?

**Comment by nsadeveloper789** [comment]
Actually, we might have figured it out.... Does `memLocation` happen to be the address of the next instruction? I'm thinking this is actually the special case where `rn` is `pc`, and our spec just needs fixing.

**Comment by mikaey** [comment]
> Actually, we might have figured it out.... Does `memLocation` happen to be the address of the next instruction? I'm thinking this is actually the special case where `rn` is `pc`, and our spec just needs fixing.

Yep!
