### ISSUE TITLE
`java.rmi.NoSuchObjectException` when using type library

### ISSUE THREAD

**Issue by mkow** [NationalSecurityAgency/ghidra#4847]
**Describe the bug**

Each time I open anything related to types in my project I get a few message boxes with `java.rmi.NoSuchObjectException`. I can of course click "ok" on each of them, but it's super annoying and makes the types barely usable :(

**To Reproduce**

Basically, anything which uses types, e.g. textboxes with type completion or structure creation:
1. In Listing view, select a bunch of data and click RMB -> `Data` -> `Create structure...`.
2. Get a few windows with Java exceptions.

**Expected behavior**

No Java exceptions message boxes reachable from GUI :)

**Attachments**

Exception log:

```
no such object in table
java.rmi.NoSuchObjectException: no such object in table
	at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:304)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:280)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:165)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:215)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:160)
	at jdk.proxy2/jdk.proxy2.$Proxy40.get(Unknown Source)
	at db.buffers.BufferFileAdapter.get(BufferFileAdapter.java:116)
	at db.buffers.BufferMgr.getBufferNode(BufferMgr.java:802)
	at db.buffers.BufferMgr.getBuffer(BufferMgr.java:956)
	at db.NodeMgr.getFixedKeyNode(NodeMgr.java:292)
	at db.Table.getFieldKeyNode(Table.java:166)
	at db.Table$ShortDurationFieldKeyIterator.initialize(Table.java:3852)
	at db.Table$ShortDurationFieldKeyIterator.<init>(Table.java:3826)
	at db.Table$FieldKeyIterator.<init>(Table.java:3370)
	at db.Table.fieldKeyIterator(Table.java:1985)
	at db.FieldIndexTable.findPrimaryKeys(FieldIndexTable.java:81)
	at db.Table.findRecords(Table.java:1420)
	at ghidra.program.database.data.TypedefDBAdapterV2.getRecordWithIDs(TypedefDBAdapterV2.java:143)
	at ghidra.program.database.data.DataTypeManagerDB.findDataTypeForIDs(DataTypeManagerDB.java:3615)
	at ghidra.program.database.data.DataTypeManagerDB$IdsToDataTypeMap.lambda$getDataType$1(DataTypeManagerDB.java:4095)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at ghidra.program.database.data.DataTypeManagerDB$IdsToDataTypeMap.getDataType(DataTypeManagerDB.java:4094)
	at ghidra.program.database.data.DataTypeManagerDB.getDataType(DataTypeManagerDB.java:3586)
	at ghidra.program.database.data.DataTypeManagerDB.findDataTypeForID(DataTypeManagerDB.java:3596)
	at ghidra.app.util.html.HTMLDataTypeRepresentation.canLinkDataType(HTMLDataTypeRepresentation.java:399)
	at ghidra.app.util.html.HTMLDataTypeRepresentation.generateTypeName(HTMLDataTypeRepresentation.java:407)
	at ghidra.app.util.html.CompositeDataTypeHTMLRepresentation.generateTypeName(CompositeDataTypeHTMLRepresentation.java:340)
	at ghidra.app.util.html.CompositeDataTypeHTMLRepresentation.buildHTMLText(CompositeDataTypeHTMLRepresentation.java:235)
	at ghidra.app.util.html.CompositeDataTypeHTMLRepresentation.<init>(CompositeDataTypeHTMLRepresentation.java:76)
	at ghidra.app.util.ToolTipUtils.getHTMLRepresentation(ToolTipUtils.java:107)
	at ghidra.app.util.ToolTipUtils.getToolTipText(ToolTipUtils.java:77)
	at ghidra.app.plugin.core.data.CreateStructureDialog$StructureCellRenderer.getTableCellRendererComponent(CreateStructureDialog.java:615)
	at docking.widgets.table.GTableCellRenderer.getTableCellRendererComponent(GTableCellRenderer.java:113)
	at java.desktop/javax.swing.JTable.prepareRenderer(JTable.java:5812)
	at java.desktop/javax.swing.plaf.synth.SynthTableUI.paintCell(SynthTableUI.java:688)
	at java.desktop/javax.swing.plaf.synth.SynthTableUI.paintCells(SynthTableUI.java:585)
	at java.desktop/javax.swing.plaf.synth.SynthTableUI.paint(SynthTableUI.java:369)
	at java.desktop/javax.swing.plaf.synth.SynthTableUI.update(SynthTableUI.java:282)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:842)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1119)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5318)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1337)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1105)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:75)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:112)
	at java.desktop/java.awt.Container.paint(Container.java:2005)
	at java.desktop/java.awt.Window.paint(Window.java:3959)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:890)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:862)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:862)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:835)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1898)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1080)
	at java.desktop/java.awt.Component.show(Component.java:1728)
	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
	at java.desktop/java.awt.Window.setVisible(Window.java:1036)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1016)
	at docking.DockingDialog.setVisible(DockingDialog.java:353)
	at docking.DockingWindowManager.lambda$doShowDialog$6(DockingWindowManager.java:1769)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at docking.DockingWindowManager.doShowDialog(DockingWindowManager.java:1773)
	at docking.DockingWindowManager.showDialog(DockingWindowManager.java:1722)
	at docking.AbstractDockingTool.showDialog(AbstractDockingTool.java:158)
	at ghidra.app.plugin.core.data.CreateStructureDialog.showCreateStructureDialog(CreateStructureDialog.java:452)
	at ghidra.app.plugin.core.data.CreateStructureAction.createStructureInProgram(CreateStructureAction.java:171)
	at ghidra.app.plugin.core.data.CreateStructureAction.actionPerformed(CreateStructureAction.java:82)
	at ghidra.app.context.ListingContextAction.actionPerformed(ListingContextAction.java:58)
	at docking.PopupMenuHandler$1.run(PopupMenuHandler.java:63)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2022-Nov-15 1249 EST
Ghidra Version: 10.2.2
Java Home: /usr/lib/jvm/java-17-openjdk-amd64
JVM Version: Private Build 17.0.5
OS: Linux 5.4.0-132-generic amd64
```

**Environment (please complete the following information):**

 - OS: Ubuntu 20.04.5
 - Java Version: see exception
 - Ghidra Version: see exception
 - Ghidra Origin: official GitHub distro

**Additional context**

The project was migrated from previous Ghidra release (one step older).

I can provide more info about the state of the type library if you provide some script snippets for dumping it.

**Comment by ghidra1** [comment]
This issue stems from using a remote project file opened from a Ghidra Server.  Holding open a remote file has known limitations when it comes to a client system going to sleep or suspending as this causes the unresponsive connection to be closed by the server.   This closed RMI connection will cause the exception you are seeing.   At this point in time there is no recovery from this condition other than to close the affect program or archive.

**Comment by mkow** [comment]
Ouch :/

> At this point in time there is no recovery from this condition other than to close the affect program or archive.

That's not really a solution for me, I have a rather large project with multiple open files and Ghidra loses state of these views when restarted.

> This can be avoided by disabling the sleep/suspend for your system.

I can't keep my laptop running 24/7 for months, especially when traveling :)

Are there any other workarounds for this bug?

**Comment by ghidra1** [comment]
Only workaround would be to plugin your laptop and disable suspend.  Display and disk are permitted to sleep but not processing and network.   This is not a bug but a consequence of using remote-objects via RMi which are connection oriented.

**Comment by collinmay** [comment]
Any time I hit this bug, it triggers a popup on every single repaint of the codebrowser window, making it impossible to close and reconnect to the server without killing Ghidra entirely. Is there some way we can make this error less fatal?
