### ISSUE TITLE
Cannot run program [...]/decompile, when switching tabs

### ISSUE THREAD

**Issue by YSaxon** [NationalSecurityAgency/ghidra#4867]
**Describe the bug**

I'm all of a sudden getting an error message, with a title "Please report this stack trace", when switching tabs from one opened file to another. So far, everything else seems to be working fine, and both files were opened and working fine until just now.

My guess is that if I restart everything will be fine, but it asked me to report it, so I am.

The decompiler window for that tab says 
```
  Decompiler: Unable to initialize the DecompilerInterface: Cannot run program
       "/opt/homebrew/Caskroom/ghidra/10.1.5-20220726/ghidra_10.1.5_PUBLIC/Ghidra/Features/Decompile r/os/mac_x86_64/decompile":
       error=2, No such file or directory
```

I've also checked the file it says it cannot run, and it is both there and runnable..

The error popup stacktrace message is:
```
Cannot run program "/opt/homebrew/Caskroom/ghidra/10.1.5-20220726/ghidra_10.1.5_PUBLIC/Ghidra/Features/Decompiler/os/mac_x86_64/decompile": error=2, No such file or directory
java.io.IOException: Cannot run program "/opt/homebrew/Caskroom/ghidra/10.1.5-20220726/ghidra_10.1.5_PUBLIC/Ghidra/Features/Decompiler/os/mac_x86_64/decompile": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at java.base/java.lang.Runtime.exec(Runtime.java:451)
	at ghidra.app.decompiler.DecompileProcess.setup(DecompileProcess.java:123)
	at ghidra.app.decompiler.DecompileProcess.registerProgram(DecompileProcess.java:440)
	at ghidra.app.decompiler.DecompInterface.initializeProcess(DecompInterface.java:228)
	at ghidra.app.decompiler.DecompInterface.openProgram(DecompInterface.java:323)
	at ghidra.app.decompiler.component.Decompiler.getDecompilerInterface(Decompiler.java:79)
	at ghidra.app.decompiler.component.Decompiler.decompile(Decompiler.java:48)
	at ghidra.app.decompiler.component.DecompilerManager.decompile(DecompilerManager.java:175)
	at ghidra.app.decompiler.component.DecompileRunnable.monitoredRun(DecompileRunnable.java:108)
	at ghidra.util.task.RunManager$RunnerJob.doExecute(RunManager.java:334)
	at ghidra.util.task.RunManager$RunnerJob.run(RunManager.java:309)
	at ghidra.util.worker.AbstractWorker$JobCallback.process(AbstractWorker.java:133)
	at ghidra.util.worker.AbstractWorker$JobCallback.process(AbstractWorker.java:123)
	at generic.concurrent.ConcurrentQ$CallbackCallable.call(ConcurrentQ.java:658)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 21 more

---------------------------------------------------
Build Date: 2022-Jul-26 1543 EDT
Ghidra Version: 10.1.5
Java Home: /opt/homebrew/Cellar/openjdk@11/11.0.16.1/libexec/openjdk.jdk/Contents/Home
JVM Version: Homebrew 11.0.16.1
OS: Mac OS X 12.6 aarch64
```

**Comment by ryanmkurtz** [comment]
This is typically due to macOS Gatekeeper.  Can you check your macOS `Privacy & Security` settings to see if the decompiler is being mentioned there?
