### ISSUE TITLE
Version tracker error RE: Blocking an already accepted association

### ISSUE THREAD

**Issue by Decryptortuning** [NationalSecurityAgency/ghidra#4875]
Version tracking error.
"Attempted to block already accepted association!"
```
ghidra.util.exception.AssertException: Attempted to block already accepted association!
	at ghidra.feature.vt.api.db.AssociationDatabaseManager.blockRelatedAssociations(AssociationDatabaseManager.java:558)
	at ghidra.feature.vt.api.db.AssociationDatabaseManager.setAssociationAccepted(AssociationDatabaseManager.java:538)
	at ghidra.feature.vt.api.db.VTAssociationDB.setAccepted(VTAssociationDB.java:184)
	at ghidra.feature.vt.gui.actions.AutoVersionTrackingTask.tryToSetAccepted(AutoVersionTrackingTask.java:427)
	at ghidra.feature.vt.gui.actions.AutoVersionTrackingTask.tryToAcceptMatchAndApplyMarkup(AutoVersionTrackingTask.java:526)
	at ghidra.feature.vt.gui.actions.AutoVersionTrackingTask.applyDuplicateFunctionMatches(AutoVersionTrackingTask.java:503)
	at ghidra.feature.vt.gui.actions.AutoVersionTrackingTask.correlateAndPossiblyApplyDuplicateFunctions(AutoVersionTrackingTask.java:361)
	at ghidra.feature.vt.gui.actions.AutoVersionTrackingTask.doRun(AutoVersionTrackingTask.java:199)
	at ghidra.feature.vt.gui.actions.AutoVersionTrackingTask.run(AutoVersionTrackingTask.java:123)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**To Reproduce**
1.Create a new version tracking session.
2. Compare two databases
3. Run auto-magic tool for matches.
4. Tool does not pass error. Session will not find matches.

**Expected behavior**
Version tracking auto-magic tool to complete and display matches.

Build Date: 2022-Nov-15 1249 EST
Ghidra Version: 10.2.2
Java Home: C:\Program Files\Java\jdk-18.0.2.1
JVM Version: Oracle Corporation 18.0.2.1
OS: Windows 10 10.0 amd64
Workstation: RYZEN-TOWER
Clean current ghidra release.

I can provide my DB discretely to a dev if needed.

![Ghidra](https://user-images.githubusercontent.com/19156562/211072974-593c4db3-af04-4b36-81a9-ee0fa34e2e96.PNG)

**Comment by Decryptortuning** [comment]
Not long after this attempting more version tracking.
![Ghidra2](https://user-images.githubusercontent.com/19156562/211092692-7800cc9f-5402-4665-bcd4-1bce4049157f.PNG)

**Comment by dragonmacher** [comment]
We will look into the error.  In the meantime, you can start over and avoid using the auto-version tracking feature.  Instead, use the plus button to run correlators of your choosing.     You can run the simple exact matching correlators first and later run the more speculative correlators.

**Comment by ryanmkurtz** [comment]
@Decryptortuning Feel free to DM me on Twitter to share your problematic program so we can debug.

**Comment by ghidra007** [comment]
The auto version tracker does the following in order if you want to manually try to recreate the issue:
1. Run the exact symbol correlator and apply only those matches. 
2. Run the exact data correlator and apply only those matches.
3. Run the exact function bytes correlator and apply only those matches.
4. Run the exact function instruction correlator and apply only those matches.
5. Run the exact function mnemonic correlator and apply only those matches.

NOTE: At each step make sure not to apply the implied matches that get found in the process of finding other matches. You can use the filters to only show particular correlator matches and also remove from the table any that have been applied already. 

6. Run the duplicate function correlator. This is the step I think is causing issues above. The ones above all look for exact unique matches. This one looks for the case where there are multiple "matching" functions and tries to find the matching ones by looking at operands that match.  In this case when you choose one of the possible matches it blocks the others. I'm guessing one of the matches it is trying to block may have been found with another correlator and it isn't taking that into account. If you could run this correlator after running the ones above and inspect them could you let us know if that is what is happening? You might have to try making a match out of one of the duplicate matches to see if you can recreate the issue. I'll try mocking up a case to see if I can reproduce the issue and test a fix. If you could share your programs with ryanmkurtz it would be easier to triage. 

7. After running the above correlator, The auto version tracker does more speculative matching by running the various reference correlators and matching ones scoring above a particularly set threshold.

**Comment by ryanmkurtz** [comment]
Cannot reproduce...original sample needed.

**Comment by ghidra007** [comment]
Decided to add checks to prevent blow up. Still not sure what is causing it to get in this state.
