### ISSUE TITLE
CParser.parse() struct bug introduced in 10.2?

### ISSUE THREAD

**Issue by phix33** [NationalSecurityAgency/ghidra#4903]
**Describe the bug**
CParser fails (ParseException) to parse 'simple' structs using python script in latest version. Script works in 10.1.5 but not in 10.2 or 10.2.2. 

**To Reproduce**
1. Using script  _Originally posted by @jarodcsaxberg in https://github.com/NationalSecurityAgency/ghidra/issues/1986#issuecomment-643710738_ 
2. We can successfully run that script in 10.1.5 and 10.2.2.
3. However, if we change the imported string to be:

```
mystruct_txt="""
struct mystruct {
    int field1;
    int field2;
};"""
```

Then fails on "parser.parse(mystruct_txt)" with ParseException on 10.2, 10.2.2 but imports successfully in 10.1.5.

**Expected behavior**
Would have expected the above struct to be imported. Couldn't see any relevant lines in the 10.2 Changelogs.

**Environment:**
 - OS: Ubuntu 22
 - Java Version: 19.0.1
 - Ghidra Version: 10.2.2., 10.2, 10.1.5
 - Ghidra Origin: Official ghidra release binaries

**Comment by Katharsas** [comment]
I have probably the same problem with Java. When calling the CParser like this:
```java
var parser = new CParser(programDtm);
parser.parse(text);
```
i get a NullPointerException:

```
WARN  java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "ghidra.program.model.data.DataType.getSourceArchive()" is null (CParser) java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "ghidra.program.model.data.DataType.getSourceArchive()" is null
	at ghidra.app.util.cparser.C.CParser.defineNamedComposite(CParser.java:349)
	at ghidra.app.util.cparser.C.CParser.StructOrUnionSpecifier(CParser.java:2562)
	at ghidra.app.util.cparser.C.CParser.TypeSpecifier(CParser.java:1439)
	at ghidra.app.util.cparser.C.CParser.DeclarationSpecifiers(CParser.java:1165)
	at ghidra.app.util.cparser.C.CParser.Declaration(CParser.java:1044)
	at ghidra.app.util.cparser.C.CParser.ExternalDeclaration(CParser.java:905)
	at ghidra.app.util.cparser.C.CParser.TranslationUnit(CParser.java:891)
	at ghidra.app.util.cparser.C.CParser.parse(CParser.java:770)
	at ghidra.app.util.cparser.C.CParser.parse(CParser.java:754)
```
