### ISSUE TITLE
Unexpected exception in Swing Update Manager

### ISSUE THREAD

**Issue by f4lkensmaz3** [NationalSecurityAgency/ghidra#4916]
Hello ghidra team,

I am getting this error when trying to open Function Graph. My OS and Java version attached in logs.
I tried both recommended java versions, but still same.
```
Cannot invoke "edu.uci.ics.jung.visualization.VisualizationViewer.getPickedVertexState()" because "viewer" is null
java.lang.NullPointerException: Cannot invoke "edu.uci.ics.jung.visualization.VisualizationViewer.getPickedVertexState()" because "viewer" is null
	at ghidra.graph.VisualGraphComponentProvider.getSelectedVertices(VisualGraphComponentProvider.java:107)
	at ghidra.app.plugin.core.functiongraph.FGProvider.createKeybindingContext(FGProvider.java:332)
	at ghidra.app.plugin.core.functiongraph.FGProvider.getActionContext(FGProvider.java:278)
	at docking.GlobalMenuAndToolBarManager.getContext(GlobalMenuAndToolBarManager.java:212)
	at docking.GlobalMenuAndToolBarManager.updateActions(GlobalMenuAndToolBarManager.java:191)
	at docking.GlobalMenuAndToolBarManager.lambda$new$0(GlobalMenuAndToolBarManager.java:41)
	at ghidra.util.task.SwingUpdateManager.swingDoWork(SwingUpdateManager.java:108)
	at ghidra.util.task.AbstractSwingUpdateManager.swingExecutePendingWork(AbstractSwingUpdateManager.java:338)
	at ghidra.util.task.AbstractSwingUpdateManager.timerCallback(AbstractSwingUpdateManager.java:287)
	at ghidra.util.task.AbstractSwingUpdateManager.lambda$new$0(AbstractSwingUpdateManager.java:131)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2022-Nov-15 1249 EST
Ghidra Version: 10.2.2
Java Home: /usr/lib/jvm/java-17-amazon-corretto
JVM Version: Amazon.com Inc. 17.0.6
OS: Linux 5.16.0-kali7-amd64 amd64

```
Edit : I'm running kali in QEMU virtual machine. Issue might be relevant with this.
Edit2 : I just succeeded to run it in Fedora on QEMU. So I think issue is not relevant with qemu.

**Comment by dragonmacher** [comment]
This sounds like a timing problem.    Unfortunately, I am unable to reproduce the issue.

Does the Function Graph open after you get this error?

**Comment by f4lkensmaz3** [comment]
![error](https://user-images.githubusercontent.com/96619492/214384402-5bbf5997-b21a-417a-bfc1-2767707e2068.jpg)
It's just prints "Graphing Function", and nothing happens.

**Comment by dragonmacher** [comment]
I see.   Will the tool work for you if you close all error dialogs?

I have put a fix in for this particular issue, which will be in the repo soon.

**Comment by f4lkensmaz3** [comment]
No, nothing works after close the dialogs. Also I updated my previous post, check out.

**Comment by dragonmacher** [comment]
If you are running from our repo, with the ability to make changes to our source code, then I can provide a change to make to get you past this issue.  Otherwise, the fix will not be available until the next build of Ghidra.

**Comment by f4lkensmaz3** [comment]
Yes. I can build for myself. I just need patches.

**Comment by dragonmacher** [comment]
The edit is inside of `ghidra.graph.VisualGraphComponentProvider`.     

There is a method that looks like this:
```
	public Set<V> getSelectedVertices() {
		VisualGraphView<V, E, G> view = getView();
		VisualizationViewer<V, E> viewer = view.getPrimaryGraphViewer();
		PickedState<V> pickedState = viewer.getPickedVertexState();
		return pickedState.getPicked();
	}
```

You need to update the method to this:

```
	public Set<V> getSelectedVertices() {
		VisualGraphView<V, E, G> view = getView();
		VisualizationViewer<V, E> viewer = view.getPrimaryGraphViewer();
		if (viewer == null) {
			// we have seen this happen on some systems; timing issue?
			return Collections.emptySet();
		}
		PickedState<V> pickedState = viewer.getPickedVertexState();
		return pickedState.getPicked();
	}
```

**Comment by f4lkensmaz3** [comment]
No luck. I got similar error.

```
Cannot invoke "ghidra.graph.viewer.GraphComponent.getRenderContext()" because "this.graphComponent" is null
java.lang.NullPointerException: Cannot invoke "ghidra.graph.viewer.GraphComponent.getRenderContext()" because "this.graphComponent" is null
	at ghidra.graph.viewer.VisualGraphView.generateGraphPerspective(VisualGraphView.java:325)
	at ghidra.app.plugin.core.functiongraph.mvc.FGController.getGraphPerspective(FGController.java:789)
	at ghidra.app.plugin.core.functiongraph.FGProvider.getMemento(FGProvider.java:1233)
	at ghidra.app.plugin.core.navigation.NavigationHistoryPlugin$HistoryList.getProgramLocation(NavigationHistoryPlugin.java:656)
	at ghidra.app.plugin.core.navigation.NavigationHistoryPlugin$HistoryList.getPreviousStartFunction(NavigationHistoryPlugin.java:630)
	at ghidra.app.plugin.core.navigation.NavigationHistoryPlugin$HistoryList.previousFunction(NavigationHistoryPlugin.java:609)
	at ghidra.app.plugin.core.navigation.NavigationHistoryPlugin$HistoryList.hasPreviousFunction(NavigationHistoryPlugin.java:548)
	at ghidra.app.plugin.core.navigation.NavigationHistoryPlugin.hasPreviousFunction(NavigationHistoryPlugin.java:235)
	at ghidra.app.plugin.core.navigation.NextPrevAddressPlugin$NextPreviousFunctionAction.isEnabledForContext(NextPrevAddressPlugin.java:412)
	at docking.DockingActionProxy.isEnabledForContext(DockingActionProxy.java:188)
	at docking.WindowActionManager.contextChanged(WindowActionManager.java:108)
	at docking.GlobalMenuAndToolBarManager.updateActions(GlobalMenuAndToolBarManager.java:193)
	at docking.GlobalMenuAndToolBarManager.lambda$new$0(GlobalMenuAndToolBarManager.java:41)
	at ghidra.util.task.SwingUpdateManager.swingDoWork(SwingUpdateManager.java:108)
	at ghidra.util.task.AbstractSwingUpdateManager.swingExecutePendingWork(AbstractSwingUpdateManager.java:338)
	at ghidra.util.task.AbstractSwingUpdateManager.timerCallback(AbstractSwingUpdateManager.java:287)
	at ghidra.util.task.AbstractSwingUpdateManager.lambda$new$0(AbstractSwingUpdateManager.java:131)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2023-Jan-24 1804 EST
Ghidra Version: 10.3
Java Home: /home/kali/jdk-17.0.6+10
JVM Version: Eclipse Adoptium 17.0.6
OS: Linux 6.0.0-kali3-amd64 amd64
```

**Comment by dragonmacher** [comment]
OK.  Next fix.  Inside of `ghidra.graph.VisualGraphView`, change this:

```
	public GraphPerspectiveInfo<V, E> generateGraphPerspective() {
		RenderContext<V, E> context = graphComponent.getRenderContext();
		return new GraphPerspectiveInfo<>(context, getZoom());
	}
```

to this:

```
	public GraphPerspectiveInfo<V, E> generateGraphPerspective() {
		if (graphComponent == null) {
			return GraphPerspectiveInfo.createInvalidGraphPerspectiveInfo();
		}
		RenderContext<V, E> context = graphComponent.getRenderContext();
		return new GraphPerspectiveInfo<>(context, getZoom());
	}
```

**Comment by f4lkensmaz3** [comment]
We got bugs over here. It's just stuck on 'Graphing Function'. I'd wait a while but nothing happened. And clicking topbar buttons give me these errors.
```
Cannot invoke "ghidra.app.plugin.core.functiongraph.graph.FGComponent.setVertexFocused(ghidra.app.plugin.core.functiongraph.graph.vertex.FGVertex, ghidra.program.util.ProgramLocation)" because "this.fgComponent" is null
java.lang.NullPointerException: Cannot invoke "ghidra.app.plugin.core.functiongraph.graph.FGComponent.setVertexFocused(ghidra.app.plugin.core.functiongraph.graph.vertex.FGVertex, ghidra.program.util.ProgramLocation)" because "this.fgComponent" is null
	at ghidra.app.plugin.core.functiongraph.mvc.FGView.setLocation(FGView.java:118)
	at ghidra.app.plugin.core.functiongraph.mvc.CurrentFunctionGraphViewSettings.setLocation(CurrentFunctionGraphViewSettings.java:57)
	at ghidra.app.plugin.core.functiongraph.mvc.FGController.display(FGController.java:538)
	at ghidra.app.plugin.core.functiongraph.FGProvider.displayLocation(FGProvider.java:527)
	at ghidra.app.plugin.core.functiongraph.FGProvider.setLocationNow(FGProvider.java:520)
	at ghidra.app.plugin.core.functiongraph.FGProvider.setPendingLocationFromUpdateManager(FGProvider.java:507)
	at ghidra.app.plugin.core.functiongraph.FGProvider.lambda$new$2(FGProvider.java:129)
	at ghidra.util.task.SwingUpdateManager.swingDoWork(SwingUpdateManager.java:108)
	at ghidra.util.task.AbstractSwingUpdateManager.swingExecutePendingWork(AbstractSwingUpdateManager.java:338)
	at ghidra.util.task.AbstractSwingUpdateManager.checkForWork(AbstractSwingUpdateManager.java:278)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2023-Jan-24 1844 EST
Ghidra Version: 10.3
Java Home: /home/kali/jdk-17.0.6+10
JVM Version: Eclipse Adoptium 17.0.6
OS: Linux 6.0.0-kali3-amd64 amd64
```

Error in Domain Object listener
```
Cannot invoke "ghidra.app.plugin.core.functiongraph.graph.FGComponent.setGraphViewStale(boolean)" because "this.fgComponent" is null
java.lang.NullPointerException: Cannot invoke "ghidra.app.plugin.core.functiongraph.graph.FGComponent.setGraphViewStale(boolean)" because "this.fgComponent" is null
	at ghidra.app.plugin.core.functiongraph.mvc.FGView.setGraphViewStale(FGView.java:220)
	at ghidra.app.plugin.core.functiongraph.mvc.FGController.invalidateAllCacheForProgram(FGController.java:808)
	at ghidra.app.plugin.core.functiongraph.FGProvider.updateGraphForAffectedAddresses(FGProvider.java:669)
	at ghidra.app.plugin.core.functiongraph.FGProvider.domainObjectChanged(FGProvider.java:637)
	at ghidra.framework.data.DomainObjectChangeSupport$EventNotification.doNotify(DomainObjectChangeSupport.java:297)
	at ghidra.framework.data.DomainObjectChangeSupport.doSendEventsNow(DomainObjectChangeSupport.java:164)
	at ghidra.framework.data.DomainObjectChangeSupport.lambda$sendEventNow$3(DomainObjectChangeSupport.java:158)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.framework.data.DomainObjectChangeSupport.sendEventNow(DomainObjectChangeSupport.java:158)
	at ghidra.framework.data.DomainObjectChangeSupport.flush(DomainObjectChangeSupport.java:134)
	at ghidra.framework.data.DomainObjectAdapter.flushEvents(DomainObjectAdapter.java:220)
	at ghidra.framework.data.DomainObjectDBTransaction$1.run(DomainObjectDBTransaction.java:89)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2023-Jan-24 1844 EST
Ghidra Version: 10.3
Java Home: /home/kali/jdk-17.0.6+10
JVM Version: Eclipse Adoptium 17.0.6
OS: Linux 6.0.0-kali3-amd64 amd64
```

**Comment by dragonmacher** [comment]
I was hoping a couple simple fixes would get you past your initial issue.  However, it sounds like something more serious is not working under the hood.

I'm curious to see what you log file has in it.     The easiest thing would be to to start fresh:

-  close Ghidra
-  revert all changes made for this ticket
-  delete or copy your application.log file located in `user home/.ghidra/.ghidra_vesion/application.log`
-  rerun Ghidra and trigger the issue
-  post the contents of the log file

**Comment by f4lkensmaz3** [comment]
It's all yours. Thanks for help @dragonmacher
[application.log](https://github.com/NationalSecurityAgency/ghidra/files/10495163/application.log)

**Comment by dragonmacher** [comment]
I see an exception in the log that I think is preventing the Function Graph from correctly initializing.

```
2023-01-24 19:54:04 ERROR (RunManager) Unexpected Exception Running Job java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	at edu.uci.ics.jung.visualization.control.RotatingGraphMousePlugin.<init>(RotatingGraphMousePlugin.java:58)
	at edu.uci.ics.jung.visualization.control.RotatingGraphMousePlugin.<init>(RotatingGraphMousePlugin.java:48)
	at edu.uci.ics.jung.visualization.control.SatelliteRotatingGraphMousePlugin.<init>(SatelliteRotatingGraphMousePlugin.java:30)
	at edu.uci.ics.jung.visualization.control.ModalSatelliteGraphMouse.loadPlugins(ModalSatelliteGraphMouse.java:36)
	at edu.uci.ics.jung.visualization.control.DefaultModalGraphMouse.<init>(DefaultModalGraphMouse.java:61)
	at edu.uci.ics.jung.visualization.control.ModalSatelliteGraphMouse.<init>(ModalSatelliteGraphMouse.java:28)
	at edu.uci.ics.jung.visualization.control.ModalSatelliteGraphMouse.<init>(ModalSatelliteGraphMouse.java:24)
	at edu.uci.ics.jung.visualization.control.SatelliteVisualizationViewer.<init>(SatelliteVisualizationViewer.java:56)
	at ghidra.graph.viewer.SatelliteGraphViewer.<init>(SatelliteGraphViewer.java:43)
	at ghidra.graph.viewer.GraphComponent.createSatelliteGraphViewer(GraphComponent.java:306)
	at ghidra.graph.viewer.GraphComponent.buildSatelliteViewer(GraphComponent.java:314)
	at ghidra.graph.viewer.GraphComponent.build(GraphComponent.java:165)
```

I have not seen this exception before, but here is how I interpret it:

- The Function Graph is initializing it's Satellite Viewer
- The Ghidra Satellite Viewer is calling the super class the Jung Satellite Viewer's constructor
- The Jung Satellite Viewer adds a few mouse handling items
- One of the mouse handling items attempts to create a custom cursor
- The Jung`RotatingGraphMousePlugin` is calling Java to get the preferred cursor size `Dimension cd = Toolkit.getDefaultToolkit().getBestCursorSize(16,16);`
- That method is unexpectedly returning a size of 0
- When Jung later uses that size of 0, we see the above exception

What does this all mean?     I'm not really sure.   For some reason, on your system (and no others that I have seen), the Java method is returning a 0 value.  The Jung code is not handling this.

My take is that your OS has some UI setting on related to cursors.   Whatever that setting is, it is causing Java to report the 0 value above. 

Do you have any special settings turned on related to the mouse or the cursor?

**Comment by tomnelson** [comment]
The javadoc for (some version I have of) Toolkit.java says this:

          Systems which don't support custom cursors will return a dimension of 0, 0.
          
 in the called getBestCursorSize method.
 I agree that jung should have protected against this. I've never seen the error before.
 
 Does anyone using Ghidra even care about the RotatingGraphMousePlugin?

**Comment by dragonmacher** [comment]
> Does anyone using Ghidra even care about the RotatingGraphMousePlugin?

It looks like it is not being used.  After the call to super(), the Ghidra viewer will install `VisualGraphSatelliteGraphMouse`.

**Comment by tomnelson** [comment]
With this version of jung, I think you'd need to extend SatelliteVisualizationViewer and have it call a CTOR for a ModalSatelliteGraphMouse extension that changes its loadPlugins to not create the Rotating (and Shearing) plugins that you don't want anyway. What a PITA. Sorry. 
Later work has the graphMouse available to set in a Builder, so it would be more flexible.

**Comment by dragonmacher** [comment]
> What a PITA. Sorry.

Not a big deal in the bigger scheme of things.  The problem has taken this many years to present itself.  I still think this can be fixed by a user OS setting.
