### ISSUE TITLE
Headless analyzer crashes when specifying projectLibrarySearchFolder

### ISSUE THREAD

**Issue by XeR** [NationalSecurityAgency/ghidra#4929]
**Describe the bug**
Using the `-loader-projectLibrarySearchFolder` with the headless analyzer throws an Exception.

**To Reproduce**
```sh
$GHIDRA_INSTALL_DIR/support/analyzeHeadless \
	$ghidra_dir $project_name \
	-import /bin/ls \
	-loader ElfLoader -loader-projectLibrarySearchFolder /
```

Based on the dependency graph, this *should* also affect other loaders such as `CoffLoader`, `MSCoffLoader`, `MachoLoader`, `MzLoader`, `NeLoader`, `DbgLoader`, and `PeLoader`. I do not have the programs to confirm this claim.

**Expected behavior**
The binary should be imported. The libraries located in specified directory should be linked to the newly-imported program.

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: 19.0.2
 - Ghidra Version: 10.2.2
 - Ghidra Origin: ArchLinux package ([built by this script](https://github.com/archlinux/svntogit-community/blob/0345c85c72067b8fedcd92b9fcdd0b8996973650/trunk/PKGBUILD))

**Additional context**
[HeadlessAnalyzer.java](https://github.com/NationalSecurityAgency/ghidra/blob/Ghidra_10.2.2_build/Ghidra/Features/Base/src/main/java/ghidra/app/util/headless/HeadlessAnalyzer.java#L1650-L1659) always pass `null` as a `DomainFolder` (as explained by the comment a few lines above).

This `null` is then dereferenced later, in `AbstractLibrarySupportLoader`.

Full stack trace:
```
INFO  IMPORTING: /bin/ls (HeadlessAnalyzer)  
INFO  Successfully applied "-loader-projectLibrarySearchFolder" to "Project Library Search Folder" (old: "", new: "/") (AutoImporter)  
INFO  Using Loader: Executable and Linking Format (ELF) (AutoImporter)  
ERROR REPORT: Cannot invoke "ghidra.framework.model.DomainFolder.getProjectData()" because "programFolder" is null (HeadlessAnalyzer) java.lang.NullPointerException: Cannot invoke "ghidra.framework.model.DomainFolder.getProjectData()" because "programFolder" is null
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.getLinkSearchFolder(AbstractLibrarySupportLoader.java:255)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadLibraries(AbstractLibrarySupportLoader.java:466)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:103)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:126)
	at ghidra.app.util.importer.AutoImporter.importFresh(AutoImporter.java:199)
	at ghidra.app.util.importer.AutoImporter.importFresh(AutoImporter.java:156)
	at ghidra.app.util.importer.AutoImporter.importByUsingSpecificLoaderClass(AutoImporter.java:77)
	at ghidra.app.util.headless.HeadlessAnalyzer.loadProgram(HeadlessAnalyzer.java:1652)
	at ghidra.app.util.headless.HeadlessAnalyzer.processFileWithImport(HeadlessAnalyzer.java:1523)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1689)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1754)
	at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:445)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:127)
	at ghidra.GhidraLauncher.launch(GhidraLauncher.java:77)
	at ghidra.Ghidra.main(Ghidra.java:54)
 
java.lang.NullPointerException: Cannot invoke "ghidra.framework.model.DomainFolder.getProjectData()" because "programFolder" is null
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.getLinkSearchFolder(AbstractLibrarySupportLoader.java:255)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadLibraries(AbstractLibrarySupportLoader.java:466)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:103)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:126)
	at ghidra.app.util.importer.AutoImporter.importFresh(AutoImporter.java:199)
	at ghidra.app.util.importer.AutoImporter.importFresh(AutoImporter.java:156)
	at ghidra.app.util.importer.AutoImporter.importByUsingSpecificLoaderClass(AutoImporter.java:77)
	at ghidra.app.util.headless.HeadlessAnalyzer.loadProgram(HeadlessAnalyzer.java:1652)
	at ghidra.app.util.headless.HeadlessAnalyzer.processFileWithImport(HeadlessAnalyzer.java:1523)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1689)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1754)
	at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:445)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:127)
	at ghidra.GhidraLauncher.launch(GhidraLauncher.java:77)
	at ghidra.Ghidra.main(Ghidra.java:54)
ERROR REPORT: Import failed for file: /bin/ls (HeadlessAnalyzer)  
```

**Comment by ryanmkurtz** [comment]
We've been working on a fix for this internally...the Loaders/AutoImporter are going through a major refactor to accommodate loading libraries from headless.
