### ISSUE TITLE
Deadlock fatal error

### ISSUE THREAD

**Issue by UnrealKaraulov** [NationalSecurityAgency/ghidra#4954]
**Describe the bug**
Deadlock error

**To Reproduce**
1. Go to 'Analysis'
2. Click on 'Analyze'

**Expected behavior**
Analyze finished without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/88730285/216565657-90261e1e-8d5f-4fe9-833a-24f1579a44c3.png)

**Environment (please complete the following information):**
 - OS: Win64 10 
 - Java Version: [jdk-19]
 - Ghidra Version: [10.3]
 - Ghidra Origin: [https://github.com/roblabla/ghidra-ci] 

**Attachments**
**Additional context**
```
Timed-out waiting to run a Swing task--potential deadlock!
java.lang.RuntimeException: Timed-out waiting to run a Swing task--potential deadlock!
	at ghidra.util.Swing.runNow(Swing.java:177)
	at ghidra.framework.data.DomainObjectChangeSupport.sendEventNow(DomainObjectChangeSupport.java:158)
	at ghidra.framework.data.DomainObjectChangeSupport.flush(DomainObjectChangeSupport.java:134)
	at ghidra.framework.data.DomainObjectAdapter.flushPrivateEventQueue(DomainObjectAdapter.java:278)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:709)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:788)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:667)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:632)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.app.plugin.core.analysis.AnalyzeAllOpenProgramsTask$MyAnalysisBackgroundCommand.applyTo(AnalyzeAllOpenProgramsTask.java:372)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:336)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: ghidra.util.exception.UnableToSwingException: Timed-out waiting for Swing thread lock in 20 SECONDS
	at ghidra.util.Swing.waitFor(Swing.java:256)
	at ghidra.util.Swing.runNow(Swing.java:235)
	at ghidra.util.Swing.runNow(Swing.java:163)
	... 12 more

---------------------------------------------------
Build Date: 2023-Feb-01 1540 UTC
Ghidra Version: 10.3
Java Home: C:\Program Files\Java\jdk-19
JVM Version: Oracle Corporation 19.0.2
OS: Windows 10 10.0 amd64
Workstation: KAR

Unspecified error occurred.
---------------------------------------------------
Build Date: 2023-Feb-01 1540 UTC
Ghidra Version: 10.3
Java Home: C:\Program Files\Java\jdk-19
JVM Version: Oracle Corporation 19.0.2
OS: Windows 10 10.0 amd64
Workstation: KAR

Fri Feb 03 12:08:03 MSK 2023     Tree Name = Program Tree, AddressSet = [empty]

Fri Feb 03 12:08:03 MSK 2023     Event: ProgramHighlight  Source: CodeBrowserPlugin
Fri Feb 03 12:08:03 MSK 2023     Event: Program Opened  Source: ProgramManagerPlugin
Fri Feb 03 12:08:03 MSK 2023     Event: Open Program  Source: ProgramManagerPlugin
Fri Feb 03 12:08:03 MSK 2023     Event: Open Program  Source: ProgramManagerPlugin
Fri Feb 03 12:08:03 MSK 2023     Event: Program Activated  Source: ProgramManagerPlugin
Fri Feb 03 12:08:03 MSK 2023     Event: ProgramLocationChange  Source: CodeBrowserPlugin
	Details: ghidra.program.util.MemoryBlockStartFieldLocation addr==> 00001000
	MemoryBlockStartFieldLocation@00001000, row=0, col=0, charOffset=0, Comment Type = -1

Fri Feb 03 12:08:03 MSK 2023     Event: ProgramHighlight  Source: CodeBrowserPlugin
Fri Feb 03 12:08:03 MSK 2023     Tree Name = Program Tree, AddressSet = [[00001000, 01181a0b] [01182000, 011830b7] [01184000, 01184003] ]
Fri Feb 03 12:08:03 MSK 2023     Tree Name = Program Tree, AddressSet = [[00001000, 01181a0b] [01182000, 011830b7] [01184000, 01184003] ]
Fri Feb 03 12:08:03 MSK 2023     Event: External Program Location Change  Source: ProgramManagerPlugin
Fri Feb 03 12:08:03 MSK 2023     Event: ProgramHighlight  Source: CodeBrowserPlugin
Fri Feb 03 12:08:03 MSK 2023     Event: ProgramHighlight  Source: CodeBrowserPlugin
Fri Feb 03 12:08:04 MSK 2023     Event: ProgramLocationChange  Source: GoToServicePlugin
	Details: ghidra.program.util.FunctionReturnTypeFieldLocation addr==> 000023bc
	FunctionReturnTypeFieldLocation@000023bc, row=0, col=0, charOffset=0, Function signature = undefined entry(), Function Return Type: undefined

Fri Feb 03 12:08:04 MSK 2023     Event: External Program Location Change  Source: ProgramManagerPlugin

Transaction has been terminated
db.TerminatedTransactionException: Transaction has been terminated
	at ghidra.framework.data.AbstractTransactionManager.startTransaction(AbstractTransactionManager.java:203)
	at ghidra.framework.data.DomainObjectAdapterDB.startTransaction(DomainObjectAdapterDB.java:347)
	at ghidra.framework.data.DomainObjectAdapterDB.startTransaction(DomainObjectAdapterDB.java:338)
	at ghidra.framework.data.DomainObjectAdapterDB.startTransaction(DomainObjectAdapterDB.java:333)
	at ghidra.app.plugin.core.analysis.AnalyzeAllOpenProgramsTask.setOptions(AnalyzeAllOpenProgramsTask.java:174)
	at ghidra.app.plugin.core.analysis.AnalyzeAllOpenProgramsTask.run(AnalyzeAllOpenProgramsTask.java:94)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

---------------------------------------------------
Build Date: 2023-Feb-01 1540 UTC
Ghidra Version: 10.3
Java Home: C:\Program Files\Java\jdk-19
JVM Version: Oracle Corporation 19.0.2
OS: Windows 10 10.0 amd64
Workstation: KAR
```

**Comment by dragonmacher** [comment]
Is this reproducible?    Does this happen every time you try to analyze?   Is this only for one particular binary or for any binary?

**Comment by UnrealKaraulov** [comment]
@dragonmacher 
In latest released version no problems. 
[DF.zip](https://github.com/NationalSecurityAgency/ghidra/files/10579484/DF.zip)

Yes when analyze any big macos x86-32 binary, for example [DF.zip](https://github.com/NationalSecurityAgency/ghidra/files/10579484/DF.zip)

**Comment by dragonmacher** [comment]
If you run into this again with a particularly large binary, it is possible to update the timeout value.   Generally, this should not be needed.  To change this value, you would edit the `{install dir}/support/launch.properties` file to add a new vm argument, adding this line:
`VMARGS=-Dghidra.util.swing.timeout.seconds=40`

The default value is 20.      The property is there in an attempt to catch lockups.  But, you can make the value  anything you desire without affecting Ghidra's functionality.

**Comment by dragonmacher** [comment]
Closing this for now.   We can reopen if this is reproducible.

**Comment by Roadou** [comment]
Hello,

This happened to me too with large binaries (400MB+).
Adding  VMARGS=-Dghidra.util.swing.timeout.seconds=40 seems to solve the problem, i think increasing this value by default would be great for other people having similar issues if it doesn't cause problems.
