### ISSUE TITLE
Used to be able to open project; can't now (Windows 10)

### ISSUE THREAD

**Issue by OndrikB** [NationalSecurityAgency/ghidra#4982]
**Describe the bug**
```
java.lang.ExceptionInInitializerError
	at org.apache.felix.framework.URLHandlers.createURLStreamHandler(URLHandlers.java:513)
	at java.base/java.net.URL.getURLStreamHandler(URL.java:1446)
	at java.base/java.net.URL.<init>(URL.java:681)
	at java.base/java.net.URL.<init>(URL.java:570)
	at java.base/java.net.URL.<init>(URL.java:517)
	at ghidra.framework.protocol.ghidra.GhidraURL.makeURL(GhidraURL.java:281)
	at ghidra.framework.model.ProjectLocator.<init>(ProjectLocator.java:51)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.getDomainFile(ProgramManagerPlugin.java:852)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.loadPrograms(ProgramManagerPlugin.java:807)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.readDataState(ProgramManagerPlugin.java:742)
	at ghidra.framework.plugintool.PluginManager.restoreDataStateFromXml(PluginManager.java:341)
	at ghidra.framework.plugintool.PluginTool.restoreDataStateFromXml(PluginTool.java:564)
	at ghidra.framework.project.tool.WorkspaceImpl.restoreFromXml(WorkspaceImpl.java:188)
	at ghidra.framework.project.tool.ToolManagerImpl.restoreFromXml(ToolManagerImpl.java:324)
	at ghidra.framework.project.DefaultProject.restore(DefaultProject.java:473)
	at ghidra.framework.project.DefaultProjectManager.openProject(DefaultProjectManager.java:142)
	at ghidra.framework.main.FileActionManager.doOpenProject(FileActionManager.java:303)
	at ghidra.framework.main.FileActionManager.openProject(FileActionManager.java:248)
	at ghidra.framework.main.FileActionManager$2.actionPerformed(FileActionManager.java:99)
	at docking.DockingActionProxy.actionPerformed(DockingActionProxy.java:47)
	at docking.MenuBarMenuHandler.lambda$processMenuAction$0(MenuBarMenuHandler.java:64)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.RuntimeException: Unable to make protected boolean java.net.URLStreamHandler.equals(java.net.URL,java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @709f9518
	at org.apache.felix.framework.URLHandlersStreamHandlerProxy.<clinit>(URLHandlersStreamHandlerProxy.java:104)
	... 34 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected boolean java.net.URLStreamHandler.equals(java.net.URL,java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @709f9518
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:201)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:195)
	at org.apache.felix.framework.util.SecureAction.setAccesssible(SecureAction.java:871)
	at org.apache.felix.framework.URLHandlersStreamHandlerProxy.<clinit>(URLHandlersStreamHandlerProxy.java:79)
	... 34 more

---------------------------------------------------
Build Date: 2023-Feb-08 1242 EST
Ghidra Version: 10.2.3
Java Home: D:\Programy\jdk-19
JVM Version: Oracle Corporation 19
OS: Windows 10 10.0 amd64
Workstation: DESKTOP-EU1B0SF
```

**To Reproduce**

1. Try to open or reopen project that used to work

**Expected behavior**
Project opens without issue. 

**Screenshots**

![obrázok](https://user-images.githubusercontent.com/38321117/219003069-e8fcb894-3de2-4794-ab0b-073d4d6a9249.png)

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Microsoft Windows 10 Version 22H2 (OS Build 19045.2486)
 - Java Version: 
```
java 19 2022-09-20
Java(TM) SE Runtime Environment (build 19+36-2238)
Java HotSpot(TM) 64-Bit Server VM (build 19+36-2238, mixed mode, sharing)
```
 - Ghidra Version: 10.2.3
 - Ghidra Origin: Official Github Releases

**Additional context**
I attempted to enable dark mode when the issue occurred. Before, the project worked perfectly.

**Comment by OndrikB** [comment]
Deleting the `projectState` file fixed the issue and allowed the project to open.
