### ISSUE TITLE
AVR: java.lang.IllegalArgumentException: Address are in different spaces code != codebyte

### ISSUE THREAD

**Issue by ghost** [NationalSecurityAgency/ghidra#5051]
While executing a program search (irrelevant but: `PORTn_OUT` constructs), the following error comes up:

```
Address are in different spaces code != codebyte
java.lang.IllegalArgumentException: Address are in different spaces code != codebyte
	at ghidra.program.model.address.AbstractAddressSpace.subtract(AbstractAddressSpace.java:292)
	at ghidra.program.model.address.GenericAddressSpace.subtract(GenericAddressSpace.java:21)
	at ghidra.program.model.address.GenericAddress.subtract(GenericAddress.java:144)
	at ghidra.program.database.function.FunctionManagerDB.getReferencedVariable(FunctionManagerDB.java:1273)
	at ghidra.program.model.listing.CodeUnitFormat.performRegisterMarkup(CodeUnitFormat.java:328)
	at ghidra.program.model.listing.CodeUnitFormat.getOperandRepresentationList(CodeUnitFormat.java:256)
	at ghidra.program.model.listing.CodeUnitFormat.getOperandRepresentationString(CodeUnitFormat.java:179)
	at ghidra.app.plugin.core.searchtext.databasesearcher.InstructionMnemonicOperandFieldSearcher.getOperandStrings(InstructionMnemonicOperandFieldSearcher.java:166)
	at ghidra.app.plugin.core.searchtext.databasesearcher.InstructionMnemonicOperandFieldSearcher.findMatchesForCurrentAddress(InstructionMnemonicOperandFieldSearcher.java:90)
	at ghidra.app.plugin.core.searchtext.databasesearcher.InstructionMnemonicOperandFieldSearcher.advance(InstructionMnemonicOperandFieldSearcher.java:82)
	at ghidra.app.plugin.core.searchtext.databasesearcher.ProgramDatabaseFieldSearcher.doAdvance(ProgramDatabaseFieldSearcher.java:52)
	at ghidra.app.plugin.core.searchtext.databasesearcher.ProgramDatabaseFieldSearcher.getNextSignificantAddress(ProgramDatabaseFieldSearcher.java:69)
	at ghidra.app.plugin.core.searchtext.databasesearcher.ProgramDatabaseSearcher.findNextSignificantAddress(ProgramDatabaseSearcher.java:139)
	at ghidra.app.plugin.core.searchtext.databasesearcher.ProgramDatabaseSearcher.search(ProgramDatabaseSearcher.java:101)
	at ghidra.app.plugin.core.searchtext.AbstractSearchTableModel.doLoad(AbstractSearchTableModel.java:65)
	at docking.widgets.table.threaded.IncrementalLoadJob.doExecute(IncrementalLoadJob.java:82)
	at docking.widgets.table.threaded.IncrementalLoadJob.run(IncrementalLoadJob.java:61)
	at ghidra.util.worker.AbstractWorker$JobCallback.process(AbstractWorker.java:133)
	at ghidra.util.worker.AbstractWorker$JobCallback.process(AbstractWorker.java:123)
	at generic.concurrent.ConcurrentQ$CallbackCallable.call(ConcurrentQ.java:658)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

---------------------------------------------------
Build Date: 2023-Feb-08 1242 EST
Ghidra Version: 10.2.3
Java Home: xxx
JVM Version: xxx
OS: xxx
```

**Comment by ghidra1** [comment]
Functions should not be defined in the `codebyte` space.  I believe all code and functions should be defined in the `code` space only.

**Comment by ghidra1** [comment]
Are you able to share you code (*.gzf) so we can better understand your situation which has caused the use of `code` and `codebyte` space to become entangled for the function which triggered this exception?

**Comment by emteere** [comment]
Would be great to have an example to show what you are running into.

Also sounds like you are trying to automate the boot up code that would copy different parts of data memory into ram.

Are you also trying to handle overlays, where different code is loaded at the same memory at any given time?
That might be complicated with the code/codebyte spaces.  I've never tried to set that up.

The current code/codebyte is sub-optimal.  It was done in order to do correct calculations and interpretation of constants. We've been discussing better ways of getting all references to go to the same location, but keep byte addresses and word addresses separate.

**Comment by ghidra1** [comment]
This is related to #2577.
