### ISSUE TITLE
StackoverflowError Exception when closing the "New Script Type" dialog

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#5065]
**Describe the bug**
Closing the "New Script: Type" dialog box causes an uncaught exception.

**To Reproduce**
1. Open CodeBrowser
2. Open "Script Manager"
3. Click "Create New Script" icon
4. On the "Please select a script type" dialog box, click "Cancel"
5. See error

**Attachments**
<img width="565" alt="exception closing dialog box" src="https://user-images.githubusercontent.com/16713498/222965825-f26588dc-6810-44f3-b7aa-0eff4c463358.png">

**Environment (please complete the following information):**
 - OS: Windows 11 x64
 - Java Version: Microsoft OpenJDK 17.0.6
 - Ghidra Version: 10.3 master branch 865cd22cab03ad4cc5e075aa7e262d9c5e8cc65d
 - Ghidra Origin: locally built 

**Additional context**
```
java.lang.StackOverflowError
	at docking.DialogComponentProvider.closeDialog(DialogComponentProvider.java:889)
	at docking.DialogComponentProvider.close(DialogComponentProvider.java:884)
	at ghidra.app.plugin.core.script.PickProviderDialog.dispose(PickProviderDialog.java:111)
	at docking.DialogComponentProvider.close(DialogComponentProvider.java:885)
	at ghidra.app.plugin.core.script.PickProviderDialog.dispose(PickProviderDialog.java:111)
	at docking.DialogComponentProvider.close(DialogComponentProvider.java:885)
	at ghidra.app.plugin.core.script.PickProviderDialog.dispose(PickProviderDialog.java:111)
	at docking.DialogComponentProvider.close(DialogComponentProvider.java:885)
	at ghidra.app.plugin.core.script.PickProviderDialog.dispose(PickProviderDialog.java:111)
	at docking.DialogComponentProvider.close(DialogComponentProvider.java:885)
... (repeated lines removed)
        at ghidra.app.plugin.core.script.PickProviderDialog.dispose(PickProviderDialog.java:111)
	at docking.DialogComponentProvider.close(DialogComponentProvider.java:885)
	at ghidra.app.plugin.core.script.PickProviderDialog.dispose(PickProviderDialog.java:111)
	at docking.DialogComponentProvider.close(DialogComponentProvider.java:885)
	at ghidra.app.plugin.core.script.PickProviderDialog.dispose(PickProviderDialog.java:111)
	at docking.DialogComponentProvider.close(DialogComponentProvider.java:885)

---------------------------------------------------
Build Date: 2023-Mar-02 1240 UTC
Ghidra Version: 10.3
Java Home: C:\Program Files\Microsoft\jdk-17.0.6.10-hotspot
JVM Version: Microsoft 17.0.6
OS: Windows 11 10.0 amd64
```

**Comment by mumbel** [comment]
confirmed on a9baf9f6d873fcde40b0692af6fb3afbaf5e91c0  (20.04  17.0.6)
