### ISSUE TITLE
UI freezes when the program is left open for a long time

### ISSUE THREAD

**Issue by cyrozap** [NationalSecurityAgency/ghidra#5085]
**Describe the bug**
Sometimes, when I leave Ghidra open for more than a few hours, the UI will start freezing up. This usually happens when I leave Ghidra open while my computer idles (but doesn't sleep) overnight, but it can also start happening while I'm actively interacting with the program. And once the freezing starts, the only way to fix it is to close the program and wait several hours. Simply closing and immediately reopening the program doesn't fix the issue, and even rebooting doesn't seem to fix it, either.

The issue is weirdly inconsistent. Sometimes, I'll leave Ghidra open for days, and nothing freezes. Other times, I'll leave it open for a just few hours while doing other things on the computer and Ghidra start freezing. It also seems to be independent of memory use--my system has 32 GB of RAM, and the freezing will happen even when RAM usage on the system is low, and Ghidra usually doesn't take much more than a couple gigabytes anyways. I've even closed the program entirely, run `swapoff -a && swapon -a`, and then reopened it, and that didn't fix the issue. The only reliable way to fix the freezing is to close Ghidra and just forget about it for a day or two before reopening it.

**To Reproduce**
1. Open a project.
2. Open a file in CodeBrowser.
3. Wait a day (though it may happen in just a few hours).
4. Click around the UI.
   - Moving the location of the code cursor always immediately results in a freeze.
   - Switching from the decompilation tab to the code listing tab ( I have these views overlayed so I can switch between their tabs) often results in a freeze.
   - Scrolling using the mouse to change the position of the scroll bar in either the listing view or the decompilation view only sometimes results in a freeze.
5. UI freezes for exactly 10 seconds.

**Expected behavior**
Ghidra should be able to be left open indefinitely without the risk of it freezing.

**Environment**
 - OS: Arch Linux, kernel 6.2.1-arch1-1
 - Java Version: 17.0.6
 - Ghidra Version: 10.2.3
 - Ghidra Origin: [Arch Linux repos](https://archlinux.org/packages/community/x86_64/ghidra/)

**Comment by cyrozap** [comment]
I corrected the bug report experiencing the bug again. The freeze only happens for exactly 10 seconds, not 20 as I originally thought, and Ghidra's logs contain no mention of the freeze happening. Also, Ghidra was only using about 1.5 GB of memory at the time of the freeze, and my system reported using zero swap and that it had 19 GB of memory available.

**Comment by dragonmacher** [comment]
When this happens, please run the commands below to capture the state of the running tool.  
```
jps
jstack <pid>
```

The first command returns all Java process ids so you can find the Ghidra process id.  The second command will dump the thread state of all threads.   This should tell us if something is blocking the UI thread.

**Comment by ryanmkurtz** [comment]
It may be worth trying our official release [(download link)](https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.2.3_build/ghidra_10.2.3_PUBLIC_20230208.zip) rather than the one from the Arch repo.

**Comment by homes410** [comment]
Your UI-hang experience during use of Ghidra isn't new. 
A quick fix is available by limiting maximum value contained in "Options->Tool->Max Navigation History Size" to 1.

And below comment are presented here only for someone really interested in.
-----------------------------------------
In a context as it was given above, When you navigate to back and forth, DecompilerLocation keeps reference to DecompileData and GoToServicePlugin.getMemento() call wraps any location object into Memento, and those stale DecompileData became still reachable from GC after a refresh of decompile tab.

Workaround for mine was replacing those call to LocationMemento.getLocationMemento(saveState, programs);
I refer to below attachment about the workaround.

[230323.zip](https://github.com/NationalSecurityAgency/ghidra/files/11049453/230323.zip)

**Comment by cyrozap** [comment]
The problem happened again today, and this time I managed to get some stack traces showing a clear difference between the frozen and idle behavior.

After clicking around in the decompilation view, I experienced the freeze and collected this stack trace: [jstack-ghidra-frozen-decompilation-view.log](https://github.com/NationalSecurityAgency/ghidra/files/11070368/jstack-ghidra-frozen-decompilation-view.log)

Then once the freeze stopped and the program was idle, I collected this stack trace: [jstack-ghidra-idle-decompilation-view.log](https://github.com/NationalSecurityAgency/ghidra/files/11070369/jstack-ghidra-idle-decompilation-view.log)

Taking a diff between the idle and frozen stack traces, I found this:

```diff
-"AWT-EventQueue-0" #31 prio=6 os_prio=0 cpu=2051809.23ms elapsed=643011.19s tid=0x00007f36ec710ef0 nid=0x44b43 waiting on condition  [0x00007f37344fa000]
-   java.lang.Thread.State: WAITING (parking)
+"AWT-EventQueue-0" #31 prio=6 os_prio=0 cpu=2051744.48ms elapsed=642989.07s tid=0x00007f36ec710ef0 nid=0x44b43 waiting on condition  [0x00007f37344f9000]
+   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.6/Native Method)
-       - parking to wait for  <0x00000005dd8054c0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
-       at java.util.concurrent.locks.LockSupport.park(java.base@17.0.6/LockSupport.java:341)
-       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@17.0.6/AbstractQueuedSynchronizer.java:506)
-       at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.6/ForkJoinPool.java:3463)
-       at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.6/ForkJoinPool.java:3434)
-       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@17.0.6/AbstractQueuedSynchronizer.java:1623)
-       at java.awt.EventQueue.getNextEvent(java.desktop@17.0.6/EventQueue.java:567)
-       at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@17.0.6/EventDispatchThread.java:190)
+       - parking to wait for  <0x00000005ddf1bbc8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
+       at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.6/LockSupport.java:252)
+       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@17.0.6/AbstractQueuedSynchronizer.java:1757)
+       at sun.awt.SunToolkit.awtLockWait(java.desktop@17.0.6/SunToolkit.java:259)
+       at sun.awt.X11.XSelection.waitForSelectionNotify(java.desktop@17.0.6/XSelection.java:180)
+       at sun.awt.X11.XSelection.getTargets(java.desktop@17.0.6/XSelection.java:220)
+       - locked <0x00000005dd7b9f78> (a java.lang.Object)
+       at sun.awt.X11.XClipboard.getClipboardFormats(java.desktop@17.0.6/XClipboard.java:118)
+       at sun.awt.datatransfer.SunClipboard.getClipboardFormatsOpenClose(java.desktop@17.0.6/SunClipboard.java:323)
+       at sun.awt.datatransfer.SunClipboard.getAvailableDataFlavors(java.desktop@17.0.6/SunClipboard.java:163)
+       at ghidra.app.plugin.core.clipboard.ClipboardPlugin.getAvailableDataFlavors(ClipboardPlugin.java:335)
+       at ghidra.app.plugin.core.clipboard.ClipboardPlugin$PasteAction.isEnabledForContext(ClipboardPlugin.java:415)
+       at docking.ComponentPlaceholder.contextChanged(ComponentPlaceholder.java:538)
+       at docking.DockingWindowManager.contextChanged(DockingWindowManager.java:2292)
+       at docking.AbstractDockingTool.contextChanged(AbstractDockingTool.java:212)
+       at ghidra.framework.plugintool.PluginTool.contextChanged(PluginTool.java:1483)
+       at docking.ComponentProvider.contextChanged(ComponentProvider.java:450)
+       at ghidra.app.plugin.core.codebrowser.CodeViewerProvider.programLocationChanged(CodeViewerProvider.java:525)
+       at ghidra.app.util.viewer.listingpanel.ListingPanel.fieldLocationChanged(ListingPanel.java:799)
+       at docking.widgets.fieldpanel.FieldPanel$CursorHandler.notifyCursorChanged(FieldPanel.java:2169)
+       at docking.widgets.fieldpanel.FieldPanel$CursorHandler.doSetCursorPosition(FieldPanel.java:2003)
+       at docking.widgets.fieldpanel.FieldPanel.goTo(FieldPanel.java:828)
+       at docking.widgets.fieldpanel.FieldPanel.goTo(FieldPanel.java:821)
+       at ghidra.app.util.viewer.listingpanel.ListingPanel.goTo(ListingPanel.java:587)
+       at ghidra.app.plugin.core.codebrowser.CodeViewerProvider.setLocation(CodeViewerProvider.java:695)
+       at ghidra.app.plugin.core.codebrowser.CodeBrowserPlugin.processEvent(CodeBrowserPlugin.java:130)
+       at ghidra.framework.plugintool.Plugin.eventSent(Plugin.java:292)
+       at ghidra.framework.plugintool.mgr.EventManager.sendEvents(EventManager.java:286)
+       at ghidra.framework.plugintool.mgr.EventManager.lambda$new$3(EventManager.java:49)
+       at ghidra.framework.plugintool.mgr.EventManager$$Lambda$321/0x00000007c06bacd8.run(Unknown Source)
+       at ghidra.util.Swing.doRun(Swing.java:292)
+       at ghidra.util.Swing.runNow(Swing.java:208)
+       at ghidra.util.Swing.runNow(Swing.java:163)
+       at ghidra.framework.plugintool.mgr.EventManager.fireEvent(EventManager.java:216)
+       at ghidra.framework.plugintool.PluginTool.firePluginEvent(PluginTool.java:502)
+       at ghidra.framework.plugintool.Plugin.firePluginEvent(Plugin.java:444)
+       at ghidra.app.plugin.core.decompile.DecompilePlugin.locationChanged(DecompilePlugin.java:207)
+       at ghidra.app.plugin.core.decompile.DecompilerProvider.locationChanged(DecompilerProvider.java:536)
+       at ghidra.app.decompiler.component.DecompilerController.locationChanged(DecompilerController.java:265)
+       at ghidra.app.decompiler.component.DecompilerPanel.fieldLocationChanged(DecompilerPanel.java:897)
+       at docking.widgets.fieldpanel.FieldPanel$CursorHandler.notifyCursorChanged(FieldPanel.java:2169)
+       at docking.widgets.fieldpanel.FieldPanel$CursorHandler.setCursorPos(FieldPanel.java:1964)
+       at docking.widgets.fieldpanel.FieldPanel$FieldPanelMouseAdapter.mousePressed(FieldPanel.java:1358)
+       at java.awt.AWTEventMulticaster.mousePressed(java.desktop@17.0.6/AWTEventMulticaster.java:287)
+       at java.awt.Component.processMouseEvent(java.desktop@17.0.6/Component.java:6623)
+       at javax.swing.JComponent.processMouseEvent(java.desktop@17.0.6/JComponent.java:3389)
+       at java.awt.Component.processEvent(java.desktop@17.0.6/Component.java:6391)
+       at java.awt.Container.processEvent(java.desktop@17.0.6/Container.java:2266)
+       at java.awt.Component.dispatchEventImpl(java.desktop@17.0.6/Component.java:5001)
+       at java.awt.Container.dispatchEventImpl(java.desktop@17.0.6/Container.java:2324)
+       at java.awt.Component.dispatchEvent(java.desktop@17.0.6/Component.java:4833)
+       at java.awt.LightweightDispatcher.retargetMouseEvent(java.desktop@17.0.6/Container.java:4948)
+       at java.awt.LightweightDispatcher.processMouseEvent(java.desktop@17.0.6/Container.java:4572)
+       at java.awt.LightweightDispatcher.dispatchEvent(java.desktop@17.0.6/Container.java:4516)
+       at java.awt.Container.dispatchEventImpl(java.desktop@17.0.6/Container.java:2310)
+       at java.awt.Window.dispatchEventImpl(java.desktop@17.0.6/Window.java:2780)
+       at java.awt.Component.dispatchEvent(java.desktop@17.0.6/Component.java:4833)
+       at java.awt.EventQueue.dispatchEventImpl(java.desktop@17.0.6/EventQueue.java:773)
+       at java.awt.EventQueue$4.run(java.desktop@17.0.6/EventQueue.java:722)
+       at java.awt.EventQueue$4.run(java.desktop@17.0.6/EventQueue.java:716)
+       at java.security.AccessController.executePrivileged(java.base@17.0.6/AccessController.java:776)
+       at java.security.AccessController.doPrivileged(java.base@17.0.6/AccessController.java:399)
+       at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@17.0.6/ProtectionDomain.java:86)
+       at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@17.0.6/ProtectionDomain.java:97)
+       at java.awt.EventQueue$5.run(java.desktop@17.0.6/EventQueue.java:746)
+       at java.awt.EventQueue$5.run(java.desktop@17.0.6/EventQueue.java:744)
+       at java.security.AccessController.executePrivileged(java.base@17.0.6/AccessController.java:776)
+       at java.security.AccessController.doPrivileged(java.base@17.0.6/AccessController.java:399)
+       at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@17.0.6/ProtectionDomain.java:86)
+       at java.awt.EventQueue.dispatchEvent(java.desktop@17.0.6/EventQueue.java:743)
+       at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@17.0.6/EventDispatchThread.java:203)
        at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@17.0.6/EventDispatchThread.java:124)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@17.0.6/EventDispatchThread.java:113)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@17.0.6/EventDispatchThread.java:109)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@17.0.6/EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.run(java.desktop@17.0.6/EventDispatchThread.java:90)
 
```

For easier reading, this is the excerpt from the idle trace:

```
"AWT-EventQueue-0" #31 prio=6 os_prio=0 cpu=2051809.23ms elapsed=643011.19s tid=0x00007f36ec710ef0 nid=0x44b43 waiting on condition  [0x00007f37344fa000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.6/Native Method)
        - parking to wait for  <0x00000005dd8054c0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(java.base@17.0.6/LockSupport.java:341)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@17.0.6/AbstractQueuedSynchronizer.java:506)
        at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.6/ForkJoinPool.java:3463)
        at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.6/ForkJoinPool.java:3434)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@17.0.6/AbstractQueuedSynchronizer.java:1623)
        at java.awt.EventQueue.getNextEvent(java.desktop@17.0.6/EventQueue.java:567)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@17.0.6/EventDispatchThread.java:190)
        at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@17.0.6/EventDispatchThread.java:124)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@17.0.6/EventDispatchThread.java:113)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@17.0.6/EventDispatchThread.java:109)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@17.0.6/EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.run(java.desktop@17.0.6/EventDispatchThread.java:90)

```

And this is the corresponding excerpt from the frozen trace:

```
"AWT-EventQueue-0" #31 prio=6 os_prio=0 cpu=2051744.48ms elapsed=642989.07s tid=0x00007f36ec710ef0 nid=0x44b43 waiting on condition  [0x00007f37344f9000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.6/Native Method)
        - parking to wait for  <0x00000005ddf1bbc8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.6/LockSupport.java:252)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@17.0.6/AbstractQueuedSynchronizer.java:1757)
        at sun.awt.SunToolkit.awtLockWait(java.desktop@17.0.6/SunToolkit.java:259)
        at sun.awt.X11.XSelection.waitForSelectionNotify(java.desktop@17.0.6/XSelection.java:180)
        at sun.awt.X11.XSelection.getTargets(java.desktop@17.0.6/XSelection.java:220)
        - locked <0x00000005dd7b9f78> (a java.lang.Object)
        at sun.awt.X11.XClipboard.getClipboardFormats(java.desktop@17.0.6/XClipboard.java:118)
        at sun.awt.datatransfer.SunClipboard.getClipboardFormatsOpenClose(java.desktop@17.0.6/SunClipboard.java:323)
        at sun.awt.datatransfer.SunClipboard.getAvailableDataFlavors(java.desktop@17.0.6/SunClipboard.java:163)
        at ghidra.app.plugin.core.clipboard.ClipboardPlugin.getAvailableDataFlavors(ClipboardPlugin.java:335)
        at ghidra.app.plugin.core.clipboard.ClipboardPlugin$PasteAction.isEnabledForContext(ClipboardPlugin.java:415)
        at docking.ComponentPlaceholder.contextChanged(ComponentPlaceholder.java:538)
        at docking.DockingWindowManager.contextChanged(DockingWindowManager.java:2292)
        at docking.AbstractDockingTool.contextChanged(AbstractDockingTool.java:212)
        at ghidra.framework.plugintool.PluginTool.contextChanged(PluginTool.java:1483)
        at docking.ComponentProvider.contextChanged(ComponentProvider.java:450)
        at ghidra.app.plugin.core.codebrowser.CodeViewerProvider.programLocationChanged(CodeViewerProvider.java:525)
        at ghidra.app.util.viewer.listingpanel.ListingPanel.fieldLocationChanged(ListingPanel.java:799)
        at docking.widgets.fieldpanel.FieldPanel$CursorHandler.notifyCursorChanged(FieldPanel.java:2169)
        at docking.widgets.fieldpanel.FieldPanel$CursorHandler.doSetCursorPosition(FieldPanel.java:2003)
        at docking.widgets.fieldpanel.FieldPanel.goTo(FieldPanel.java:828)
        at docking.widgets.fieldpanel.FieldPanel.goTo(FieldPanel.java:821)
        at ghidra.app.util.viewer.listingpanel.ListingPanel.goTo(ListingPanel.java:587)
        at ghidra.app.plugin.core.codebrowser.CodeViewerProvider.setLocation(CodeViewerProvider.java:695)
        at ghidra.app.plugin.core.codebrowser.CodeBrowserPlugin.processEvent(CodeBrowserPlugin.java:130)
        at ghidra.framework.plugintool.Plugin.eventSent(Plugin.java:292)
        at ghidra.framework.plugintool.mgr.EventManager.sendEvents(EventManager.java:286)
        at ghidra.framework.plugintool.mgr.EventManager.lambda$new$3(EventManager.java:49)
        at ghidra.framework.plugintool.mgr.EventManager$$Lambda$321/0x00000007c06bacd8.run(Unknown Source)
        at ghidra.util.Swing.doRun(Swing.java:292)
        at ghidra.util.Swing.runNow(Swing.java:208)
        at ghidra.util.Swing.runNow(Swing.java:163)
        at ghidra.framework.plugintool.mgr.EventManager.fireEvent(EventManager.java:216)
        at ghidra.framework.plugintool.PluginTool.firePluginEvent(PluginTool.java:502)
        at ghidra.framework.plugintool.Plugin.firePluginEvent(Plugin.java:444)
        at ghidra.app.plugin.core.decompile.DecompilePlugin.locationChanged(DecompilePlugin.java:207)
        at ghidra.app.plugin.core.decompile.DecompilerProvider.locationChanged(DecompilerProvider.java:536)
        at ghidra.app.decompiler.component.DecompilerController.locationChanged(DecompilerController.java:265)
        at ghidra.app.decompiler.component.DecompilerPanel.fieldLocationChanged(DecompilerPanel.java:897)
        at docking.widgets.fieldpanel.FieldPanel$CursorHandler.notifyCursorChanged(FieldPanel.java:2169)
        at docking.widgets.fieldpanel.FieldPanel$CursorHandler.setCursorPos(FieldPanel.java:1964)
        at docking.widgets.fieldpanel.FieldPanel$FieldPanelMouseAdapter.mousePressed(FieldPanel.java:1358)
        at java.awt.AWTEventMulticaster.mousePressed(java.desktop@17.0.6/AWTEventMulticaster.java:287)
        at java.awt.Component.processMouseEvent(java.desktop@17.0.6/Component.java:6623)
        at javax.swing.JComponent.processMouseEvent(java.desktop@17.0.6/JComponent.java:3389)
        at java.awt.Component.processEvent(java.desktop@17.0.6/Component.java:6391)
        at java.awt.Container.processEvent(java.desktop@17.0.6/Container.java:2266)
        at java.awt.Component.dispatchEventImpl(java.desktop@17.0.6/Component.java:5001)
        at java.awt.Container.dispatchEventImpl(java.desktop@17.0.6/Container.java:2324)
        at java.awt.Component.dispatchEvent(java.desktop@17.0.6/Component.java:4833)
        at java.awt.LightweightDispatcher.retargetMouseEvent(java.desktop@17.0.6/Container.java:4948)
        at java.awt.LightweightDispatcher.processMouseEvent(java.desktop@17.0.6/Container.java:4572)
        at java.awt.LightweightDispatcher.dispatchEvent(java.desktop@17.0.6/Container.java:4516)
        at java.awt.Container.dispatchEventImpl(java.desktop@17.0.6/Container.java:2310)
        at java.awt.Window.dispatchEventImpl(java.desktop@17.0.6/Window.java:2780)
        at java.awt.Component.dispatchEvent(java.desktop@17.0.6/Component.java:4833)
        at java.awt.EventQueue.dispatchEventImpl(java.desktop@17.0.6/EventQueue.java:773)
        at java.awt.EventQueue$4.run(java.desktop@17.0.6/EventQueue.java:722)
        at java.awt.EventQueue$4.run(java.desktop@17.0.6/EventQueue.java:716)
        at java.security.AccessController.executePrivileged(java.base@17.0.6/AccessController.java:776)
        at java.security.AccessController.doPrivileged(java.base@17.0.6/AccessController.java:399)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@17.0.6/ProtectionDomain.java:86)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@17.0.6/ProtectionDomain.java:97)
        at java.awt.EventQueue$5.run(java.desktop@17.0.6/EventQueue.java:746)
        at java.awt.EventQueue$5.run(java.desktop@17.0.6/EventQueue.java:744)
        at java.security.AccessController.executePrivileged(java.base@17.0.6/AccessController.java:776)
        at java.security.AccessController.doPrivileged(java.base@17.0.6/AccessController.java:399)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@17.0.6/ProtectionDomain.java:86)
        at java.awt.EventQueue.dispatchEvent(java.desktop@17.0.6/EventQueue.java:743)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@17.0.6/EventDispatchThread.java:203)
        at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@17.0.6/EventDispatchThread.java:124)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@17.0.6/EventDispatchThread.java:113)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@17.0.6/EventDispatchThread.java:109)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@17.0.6/EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.run(java.desktop@17.0.6/EventDispatchThread.java:90)

```

Hopefully this isn't just another trace of Ghidra doing nothing, haha.

**Comment by dragonmacher** [comment]
This is helpful.   As @dev747368 recently reminded me, some linux distros can show this issue.   The application is interacting with the native clipboard when this is happening.  In the past, the issue is related to the contents on the clipboard that were placed there in an application that is not Ghidra.   When this happens, the fix should be as simple as making a simple copy from a basic text editor.    This will update the clipboard with simple and small data, which should prevent the OS and Java interaction from showing this behavior.

**Comment by dragonmacher** [comment]
This is helpful.   As @dev747368 recently reminded me, some linux distros can show this issue.   The application is interacting with the native clipboard when this is happening.  In the past, the issue is related to the contents on the clipboard that were placed there in an application that is not Ghidra.   When this happens, the fix should be as simple as making a simple copy from a basic text editor.    This will update the clipboard with simple and small data, which should prevent the OS and Java interaction from showing this behavior.

**Comment by dragonmacher** [comment]
This is helpful.   As @dev747368 recently reminded me, some linux distros can show this issue.   The application is interacting with the native clipboard when this is happening.  In the past, the issue is related to the contents on the clipboard that were placed there in an application that is not Ghidra.   When this happens, the fix should be as simple as making a simple copy from a basic text editor.    This will update the clipboard with simple and small data, which should prevent the OS and Java interaction from showing this behavior.

**Comment by cyrozap** [comment]
I think the clipboard is exactly the issue. The application just froze on me again, and when I ran `wl-paste` (from [bugaevc/wl-clipboard](https://github.com/bugaevc/wl-clipboard)), I saw that my clipboard was empty. Copying literally any text immediately caused Ghidra to stop freezing. What's odd is, after I confirmed that the clipboard was the issue I tried to trigger the freeze again by running `wl-copy --clear` to clear the clipboard, but I didn't experience the freezing again.

Maybe this issue has something to do with the fact that I'm running a Wayland compositor (KDE's Plasma/Kwin), which is using XWayland to display Ghidra, a Java application, and there's some weird interaction happening between the three? As far as I can tell, when the clipboard is empty, running `wl-paste --list-types` (which I assume is similar to what `ghidra.app.plugin.core.clipboard.ClipboardPlugin.getAvailableDataFlavors()` is doing) just hangs waiting for data. Maybe the fix is to make sure that `getAvailableDataFlavors()` won't block the UI?

**Comment by dragonmacher** [comment]
> Maybe the fix is to make sure that getAvailableDataFlavors() won't block the UI?

To do so would require us to create multi-threaded clipboard API that would allow us to check for timeouts and not block the UI.   That is a complex solution for working around a Java issue.  Considering the number of clients affected by this particular issue, the additional complexity does not seem worth it at this time.

**Comment by dev747368** [comment]
@cyrozap re: speculation on root causes... I originally traced this down 7+ years ago on a plain jane xwindows system, a couple of java lines in a standalone main() to call the clipboard methods, and could duplicate it with Xvfb (headless xwindows frame buffer).

**Comment by PatchByte** [comment]
So this is now happening for me constantly and I don't really know what to do, it is always really annoying to type `wl-paste --clear`. Anyone knows a fix?
