### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by dzik87** [NationalSecurityAgency/ghidra#51]
**Describe the bug**
While closing ghidra with X on right top corner unhadled exception occured.

**To Reproduce**
1. Go to Open any project
2. Click on X
3. See error

**Expected behavior**
Exception should be added in handler

**Screenshots**
https://i.imgur.com/mzkECcv.png

**Environment (please complete the following information):**
 - OS: Windws 10
 - Browser Chrome
 - Version 72.0.3626.119

**Additional context**
Log:
Uncaught Exception! 
RuntimeException - java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
	at ghidra.framework.plugintool.Plugin.cleanup(Plugin.java:307)
	at ghidra.framework.plugintool.PluginManager.dispose(PluginManager.java:58)
	at ghidra.framework.plugintool.PluginTool.dispose(PluginTool.java:595)
	at ghidra.framework.plugintool.PluginTool.exit(PluginTool.java:576)
	at ghidra.framework.project.tool.GhidraTool.exit(GhidraTool.java:174)
	at ghidra.framework.plugintool.PluginTool.doClose(PluginTool.java:1299)
	at ghidra.framework.plugintool.PluginTool.close(PluginTool.java:1280)
	at docking.DockingWindowManager.close(DockingWindowManager.java:1096)
	at docking.RootNode$JFrameWindowWrapper$1.windowClosing(RootNode.java:723)
	at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
	at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
	at java.desktop/java.awt.Window.processWindowEvent(Window.java:2078)
	at java.desktop/javax.swing.JFrame.processWindowEvent(JFrame.java:298)
	at java.desktop/java.awt.Window.processEvent(Window.java:2037)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException
	at ghidra.app.plugin.core.string.translate.ManualStringTranslationService.setTranslatedValue(ManualStringTranslationService.java:103)
	at ghidra.app.plugin.core.strings.ViewStringsTableModel.setValueAt(ViewStringsTableModel.java:81)
	at java.desktop/javax.swing.JTable.setValueAt(JTable.java:2730)
	at java.desktop/javax.swing.JTable.editingStopped(JTable.java:4728)
	at java.desktop/javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:147)
	at java.desktop/javax.swing.DefaultCellEditor$EditorDelegate.stopCellEditing(DefaultCellEditor.java:370)
	at java.desktop/javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:234)
	at java.desktop/javax.swing.JTable.columnMarginChanged(JTable.java:4597)
	at docking.widgets.table.GTableColumnModel.fireColumnMarginChanged(GTableColumnModel.java:564)
	at docking.widgets.table.GTableColumnModel.propertyChange(GTableColumnModel.java:528)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(SwingPropertyChangeSupport.java:92)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/javax.swing.table.TableColumn.firePropertyChange(TableColumn.java:290)
	at java.desktop/javax.swing.table.TableColumn.firePropertyChange(TableColumn.java:296)
	at java.desktop/javax.swing.table.TableColumn.setWidth(TableColumn.java:519)
	at java.desktop/javax.swing.JTable$2.setSizeAt(JTable.java:3223)
	at java.desktop/javax.swing.JTable$4.setSizeAt(JTable.java:3304)
	at java.desktop/javax.swing.JTable.adjustSizes(JTable.java:3349)
	at java.desktop/javax.swing.JTable.adjustSizes(JTable.java:3317)
	at java.desktop/javax.swing.JTable.setWidthsFromPreferredWidths(JTable.java:3231)
	at java.desktop/javax.swing.JTable.doLayout(JTable.java:3117)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at docking.RootNode$JFrameWindowWrapper.validate(RootNode.java:780)
	at docking.RootNode.removeStatusItem(RootNode.java:548)
	at docking.DockingWindowManager.removeStatusItem(DockingWindowManager.java:1910)
	at ghidra.framework.plugintool.PluginTool.removeStatusComponent(PluginTool.java:1038)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.dispose(MultiProgramManager.java:111)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.dispose(ProgramManagerPlugin.java:354)
	at ghidra.framework.plugintool.Plugin.cleanup(Plugin.java:295)
	... 34 more

---------------------------------------------------
Build Date: 2019-Feb-28 1236 EST
Ghidra Version: 9.0
Java Home: C:\ghidra_9.0\jdk-11.0.2
JVM Version: Oracle Corporation 11.0.2
OS: Windows 10 10.0 amd64
Workstation: dzik

**Comment by ryanmkurtz** [comment]
This will be fixed in our next release.
