### ISSUE TITLE
PEF file import (from Mac OS 9 PowerPC) fails due to destination index out of bounds

### ISSUE THREAD

**Issue by beshelto** [NationalSecurityAgency/ghidra#5169]
**Describe the bug**
The PEF file attached at [AudExtR_nift_-20493.bin.zip](https://github.com/NationalSecurityAgency/ghidra/files/11074285/AudExtR_nift_-20493.bin.zip) comes from the Mac OS 9 audio support extension.  I would like to decompile it to help fix an audio issue I'm encountering.  However, when I import it into my project, it fails with the following message:

```
arraycopy: last destination index 19721 out of bounds for byte[19700]
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 19721 out of bounds for byte[19700]
	at java.base/java.lang.System.arraycopy(Native Method)
	at ghidra.app.util.bin.format.pef.SectionHeader.getUnpackedData(SectionHeader.java:157)
	at ghidra.app.util.opinion.PefLoader.processSections(PefLoader.java:395)
	at ghidra.app.util.opinion.PefLoader.load(PefLoader.java:89)
	at ghidra.app.util.opinion.AbstractProgramWrapperLoader.loadProgram(AbstractProgramWrapperLoader.java:73)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:125)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:368)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```
---------------------------------------------------
Build Date: 2023-Feb-08 1242 EST
Ghidra Version: 10.2.3
Java Home: /Library/Java/JavaVirtualMachines/temurin-19.jdk/Contents/Home
JVM Version: Eclipse Adoptium 19.0.2
OS: Mac OS X 13.2.1 aarch64

**To Reproduce**
1. Drag the attached PEF file to a Ghidra project
2. Select to import it as PowerPC, 32-bit, big endian, default variant and compiler
3. Click OK

**Expected behavior**
PEF file loads into Ghidra and I can decompile it.

**Screenshots**
N/A

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: Mac OS X 13.2.1 aarch64
 - Java Version: Eclipse Adoptium 19.0.2
 - Ghidra Version: 10.2.3
 - Ghidra Origin: Homebrew package manager

**Additional context**
N/A

**Comment by dev747368** [comment]
FYI, apart from the initial error when unpacking the data of the section, it will then run into an unsupported relocation that also kills the import.  Commenting out the RuntimeException in RelocSmRepeat, it finishes loading, but there will probably be some messed up values that cause bad disassembly / decompilation.

**Comment by beshelto** [comment]
Tell you what, let me take a whack at the unsupported relocation.  That stuff is fresh enough in my mind that I don't think it would be too much work to throw something together.

**Comment by beshelto** [comment]
I have a fix for this bug and the unsupported relocation.  Once I have it cleaned up, I'll post a PR.

**Comment by beshelto** [comment]
OK, I posted the PR at https://github.com/NationalSecurityAgency/ghidra/pull/5178 -- with these changes, I can successfully import the attached PEF file.
