### ISSUE TITLE
ArrayIndexOutOfBoundsException when opening Help TOC

### ISSUE THREAD

**Issue by creffett** [NationalSecurityAgency/ghidra#519]
**Describe the bug**
When opening Help->Contents, the following exception was thrown:
`java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1`

**To Reproduce**
I'm not certain what led to this state, though earlier I had a help window freeze on me. Upon opening a new Ghidra instance, the issue did not happen again.

**Expected behavior**
I expected the help table of contents to open.

**Screenshots**
N/A

**Attachments**
N/A (nothing before or after the backtrace was related to the exception)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0.2
 - Ghidra Version: 9.0.2

**Additional context**
Full backtrace:
```
2019-04-26 13:40:37 ERROR (SwingExceptionHandler) Error: Uncaught Exception!
ArrayIndexOutOfBoundsException - Index 1 out of bounds for length 1 java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1^M
        at javax.help.WindowPresentation.createHelpWindow(WindowPresentation.java:898)^M
        at docking.help.GHelpBroker.updateWindowSize(GHelpBroker.java:349)^M
        at docking.help.GHelpBroker.setDisplayed(GHelpBroker.java:173)^M
        at docking.help.HelpManager.displayHelp(HelpManager.java:406)^M
        at docking.help.HelpManager.showHelp(HelpManager.java:267)^M
        at ghidra.framework.plugintool.PluginTool$9.actionPerformed(PluginTool.java:1227)^M
        at docking.DockingActionProxy.actionPerformed(DockingActionProxy.java:47)^M
        at docking.MenuBarMenuHandler$1.run(MenuBarMenuHandler.java:79)^M
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)^M
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)^M
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)^M
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)^M
        at java.base/java.security.AccessController.doPrivileged(Native Method)^M
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)^M
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)^M
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)^M
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)^M
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)^M
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)^M
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)^M
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by dragonmacher** [comment]
In examining the Java code where this happened, it seems that this could only happen if the graphics configuration changes while Ghidra was running.

I am closing this for now, as it it unreproducible.

**Comment by brainstorm** [comment]
Well, here you go:

```
Uncaught Exception! 
ArrayIndexOutOfBoundsException - Index 1 out of bounds for length 1
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at javax.help.WindowPresentation.createHelpWindow(WindowPresentation.java:898)
	at docking.help.GHelpBroker.updateWindowSize(GHelpBroker.java:349)
	at docking.help.GHelpBroker.setDisplayed(GHelpBroker.java:173)
	at docking.help.HelpManager.displayHelp(HelpManager.java:405)
	at docking.help.HelpManager.showHelp(HelpManager.java:266)
	at ghidra.framework.plugintool.PluginTool$10.actionPerformed(PluginTool.java:1079)
	at docking.DockingActionProxy.actionPerformed(DockingActionProxy.java:47)
	at docking.MenuBarMenuHandler$1.run(MenuBarMenuHandler.java:78)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2019-okt.-31 2242 AEDT
Ghidra Version: 9.2
Java Home: /Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
JVM Version: Amazon.com Inc. 11.0.4
OS: Mac OS X 10.15.1 x86_64
Workstation: localhost
```
