### ISSUE TITLE
Error importing DOS 16 bit binary

### ISSUE THREAD

**Issue by bsturk** [NationalSecurityAgency/ghidra#5206]
I have a real mode DOS executable which has an embedded overlay (done with RTLink).  I've used a tool re-arrange things such that the overlay is inline in the binary so it can be disassembled.  The binary ends up being larger than allowed address space for a DOS app, but I'm not looking to run it, just disassemble it.  When I try to import it I get the following error:

```
ghidra.program.model.address.AddressOutOfBoundsException: Address Overflow in subtract: 0000:0000 + 1025537
java.io.IOException: ghidra.program.model.address.AddressOutOfBoundsException: Address Overflow in subtract: 0000:0000 + 1025537
	at ghidra.app.util.opinion.MzLoader.load(MzLoader.java:112)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:724)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:98)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:125)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:368)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: ghidra.program.model.address.AddressOutOfBoundsException: Address Overflow in subtract: 0000:0000 + 1025537
	at ghidra.program.model.address.SegmentedAddressSpace.subtract(SegmentedAddressSpace.java:197)
	at ghidra.program.model.address.SegmentedAddressSpace.add(SegmentedAddressSpace.java:210)
	at ghidra.program.model.address.GenericAddress.add(GenericAddress.java:237)
	at ghidra.app.util.opinion.MzLoader.processMemoryBlocks(MzLoader.java:230)
	at ghidra.app.util.opinion.MzLoader.load(MzLoader.java:99)
	... 11 more

```
Steps to reproduce:

- Create a new project
- Import the binary keeping the defaults for "old" dos application
- Errors immediately

**Environment (please complete the following information):**
   Windows 11 Ghidra 10.2.3

**Additional context**
I can load the binary in IDA 5.0 which seems to be the last version which supports MZ DOS binaries.

**Comment by ryanmkurtz** [comment]
Can you share the binary?

**Comment by bsturk** [comment]
I can, yes.  I placed it here:

https://www.dropbox.com/s/8l5trjy81e14p73/CKIT_FOR_DISASM.zip?dl=0

Please let me know if you can't get at it, etc.

thank you!

**Comment by ryanmkurtz** [comment]
Got it, thanks!

**Comment by ryanmkurtz** [comment]
We don't think we are going to try to support your sample as-is, which does not seem to follow the MZ spec.  Have you tried loading in the original unaltered binary with the MZ loader and then using Ghidra's memory overlay features to model the overlays?  Or, if you are interested in getting bytes to disassemble, have you considered loading it in not as an MZ but as a Raw Binary, and then manually disassembling at the locations you care about?

**Comment by bsturk** [comment]
makes total sense, thanks for looking into it for me.

treating it as a normal overlay doesn't really work, the tool I used handles all of the fixing up of addresses etc.  The overlay is handled by RTLink.

and your last suggestion is what I have been doing, treating the base binary and overlay as different binaries in my project.

**Comment by ryanmkurtz** [comment]
Alrighty, I will go ahead and close this ticket then.
