### ISSUE TITLE
I want to use ghidra command line integration in code, but can't get it to work.

### ISSUE THREAD

**Issue by DaDong-G** [NationalSecurityAgency/ghidra#5257]
```
D:\work\python\binary_iot_project\ghidra\support>analyzeHeadless  D:\work\python\MyProject MyProject  -import C:\Users\Administrator\Desktop\librcm.so
Java HotSpot(TM) 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "ghidra.GhidraClassLoader"). To use archived non-system classes, this property must not be set
INFO  Using log config file: jar:file:/D:/work/python/binary_iot_project/ghidra/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)
INFO  Using log file: C:\Users\Administrator\.ghidra\.ghidra_9.2.1_PUBLIC\application.log (LoggingInitialization)
INFO  Loading user preferences: C:\Users\Administrator\.ghidra\.ghidra_9.2.1_PUBLIC\preferences (Preferences)
INFO  Loading previous preferences: C:\Users\Administrator\.ghidra\.ghidra_10.2.3_PUBLIC\preferences (Preferences)
INFO  Class search complete (620 ms) (ClassSearcher)
INFO  Initializing SSL Context (SSLContextInitializer)
INFO  Initializing Random Number Generator... (SecureRandomFactory)
INFO  Random Number Generator initialization complete: SHA1PRNG (SecureRandomFactory)
INFO  Trust manager disabled, cacerts have not been set (ApplicationTrustManagerFactory)
INFO  HEADLESS Script Paths:
    D:\work\python\binary_iot_project\ghidra\Ghidra\Features\BytePatterns\ghidra_scripts
    D:\work\python\binary_iot_project\ghidra\Ghidra\Processors\PIC\ghidra_scripts
    D:\work\python\binary_iot_project\ghidra\Ghidra\Features\Base\ghidra_scripts
    D:\work\python\binary_iot_project\ghidra\Ghidra\Processors\8051\ghidra_scripts
    D:\work\python\binary_iot_project\ghidra\Ghidra\Features\Decompiler\ghidra_scripts
    C:\Users\Administrator\ghidra_scripts
    D:\work\python\binary_iot_project\ghidra\Ghidra\Features\Python\ghidra_scripts
    D:\work\python\binary_iot_project\ghidra\Ghidra\Features\VersionTracking\ghidra_scripts
    D:\work\python\binary_iot_project\ghidra\Ghidra\Features\GnuDemangler\ghidra_scripts
    D:\work\python\binary_iot_project\ghidra\Ghidra\Processors\DATA\ghidra_scripts
    D:\work\python\binary_iot_project\ghidra\Ghidra\Features\FunctionID\ghidra_scripts
    D:\work\python\binary_iot_project\ghidra\Ghidra\Features\FileFormats\ghidra_scripts (HeadlessAnalyzer)
INFO  HEADLESS: execution starts (HeadlessAnalyzer)
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.lang.Object java.net.URL.streamHandlerLock accessible: module java.base does not "opens java.net" to unnamed module @79efed2d
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at org.apache.felix.framework.util.SecureAction._swapStaticFieldIfNotClass(SecureAction.java:998)
        at org.apache.felix.framework.util.SecureAction.swapStaticFieldIfNotClass(SecureAction.java:983)
        at org.apache.felix.framework.URLHandlers.unregisterFrameworkListsForContextSearch(URLHandlers.java:346)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.felix.framework.util.SecureAction.invoke(SecureAction.java:893)
        at org.apache.felix.framework.URLHandlers.unregisterFrameworkInstance(URLHandlers.java:661)
        at org.apache.felix.framework.URLHandlersActivator.stop(URLHandlersActivator.java:75)
        at org.apache.felix.framework.util.SecureAction.stopActivator(SecureAction.java:720)
        at org.apache.felix.framework.Felix$SystemBundleActivator.stop(Felix.java:5224)
        at org.apache.felix.framework.util.SecureAction.stopActivator(SecureAction.java:720)
        at org.apache.felix.framework.Felix.stopBundle(Felix.java:2795)
        at org.apache.felix.framework.Felix$2.run(Felix.java:1154)
java.lang.reflect.InaccessibleObjectException: Unable to make field private static volatile java.net.ContentHandlerFactory java.net.URLConnection.factory accessible: module java.base does not "opens java.net" to unnamed module @79efed2d
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at org.apache.felix.framework.util.SecureAction._swapStaticFieldIfNotClass(SecureAction.java:1019)
        at org.apache.felix.framework.util.SecureAction.swapStaticFieldIfNotClass(SecureAction.java:983)
        at org.apache.felix.framework.URLHandlers.unregisterFrameworkListsForContextSearch(URLHandlers.java:361)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.felix.framework.util.SecureAction.invoke(SecureAction.java:893)
        at org.apache.felix.framework.URLHandlers.unregisterFrameworkInstance(URLHandlers.java:661)
        at org.apache.felix.framework.URLHandlersActivator.stop(URLHandlersActivator.java:75)
        at org.apache.felix.framework.util.SecureAction.stopActivator(SecureAction.java:720)
        at org.apache.felix.framework.Felix$SystemBundleActivator.stop(Felix.java:5224)
        at org.apache.felix.framework.util.SecureAction.stopActivator(SecureAction.java:720)
        at org.apache.felix.framework.Felix.stopBundle(Felix.java:2795)
        at org.apache.felix.framework.Felix$2.run(Felix.java:1154)
ERROR Abort due to Headless analyzer error: null (HeadlessAnalyzer) java.lang.ExceptionInInitializerError
        at org.apache.felix.framework.URLHandlers.createURLStreamHandler(URLHandlers.java:513)
        at java.base/java.net.URL.getURLStreamHandler(URL.java:1436)
        at java.base/java.net.URL.<init>(URL.java:680)
        at java.base/java.net.URL.<init>(URL.java:569)
        at java.base/java.net.URL.<init>(URL.java:516)
        at ghidra.framework.protocol.ghidra.GhidraURL.makeURL(GhidraURL.java:281)
        at ghidra.framework.model.ProjectLocator.<init>(ProjectLocator.java:51)
        at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:411)
        at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:121)
        at ghidra.GhidraLauncher.main(GhidraLauncher.java:82)
Caused by: java.lang.RuntimeException: Unable to make protected boolean java.net.URLStreamHandler.equals(java.net.URL,java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @79efed2d
        at org.apache.felix.framework.URLHandlersStreamHandlerProxy.<clinit>(URLHandlersStreamHandlerProxy.java:104)
        ... 10 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected boolean java.net.URLStreamHandler.equals(java.net.URL,java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @79efed2d
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at org.apache.felix.framework.util.SecureAction.setAccesssible(SecureAction.java:871)
        at org.apache.felix.framework.URLHandlersStreamHandlerProxy.<clinit>(URLHandlersStreamHandlerProxy.java:79)
```

Environment (please complete the following information):

OS: windows 10
Ghidra Version: ghidra_10.2.3_PUBLIC

**Comment by ryanmkurtz** [comment]
Did you unzip ghidra 10.2.3 to a fresh location, or did you unzip it overtop an existing installation?

**Comment by DaDong-G** [comment]
> Did you unzip ghidra 10.2.3 to a fresh location, or did you unzip it overtop an existing installation?

Unpacked to a fresh location
java version 17.04

**Comment by DaDong-G** [comment]
版本的原因，我将java 17.04 换成了 11.0.1好了
