### ISSUE TITLE
Exception occured : XML Importer/Exporter failed

### ISSUE THREAD

**Issue by wichiandyx** [NationalSecurityAgency/ghidra#5276]
**Describe the bug**
When I tried to export XML from Ghidra to IDA, exception shown at IDA when try to select Edit -> Plugins -> XML Importer/XML Exporter.
I've tried to use latest \IDAPro\Python\7xx\ from the master
![image](https://user-images.githubusercontent.com/68545291/235355300-45d00b91-a96c-49dd-a9ae-81e56f8fa43e.png)

**To Reproduce**
1. Apply the  \IDAPro\Python\7xx\ files to IDA's loader, plugin, python's folder
2. Open IDA
3. Click Edit -> Plugins -> XML Importer/Exporter
4. See error shown below
![image](https://user-images.githubusercontent.com/68545291/235355408-ebfc2ea3-49e3-4541-82b5-5db74bb7d1e6.png)

**Update : **
I've tried to add a traceback to the xml_importer.py and this is what i found : 
```
***** Exception occurred: XML Importer failed! *****
 <function <lambda> at 0x00000208B158A0D0> <function <lambda> at 0x00000208B0CE1040>
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.7/plugins/xml_importer.py", line 75, in run
    xml.import_xml()
  File "C:\Program Files\IDA 7.7\python\3\idaxml.py", line 2272, in import_xml
    self.get_options(displayMenu)
  File "C:\Program Files\IDA 7.7\python\3\idaxml.py", line 2342, in get_options
    Opts =  { 'cGroup1': ida_kernwin.Form.ChkGroupControl ((
  File "C:\Program Files\IDA 7.7\python\3\ida_kernwin.py", line 9761, in __init__
    Form.GroupControl.__init__(
  File "C:\Program Files\IDA 7.7\python\3\ida_kernwin.py", line 9731, in __init__
    Form.NumericArgument.__init__(self, Form._FT_USHORT, value)
  File "C:\Program Files\IDA 7.7\python\3\ida_kernwin.py", line 9534, in __init__
    cls = Form.fieldtype_to_ctype(tp, self.DefI64)
  File "C:\Program Files\IDA 7.7\python\3\ida_kernwin.py", line 9517, in fieldtype_to_ctype
    return ctypes.c_ushort
NameError: name 'ctypes' is not defined
```

**Expected behavior**
To make XML Importer/Exporter work to make it's easier to migrate back and forth

**Screenshots**
Screenshots already been provided above

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: [17.0.4.1]
 - Ghidra Version: [10.2 DEV 28 April 2022 (latest)]
 - Ghidra Origin: [Official Github] 

**Additional context**
- IDA Pro Version: [7.7]
- Python Version : 
> Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] 
> IDAPython v7.4.0 final (serial 0)

**Comment by wichiandyx** [comment]
It seems I've already know what's the problem, there's 2 type of Python with different architecture in my computer, and my PYTHONHOME and PATH has different python, solving PYTHONHOME from C:\Users\User\AppData\Local\Programs\Python\Python38-32\ to C:\Users\User\AppData\Local\Programs\Python\Python39\ helps fix the problem 😄
