### ISSUE TITLE
MZ Loader cannot split on an overlay block

### ISSUE THREAD

**Issue by matthewturk** [NationalSecurityAgency/ghidra#5320]
**Describe the bug**
I'm trying to load a file, which I believe was generated by Borland Turbo-C, somewhere in the 2.0 range.  (It includes the string `Turbo-C - Copyright (c) 1988 Borland Intl.`)

I'm quite excited about the MZ Loader and immediately attempted to load a binary that I was able to import and analyze previously, albeit without the enhancements from the new developments in the 10.2.3 and 10.3 series.  I received an error message:

```
java.lang.IllegalArgumentException: Split cannot be done on an overlay block
java.io.IOException: java.lang.IllegalArgumentException: Split cannot be done on an overlay block
	at ghidra.app.util.opinion.MzLoader.load(MzLoader.java:113)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:809)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:100)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:388)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:347)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.IllegalArgumentException: Split cannot be done on an overlay block
	at ghidra.program.database.mem.MemoryMapDB.split(MemoryMapDB.java:962)
	at ghidra.app.util.opinion.MzLoader.adjustSegmentStarts(MzLoader.java:290)
	at ghidra.app.util.opinion.MzLoader.load(MzLoader.java:101)
	... 11 more
```

It looked like there was a segment start setup that I did not understand, so I've parsed the MZ header (using the [kaitai web ide](https://ide.kaitai.io/devel/)) and exported it to JSON:

https://gist.github.com/matthewturk/73772ca2e82381a6d44f95478423e296

There doesn't seem to be debugging output as to the specific values, but I can attempt to provide them if there is a way to do so.

**Expected behavior**

I have a handful of other executables *also* generated from the same basic setup, and they do load.  I will note that one thing that may be important is that this executable isn't expected to be run directly, but rather through INT 21h-4Bh, after an interrupt vector is set (for graphics drivers).

**Environment (please complete the following information):**

 - OS: Linux
 - Ghidra Version: 10.3 (released today!)
 - Ghidra Origin: official GitHub distro

**Additional context**

I'm more than happy to try to debug this, or to provide a patch, but I'm not entirely certain I understand where the error is coming from.  Additionally, if it would help I can manipulate the MZ header into whatever format works best to help with understanding it.

**Comment by ryanmkurtz** [comment]
Can you provide us the binary so we can debug it?

**Comment by matthewturk** [comment]
Yes -- the file is `CODE.1` inside this archive: https://archive.org/details/SUMM_12_ZIP , which can be directly accessed [through this deeplink](https://archive.org/download/SUMM_12_ZIP/SUMM_12.ZIP/CODE.1).

**Comment by ryanmkurtz** [comment]
Thanks. I can reproduce the problem and will work on a fix.

**Comment by matthewturk** [comment]
@ryanmkurtz Hey -- just wanted to say thank you.  I really appreciate you taking the time to work on this!

**Comment by ryanmkurtz** [comment]
Sure thing.  Turns out were were including the HEADER block in the blocks to split and join, which caused problems.  It was a very easy fix.
