### ISSUE TITLE
GhidraHelpService (v10.3) - URL is null

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#5327]
Subj. Happens during debugging my own module.

![image](https://github.com/NationalSecurityAgency/ghidra/assets/7189309/b4a7285a-b6a0-4490-b10e-e787db4370ff)

```
NullPointerException - Cannot invoke "java.net.URL.toExternalForm()" because "url" is null (SwingExceptionHandler) java.lang.NullPointerException: Cannot invoke "java.net.URL.toExternalForm()" because "url" is null
	at ghidra.base.help.GhidraHelpService.mapHelpToModule(GhidraHelpService.java:120)
	at ghidra.base.help.GhidraHelpService.findHelpSetsByModule(GhidraHelpService.java:104)
	at ghidra.base.help.GhidraHelpService.loadHelpSets(GhidraHelpService.java:85)
	at ghidra.base.help.GhidraHelpService.<init>(GhidraHelpService.java:60)
	at ghidra.base.help.GhidraHelpService.install(GhidraHelpService.java:51)
	at ghidra.GhidraRun.lambda$launch$1(GhidraRun.java:82)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by lab313ru** [comment]
I believe this is related too: https://github.com/NationalSecurityAgency/ghidra/issues/5328

**Comment by lab313ru** [comment]
Removing `build` folder of my extension fixed the bug.

**Comment by rjzak** [comment]
> Removing `build` folder of my extension fixed the bug.

Same, but now Ghidra I have a `java.lang.ClassNotFoundException` issue instead. If the compiled classes aren't in `build/`, when where are they supposed to be?

**Comment by lab313ru** [comment]
Debugging a plugin after building it gives you that error.
