### ISSUE TITLE
Cannot build old (10.2.3) module for 10.3 Ghidra

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#5328]
This is what happens:
```
Exception in thread "main" ghidra.util.exception.AssertException: Errors parsing HTML file: help.html
Incorrect stylesheet defined - none match help/shared/DefaultStyle.css in file F:\projects\v8dec\src\main\help\help\topics\v8dec\help.html
	Discovered stylesheets: [F:\projects\v8dec\src\main\help\help\shared\Frontpage.css]

	at help.validator.model.HelpFile.parseLinks(HelpFile.java:106)
	at help.validator.model.HelpFile.<init>(HelpFile.java:43)
	at help.validator.model.HelpTopic$1.visitFile(HelpTopic.java:85)
	at help.validator.model.HelpTopic$1.visitFile(HelpTopic.java:71)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
	at help.validator.model.HelpTopic.loadHelpFiles(HelpTopic.java:71)
	at help.validator.model.HelpTopic.<init>(HelpTopic.java:56)
	at help.validator.location.HelpModuleLocation.loadHelpTopics(HelpModuleLocation.java:62)
	at help.validator.location.HelpModuleLocation.<init>(HelpModuleLocation.java:41)
	at help.validator.location.DirectoryHelpModuleLocation.<init>(DirectoryHelpModuleLocation.java:29)
	at help.HelpBuildUtils.toLocation(HelpBuildUtils.java:68)
	at help.validator.location.HelpModuleCollection.toHelpLocations(HelpModuleCollection.java:95)
	at help.validator.location.HelpModuleCollection.fromFiles(HelpModuleCollection.java:79)
	at help.GHelpBuilder.collectAllHelp(GHelpBuilder.java:115)
	at help.GHelpBuilder.build(GHelpBuilder.java:89)
	at help.GHelpBuilder.main(GHelpBuilder.java:83)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildHelp'.
> Process 'command 'C:\Program Files\Eclipse Adoptium\jdk-17.0.6.10-hotspot\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by lab313ru** [comment]
It looks like old projects are incompatible in the LINK field:
![image](https://github.com/NationalSecurityAgency/ghidra/assets/7189309/96770682-dd36-4c8d-a34a-0c5a92244a09)

**Comment by lab313ru** [comment]
Changing to the `DefaultStyle.css` path fixed the bug.
