### ISSUE TITLE
10.3: Can No Longer Build Loader, Incorrect stylesheet defined

### ISSUE THREAD

**Issue by pjsoberoi** [NationalSecurityAgency/ghidra#5329]
**Describe the bug**
I can no longer build my loader. Ghidra 10.2.3 works, Ghidra 10.3 does no longer works.

**To Reproduce**
gradle -PGHIDRA_INSTALL_DIR=/home/poberoi/Desktop/ghidra_10.2.2_PUBLIC -> works
gradle -PGHIDRA_INSTALL_DIR=/home/poberoi/Desktop/ghidra_10.3_PUBLIC -> fails with the following error message:

```
> Task :buildHelp FAILED
INFO  Using log config file: jar:file:/home/poberoi/Desktop/ghidra_10.3_PUBLIC/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)  
INFO  Using log file: /home/poberoi/.helpbuilder/.helpbuilder_0.1_NO_RELEASE/application.log (LoggingInitialization)  
Exception in thread "main" ghidra.util.exception.AssertException: Errors parsing HTML file: help.html
Incorrect stylesheet defined - none match help/shared/DefaultStyle.css in file /home/poberoi/Ghidra-Loader/src/main/help/help/topics/loader/help.html
        Discovered stylesheets: [/home/poberoi/Ghidra-Loader/src/main/help/help/shared/Frontpage.css]

        at help.validator.model.HelpFile.parseLinks(HelpFile.java:106)
        at help.validator.model.HelpFile.<init>(HelpFile.java:43)
        at help.validator.model.HelpTopic$1.visitFile(HelpTopic.java:85)
        at help.validator.model.HelpTopic$1.visitFile(HelpTopic.java:71)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
        at help.validator.model.HelpTopic.loadHelpFiles(HelpTopic.java:71)
        at help.validator.model.HelpTopic.<init>(HelpTopic.java:56)
        at help.validator.location.HelpModuleLocation.loadHelpTopics(HelpModuleLocation.java:62)
        at help.validator.location.HelpModuleLocation.<init>(HelpModuleLocation.java:41)
        at help.validator.location.DirectoryHelpModuleLocation.<init>(DirectoryHelpModuleLocation.java:29)
        at help.HelpBuildUtils.toLocation(HelpBuildUtils.java:68)
        at help.validator.location.HelpModuleCollection.toHelpLocations(HelpModuleCollection.java:95)
        at help.validator.location.HelpModuleCollection.fromFiles(HelpModuleCollection.java:79)
        at help.GHelpBuilder.collectAllHelp(GHelpBuilder.java:115)
        at help.GHelpBuilder.build(GHelpBuilder.java:89)
        at help.GHelpBuilder.main(GHelpBuilder.java:83)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildHelp'.
> Process 'command '/usr/lib/jvm/java-17-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
4 actionable tasks: 3 executed, 1 up-to-date
```

**Expected behavior**
I expect my loader to build. 

**Environment (please complete the following information):**
 - Java Version: openjdk version "17.0.6" 2023-01-17
 - Ghidra Version: 10.3
 - Ghidra Origin: GitHub release

**Additional context**
I will try removing the help dir.

**Comment by topia** [comment]
seems to be the same as https://github.com/NationalSecurityAgency/ghidra/issues/5328#issue-1708689142

**Comment by pjsoberoi** [comment]
Yes it was the same issue. Thank you!
