### ISSUE TITLE
Unwinding stack produces VarnodeAST.getHigh() is null error

### ISSUE THREAD

**Issue by logdot** [NationalSecurityAgency/ghidra#5332]
**Describe the bug**
Unwinding the stack produces an error

**To Reproduce**
1. Create a new project
2. Import `WinHelloCPP.exe` from `.\docs\GhidraClass\ExerciseFiles\WinhelloCPP` and do default analysis
3. Launch the application in `dbgengine locally IN-VM`
4. Map the WinHello.exe module to WinHelloCPP.exe
5. Set breakpoint at `004014e0` (the program's main)
6. Start execution (F5)
7. Cause the stack to unwind (Debugger > Analysis > Unwind from frame 0)
8. Get error:
```
Cannot invoke "ghidra.program.model.pcode.HighVariable.getDataType()" because the return value of "ghidra.program.model.pcode.VarnodeAST.getHigh()" is null
```

**Expected behavior**
Would expect for stack unwinds to work.

**Environment (please complete the following information):**
 - OS: Windows 11 Insider Edition
 - Java Version: 17.0.2
 - Ghidra Version: 10.3
 - Ghidra Origin: Github

**Full Error**
```
Cannot invoke "ghidra.program.model.pcode.HighVariable.getDataType()" because the return value of "ghidra.program.model.pcode.VarnodeAST.getHigh()" is null
ghidra.pcode.exec.PcodeExecutionException: Cannot invoke "ghidra.program.model.pcode.HighVariable.getDataType()" because the return value of "ghidra.program.model.pcode.VarnodeAST.getHigh()" is null
	at ghidra.pcode.exec.PcodeExecutor.step(PcodeExecutor.java:275)
	at ghidra.pcode.exec.PcodeExecutor.finish(PcodeExecutor.java:178)
	at ghidra.pcode.exec.PcodeExecutor.execute(PcodeExecutor.java:160)
	at ghidra.pcode.exec.PcodeExecutor.execute(PcodeExecutor.java:135)
	at ghidra.app.plugin.core.debug.stack.UnwindAnalysis$AnalysisForPC.executeSet(UnwindAnalysis.java:248)
	at ghidra.app.plugin.core.debug.stack.UnwindAnalysis$AnalysisForPC.executeBlockFrom(UnwindAnalysis.java:296)
	at ghidra.app.plugin.core.debug.stack.UnwindAnalysis$AnalysisForPC.executeFromPc(UnwindAnalysis.java:379)
	at ghidra.app.plugin.core.debug.stack.UnwindAnalysis$AnalysisForPC.computeUnwindInfo(UnwindAnalysis.java:470)
	at ghidra.app.plugin.core.debug.stack.UnwindAnalysis.computeUnwindInfo(UnwindAnalysis.java:514)
	at ghidra.app.plugin.core.debug.stack.StackUnwinder.computeUnwindInfo(StackUnwinder.java:234)
	at ghidra.app.plugin.core.debug.stack.StackUnwinder.unwind(StackUnwinder.java:242)
	at ghidra.app.plugin.core.debug.stack.StackUnwinder.start(StackUnwinder.java:203)
	at ghidra.app.plugin.core.debug.stack.StackUnwinder.start(StackUnwinder.java:173)
	at ghidra.app.plugin.core.debug.stack.StackUnwinder$1$1.tryStart(StackUnwinder.java:284)
	at ghidra.app.plugin.core.debug.stack.StackUnwinder$1$1.<init>(StackUnwinder.java:268)
	at ghidra.app.plugin.core.debug.stack.StackUnwinder$1.iterator(StackUnwinder.java:267)
	at ghidra.app.plugin.core.debug.stack.UnwindStackCommand.applyToTyped(UnwindStackCommand.java:46)
	at ghidra.app.plugin.core.debug.stack.UnwindStackCommand.applyToTyped(UnwindStackCommand.java:30)
	at ghidra.framework.cmd.TypedBackgroundCommand.applyTo(TypedBackgroundCommand.java:34)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:336)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "ghidra.program.model.pcode.HighVariable.getDataType()" because the return value of "ghidra.program.model.pcode.VarnodeAST.getHigh()" is null
	at ghidra.app.plugin.core.debug.stack.SymPcodeExecutor.getSignatureFromTargetPointerType(SymPcodeExecutor.java:219)
	at ghidra.app.plugin.core.debug.stack.SymPcodeExecutor.getSignatureOfIndirectCall(SymPcodeExecutor.java:290)
	at ghidra.app.plugin.core.debug.stack.SymPcodeExecutor.computeStackChangeIndirect(SymPcodeExecutor.java:346)
	at ghidra.app.plugin.core.debug.stack.SymPcodeExecutor.executeIndirectCall(SymPcodeExecutor.java:385)
	at ghidra.pcode.exec.PcodeExecutor.stepOp(PcodeExecutor.java:246)
	at ghidra.pcode.exec.PcodeExecutor.step(PcodeExecutor.java:268)
	... 21 more
```

**Comment by nsadeveloper789** [comment]
This is a nascent feature, so I would not expect it to work in most cases. It may also need a good bit of manual analysis first, (especially on 32-bit x86 targets). Most of our testing, just to prove the concept, was done on innocuous Linux x86-64 binaries, like bash. It's also known to fail for non-returning functions. Best I can tell from your stack (having not yet replicated it myself) is that it's analyzing a CALL somewhere within the current function to assess its net effect on the stack pointer. Granted, this particular error looks more like a coding issue than an analysis issue.

That said, assuming I fix the coding error, there's no guarantee the stack unwind will be successful. It might just result in a better presentation of the failure :/ .

Also, FWIW, the dbgeng.dll should unwind the stack for you, so if you just need the frames' program counters, use the Stack window (or the Stack node in the Objects window). You don't need Ghidra's unwinder unless you're emulating or you want more insight into the actual stack frames. In any case, thanks for pointing out this case.

**Comment by logdot** [comment]
I understand. Assuming the issue stems from the analysis and not the code, my main concern is the really obtuse exception instead of a more intelligible error.

If it's of any help, these are all the binaries I've tested unwinding the stack on:
- A game's exe, written in C++. The binary is in x86-64. No debug information. (This is the exe I'm actually interested in)
- WinHelloCPP from the exercise files. The binary is in x86. No debug information. (I used this as a MRE)
- A simple C++ cmd app built from my own code. The binary is in x86-64. Debug information was included.

All of them (except sometimes the game*) always produce the same error when attempting to unwind the stack, no matter of from where the stack is being unwound.

*Depending on where I unwind the stack from in the game, I get this very similar error instead. I haven't been able to discern what the cause is at all. All I've been able to figure out is that at a specific point in the call stack the error switches from the original error to this one. Any calls deeper into the call stack once the error changes "inherit" the new error.
```
Cannot invoke "ghidra.program.model.pcode.HighFunction.getPcodeOps(ghidra.program.model.address.Address)" because "hfunc" is null
ghidra.pcode.exec.PcodeExecutionException: Cannot invoke "ghidra.program.model.pcode.HighFunction.getPcodeOps(ghidra.program.model.address.Address)" because "hfunc" is null
	at ghidra.pcode.exec.PcodeExecutor.step(PcodeExecutor.java:275)
	at ghidra.pcode.exec.PcodeExecutor.finish(PcodeExecutor.java:178)
	at ghidra.pcode.exec.PcodeExecutor.execute(PcodeExecutor.java:160)
	at ghidra.pcode.exec.PcodeExecutor.execute(PcodeExecutor.java:135)
	at ghidra.app.plugin.core.debug.stack.UnwindAnalysis$AnalysisForPC.executeSet(UnwindAnalysis.java:248)
	at ghidra.app.plugin.core.debug.stack.UnwindAnalysis$AnalysisForPC.executeBlock(UnwindAnalysis.java:279)
	at ghidra.app.plugin.core.debug.stack.UnwindAnalysis$AnalysisForPC.executePathTo(UnwindAnalysis.java:316)
	at ghidra.app.plugin.core.debug.stack.UnwindAnalysis$AnalysisForPC.executeToPc(UnwindAnalysis.java:357)
	at ghidra.app.plugin.core.debug.stack.UnwindAnalysis$AnalysisForPC.computeUnwindInfo(UnwindAnalysis.java:459)
	at ghidra.app.plugin.core.debug.stack.UnwindAnalysis.computeUnwindInfo(UnwindAnalysis.java:514)
	at ghidra.app.plugin.core.debug.stack.StackUnwinder.computeUnwindInfo(StackUnwinder.java:234)
	at ghidra.app.plugin.core.debug.stack.StackUnwinder.unwind(StackUnwinder.java:242)
	at ghidra.app.plugin.core.debug.stack.AnalysisUnwoundFrame.unwindNext(AnalysisUnwoundFrame.java:152)
	at ghidra.app.plugin.core.debug.stack.StackUnwinder$1$1.tryNext(StackUnwinder.java:293)
	at ghidra.app.plugin.core.debug.stack.StackUnwinder$1$1.next(StackUnwinder.java:278)
	at ghidra.app.plugin.core.debug.stack.StackUnwinder$1$1.next(StackUnwinder.java:267)
	at ghidra.app.plugin.core.debug.stack.UnwindStackCommand.applyToTyped(UnwindStackCommand.java:46)
	at ghidra.app.plugin.core.debug.stack.UnwindStackCommand.applyToTyped(UnwindStackCommand.java:30)
	at ghidra.framework.cmd.TypedBackgroundCommand.applyTo(TypedBackgroundCommand.java:34)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:336)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "ghidra.program.model.pcode.HighFunction.getPcodeOps(ghidra.program.model.address.Address)" because "hfunc" is null
	at ghidra.app.plugin.core.debug.stack.SymPcodeExecutor.getHighCallOp(SymPcodeExecutor.java:193)
	at ghidra.app.plugin.core.debug.stack.SymPcodeExecutor.getSignatureOfIndirectCall(SymPcodeExecutor.java:286)
	at ghidra.app.plugin.core.debug.stack.SymPcodeExecutor.computeStackChangeIndirect(SymPcodeExecutor.java:346)
	at ghidra.app.plugin.core.debug.stack.SymPcodeExecutor.executeIndirectCall(SymPcodeExecutor.java:385)
	at ghidra.pcode.exec.PcodeExecutor.stepOp(PcodeExecutor.java:246)
	at ghidra.pcode.exec.PcodeExecutor.step(PcodeExecutor.java:268)
	... 21 more
```

I have no idea if this error is related to the original one, or if it affects all of the binaries and I just haven't encountered it in the other ones. Do you want me to create a new issue for it, or should I keep it in this one?

**Comment by nsadeveloper789** [comment]
No need for a new issue, I think this one captures the overall issue well enough. If there are related things, we'll probably end up addressing them as we encounter them. It seems to me all we probably need to do is test it out on Windows. We ought to get it working there eventually, anyway.... If you're worried about issue curation, the furthest I'd go is re-titling this one: "Port Debugger stack unwinder to Windows targets."

Thanks for the additional details. It's helpful to know x64 binaries are affected as well.
