### ISSUE TITLE
Eclipse 2023-06 - Invalid URI scheme

### ISSUE THREAD

**Issue by lab313ru** [NationalSecurityAgency/ghidra#5363]
Subj. It's impossible to install GhidraDev v3.0.0 into Eclipse 2023-06 version.

![image](https://github.com/NationalSecurityAgency/ghidra/assets/7189309/a87ae6b4-eb4e-4686-b869-7bd39f46488a)

**Comment by lab313ru** [comment]
Stacktrace:
```
java.lang.IllegalArgumentException: invalid URI scheme file
	at java.net.http/jdk.internal.net.http.common.Utils.newIAE(Utils.java:286)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.checkURI(HttpRequestBuilderImpl.java:82)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.uri(HttpRequestBuilderImpl.java:71)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.uri(HttpRequestBuilderImpl.java:43)
	at org.eclipse.equinox.internal.p2.engine.phases.AuthorityChecker.lambda$9(AuthorityChecker.java:253)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:3064)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.eclipse.equinox.internal.p2.engine.phases.AuthorityChecker.gatherCertificates(AuthorityChecker.java:251)
	at org.eclipse.equinox.internal.p2.engine.phases.AuthorityChecker.getCertificates(AuthorityChecker.java:244)
	at org.eclipse.equinox.internal.p2.engine.phases.AuthorityChecker.start(AuthorityChecker.java:124)
	at org.eclipse.equinox.internal.p2.engine.phases.Collect.completePhase(Collect.java:97)
	at org.eclipse.equinox.internal.p2.engine.Phase.postPerform(Phase.java:254)
	at org.eclipse.equinox.internal.p2.engine.Phase.perform(Phase.java:105)
	at org.eclipse.equinox.internal.p2.engine.PhaseSet.perform(PhaseSet.java:50)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:95)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:49)
	at org.eclipse.equinox.p2.operations.ProvisioningSession.performProvisioningPlan(ProvisioningSession.java:181)
	at org.eclipse.equinox.p2.operations.ProfileModificationJob.runModal(ProfileModificationJob.java:76)
	at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:188)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by ryanmkurtz** [comment]
I just tried it and could not reproduce this.  Does it work with 2023-03 for you?  I just tried it with [4.28RC1](https://download.eclipse.org/eclipse/downloads/drops4/S-4.28RC1-202305250350/).

**Comment by ryanmkurtz** [comment]
I just tried again with the final released version of 2023-06 and didn't have an issue.

**Comment by ryanmkurtz** [comment]
If you continue to run into the issue with the newest version, let me know.
