### ISSUE TITLE
Exception when importing the dyld_shared_cache

### ISSUE THREAD

**Issue by find0x90** [NationalSecurityAgency/ghidra#5392]
**Describe the bug**
Exception when importing the dyld_shared_cache. 

**To Reproduce**
On macOS 13.4, the arm64 cache is located at `/System/Volumes/Preboot/Cryptexes/OS/System/Library/dyld/dyld_shared_cache_arm64e`. 
1. Create a new project. 
2. Drag the shared cache from that path above in Finder onto the project. 
3. Import with the default settings. 

**Expected behavior**
The file to import successfully. 

**Screenshots**
<img width="1052" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/16763079/dc0a7008-34db-4abc-ac52-1ca1f4583265">

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**
 - OS: [macOS 13.4]
 - Java Version: [20.0.1]
 - Ghidra Version: [10.4-DEV commit: 007cfacd6cba3bb8d50e2ec78c9521025a5c7fcd]
 - Ghidra Origin: [locally built] 

**Additional context**
```
Address Overflow in subtract: 18f10f000 - 0x7ffffffb00000001
java.io.IOException: Address Overflow in subtract: 18f10f000 - 0x7ffffffb00000001
	at ghidra.app.util.opinion.DyldCacheLoader.load(DyldCacheLoader.java:97)
	at ghidra.app.util.opinion.AbstractProgramWrapperLoader.loadProgram(AbstractProgramWrapperLoader.java:76)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:388)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:347)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: ghidra.program.model.address.AddressOutOfBoundsException: Address Overflow in subtract: 18f10f000 - 0x7ffffffb00000001
	at ghidra.program.model.address.AbstractAddressSpace.add(AbstractAddressSpace.java:431)
	at ghidra.program.model.address.GenericAddressSpace.add(GenericAddressSpace.java:21)
	at ghidra.program.model.address.GenericAddress.add(GenericAddress.java:237)
	at ghidra.app.util.opinion.MachoProgramBuilder.processExports(MachoProgramBuilder.java:514)
	at ghidra.app.util.opinion.DyldCacheProgramBuilder$DyldCacheMachoInfo.createExports(DyldCacheProgramBuilder.java:418)
	at ghidra.app.util.opinion.DyldCacheProgramBuilder.processDylibs(DyldCacheProgramBuilder.java:319)
	at ghidra.app.util.opinion.DyldCacheProgramBuilder.build(DyldCacheProgramBuilder.java:124)
	at ghidra.app.util.opinion.DyldCacheProgramBuilder.buildProgram(DyldCacheProgramBuilder.java:88)
	at ghidra.app.util.opinion.DyldCacheLoader.load(DyldCacheLoader.java:88)
	... 10 more
```

**Comment by find0x90** [comment]
Noticed there were changes since I built, this also reproduces with 3e9419d4d793dad0619e51769474be61d6968ef9.

**Comment by ryanmkurtz** [comment]
I was only seeing 1 bad export so I just gracefully handled the error.  I didn't look into why that one particular export had a weird address value.

**Comment by find0x90** [comment]
It now imports successfully for me, thanks!
