### ISSUE TITLE
NullPointerException when navigating

### ISSUE THREAD

**Issue by find0x90** [NationalSecurityAgency/ghidra#5468]
**Describe the bug**
When navigating to and back from certain functions, a null pointer exception is raised. After dismissing the exception, clicking in the decompiler window will repeatedly raise the same exception. 

**To Reproduce**
1. Download iOS 16.5: https://ipsw.me/download/iPhone15,3/20F66 (direct link: https://updates.cdn-apple.com/2023SpringFCS/fullrestores/032-85649/B60EDD9A-281A-4BD8-8EF6-F9F37812D217/iPhone15,3_16.5_20F66_Restore.ipsw)
3. Extract the ipsw: ` cd ~/Downloads && unzip ./iPhone15,3_16.5_20F66_Restore.ipsw -d ./iPhone15,3_16.5_20F66_Restore.ipsw.extracted`
4. Mount this dmg: `hdiutil attach ~/Downloads/iPhone15,3_16.5_20F66_Restore.ipsw.extracted/096-04007-076.dmg`
5. Open this path in Finder: `/Volumes/SydneyF20F66.D74OS/private/var/staged_system_apps/`
6. Create a new Ghidra project and drag `Calculator.app` into the project. After importing, open in the Code Browser and autoanalyze. 
7. In the decompilation of the entry function, find and double click `_UIApplicationMain`. Note that the UI may not appear to actually navigate to `_UIApplicationMain`. 
8. Navigate back using the back button. 
9. The exception occurs. 

**Screenshots**
<img width="1024" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/16763079/dfbb3685-1e8f-4eab-bac1-e51d72418bc8">
****

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: macOS 14.0
 - Java Version: 20.0.1
 - Ghidra Version: 8cc3a9443b023c4c761d9da141ed977d74a86054 (built from master on 2023-06-19)
 - Ghidra Origin: locally built

**Additional context**
Exception text:
```
Cannot invoke "docking.widgets.fieldpanel.field.Field.getText()" because "f" is null
java.lang.NullPointerException: Cannot invoke "docking.widgets.fieldpanel.field.Field.getText()" because "f" is null
	at ghidra.app.decompiler.component.DecompilerPanel$DecompilerFieldPanel.lambda$new$0(DecompilerPanel.java:1304)
	at docking.widgets.fieldpanel.AccessibleFieldPanelDelegate.generateDescription(AccessibleFieldPanelDelegate.java:160)
	at docking.widgets.fieldpanel.AccessibleFieldPanelDelegate.setCaret(AccessibleFieldPanelDelegate.java:110)
	at docking.widgets.fieldpanel.FieldPanel$AccessibleFieldPanel.cursorChanged(FieldPanel.java:1404)
	at docking.widgets.fieldpanel.FieldPanel$CursorHandler.notifyCursorChanged(FieldPanel.java:2431)
	at docking.widgets.fieldpanel.FieldPanel$CursorHandler.setCursorPos(FieldPanel.java:2175)
	at docking.widgets.fieldpanel.FieldPanel$CursorHandler.updateCursor(FieldPanel.java:2453)
	at docking.widgets.fieldpanel.FieldPanel.modelSizeChanged(FieldPanel.java:1049)
	at ghidra.app.decompiler.component.ClangLayoutController.modelChanged(ClangLayoutController.java:120)
	at ghidra.app.decompiler.component.ClangLayoutController.buildLayoutInternal(ClangLayoutController.java:247)
	at ghidra.app.decompiler.component.ClangLayoutController.buildLayouts(ClangLayoutController.java:326)
	at ghidra.app.decompiler.component.DecompilerPanel.setDecompileData(DecompilerPanel.java:409)
	at ghidra.app.decompiler.component.DecompilerController.setDecompileData(DecompilerController.java:182)
	at ghidra.app.decompiler.component.DecompilerController.loadFromCache(DecompilerController.java:129)
	at ghidra.app.decompiler.component.DecompilerController.display(DecompilerController.java:106)
	at ghidra.app.plugin.core.decompile.DecompilerProvider.setLocation(DecompilerProvider.java:448)
	at ghidra.app.plugin.core.decompile.DecompilerProvider.goTo(DecompilerProvider.java:250)
	at ghidra.app.plugin.core.gotoquery.GoToHelper.doGoTo(GoToHelper.java:120)
	at ghidra.app.plugin.core.gotoquery.GoToHelper.lambda$goTo$0(GoToHelper.java:84)
	at ghidra.util.Swing.lambda$runNow$1(Swing.java:148)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.util.Swing.runNow(Swing.java:148)
	at ghidra.app.plugin.core.gotoquery.GoToHelper.goTo(GoToHelper.java:84)
	at ghidra.app.plugin.core.gotoquery.GoToHelper.goToExternalLinkage(GoToHelper.java:233)
	at ghidra.app.plugin.core.gotoquery.GoToHelper.goToExternalLocation(GoToHelper.java:264)
	at ghidra.app.util.navigation.GoToServiceImpl.goToExternalLocation(GoToServiceImpl.java:131)
	at ghidra.app.plugin.core.decompile.DecompilerProvider.goToFunction(DecompilerProvider.java:651)
	at ghidra.app.decompiler.component.DecompilerController.goToFunction(DecompilerController.java:283)
	at ghidra.app.decompiler.component.DecompilerPanel.tryGoToFunction(DecompilerPanel.java:757)
	at ghidra.app.decompiler.component.DecompilerPanel.tryToGoto(DecompilerPanel.java:722)
	at ghidra.app.decompiler.component.DecompilerPanel.buttonPressed(DecompilerPanel.java:701)
	at docking.widgets.fieldpanel.FieldPanel.lambda$notifyFieldMouseListeners$0(FieldPanel.java:1328)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2023-Jun-19 1045 PDT
Ghidra Version: 10.4
Java Home: /Applications/Ghidra.app/Contents/Resources/java_home
JVM Version: Eclipse Adoptium 20.0.1
OS: Mac OS X 14.0 aarch64

```

**Comment by find0x90** [comment]
Fixed for me with 0beaf23e035a0e82fd737949b774f0a8a55f9e35, thanks!
