### ISSUE TITLE
Error importing file - Invalid Index

### ISSUE THREAD

**Issue by Gnomey123** [NationalSecurityAgency/ghidra#5496]
**Describe the bug**
Whenever attempting to import vhusbdwin64.exe into a new blank project, it responds with a Java Invalid Index error

**To Reproduce**
1. Create New Project
2. Click Import
3. Select vhusbdwin64.exe
4. Confirm default importing settings
5. See error

**Expected behavior**
After parsing through the exe, it should make it available to be opened within the Active Project window

**Screenshots**
![image](https://github.com/NationalSecurityAgency/ghidra/assets/34148010/36a49653-22d6-49ee-b3d8-be56b4965737)
![image](https://github.com/NationalSecurityAgency/ghidra/assets/34148010/f042d55e-4335-4c89-84c8-03febe9e021d)

**Attachments**
[vhusbdwin64.zip](https://github.com/NationalSecurityAgency/ghidra/files/11872247/vhusbdwin64.zip)

**Environment (please complete the following information):**
Build Date: 2023-Jun-14 1629 EDT
Ghidra Version: 10.3.1
Java Home: C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot
JVM Version: Eclipse Adoptium 17.0.7
OS: Windows 10 10.0 amd64

**Additional context**
Here's the complete error message:

```
Invalid index: 4612792
java.io.IOException: Invalid index: 4612792
	at ghidra.app.util.bin.FileByteProvider.ensureBounds(FileByteProvider.java:264)
	at ghidra.app.util.bin.FileByteProvider.readByte(FileByteProvider.java:112)
	at ghidra.formats.gfilesystem.RefdByteProvider.readByte(RefdByteProvider.java:90)
	at ghidra.app.util.bin.BinaryReader.readByte(BinaryReader.java:882)
	at ghidra.app.util.bin.BinaryReader.readNextByte(BinaryReader.java:391)
	at ghidra.app.util.bin.format.pe.PEx64UnwindInfo.readUnwindInfo(PEx64UnwindInfo.java:171)
	at ghidra.app.util.bin.format.pe.ImageRuntimeFunctionEntries_X86.<init>(ImageRuntimeFunctionEntries_X86.java:99)
	at ghidra.app.util.bin.format.pe.ExceptionDataDirectory.parse(ExceptionDataDirectory.java:60)
	at ghidra.app.util.bin.format.pe.DataDirectory.processDataDirectory(DataDirectory.java:80)
	at ghidra.app.util.bin.format.pe.ExceptionDataDirectory.<init>(ExceptionDataDirectory.java:38)
	at ghidra.app.util.bin.format.pe.OptionalHeaderImpl.processDataDirectories(OptionalHeaderImpl.java:313)
	at ghidra.app.util.opinion.PeLoader.load(PeLoader.java:124)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:811)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:100)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:388)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:347)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

---------------------------------------------------
Build Date: 2023-Jun-14 1629 EDT
Ghidra Version: 10.3.1
Java Home: C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot
JVM Version: Eclipse Adoptium 17.0.7
OS: Windows 10 10.0 amd64
Workstation: N****-DESKPC
```

**Comment by ryanmkurtz** [comment]
Same exception as #5483

**Comment by ryanmkurtz** [comment]
Binary is packed with UPX.

**Comment by Gnomey123** [comment]
Hum, UPX might be related to issue #5483

**Comment by ryanmkurtz** [comment]
To address this, I just gracefully handled the failed parsing of the `ExceptionDataDirectory` so the import could complete.  Since it is UPX packed, you will run into more warnings about Ghidra failing to parse packed data.
