### ISSUE TITLE
data created with older software and requires upgrade

### ISSUE THREAD

**Issue by RenaKunisaki** [NationalSecurityAgency/ghidra#5536]
**Describe the bug**
When I open my program, I get this error popup:

```
data created with older software and requires upgrade
ghidra.util.exception.VersionException: data created with older software and requires upgrade
	at ghidra.program.database.module.ModuleDBAdapterV1.<init>(ModuleDBAdapterV1.java:64)
	at ghidra.program.database.module.ModuleDBAdapter.getAdapter(ModuleDBAdapter.java:48)
	at ghidra.program.database.module.ModuleManager.initializeAdapters(ModuleManager.java:116)
	at ghidra.program.database.module.ModuleManager.<init>(ModuleManager.java:87)
	at ghidra.program.database.module.TreeManager.initTreeMap(TreeManager.java:483)
	at ghidra.program.database.module.TreeManager.<init>(TreeManager.java:80)
	at ghidra.program.database.ProgramDB.createManagers(ProgramDB.java:1739)
	at ghidra.program.database.ProgramDB.<init>(ProgramDB.java:342)
	at ghidra.program.database.ProgramContentHandler.getChangeSet(ProgramContentHandler.java:297)
	at ghidra.framework.data.GhidraFileData.getChangesByOthersSinceCheckout(GhidraFileData.java:336)
	at ghidra.framework.data.GhidraFile.getChangesByOthersSinceCheckout(GhidraFile.java:202)
	at ghidra.app.plugin.core.misc.MyProgramChangesDisplayPlugin$UpdateChangeSetJob.run(MyProgramChangesDisplayPlugin.java:439)
	at ghidra.util.worker.AbstractWorker$JobCallback.process(AbstractWorker.java:133)
	at ghidra.util.worker.AbstractWorker$JobCallback.process(AbstractWorker.java:123)
	at generic.concurrent.ConcurrentQ$CallbackCallable.call(ConcurrentQ.java:658)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)

---------------------------------------------------
Build Date: 2023-Jun-17 1523 CEST
Ghidra Version: 10.3.1
Java Home: /usr/lib/jvm/java-20-openjdk
JVM Version: N/A 20.0.1
OS: Linux 6.3.6-artix1-1 amd64
Workstation: greymon
```

But what data is this referring to and how do I upgrade it?

**To Reproduce**
1. Open project
2. Open program
3. Get error popup

**Expected behavior**
Error should explain what data needs upgrading, and how to do that.

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Artix Linux AMD64
 - Java Version: 20.0.1
 - Ghidra Version: 10.3.1
 - Ghidra Origin: Artix package manager

**Additional context**
Can provide project file if necessary, but it's gigantic.

**Comment by astrelsky** [comment]
If you are using version control I think you need to open it so you can make modifications. I don't use Ghidra's version control so my terminology is lacking.

**Comment by ghidra1** [comment]
Are you accessing a shared Ghidra Server project where others have checked-in revisions and you have not? Could you look at your Program information properties and tell me what you have for "Created with Ghidra Version". You can find this from the Help->About <your-program-name>.

What version of Ghidra are you currently using?

There are no provisions in the DomainFile.getChangesByOthersSinceCheckout method to cope with a VersionException, however you should not have run into this under normal conditions.

The Module DB Adapter schema version has not been changed since Ghidra was released so I can only assumed there may be some other issue. Are you able to share your Ghidra project file with us? If so, I would need to it to be produced from the project file on your server and not the one you may have checked-out. If your answer is yes, I will provide further instructions on how best to do this.

**Comment by RenaKunisaki** [comment]
I'm not using a server, but one of the programs does give a message about being shared. It's created with version 9.0.4.

**Comment by ghidra1** [comment]
What do you see for the offending file if you Show History... on it from main Project window (assuming it is enabled)?

**Comment by RenaKunisaki** [comment]
```
4	Fri Apr 02 17:09:59 EDT 2021	rena	names from debug version
3	Tue Mar 30 19:17:59 EDT 2021	rena	some gametext stuff
2	Sat Mar 27 22:22:29 EDT 2021	rena	importing some names from default.dol
1	Sat Mar 27 15:25:43 EDT 2021	rena	SFA v1.0 main.dol
```

I noticed it was "checked out", so I tried to check it back in and got another message:

```
Unable to Checkin Program: main.dol.patchedOsReport

File was created with an older version of Ghidra (data upgrade is possible)
---------------------------------------------------
Build Date: 2023-Jun-17 1523 CEST
Ghidra Version: 10.3.1
Java Home: /usr/lib/jvm/java-20-openjdk
JVM Version: N/A 20.0.1
OS: Linux 6.3.6-artix1-1 amd64
Workstation: greymon
```

So I suppose that's what the message refers to, but it doesn't explain *how* to upgrade.

FWIW the point of opening this bug report is more to say that these messages should be more helpful than to ask for help with my case specifically, but the help is appreciated too.
