### ISSUE TITLE
flatlaf: Uncaught Exception!  IllegalArgumentException - Invalid location

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#5539]
**Describe the bug**
Not sure what I clicked on or did to trigger this, but this popped up infinitely, had to force close ghidra process

```
Invalid location
java.lang.IllegalArgumentException: Invalid location
	at java.desktop/javax.swing.text.JTextComponent.getSelectedText(JTextComponent.java:1784)
	at java.desktop/javax.swing.text.DefaultCaret.updateSystemSelection(DefaultCaret.java:1390)
	at java.desktop/javax.swing.text.DefaultCaret.focusGained(DefaultCaret.java:385)
	at com.formdev.flatlaf.ui.FlatCaret.focusGained(FlatCaret.java:150)
	at java.desktop/java.awt.AWTEventMulticaster.focusGained(AWTEventMulticaster.java:228)
	at java.desktop/java.awt.Component.processFocusEvent(Component.java:6515)
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1952)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1061)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:687)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4882)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Environment (please complete the following information):**
 - OS: 22.04
 - Java Version: 17.0.7
 - Ghidra Version: 10.3.1
 - Ghidra Origin: official

**Comment by dragonmacher** [comment]
Gremlins?

**Comment by mumbel** [comment]
That's what I was thinking too, since I didn't see "ghidra" things really, just reporting incase

**Comment by ryanmkurtz** [comment]
Cool, looks like the fix for this ticket will be to upgrade our flatlaf jar to 3.2 when they release it.

**Comment by DevCharly** [comment]
FlatLaf 3.2 is available.

Note that there is a problem in class `GTableHeaderRenderer` with newer FlatLaf versions. See: https://github.com/JFormDesigner/FlatLaf/issues/722

**Comment by dragonmacher** [comment]
> FlatLaf 3.2 is available.
> 
> Note that there is a problem in class `GTableHeaderRenderer` with newer FlatLaf versions. See: [JFormDesigner/FlatLaf#722](https://github.com/JFormDesigner/FlatLaf/issues/722)

This appears to be a flaw in Ghidra's code where we assume that the `delegate` renderer is a `Component`, which it does not have to be.
