### ISSUE TITLE
Error recovering a class with unknown parents (RecoverClassesFromRTTIScript.java)

### ISSUE THREAD

**Issue by saruman9** [NationalSecurityAgency/ghidra#5642]
**Describe the bug**

If a class has unknown (maybe external) parents, then the analysis is interrupted with an error.

**To Reproduce**
1. Run the script (`RecoverClassesFromRTTIScript.java`) on a file that contains classes with unknown/external parents.
2. See error:

<details>
  <summary>Error running script: `RecoverClassesFromRTTIScript.java`</summary>

```
java.lang.reflect.InvocationTargetException
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1734)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:690)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:790)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:669)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:634)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:334)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.IllegalArgumentException: RecoveredClass should already exist for std::__ndk1::basic_ios<char,std::__ndk1::char_traits<char>>
	at classrecovery.RTTIGccClassRecoverer.addClassParentsAndFlagsForVmiClass(RTTIGccClassRecoverer.java:3552)
	at classrecovery.RTTIGccClassRecoverer.updateClassesWithParentsAndFlags(RTTIGccClassRecoverer.java:733)
	at classrecovery.RTTIGccClassRecoverer.createRecoveredClasses(RTTIGccClassRecoverer.java:253)
	at RecoverClassesFromRTTIScript.run(RecoverClassesFromRTTIScript.java:336)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:399)
	at ghidra.app.script.GhidraScript$1.analysisWorkerCallback(GhidraScript.java:381)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1728)
	... 8 more
```

</details>

**Expected behavior**

The analysis should continue and finish, even if with errors.

**Screenshots**

N/A

**Attachments**

The binary file in which I encountered the error is private.

**Environment (please complete the following information):**
 - OS: ArchLinux
 - Java Version: openjdk 20.0.1 2023-04-18
 - Ghidra Version: 26d4bd91
 - Ghidra Origin: locally built

**Additional context**

I have created a PR (#5641) that fixes this problem.

**Comment by ryanmkurtz** [comment]
Fixed by 5709ca80d3444607edaf6a120a8eca6374eb2f11
