### ISSUE TITLE
Concurrent Modification Exception in TableChooserDialog

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#5690]
**Describe the bug**
The stack is as follows:
```
Error: Uncaught Exception!  java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at docking.widgets.table.GTableColumnModel.recalcWidthCache(GTableColumnModel.java:460)
	at docking.widgets.table.GTableColumnModel.getTotalColumnWidth(GTableColumnModel.java:332)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4486)
	at docking.widgets.table.GTable.tableChanged(GTable.java:170)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
	at docking.widgets.table.AbstractSortedTableModel.notifyModelSorted(AbstractSortedTableModel.java:356)
	at docking.widgets.table.threaded.ThreadedTableModel.setModelState(ThreadedTableModel.java:569)
	at docking.widgets.table.threaded.TableUpdateJob.lambda$applyData$0(TableUpdateJob.java:686)
	at ghidra.util.Swing.lambda$runNow$2(Swing.java:227)
```

**To Reproduce**
I have not been able to consistently reproduce this bug, but it seems to occur when running a (custom) script the first time upon reloading Ghidra. The script creates a ``TableChooserDialog`` with various non-default settings e.g. additional columns, already saved.

**Comment by dragonmacher** [comment]
In looking at this ticket, my guess is that you are modifying the dialog in your script in a way that is not doing the work in the Swing thread.    I  looked at a few of the scripts we ship and they are calling API methods that are doing this the correct way, for example, on the `TableChooserDialog`, we use this method to add columns:

```
	public void addCustomColumn(ColumnDisplay<?> columnDisplay) {
		Swing.runNow(() -> model.addCustomColumn(columnDisplay));
	}
```
This method is placing the execution onto the Swing thread via the `Swing.runNow()` call.   We can probably fix other places in the API that need this call.

Would you mind pasting your script code that configures or changes the dialog?

**Comment by sad-dev** [comment]
I havn't been able to reproduce it consistently, but a (shortened) version of my script is:

```
import java.awt.Component;
import java.util.Iterator;

import javax.swing.JLabel;

import docking.widgets.table.GTableCellRenderingData;
import ghidra.app.script.GhidraScript;
import ghidra.app.tablechooser.AbstractComparableColumnDisplay;
import ghidra.app.tablechooser.AddressableRowObject;
import ghidra.app.tablechooser.StringColumnDisplay;
import ghidra.app.tablechooser.TableChooserDialog;
import ghidra.docking.settings.Settings;
import ghidra.program.model.address.Address;
import ghidra.program.model.address.AddressRange;
import ghidra.program.model.listing.Instruction;
import ghidra.util.table.column.AbstractGColumnRenderer;
import ghidra.util.table.column.GColumnRenderer;

public class TableFail extends GhidraScript {
	TableChooserDialog dlg;
	@Override
	public AnalysisMode getScriptAnalysisMode() {
		return AnalysisMode.DISABLED;
	}
	@Override
	protected void run() throws Exception {
		dlg = createTableChooserDialog("Show Instructions", null);
		configure(dlg);
		dlg.show();
		Iterator<AddressRange> iter = currentSelection.iterator();
		while (iter.hasNext()) {
			AddressRange rng = iter.next();
			process(rng.getMinAddress(), rng.getMaxAddress());
		}
	}
	
	void configure(TableChooserDialog dlg) {

		AddressColumnDisplay maxAddrColumn = new AddressColumnDisplay() {
			@Override
			public String getColumnName() {
				return "Max Addr";
			}
			@Override
			public Address getColumnValue(AddressableRowObject rowObject) {
				if (!(rowObject instanceof TextLabelObject)) {
					return null;
				}
				TextLabelObject entry = (TextLabelObject) rowObject;
				return entry.getMaxAddress();
			}
		};
		AddressColumnDisplay minAddrColumn = new AddressColumnDisplay() {
			@Override
			public String getColumnName() {
				return "Min Addr";
			}

			@Override
			public Address getColumnValue(AddressableRowObject rowObject) {
				if (!(rowObject instanceof TextLabelObject)) {
					return null;
				}
				TextLabelObject entry = (TextLabelObject) rowObject;
				return entry.getMinAddress();
			}
		};

		StringColumnDisplay contentsColumn = new StringColumnDisplay() {

			private GColumnRenderer<String> renderer = new AbstractGColumnRenderer<String>() {
				{
					setHTMLRenderingEnabled(true);
				}
				@Override
				public String getFilterString(String arg0, Settings arg1) {
					return arg0;
				}
				@Override
				public Component getTableCellRendererComponent(GTableCellRenderingData data) {
					JLabel label = (JLabel) super.getTableCellRendererComponent(data);
					Object rowObject = data.getRowObject();
					String content_text = "";
					if (rowObject instanceof TextLabelObject) {
						TextLabelObject entry = (TextLabelObject) rowObject;
						String contents = entry.getContents();
						if (contents != null) {
							content_text = htmlFormatASMString(entry.getColorString(), contents);
						}
					}
					setText(content_text);
					return label;
				}
			};

			@Override
			public String getColumnName() {
				return "Contents";
			}

			@Override
			public String getColumnValue(AddressableRowObject rowObject) {
				TextLabelObject entry = (TextLabelObject) rowObject;
				String contents = entry.getContents();
				if (contents == null) {
					return "";
				}
				return contents;
			}

			@Override
			public GColumnRenderer<String> getRenderer() {
				return renderer;
			}
		};
		dlg.addCustomColumn(minAddrColumn);
		dlg.addCustomColumn(maxAddrColumn);
		dlg.addCustomColumn(contentsColumn);
	}
	
	void process(Address min, Address max) {		
		Instruction instr = getInstructionContaining(min);
		if (instr == null) {
			return;
		}
		TextLabelObject obj = new TextLabelObject(min);
		obj.setContents(instr.toString());
		obj.setMinAddress(min);
		obj.setMaxAddress(max);
		if (min.getOffset() % 2 == 0) {
			obj.setColorString("#008000"); // green
		} else {
			obj.setColorString("#000080"); // blue
		}
		dlg.add(obj);;
	}
	
	class TextLabelObject implements AddressableRowObject {
		private Address addr;
		private Address maxAddress = null;
		private Address minAddress = null;
		private String colorString = null;
		private String contents = null;

		TextLabelObject(Address addr) {
			this.addr = addr;
		}

		@Override
		public Address getAddress() {
			return addr;
		}

		public void setMaxAddress(Address maxAddress) {
			this.maxAddress = maxAddress;
		}

		public void setMinAddress(Address minAddress) {
			this.minAddress = minAddress;
		}

		public Address getMaxAddress() {
			return maxAddress;
		}

		public Address getMinAddress() {
			return minAddress;
		}

		public void setColorString(String colorString) {
			this.colorString = colorString;
		}

		public String getColorString() {
			return colorString;
		}

		public String getContents() {
			return contents;
		}

		public void setContents(String contents) {
			this.contents = contents;
		}
	}
	
	protected String htmlFormatASMString(String colorString, String asm) {
		if (colorString == null) {
			return asm;
		}
		return String.format("<html><span style= color:%s>%s</span></html>", colorString, asm);
	}

	public abstract class AddressColumnDisplay extends AbstractComparableColumnDisplay<Address>{}
}
```

**Comment by dragonmacher** [comment]
Thanks for the script.  Everything in  the script looks correct.   I did some debugging and cannot find any place that is working in the background thread instead of the Swing thread for modifying the dialog.   Maybe a previous version of the script had code that could trigger the issue.

I will close this for now.  If you can make it happen, even sporadically, in a future script, then please post that script here.
