### ISSUE TITLE
error importing file ("Cannot read past EOF")

### ISSUE THREAD

**Issue by shaiku** [NationalSecurityAgency/ghidra#5899]
**Describe the bug**
Importing USB driver files gives Unable to read past EOF: 162540, 4
```
Unable to read past EOF: 162540, 4
java.io.IOException: Unable to read past EOF: 162540, 4
	at ghidra.app.util.bin.FileByteProvider.ensureBounds(FileByteProvider.java:267)
	at ghidra.app.util.bin.FileByteProvider.readBytes(FileByteProvider.java:121)
	at ghidra.formats.gfilesystem.RefdByteProvider.readBytes(RefdByteProvider.java:95)
	at ghidra.app.util.bin.BinaryReader.readInt(BinaryReader.java:923)
	at ghidra.app.util.bin.format.pe.debug.OMFSrcModuleLine.<init>(OMFSrcModuleLine.java:50)
	at ghidra.app.util.bin.format.pe.debug.OMFSrcModuleFile.<init>(OMFSrcModuleFile.java:89)
	at ghidra.app.util.bin.format.pe.debug.OMFSrcModule.<init>(OMFSrcModule.java:81)
	at ghidra.app.util.bin.format.pe.debug.DebugCodeViewSymbolTable.<init>(DebugCodeViewSymbolTable.java:96)
	at ghidra.app.util.bin.format.pe.debug.DebugCodeView.<init>(DebugCodeView.java:58)
	at ghidra.app.util.bin.format.pe.debug.DebugDirectoryParser.<init>(DebugDirectoryParser.java:140)
	at ghidra.app.util.bin.format.pe.DebugDataDirectory.parse(DebugDataDirectory.java:61)
	at ghidra.app.util.bin.format.pe.DataDirectory.processDataDirectory(DataDirectory.java:80)
	at ghidra.app.util.bin.format.pe.DebugDataDirectory.<init>(DebugDataDirectory.java:45)
	at ghidra.app.util.bin.format.pe.OptionalHeaderImpl.processDataDirectories(OptionalHeaderImpl.java:352)
	at ghidra.app.util.opinion.PeLoader.load(PeLoader.java:124)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:845)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:99)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:395)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:336)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

---------------------------------------------------
Build Date: 2023-Sep-28 1301 EDT
Ghidra Version: 10.4
Java Home: C:\Program Files\Eclipse Adoptium\jdk-17.0.8.101-hotspot
JVM Version: Eclipse Adoptium 17.0.8.1
OS: Windows 10 10.0 amd64
```

**To Reproduce**
1. Create a new project
2. Attempt to import file

**Expected behavior**
Successful import without errors

**Attachments**
[Drivers.zip](https://github.com/NationalSecurityAgency/ghidra/files/13059875/Drivers.zip)

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - Java Version: openJDK 17-LTS
 - Ghidra Version: 10.4 public build
 - Ghidra Origin: official GitHub distro

**Comment by ryanmkurtz** [comment]
Thanks, I have a fix for this.
