### ISSUE TITLE
Data Type Manager: Dynamic and Factory data types are not permitted

### ISSUE THREAD

**Issue by bdemick** [NationalSecurityAgency/ghidra#5927]
**Describe the bug**
After importing DWARF info for an ELF binary, attempting to edit/view some of the types in the Data Type Manager results in an uncaught `IllegalArgumentException - Dynamic and Factory data types are not permitted: -BAD-` message. I can export the type to a header file just fine, and it does look like it's being applied appropriately across the database, although it does look like it wasn't completely parsed. I don't see anything specifically in the DWARF analysis logs for this type.

**To Reproduce**
Unfortunately I don't have an example binary I can share to reproduce the issue.

**Expected behavior**
Data Type Manager editor opens and displays the detailed type.

**Environment (please complete the following information):**
 - OS: macOS 13.6
 - Java Version: 17.0.6
 - Ghidra Version: 10.4
 - Ghidra Origin: Official GitHub distro

**Additional context**
```
Dynamic and Factory data types are not permitted: -BAD-
java.lang.IllegalArgumentException: Dynamic and Factory data types are not permitted: -BAD-
	at ghidra.program.model.data.ParameterDefinitionImpl.validateDataType(ParameterDefinitionImpl.java:77)
	at ghidra.program.database.data.FunctionDefinitionDB.setArguments(FunctionDefinitionDB.java:291)
	at ghidra.program.database.data.DataTypeManagerDB.createFunctionDefinition(DataTypeManagerDB.java:3316)
	at ghidra.program.database.data.DataTypeManagerDB.createDataType(DataTypeManagerDB.java:2963)
	at ghidra.program.database.data.DataTypeManagerDB.createDataType(DataTypeManagerDB.java:1686)
	at ghidra.program.database.data.DataTypeManagerDB.resolveNoEquivalentFound(DataTypeManagerDB.java:1645)
	at ghidra.program.database.data.DataTypeManagerDB.resolveDataTypeNoSource(DataTypeManagerDB.java:1574)
	at ghidra.program.database.data.DataTypeManagerDB.resolve(DataTypeManagerDB.java:1245)
	at ghidra.app.plugin.core.compositeeditor.CompositeViewerDataTypeManager.resolve(CompositeViewerDataTypeManager.java:103)
	at ghidra.program.database.data.DataTypeManagerDB.createPointer(DataTypeManagerDB.java:3106)
	at ghidra.program.database.data.DataTypeManagerDB.createDataType(DataTypeManagerDB.java:2943)
	at ghidra.program.database.data.DataTypeManagerDB.createDataType(DataTypeManagerDB.java:1686)
	at ghidra.program.database.data.DataTypeManagerDB.resolveNoEquivalentFound(DataTypeManagerDB.java:1645)
	at ghidra.program.database.data.DataTypeManagerDB.resolveDataTypeNoSource(DataTypeManagerDB.java:1574)
	at ghidra.program.database.data.DataTypeManagerDB.resolve(DataTypeManagerDB.java:1240)
	at ghidra.app.plugin.core.compositeeditor.CompositeViewerDataTypeManager.resolve(CompositeViewerDataTypeManager.java:103)
	at ghidra.program.database.data.DataTypeManagerDB.createTypeDef(DataTypeManagerDB.java:3029)
	at ghidra.program.database.data.DataTypeManagerDB.createDataType(DataTypeManagerDB.java:2954)
	at ghidra.program.database.data.DataTypeManagerDB.createDataType(DataTypeManagerDB.java:1686)
	at ghidra.program.database.data.DataTypeManagerDB.resolveNoEquivalentFound(DataTypeManagerDB.java:1645)
	at ghidra.program.database.data.DataTypeManagerDB.resolveDataTypeNoSource(DataTypeManagerDB.java:1574)
	at ghidra.program.database.data.DataTypeManagerDB.resolve(DataTypeManagerDB.java:1245)
	at ghidra.app.plugin.core.compositeeditor.CompositeViewerDataTypeManager.resolve(CompositeViewerDataTypeManager.java:103)
	at ghidra.program.database.data.DataTypeDB.resolve(DataTypeDB.java:263)
	at ghidra.program.database.data.CompositeDB.doCheckedResolve(CompositeDB.java:338)
	at ghidra.program.database.data.StructureDB.doReplaceWith(StructureDB.java:1610)
	at ghidra.program.database.data.DataTypeManagerDB.createStructure(DataTypeManagerDB.java:3004)
	at ghidra.program.database.data.DataTypeManagerDB.createDataType(DataTypeManagerDB.java:2950)
	at ghidra.program.database.data.DataTypeManagerDB.createDataType(DataTypeManagerDB.java:1686)
	at ghidra.program.database.data.DataTypeManagerDB.resolveNoEquivalentFound(DataTypeManagerDB.java:1645)
	at ghidra.program.database.data.DataTypeManagerDB.resolveDataTypeNoSource(DataTypeManagerDB.java:1574)
	at ghidra.program.database.data.DataTypeManagerDB.resolve(DataTypeManagerDB.java:1245)
	at ghidra.app.plugin.core.compositeeditor.CompositeViewerDataTypeManager.resolve(CompositeViewerDataTypeManager.java:103)
	at ghidra.program.database.data.DataTypeManagerDB.createPointer(DataTypeManagerDB.java:3106)
	at ghidra.program.database.data.DataTypeManagerDB.createDataType(DataTypeManagerDB.java:2943)
	at ghidra.program.database.data.DataTypeManagerDB.createDataType(DataTypeManagerDB.java:1686)
	at ghidra.program.database.data.DataTypeManagerDB.resolveNoEquivalentFound(DataTypeManagerDB.java:1645)
	at ghidra.program.database.data.DataTypeManagerDB.resolveDataTypeNoSource(DataTypeManagerDB.java:1574)
	at ghidra.program.database.data.DataTypeManagerDB.resolve(DataTypeManagerDB.java:1240)
	at ghidra.app.plugin.core.compositeeditor.CompositeViewerDataTypeManager.resolve(CompositeViewerDataTypeManager.java:103)
	at ghidra.program.database.data.CompositeDB.postPointerResolve(CompositeDB.java:698)
	at ghidra.program.database.data.DataTypeManagerDB.flushResolveQueue(DataTypeManagerDB.java:4347)
	at ghidra.program.database.data.DataTypeManagerDB.resolve(DataTypeManagerDB.java:1259)
	at ghidra.app.plugin.core.compositeeditor.CompositeViewerDataTypeManager.<init>(CompositeViewerDataTypeManager.java:62)
	at ghidra.app.plugin.core.compositeeditor.CompositeEditorModel.createViewCompositeFromOriginalComposite(CompositeEditorModel.java:141)
	at ghidra.app.plugin.core.compositeeditor.CompositeEditorModel.load(CompositeEditorModel.java:104)
	at ghidra.app.plugin.core.compositeeditor.CompEditorModel.load(CompEditorModel.java:54)
	at ghidra.app.plugin.core.compositeeditor.StructureEditorModel.load(StructureEditorModel.java:102)
	at ghidra.app.plugin.core.compositeeditor.StructureEditorProvider.<init>(StructureEditorProvider.java:37)
	at ghidra.app.plugin.core.datamgr.editor.DataTypeEditorManager.edit(DataTypeEditorManager.java:123)
	at ghidra.app.plugin.core.datamgr.DataTypesProvider.editNode(DataTypesProvider.java:644)
	at ghidra.app.plugin.core.datamgr.actions.EditAction.actionPerformed(EditAction.java:77)
	at docking.PopupMenuHandler$1.run(PopupMenuHandler.java:63)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by astrelsky** [comment]
I _think_ there is a built-in "bad data type" and that log message might be referencing that. I remember having issues in the past with go's string type being replaced with ghidra's built-in StringDataType and encountering similar problems (which have since been fixed). This could be a similar situation.

**Comment by loverics** [comment]
@dev747368 @ryanmkurtz any more insight on this? Thank you!

**Comment by dev747368** [comment]
@loverics - sorry, slipped off my radar.

Do you get the same error with the binary if you imported a second copy and ran just dwarf analysis on it?  If so, does the same error happen if you use an older ghidra build like 10.1 to import and run dwarf analysis?

I'm assuming the data type you are viewing/editing is a structure, and it appears its trying to do something with the parameters of a function definition data type referenced from a struct.  I'm not sure if you'll be able to track down which field/type is causing the problem, but if you do, you can correlate that type to the DWARF DIE record if you turn on some extra options in ghidra's DWARF analyzer that tag each type with the DIE number in the comment field.

**Comment by loverics** [comment]
@dev747368 I imported the binary into new project in ghidra 10.4 (from brew, also tried official ghidra release) and ran the dwarf analyzer only and got the same exception. I did the same ghidra 10.1.5 (from the ghidra official releases) and there was no exception. The `Structure Editor` opened without any issues.

**Comment by loverics** [comment]
Interestingly ghidra 10.4 reports several DWARFFunctionImporter errors that result in backtraces while ghidra 10.1.5 doesn't report the same issues.

```
2023-11-28 12:18:57 ERROR (DWARFFunctionImporter) Error creating data object at 417fc00cb0ac ghidra.program.model.util.CodeUnitInsertionException: Could not create Data at address 417fc00cb0ac
    at ghidra.program.model.data.DataUtilities.getData(DataUtilities.java:249)
    at ghidra.program.model.data.DataUtilities.createData(DataUtilities.java:164)
    at ghidra.program.model.data.DataUtilities.createData(DataUtilities.java:144)
    at ghidra.app.util.bin.format.dwarf4.next.DWARFFunctionImporter.outputGlobal(DWARFFunctionImporter.java:425)
    at ghidra.app.util.bin.format.dwarf4.next.DWARFFunctionImporter.processSubprogram(DWARFFunctionImporter.java:238)
    at ghidra.app.util.bin.format.dwarf4.next.DWARFFunctionImporter.importFunctions(DWARFFunctionImporter.java:115)
    at ghidra.app.util.bin.format.dwarf4.next.DWARFParser.parse(DWARFParser.java:202)
    at ghidra.app.plugin.core.analysis.DWARFAnalyzer.added(DWARFAnalyzer.java:199)
    at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:186)
    at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
    at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:686)
    at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:786)
    at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:665)
    at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:630)
    at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
    at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
    at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:334)
    at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by loverics** [comment]
Looks like Ghidra 10.4 struggles a bit more with importing DWARF info than ghidra 10.1.5.

ghidra 10.4 

```
2023-11-28 12:21:17 INFO  (DWARFImportSummary) DWARF import - total elapsed: 308144ms
2023-11-28 12:21:17 INFO  (DWARFImportSummary) DWARF data type import - elapsed: 167310ms
2023-11-28 12:21:17 INFO  (DWARFImportSummary) DWARF func & symbol import - elapsed: 19673ms
2023-11-28 12:21:17 INFO  (DWARFImportSummary) DWARF types imported: 17270
2023-11-28 12:21:17 INFO  (DWARFImportSummary) DWARF function signatures added: 26902
2023-11-28 12:21:17 ERROR (DWARFImportSummary) DWARF variable definitions that failed because they depended on the dynamic value of a register: 625
2023-11-28 12:21:17 ERROR (DWARFImportSummary) DWARF variable definitions that failed because they are computed pseudo variables: 23018
2023-11-28 12:21:17 ERROR (DWARFImportSummary) DWARF expression failed to read: 3254
```

ghidra 10.1.5

```
2023-11-28 12:07:56 INFO  (DWARFImportSummary) DWARF import - total elapsed: 352977ms
2023-11-28 12:07:56 INFO  (DWARFImportSummary) DWARF data type import - elapsed: 185290ms
2023-11-28 12:07:56 INFO  (DWARFImportSummary) DWARF func & symbol import - elapsed: 34793ms
2023-11-28 12:07:56 INFO  (DWARFImportSummary) DWARF types imported: 20095
2023-11-28 12:07:56 INFO  (DWARFImportSummary) DWARF function signatures added: 27032
2023-11-28 12:07:56 ERROR (DWARFImportSummary) DWARF variable definitions that failed because they depended on the dynamic value of a register: 348
2023-11-28 12:07:56 ERROR (DWARFImportSummary) DWARF variable definitions that failed because they are computed pseudo variables: 5443
2023-11-28 12:07:56 ERROR (DWARFImportSummary) DWARF expression failed to read: 1064

```

**Comment by dev747368** [comment]
I've got a pretty good idea of part of the problem, which are some funcdefs that have parameters that should be pointers to structs, that themselves have fields that contain these funcdefs.  At some point when ingesting the dwarf data, the data types for the parameters got into a bad state.
As a workaround, I was able to manually edit those funcdef types (20-30'ish) and fix/remove the bad parameter from the prototype, and then was able to open the problematic structure.
Filtering in the DTM tree for the substring "DescriptorInt_ptr" should get you a list funcdefs that have the bad parameter info.  If you turn on the preview pane of the DTM tree, you will be able to quickly see "-BAD-" in the funcdef's parameter list, and then fix each one that has that.

**Comment by loverics** [comment]
thank you @dev747368. I'll have a look.

**Comment by loverics** [comment]
@dev747368 that worked. thank you! Another workaround I found worked is to open the binary in ghidra 10.1.5, do the dwarf analysis, save it and then open the project in ghidra 10.4.

**Comment by loverics** [comment]
Thank you @dev747368 !
