### ISSUE TITLE
how to export function signature

### ISSUE THREAD

**Issue by Zaraxon** [NationalSecurityAgency/ghidra#5944]
Hi. I'd like to export some signatures of functions into a file(using HeadlessAnalyzer), and then use it in another Ghidra project. I hope to export them as json so It would be readable and easy to use anywhere.

I tried something like below, where I tried to directly use Gson to encode members of  FunctionDefinitionDataType:
```
public class SignatureToJson extends HeadlessScript {

    @Override
    public void run() throws Exception {
        Function f = getFunction("_init");
        FunctionSignature fsig = f.getSignature();
        
        println(functionSignatureToJson(fsig));
    }

    private String functionSignatureToJson(FunctionSignature fSig) {
        FunctionDefinitionDataType fDef = new FunctionDefinitionDataType(fSig);
        Map<String, Object> fDefMapping = new HashMap();
        fDefMapping.put("returnType", fDef.getReturnType());
        fDefMapping.put("hasVaArgs", fDef.hasVarArgs());
        fDefMapping.put("callingConvention", fDef.getCallingConvention());
        fDefMapping.put("arguments", fDef.getArguments());

        Gson gson = new Gson();
        String fDefJson = gson.toJson(fDefMapping);

        return fDefJson;
    }
}
```

But I got errors that saying it seems Gson that cannot access a member called `java.lang.ThreadLocal#threadLocalHashCode`:

```
Failed making field 'java.lang.ThreadLocal#threadLocalHashCode' accessible; either change its visibility or write a custom TypeAdapter for its declaring type (HeadlessAnalyzer) com.google.gson.JsonIOException: Failed making field 'java.lang.ThreadLocal#threadLocalHashCode' accessible; either change its visibility or write a custom TypeAdapter for its declaring type
        at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:22)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:158)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:101)
        at com.google.gson.Gson.getAdapter(Gson.java:501)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:116)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:165)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:101)
        at com.google.gson.Gson.getAdapter(Gson.java:501)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:126)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:244)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:95)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
        at com.google.gson.Gson.toJson(Gson.java:747)
        at com.google.gson.Gson.toJson(Gson.java:726)
        at com.google.gson.Gson.toJson(Gson.java:681)
        at com.google.gson.Gson.toJson(Gson.java:661)
        at SignatureToJson.functionSignatureToJson(SignatureToJson.java:35)
        at SignatureToJson.run(SignatureToJson.java:23)
        at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:399)
        at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:254)
        at ghidra.app.script.GhidraScript.execute(GhidraScript.java:232)
        at ghidra.app.util.headless.HeadlessAnalyzer.runScript(HeadlessAnalyzer.java:579)
        at ghidra.app.util.headless.HeadlessAnalyzer.runScriptsList(HeadlessAnalyzer.java:912)
        at ghidra.app.util.headless.HeadlessAnalyzer.analyzeProgram(HeadlessAnalyzer.java:1060)
        at ghidra.app.util.headless.HeadlessAnalyzer.processFileNoImport(HeadlessAnalyzer.java:1151)
        at ghidra.app.util.headless.HeadlessAnalyzer.processFolderNoImport(HeadlessAnalyzer.java:1323)
        at ghidra.app.util.headless.HeadlessAnalyzer.processNoImport(HeadlessAnalyzer.java:1352)
        at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:445)
        at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:127)
        at ghidra.GhidraLauncher.launch(GhidraLauncher.java:77)
        at ghidra.Ghidra.main(Ghidra.java:54)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final int java.lang.ThreadLocal.threadLocalHashCode accessible: module java.base does not "opens java.lang" to unnamed module @68e965f5
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
        at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:19)
        ... 34 more
 
```

Seems like Ghidra is designed not to export its internal data like FunctionDefinitionDataType?
Or did I missed some ways to do this?
Thanks in advance.

**Comment by d-millar** [comment]
@Zaraxon We have code just completed that will do exactly what you are looking to do.   Unfortunately, it is considerably more complicated than one might expect.  Are you under time pressure to complete that particular aspect of your code or could you, perhaps, wait for the next release?

**Comment by Zaraxon** [comment]
> @Zaraxon We have code just completed that will do exactly what you are looking to do. Unfortunately, it is considerably more complicated than one might expect. Are you under time pressure to complete that particular aspect of your code or could you, perhaps, wait for the next release?

Wow so quickly reply. 
I'm not under time pressure, and waiting for a some time (around several weeks) is OK.
And just as you said, I realized that this could be complicated to pass these internal structures among projects or even used in other places :(

By the way, are developers tring to make more data like FunctionDefinitionDataType exportable?

**Comment by d-millar** [comment]
Basically, the entire program will be exportable as SARIF (a Json schema), much as it currently is as XML.  The XMl exporter will give you some idea of the complexities, by the way.
