### ISSUE TITLE
Relocation block for X86_64 GOT is not enough

### ISSUE THREAD

**Issue by davendu** [NationalSecurityAgency/ghidra#5961]
**Describe the bug**

When loading target file, the following error is displayed, resulting in an import error:

```
ghidra.util.exception.AssertException: Unexpected Error: %got does not contain address NO ADDRESS
 at ghidra.app.util.bin.format.elf.relocation.X86_64_ElfRelocationContext.createGot(X86_64_ElfRelocationContext.java:257)
 at ghidra.app.util.bin.format.elf.relocation.X86_64_ElfRelocationContext.dispose(X86_64_ElfRelocationContext.java:265)
 at ghidra.app.util.opinion.ElfProgramBuilder.processRelocations(ElfProgramBuilder.java:890)
 at ghidra.app.util.opinion.ElfProgramBuilder.load(ElfProgramBuilder.java:171)
 at ghidra.app.util.opinion.ElfProgramBuilder.loadElf(ElfProgramBuilder.java:108)
 at ghidra.app.util.opinion.ElfLoader.load(ElfLoader.java:147)
 at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:811)
 at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:100)
 at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
 at ghidra.app.util.importer.AutoImporter.importFresh(AutoImporter.java:502)
 at ghidra.app.util.importer.AutoImporter.importByUsingBestGuess(AutoImporter.java:128)
 // internal stack
```

![image](https://github.com/NationalSecurityAgency/ghidra/assets/58910463/e4689830-5b37-460d-9959-d0ca4731a940)

**To Reproduce**

Load this file: https://www.virustotal.com/gui/file/54493bd487a6b0b2361905bd07bd62cd377df3e1fc90e3ef856fa4228e377a31

**Expected behavior**

The file should load correctly.

**Environment (please complete the following information):**
 - OS: Linux 6.x
 - Java Version: `OpenJDK 64-Bit Server VM (build 21+35, mixed mode)`
 - Ghidra Version: Both 10.3.2 and 10.4
 - Ghidra Origin: Both official & locally build

**Additional context**

The exception is thrown because `getNextAllocatedGotEntryAddress` returns `Address.NO_ADDRESS` after some calls. However, I'm not familiar with Ghidra's design, so I'm unsure whether the root cause is `allocateGot` providing an incorrect size or `getGotEntryAddress` using incorrect index.

**Comment by ghidra1** [comment]
The link only provides virus analysis and not the file itself

**Comment by davendu** [comment]
@ghidra1 Here is the file: [fpcunit.zip](https://github.com/NationalSecurityAgency/ghidra/files/13582210/fpcunit.zip). To retrieve it from a 3rd party source, download & unpack [fp-units-fcl-3.0.4](https://packages.ubuntu.com/focal/fp-units-fcl-3.0.4) and find the file name `fpcunit.o`.
