### ISSUE TITLE
Stack Trace - failure after undo after add spurious parameter to func signature

### ISSUE THREAD

**Issue by YSaxon** [NationalSecurityAgency/ghidra#6018]
```
Cannot run program "/opt/homebrew/Caskroom/ghidra/10.3.1-20230614/ghidra_10.3.1_PUBLIC/Ghidra/Features/Decompiler/build/os/mac_arm_64/decompile": error=316, posix_spawn failed
java.io.IOException: Cannot run program "/opt/homebrew/Caskroom/ghidra/10.3.1-20230614/ghidra_10.3.1_PUBLIC/Ghidra/Features/Decompiler/build/os/mac_arm_64/decompile": error=316, posix_spawn failed
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.lang.Runtime.exec(Runtime.java:594)
	at java.base/java.lang.Runtime.exec(Runtime.java:453)
	at ghidra.app.decompiler.DecompileProcess.setup(DecompileProcess.java:137)
	at ghidra.app.decompiler.DecompileProcess.registerProgram(DecompileProcess.java:433)
	at ghidra.app.decompiler.DecompInterface.initializeProcess(DecompInterface.java:284)
	at ghidra.app.decompiler.DecompInterface.resetDecompiler(DecompInterface.java:844)
	at ghidra.app.decompiler.component.Decompiler.resetDecompiler(Decompiler.java:98)
	at ghidra.app.decompiler.component.DecompilerManager.resetDecompiler(DecompilerManager.java:79)
	at ghidra.app.decompiler.component.DecompilerController.resetDecompiler(DecompilerController.java:167)
	at ghidra.app.plugin.core.decompile.DecompilerProvider.domainObjectChanged(DecompilerProvider.java:299)
	at ghidra.framework.data.DomainObjectChangeSupport$EventNotification.doNotify(DomainObjectChangeSupport.java:297)
	at ghidra.framework.data.DomainObjectChangeSupport.doSendEventsNow(DomainObjectChangeSupport.java:164)
	at ghidra.framework.data.DomainObjectChangeSupport.lambda$sendEventNow$3(DomainObjectChangeSupport.java:158)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.framework.data.DomainObjectChangeSupport.sendEventNow(DomainObjectChangeSupport.java:158)
	at ghidra.framework.data.DomainObjectChangeSupport.flush(DomainObjectChangeSupport.java:134)
	at ghidra.framework.data.DomainObjectAdapter.flushEvents(DomainObjectAdapter.java:220)
	at ghidra.framework.data.DomainObjectDBTransaction$1.run(DomainObjectDBTransaction.java:89)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.io.IOException: error=316, posix_spawn failed
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 34 more

---------------------------------------------------
Build Date: 2023-Jun-14 1629 EDT
Ghidra Version: 10.3.1
Java Home: /opt/homebrew/Cellar/openjdk@17/17.0.8.1/libexec/openjdk.jdk/Contents/Home
JVM Version: Homebrew 17.0.8.1
OS: Mac OS X 13.4.1 aarch64
```

This happened immediately after I hit "undo" after adding a single (probably incorrect) parameter to a function via "edit signature".

**Comment by YSaxon** [comment]
2 is 
```
Cannot run program "/opt/homebrew/Caskroom/ghidra/10.3.1-20230614/ghidra_10.3.1_PUBLIC/Ghidra/Features/Decompiler/build/os/mac_arm_64/decompile": error=0, posix_spawn failed
java.io.IOException: Cannot run program "/opt/homebrew/Caskroom/ghidra/10.3.1-20230614/ghidra_10.3.1_PUBLIC/Ghidra/Features/Decompiler/build/os/mac_arm_64/decompile": error=0, posix_spawn failed
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.lang.Runtime.exec(Runtime.java:594)
	at java.base/java.lang.Runtime.exec(Runtime.java:453)
	at ghidra.app.decompiler.DecompileProcess.setup(DecompileProcess.java:137)
	at ghidra.app.decompiler.DecompileProcess.registerProgram(DecompileProcess.java:433)
	at ghidra.app.decompiler.DecompInterface.initializeProcess(DecompInterface.java:284)
	at ghidra.app.decompiler.DecompInterface.verifyProcess(DecompInterface.java:337)
	at ghidra.app.decompiler.DecompInterface.setOptions(DecompInterface.java:658)
	at ghidra.app.decompiler.component.Decompiler.decompile(Decompiler.java:54)
	at ghidra.app.decompiler.component.DecompilerManager.decompile(DecompilerManager.java:175)
	at ghidra.app.decompiler.component.DecompileRunnable.monitoredRun(DecompileRunnable.java:108)
	at ghidra.util.task.RunManager$RunnerJob.doExecute(RunManager.java:334)
	at ghidra.util.task.RunManager$RunnerJob.run(RunManager.java:309)
	at ghidra.util.worker.AbstractWorker$JobCallback.process(AbstractWorker.java:133)
	at ghidra.util.worker.AbstractWorker$JobCallback.process(AbstractWorker.java:123)
	at generic.concurrent.ConcurrentQ$CallbackCallable.call(ConcurrentQ.java:658)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: error=0, posix_spawn failed
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 21 more

---------------------------------------------------
Build Date: 2023-Jun-14 1629 EDT
Ghidra Version: 10.3.1
Java Home: /opt/homebrew/Cellar/openjdk@17/17.0.8.1/libexec/openjdk.jdk/Contents/Home
JVM Version: Homebrew 17.0.8.1
OS: Mac OS X 13.4.1 aarch64
```

3 is 
```
Cannot run program "/opt/homebrew/Caskroom/ghidra/10.3.1-20230614/ghidra_10.3.1_PUBLIC/Ghidra/Features/Decompiler/build/os/mac_arm_64/decompile": error=0, posix_spawn failed
java.io.IOException: Cannot run program "/opt/homebrew/Caskroom/ghidra/10.3.1-20230614/ghidra_10.3.1_PUBLIC/Ghidra/Features/Decompiler/build/os/mac_arm_64/decompile": error=0, posix_spawn failed
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.lang.Runtime.exec(Runtime.java:594)
	at java.base/java.lang.Runtime.exec(Runtime.java:453)
	at ghidra.app.decompiler.DecompileProcess.setup(DecompileProcess.java:137)
	at ghidra.app.decompiler.DecompileProcess.registerProgram(DecompileProcess.java:433)
	at ghidra.app.decompiler.DecompInterface.initializeProcess(DecompInterface.java:284)
	at ghidra.app.decompiler.DecompInterface.verifyProcess(DecompInterface.java:337)
	at ghidra.app.decompiler.DecompInterface.decompileFunction(DecompInterface.java:781)
	at ghidra.app.decompiler.component.Decompiler.decompile(Decompiler.java:57)
	at ghidra.app.decompiler.component.DecompilerManager.decompile(DecompilerManager.java:175)
	at ghidra.app.decompiler.component.DecompileRunnable.monitoredRun(DecompileRunnable.java:108)
	at ghidra.util.task.RunManager$RunnerJob.doExecute(RunManager.java:334)
	at ghidra.util.task.RunManager$RunnerJob.run(RunManager.java:309)
	at ghidra.util.worker.AbstractWorker$JobCallback.process(AbstractWorker.java:133)
	at ghidra.util.worker.AbstractWorker$JobCallback.process(AbstractWorker.java:123)
	at generic.concurrent.ConcurrentQ$CallbackCallable.call(ConcurrentQ.java:658)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: error=0, posix_spawn failed
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 21 more

---------------------------------------------------
Build Date: 2023-Jun-14 1629 EDT
Ghidra Version: 10.3.1
Java Home: /opt/homebrew/Cellar/openjdk@17/17.0.8.1/libexec/openjdk.jdk/Contents/Home
JVM Version: Homebrew 17.0.8.1
OS: Mac OS X 13.4.1 aarch64
```


They also say Please report to Ghidra team

**Comment by YSaxon** [comment]
![Screenshot 2023-12-11 at 4 08 45 PM](https://github.com/NationalSecurityAgency/ghidra/assets/11711101/1a355d0e-5366-4516-9269-a245993b7ab1)

**Comment by ryanmkurtz** [comment]
Is `/opt/homebrew/Caskroom/ghidra/10.3.1-20230614/ghidra_10.3.1_PUBLIC/Ghidra/Features/Decompiler/build/os/mac_arm_64/decompile` present on your system?  Gatekeeper may have quarantined it.  

If so, the simplest solution to this is to build Ghidra's native components yourself by running the `support/buildNatives` script.  This assumes you have either XCode of the command line developer tools installed.  You will also need a Gradle 7.3+ on your PATH.

If you don't want to build the natives, you can poke around in your Settings -> Privacy & Security settings to allow the unsigned decompile binary to run.

**Comment by YSaxon** [comment]
Hi, sorry I missed your response initially. Yes the binaries were present and presumably not quarantined as I was using Ghidra fine before and after this bug arose. That said, I'm fine with closing if there isn't enough data upon which to reproduce or investigate. Whatever the bug was, it resolved itself upon restarting and it hasn't recurred since then.
