### ISSUE TITLE
"Index 0 out of bounds for length 0" error

### ISSUE THREAD

**Issue by alexdevsec** [NationalSecurityAgency/ghidra#6047]
**Describe the bug**
Analysis crashes with a Java error anytime analysis is being done.

**To Reproduce**
Steps to reproduce the behavior:.
1. Load the Ghidra program. This is a large M1 binary, previously analyzed in Ghidra 10.x.
1. Analyze->One Shot->Variadic Function Symbol Override
2. It doesn't proceed
3. In the Ghidra User Log, notice the stack trace (below)

**Expected behavior**
It should proceed!

**Screenshots**

Here's the error I get: 
```
Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at ghidra.program.model.lang.protorules.HomogeneousAggregate.filter(HomogeneousAggregate.java:74)
	at ghidra.program.model.lang.protorules.ModelRule.assignAddress(ModelRule.java:162)
	at ghidra.program.model.lang.ParamListStandard.assignAddress(ParamListStandard.java:134)
	at ghidra.program.model.lang.ParamListStandard.assignMap(ParamListStandard.java:181)
	at ghidra.program.model.lang.PrototypeModel.assignParameterStorage(PrototypeModel.java:319)
	at ghidra.program.model.lang.PrototypeModel.getStorageLocations(PrototypeModel.java:363)
	at ghidra.program.database.function.FunctionDB.updateParametersAndReturn(FunctionDB.java:830)
	at ghidra.program.database.function.FunctionDB.loadVariables(FunctionDB.java:723)
	at ghidra.program.database.function.FunctionDB.getParameterCount(FunctionDB.java:1211)
	at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer.usesVariadicFormatString(FormatStringAnalyzer.java:231)
	at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer.run(FormatStringAnalyzer.java:127)
	at ghidra.app.plugin.core.string.variadic.FormatStringAnalyzer.added(FormatStringAnalyzer.java:91)
	at ghidra.app.plugin.core.analysis.OneShotAnalysisCommand.applyTo(OneShotAnalysisCommand.java:48)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:686)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:786)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:665)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:630)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:103)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:334)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Attachments**
If applicable, please attach any files that caused problems or log files generated by the software.

**Environment (please complete the following information):**

---------------------------------------------------
Build Date: 2023-Dec-22 0936 EST
Ghidra Version: 11.0 (from download)
Java Home: /opt/homebrew/Cellar/openjdk/18.0.1.1/libexec/openjdk.jdk/Contents/Home
JVM Version: Homebrew 18.0.1.1
OS: Mac OS X 13.2.1 aarch64

 
**Additional context**

**Comment by ghidracadabra** [comment]
Thank you for reporting this.  I'm getting a similar stack trace during initial analysis of the aarch64 ``sleigh`` executable included with Ghidra.   My suspicion is that it's not directly related to the Variadic analyzer and that you would see a similar stack trace if you did a fresh analysis on a new import of your executable.  We'll take a closer look.

**Comment by alexdevsec** [comment]
I agree it's probably not related to variadic analyzer, it's just what I could easily use to reproduce it. I'd seen it when performing other operations, I just couldn't narrow it down.

**Comment by twokilohertz** [comment]
Experiencing the same issue when analysing an arm64-v8a binary. Analysis finishes and the exception is thrown. If I attempt to expand the symbol tree (expanding the exports causes it to happen reproducibly for me) the exception is thrown again. Symbol tree is unusable.
