### ISSUE TITLE
Increase font by one in Configure Theme dialog throws NPE

### ISSUE THREAD

**Issue by xiaoyinl** [NationalSecurityAgency/ghidra#6048]
**Describe the bug**
Click: Edit -> Theme -> Configure. Then click the first icon "Increases all font sizes by 1". An uncaught exception shows up.

```
Cannot invoke "javax.help.JHelpTOCNavigator.getModel()" because "this.toc" is null
java.lang.NullPointerException: Cannot invoke "javax.help.JHelpTOCNavigator.getModel()" because "this.toc" is null
	at javax.help.plaf.basic.BasicTOCNavigatorUI.presentData(BasicTOCNavigatorUI.java:244)
	at javax.help.plaf.basic.BasicTOCNavigatorUI.access$100(BasicTOCNavigatorUI.java:75)
	at javax.help.plaf.basic.BasicTOCNavigatorUI$NavSwingWorker.finished(BasicTOCNavigatorUI.java:267)
	at com.sun.java.help.impl.SwingWorker$1.run(SwingWorker.java:133)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2023-Dec-23 1040 UTC
Ghidra Version: 11.1
Java Home: C:\Program Files\Microsoft\jdk-17.0.6.10-hotspot
JVM Version: Microsoft 17.0.6
OS: Windows 11 10.0 amd64
```

**Screenshots**
<img width="809" alt="increase font size npe" src="https://github.com/NationalSecurityAgency/ghidra/assets/16713498/048f3448-87c7-4670-a159-fb8570d49f10">

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: 17.0.9
 - Ghidra Version: 11.1-DEV  f7013bdfab8eac54387a49ed290444da9af88499
 - Ghidra Origin: locally built

**Comment by ryanmkurtz** [comment]
I am not reproducing this.  Is there a way you can reliably get it back to the "first time" state so you can force the exception?

**Comment by ryanmkurtz** [comment]
Thanks, I was able to reproduce it.  I was trying it from Eclipse dev mode but when I made a local build I saw the exception.

**Comment by dragonmacher** [comment]
This is a known issue.   If you have ever opened the help window before altering themes, you are likely to get this exception, even if the help window has been closed.

We have no fix currently.

**Comment by dragonmacher** [comment]
My statement was not very clear.   The exception happens if the help window has been opened in a given instance of Ghidra.   If you shut down Ghidra, restart Ghidra and then edit the theme (all without opening the help), you will not get the exception.   Also, while annoying, the exception is not critical, in terms of impeding Ghidra functionality.

The exception is manifesting from a sun API that we cannot change.   To fix the issue would require a yet unknown workaround somewhere in our code.
