### ISSUE TITLE
Version tracker: Exception when clicking "Version Tracking Matches for Source" entries

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#6062]
**Describe the bug**
An exception with the following stack trace is thrown:

```
Index 1 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at docking.widgets.table.GDynamicColumnTableModel.getColumn(GDynamicColumnTableModel.java:513)
	at docking.widgets.table.GDynamicColumnTableModel.createSortComparatorForColumn(GDynamicColumnTableModel.java:210)
	at docking.widgets.table.threaded.ThreadedTableModel.createSortComparator(ThreadedTableModel.java:330)
	at ghidra.feature.vt.gui.provider.onetomany.VTMatchOneToManyTableModel.createSortComparator(VTMatchOneToManyTableModel.java:39)
	at ghidra.feature.vt.gui.provider.onetomany.VTMatchSourceTableModel.createSortComparator(VTMatchSourceTableModel.java:121)
	at docking.widgets.table.AbstractSortedTableModel.getComparator(AbstractSortedTableModel.java:428)
	at docking.widgets.table.AbstractSortedTableModel.getComparatorChain(AbstractSortedTableModel.java:412)
	at docking.widgets.table.AbstractSortedTableModel.getIndexForRowObject(AbstractSortedTableModel.java:300)
	at docking.widgets.table.AbstractSortedTableModel.getIndexForRowObject(AbstractSortedTableModel.java:287)
	at docking.widgets.table.AbstractSortedTableModel.getRowIndex(AbstractSortedTableModel.java:107)
	at ghidra.feature.vt.gui.provider.onetomany.VTMatchOneToManyTableProvider.setSelectedMatch(VTMatchOneToManyTableProvider.java:239)
	at ghidra.feature.vt.gui.plugin.VTSubToolManager.setMatch(VTSubToolManager.java:436)
	at ghidra.feature.vt.gui.provider.onetomany.VTMatchOneToManyTableProvider$1.valueChanged(VTMatchOneToManyTableProvider.java:200)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at docking.widgets.table.RowObjectSelectionManager.superFireValueChanged(RowObjectSelectionManager.java:189)
	at docking.widgets.table.RowObjectSelectionManager.fireValueChanged(RowObjectSelectionManager.java:175)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:191)
	at java.desktop/javax.swing.DefaultListSelectionModel.setValueIsAdjusting(DefaultListSelectionModel.java:728)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.setValueIsAdjusting(BasicTableUI.java:992)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(BasicTableUI.java:1205)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**To Reproduce**
Clicking any entry after going to data/function in the Version Tracking Matches for Source/Destination table will trigger the exception

**Screenshots**
![image](https://github.com/NationalSecurityAgency/ghidra/assets/55233728/81b494bc-ac4a-4e87-9825-e887384f1e98)

**Environment (please complete the following information):**
0de3f53c

**Comment by sad-dev** [comment]
As per #6067 after switching back to the default tool, I have been unable to reproduce this bug; am fine with closing this if no obvious cause is found.
