### ISSUE TITLE
Version Tracker: Exception when re-opening session

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#6067]
**Describe the bug**

A stack with the following exception is thrown:
```
Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.openProgramLocations(ProgramManagerPlugin.java:678)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.openPrograms(ProgramManagerPlugin.java:660)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.acceptData(ProgramManagerPlugin.java:158)
	at ghidra.framework.plugintool.PluginManager.acceptData(PluginManager.java:75)
	at ghidra.framework.plugintool.PluginTool.acceptDomainFiles(PluginTool.java:466)
	at ghidra.framework.project.tool.ToolServicesImpl.lambda$launchTool$3(ToolServicesImpl.java:241)
	at ghidra.framework.project.tool.ToolServicesImpl.defaultLaunch(ToolServicesImpl.java:216)
	at ghidra.framework.project.tool.ToolServicesImpl.launchTool(ToolServicesImpl.java:237)
	at ghidra.framework.main.ToolButton.openDomainFiles(ToolButton.java:564)
	at ghidra.framework.main.ToolButton$2.end(ToolButton.java:541)
	at ghidra.framework.main.ZoomImageRunner$1.end(ZoomImageRunner.java:54)
	at org.jdesktop.animation.timing.Animator.end(Animator.java:755)
	at org.jdesktop.animation.timing.Animator.stop(Animator.java:660)
	at org.jdesktop.animation.timing.Animator.timingEvent(Animator.java:732)
	at org.jdesktop.animation.timing.Animator.access$200(Animator.java:75)
	at org.jdesktop.animation.timing.Animator$TimerTarget.actionPerformed(Animator.java:1041)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**To Reproduce**
1.) Create a VT session, run some correlators, and accept matches
2.) Close and re-open by double clicking

Mitigation: Opening the Version Tracking tool and *then* clicking Open Session doesn't seem to produce this exception

**Screenshots**
![image](https://github.com/NationalSecurityAgency/ghidra/assets/55233728/a0572a96-6939-4593-af75-a69c7474cd48)

Noticed further, possibly related errors

![image](https://github.com/NationalSecurityAgency/ghidra/assets/55233728/3fe26e15-fa68-4fbe-938c-1350e4d36fbe)

**Environment (please complete the following information):**
0de3f53c

I have the BSIMElastic, MachineLearning plugins installed.

**Comment by ghidragon** [comment]
I can't reproduce your error. It seems like your Ghidra install is in a bad state. Those error messages related to extensions  are troubling. Never seen anything like that before.  I can put in a simple fix to prevent that stack trace where it assumes a tool is opening a valid file type, but I don't see anyway to actually make it happen.  Can you delete all your tools and re-import the default tools and try the scenario from scratch. The only way I've come close to repeating your issue is to delete the version tracking tool and rename the code browser tool to "Version Tracking". That confuses the tool to try and open the version tracking session as if it were a program. But I doubt you did anything like that.

**Comment by ghidra1** [comment]
FYI - BSimElasticPlugin is not a Ghidra Plugin and simply provides a plugin to be installed with an Elasticsearch server.  Its name can certainly imply otherwise.

**Comment by dragonmacher** [comment]
Regarding the extension errors shown in the log, this is happening during extension loading when we check the `ApplicationLayout.getExtensionArchiveDir()` for zip files that contain extensions.      Presumably, you have zip files in this directory.  It seems that these zip files may have duplicate extensions.

If you are interested, you can debug this section of code to see which zip files contain the extensions being discovered, `ExtensionUtils.getArchiveExtensions()`, stepping into the all to `findExtensionsInZips(archiveFiles, results)`:

```java
        public static Set<ExtensionDetails> getArchiveExtensions() {

		log.trace("Finding archived extensions");

		ApplicationLayout layout = Application.getApplicationLayout();
		ResourceFile archiveDir = layout.getExtensionArchiveDir();
		if (archiveDir == null) {
			log.trace("No extension archive dir found");
			return Collections.emptySet();
		}

		ResourceFile[] archiveFiles = archiveDir.listFiles();
		if (archiveFiles == null) {
			log.trace("No files in extension archive dir: " + archiveDir);
			return Collections.emptySet(); // no files or dirs inside of the archive directory
		}

		Set<ExtensionDetails> results = new HashSet<>();
		findExtensionsInZips(archiveFiles, results);
		findExtensionsInFolder(archiveDir.getFile(false), results);

		return results;
	}
```

This should not be causing the stack trace you show above, but does suggest an odd environment.

**Comment by ghidra1** [comment]
The BSimElastPlugin provides an indexing plugin for the Elastsearch server and is not a "Ghidra plugin".  Installing the extension simply provides access to the code which can be installed on your server.

**Comment by sad-dev** [comment]
After deleting the tool and re-importing the default, I have not been able to replicate the exception. It happened after I switched from 10.4 to 11.1_DEV, so it might have been something that did not quite carry over from my old (custom) tools/plugins

@dragonmacher It appears that the Extensions/Ghidra in my build has a lot of uncleared junk, which are triggering the errors:

![image](https://github.com/NationalSecurityAgency/ghidra/assets/55233728/a1a0cf14-f556-4367-93d3-1c915a35fa19)

I am fine with closing the issue/renaming to reflect the extension problem, since the original exception seems to only occur rarely

**Comment by ryanmkurtz** [comment]
@sad-dev It looks like when you are building, you are unzipping the resulting file overtop of the previous installation, resulting in the old extension zip files.  If so, you should be deleting `build/dist` from build to build.

**Comment by dragonmacher** [comment]
I think there is probably a better way for us to handle extension collisions.   For now, the code is doing what is intended, which is to report the situation.   Considering that, I will close this for now, with the understanding that this can be improved in the future.

**Comment by sad-dev** [comment]
> @sad-dev It looks like when you are building, you are unzipping the resulting file overtop of the previous installation, resulting in the old extension zip files. If so, you should be deleting `build/dist` from build to build.

I always assumed that since the unzipped installation was deleted during ``gradle buildGhidra``, I wouldn't need to clear it. Apparently extensions carry over, but no big deal since its easy to deal with. Perhaps add a more verbose error message e.g.

```
if (results.contains(extension)) {
	log.error("Error in handling archive file \"" + file.getAbsolutePath() + "\""); // This
	log.error("Skipping extension \"" + extension.getName() + "\" found at " +
		extension.getInstallPath() +
		".\nArchived extension by that name already found.");
}
```
