### ISSUE TITLE
IndexOutOfBoundException when expanding symbol tree after newest update

### ISSUE THREAD

**Issue by POGnator** [NationalSecurityAgency/ghidra#6068]
**Describe the bug**
When wanting to expand member "Exports" of the symbol tree tab, ghidra throws an Uncaught exception. This also happens when using "Filter".

**To Reproduce**
1. open any executable in CodeBrowser
2. In symbol tree, click on "export"
3. see error

**Expected behavior**
Expand and show exports

**Screenshots**

**Attachments**
Log created by ghidra:
```
Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at ghidra.program.model.lang.protorules.HomogeneousAggregate.filter(HomogeneousAggregate.java:74)
	at ghidra.program.model.lang.protorules.ModelRule.assignAddress(ModelRule.java:162)
	at ghidra.program.model.lang.ParamListStandard.assignAddress(ParamListStandard.java:134)
	at ghidra.program.model.lang.ParamListStandard.assignMap(ParamListStandard.java:181)
	at ghidra.program.model.lang.PrototypeModel.assignParameterStorage(PrototypeModel.java:319)
	at ghidra.program.model.lang.PrototypeModel.getStorageLocations(PrototypeModel.java:363)
	at ghidra.program.database.function.FunctionDB.updateParametersAndReturn(FunctionDB.java:830)
	at ghidra.program.database.function.FunctionDB.loadVariables(FunctionDB.java:723)
	at ghidra.program.database.function.FunctionDB.getReturn(FunctionDB.java:375)
	at ghidra.program.database.function.FunctionDB.getReturnType(FunctionDB.java:364)
	at ghidra.app.util.ToolTipUtils.getFunctionSignaturePreview(ToolTipUtils.java:290)
	at ghidra.app.util.ToolTipUtils.getToolTipText(ToolTipUtils.java:202)
	at ghidra.app.plugin.core.symboltree.nodes.FunctionSymbolNode.createTooltip(FunctionSymbolNode.java:80)
	at ghidra.app.plugin.core.symboltree.nodes.FunctionSymbolNode.getToolTip(FunctionSymbolNode.java:68)
	at docking.widgets.tree.support.GTreeRenderer.getTreeCellRendererComponent(GTreeRenderer.java:73)
	at ghidra.app.plugin.core.symboltree.SymbolGTree$SymbolTreeCellRenderer.getTreeCellRendererComponent(SymbolGTree.java:80)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:3220)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:497)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1465)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.treeStructureChanged(VariableHeightLayoutCache.java:651)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.treeStructureChanged(BasicTreeUI.java:4404)
	at docking.widgets.tree.internal.GTreeModel.fireNodeStructureChanged(GTreeModel.java:147)
	at docking.widgets.tree.CoreGTreeNode.doFireNodeStructureChanged(CoreGTreeNode.java:367)
	at docking.widgets.tree.CoreGTreeNode.doSetChildrenAndFireEvent(CoreGTreeNode.java:151)
	at docking.widgets.tree.GTreeNode.lambda$setChildren$5(GTreeNode.java:313)
	at ghidra.util.Swing.lambda$runNow$2(Swing.java:227)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2023-Dec-23 1133 UTC
Ghidra Version: 11.0
Java Home: /usr/lib/jvm/java-21-openjdk
JVM Version: N/A 21
OS: Linux 6.6.8-arch1-1 amd64
```

**Environment (please complete the following information):**
 - OS: Arch Linux (Hyprland)
 - Java Version: "21" 2023-09-19
 - Ghidra Version: 11.0
 - Ghidra Origin: Arch repository 

**Additional context**
I have an extension for a dark theme and one to support switch binaries if that matters

**Comment by ryanmkurtz** [comment]
I am not reproducing this.  Can you try it again with the same binary on a clean installation of Ghidra 11.0 (no installed extensions)?

**Comment by ryanmkurtz** [comment]
Likely duplicate of #6047
