### ISSUE TITLE
ARM64 PcodeExecutionException for ExclusiveMonitorPass

### ISSUE THREAD

**Issue by TheDauntless** [NationalSecurityAgency/ghidra#6089]
**Describe the bug**
When using the Emulator for ARM64, it throws an error when executing an STLRX instruction (ExclusiveMonitorPass). It is not possible to continue the trace.

**To Reproduce**
1. Start an Emulator for the attached file
2. Start trace on `0x001018c0`
3. Continue until `0x001017c4`
4. See error below

```
Sleigh userop 'ExclusiveMonitorPass' is not in the library ghidra.pcode.exec.ComposedPcodeUseropLibrary@410e17f1
ghidra.pcode.exec.PcodeExecutionException: Sleigh userop 'ExclusiveMonitorPass' is not in the library ghidra.pcode.exec.ComposedPcodeUseropLibrary@410e17f1
	at ghidra.pcode.exec.PcodeExecutor.step(PcodeExecutor.java:275)
	at ghidra.pcode.exec.PcodeExecutor.finish(PcodeExecutor.java:178)
	at ghidra.pcode.exec.PcodeExecutor.execute(PcodeExecutor.java:160)
	at ghidra.pcode.exec.PcodeExecutor.execute(PcodeExecutor.java:135)
	at ghidra.pcode.emu.DefaultPcodeThread.executeInstruction(DefaultPcodeThread.java:584)
	at ghidra.pcode.emu.DefaultPcodeThread.stepInstruction(DefaultPcodeThread.java:415)
	at ghidra.trace.model.time.schedule.Stepper$Enum$1.tick(Stepper.java:25)
	at ghidra.trace.model.time.schedule.TickStep.execute(TickStep.java:74)
	at ghidra.trace.model.time.schedule.Step.execute(Step.java:182)
	at ghidra.trace.model.time.schedule.Sequence.execute(Sequence.java:392)
	at ghidra.trace.model.time.schedule.TraceSchedule.execute(TraceSchedule.java:352)
	at ghidra.app.plugin.core.debug.service.emulation.DebuggerEmulationServicePlugin.doEmulateFromCached(DebuggerEmulationServicePlugin.java:734)
	at ghidra.app.plugin.core.debug.service.emulation.DebuggerEmulationServicePlugin.doEmulate(DebuggerEmulationServicePlugin.java:771)
	at ghidra.app.plugin.core.debug.service.emulation.DebuggerEmulationServicePlugin$EmulateTask.compute(DebuggerEmulationServicePlugin.java:262)
	at ghidra.app.plugin.core.debug.service.emulation.DebuggerEmulationServicePlugin$EmulateTask.compute(DebuggerEmulationServicePlugin.java:252)
	at ghidra.app.plugin.core.debug.service.emulation.DebuggerEmulationServicePlugin$AbstractEmulateTask.run(DebuggerEmulationServicePlugin.java:239)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: ghidra.pcode.exec.SleighLinkException: Sleigh userop 'ExclusiveMonitorPass' is not in the library ghidra.pcode.exec.ComposedPcodeUseropLibrary@410e17f1
	at ghidra.pcode.exec.PcodeExecutor.onMissingUseropDef(PcodeExecutor.java:578)
	at ghidra.pcode.emu.DefaultPcodeThread$PcodeThreadExecutor.onMissingUseropDef(DefaultPcodeThread.java:203)
	at ghidra.pcode.exec.PcodeExecutor.executeCallother(PcodeExecutor.java:562)
	at ghidra.pcode.exec.PcodeExecutor.stepOp(PcodeExecutor.java:249)
	at ghidra.pcode.emu.DefaultPcodeThread$PcodeThreadExecutor.stepOp(DefaultPcodeThread.java:180)
	at ghidra.pcode.exec.PcodeExecutor.step(PcodeExecutor.java:268)
	... 20 more

---------------------------------------------------

```
The assembly code:
```
        001017c0 61 00 00 54     b.ne       LAB_001017cc
        001017c4 6c fd 0a 88     stlxr      w10,w12,[x11]
        001017c8 8a ff ff 35     cbnz       w10,LAB_001017b8
```

**Expected behavior**
No error

**Attachments**
A very basic file that contains a main method that calls xorString which uses the atomic operations:
[a.out.zip](https://github.com/NationalSecurityAgency/ghidra/files/13853144/a.out.zip)

**Environment:**
Build Date: 2023-Dec-22 0936 EST
Ghidra Version: 11.0 (Same issue on 10.4)
Java Home: /Library/Java/JavaVirtualMachines/temurin-20.jdk/Contents/Home
JVM Version: Eclipse Adoptium 20.0.1
OS: Mac OS X 14.1 aarch64
Obtained from github releases

**Comment by nsadeveloper789** [comment]
This is the intended behavior. You'll need to provide an implementation of that p-code userop in a custom emulator, and then provide that emulator to the EmulationService. It's a small burden, but pretty straightforward with a Ghidra script in Java. See the Modeling section of Debugger Tutorial:

https://github.com/NationalSecurityAgency/ghidra/blob/master/GhidraDocs/GhidraClass/Debugger/B4-Modeling.md

In your case, the method would be named `ExclusiveMonitorPass`, e.g.:

(untested gist)
```java
public class ActivateMyCustomARM64EmulatorScript extends GhidraScript implements FlatDebuggerAPI {
    public static class MyARM64UseropLibrary extends AnnotatedPcodeUseropLibrary<byte[]> {
        @PcodeUserop
        public void ExclusiveMonitorPass(@OpState PcodeExecutorState<byte[]> state) {
            // TODO: Your logic, which I suppose could be NOP
        }
    }
    public static class MyCustomARM64Emulator extends BytesDebuggerPcodeEmulator {
        // constructor boilerplate, etc.
        @Override
        protected PcodeUseropLibrary<byte[]> createUseropLibrary() {
            return super.createUseropLibrary().compose(new MyARM64UseropLibrary(....));
        }
    }
    @Override
    protected void run() throws Exception {
        getEmulationService().setEmulatorFactory(new MyCustomARM64Emulator(...));
    }
}
```

Honestly, if you want to get into the business of implementing p-code userops, I cannot overemphasize reading the Modeling part of the Debugger Tutorial. If you build out a nice library for ARM64, we might be interested in your contribution.
