### ISSUE TITLE
Loading a PE dll with an MZ header

### ISSUE THREAD

**Issue by Wall-AF** [NationalSecurityAgency/ghidra#6093]
How can this be done???

**Comment by Wall-AF** [comment]
If I open the file using the option "Raw Binary" ("Old-style DOS Executable (MZ)" doesn't load much of it!) and perform "Auto Analysis" on it, Ghidra recognises the first 0x80 bytes as a `IMAGE_DOS_HEADER`, but then shows an error related to `ghidra.app.util.bin.format.pe.NTHeader.getName(NTHeader.java:89)` and totally misses the fact that the next 0xe0 bytes represent an `IMAGE_OPTIONAL_HEADER` structure (which is a `PE` header).  Below shows those bytes after manually setting the datatype at byte 0x80 to `IMAGE_OPTIONAL_HEADER`
```
                             //
                             // ram 
                             // ram:00000000-ram:00006fff
                             //
             assume DF = 0x0  (Default)
    00000000 4d 5a 00                   IMAGE_DOS_HEADER
             00 02 00 
             00 00 04 
           00000000 4d 5a           char[2]   "MZ"                    e_magic       Magic number
           00000002 00 00           dw        0h                      e_cblp        Bytes of last page
           00000004 02 00           dw        2h                      e_cp          Pages in file
           00000006 00 00           dw        0h                      e_crlc        Relocations
           00000008 04 00           dw        4h                      e_cparhdr     Size of header in 
           0000000a 00 00           dw        0h                      e_minalloc    Minimum extra para
           0000000c ff ff           dw        FFFFh                   e_maxalloc    Maximum extra para
           0000000e 00 00           dw        0h                      e_ss          Initial (relative)
           00000010 b8 00           dw        B8h                     e_sp          Initial SP value
           00000012 00 00           dw        0h                      e_csum        Checksum
           00000014 00 00           dw        0h                      e_ip          Initial IP value
           00000016 00 00           dw        0h                      e_cs          Initial (relative)
           00000018 40 00           dw        40h                     e_lfarlc      File address of re
           0000001a 00 00           dw        0h                      e_ovno        Overlay number
           0000001c 00 00 00 00 00  dw[4]                             e_res[4]      Reserved words
                    00 00 00
           00000024 00 00           dw        0h                      e_oemid       OEM identifier (fo
           00000026 00 00           dw        0h                      e_oeminfo     OEM information; e
           00000028 00 00 00 00 00  dw[10]                            e_res2[10]    Reserved words
                    00 00 00 00 00 
                    00 00 00 00 00
           0000003c 80 00 00 00     ddw       80h                     e_lfanew      File address of ne
           00000040 0e 1f ba 0e 00  db[64]                            e_program     Actual DOS program
                    b4 09 cd 21 b8 
                    01 4c cd 21 54
    00000080 50 45 00                   IMAGE_OPTIONAL_HEADER
             00 4c 01 
             05 00 14 
           00000080 50 45           char[2]   "PE"                    Magic
           00000082 00              db        0h                      MajorLinkerV
           00000083 00              db        0h                      MinorLinkerV
           00000084 4c 01 05 00     ULONG     5014Ch                  SizeOfCode
           00000088 14 7d 4d 2c     ULONG     2C4D7D14h               SizeOfInitia
           0000008c 00 00 00 00     ULONG     0h                      SizeOfUninit
           00000090 00 00 00 00     ULONG     0h                      AddressOfEnt
           00000094 a8 00 02 20     ULONG     200200A8h               BaseOfCode
           00000098 00 00 02 02     ULONG     2020000h                BaseOfData
           0000009c 00 00 00 00     ULONG     0h                      ImageBase
           000000a0 00 00 00 00     ULONG     0h                      SectionAlign
           000000a4 00 00 00 00     ULONG     0h                      FileAlignment
           000000a8 44 37           USHORT    3744h                   MajorOperati
           000000aa 00 00           USHORT    0h                      MinorOperati
           000000ac 00 00           USHORT    0h                      MajorImageVe
           000000ae 00 00           USHORT    0h                      MinorImageVe
           000000b0 00 00           USHORT    0h                      MajorSubsyst
           000000b2 00 00           USHORT    0h                      MinorSubsyst
           000000b4 00 00 01 00     ULONG     10000h                  Reserved1
           000000b8 00 10 00 00     ULONG     1000h                   SizeOfImage
           000000bc 00 02 00 00     ULONG     200h                    SizeOfHeaders
           000000c0 00 00 00 00     ULONG     0h                      CheckSum
           000000c4 00 00           USHORT    0h                      Subsystem
           000000c6 00 00           USHORT    0h                      DllCharacter
           000000c8 00 00 00 00     ULONG     0h                      SizeOfStackR
           000000cc 00 00 00 00     ULONG     0h                      SizeOfStackC
           000000d0 00 b0 00 00     ULONG     B000h                   SizeOfHeapRe
           000000d4 58 02 00 00     ULONG     258h                    SizeOfHeapCo
           000000d8 00 00 00 00     ULONG     0h                      LoaderFlags
           000000dc 03 00 00 00     ULONG     3h                      NumberOfRvaA
           000000e0 00 00 00 00 00  IMAGE_DA                          DataDirectory
                    00 00 00 00 00 
                    00 00 00 00 00
````

**Comment by ryanmkurtz** [comment]
Can you attach the binary?  The optional header definitely should not be placed at `0x80`...it should be placed at `0x98`.  But, the value at `0x98` also shouldn't be 0.

**Comment by ryanmkurtz** [comment]
Actually, i see we have some code that supports the optional header magic value being 0...so the problem is something else.

**Comment by d-millar** [comment]
Unless I'm missing the point (always likely), I think if you're importing as RawBinary you want to run the PE_script on it, rather than "AutoAnalysis".  I think "AutoAnalysis" presumes the data is in a "loaded" state.  (You might also try dragging the relevant structure into the program, but am pretty sure the script does a better job of this.

**Comment by ryanmkurtz** [comment]
To follow up on what @d-millar said, the correct loader to choose is the `Portable Executable (PE)` loader, but i'm suspecting that is not a choice for you, which if true, seems like a bug.

**Comment by ryanmkurtz** [comment]
Is this a "resource-only" DLL?

**Comment by Wall-AF** [comment]
Here's the actual DLL [USER32.zip](https://github.com/NationalSecurityAgency/ghidra/files/13871790/USER32.zip).

It comes from `WIN32S` implementation.

**Comment by Wall-AF** [comment]
> Unless I'm missing the point (always likely), I think if you're importing as RawBinary you want to run the PE_script on it, rather than "AutoAnalysis". I think "AutoAnalysis" presumes the data is in a "loaded" state. (You might also try dragging the relevant structure into the program, but am pretty sure the script does a better job of this.

Tried that, and here's the error:
```
PE_script.java> Running...
> Error running script: PE_script.java
java.lang.reflect.InvocationTargetException
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1732)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:686)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:786)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:665)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:630)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:103)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:334)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "ghidra.app.util.bin.format.pe.OptionalHeader.is64bit()" because "this.optionalHeader" is null
	at ghidra.app.util.bin.format.pe.NTHeader.getName(NTHeader.java:89)
	at ghidra.app.util.bin.format.pe.NTHeader.toDataType(NTHeader.java:117)
	at ghidra.app.cmd.formats.PortableExecutableBinaryAnalysisCommand.processNTHeader(PortableExecutableBinaryAnalysisCommand.java:192)
	at ghidra.app.cmd.formats.PortableExecutableBinaryAnalysisCommand.createDataTypes(PortableExecutableBinaryAnalysisCommand.java:129)
	at ghidra.app.cmd.formats.PortableExecutableBinaryAnalysisCommand.analysisWorkerCallback(PortableExecutableBinaryAnalysisCommand.java:92)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1726)
	... 8 more
```

**Comment by Wall-AF** [comment]
> To follow up on what @d-millar said, the correct loader to choose is the `Portable Executable (PE)` loader, but i'm suspecting that is not a choice for you, which if true, seems like a bug.

Correct.

**Comment by d-millar** [comment]
LOL - well, this is a terribly dorky solution, but, if you write 0x0B 0x01 (IMAGE_NT_OPTIONAL_HDR32_MAGIC) at offset 0x98 in the file, the PE_script will work.  You may even by able to import it directly.  Not sure why the "magic" dword is missing, but we definitely don't handle it correctly when it is.

**Comment by ryanmkurtz** [comment]
Will be fixed in our next push.

**Comment by Wall-AF** [comment]
> LOL - well, this is a terribly dorky solution, but, if you write 0x0B 0x01 (IMAGE_NT_OPTIONAL_HDR32_MAGIC) at offset 0x98 in the file, the PE_script will work. You may even by able to import it directly. Not sure why the "magic" dword is missing, but we definitely don't handle it correctly when it is.

Thanks @ryanmkurtz.  That enabled PE_script to run, but none of the exports (there are lots) (or imports) are showing!  Any ideas?

**Comment by ryanmkurtz** [comment]
If you write `0B 01` at file offset `0x98` like @d-millar suggested, you should be able to import that file and select the PE loader.  If you use that loader, you should have all the imports/exports.

**Comment by d-millar** [comment]
Actually, not sure that's going to work....looking into it now.

**Comment by d-millar** [comment]
My mistake - that actually works fine.  (I made the mistake of exporting as "Raw Bytes", not "Original File".)

**Comment by Wall-AF** [comment]
Modifying a copy of the original DLL and importing that, fixed the import.
