### ISSUE TITLE
Can't get LLDB via GADP to work in Ghidra on M2 macOS

### ISSUE THREAD

**Issue by viktorb1** [NationalSecurityAgency/ghidra#6095]
Hi, I'm trying to use the Ghidra v11.0 debugger on my macos M2 computer. When I select "Debug in LLDB via GADP" and press connect, I get the following error:

```
[java.lang.RuntimeException: Agent terminated with error: no lldb in java.library.path: 
/Users/me/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Ex
tensions:/usr/lib/java:.
liblldb not found - add relevant java.library.path to support/launch.properties
no lldb-java in java.library.path: 
/Users/me/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Ex
tensions:/usr/lib/java:.
liblld...SBDebugger_eBroadcastBitProgress_get(Native Method)
	at SWIG.SBDebugger.<clinit>(SBDebugger.java:478)
	at agent.lldb.lldb.DebugClientImpl.createClient(DebugClientImpl.java:45)
	at agent.lldb.manager.impl.LldbManagerImpl.lambda$start$0(LldbManagerImpl.java:483)
	at agent.lldb.gadp.impl.LldbClientThreadExecutor.init(LldbClientThreadExecutor.java:50)
	at agent.lldb.gadp.impl.AbstractClientThreadExecutor.run(AbstractClientThreadExecutor.java:95)
	at java.base/java.lang.Thread.run(Thread.java:1583)

---------------------------------------------------
Build Date: 2023-Dec-22 0936 EST
Ghidra Version: 11.0
Java Home: /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home
JVM Version: Eclipse Adoptium 21.0.1
OS: Mac OS X 14.2.1 x86_64
](url)
```

I tried to follow the steps mentioned in #4035 but wasn't able to get it working. 

I tried following the steps, but it does not build for some reason, I get a bunch of errors which I don't know what they mean and the build fails:

```
➜  Debug git:(master) ✗ cd Debugger-swig-lldb
➜  Debugger-swig-lldb git:(master) ✗ ls
InstructionsForBuildingLLDBInterface.txt buildNatives.gradle
Module.manifest                          certification.manifest
build                                    macos_debugger_lldb_build_from_brew.sh
build.gradle                             src
➜  Debugger-swig-lldb git:(master) ✗
➜  Debugger-swig-lldb git:(master) ✗ ls
InstructionsForBuildingLLDBInterface.txt buildNatives.gradle
Module.manifest                          certification.manifest
build                                    macos_debugger_lldb_build_from_brew.sh
build.gradle                             src
➜  Debugger-swig-lldb git:(master) ✗ gradle build

> Configure project :
Gradle: 8.5
OS: Mac OS X
Arch: aarch64
Using platform: mac_arm_64

> Task :Generic:compileJava FAILED
/Users/me/Desktop/ghidra/Ghidra/Framework/Generic/src/main/java/ghidra/generic/util/datastruct/TreeValueSortedMap.java:653: error: types Deque<Entry<K,V>> and List<Entry<K,V>> are incompatible;
        protected class ValueSortedTreeMapEntrySet extends AbstractSet<Entry<K, V>>
                  ^
  both define reversed(), but with unrelated return types
  where K,V are type-variables:
    K extends Object declared in class TreeValueSortedMap
    V extends Object declared in class TreeValueSortedMap
/Users/me/Desktop/ghidra/Ghidra/Framework/Generic/src/main/java/ghidra/generic/util/datastruct/TreeValueSortedMap.java:973: error: types Deque<K> and List<K> are incompatible;
        protected class ValueSortedTreeMapKeySet extends AbstractSet<K>
                  ^
  both define reversed(), but with unrelated return types
  where K is a type-variable:
    K extends Object declared in class TreeValueSortedMap
/Users/me/Desktop/ghidra/Ghidra/Framework/Generic/src/main/java/ghidra/generic/util/datastruct/TreeValueSortedMap.java:1211: error: types Deque<V> and List<V> are incompatible;
        protected class ValueSortedTreeMapValues extends AbstractCollection<V>
                  ^
  both define reversed(), but with unrelated return types
  where V is a type-variable:
    V extends Object declared in class TreeValueSortedMap
/Users/me/Desktop/ghidra/Ghidra/Framework/Generic/src/main/java/ghidra/generic/util/datastruct/ValueSortedMap.java:39: error: types Deque<Entry<K,V>> and List<Entry<K,V>> are incompatible;
        public interface ValueSortedMapEntryList<K, V>
               ^
  both define reversed(), but with unrelated return types
  where K,V are type-variables:
    K extends Object declared in interface ValueSortedMapEntryList
    V extends Object declared in interface ValueSortedMapEntryList
/Users/me/Desktop/ghidra/Ghidra/Framework/Generic/src/main/java/ghidra/generic/util/datastruct/ValueSortedMap.java:47: error: types Deque<K> and List<K> are incompatible;
        public interface ValueSortedMapKeyList<K> extends Set<K>, List<K>, Deque<K> {
               ^
  both define reversed(), but with unrelated return types
  where K is a type-variable:
    K extends Object declared in interface ValueSortedMapKeyList
/Users/me/Desktop/ghidra/Ghidra/Framework/Generic/src/main/java/ghidra/generic/util/datastruct/RestrictedValueSortedMap.java:253: error: types Deque<Entry<K,V>> and List<Entry<K,V>> are incompatible;
        public class RestrictedValueSortedMapEntryList implements ValueSortedMapEntryList<K, V> {
               ^
  both define reversed(), but with unrelated return types
  where K,V are type-variables:
    K extends Object declared in class RestrictedValueSortedMap
    V extends Object declared in class RestrictedValueSortedMap
/Users/me/Desktop/ghidra/Ghidra/Framework/Generic/src/main/java/ghidra/generic/util/datastruct/RestrictedValueSortedMap.java:548: error: types Deque<K> and List<K> are incompatible;
        public class RestrictedValueSortedMapKeyList implements ValueSortedMapKeyList<K> {
               ^
  both define reversed(), but with unrelated return types
  where K is a type-variable:
    K extends Object declared in class RestrictedValueSortedMap
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API that is marked for removal.
Note: Recompile with -Xlint:removal for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
7 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Generic:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 3s
4 actionable tasks: 1 executed, 3 up-to-date
➜  Debugger-swig-lldb git:(master) ✗
```

Here is a full output of the errors: https://gist.github.com/viktorb1/7576abc6e8eecf0c7eb6a9ca4e8ab995

 If someone knows how to fix this, I would appreciate it. Thanks

**Comment by d-millar** [comment]
@viktorb1 Hey, and, first off, sorry to hear you're having difficulties.  Looking at the errors, am pretty sure you have a mismatch between your version of lldb and the SWIG files included with the distribution.   The SWIG files in the distro match lldb v16 and, as you noted, you have 17.0.6.  The complete instructions for how to solve this are in the Ghidra/Debug/Debugger-swig-lldb/InstructionsForBuildingLLDBInterface.txt, but will give you the basic outline.

First off, make sure you have swig installed.  Second, I would recommend "git clone"ing the llvm repo and using that for LLVM_HOME.  I would also use "git checkout release/17.x" to make sure things match your version.  Alternatively, you can use the brew-installed version, but you may have to modify some paths in the build.gradle file in Debugger-swig-lldb, so that things line up correctly.  It's basically expecting LLVM_HOME/lldb//include/lldb, so....  I would also verify that LLVM_BUILD/lib/liblldb.dylib exists.  Again, different packages seem to have slightly different organizations.

With all of that set, from the Debugger-swig-lldb dir, run "gradle generateSwig" and then "gradle build".

Fingers crossed, but let us know if things go sideways.

**Comment by viktorb1** [comment]
I followed all your steps. I installed SWIG using `brew install swig`. I cloned the repo and switched to release 17.x and tried using its directory as the environmental variable for LLVM_HOME. I tried both modifying the paths in the gradle build file and using the original LLVM_HOME and I verified that the liblldb.dylib file exists in the correct path. Despite this, the command `gradle build` (and buildNatives) still gives me those errors shown above. However `grade generateSwig` runs without errors. I don't think this is related to not being able to find the header files because I had that error earlier and I resolved it by changing build file so that it points to the correct path. This error that I am now getting happens after I resolved that header file error. I'm out of ideas about what to do.
