### ISSUE TITLE
NullPointerException Infinite Loop in Symbol Column Filter UI

### ISSUE THREAD

**Issue by utkonos** [NationalSecurityAgency/ghidra#6123]
**Describe the bug**
The combination of `Location`, `At Least`, and `0x0` when set in the Symbols Column Filter of the Symbol Table starts an infinite loop of exceptions. You cannot close the window or do anything in the UI once the loop starts. You then must kill Ghidra to restart it.

**To Reproduce**
1. Open the Symbol Table
2. In the lower right, click the button "Create Column Filter"
3. Set the Table Column to "Location"
4. Set the Filter to "At Least"
5. Set the Filter Value to "0x0"

**Expected behavior**
An error message may be appropriate, but it should then allow the user to clear the filter.

**Screenshots**
<img width="982" alt="image" src="https://github.com/NationalSecurityAgency/ghidra/assets/2775739/57de3a85-3875-4cad-b810-67793fb349ab">

**Environment (please complete the following information):**
 - OS: macOS 14.2.1
 - Java Version: 21.0.1
 - Ghidra Version: 11.0
 - Ghidra Origin: Official GitHub distro

**Comment by dragonmacher** [comment]
I was unable to reproduce this.  There must be something specific about your binary causing the issue.   

Would you please include the full stack trace from you application log file?  It can be found at:
`{user home}/.ghidra/.ghidra_11/applacation.log`

**Comment by utkonos** [comment]
```
ERROR (SwingExceptionHandler) Error: Uncaught Exception! 
NullPointerException - Cannot invoke "docking.widgets.table.constraint.ColumnConstraint.getName()" because 
"selectedConstraint" is null java.lang.NullPointerException: Cannot invoke "docking.widgets.table.constraint.ColumnConstraint.getName()" because "selectedConstraint" is null
        at docking.widgets.table.constraint.dialog.ConstraintFilterPanel.constraintChanged(ConstraintFilterPanel.java:108)
        at docking.widgets.table.constraint.dialog.ConstraintFilterPanel.lambda$new$0(ConstraintFilterPanel.java:39)
        at java.desktop/javax.swing.JComboBox.fireActionEvent(JComboBox.java:1294)
        at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:619)
        at java.desktop/javax.swing.JComboBox.setSelectedIndex(JComboBox.java:650)
        at java.desktop/javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:946)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
        at java.desktop/com.apple.laf.AquaComboBoxPopup$1.processMouseEvent(AquaComboBoxPopup.java:178)
        at java.desktop/java.awt.Component.processEvent(Component.java:6386)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
        
ERROR (SwingExceptionHandler) Error: Uncaught Exception! 
NullPointerException - Cannot invoke "docking.widgets.table.constraint.ColumnConstraint.getName()" because "value" is 
null java.lang.NullPointerException: Cannot invoke "docking.widgets.table.constraint.ColumnConstraint.getName()" because "value" is null
        at docking.widgets.table.constraint.dialog.ConstraintFilterPanel$ConstraintComboBoxCellRenderer.getItemText(ConstraintFilterPanel.java:126)
        at docking.widgets.table.constraint.dialog.ConstraintFilterPanel$ConstraintComboBoxCellRenderer.getItemText(ConstraintFilterPanel.java:122)
        at docking.widgets.list.GListCellRenderer.getListCellRendererComponent(GListCellRenderer.java:76)
        at java.desktop/com.apple.laf.AquaComboBoxButton.doRendererPaint(AquaComboBoxButton.java:176)
        at java.desktop/com.apple.laf.AquaComboBoxButton.paintComponent(AquaComboBoxButton.java:168)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5318)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1656)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1631)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1569)
        at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1336)
        at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5266)
        at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5076)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:878)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:861)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:861)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:834)
        at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
        at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1897)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
        at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
        at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
        at java.desktop/java.awt.Dialog.show(Dialog.java:1079)
        at java.desktop/java.awt.Component.show(Component.java:1728)
        at java.desktop/java.awt.Component.setVisible(Component.java:1675)
        at java.desktop/java.awt.Window.setVisible(Window.java:1036)
        at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1015)
        at docking.DockingDialog.setVisible(DockingDialog.java:351)
        at docking.DockingWindowManager.lambda$doShowDialog$6(DockingWindowManager.java:1807)
        at ghidra.util.Swing.doRun(Swing.java:292)
        at ghidra.util.Swing.runNow(Swing.java:208)
        at ghidra.util.Swing.runNow(Swing.java:163)
        at docking.DockingWindowManager.doShowDialog(DockingWindowManager.java:1811)
        at docking.DockingWindowManager.showDialog(DockingWindowManager.java:1760)
        at docking.DockingErrorDisplay.showErrorDialogOnSwing(DockingErrorDisplay.java:187)
        at docking.DockingErrorDisplay.showDialog(DockingErrorDisplay.java:166)
        at docking.DockingErrorDisplay.doDisplayMessage(DockingErrorDisplay.java:134)
        at docking.DockingErrorDisplay.lambda$displayMessage$0(DockingErrorDisplay.java:102)
        at ghidra.util.Swing.runIfSwingOrRunLater(Swing.java:124)
        at docking.DockingErrorDisplay.displayMessage(DockingErrorDisplay.java:102)
        at docking.DockingErrorDisplay.displayErrorMessage(DockingErrorDisplay.java:55)
        at ghidra.util.Msg.showError(Msg.java:306)
        at ghidra.SwingExceptionHandler.handleUncaughtException(SwingExceptionHandler.java:80)
        at ghidra.GhidraThreadGroup.handleUncaughtException(GhidraThreadGroup.java:68)
        at ghidra.GhidraThreadGroup.uncaughtException(GhidraThreadGroup.java:38)
        at java.desktop/java.awt.EventDispatchThread.processException(EventDispatchThread.java:218)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:210)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

ERROR (DecompileProcess) Unexpected Exception: Cannot invoke "String.getBytes()" because "val" is null java.lang.NullPointerException: Cannot invoke "String.getBytes()" because "val" is null
        at ghidra.program.model.pcode.PackedEncode.writeString(PackedEncode.java:162)
        at ghidra.program.model.pcode.FunctionPrototype.encodePrototype(FunctionPrototype.java:324)
        at ghidra.program.model.pcode.HighFunction.encode(HighFunction.java:453)
        at ghidra.program.model.pcode.HighFunctionSymbol.encode(HighFunctionSymbol.java:77)
        at ghidra.program.model.pcode.HighSymbol.encodeMapSym(HighSymbol.java:567)
        at ghidra.app.decompiler.DecompileCallback.encodeResult(DecompileCallback.java:823)
        at ghidra.app.decompiler.DecompileCallback.encodeFunction(DecompileCallback.java:959)
        at ghidra.app.decompiler.DecompileCallback.getMappedSymbols(DecompileCallback.java:659)
        at ghidra.app.decompiler.DecompileProcess.getMappedSymbols(DecompileProcess.java:746)
        at ghidra.app.decompiler.DecompileProcess.readResponse(DecompileProcess.java:305)
        at ghidra.app.decompiler.DecompileProcess.sendCommandTimeout(DecompileProcess.java:538)
        at ghidra.app.decompiler.DecompInterface.decompileFunction(DecompInterface.java:807)
        at ghidra.app.decompiler.component.Decompiler.decompile(Decompiler.java:57)
        at ghidra.app.decompiler.component.DecompilerManager.decompile(DecompilerManager.java:175)
        at ghidra.app.decompiler.component.DecompileRunnable.monitoredRun(DecompileRunnable.java:108)
        at ghidra.util.task.RunManager$RunnerJob.doExecute(RunManager.java:334)
        at ghidra.util.task.RunManager$RunnerJob.run(RunManager.java:309)
        at ghidra.util.worker.AbstractWorker$JobCallback.process(AbstractWorker.java:133)
        at ghidra.util.worker.AbstractWorker$JobCallback.process(AbstractWorker.java:123)
        at generic.concurrent.ConcurrentQ$CallbackCallable.call(ConcurrentQ.java:658)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by dragonmacher** [comment]
Thanks for the traces.   My guess in looking at these is that there is an earlier trace / failure and these are showing the symptom of that previous failure.

If you look backwards through the log, can you find the start of these exceptions?   (If there were enough exceptions, the log may have  rolled over.)   I'm interested in seeing if you have different exception(s) before these.

**Comment by utkonos** [comment]
> If you look backwards through the log, can you find the start of these exceptions?

The first exception above is the first exception in the log. I have not had version 11 installed and running for long enough to have the log roll over. The first exception is line 209 of the log.
