### ISSUE TITLE
Likely bug in ThreadedTableModelUpdateMgr when adding more than 3000 elements to an AddressBasedTableModel

### ISSUE THREAD

**Issue by sad-dev** [NationalSecurityAgency/ghidra#6131]
**Describe the bug**
I have a plugin that implements a ``GhidraThreadedTablePanel`` and ``GhidraTableFilterPanel`` on an ``AddressBasedTableModel``. By binary search, I observed that trying to add more than 3000 (plus a bit, typically) elements to the model from a script was resulting in no rows after the script finishes, while adding less than that, or calling ``Thread.sleep`` with a sufficiently large wait time will allow the addition of all elements successfully.

I had similar issues when trying to add more than 3000 elements from a ``DockingAction``, with the additional limitation of not being able to call long ``Thread.sleep`` due to a deadlock (Edit: I later resolved this by implementing a ``BackgroundCommand`` which adds the elements in batches, calling ``Thread.sleep`` between each batch.
```
ERROR Timed-out waiting to run a Swing task--potential deadlock!
Threads State:
java.lang.Throwable (Swing)  
ERROR Unexpected Exception: Timed-out waiting to run a Swing task--potential deadlock! (LoadJob) java.lang.RuntimeException: Timed-out waiting to run a Swing task--potential deadlock!
	at ghidra.util.Swing.runNow(Swing.java:177)
	at docking.widgets.table.threaded.TableUpdateJob.applyData(TableUpdateJob.java:682)
	at docking.widgets.table.threaded.TableUpdateJob.processState(TableUpdateJob.java:346)
	at docking.widgets.table.threaded.TableUpdateJob.run(TableUpdateJob.java:129)
	at docking.widgets.table.threaded.ThreadedTableModelUpdateMgr$ThreadRunnable.run(ThreadedTableModelUpdateMgr.java:415)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: ghidra.util.exception.UnableToSwingException: Timed-out waiting for Swing thread lock in 20 SECONDS
	at ghidra.util.Swing.waitFor(Swing.java:256)
	at ghidra.util.Swing.runNow(Swing.java:235)
	at ghidra.util.Swing.runNow(Swing.java:163)
	... 5 more
```

The approximate threshold of 3000 leads me to suspect that this is due to the implementation of ``ThreadedTableModelUpdateMgr``:

(edit: it looks like this behaviour is intentional; if so (or if, as is fairly likely, I have done something wrong with my code), is there any recommendation on how to add many elements to the model safely + quickly?)

```
// make the delay large enough that a flurry of events will stay buffered
public final static int DELAY = 5000;
public final static int MAX_DELAY = 1000 * 60 * 20;
static final int TOO_MANY_ADD_REMOVES = 3000;
// this.maxAddRemoveCount = TOO_MANY_ADD_REMOVES;

	private void processAddRemoveItems() {
		synchronized (addRemoveUpdater) {

			if (addRemoveWaitList.isEmpty()) {
				return;
			}

			// too many requests for add/remove triggers a full reload for efficiency
			if (addRemoveWaitList.size() > getMaxAddRemoveCount()) {
				reload();
				return;
			}

			runJob(new AddRemoveJob<>(model, addRemoveWaitList, monitor));
			addRemoveWaitList = new ArrayList<>();
		}
	}

```

**To Reproduce**
The script:
```
public class AddFnsToPlugin extends GhidraScript {
	int MAX_FNS = 3100;
	@Override
	protected void run() throws Exception {
		MyFirstPlugin plugin = getPlugin(MyFirstPlugin.class);
		FunctionIterator fIter = currentProgram.getFunctionManager().getFunctionsNoStubs(true);
		int i = 0;
		while (fIter.hasNext()) {
			i++;
			plugin.addFn(fIter.next());
			if (i > MAX_FNS) {
				break;
			}
		}
	}

	private <T extends Plugin> T getPlugin(Class<T> c) {
		List<Plugin> list = tool.getManagedPlugins();
		Iterator<Plugin> it = list.iterator();
		while (it.hasNext()) {
			Plugin p = it.next();
			if (p.getClass() == c) {
				return c.cast(p);
			}
		}
		println("Error retrieving plugin by class ");
		return null;
	}
}
```

A partial reproduction of my plugin (which I am not able to share, unfortunately) is as follows:

```
public class MyFirstPlugin extends ProgramPlugin {
	RuntimeFuncProvider fnProvider;
	public MyFirstPlugin(PluginTool tool) {
		fsProvider = new RuntimeFuncProvider(this, pluginName);
	}
	void addFn(Function fn) {
		fnProvider.addObject(fn);
	}
}
	
public class RuntimeFuncProvider extends ComponentProviderAdapter {
	private FuncTableModel model;
	private GhidraTable table;
	private GhidraThreadedTablePanel<Function> threadedTablePanel;
	private GhidraTableFilterPanel<Function> tableFilterPanel;
	private TableModelListener listener;

	public RuntimeFuncProvider(Plugin plugin, String owner) {
		super(plugin.getTool(), "My Functions", owner, ProgramActionContext.class);

		model = new FuncTableModel(tool, null);
		threadedTablePanel = new GhidraThreadedTablePanel<>(model);
		GhidraTable table = threadedTablePanel.getTable();
		tableFilterPanel = new GhidraTableFilterPanel<>(table, model);
		panel = new JPanel(new BorderLayout());
		panel.add(threadedTablePanel, BorderLayout.CENTER);
		panel.add(tableFilterPanel, BorderLayout.SOUTH);

		listener = e -> {
			String subTitle;
			if (model.isFiltered()) {
				subTitle = "(filter matched " + table.getRowCount() + " of " +
					model.getKeyCount() + ")";
			}
			else {
				subTitle = "(" + table.getRowCount() + " fns)";
			}
			setSubTitle(subTitle);
			contextChanged();
		};

		table.getModel().addTableModelListener(listener);
		setDefaultWindowPosition(WindowPosition.BOTTOM);
		setVisible(true);

	}

	public void addObject(Function fn) {
		model.addObject(fn);
	}
}

public class FuncTableModel extends AddressBasedTableModel<Function> {
	FuncTableModel(PluginTool tool, Program program) {
		super("MyFunctions", tool, program, null);
		initialize(program);
	}

	private void initialize(Program program) {
	}

	@Override
	public Address getAddress(int row) {
		Function rs = this.getRowObject(row);
		return rs.getEntryPoint();
	}
	public int getKeyCount() {
		return getRowCount();
	}

	void reload(Program newProgram) {
		setProgram(newProgram);
		initialize(getProgram());
		reload();
	}

	@Override
	protected void doLoad(Accumulator<Function> accumulator, TaskMonitor monitor) throws CancelledException {
		return;
	}
}
```

**Environment (please complete the following information):**
 - Ghidra 1281fb9

**Comment by dragonmacher** [comment]
Regarding the 3000 item limit, the intention is that at some point a full table reload is more efficient that performing individual add/remove/update operations.     Once the threshold is crossed, the table signals that a full reload is needed.  It seems like there is a path where this is not working correctly.

Regarding performing slow operations from an action (or any UI widget), we typically use a `TaskLauncher` for this, which will use a background thread and show the user a progress monitor.   Although, if you have the background command working, there is nothing wrong with using that.

**Comment by sad-dev** [comment]
Thanks, that was immensely helpful! I had a hunch that ``doLoad`` was the function I needed to implement but struggled to find an example in ghidra code that matched my use case. 

I will close this as its clearly working as intended.
