### ISSUE TITLE
GhidraJarApplicationLayout null pointer exception

### ISSUE THREAD

**Issue by Cazra** [NationalSecurityAgency/ghidra#6178]
I'm trying to use Ghidra as a jar to analyze samples headlessly. I am using the following chunk of code lifted from the HeadlessAnalyzer example to initialize my analysis:

```
public static MyHeadlessAnalyzer getInstance(LibProgramHandler handler) throws IOException {
		// Prevent more than one headless analyzer from being instantiated.  Too much about it
		// messes with global system settings, so under the current design of Ghidra, allowing
		// more than one to exist could result in unpredictable behavior.
		if (THREAD_LOCAL_INSTANCE.get() != null) {
			THREAD_LOCAL_INSTANCE.get().programHandler = handler;
			return THREAD_LOCAL_INSTANCE.get();
		}

		// Initialize application (if necessary)
		synchronized (THREAD_LOCK) {
			if (!Application.isInitialized()) {
				ApplicationConfiguration configuration = new HeadlessGhidraApplicationConfiguration();
				Application.initializeApplication(getApplicationLayout(), configuration);
			}
		}
		THREAD_LOCAL_INSTANCE.set(new LibHeadlessAnalyzer());
		THREAD_LOCAL_INSTANCE.get().programHandler = handler;
		return THREAD_LOCAL_INSTANCE.get();
	}

	/**
	 * Gets the appropriate Ghidra application layout for this headless analyzer.
	 * <p>
	 * The headless analyzer can be used in both "normal" mode and single jar mode, so
	 * we need to use the appropriate layout for either case.
	 *
	 * @return The appropriate Ghidra application layout for this headless analyzer.
	 * @throws IOException if there was a problem getting an appropriate application layout.
	 */
	private static GhidraApplicationLayout getApplicationLayout() throws IOException {
		GhidraApplicationLayout layout;
		try {
			layout = new GhidraApplicationLayout();
		}
		catch (IOException e) {
			layout = new GhidraJarApplicationLayout();
		}
		return layout;
	}
```

When it tries to instantiate the GhidraJarApplicationLayout, it is throwing a null pointer exception. Here is my stack trace:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.net.URL.toExternalForm()" because "url" is null
	at io.package.to.MyMainApplication.main(MyMainApplication.java:81)
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.toExternalForm()" because "url" is null
	at ghidra.GhidraJarApplicationLayout.fromUrl(GhidraJarApplicationLayout.java:94)
	at ghidra.GhidraJarApplicationLayout.findExtensionInstallationDirectories(GhidraJarApplicationLayout.java:83)
	at ghidra.GhidraApplicationLayout.<init>(GhidraApplicationLayout.java:62)
	at ghidra.GhidraJarApplicationLayout.<init>(GhidraJarApplicationLayout.java:42)
	at io.package.to.MyHeadlessAnalyzer.getApplicationLayout(LibHeadlessAnalyzer.java:136)
	...
```

Is there a step I'm missing or something I'm doing wrong to set things up?

**Comment by dragonmacher** [comment]
This code reads a bit strangely to me:

```
try {
    layout = new GhidraApplicationLayout();
}
catch (IOException e) {
    layout = new GhidraJarApplicationLayout();
}
return layout;
```

The `GhidraJarApplicationLayout` is meant to be used for clients that create a fat Ghidra jar manually.  I'm assuming you have not created a fat Ghidra jar, but are instead running from a  standard installation.    In that case, the real issue is that creating the `GhidraApplicationLayout` failed for some reason.  Unfortunately. the catch block above does not log the exception, so we cannot see what failed.

**Comment by Cazra** [comment]
Those lines of code are lifted straight from the HeadlessAnalyzer.java example: https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/src/main/java/ghidra/app/util/headless/HeadlessAnalyzer.java

I already know *what* the exception. It's a null pointer exception generated within `GhidraJarApplicationLayout`. When `GhidraJarApplicationLayout` is instantiated, it calls the method `findExtensionInstallationDirectories`, which tries to construct a URL object to the jar resource "/_ROOT/Ghidra/Extensions", which doesn't exist in the Ghidra.jar file built with `buildGhidraJar`.

**Comment by Cazra** [comment]
I've found that by manually adding a `/_Root/Ghidra/Extensions` path to the jar, the issue has resolved and I'm no longer getting the null pointer exception! 

Weird that is wasn't added in the first place by the `buildGhidraJar` script though... :/

**Comment by dragonmacher** [comment]
> Weird that is wasn't added in the first place by the buildGhidraJar script though... :/

It wasn't clear to me which environment you were using, standard install vs fat jar.   I see now.   And yes, this is clearly a disconnect between how our support script builds the fat jar and how the system uses it.    Building and running from the fat jar is not something that is well-supported on our side.  I think there is an expectation that if you are using the fat jar, you have to be willing to work with the sharp edges, which it sounds like you have successfully done.


> Those lines of code are lifted straight from the HeadlessAnalyzer.java 

That is unfortunate that the original devs didn't add a log line and a helpful message.


> I've found that by manually adding a /_Root/Ghidra/Extensions path to the jar

This may actually be something that I personally broke recently while working with Extensions.   I will use this ticket to update the code that was throwing the exception.
