### ISSUE TITLE
Potential memory issue with image upgrade

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#6233]
**Describe the bug**
Hitting out of disk space while trying to upgrade some PPC 32-bit images in master.  Trying with 11.0 and upgrading to 11.0.1 it does have to re-disassemble but this time uses RAM.  I have upgraded these images before for several years now (same machine) from eclipse (run, not debug).

Reporting in case there might have been some accidental bloat added or change in the upgrade process (Is eclipse vs PUBLIC.zip  the difference between tmpfs vs RAM or is that a recent change?).   tmpfs  (/run/user/1001) is 1.6 GB and 1.4MB before starting upgrade.

**Environment (please complete the following information):**
 - OS: 22.04
 - Java Version: 17.0.9
 - Ghidra Version: 6d6d0317e263a536798e7ec754b1466443d5b1b1
 - Ghidra Origin: local

**Additional context**

```
ERROR getDomainObject failed java.lang.IllegalStateException: Set language aborted - program object is now in an unusable state!
	at ghidra.program.database.ProgramDB.setLanguage(ProgramDB.java:2125)
	at ghidra.program.database.ProgramDB.<init>(ProgramDB.java:371)
	at ghidra.program.database.ProgramContentHandler.getDomainObject(ProgramContentHandler.java:187)
	at ghidra.program.database.ProgramContentHandler.getDomainObject(ProgramContentHandler.java:1)
	at ghidra.framework.data.GhidraFileData.getDomainObject(GhidraFileData.java:509)
	at ghidra.framework.data.GhidraFile.getDomainObject(GhidraFile.java:231)
	at ghidra.app.util.task.ProgramOpener.openFileMaybeUgrade(ProgramOpener.java:286)
	at ghidra.app.util.task.ProgramOpener.openNormal(ProgramOpener.java:183)
	at ghidra.app.util.task.ProgramOpener.openProgram(ProgramOpener.java:175)
	at ghidra.app.util.task.ProgramOpener.openProgram(ProgramOpener.java:96)
	at ghidra.app.util.task.OpenProgramTask.run(OpenProgramTask.java:144)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: ghidra.framework.model.DomainObjectException caused by: java.io.IOException: No space left on device
	at ghidra.framework.data.DomainObjectAdapter.fatalErrorOccurred(DomainObjectAdapter.java:489)
	at ghidra.framework.data.DomainObjectAdapterDB.dbError(DomainObjectAdapterDB.java:236)
	at ghidra.program.database.references.ReferenceDBManager.dbError(ReferenceDBManager.java:1873)
	at ghidra.program.database.references.ReferenceDBManager.getFromRefs(ReferenceDBManager.java:1623)
	at ghidra.program.database.references.ReferenceDBManager.getReferencesFrom(ReferenceDBManager.java:837)
	at ghidra.program.database.code.CodeManager.addReferencesForInstruction(CodeManager.java:2886)
	at ghidra.program.database.code.CodeManager.addInstruction(CodeManager.java:676)
	at ghidra.program.database.code.CodeManager.addInstructions(CodeManager.java:527)
	at ghidra.program.database.ListingDB.addInstructions(ListingDB.java:279)
	at ghidra.program.disassemble.Disassembler.disassemble(Disassembler.java:638)
	at ghidra.program.disassemble.Disassembler.disassemble(Disassembler.java:502)
	at ghidra.program.disassemble.Disassembler.disassemble(Disassembler.java:433)
	at ghidra.program.database.code.CodeManager.reDisassembleAllInstructions(CodeManager.java:3598)
	at ghidra.program.database.ProgramDB.setLanguage(ProgramDB.java:2098)
	... 15 more
Caused by: java.io.IOException: No space left on device
	at java.base/java.io.RandomAccessFile.writeBytes(Native Method)
	at java.base/java.io.RandomAccessFile.write(RandomAccessFile.java:558)
	at db.buffers.LocalBufferFile.put(LocalBufferFile.java:705)
	at db.buffers.BufferMgr.unloadCachedNode(BufferMgr.java:931)
	at db.buffers.BufferMgr.getBuffer(BufferMgr.java:963)
	at db.NodeMgr.getLongKeyNode(NodeMgr.java:257)
	at db.LongKeyInteriorNode.getLeafNode(LongKeyInteriorNode.java:414)
	at db.LongKeyInteriorNode.getLeafNode(LongKeyInteriorNode.java:416)
	at db.Table.getRecord(Table.java:701)
	at ghidra.program.database.references.FromAdapterV0.getRefList(FromAdapterV0.java:61)
	at ghidra.program.database.references.ReferenceDBManager.getFromRefs(ReferenceDBManager.java:1620)
	... 25 more
  (ProgramContentHandler.java:206) 
ERROR Error During Open File: Open failed: Set language aborted - program object is now in an unusable state! java.io.IOException: Open failed: Set language aborted - program object is now in an unusable state!
	at ghidra.program.database.ProgramContentHandler.getDomainObject(ProgramContentHandler.java:211)
	at ghidra.program.database.ProgramContentHandler.getDomainObject(ProgramContentHandler.java:1)
	at ghidra.framework.data.GhidraFileData.getDomainObject(GhidraFileData.java:509)
	at ghidra.framework.data.GhidraFile.getDomainObject(GhidraFile.java:231)
	at ghidra.app.util.task.ProgramOpener.openFileMaybeUgrade(ProgramOpener.java:286)
	at ghidra.app.util.task.ProgramOpener.openNormal(ProgramOpener.java:183)
	at ghidra.app.util.task.ProgramOpener.openProgram(ProgramOpener.java:175)
	at ghidra.app.util.task.ProgramOpener.openProgram(ProgramOpener.java:96)
	at ghidra.app.util.task.OpenProgramTask.run(OpenProgramTask.java:144)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalStateException: Set language aborted - program object is now in an unusable state!
	at ghidra.program.database.ProgramDB.setLanguage(ProgramDB.java:2125)
	at ghidra.program.database.ProgramDB.<init>(ProgramDB.java:371)
	at ghidra.program.database.ProgramContentHandler.getDomainObject(ProgramContentHandler.java:187)
	... 13 more
Caused by: ghidra.framework.model.DomainObjectException caused by: java.io.IOException: No space left on device
	at ghidra.framework.data.DomainObjectAdapter.fatalErrorOccurred(DomainObjectAdapter.java:489)
	at ghidra.framework.data.DomainObjectAdapterDB.dbError(DomainObjectAdapterDB.java:236)
	at ghidra.program.database.references.ReferenceDBManager.dbError(ReferenceDBManager.java:1873)
	at ghidra.program.database.references.ReferenceDBManager.getFromRefs(ReferenceDBManager.java:1623)
	at ghidra.program.database.references.ReferenceDBManager.getReferencesFrom(ReferenceDBManager.java:837)
	at ghidra.program.database.code.CodeManager.addReferencesForInstruction(CodeManager.java:2886)
	at ghidra.program.database.code.CodeManager.addInstruction(CodeManager.java:676)
	at ghidra.program.database.code.CodeManager.addInstructions(CodeManager.java:527)
	at ghidra.program.database.ListingDB.addInstructions(ListingDB.java:279)
	at ghidra.program.disassemble.Disassembler.disassemble(Disassembler.java:638)
	at ghidra.program.disassemble.Disassembler.disassemble(Disassembler.java:502)
	at ghidra.program.disassemble.Disassembler.disassemble(Disassembler.java:433)
	at ghidra.program.database.code.CodeManager.reDisassembleAllInstructions(CodeManager.java:3598)
	at ghidra.program.database.ProgramDB.setLanguage(ProgramDB.java:2098)
	... 15 more
Caused by: java.io.IOException: No space left on device
	at java.base/java.io.RandomAccessFile.writeBytes(Native Method)
	at java.base/java.io.RandomAccessFile.write(RandomAccessFile.java:558)
	at db.buffers.LocalBufferFile.put(LocalBufferFile.java:705)
	at db.buffers.BufferMgr.unloadCachedNode(BufferMgr.java:931)
	at db.buffers.BufferMgr.getBuffer(BufferMgr.java:963)
	at db.NodeMgr.getLongKeyNode(NodeMgr.java:257)
	at db.LongKeyInteriorNode.getLeafNode(LongKeyInteriorNode.java:414)
	at db.LongKeyInteriorNode.getLeafNode(LongKeyInteriorNode.java:416)
	at db.Table.getRecord(Table.java:701)
	at ghidra.program.database.references.FromAdapterV0.getRefList(FromAdapterV0.java:61)
	at ghidra.program.database.references.ReferenceDBManager.getFromRefs(ReferenceDBManager.java:1620)
	... 25 more
  (ConsoleErrorDisplay.java:45) 
```

**Comment by ryanmkurtz** [comment]
> Trying with 11.0 and upgrading to 11.0.1 it does have to re-disassemble but this time uses RAM.

Is it really 11.0.1 or did you mean 11.1-DEV/master?  In master the default user settings/temp/cache directories have changed, and XDG environment variables are supported.  Do you have any [XDG](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) env variables set?

**Comment by ryanmkurtz** [comment]
FYI in master there is a new window under `Help -> Runtime Information` that can quickly show your current Environment and Application Layout.

**Comment by mumbel** [comment]
Master is where I noticed the issue.  I then tried making sure it opened/upgraded in 11.0.1

**Comment by ryanmkurtz** [comment]
We are still discussing the best way to deal with this generically.  In the meantime, you can work around it by going into `support/launch.properties`, and uncommenting/setting 

```
VMARGS=-Dapplication.tempdir=/tmp
```
