### ISSUE TITLE
COFF importer crashes while loading some SysV/i386 (ISC UNIX) binaries

### ISSUE THREAD

**Issue by philpem** [NationalSecurityAgency/ghidra#6236]
**Describe the bug**
COFF importer crashes while loading the attached binary. Binary was created for ISC UNIX (Interactive Unix) on the i386 platform, a System V variant.

**To Reproduce**
1. Import binary, "ANICDOWNLOAD".
2. Click OK, accept default settings for a COFF binary
3. See error

**Expected behavior**
COFF binary loads correctly

**Error log**
```
Attempted to read string at 0x43cba
java.io.EOFException: Attempted to read string at 0x43cba
	at ghidra.app.util.bin.BinaryReader.readUntilNullTerm(BinaryReader.java:716)
	at ghidra.app.util.bin.BinaryReader.readString(BinaryReader.java:874)
	at ghidra.app.util.bin.BinaryReader.readAsciiString(BinaryReader.java:759)
	at ghidra.app.util.bin.format.coff.CoffSymbol.<init>(CoffSymbol.java:44)
	at ghidra.app.util.bin.format.coff.CoffFileHeader.parse(CoffFileHeader.java:211)
	at ghidra.app.util.opinion.CoffLoader.load(CoffLoader.java:172)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:883)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:98)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:395)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:336)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

---------------------------------------------------
Build Date: 2024-Jan-30 1212 EST
Ghidra Version: 11.0.1
Java Home: /usr/lib/jvm/java-21-openjdk-amd64
JVM Version: Private Build 21.0.1
OS: Linux 5.15.0-92-generic amd64
```

**Attachments**
[ANICDOWNLOAD.zip](https://github.com/NationalSecurityAgency/ghidra/files/14323072/ANICDOWNLOAD.zip)

**Environment (please complete the following information):**
 - OS: Linux Mint 21.2
 - Java Version: OpenJDK 21.0.1
 - Ghidra Version: 11.0.1 and 11.1 (locally built from git HEAD at time of testing)
 - Ghidra Origin: 11.0.1 from official release packages. 11.1 locally built from Git HEAD.

**Comment by ryanmkurtz** [comment]
Thanks, i'm working on a fix.

**Comment by ryanmkurtz** [comment]
@rhjdvsgsgks yes, a new issue would be good...thanks.
