### ISSUE TITLE
macOS - NullPointerException on suspend and/or server disconnect?

### ISSUE THREAD

**Issue by virtuald** [NationalSecurityAgency/ghidra#6254]
**Describe the bug**

When I start Ghidra at work, and close my laptop and go home, typically when I try to use Ghidra again when getting back to work I am presented with a NullPointerException that happens over and over and over again. In the past if you dismissed it enough times it would go away, but it seems the only way to address it now is to completely shut down ghidra and start over.

It's not clear to me whether the behavior is caused by disconnecting from the server or by the laptop suspending.

**To Reproduce**
1. Start ghidra, connect
2. Do work
3. Go home, close laptop
4. Come back, go to one of the CodeBrowser windows left open
5. Cry in frustration due to NullPointerException happening over and over again

**Expected behavior**
No error

**Attachments**

```
Cannot invoke "String.hashCode()" because the return value of "ghidra.framework.model.DomainFile.getFileID()" is null
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because the return value of "ghidra.framework.model.DomainFile.getFileID()" is null
	at ghidra.app.plugin.core.datamgr.archive.ProjectArchive.hashCode(ProjectArchive.java:72)
	at ghidra.app.plugin.core.datamgr.tree.ArchiveNode.hashCode(ArchiveNode.java:229)
	at java.desktop/javax.swing.tree.TreePath.hashCode(TreePath.java:278)
	at java.base/java.util.Hashtable.get(Hashtable.java:381)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.getMapping(VariableHeightLayoutCache.java:693)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.getNodeForPath(VariableHeightLayoutCache.java:805)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.getExpandedState(VariableHeightLayoutCache.java:198)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.paint(BasicTreeUI.java:1391)
	at java.desktop/com.apple.laf.AquaTreeUI.paint(AquaTreeUI.java:129)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:852)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JSplitPane.paintChildren(JSplitPane.java:1034)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5318)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1656)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1631)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1569)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1336)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5266)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5076)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:878)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:861)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:861)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:834)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1897)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2024-Jan-30 1212 EST
Ghidra Version: 11.0.1
Java Home: /usr/local/Cellar/openjdk/20.0.1/libexec/openjdk.jdk/Contents/Home
JVM Version: Homebrew 20.0.1
OS: Mac OS X 12.7.2 x86_64
```

**Environment (please complete the following information):**
 - OS: Mac OS X 12.7.2 x86_64
 - Java Version: Homebrew 20.0.1
 - Ghidra Version: 11.0.1
 - Ghidra Origin: official GitHub distro

**Comment by mumbel** [comment]
Possible dup #6206

**Comment by virtuald** [comment]
Yes, that looks very similar. Did that one just randomly happen or does it happen in certain circumstances?

**Comment by mumbel** [comment]
I think it was a connected image, then the laptop slept, and then tried doing something with DTM which triggered the popup/exception

**Comment by ghidra1** [comment]
Was this case opening a remote Project Archive that was not checked-out?  If so, that would be an issue since we have no means of recovering a lost remote-object connection (known issue) and suggest sleep be disabled if persistent remote objects must remain open for extended periods (e.g., long-running multi-user merge).  For Project Archives this can also be avoided by keeping it checked-out.  

The resulting errors can be severe. In this case, an attempt to get the remote item silently fails and returns a null FileID which in turn causes the failure observed.  In addition, long ago FileIDs did not exist and method would return null for older files.  At a minimum, javadocs need to be updated to reflect possible null FileID and dependency on it should be corrected.  Although, I suspect getting past this would simply produce a subsequent remote-object exception at some point.

This response also applies to #6206

**Comment by mumbel** [comment]
I have one shared archive in the project, not checked out

**Comment by ghidra1** [comment]
Loosing the connection in this case is similar to the DomainFile no longer existing since we do not force a re-connect.  Even if we did and were able to re-acquire the FileID, the remote-object would be lost causing the ProjectArchive DomainObject to no longer be viable.

**Comment by virtuald** [comment]
I usually check out projects, so I'm pretty sure in my case that it was checked out (though, I can't say for certain). I'll try to pay attention to that when it happens again.
