### ISSUE TITLE
Unusual Mach-O binary can not be imported.

### ISSUE THREAD

**Issue by intrigus-lgtm** [NationalSecurityAgency/ghidra#6271]
**Describe the bug**
When parsing a Mach-O binary with corrupted LC_SUB_FRAMEWORK commands, ghidra fails.
NOTE: There may be further LC_XXX that ghidra can not handle correctly, but this was the first one I encountered.

**To Reproduce**
1. Import `command_injection`

**Expected behavior**
Importing does not fail.

**Screenshots**
![grafik](https://github.com/NationalSecurityAgency/ghidra/assets/60750685/aaea6081-84e1-4034-ad7d-321a0306f432)

**Attachments**
[command_injection.tar.gz](https://github.com/NationalSecurityAgency/ghidra/files/14473529/command_injection.tar.gz)

**Stacktrace**
```
Attempted to read string at 0xfffffffff050f826
java.io.EOFException: Attempted to read string at 0xfffffffff050f826
	at ghidra.app.util.bin.BinaryReader.readUntilNullTerm(BinaryReader.java:715)
	at ghidra.app.util.bin.BinaryReader.readString(BinaryReader.java:874)
	at ghidra.app.util.bin.BinaryReader.readAsciiString(BinaryReader.java:759)
	at ghidra.app.util.bin.format.macho.commands.LoadCommandString.<init>(LoadCommandString.java:37)
	at ghidra.app.util.bin.format.macho.commands.SubFrameworkCommand.<init>(SubFrameworkCommand.java:39)
	at ghidra.app.util.bin.format.macho.commands.LoadCommandFactory.getLoadCommand(LoadCommandFactory.java:90)
	at ghidra.app.util.bin.format.macho.MachHeader.parse(MachHeader.java:188)
	at ghidra.app.util.bin.format.macho.MachHeader.parse(MachHeader.java:150)
	at ghidra.app.util.opinion.MachoProgramBuilder.build(MachoProgramBuilder.java:118)
	at ghidra.app.util.opinion.MachoProgramBuilder.buildProgram(MachoProgramBuilder.java:110)
	at ghidra.app.util.opinion.MachoLoader.load(MachoLoader.java:97)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:887)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:98)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:395)
	at ghidra.plugin.importer.ImporterDialog.lambda$7(ImporterDialog.java:336)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
**Environment (please complete the following information):**
Build Date: 2024-Mar-03
Ghidra Version: 11.1
Java Home: /usr/lib/jvm/java-17-openjdk-amd64
JVM Version: Debian 17.0.10
OS: Linux 6.1.0-18-amd64 amd64
 - Ghidra Origin: locally built, **but 11.0 has the same problems.**

**Fix/Problem**
The problem appears that ghidra tries to parse an LC_SUB_FRAMEWORK load command that is clearly malformed.
This is not a problem for the actual Mach-O loader on macOS, because it simply ignores these commands:
https://github.com/clemensg/xnu/blob/9591534ce6579dad34365a4e45b9388f66f2f447/bsd/kern/mach_loader.c#L1414-L1418
I don't know how feasible it is for you to also just ignore the commands.

**Comment by intrigus-lgtm** [comment]
Yes, it does run without problems on an actual machine.
See here for more information:
https://github.com/spipm/BraekerCTF_2024_public/tree/main/challenges/binaries-reversing/injecting-commands

**Comment by ryanmkurtz** [comment]
@intrigus-lgtm, if you want to try again with the latest `master` branch, you can RE this binary now.

**Comment by intrigus-lgtm** [comment]
> @intrigus-lgtm, if you want to try again with the latest `master` branch, you can RE this binary now.

Thank you, just tried latest `master` and it works :tada:
