### ISSUE TITLE
The data is not legal for a JDOM attribute? Sorry to bug. Google is useless and so is trashgpt.

### ISSUE THREAD

**Issue by satandidnowrong** [NationalSecurityAgency/ghidra#6288]
The data "" is not legal for a JDOM attribute: 0x1 is not a legal XML character.
org.jdom.IllegalDataException: The data "" is not legal for a JDOM attribute: 0x1 is not a legal XML character.
	at org.jdom.Attribute.setValue(Attribute.java:491)
	at org.jdom.Attribute.<init>(Attribute.java:228)
	at org.jdom.Attribute.<init>(Attribute.java:251)
	at org.jdom.Element.setAttribute(Element.java:1149)
	at ghidra.app.util.opinion.LibrarySymbolTable.write(LibrarySymbolTable.java:495)
	at ghidra.app.util.opinion.LibraryLookupTable.createFile(LibraryLookupTable.java:176)
	at ghidra.app.util.opinion.LibraryLookupTable.createFile(LibraryLookupTable.java:127)
	at ghidra.app.util.opinion.AbstractOrdinalSupportLoader.processLibrary(AbstractOrdinalSupportLoader.java:114)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadLibraryFromSearchPaths(AbstractLibrarySupportLoader.java:655)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadLibraries(AbstractLibrarySupportLoader.java:533)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:104)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:395)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:336)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

---------------------------------------------------
Build Date: 2024-Jan-30 1212 EST
Ghidra Version: 11.0.1
Java Home: C:\Program Files\Eclipse Adoptium\jdk-17.0.10.7-hotspot
JVM Version: Eclipse Adoptium 17.0.10
OS: Windows 11 10.0 amd64

This is on executable import. May have japanese characters- is this the issue? Would changing java provider help? Thanks. This program is hnng.
Also why can't we drag and drop rearrange tabs in list view wtf lol.

**Comment by satandidnowrong** [comment]
I found this but I do not know how to apply the information. This seems like a java issue.

https://stackoverflow.com/questions/15958221/the-name-is-not-legal-for-jdom-xml-namespaces

**Comment by satandidnowrong** [comment]
I opened the exe in a hex editor and exported it
This seems to have fixed the issue. Still would like a native alternative. (ha.. native.. alterNATIVE)

**Comment by dragonmacher** [comment]
> Also why can't we drag and drop rearrange tabs in list view wtf lol.

Hard to believe, but this request does not come up very often.

**Comment by marcinjrojek** [comment]
> I opened the exe in a hex editor and exported it This seems to have fixed the issue. Still would like a native alternative. (ha.. native.. alterNATIVE)

How do you know which "0x1" byte to fix ?

**Comment by grappigegovert** [comment]
I ran into this issue as well when trying to open the main executable for the game "Hitman: World of Assassination" (free demo is available on steam if you need to test it).
The same executable imported fine on an older version of ghidra, so I ran a git bisect and it seems to be introduced by commit a31063dcb00c31e9400f7b851972933eefd6229d.
Reverting that commit from the current master makes the exe import without issue.

**Comment by nathan130200** [comment]
There's no fix for this yet?
