### ISSUE TITLE
RTTIWindowsClassRecoverer NullPointerException

### ISSUE THREAD

**Issue by llyama** [NationalSecurityAgency/ghidra#6348]
**Describe the bug**
Running the RecoverClassesFromRTTIScript.java script produces a NullPointerException

**To Reproduce**
1. Fresh Project
2. Auto Analyze (has PDB)
3. Run RecoverClassesFromRTTIScript.java
4. NullPointerException

**Expected behavior**
No exception and the script to finish successfully.

**Attachments**
I can't share the executable.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: Microsoft JDK 17.0.10
 - Ghidra Version: 11.0.1
 - Ghidra Origin: official GitHub distro

**Additional context**

Stack trace:
```
java.lang.reflect.InvocationTargetException
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1732)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:686)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:786)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:665)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:630)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:103)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:334)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "classrecovery.RTTIWindowsClassRecoverer.getSingleVirtualParentOffset(classrecovery.RecoveredClass)" is null
	at classrecovery.RTTIWindowsClassRecoverer.createClassStructureUsingRTTI(RTTIWindowsClassRecoverer.java:2408)
	at classrecovery.RTTIWindowsClassRecoverer.processDataTypes(RTTIWindowsClassRecoverer.java:2257)
	at classrecovery.RTTIWindowsClassRecoverer.createAndApplyClassStructures(RTTIWindowsClassRecoverer.java:2223)
	at classrecovery.RTTIWindowsClassRecoverer.createRecoveredClasses(RTTIWindowsClassRecoverer.java:209)
	at RecoverClassesFromRTTIScript.run(RecoverClassesFromRTTIScript.java:336)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:403)
	at ghidra.app.script.GhidraScript$1.analysisWorkerCallback(GhidraScript.java:385)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1726)
	... 8 more
```

It seems to be failing because of a class heirarchy 3 levels deep, with a virtual class at the root. It's a single inheritance chain.

A -> B -> C

Classes A and B have `inheritsVirtualAncestor = true`, with the virtual ancestor being C.

When it's recovering class A, it gets to `getSingleVirtualParentOffset`:

```
	public Integer getSingleVirtualParentOffset(RecoveredClass recoveredClass)
			throws CancelledException, MemoryAccessException, AddressOutOfBoundsException {

		List<RecoveredClass> virtualParentClasses = getVirtualParentClasses(recoveredClass);
		if (virtualParentClasses.size() != 1) {
			return NONE;
		}

		Map<RecoveredClass, Integer> parentOffsetMap = getBaseClassOffsetMap(recoveredClass);

		return parentOffsetMap.get(virtualParentClasses.get(0));

	}
```

`getVirtualParentClasses` returns a reference to class C, which is correct. But getBaseClassOffsetMap only returns class B, causing the null return value. The reason class C is not in the collection generated by `getBaseClassOffsetMap` is because of this code:

```
// Continue if the class has mult inh but base class is not on the parent list
//TODO: possibly update to include all base classes
if (!recoveredClass.getParentList().contains(baseClass)) {
	continue;
}
```

This filters out anything not in `getParentList()`, which from what I can tell is meant to be a list of _direct parents_ and won't include ancestors, like C. Simply removing this code makes it work, class C is included in the returned collection and the calling function returns class C. It seems like it all works. The structures look correct to me in Ghidra after it's complete.

I'm new to this so there could definitely be problems with removing that code.

**Comment by ghidra007** [comment]
@llyama Thank you for the great summary. Will take a look at your suggested fix.

**Comment by ghidra007** [comment]
I'm going to use your fix as it doesn't break anything as far as I can tell either. I also added a null check where the blow up happened. I considered leaving the code as is and just doing the null check but didn't have your use-case to test on to see what the resulting structure looked like. I'd be curious to know what the structures look like in both cases if you are able to share pics of them or describe them.  I'm not too concerned as I have been refactoring that code anyway so it will be changing  in a future release.

**Comment by llyama** [comment]
Thanks for looking into this. The inheritance chain in my case is `FXBeam : FXLightning : FX : TaskObject`.
When putting in a null check the structure looks like this:

![return none](https://github.com/NationalSecurityAgency/ghidra/assets/4733017/74aac5e4-506e-414b-86f5-c65c04e27c2e)

With my change:

![return TaskObject](https://github.com/NationalSecurityAgency/ghidra/assets/4733017/d01fa9e2-468f-4937-956a-e32861358aca)

I've only just started poking around in C++ but I've made a small program that reproduces the error. The heirarchy needs to be at least 4 levels. It fails recovering `FXBeam` when processing `FXLightning`. 

```
#include <iostream>

struct TaskObject {
    int d = 10;
    virtual void print() {
        std::cout << d;
    }
};

struct FX : virtual TaskObject {
    int c = 20;
    virtual void print() {
        std::cout << c;
    }

    virtual void print2() {
        std::cout << c;
    }
};

struct FXLightning : FX {
    int b = 30;
};

struct FXBeam : FXLightning {
    int a = 40;
    void print()
    {
        std::cout << a;
    }

    void print2() {
        std::cout << a;
    }
};

int main()
{
    auto beam = new FXBeam();
}
```

Compiled version: [rtti_repl.zip](https://github.com/NationalSecurityAgency/ghidra/files/14774108/rtti_repl.zip)

**Comment by ghidra007** [comment]
Thanks!
