### ISSUE TITLE
EOFException while importing a pe file

### ISSUE THREAD

**Issue by rhjdvsgsgks** [NationalSecurityAgency/ghidra#6380]
**Describe the bug**
importer crashed on importing a pe file ("x86","default","32","little","Delphi")

**To Reproduce**
1. import the dll with default config

**Expected behavior**
correctly imported

**Attachments**
i throught it may similar to #6236 . but if you still need the file to reproduce, please share me your gpg public key. so that i can sent it privately. (i dont want others know what im working on)

**Environment**
 - OS: linux 6.7
 - Java Version: 21.0.1
 - Ghidra Version: 11.0.2
 - Ghidra Origin: arch linux build

**Additional context**
```
java.io.EOFException: Attempted to read string at 0x70450
        at ghidra.app.util.bin.BinaryReader.readUntilNullTerm(BinaryReader.java:716)
        at ghidra.app.util.bin.BinaryReader.readString(BinaryReader.java:874)
        at ghidra.app.util.bin.BinaryReader.readAsciiString(BinaryReader.java:759)
        at ghidra.app.util.bin.format.pe.ExportDataDirectory.parse(ExportDataDirectory.java:272)
        at ghidra.app.util.bin.format.pe.DataDirectory.processDataDirectory(DataDirectory.java:80)
        at ghidra.app.util.bin.format.pe.ExportDataDirectory.<init>(ExportDataDirectory.java:83)
        at ghidra.app.util.bin.format.pe.OptionalHeaderImpl.processDataDirectories(OptionalHeaderImpl.java:259)
        at ghidra.app.util.opinion.PeLoader.load(PeLoader.java:128)
        at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:887)
        at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:98)
        at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
        at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:395)
        at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:336)
        at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
        at ghidra.util.task.Task.monitoredRun(Task.java:134)
        at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by ryanmkurtz** [comment]
Alternatively, you could push the sample to a new GitHub private repo and invite just me to it.  I will need the binary to debug the issue.

**Comment by ryanmkurtz** [comment]
I got it, thanks.  Looking into it now...

**Comment by ryanmkurtz** [comment]
The general issue is that the sections have a lot of padding, and some of the data directories point to this padding.  We weren't correctly handling that in a couple of cases.  The fix is working its way through our review and merge process.
