### ISSUE TITLE
Self-referencing/recursive function type fields cause a StackOverflowError when being exported.

### ISSUE THREAD

**Issue by Varriount** [NationalSecurityAgency/ghidra#6491]
**Describe the bug**
Exporting a structure type containing a "self-referencing" function type field (e.g., `void TaskCallback(TaskCallback *callback)`) causes a StackOverflowError.

**To Reproduce**
1. Create a function type with no parameters (`void TaskCallback()`).
2. Modify the function type to accept itself as a parameter (`void TaskCallback(TaskCallback *callback)`).
3. Create a structure type with the function type pointer as a field.
4. Export the structure and function type to a header.

**Expected behavior**
The structure and function type should both export successfully to a file.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: OpenJDK 17.0.2
 - Ghidra Version: 11.0.4
 - Ghidra Origin: Official GitHub Distribution

**Comment by ryanmkurtz** [comment]
```java
	at ghidra.program.model.data.DataTypeWriter.getTypeDeclaration(DataTypeWriter.java:552)
	at ghidra.program.model.data.DataTypeWriter.getParameterListString(DataTypeWriter.java:877)
	at ghidra.program.model.data.DataTypeWriter.getFunctionPointerString(DataTypeWriter.java:850)
	at ghidra.program.model.data.DataTypeWriter.getTypeDeclaration(DataTypeWriter.java:552)
	at ghidra.program.model.data.DataTypeWriter.getParameterListString(DataTypeWriter.java:877)
	at ghidra.program.model.data.DataTypeWriter.getFunctionPointerString(DataTypeWriter.java:850)
	at ghidra.program.model.data.DataTypeWriter.getTypeDeclaration(DataTypeWriter.java:552)
	at ghidra.program.model.data.DataTypeWriter.getParameterListString(DataTypeWriter.java:877)
	at ghidra.program.model.data.DataTypeWriter.getFunctionPointerString(DataTypeWriter.java:850)
```
