### ISSUE TITLE
Problem launching decompiler(?)

### ISSUE THREAD

**Issue by EmosewaMC** [NationalSecurityAgency/ghidra#6546]
**Describe the bug**
Ghidra logs said to report it, so here I am

**To Reproduce**
1. pressed D on second instruction of a non-decompiled function
2. get error(?)

**Expected behavior**
No error ig

**Screenshots**

**Attachments**
here is the log ghidra said to report
```
2024-05-20 03:43:43 ERROR (DecompileProcess) Problem launching decompiler: Please report this stack trace to the Ghidra Team java.io.IOException: Cannot run program "C:\ghidra_11.0.1_PUBLIC\Ghidra\Features\Decompiler\os\win_x86_64\decompile.exe": CreateProcess error=5, Access is denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.lang.Runtime.exec(Runtime.java:615)
	at java.base/java.lang.Runtime.exec(Runtime.java:474)
	at ghidra.app.decompiler.DecompileProcess.setup(DecompileProcess.java:137)
	at ghidra.app.decompiler.DecompileProcess.registerProgram(DecompileProcess.java:433)
	at ghidra.app.decompiler.DecompInterface.initializeProcess(DecompInterface.java:291)
	at ghidra.app.decompiler.DecompInterface.openProgram(DecompInterface.java:402)
	at WindowsResourceReference.setUpDecompiler(WindowsResourceReference.java:784)
	at WindowsResourceReference.run(WindowsResourceReference.java:129)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:403)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:258)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:236)
	at ghidra.app.script.GhidraScript.runScript(GhidraScript.java:856)
	at ghidra.app.script.GhidraScript.runScript(GhidraScript.java:766)
	at ghidra.app.plugin.prototype.MicrosoftCodeAnalyzerPlugin.WindowsResourceReferenceAnalyzer.runScript(WindowsResourceReferenceAnalyzer.java:103)
	at ghidra.app.plugin.prototype.MicrosoftCodeAnalyzerPlugin.WindowsResourceReferenceAnalyzer.added(WindowsResourceReferenceAnalyzer.java:72)
	at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:186)
	at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:686)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:786)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:665)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:630)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.taskCompleted(ToolTaskManager.java:396)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:105)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:334)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: CreateProcess error=5, Access is denied
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:494)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 27 more
```

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 18.0.2.1
 - Ghidra Version: 11.0.1
 - Ghidra Origin: Downloaded from Release

**Additional context**
Probably not useful, but i would like to assume if you put this log line in there, then this is what is wanted.

Feel free to close if its a non-issue.  Can provide further details if necessary.

**Comment by ryanmkurtz** [comment]
Looks like you don't have executable permission on the `decompiler.exe` binary.  What happens if you open up a command prompt and try to run `<Ghidra Install Dir>\Ghidra\Features\Decompiler\os\win_x86_64\decompile.exe` directly?

**Comment by EmosewaMC** [comment]
> Looks like you don't have executable permission on the `decompiler.exe` binary. What happens if you open up a command prompt and try to run `<Ghidra Install Dir>\Ghidra\Features\Decompiler\os\win_x86_64\decompile.exe` directly?

The decompiler ran without issue just after this within ghidra, should I still check via cli?

**Comment by ryanmkurtz** [comment]
No, that's ok.  I am going to close this because I'm guessing it wasn't an issue with Ghidra, but with some security feature of your OS.
