### ISSUE TITLE
A lot of functionality suddenly disappeared

### ISSUE THREAD

**Issue by hippietrail** [NationalSecurityAgency/ghidra#6798]
**Describe the bug**
I was working on my Loader extension for hours and about to push new features to GitHub after final testing when I noticed many keys were suddenly no longer working.

Then I noticed I can't do those operations from the GUI either. Things like 'd' for disassemble, changing data types, etc.

Restarting Ghidra, exiting Eclipse and running Ghidra outside it, closing a lot of apps that were using memory, all had no effect.

Maybe I hit some key combination that turned things off? Maybe some settings file got corrupted?

I saw no error messages or anything related in the logs when running my extension.

**To Reproduce**
Sadly, I do not know.

**Expected behavior**
Missing functionalities to return.

**Screenshots**
If there's something I should grab and attach, let me know.

**Environment (please complete the following information):**
 - OS: macOS Sonoma 14.4 (23E214)
 - Java Version: Version 8 Update 421 (build 1.8.0_421-b09)
 - Ghidra Version: 11.1.2
 - Ghidra Origin: official GitHub distro

**Additional context**

**Comment by hippietrail** [comment]
I downloaded a second copy of Ghidra and unarchived it in a different folder and opened by double-clicking on the new `ghidraRun` - it behaves identically.

I suspect something has changed/broken in my user settings?

**Comment by hippietrail** [comment]
Nothing in my `~/.ghidra/` directory seems to have been changed more recently than four or five days ago.

**Comment by hippietrail** [comment]
I have found the log and see nothing I think caused it. But this one looks the most serious. I assumed it was standard every time I accidentally start a new Ghidra from inside Eclipse while forgetting one is already open.

But maybe it's not that and it is something serious?
```log
2024-08-09 19:44:53 ERROR (FrontEndPlugin) Unexpected Exception: java.util.ConcurrentModificationException java.lang.RuntimeException: java.util.ConcurrentModificationException
	at ghidra.framework.plugintool.Plugin.cleanup(Plugin.java:276)
	at ghidra.framework.plugintool.PluginManager.dispose(PluginManager.java:104)
	at ghidra.framework.plugintool.PluginTool.dispose(PluginTool.java:515)
	at ghidra.framework.project.tool.GhidraTool.dispose(GhidraTool.java:196)
	at ghidra.framework.plugintool.PluginToolAccessUtils.dispose(PluginToolAccessUtils.java:35)
	at ghidra.framework.project.tool.WorkspaceImpl.dispose(WorkspaceImpl.java:252)
	at ghidra.framework.project.tool.ToolManagerImpl.dispose(ToolManagerImpl.java:440)
	at ghidra.framework.project.DefaultProject.close(DefaultProject.java:391)
	at ghidra.framework.main.FileActionManager.closeProject(FileActionManager.java:451)
	at ghidra.framework.main.FrontEndPlugin.closeActiveProject(FrontEndPlugin.java:454)
	at ghidra.framework.main.FrontEndTool.canClose(FrontEndTool.java:404)
	at ghidra.framework.plugintool.PluginTool.close(PluginTool.java:1211)
	at ghidra.framework.plugintool.PluginToolMacQuitHandler.lambda$install$0(PluginToolMacQuitHandler.java:56)
	at java.desktop/com.apple.eawt._AppEventHandler$_QuitDispatcher.performUsing(_AppEventHandler.java:431)
	at java.desktop/com.apple.eawt._AppEventHandler$_QuitDispatcher.performUsing(_AppEventHandler.java:420)
	at java.desktop/com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:552)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605)
	at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1633)
	at ghidra.plugins.fsbrowser.FileSystemBrowserPlugin.dispose(FileSystemBrowserPlugin.java:126)
	at ghidra.framework.plugintool.Plugin.cleanup(Plugin.java:265)
	... 28 more
 ```

**Comment by dev747368** [comment]
It sounds like you ran into an exception when the codebrowser tool was shutting down and saving its state.
When that happens the offending plugin gets removed from tool's configuration.

Probably the easiest way to deal with this is to create a new codebrowser tool button in your front end (project window) and discard the old one.

Tools | Import Default Tools | select the CodeBrowser and click ok.  You will now have a second green headed dragon button.

**Comment by hippietrail** [comment]
Ah yes I do remember some warnings about that now! I tried a few of the options and when they didn't seem to work I went with the "terminate" option. My eyes were burning after a very long coding session so I forgot those details. Will try when I get back to my main laptop...

**Comment by hippietrail** [comment]
Apparently some other functionality also disappeared. I can no longer 'Import' from the project window. I can 'import' from a CodeBrowser window. But that means I can't start a new project and add anything to it, I have to add to other projects that are not related )-: I'll ask a new qustion.

**Comment by dragonmacher** [comment]
If you can't import from the Front End project window, that implies somehow you are missing plugins there too.  You can check this by using File -> Configure and then making sure all of the plugins you need are installed.  In this case, make sure the `Importer Plugin` is installed.
