### ISSUE TITLE
Can't import files into project window

### ISSUE THREAD

**Issue by hippietrail** [NationalSecurityAgency/ghidra#6801]
**Describe the bug**
I had [a recent issue](https://github.com/NationalSecurityAgency/ghidra/issues/6798) that caused my CodeBrowser tool to corrupt its state while shutting down. I was able to mostly fix that with the advice in the other issue, creating a new CodeBrowser tool button in the project window.

But that didn't bring back all lost functionality. I noticed I can't import files from the project window. The 'i' key doesn't work and there's nothing in the project window's menus.

**Expected behavior**
I should be able to make new projects and import files. Drag and drop also doesn't work but I don't know if that was supported before or not.

**Screenshots**
I think there was an 'import' option in the file menu before but I'm not sure as I mostly used the 'i' key to import. Here's a screenshot of what the file menu looks like now:
<img width="189" alt="image" src="https://github.com/user-attachments/assets/c05a1735-643d-4902-866c-361173d7fba0">

**Attachments**
Here's the log from the previous issue which probably also led to this problem:
```
2024-08-09 19:44:53 ERROR (FrontEndPlugin) Unexpected Exception: java.util.ConcurrentModificationException java.lang.RuntimeException: java.util.ConcurrentModificationException
	at ghidra.framework.plugintool.Plugin.cleanup(Plugin.java:276)
	at ghidra.framework.plugintool.PluginManager.dispose(PluginManager.java:104)
	at ghidra.framework.plugintool.PluginTool.dispose(PluginTool.java:515)
	at ghidra.framework.project.tool.GhidraTool.dispose(GhidraTool.java:196)
	at ghidra.framework.plugintool.PluginToolAccessUtils.dispose(PluginToolAccessUtils.java:35)
	at ghidra.framework.project.tool.WorkspaceImpl.dispose(WorkspaceImpl.java:252)
	at ghidra.framework.project.tool.ToolManagerImpl.dispose(ToolManagerImpl.java:440)
	at ghidra.framework.project.DefaultProject.close(DefaultProject.java:391)
	at ghidra.framework.main.FileActionManager.closeProject(FileActionManager.java:451)
	at ghidra.framework.main.FrontEndPlugin.closeActiveProject(FrontEndPlugin.java:454)
	at ghidra.framework.main.FrontEndTool.canClose(FrontEndTool.java:404)
	at ghidra.framework.plugintool.PluginTool.close(PluginTool.java:1211)
	at ghidra.framework.plugintool.PluginToolMacQuitHandler.lambda$install$0(PluginToolMacQuitHandler.java:56)
	at java.desktop/com.apple.eawt._AppEventHandler$_QuitDispatcher.performUsing(_AppEventHandler.java:431)
	at java.desktop/com.apple.eawt._AppEventHandler$_QuitDispatcher.performUsing(_AppEventHandler.java:420)
	at java.desktop/com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:552)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605)
	at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1633)
	at ghidra.plugins.fsbrowser.FileSystemBrowserPlugin.dispose(FileSystemBrowserPlugin.java:126)
	at ghidra.framework.plugintool.Plugin.cleanup(Plugin.java:265)
	... 28 more
```

**Environment (please complete the following information):**
 - OS: macOS Sonoma 14.4 (23E214)
 - Java Version: Version 8 Update 421 (build 1.8.0_421-b09)
 - Ghidra Version: 11.1.2
 - Ghidra Origin: official GitHub distro

**Comment by hippietrail** [comment]
RIght clicking / control-clicking in the project window also brings up no context menu.

**Comment by dev747368** [comment]
Check in File | Configure | "Ghidra Core" Configure, make sure the Importer plugin is enabled.  (everything in the Ghidra Core category should be enabled)

This is the same thing as what happened to your code browser tool, just seemed easier to just reimport a new copy of the tool button.

**Comment by hippietrail** [comment]
It is enabled actually.
<img width="578" alt="image" src="https://github.com/user-attachments/assets/3ba5dabc-fb4e-4951-b9b4-d498654f0a38">
Importing still works from the listing window, just not from the project window anymore.

**Comment by dev747368** [comment]
Make sure you are using the "File" menu from the project window, not the code browser tool window.
