### ISSUE TITLE
How to fix Unable to locate script class: Lua2CPPAnalysis.java

### ISSUE THREAD

**Issue by yvetalkyogre** [NationalSecurityAgency/ghidra#6815]
I tried running a script Lua2CPPAAnalysis.java and it wont work and it says "Unable to locate script class: Lua2CPPAnalysis.java". I tried using JDK 22 and JKD 11 and both gave this. How do i fix this?

**Comment by yvetalkyogre** [comment]
solved it

**Comment by yvetalkyogre** [comment]
Got another error. This is what it gave: 

java.lang.NullPointerException
	at Lua2CPPAnalysis.makeStatuses(Lua2CPPAnalysis.java:482)
	at Lua2CPPAnalysis.run(Lua2CPPAnalysis.java:732)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:379)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:234)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:212)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:47)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
