### ISSUE TITLE
aContainer is not a focus cycle root of aComponent

### ISSUE THREAD

**Issue by mumbel** [NationalSecurityAgency/ghidra#6838]
clicked help -> component diagnostics and went into an infinite loop, had to hard kill java process

```
aContainer is not a focus cycle root of aComponent
java.lang.IllegalArgumentException: aContainer is not a focus cycle root of aComponent
	at java.desktop/javax.swing.SortingFocusTraversalPolicy.getComponentAfter(SortingFocusTraversalPolicy.java:281)
	at java.desktop/javax.swing.LayoutFocusTraversalPolicy.getComponentAfter(LayoutFocusTraversalPolicy.java:112)
	at ghidra.docking.util.ComponentInfoDialog$ComponentInfo.computeTraversalComps(ComponentInfoDialog.java:730)
	at ghidra.docking.util.ComponentInfoDialog$ComponentInfo.<init>(ComponentInfoDialog.java:702)
	at ghidra.docking.util.ComponentInfoDialog.findComponents(ComponentInfoDialog.java:311)
	at ghidra.docking.util.ComponentInfoDialog.buildComponentModel(ComponentInfoDialog.java:285)
	at ghidra.docking.util.ComponentInfoDialog.setRootContainer(ComponentInfoDialog.java:280)
	at ghidra.docking.util.ComponentInfoDialog.selectFocusedComponentInTable(ComponentInfoDialog.java:269)
	at ghidra.docking.util.ComponentInfoDialog.propertyChange(ComponentInfoDialog.java:214)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:336)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at java.desktop/java.awt.KeyboardFocusManager.firePropertyChange(KeyboardFocusManager.java:1489)
	at java.desktop/java.awt.KeyboardFocusManager.setGlobalPermanentFocusOwner(KeyboardFocusManager.java:784)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:664)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4877)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2024-Jul-09 1157 EDT
Ghidra Version: 11.1.2
Java Home: /usr/lib/jvm/java-21-openjdk-amd64
JVM Version: Ubuntu 21.0.4
OS: Linux 6.8.0-40-generic amd64
```

**Comment by dragonmacher** [comment]
Did you have any extra info about what windows or component providers were open?   Do you have any sort of custom plugins open?

**Comment by mumbel** [comment]
No I don't think I had any windows besides frontend, codebrowser, and this window open at the time.  no additional plugins/extensions even installed

I was just looking for the 'about' output and clicked by mistake in the menu, and closing it caused this inf popup
