### ISSUE TITLE
NullPointerException trying to load pdb

### ISSUE THREAD

**Issue by epinter** [NationalSecurityAgency/ghidra#6843]
**Describe the bug**
A NullPointerException is thrown when trying to load a PDB using PDB Universal.

**To Reproduce**
1. Go to File, click Load PDB File
2. Select a PDB file
3. Select Data type only
4. Load with PDB Universal
5. The error is shown.

**Expected behavior**
The data types from PDB should be imported.

**Environment (please complete the following information):**
 - OS: Windows
 - Java Version: 21
 - Ghidra Version: 11.2-DEV
 - Ghidra Origin: locally built, master branch

**Additional context**
```
Cannot invoke "ghidra.app.util.bin.format.pdb2.pdbreader.PdbDebugInfo.getSegmentMapList()" because "debugInfo" is null java.lang.reflect.InvocationTargetException
        at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1705)
        at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1586)
        at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:660)
        at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:760)
        at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:639)
        at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:604)
        at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:55)
        at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:33)
        at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:103)
        at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:351)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke "ghidra.app.util.bin.format.pdb2.pdbreader.PdbDebugInfo.getSegmentMapList()" because "debugInfo" is null
        at ghidra.app.util.pdb.pdbapplicator.PdbAddressManager.determineMemoryBlocks(PdbAddressManager.java:361)
        at ghidra.app.util.pdb.pdbapplicator.PdbAddressManager.initialize(PdbAddressManager.java:105)
        at ghidra.app.util.pdb.pdbapplicator.DefaultPdbApplicator.doPdbPreWork(DefaultPdbApplicator.java:602)
        at ghidra.app.util.pdb.pdbapplicator.DefaultPdbApplicator.applyDataTypesAndMainSymbolsAnalysis(DefaultPdbApplicator.java:285)
        at ghidra.app.plugin.core.analysis.PdbUniversalAnalyzer.doAnalysis(PdbUniversalAnalyzer.java:211)
        at pdb.LoadPdbTask.parseWithNewParser(LoadPdbTask.java:145)
        at pdb.LoadPdbTask$2.analysisWorkerCallback(LoadPdbTask.java:85)
        at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1699)
        ... 10 more
```

**Comment by ghizard** [comment]
Thanks for finding this a providing the fix.  Most likely the result of merging the long-running branch (GP-1777).

**Comment by epinter** [comment]
> Thanks for finding this a providing the fix. Most likely the result of merging the long-running branch (GP-1777).

Yes, I saw long commits after that fix. Sometimes is easy to forget this small conditions in the middle of big changes.
