### ISSUE TITLE
RecoverClassesFromRTTIScript stops with CodeUnitInsertionException

### ISSUE THREAD

**Issue by epinter** [NationalSecurityAgency/ghidra#6848]
**Describe the bug**
RecoverClassesFromRTTIScript stops with "CodeUnitInsertionException: Conflicting data exists at address"

**To Reproduce**
1. Do AutoAnalysis with PE RTTI
2. Run RecoverClassesFromRTTIScript 

**Expected behavior**
The script should finish without errors.

**Screenshots**
![Screenshot 2024-08-23 110211](https://github.com/user-attachments/assets/3e4eb84a-e84f-4d2f-8483-22d3987d0736)

**Environment (please complete the following information):**
 - OS: Windows
 - Java Version: 21
 - Ghidra Version: 11.2-DEV
 - Ghidra Origin: locally built, master branch

**Additional context**
```
java.lang.reflect.InvocationTargetException
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1705)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1586)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:660)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:760)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:639)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:604)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:55)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:33)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:103)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:351)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: ghidra.program.model.util.CodeUnitInsertionException: Conflicting data exists at address 1452beac0 to 1452beac7
	at ghidra.program.database.code.CodeManager.checkValidAddressRange(CodeManager.java:1954)
	at ghidra.program.database.code.CodeManager.createCodeUnit(CodeManager.java:2031)
	at ghidra.program.database.ListingDB.createData(ListingDB.java:284)
	at ghidra.program.flatapi.FlatProgramAPI.createData(FlatProgramAPI.java:1717)
	at classrecovery.RecoveredClassHelper.fillInAndApplyVftableStructAndNameVfunctions(RecoveredClassHelper.java:4532)
	at classrecovery.RTTIWindowsClassRecoverer.processDataTypes(RTTIWindowsClassRecoverer.java:2257)
	at classrecovery.RTTIWindowsClassRecoverer.createAndApplyClassStructures(RTTIWindowsClassRecoverer.java:2193)
	at classrecovery.RTTIWindowsClassRecoverer.createRecoveredClasses(RTTIWindowsClassRecoverer.java:180)
	at RecoverClassesFromRTTIScript.run(RecoverClassesFromRTTIScript.java:307)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:405)
	at ghidra.app.script.GhidraScript$1.analysisWorkerCallback(GhidraScript.java:387)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1699)
	... 10 more

```

**Comment by epinter** [comment]
I tested with two different binaries, happens with one and not with the other.

**Comment by ghidra007** [comment]
Do you see what is different about the one it is happening on?

**Comment by epinter** [comment]
> Do you see what is different about the one it is happening on?

The one which works fine is the executable from Skyrim Special Edition (SkyrimSE.exe), the binary that RTTI script don't analyse is Starfield.exe. While SkyrimSE.exe has 33.7MB, Starfield.exe has 104MB. The script shows around 7700 classes for SkyrimSE.exe and 32000 for Starfield.exe.

I don't know what to look to help more.

**Comment by mirh** [comment]
I was also seeing the same error, already in the file import step, with Just Cause (JustCause.exe)
