### ISSUE TITLE
Index out of bound exception when importing .lib file

### ISSUE THREAD

**Issue by leechristensen** [NationalSecurityAgency/ghidra#6862]
**Describe the bug**
The following exception is thrown when batch importing an older Borland .lib file into a project:
```
Index 16459 out of bounds for length 417
java.lang.IndexOutOfBoundsException: Index 16459 out of bounds for length 417
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at ghidra.app.util.opinion.OmfLoader.processPublicSymbols(OmfLoader.java:452)
	at ghidra.app.util.opinion.OmfLoader.load(OmfLoader.java:144)
	at ghidra.app.util.opinion.AbstractProgramWrapperLoader.loadProgram(AbstractProgramWrapperLoader.java:76)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.plugins.importer.tasks.ImportBatchTask.doImportApp(ImportBatchTask.java:152)
	at ghidra.plugins.importer.tasks.ImportBatchTask.doImportBatchGroup(ImportBatchTask.java:128)
	at ghidra.plugins.importer.tasks.ImportBatchTask.doBatchImport(ImportBatchTask.java:117)
	at ghidra.plugins.importer.tasks.ImportBatchTask.run(ImportBatchTask.java:92)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

The file being imported is `bdtawrl.lib` file from the Borland 5.02 compiler and [can be found here](https://github.com/leechristensen/tribes-build-image/blob/main/BC5/LIB/bdtawrl.lib).

**To Reproduce**
1. Open Ghidra
2. Create a project and try and import the `bdtawrl.lib` file
3. When prompted, perform a batch import.
4. Upon doing so, you will see the error.

**Expected behavior**
The .lib to import successuflly.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: OpenJDK Runtime Environment Corretto-21.0.3.9.1
 - Ghidra Version: 11.1.2
 - Ghidra Origin: official GitHub distro

**Comment by ryanmkurtz** [comment]
Thanks, I have a fix...just doing some additional testing.
