### ISSUE TITLE
Unable to read past EOF exception when importing file

### ISSUE THREAD

**Issue by Cnly** [NationalSecurityAgency/ghidra#6864]
**Describe the bug**

A sample executable file from [one of IDA Pro's official tutorials](https://hex-rays.com/products/ida/support/tutorials/unpack_pe/manual/) can't be imported into Ghidra.

```
Unable to read past EOF: 2465, 4
java.io.IOException: Unable to read past EOF: 2465, 4
	at ghidra.app.util.bin.FileByteProvider.ensureBounds(FileByteProvider.java:267)
	at ghidra.app.util.bin.FileByteProvider.readBytes(FileByteProvider.java:121)
	at ghidra.formats.gfilesystem.RefdByteProvider.readBytes(RefdByteProvider.java:95)
	at ghidra.app.util.bin.BinaryReader.readInt(BinaryReader.java:932)
	at ghidra.app.util.bin.format.pe.ImportDescriptor.<init>(ImportDescriptor.java:64)
	at ghidra.app.util.bin.format.pe.ImportDataDirectory.parse(ImportDataDirectory.java:243)
	at ghidra.app.util.bin.format.pe.DataDirectory.processDataDirectory(DataDirectory.java:80)
	at ghidra.app.util.bin.format.pe.ImportDataDirectory.<init>(ImportDataDirectory.java:46)
	at ghidra.app.util.bin.format.pe.OptionalHeaderImpl.processDataDirectories(OptionalHeaderImpl.java:272)
	at ghidra.app.util.opinion.PeLoader.load(PeLoader.java:130)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:864)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:98)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:395)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:338)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)

---------------------------------------------------
Build Date: 2024-Jul-09 1157 EDT
Ghidra Version: 11.1.2
Java Home: /opt/homebrew/Cellar/openjdk/22.0.2/libexec/openjdk.jdk/Contents/Home
JVM Version: Homebrew 22.0.2
OS: Mac OS X 14.6.1 aarch64
```

**Attachments**

The file can be downloaded [here](https://hex-rays.com/wp-content/uploads/2019/12/test00.zip) (unpack twice with the password 123)

**Environment (please complete the following information):**
- Ghidra Version: 11.1.2
- JVM Version: Homebrew 22.0.2
- OS: Mac OS X 14.6.1 aarch64
- Ghidra Origin: Homebrew

**Comment by chf0x** [comment]
One more example where ghidra fails with `Java.io.IOException: Unable to read past EOF`

[example.zip](https://github.com/user-attachments/files/20575968/example.zip)

**Comment by ryanmkurtz** [comment]
> One more example where ghidra fails with `Java.io.IOException: Unable to read past EOF`
> 
> [example.zip](https://github.com/user-attachments/files/20575968/example.zip)

@chf0x This turns out to be an unrelated issue...can you open up a new issue for it please?

**Comment by ryanmkurtz** [comment]
> > One more example where ghidra fails with `Java.io.IOException: Unable to read past EOF`
> > [example.zip](https://github.com/user-attachments/files/20575968/example.zip)
> 
> [@chf0x](https://github.com/chf0x) This turns out to be an unrelated issue...can you open up a new issue for it please?

Actually you can disregard this...I'll address them both in the same issue.
