### ISSUE TITLE
java.lang.NullPointerException on import of Mach-O 64-bit executable arm64e

### ISSUE THREAD

**Issue by ro-achterberg** [NationalSecurityAgency/ghidra#6865]
**Describe the bug**
Attempted to import a Mach-O 64-bit executable arm64e as a Single file. It processes up to the "Processing section markup..." stage before it aborts the import with the error message "Error importing file: com.apple.kernel".

**To Reproduce**
1. Start a new project.
2. Import a file by typing 'i'. The file that causes the exception was of format Mac OS X Mach-O and language AARCH64:LE:64:AppleSilicon:default
3. Answer "Single file" in the "Container File Detected" dialog, then hit OK.
4. Observe it processing up until the "Processing section markup..." stage, before exiting with the error.

**Expected behavior**
The file ought to be added to the "Active Project: <redacted>" pane.

**Screenshots**
```java
java.lang.NullPointerException: Cannot invoke "ghidra.program.model.mem.MemoryBlock.getEnd()" because the return value of "ghidra.program.model.mem.Memory.getBlock(ghidra.program.model.address.Address)" is null
java.io.IOException: java.lang.NullPointerException: Cannot invoke "ghidra.program.model.mem.MemoryBlock.getEnd()" because the return value of "ghidra.program.model.mem.Memory.getBlock(ghidra.program.model.address.Address)" is null
	at ghidra.app.util.opinion.MachoLoader.load(MachoLoader.java:120)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:864)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:98)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:395)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:338)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.NullPointerException: Cannot invoke "ghidra.program.model.mem.MemoryBlock.getEnd()" because the return value of "ghidra.program.model.mem.Memory.getBlock(ghidra.program.model.address.Address)" is null
	at ghidra.app.util.opinion.MachoProgramBuilder.fixupProgramTree(MachoProgramBuilder.java:437)
	at ghidra.app.util.opinion.MachoProgramBuilder.build(MachoProgramBuilder.java:170)
	at ghidra.app.util.opinion.MachoPrelinkProgramBuilder.build(MachoPrelinkProgramBuilder.java:79)
	at ghidra.app.util.opinion.MachoPrelinkProgramBuilder.buildProgram(MachoPrelinkProgramBuilder.java:72)
	at ghidra.app.util.opinion.MachoLoader.load(MachoLoader.java:107)
	... 11 more
```

---------------------------------------------------
Build Date: 2024-Jul-09 1157 EDT
Ghidra Version: 11.1.2
Java Home: /Library/Java/JavaVirtualMachines/jdk-22.jdk/Contents/Home
JVM Version: Oracle Corporation 22.0.2
OS: Mac OS X 14.5 x86_64

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: [e.g. macOS 14.5]
 - Java Version: [e.g. 22.0.2]
 - Ghidra Version: [e.g. 11.1.2]
 - Ghidra Origin: official GitHub distro

**Additional context**
N/A

**Comment by ryanmkurtz** [comment]
Can you please attach the file you are trying to import?

**Comment by ro-achterberg** [comment]
Hi Ryan,

Thanks for getting back to us to quick. Is there any way I can share the 
file with you privately?

Best,
Ro

**Comment by ryanmkurtz** [comment]
You could make a private github repo and invite me to it if you want.

**Comment by ro-achterberg** [comment]
Done.

29 aug. 2024 16:04:02 Ryan Kurtz ***@***.***>:

**Comment by ryanmkurtz** [comment]
Got it.  I was able to reproduce the problem.  I'll take a look at it more after I finish up the current thing I'm fixing.
