### ISSUE TITLE
.exe import error: Specified length extends beyond file bytes length

### ISSUE THREAD

**Issue by 0xNF** [NationalSecurityAgency/ghidra#6889]
**Describe the bug**

Related: #1371, #2496

I'm trying to import Windows 95 installer (SETUP.EXE) binary with the default settings but get an import error. The linked issues suggested that Ghidra itself was patched to fix this, but those issues are 2+ years old and the most recent release build seems to still have the same or similar issue.

Binja version 4.1.5902 loads it fine.

**To Reproduce**
1. Import exe file
2. Keep default import settings
3. Import
4. Get error

**Expected behavior**
To import successfully. But import fails with error:

```text
Specified length extends beyond file bytes length
java.lang.IndexOutOfBoundsException: Specified length extends beyond file bytes length
	at ghidra.program.database.mem.MemoryMapDB.checkFileBytesRange(MemoryMapDB.java:786)
	at ghidra.program.database.mem.MemoryMapDB.createInitializedBlock(MemoryMapDB.java:749)
	at ghidra.app.util.MemoryBlockUtils.createInitializedBlock(MemoryBlockUtils.java:227)
	at ghidra.app.util.opinion.NeLoader.processResourceTable(NeLoader.java:356)
	at ghidra.app.util.opinion.NeLoader.load(NeLoader.java:131)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:864)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:98)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:395)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:338)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Screenshots**
<img src="https://github.com/user-attachments/assets/61f902fa-629c-4368-a93b-de59cfb4a27f" height=250>
<img src="https://github.com/user-attachments/assets/870c8687-f101-41dd-9c78-5cb0b7a611f9" height=500>

**Attachments**
<details>
<summary>Here's a hexdump of the file up to 0x900</summary>

```
Hex View  00 01 02 03 04 05 06 07  08 09 0A 0B 0C 0D 0E 0F
 
00000000  4D 5A FF 00 05 00 00 00  20 00 00 00 FF FF 00 00  MZ...... .......
00000010  00 00 00 00 00 00 00 00  40 00 00 00 01 00 00 00  ........@.......
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 06 00 00  ................
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000060  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000080  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000090  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000000A0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000000B0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000000C0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000000D0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000000E0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000000F0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000100  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000110  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000120  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000130  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000140  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000150  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000160  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000170  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000180  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000190  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000001A0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000001B0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000001C0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000001D0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000001E0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000001F0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000200  8C D8 33 DB 8E D0 8B E3  53 50 B8 0F 01 50 CB B1  ..3.....SP...P..
00000210  20 B8 01 00 D3 D8 83 F8  01 74 0D BA 1E 03 B4 09   ........t......
00000220  CD 21 B0 01 B4 4C CD 21  B4 30 CD 21 3C 03 73 05  .!...L.!.0.!<.s.
00000230  BA 1E 03 EB E9 8E 06 2C  00 33 C0 8B F8 B9 FF FF  .......,.3......
00000240  26 81 3D 50 41 75 16 26  81 7D 02 54 48 75 0E 26  &.=PAu.&.}.THu.&
00000250  80 7D 04 3D 75 07 8D 75  05 89 36 9B 03 26 81 3D  .}.=u..u..6..&.=
00000260  77 69 75 1C 26 81 7D 02  6E 64 75 14 26 81 7D 04  wiu.&.}.ndu.&.}.
00000270  69 72 75 0C 26 80 7D 06  3D 75 05 BA 49 03 EB 9E  iru.&.}.=u..I...
00000280  F2 AE 26 38 05 75 B9 8D  7D 03 89 3E 9D 03 B4 19  ..&8.u..}..>....
00000290  CD 21 04 41 BE D8 02 88  04 46 C6 04 3A 46 C6 04  .!.A.....F..:F..
000002A0  5C 46 B4 47 B2 00 CD 21  8C D8 8E C0 BF D8 02 32  \F.G...!.......2
000002B0  C0 B9 46 00 F2 AE 4F 80  7D FF 5C 74 04 C6 05 5C  ..F...O.}.\t...\
000002C0  47 BE D0 02 8B 0E CE 02  F3 A4 BA D8 02 B8 00 3D  G..............=
000002D0  CD 21 72 0F A3 9F 03 EB  48 8C D0 8E D8 BA 1E 03  .!r.....H.......
000002E0  E9 3B FF 8B 36 9B 03 83  FE FF 74 ED 8E 1E 2C 00  .;..6.....t...,.
000002F0  8B FE 80 3C 00 74 E2 AC  3C 3B 74 04 0A C0 75 F7  ...<.t..<;t...u.
00000300  8B CE 2B CF 83 F9 01 74  E7 8B F7 BF D8 02 F3 A4  ..+....t........
00000310  4F 8C D0 8E D8 89 36 9B  03 EB 9C BA 76 03 E9 FD  O.....6.....v...
00000320  FE 8E 06 2C 00 8B 3E 9D  03 32 C0 B9 FF FF F2 AE  ...,..>..2......
00000330  F7 D1 8B D9 8B D1 8C D8  8E C0 BE 81 00 26 8A 4C  .............&.L
00000340  FF 8A C1 02 C3 3C 7E 77  D2 26 88 44 FF 32 ED 03  .....<~w.&.D.2..
00000350  F1 8D 38 41 FD F3 A4 FC  BF 81 00 26 C6 05 20 47  ..8A.......&.. G
00000360  8B 36 9D 03 8E 1E 2C 00  8B CB 49 F3 A4 BF D8 02  .6....,...I.....
00000370  32 C0 B9 FF FF F2 AE F7  D1 8C D8 8E C0 8C D0 8E  2...............
00000380  D8 A1 9D 03 03 C2 2B D1  73 08 24 0F 04 F1 38 C2  ......+.s.$...8.
00000390  72 89 8B 3E 9D 03 BE D8  02 F3 A4 8C D8 8E C0 8B  r..>............
000003A0  1E 9F 03 BE 5C 00 C7 04  BC FE C7 44 02 FF CD C7  ....\......D....
000003B0  44 04 21 B4 C7 44 06 3E  CD C7 44 08 21 E9 C7 44  D.!..D.>..D.!..D
000003C0  0A 98 00 B4 3F B9 FF FF  BA 00 01 1E 56 CB 08 00  ....?.......V...
000003D0  77 69 6E 2E 63 6F 6D 00  00 00 00 00 00 00 00 00  win.com.........
000003E0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000003F0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000400  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000410  00 00 00 00 00 00 00 00  00 00 00 00 00 00 54 68  ..............Th
00000420  69 73 20 70 72 6F 67 72  61 6D 20 72 65 71 75 69  is program requi
00000430  72 65 73 20 4D 69 63 72  6F 73 6F 66 74 20 57 69  res Microsoft Wi
00000440  6E 64 6F 77 73 2E 0D 0A  24 59 6F 75 20 61 72 65  ndows...$You are
00000450  20 61 6C 72 65 61 64 79  20 72 75 6E 6E 69 6E 67   already running
00000460  20 4D 69 63 72 6F 73 6F  66 74 20 57 69 6E 64 6F   Microsoft Windo
00000470  77 73 2E 0D 0A 24 55 6E  61 62 6C 65 20 74 6F 20  ws...$Unable to 
00000480  73 74 61 72 74 20 4D 69  63 72 6F 73 6F 66 74 20  start Microsoft 
00000490  57 69 6E 64 6F 77 73 2E  0D 0A 24 FF FF 00 00 00  Windows...$.....
000004A0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000004B0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000004C0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000004D0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000004E0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000004F0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000500  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000510  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000520  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000530  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000540  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000550  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000560  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000570  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000580  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000590  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000005A0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000005B0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000005C0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000005D0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000005E0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000005F0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000600  4E 45 05 0A 00 01 02 00  46 45 52 47 12 03 02 00  NE......FERG....
00000610  00 10 00 50 10 00 01 00  00 00 02 00 06 00 01 00  ...P............
00000620  1C 00 40 00 78 00 E8 00  F4 00 F6 00 02 07 00 00  ..@.x...........
00000630  00 00 08 00 FF FF 02 08  00 00 00 00 00 00 00 03  ................
00000640  08 00 19 00 50 1D 19 00  00 00 00 00 11 0C 02 00  ....P...........
00000650  5C 00 50 0D 10 1D 50 0D  09 00 30 4C 10 1C 30 4C  \.P...P...0L..0L
00000660  56 00 DE 03 10 1C DE 03  5A 00 82 01 10 1C 82 01  V.......Z.......
00000670  00 00 00 00 00 00 00 00  08 00 0E 80 01 00 00 00  ................
00000680  00 00 6A 00 01 00 30 1C  01 80 00 00 00 00 03 80  ..j...0.........
00000690  01 00 00 00 00 00 6B 00  03 00 30 1C 01 80 00 00  ......k...0.....
000006A0  00 00 0A 80 05 00 00 00  00 00 6E 00 02 00 30 1C  ..........n...0.
000006B0  01 80 00 00 00 00 70 00  07 00 30 1C 02 80 00 00  ......p...0.....
000006C0  00 00 77 00 87 00 30 1C  04 80 00 00 00 00 FE 00  ..w...0.........
000006D0  04 00 30 1C 05 80 00 00  00 00 00 00 00 00 00 00  ..0.............
000006E0  00 00 00 00 00 00 00 00  08 53 45 54 55 50 00 00  .........SETUP..
000006F0  00 00 00 00 01 00 00 08  56 42 52 55 4E 33 30 30  ........VBRUN300
00000700  00 00 18 52 45 50 41 49  52 00 00 00 00 00 00 00  ...REPAIR.......
00000710  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000720  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000730  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000740  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000750  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000760  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000770  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000780  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000790  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000007A0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000007B0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000007C0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000007D0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000007E0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000007F0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000800  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000810  9A FF FF 00 00 01 00 FF  FF 02 00 03 01 11 00 01  ................
00000820  00 64 00 02 00 17 00 03  00 00 00 00 00 00 00 00  .d..............
00000830  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000840  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000850  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000860  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000870  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000880  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
00000890  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000008A0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000008B0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000008C0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000008D0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000008E0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
000008F0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
```
</details>

**Environment (please complete the following information):**
 - OS: Windows 11 10.0 amd64
 - Java Version: Microsoft 21.0.3
 - Ghidra Version: 11.1.2
 - Ghidra Origin: official GitHub distro

**Comment by ryanmkurtz** [comment]
Can you please attach the entire file?

**Comment by 0xNF** [comment]
https://github.com/user-attachments/assets/337a4747-8936-4dc1-9472-210ab10a7015

Here it is. I renamed it to .mov to avoid github's anti-exe upload rules, so just rename it back to .exe after you download it.

**Comment by 0xNF** [comment]
[SETUP.zip](https://github.com/user-attachments/files/16933537/SETUP.zip)
Sorry, should have thought of putting it as a zip in the first place.
