### ISSUE TITLE
Crash on instruction patching

### ISSUE THREAD

**Issue by consnop** [NationalSecurityAgency/ghidra#6950]
When using right click in disassembly window -> patch instruction, once I type into the instruction/argument field, I get a crash. Happens across all binaries I've tried.

```
Cannot invoke "ghidra.app.plugin.assembler.sleigh.parse.AssemblyParser.parse(java.lang.String, ghidra.app.plugin.assembler.sleigh.symbol.AssemblyNumericSymbols)" because "this.parser" is null
java.lang.NullPointerException: Cannot invoke "ghidra.app.plugin.assembler.sleigh.parse.AssemblyParser.parse(java.lang.String, ghidra.app.plugin.assembler.sleigh.symbol.AssemblyNumericSymbols)" because "this.parser" is null
	at ghidra.app.plugin.assembler.sleigh.AbstractSleighAssembler.parseLine(AbstractSleighAssembler.java:182)
	at ghidra.app.plugin.core.assembler.AssemblyDualTextField.computeCompletions(AssemblyDualTextField.java:898)
	at ghidra.app.plugin.core.assembler.AssemblyDualTextField$AssemblyAutocompletionModel.computeCompletions(AssemblyDualTextField.java:316)
	at docking.widgets.autocomplete.TextFieldAutocompleter.doUpdateDisplayContents(TextFieldAutocompleter.java:317)
	at docking.widgets.autocomplete.TextFieldAutocompleter.lambda$new$0(TextFieldAutocompleter.java:128)
	at ghidra.util.task.SwingUpdateManager.swingDoWork(SwingUpdateManager.java:108)
	at ghidra.util.task.AbstractSwingUpdateManager.swingExecutePendingWork(AbstractSwingUpdateManager.java:338)
	at ghidra.util.task.AbstractSwingUpdateManager.timerCallback(AbstractSwingUpdateManager.java:287)
	at ghidra.util.task.AbstractSwingUpdateManager.lambda$new$0(AbstractSwingUpdateManager.java:131)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:718)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2024-Aug-12 2018 GMT
Ghidra Version: 11.1.2
Java Home: /usr/lib64/jvm/java-17-openj9-17
JVM Version: Eclipse OpenJ9 17.0.12
OS: Linux 6.10.5-1-default amd64
Workstation: bayes
```

**Environment:**
 - OS: OpenSUSE Tubleweed
 - Ghidra Origin: distro repos

**Comment by ryanmkurtz** [comment]
What processor are you doing this on?  When you say across all binaries, are they a variety of processor?

**Comment by ryanmkurtz** [comment]
I am having trouble reproducing.  Perhaps you can attach one of the problematic binaries and provide an address where the problem occurs?
