### ISSUE TITLE
IllegalArgumentException when Importing Binary: Uncaught Exception in PeLoader

### ISSUE THREAD

**Issue by Oren-i** [NationalSecurityAgency/ghidra#6960]
I encountered an issue while importing a binary file in Ghidra using the headless analyzer. The import process fails with the following error:
`java.lang.IllegalArgumentException: Function entryPoint may not be created on defined data`

The issue appears to be an uncaught exception in the ControlFlowGuard class, specifically triggered by the createFunction method when a function entry point is attempted to be created on defined data.

The error is raised when importing certain UEFI modules, which I am unable to share publicly.

The import process fails, and the following stack trace is recorded:

```java
ERROR REPORT: Function entryPoint may not be created on defined data (HeadlessAnalyzer) java.lang.IllegalArgumentException: Function entryPoint may not be created on defined data
	at ghidra.program.database.function.FunctionManagerDB.createFunction(FunctionManagerDB.java:247)
	at ghidra.program.database.function.FunctionManagerDB.createFunction(FunctionManagerDB.java:201)
	at ghidra.app.util.opinion.AbstractProgramLoader.markAsFunction(AbstractProgramLoader.java:449)
	at ghidra.app.util.bin.format.pe.ControlFlowGuard.markupCfgDispatchFunction(ControlFlowGuard.java:130)
	at ghidra.app.util.bin.format.pe.ControlFlowGuard.markup(ControlFlowGuard.java:67)
	at ghidra.app.util.bin.format.pe.LoadConfigDataDirectory.markup(LoadConfigDataDirectory.java:67)
	at ghidra.app.util.opinion.PeLoader.load(PeLoader.java:141)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:864)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:98)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.app.util.importer.AutoImporter.importFresh(AutoImporter.java:722)
	at ghidra.app.util.importer.AutoImporter.importFresh(AutoImporter.java:634)
	at ghidra.app.util.importer.AutoImporter.importByUsingBestGuess(AutoImporter.java:126)
	at ghidra.app.util.headless.HeadlessAnalyzer.loadPrograms(HeadlessAnalyzer.java:1655)
	at ghidra.app.util.headless.HeadlessAnalyzer.processFileWithImport(HeadlessAnalyzer.java:1538)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithLoader(HeadlessAnalyzer.java:1745)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1686)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1770)
	at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:457)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:131)
	at ghidra.GhidraLauncher.launch(GhidraLauncher.java:81)
	at ghidra.Ghidra.main(Ghidra.java:54)
```

**Proposed Fix:** 

[import_fix.txt](https://github.com/user-attachments/files/17155370/import_fix.txt)

Patch to handle the uncaught exception in the ControlFlowGuard class. This patch ensures that the exception is handled appropriately when attempting to create a function at an entry point that is already defined as data. Another untested possibility is handling the exception in AbstractProgramLoader.markAsFunction

**Environment:**
 - OS: any linux
 - Java Version: any java version
 - Ghidra Version: 11.1.2 and olders
 - Ghidra Origin: official build

**Comment by ryanmkurtz** [comment]
Is it expected that a UEFI module is using Control Flow Guard?  I thought that was more of a win32 application thing.  I just want to make sure that the real bug isn't that it's going into the Control Flow Guard parsing code when it shouldn't be.

**Comment by ryanmkurtz** [comment]
Thanks, working on better error handling now.  I'd be curious to know what kind of data is at the place we are trying to create a function once the binary loads for you, if you are able to share that.
