### ISSUE TITLE
WSL support

### ISSUE THREAD

**Issue by cfossace** [NationalSecurityAgency/ghidra#697]
**DESCRIPTION**
Running Windows Subsystem for Linux on Windows 10.  Ghidra currently exists on Windows 10.  Trying to run Ghidra on WSL, however, Java (JDK ) errors prevent this from happening. 

**ERROR 1**
Even after adding the jdk to the path

_running_
./analyzeHeadless

_causes the error_ 

Java runtime not found.  Please refer to the Ghidra Installation Guide's Troubleshooting section.

**ERROR 2**

installing openjdk through apt 

_running_
./analyzeHeadless

_causes the error_ 

/mnt/c/Users/me/Documents/GHIDRA/ghidra_9.0/support/launch.sh: line 180: /mnt/c/Users/me/Documents/JavaJDK/jdk-11.0.2/bin/java: No such file or directory

**Environment (please complete the following information):**
 - OS: Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
 - Java Version: 11
 - Ghidra Version: 9.0

**Comment by ryanmkurtz** [comment]
When in WSL, what is the output of 
`> java -version`
and 
`> /mnt/c/Users/me/Documents/JavaJDK/jdk-11.0.2/bin/java -version`

**Comment by emteere** [comment]
I've tried this as well. In the WSL there is no graphics support in java, so you can only run it headlessly as you are doing.
As I recall you need to install the java headless package into the WSL.  I can't remember if I used "yum" or "apt-get".

**Comment by emteere** [comment]
sudo apt install openjdk-11-jdk-headless

**Comment by emteere** [comment]
As @ryanmkurtz noted you should get something like the following when you type java -version in the wsl shell

openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)

**Comment by huettenhain** [comment]
I have successfully executed Ghidra from WSL in Windows 10 using [xming](https://sourceforge.net/projects/xming/), and installing OpenJDK in the following manner:
```
sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update
sudo apt install openjdk-11-jdk
```
You might also want to
```
sudo apt install lxappearance
```
making it easier to theme your Ghidra via GTK, if you're so inclined.

**Comment by ryanmkurtz** [comment]
I'm going to close this issue because it seems to be just a matter of configuring WSL/java correctly.  Thanks for the tip @huettenhain.

@cfossace, if you are still having issue, let us know.

**Comment by cfossace** [comment]
@emteere thanks! installing openjdk headless through apt worked for me.   

The issue I was running into previously was that ghidra was defaulting to the Windows installation of Java (which was incompatible) even when I manually set the environment variable to the java install through apt.  (I was trying to run headless ghidra in WSL on the same machine I use normal ghidra on, so the packages were colliding). The headless version install worked out of the box, no manual env setting required, and it didn't break my main ghidra with the gui.

**Comment by 0xXyc** [comment]
Does anyone have an update on this for 2023?

I can't seem to get mine working.

**Comment by topia** [comment]
Could you create a new issue (or discussion) instead of commenting on the old issue? BTW, you may be able to get additional information with `./support/launch.sh fg jdk Ghidra 2G "" ghidra.GhidraRun`.
I can launch ghidra graphically on my own WSLg Ubuntu, but you need appropriate steps to match your problem.

**Comment by ryanmkurtz** [comment]
> BTW, you may be able to get additional information with ./support/launch.sh fg jdk Ghidra 2G "" ghidra.GhidraRun.

You can achieve this with `support/ghidraDebug`

**Comment by topia** [comment]
> > BTW, you may be able to get additional information with ./support/launch.sh fg jdk Ghidra 2G "" ghidra.GhidraRun.
> 
> You can achieve this with `support/ghidraDebug`

Thanks, updated.

**Comment by Aeres-u99** [comment]
For anyone experiencing the same issue, Came across this same isssue on My VM. The vm is created using libvirt + vagrant, and encountered this problem

```
❯ sudo archlinux-java status
Available Java environments:
  java-17-openjdk
  java-21-openjdk
  java-25-openjdk (default)
❯ sudo archlinux-java set java-21-openjdk
❯ ./ghidraDebug
Listening for transport dt_socket at address: 18001
openjdk version "21.0.9" 2025-10-21
OpenJDK Runtime Environment (build 21.0.9+10)
OpenJDK 64-Bit Server VM (build 21.0.9+10, mixed mode)
Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-21-openjdk/lib/libawt_xawt.so: libXtst.so.6: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2025)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:259)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:249)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2427)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
	at java.base/java.lang.System.loadLibrary(System.java:2063)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1384)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1382)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1381)
	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1419)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1393)
	at java.desktop/java.awt.Taskbar.isTaskbarSupported(Taskbar.java:242)
	at ghidra.Ghidra.main(Ghidra.java:46)

```
This specific exceptions are on Minimal system which do not have specific X libraries, which was true for my system

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-21-openjdk/lib/libawt_xawt.so: libXtst.so.6: cannot open shared object file: No such file or directory
```
For this, I installed following 
```
sudo pacman -S libxtst libxrender libxi libxext
```

Which changed the error Message to:

```
ERROR Error: Uncaught Exception! 
RuntimeException - Fontconfig head is null, check your fonts or fonts configuration  (FrontEndTool.java:312) 
java.lang.RuntimeException: Fontconfig head is null, check your fonts or fonts configuration
	at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1263) ~[?:?]
	at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:221) ~[?:?]
	at sun.awt.FontConfiguration.init(FontConfiguration.java:105) ~[?:?]
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:696) ~[?:?]
	at sun.font.SunFontManager$2.run(SunFontManager.java:352) ~[?:?]
	at sun.font.SunFontManager$2.run(SunFontManager.java:309) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:319) ~[?:?]
	at sun.font.SunFontManager.<init>(SunFontManager.java:309) ~[?:?]
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35) ~[?:?]
	at sun.awt.X11FontManager.<init>(X11FontManager.java:55) ~[?:?]
	at sun.font.PlatformFontInfo.createFontManager(PlatformFontInfo.java:37) ~[?:?]
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:51) ~[?:?]
	at sun.font.SunFontManager.getInstance(SunFontManager.java:242) ~[?:?]
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:260) ~[?:?]
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1242) ~[?:?]
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1700) ~[?:?]
	at docking.widgets.filter.ClearFilterLabel.touchesText(ClearFilterLabel.java:234) ~[Docking.jar:?]
	at docking.widgets.filter.ClearFilterLabel.checkForTouchyText(ClearFilterLabel.java:219) ~[Docking.jar:?]
	at docking.widgets.filter.ClearFilterLabel.doResetBounds(ClearFilterLabel.java:210) ~[Docking.jar:?]
	at docking.widgets.filter.ClearFilterLabel.lambda$resetBounds$0(ClearFilterLabel.java:186) ~[Docking.jar:?]
	at ghidra.util.Swing.runIfSwingOrRunLater(Swing.java:124) ~[Utility.jar:?]
	at ghidra.util.SystemUtilities.runIfSwingOrPostSwingLater(SystemUtilities.java:257) ~[Utility.jar:?]
	at docking.widgets.filter.ClearFilterLabel.resetBounds(ClearFilterLabel.java:186) ~[Docking.jar:?]
	at docking.widgets.filter.ClearFilterLabel$2.componentResized(ClearFilterLabel.java:82) ~[Docking.jar:?]
	at java.awt.Component.processComponentEvent(Component.java:6447) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6401) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2266) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:4996) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2324) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4828) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:720) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:714) [?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:400) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:747) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:400) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:744) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117) ~[?:?]
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191) ~[?:?]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236) ~[?:?]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:319) [?:?]
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234) ~[?:?]
	at java.awt.Dialog.show(Dialog.java:1079) ~[?:?]
	at java.awt.Component.show(Component.java:1728) ~[?:?]
	at java.awt.Component.setVisible(Component.java:1675) ~[?:?]
	at java.awt.Window.setVisible(Window.java:1036) ~[?:?]
	at java.awt.Dialog.setVisible(Dialog.java:1015) ~[?:?]
	at docking.DockingDialog.setVisible(DockingDialog.java:363) ~[Docking.jar:?]
	at docking.DockingWindowManager.lambda$doShowDialog$7(DockingWindowManager.java:1873) ~[Docking.jar:?]
	at ghidra.util.Swing.doRun(Swing.java:292) ~[Utility.jar:?]
	at ghidra.util.Swing.runNow(Swing.java:208) ~[Utility.jar:?]
	at ghidra.util.Swing.runNow(Swing.java:163) ~[Utility.jar:?]
	at docking.DockingWindowManager.doShowDialog(DockingWindowManager.java:1877) ~[Docking.jar:?]
	at docking.DockingWindowManager.showDialog(DockingWindowManager.java:1825) ~[Docking.jar:?]
	at docking.DockingErrorDisplay.showErrorDialogOnSwing(DockingErrorDisplay.java:187) ~[Docking.jar:?]
	at docking.DockingErrorDisplay.showDialog(DockingErrorDisplay.java:166) ~[Docking.jar:?]
	at docking.DockingErrorDisplay.doDisplayMessage(DockingErrorDisplay.java:134) ~[Docking.jar:?]
	at docking.DockingErrorDisplay.lambda$displayMessage$0(DockingErrorDisplay.java:102) ~[Docking.jar:?]
	at ghidra.util.Swing.runIfSwingOrRunLater(Swing.java:124) ~[Utility.jar:?]
	at docking.DockingErrorDisplay.displayMessage(DockingErrorDisplay.java:102) ~[Docking.jar:?]
	at docking.DockingErrorDisplay.displayErrorMessage(DockingErrorDisplay.java:55) ~[Docking.jar:?]
	at ghidra.util.Msg.showError(Msg.java:306) ~[Utility.jar:?]
	at ghidra.framework.main.FrontEndTool.installDefaultApplicationLevelPlugins(FrontEndTool.java:312) ~[Project.jar:?]
	at ghidra.framework.main.FrontEndTool.loadToolConfigurationFromDisk(FrontEndTool.java:215) ~[Project.jar:?]
	at ghidra.framework.main.FrontEndTool.<init>(FrontEndTool.java:150) ~[Project.jar:?]
	at ghidra.GhidraRun.openProject(GhidraRun.java:172) ~[Base.jar:?]
	at ghidra.GhidraRun.lambda$launch$0(GhidraRun.java:95) ~[Base.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:720) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:714) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:400) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
```

This was possibly because of absence of `fontconfig` post installing it, the ghidra started working correctly.
