### ISSUE TITLE
VSCodeProjectScript.java crashes

### ISSUE THREAD

**Issue by casept** [NationalSecurityAgency/ghidra#6971]
**Describe the bug**

When trying to create a new project, VSCodeProjectScript.java complains about a missing path and crashes.

**To Reproduce**

1. Open the Script Manager
2. Run `VSCodeProjectScript.java`
3. Fill out the form and click `OK`

**Expected behavior**

The project gets created.

**Screenshots**

N/A, see error log below

**Attachments**

Backtrace displayed by the error dialogue:

```
File system element for parameter 'source' does not exist: '/<redacted>/ghidra_11.2_PUBLIC/Extensions/Ghidra/skeleton'
java.io.FileNotFoundException: File system element for parameter 'source' does not exist: '/<redacted>/ghidra_11.2_PUBLIC/Extensions/Ghidra/skeleton'
	at org.apache.commons.io.FileUtils.requireExistsChecked(FileUtils.java:2719)
	at org.apache.commons.io.FileUtils.requireFileCopy(FileUtils.java:2751)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:681)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:630)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:531)
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:502)
	at VSCodeProjectScript.writeSampleModule(VSCodeProjectScript.java:241)
	at VSCodeProjectScript.run(VSCodeProjectScript.java:68)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:405)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:260)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:238)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:47)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

---------------------------------------------------
Build Date: 2024-Sep-26 1444 EDT
Ghidra Version: 11.2
Java Home: /usr/lib/jvm/java-21-openjdk-21.0.4.0.7-2.fc40.x86_64
JVM Version: Red Hat, Inc. 21.0.4
OS: Linux 6.10.10-200.fc40.x86_64 amd64
Workstation: l13
```

**Environment (please complete the following information):**

 - OS: [Linux 6.10.10-200.fc40.x86_64 amd64]
 - Java Version: [Red Hat, Inc. 21.0.4]
 - Ghidra Version: [11.2]
 - Ghidra Origin: [official GitHub distro] 

**Additional context**

I believe this is a problem with case-sensitive paths. `Extensions/Ghidra/Skeleton` exists, `Extensions/Ghidra/skeleton` does not. Symlinking `Skeleton` to `skeleton` solves the issue. Perhaps the script was not tested on a case-sensitive filesystem?

**Comment by ryanmkurtz** [comment]
Thanks, i'll get that fixed.
