### ISSUE TITLE
在关闭主程序时报错

### ISSUE THREAD

**Issue by 867315310** [NationalSecurityAgency/ghidra#6984]
在关闭主程序窗口时报错：
```java
java.lang.NullPointerException: Cannot invoke "ghidra.framework.main.FrontEndService.addProjectListener(ghidra.framework.model.ProjectListener)" because "frontEnd" is null
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "ghidra.framework.main.FrontEndService.addProjectListener(ghidra.framework.model.ProjectListener)" because "frontEnd" is null
	at ghidra.framework.plugintool.Plugin.cleanup(Plugin.java:276)
	at ghidra.framework.plugintool.PluginManager.dispose(PluginManager.java:104)
	at ghidra.framework.plugintool.PluginTool.dispose(PluginTool.java:515)
	at ghidra.framework.main.FrontEndTool.dispose(FrontEndTool.java:168)
	at ghidra.framework.plugintool.PluginTool.close(PluginTool.java:1212)
	at docking.DockingWindowManager.close(DockingWindowManager.java:1188)
	at docking.RootNode$JFrameWindowWrapper$1.windowClosing(RootNode.java:814)
	at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
	at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
	at java.desktop/java.awt.Window.processWindowEvent(Window.java:2085)
	at java.desktop/javax.swing.JFrame.processWindowEvent(JFrame.java:298)
	at java.desktop/java.awt.Window.processEvent(Window.java:2044)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException: Cannot invoke "ghidra.framework.main.FrontEndService.addProjectListener(ghidra.framework.model.ProjectListener)" because "frontEnd" is null
	at ghidra.app.plugin.debug.DomainFolderChangesDisplayPlugin.dispose(DomainFolderChangesDisplayPlugin.java:63)
	at ghidra.framework.plugintool.Plugin.cleanup(Plugin.java:265)
	... 32 more
```
---------------------------------------------------
Build Date: 2024-Jul-09 1157 EDT
Ghidra Version: 11.1.2
Java Home: C:\Program Files\BellSoft\LibericaJDK-21
JVM Version: BellSoft 21.0.4
OS: Windows 11 10.0 amd64
Workstation: LAPTOP-CS74GFEL

**Comment by ryanmkurtz** [comment]
Duplicate of #6937
