### ISSUE TITLE
iOS 18.0 shared cache - slide info is null

### ISSUE THREAD

**Issue by avrubel** [NationalSecurityAgency/ghidra#7006]
I downloaded and extracted the iOS 18.0 shared cache:

```sh
ipsw download ipsw --version 18.0 --device iPhone12,8
ipsw extract --dyld iPhone12,8_18.0_22A3354_Restore.ipsw
```

However, when I tried to open up the shared cache as a file system and import a framework (e.g., `System/Library/Frameworks/Foundation.framework/Foundation`, I got the error

```text
ERROR | (AbstractWorker) Unexpected error processing job:  java.lang.NullPointerException: Cannot invoke "ghidra.app.util.bin.format.macho.dyld.DyldCacheSlideInfoCommon.getMappingFileOffset()" because "slideInfo" is null
-- | -- | -- | --
  |   |   | at ghidra.file.formats.ios.dyldcache.DyldCacheExtractor.getSlideFixups(DyldCacheExtractor.java:200)
  |   |   | at ghidra.file.formats.ios.dyldcache.DyldCacheFileSystem.getByteProvider(DyldCacheFileSystem.java:95)
  |   |   | at ghidra.formats.gfilesystem.FileSystemService.getByteProvider(FileSystemService.java:364)
  |   |   | at ghidra.plugins.fsbrowser.FSBActionManager.ensureFileAccessable(FSBActionManager.java:950)
  |   |   | at ghidra.plugins.fsbrowser.FSBActionManager.lambda$createImportAction$35(FSBActionManager.java:674)
  |   |   | at docking.widgets.tree.GTree$1.run(GTree.java:1344)
  |   |   | at ghidra.util.worker.AbstractWorker$JobCallback.process(AbstractWorker.java:133)
  |   |   | at ghidra.util.worker.AbstractWorker$JobCallback.process(AbstractWorker.java:123)
  |   |   | at generic.concurrent.ConcurrentQ$CallbackCallable.call(ConcurrentQ.java:658)
  |   |   | at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
  |   |   | at generic.concurrent.FutureTaskMonitor.run(FutureTaskMonitor.java:76)
  |   |   | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  |   |   | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  |   |   | at java.base/java.lang.Thread.run(Thread.java:1583)
```

All other frameworks I tried gave me the same error.  I've had no trouble with earlier iOS versions.

What's interesting is, if I expand the cache,

```sh
cd 22A3354__iPhone12,8
dyld-shared-cache-extractor dyld_shared_cache_arm64e .
```

and try to import the file directly, it works fine.  However, if I do it that way, I'm unable to resolve pointers that reference other frameworks in the cache.

I'm using Ghidra 11.0.1 on macOS Sonoma 14.6.1

**Comment by ryanmkurtz** [comment]
I didn't notice in your other post that you are using Ghidra 11.0.1.  I know there was a new slide info 5 that I somewhat recently added support for.  Can you give the latest Ghidra a try?

**Comment by avrubel** [comment]
Ah, upgrading did it.  Thanks!
