### ISSUE TITLE
Printing help throws an exception

### ISSUE THREAD

**Issue by leechristensen** [NationalSecurityAgency/ghidra#7016]
**Describe the bug**
If you hit F1 to open the help and try to print, it throws the following exception:
```
This function should be called while holding treeLock
java.lang.IllegalStateException: This function should be called while holding treeLock
	at java.desktop/java.awt.Component.checkTreeLock(Component.java:1235)
	at java.desktop/java.awt.Container.validateTree(Container.java:1719)
	at com.sun.java.help.impl.JHelpPrintHandler$JHFrame.validate(JHelpPrintHandler.java:975)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2778)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2024-Sep-26 1444 EDT
Ghidra Version: 11.2
Java Home: C:\Program Files\Amazon Corretto\jdk21.0.3_9
JVM Version: Amazon.com Inc. 21.0.3
OS: Windows 11 10.0 amd64
```

**To Reproduce**
1. Open Ghidra
2. Hit F1 to open the help
3. Click the print button
4. An exception will then occur

**Expected behavior**
Print dialog box appears without an exception ocurring.

**Screenshots**
![image](https://github.com/user-attachments/assets/f25fc879-fce9-4176-9be1-a88c60145223)

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Windows 11
 - Java Version: Amazon 21.0.3
 - Ghidra Version: 11.2
 - Ghidra Origin: Github

**Additional context**
As an aside, I went to print the docs because, as I've been learning Ghidra, I've found them more useful than many online resources. Regrettably, I've yet to see them actually hosted anywhere online (please correct me if I'm wrong here!) so I've been resorting to printing them as PDFs so I can read them from when Ghidra is not available (e.g., on my mobile device).

**Comment by dragonmacher** [comment]
Unfortunately, this exception is coming from inside of Java's APIs.  I'm guessing that the print operation still works, despite the exception.  There may be nothing the Ghidra team can do to prevent this exception from happening.

**Comment by leechristensen** [comment]
Can confirm printing still works.
