### ISSUE TITLE
askFile() cannot be used in headless mode when the file does not exist

### ISSUE THREAD

**Issue by gemesa** [NationalSecurityAgency/ghidra#7025]
**Describe the bug**
While working with FunctionID scripts (and on #7012 and #7014) I noticed that `askFile()` cannot be used in headless mode when the file does not exist and needs to be created. An `IllegalArgumentException` is raised which is a [documented limitation/feature](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/src/main/java/ghidra/app/script/GhidraScript.java#L2041), relevant source is [here](https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Base/src/main/java/ghidra/app/script/GhidraScript.java#L1878). While this is clearly documented, I do not understand why raising this exception is necessary. This behavior prevents some scripts from running in headless mode, specifically those where the file passed to `askFile()` does not exist yet and will be created later (for example `RepackFid.java`).

We already started a discussion with @ryanmkurtz [here](https://github.com/NationalSecurityAgency/ghidra/pull/7014/files#r1790658465). I just wanted to create a separate issue to track this.

**To Reproduce**
1. Create an empty FID database by navigating to `Tools -> Function ID -> Create new empty FidDb...` in the GUI.
2. Run `RepackFid.java` in headless mode with 2 cmd line args (input and output `.fidb`):
```
$ ./support/analyzeHeadless /home/gemesa/git-repos/my-projects fidb-project -scriptPath /home/gemesa/git-repos/ghidra/Ghidra/Features/FunctionID/ghidra_scripts -preScript RepackFid.java ~/in.fidb out.fidb -noanalysis
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode)
INFO  Using log config file: jar:file:/home/gemesa/git-repos/ghidra/build/dist/ghidra_11.3_DEV/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)  
INFO  Using log file: /home/gemesa/.config/ghidra/ghidra_11.3_DEV/application.log (LoggingInitialization)  
INFO  Loading user preferences: /home/gemesa/.config/ghidra/ghidra_11.3_DEV/preferences (Preferences)  
INFO  Searching for classes... (ClassSearcher)  
INFO  Class search complete (1008 ms) (ClassSearcher)  
INFO  Initializing SSL Context (SSLContextInitializer)  
INFO  Initializing Random Number Generator... (SecureRandomFactory)  
INFO  Random Number Generator initialization complete: NativePRNGNonBlocking (SecureRandomFactory)  
INFO  Trust manager disabled, cacerts have not been set (ApplicationTrustManagerFactory)  
WARN  Neither the -import parameter nor the -process parameter was specified; therefore, the specified prescripts and/or postscripts will be executed without any type of program context. (HeadlessAnalyzer)  
INFO  Headless startup complete (1933 ms) (AnalyzeHeadless)  
INFO  Class searcher loaded 57 extension points (18 false positives) (ClassSearcher)  
INFO  HEADLESS Script Paths:
    /home/gemesa/git-repos/ghidra/Ghidra/Features/FunctionID/ghidra_scripts
...
    /home/gemesa/git-repos/ghidra/build/dist/ghidra_11.3_DEV/Ghidra/Features/WildcardAssembler/ghidra_scripts (HeadlessAnalyzer)  
INFO  HEADLESS: execution starts (HeadlessAnalyzer)  
INFO  Opening existing project: /home/gemesa/git-repos/my-projects/fidb-project (HeadlessAnalyzer)  
INFO  Opening project: /home/gemesa/git-repos/my-projects/fidb-project (HeadlessProject)  
INFO  SCRIPT: /home/gemesa/git-repos/ghidra/Ghidra/Features/FunctionID/ghidra_scripts/RepackFid.java (HeadlessAnalyzer)  
INFO  RepackFid.java> debug 0 (GhidraScript)  
INFO  RepackFid.java> debug 1 (GhidraScript)  
INFO  Packed database cache: /var/tmp/gemesa-ghidra/packed-db-cache (PackedDatabaseCache)  
INFO  RepackFid.java> debug 0 (GhidraScript)  
INFO  RepackFid.java> debug 1 (GhidraScript)  
ERROR REPORT SCRIPT ERROR:  (HeadlessAnalyzer) java.lang.IllegalArgumentException: Invalid file: out.fidb
	at ghidra.app.script.GhidraScript.parseFile(GhidraScript.java:1879)
	at ghidra.app.script.GhidraScript.loadAskValue(GhidraScript.java:1934)
	at ghidra.app.script.GhidraScript.loadAskValue(GhidraScript.java:1909)
	at ghidra.app.script.GhidraScript.askFile(GhidraScript.java:2066)
	at RepackFid.run(RepackFid.java:62)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:405)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:260)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:238)
	at ghidra.app.util.headless.HeadlessAnalyzer.runScript(HeadlessAnalyzer.java:588)
	at ghidra.app.util.headless.HeadlessAnalyzer.runScriptsList(HeadlessAnalyzer.java:926)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1781)
	at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:457)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:198)
	at ghidra.GhidraLauncher.launch(GhidraLauncher.java:81)
	at ghidra.Ghidra.main(Ghidra.java:54)

```

**Expected behavior**
The repacked `out.fidb` file is created.

**Screenshots**
N/A

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Linux fedora 6.10.12-200.fc40.x86_64
 - Java Version: openjdk 21.0.4 2024-07-16 LTS
 - Ghidra Version: 11.3_DEV
 - Ghidra Origin: locally built from the GitHub repo without any changes (commit [8e3aaf0](https://github.com/NationalSecurityAgency/ghidra/commit/8e3aaf0304bbef22ee21d2de90ebb5e8c6a97634))

**Additional context**
N/A

**Comment by gemesa** [comment]
Thank you for fixing this, it has been a real headache for me.
