### ISSUE TITLE
Version Tracking:  Mapping C Tokens Between Functions - Uncaught Exception: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by rrrrrrri** [NationalSecurityAgency/ghidra#7028]
**Describe the bug**
I'm trying to do a patch diff on two ELF files. Ghidra could not identify the difference in one of the functions. When manually check this function (Shift + C) there will be a java.lang.IndexOutOfBoundsException.

**To Reproduce**
1. Load the two files and perform auto-analyze on them
2. Create a new Version Tracking session and import the two files
3. Run the "Automatic Version Tracking"
4. Locate the "ProcessRequests" function and press Shift+C

**Expected behavior**
The Version Tracking can identify the difference in that function without any Exception.

**Screenshots**
![image](https://github.com/user-attachments/assets/8cac5a98-be77-47ad-bdc9-cb95693cef13)

**Attachments**
[files.zip](https://github.com/user-attachments/files/17306113/files.zip)

**Environment**
Build Date: 2024-Sep-26 1444 EDT
Ghidra Version: 11.2
Java Home: C:\Program Files\Eclipse Adoptium\jdk-23
JVM Version: Oracle Corporation 23
OS: Windows 11 10.0 amd64

**Additional context**
```
Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:365)
	at java.base/java.util.ArrayList.remove(ArrayList.java:552)
	at ghidra.features.codecompare.graphanalysis.DataGraph.removeInEdge(DataGraph.java:334)
	at ghidra.features.codecompare.graphanalysis.DataGraph.eliminateCasts(DataGraph.java:257)
	at ghidra.features.codecompare.graphanalysis.DataGraph.<init>(DataGraph.java:162)
	at ghidra.features.codecompare.graphanalysis.Pinning.<init>(Pinning.java:173)
	at ghidra.features.codecompare.graphanalysis.Pinning.makePinning(Pinning.java:848)
	at ghidra.features.codecompare.decompile.DecompileDataDiff.getTokenMap(DecompileDataDiff.java:110)
	at ghidra.features.codecompare.decompile.DetermineDecompilerDifferencesTask.determineDifferences(DetermineDecompilerDifferencesTask.java:66)
	at ghidra.features.codecompare.decompile.DetermineDecompilerDifferencesTask.run(DetermineDecompilerDifferencesTask.java:57)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)

---------------------------------------------------
Build Date: 2024-Sep-26 1444 EDT
Ghidra Version: 11.2
Java Home: C:\Program Files\Eclipse Adoptium\jdk-23
JVM Version: Oracle Corporation 23
OS: Windows 11 10.0 amd64
```

**Comment by MmAaXx500** [comment]
Hi @dragonmacher, I think I ran into the same issue and unfortunately your change seems to be moved the problem elsewhere.
On 11.2.1:
```
Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:365)
	at java.base/java.util.ArrayList.remove(ArrayList.java:552)
	at ghidra.features.codecompare.graphanalysis.DataGraph.removeInEdge(DataGraph.java:334)
	at ghidra.features.codecompare.graphanalysis.DataGraph.eliminateCasts(DataGraph.java:257)
	at ghidra.features.codecompare.graphanalysis.DataGraph.<init>(DataGraph.java:162)
	at ghidra.features.codecompare.graphanalysis.Pinning.<init>(Pinning.java:175)
	at ghidra.features.codecompare.graphanalysis.Pinning.makePinning(Pinning.java:848)
	at ghidra.features.codecompare.correlator.CodeCompareAddressCorrelation.processCodeCompare(CodeCompareAddressCorrelation.java:172)
	at ghidra.features.codecompare.correlator.CodeCompareAddressCorrelation.initialize(CodeCompareAddressCorrelation.java:105)
	at ghidra.features.codecompare.correlator.CodeCompareAddressCorrelation.getCorrelatedDestinationRange(CodeCompareAddressCorrelation.java:73)
	at ghidra.feature.vt.gui.util.ImpliedMatchUtils.findImpliedMatch(ImpliedMatchUtils.java:196)
	at ghidra.feature.vt.gui.util.ImpliedMatchUtils.findImpliedMatches(ImpliedMatchUtils.java:157)
	at ghidra.feature.vt.gui.util.ImpliedMatchUtils.updateImpliedMatchForAcceptedAssocation(ImpliedMatchUtils.java:57)
	at ghidra.feature.vt.gui.provider.impliedmatches.ImpliedMatchAssociationHook.associationAccepted(ImpliedMatchAssociationHook.java:74)
	at ghidra.feature.vt.api.db.AssociationDatabaseManager.setAssociationAccepted(AssociationDatabaseManager.java:495)
	at ghidra.feature.vt.api.db.VTAssociationDB.setAccepted(VTAssociationDB.java:184)
	at ghidra.feature.vt.gui.task.ApplyMatchTask.acceptMatch(ApplyMatchTask.java:135)
	at ghidra.feature.vt.gui.task.ApplyMatchTask.applyMatches(ApplyMatchTask.java:107)
	at ghidra.feature.vt.gui.task.ApplyMatchTask$1.analysisWorkerCallback(ApplyMatchTask.java:89)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1699)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1586)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:660)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:760)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:639)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:604)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:55)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:33)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:103)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:351)
	at java.base/java.lang.Thread.run(Thread.java:1575)

---------------------------------------------------
Build Date: 2024-Nov-05 1643 EST
Ghidra Version: 11.2.1
Java Home: /usr/lib/jvm/java-23-temurin
JVM Version: Eclipse Adoptium 23.0.1
OS: Linux 6.11.6-arch1-1 amd64
```

On current master (30ef757d81c88c5fc413d9136127cfeb4c6fbf81)
```
Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:365)
	at java.base/java.util.ArrayList.get(ArrayList.java:428)
	at ghidra.features.codecompare.graphanalysis.DataVertex.nextNGramSource(DataVertex.java:169)
	at ghidra.features.codecompare.graphanalysis.DataGraph.makeNGrams(DataGraph.java:279)
	at ghidra.features.codecompare.graphanalysis.Pinning.<init>(Pinning.java:183)
	at ghidra.features.codecompare.graphanalysis.Pinning.makePinning(Pinning.java:848)
	at ghidra.features.codecompare.correlator.CodeCompareAddressCorrelation.processCodeCompare(CodeCompareAddressCorrelation.java:172)
	at ghidra.features.codecompare.correlator.CodeCompareAddressCorrelation.initialize(CodeCompareAddressCorrelation.java:105)
	at ghidra.features.codecompare.correlator.CodeCompareAddressCorrelation.getCorrelatedDestinationRange(CodeCompareAddressCorrelation.java:73)
	at ghidra.feature.vt.gui.util.ImpliedMatchUtils.findImpliedMatch(ImpliedMatchUtils.java:196)
	at ghidra.feature.vt.gui.util.ImpliedMatchUtils.findImpliedMatches(ImpliedMatchUtils.java:157)
	at ghidra.feature.vt.gui.util.ImpliedMatchUtils.updateImpliedMatchForAcceptedAssocation(ImpliedMatchUtils.java:57)
	at ghidra.feature.vt.gui.provider.impliedmatches.ImpliedMatchAssociationHook.associationAccepted(ImpliedMatchAssociationHook.java:74)
	at ghidra.feature.vt.api.db.AssociationDatabaseManager.setAssociationAccepted(AssociationDatabaseManager.java:495)
	at ghidra.feature.vt.api.db.VTAssociationDB.setAccepted(VTAssociationDB.java:184)
	at ghidra.feature.vt.gui.task.ApplyMatchTask.acceptMatch(ApplyMatchTask.java:135)
	at ghidra.feature.vt.gui.task.ApplyMatchTask.applyMatches(ApplyMatchTask.java:107)
	at ghidra.feature.vt.gui.task.ApplyMatchTask$1.analysisWorkerCallback(ApplyMatchTask.java:89)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1699)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1586)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:660)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:760)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:639)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:604)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:55)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:33)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:103)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:351)
	at java.base/java.lang.Thread.run(Thread.java:1575)

---------------------------------------------------
Build Date: 2024-Nov-10 1829 CET
Ghidra Version: 11.3
Java Home: /usr/lib/jvm/java-23-temurin
JVM Version: Eclipse Adoptium 23.0.1
OS: Linux 6.11.6-arch1-1 amd64
```
