### ISSUE TITLE
Build errors not displayed in headless mode when executing ghidra script

### ISSUE THREAD

**Issue by gemesa** [NationalSecurityAgency/ghidra#7060]
**Describe the bug**
When developing custom Ghidra scripts sometimes I encounter build errors that are not displayed when executing the script in headless mode. Instead I only see that the class file could not be created without any details about the build errors.

**To Reproduce**

Run the following script in headless mode:

```java
import ghidra.util.task.ConsoleTaskMonitor;
import ghidra.util.task.TaskMonitor;

public class TestGhidraScript extends GhidraScript {

  @Override
  protected void run() throws Exception {
    TaskMonitor monitor = new ConsoleTaskMonitor();
  }
}
```

It only indicates that the class could not be found:
```
$ ./support/analyzeHeadless /home/gemesa/git-repos/my-projects fidb-rust/rustc-1.81.0/testlib/1.0.0/x64-debug-build/ -process 45c91108d938afe8-absvsi2.o -scriptPath /home/gemesa/git-repos/binexport/java/ghidra_scripts -preScript TestGhidraScript.java -noanalysis
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode)
...
INFO  HEADLESS: execution starts (HeadlessAnalyzer)  
INFO  Opening existing project: /home/gemesa/git-repos/my-projects/fidb-rust (HeadlessAnalyzer)  
INFO  Opening project: /home/gemesa/git-repos/my-projects/fidb-rust (HeadlessProject)  
INFO  REPORT: Processing project file: /rustc-1.81.0/testlib/1.0.0/x64-debug-build/45c91108d938afe8-absvsi2.o (HeadlessAnalyzer)  
ERROR REPORT SCRIPT ERROR: TestGhidraScript.java : The class could not be found. It must be the public class of the .java file: Failed to get OSGi bundle containing script: /home/gemesa/git-repos/binexport/java/ghidra_scripts/TestGhidraScript.java (HeadlessAnalyzer) ghidra.app.script.GhidraScriptLoadException: The class could not be found. It must be the public class of the .java file: Failed to get OSGi bundle containing script: /home/gemesa/git-repos/binexport/java/ghidra_scripts/TestGhidraScript.java
	at ghidra.app.script.JavaScriptProvider.getScriptInstance(JavaScriptProvider.java:110)
	at ghidra.app.util.headless.HeadlessAnalyzer.runScriptsList(HeadlessAnalyzer.java:912)
	at ghidra.app.util.headless.HeadlessAnalyzer.analyzeProgram(HeadlessAnalyzer.java:993)
	at ghidra.app.util.headless.HeadlessAnalyzer.processFileNoImport(HeadlessAnalyzer.java:1172)
	at ghidra.app.util.headless.HeadlessAnalyzer.processFolderNoImport(HeadlessAnalyzer.java:1344)
	at ghidra.app.util.headless.HeadlessAnalyzer.processNoImport(HeadlessAnalyzer.java:1373)
	at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:454)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:198)
	at ghidra.GhidraLauncher.launch(GhidraLauncher.java:81)
	at ghidra.Ghidra.main(Ghidra.java:54)
Caused by: java.lang.ClassNotFoundException: Failed to get OSGi bundle containing script: /home/gemesa/git-repos/binexport/java/ghidra_scripts/TestGhidraScript.java
	at ghidra.app.script.JavaScriptProvider.loadClass(JavaScriptProvider.java:159)
	at ghidra.app.script.JavaScriptProvider.getScriptInstance(JavaScriptProvider.java:96)
	... 9 more
 
INFO  REPORT: Save succeeded for processed file: /rustc-1.81.0/testlib/1.0.0/x64-debug-build/45c91108d938afe8-absvsi2.o (HeadlessAnalyzer)
```

**Expected behavior**
Build errors are shown in stdout.

**Screenshots**
In GUI mode all errors are displayed:
![image](https://github.com/user-attachments/assets/69ee0cdc-90cc-4072-a21d-1de46a20c68a)

**Attachments**
N/A

**Environment (please complete the following information):**
 - OS: Linux fedora 6.10.12-200.fc40.x86_64
 - Java Version: openjdk 21.0.4 2024-07-16 LTS
 - Ghidra Version: 11.3_DEV
 - Ghidra Origin: locally built from the GitHub repo without any changes (commit [7d5a514f](https://github.com/NationalSecurityAgency/ghidra/commit/7d5a514f25fe5bea52a0465c26ae5663855f79c9))

**Additional context**
N/A

**Comment by ryanmkurtz** [comment]
Thanks, I'll investigate this.

**Comment by gemesa** [comment]
I rebuilt my Ghidra with the latest master branch and now I cannot reproduce the issue either. However I remember it working earlier (displaying the build errors) and then the errors just disappeared somehow. Lets close this for now and I will reopen it if I can reproduce the issue.

```
$ ./support/analyzeHeadless /home/gemesa/git-repos/my-projects fidb-rust/rustc-1.81.0/testlib/1.0.0/x64-debug-build/ -process 45c91108d938afe8-absvsi2.o -preScript TestGhidraScript.java -noanalysis
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode)
INFO  Using log config file: jar:file:/home/gemesa/git-repos/ghidra/build/dist/ghidra_11.3_DEV/Ghidra/Framework/Generic/lib/Generic.jar!/generic.log4j.xml (LoggingInitialization)  
INFO  Using log file: /home/gemesa/.config/ghidra/ghidra_11.3_DEV/application.log (LoggingInitialization)  
INFO  Loading user preferences: /home/gemesa/.config/ghidra/ghidra_11.3_DEV/preferences (Preferences)  
INFO  Searching for classes... (ClassSearcher)  
INFO  Class search complete (971 ms) (ClassSearcher)  
INFO  Initializing SSL Context (SSLContextInitializer)  
INFO  Initializing Random Number Generator... (SecureRandomFactory)  
INFO  Random Number Generator initialization complete: NativePRNGNonBlocking (SecureRandomFactory)  
INFO  Trust manager disabled, cacerts have not been set (ApplicationTrustManagerFactory)  
INFO  Headless startup complete (1808 ms) (AnalyzeHeadless)  
INFO  Class searcher loaded 57 extension points (18 false positives) (ClassSearcher)  
INFO  HEADLESS Script Paths:
...
INFO  HEADLESS: execution starts (HeadlessAnalyzer)  
INFO  Opening existing project: /home/gemesa/git-repos/my-projects/fidb-rust (HeadlessAnalyzer)  
INFO  Opening project: /home/gemesa/git-repos/my-projects/fidb-rust (HeadlessProject)  
INFO  REPORT: Processing project file: /rustc-1.81.0/testlib/1.0.0/x64-debug-build/45c91108d938afe8-absvsi2.o (HeadlessAnalyzer)  
INFO  Packed database cache: /var/tmp/gemesa-ghidra/packed-db-cache (PackedDatabaseCache)  
TestGhidraScript.java:4: error: cannot find symbol
public class TestGhidraScript extends GhidraScript {
                                      ^
  symbol: class GhidraScript
TestGhidraScript.java:6: error: method does not override or implement a method from a supertype
  @Override
  ^
skipping /home/gemesa/ghidra_scripts/TestGhidraScript.java
ERROR REPORT SCRIPT ERROR: TestGhidraScript.java : The class could not be found. It must be the public class of the .java file: TestGhidraScript not found by aff0119e [1] (HeadlessAnalyzer) ghidra.app.script.GhidraScriptLoadException: The class could not be found. It must be the public class of the .java file: TestGhidraScript not found by aff0119e [1]
	at ghidra.app.script.JavaScriptProvider.getScriptInstance(JavaScriptProvider.java:110)
	at ghidra.app.util.headless.HeadlessAnalyzer.runScriptsList(HeadlessAnalyzer.java:912)
	at ghidra.app.util.headless.HeadlessAnalyzer.analyzeProgram(HeadlessAnalyzer.java:993)
	at ghidra.app.util.headless.HeadlessAnalyzer.processFileNoImport(HeadlessAnalyzer.java:1172)
	at ghidra.app.util.headless.HeadlessAnalyzer.processFolderNoImport(HeadlessAnalyzer.java:1344)
	at ghidra.app.util.headless.HeadlessAnalyzer.processNoImport(HeadlessAnalyzer.java:1373)
	at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:454)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:198)
	at ghidra.GhidraLauncher.launch(GhidraLauncher.java:81)
	at ghidra.Ghidra.main(Ghidra.java:54)
Caused by: java.lang.ClassNotFoundException: TestGhidraScript not found by aff0119e [1]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1591)
	at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1976)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.apache.felix.framework.Felix.loadBundleClass(Felix.java:2116)
	at org.apache.felix.framework.BundleImpl.loadClass(BundleImpl.java:986)
	at ghidra.app.script.JavaScriptProvider.loadClass(JavaScriptProvider.java:161)
	at ghidra.app.script.JavaScriptProvider.getScriptInstance(JavaScriptProvider.java:96)
	... 9 more
 
INFO  REPORT: Save succeeded for processed file: /rustc-1.81.0/testlib/1.0.0/x64-debug-build/45c91108d938afe8-absvsi2.o (HeadlessAnalyzer)
```
