### ISSUE TITLE
Uncaught Exception when trying to rename Undefined Functions

### ISSUE THREAD

**Issue by athena255** [NationalSecurityAgency/ghidra#787]
**Describe the bug**
An uncaught exception occurs upon renaming Undefined Functions. 

**To Reproduce**
1. Load vmware-vmx.exe
2. Open the string window and search for strings that are XREFed by an undefined function
3. Follow the undefined function and view it in the Decompile window
4. Press 'L' to rename.
5. See uncaught exception 

**Expected behavior**
A prompt should have appeared allowing the user to rename the function

**Attachments**
![image](https://user-images.githubusercontent.com/14916525/61174872-69b88300-a574-11e9-95f2-5c5bc3e7b31d.png)

> Uncaught Exception! 
java.lang.UnsupportedOperationException
	at ghidra.util.UndefinedFunction.getSymbol(UndefinedFunction.java:510)
	at ghidra.app.plugin.core.decompile.actions.RenameFunctionAction.actionPerformed(RenameFunctionAction.java:79)
	at docking.ExecutableKeyActionAdapter.execute(ExecutableKeyActionAdapter.java:40)
	at docking.action.MultipleKeyAction.actionPerformed(MultipleKeyAction.java:167)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at docking.KeyBindingOverrideKeyEventDispatcher.actionInProgress(KeyBindingOverrideKeyEventDispatcher.java:204)
	at docking.KeyBindingOverrideKeyEventDispatcher.dispatchKeyEvent(KeyBindingOverrideKeyEventDispatcher.java:116)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1133)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2019-May-16 1545 EDT
Ghidra Version: 9.0.4
Java Home: C:\Program Files\Java\jdk-12.0.1
JVM Version: Oracle Corporation 12.0.1
OS: Windows 10 10.0 amd64

**Environment (please complete the following information):**
 - OS: Windows 10 10.0 amd64
 - Java Version: jdk-12.0.1
 - Ghidra Version: 9.0.4

**Additional context**
It seems to only apply to undefined functions

**Comment by ryanmkurtz** [comment]
Closing as duplicate of #753
