### ISSUE TITLE
java.lang.NullPointerException buildSubcategoryMap

### ISSUE THREAD

**Issue by kant2002** [NationalSecurityAgency/ghidra#821]
**Describe the bug**
```
Uncaught Exception! 
java.lang.NullPointerException
	at ghidra.program.database.data.CategoryDB.buildSubcategoryMap(CategoryDB.java:197)
	at ghidra.program.database.data.CategoryDB$1.loadMap(CategoryDB.java:63)
	at ghidra.program.database.data.LazyLoadingCachingMap.getOrLoadMap(LazyLoadingCachingMap.java:120)
	at ghidra.program.database.data.LazyLoadingCachingMap.valuesToArray(LazyLoadingCachingMap.java:100)
	at ghidra.program.database.data.CategoryDB.getCategories(CategoryDB.java:219)
	at ghidra.app.plugin.core.datamgr.tree.CategoryNode.generateChildren(CategoryNode.java:68)
	at docking.widgets.tree.GTreeLazyNode.loadChildren(GTreeLazyNode.java:37)
	at docking.widgets.tree.AbstractGTreeNode.getChildCount(AbstractGTreeNode.java:125)
```

**To Reproduce**
Not sure how to reproduce the behavior. Maybe I have something screwed in the database, or in UI, due to low disk space. (?)

**Expected behavior**
A clear and concise description of what happen. At least I think would be practical to place debugging message

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: 11.0.2
 - Ghidra Version: 9.0.1

**Additional context**
Will try to submit small PR with diagnostic message

**Comment by kant2002** [comment]
Notice that this is happens when I select next symbol in the "Symbol Tree Window". I select just one element, but instead of that selected two items. See screenshot below

![image](https://user-images.githubusercontent.com/4257079/61590084-25149380-abd5-11e9-985b-7dddc4874f53.png)

**Comment by kant2002** [comment]
And before that error appear, I see following error message

```
Locked buffer
java.io.IOException: Locked buffer
	at db.buffers.BufferMgr.getBufferNode(BufferMgr.java:819)
	at db.buffers.BufferMgr.getBuffer(BufferMgr.java:957)
	at db.NodeMgr.getVarKeyNode(NodeMgr.java:219)
	at db.Table$VarKeyIterator2.initialize(Table.java:3777)
	at db.Table$VarKeyIterator2.<init>(Table.java:3751)
	at db.Table$VarKeyIterator.<init>(Table.java:3314)
	at db.Table.fieldKeyIterator(Table.java:1909)
	at db.FieldIndexTable.findPrimaryKeys(FieldIndexTable.java:76)
	at db.Table.findRecords(Table.java:1368)
	at ghidra.program.database.data.CategoryDBAdapterV0.getRecordIdsWithParent(CategoryDBAdapterV0.java:74)
	at ghidra.program.database.data.CategoryDB.getCategories(CategoryDB.java:182)
	at ghidra.program.database.data.CategoryDB.buildSubcategoryMap(CategoryDB.java:196)
	at ghidra.program.database.data.CategoryDB$1.loadMap(CategoryDB.java:63)
	at ghidra.program.database.data.LazyLoadingCachingMap.getOrLoadMap(LazyLoadingCachingMap.java:120)
	at ghidra.program.database.data.LazyLoadingCachingMap.valuesToArray(LazyLoadingCachingMap.java:100)
	at ghidra.program.database.data.CategoryDB.getCategories(CategoryDB.java:219)
	at ghidra.app.plugin.core.datamgr.tree.CategoryNode.generateChildren(CategoryNode.java:68)
	at docking.widgets.tree.GTreeLazyNode.loadChildren(GTreeLazyNode.java:37)
	at docking.widgets.tree.AbstractGTreeNode.getChildCount(AbstractGTreeNode.java:125)
	at docking.widgets.tree.internal.GTreeModel.getChildCount(GTreeModel.java:77)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.paintExpandControl(BasicTreeUI.java:1699)
```

It may be that this is related to function renaming

**Comment by dragonmacher** [comment]
Based on a cursory look at the stack trace, it seems as though there is an inconsistency with the database locking, presumably encountered by a race condition between the Swing thread and a background thread that was updating the database.    

It is not clear from the stack trace alone how this could happen.   If you are able to reproduce it, then any extra background information would be helpful.

**Comment by dragonmacher** [comment]
I haven't seen anything like this for some time.  The code in this area has changed quite a bit as well.
