### ISSUE TITLE
PDB Execution failure of pdb.exe.

### ISSUE THREAD

**Issue by miladkahsarialhadi** [NationalSecurityAgency/ghidra#899]
**PDB Parser Error**
I have created a sample program with VS C++ in Debug Mode. Before disassembling the binary file with Ghidra, I disassembled it with IDA Pro. It (IDA Pro) successfully could analysis the file-based PDB information which I load into it. 

Next step, I wanted to disassemble the binary file with Ghidra. It first nags about XML file, so I created an XML file for the binary. In the next step, it shows "PDB Execution failure of pdb.exe."

In order to fix the problem, I rebuild the PDB solution but the problem still remains. What should I do now?

**To Reproduce**
1. Load C++ Binary
2. Load PDB File
3. PDB.exe error.

**Expected behavior**
I load the PDB file into Ghidra to show a better and more readable disassembly output but Ghidra couldn't load the PDB file successfully. It nags about pdb.exe, so I recompile it but the problem still remains.

Build Date: 2019-May-16 1545 EDT
Ghidra Version: 9.0.4
Java Home: C:\Program Files\Java\jdk-12.0.1
JVM Version: Oracle Corporation 12.0.1
OS: Windows 10 10.0 amd64
Workstation: clightning

**Comment by ghizard** [comment]
Can you verify that the XML file was completely written.  It should end in
```</pdb>```
If it did not, then the pdb.exe likely crashed.  There are fixes in master/9.1 that should lessen the chance of the pdb.exe crashing.

**Comment by miladkahsarialhadi** [comment]
I did it, but the problem keeps remain. My XML file started and also end it with PDB tag but it doesn't work anyway. However, when I add it PDB tag to the XML file, the ghidra shows me the following error message:

Problem parsing or applying PDB information: org.xml.sax.SAXParseException; lineNumber: 72; columnNumber: 56; XML document structures must start and end within the same entity.
java.io.IOException: Problem parsing or applying PDB information: org.xml.sax.SAXParseException; lineNumber: 72; columnNumber: 56; XML document structures must start and end within the same entity.
	at ghidra.app.util.bin.format.pdb.PdbParserNEW.applyTo(PdbParserNEW.java:406)
	at pdb.LoadPdbTask$1.analysisWorkerCallback(LoadPdbTask.java:61)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisWorkerCommand.applyTo(AutoAnalysisManager.java:1683)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:685)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:785)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:664)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:629)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:62)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:101)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.RuntimeException: org.xml.sax.SAXParseException; lineNumber: 72; columnNumber: 56; XML document structures must start and end within the same entity.
	at ghidra.xml.ThreadedXmlPullParserImpl.checkForException(ThreadedXmlPullParserImpl.java:122)
	at ghidra.xml.ThreadedXmlPullParserImpl.waitForNextElement(ThreadedXmlPullParserImpl.java:159)
	at ghidra.xml.ThreadedXmlPullParserImpl.hasNext(ThreadedXmlPullParserImpl.java:154)
	at ghidra.app.util.bin.format.pdb.PdbParserNEW.applyTo(PdbParserNEW.java:327)
	... 10 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 72; columnNumber: 56; XML document structures must start and end within the same entity.
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1243)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at ghidra.xml.ThreadedXmlPullParserImpl$ContentHandlerRunnable.run(ThreadedXmlPullParserImpl.java:267)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more

---------------------------------------------------
Build Date: 2019-May-16 1545 EDT
Ghidra Version: 9.0.4
Java Home: C:\Program Files\Java\jdk-12.0.2
JVM Version: Oracle Corporation 12.0.2
OS: Windows 10 10.0 amd64
Workstation: clightning

**Comment by ghizard** [comment]
Is it possible to show us what is going on around line 72 of the xml file? If you can capture and paste from a few lines before until a few lines after line 72, it might help us diagnose this issue.  Please make sure you tell us which line is line 72.
It could be that some character is not properly escaped on that line. Not sure.

**Comment by miladkahsarialhadi** [comment]
The XML file created by VS19 has less than 8 line code which it is simply introduced the program name I wanted to disassemble. The XML file content:

<pdb>
<?xml version="1.0"?>
<doc>
    <assembly>
        "Project0000-RVLV"
    </assembly>
    <members />
</doc>
</pdb>

I don't know, It is a correct XML file or not because when I wanted to load PDB file for the executable, Ghidra said I need the XML file. So I turn on the flag of /doc to create XML documentation for the executable and this XML file created but nothing changed. 

I don't know exactly what steps I should follow to create a program that Ghidra can disassemble it with its PDB information.

**Comment by ghizard** [comment]
More recent Visual Studio versions do not automatically create much debug information.
See:
https://docs.microsoft.com/en-us/cpp/build/reference/debug-generate-debug-info?view=vs-2019
If you are doing command line, I believe the option you need is /debug:full
If you are using the GUI, there should be something that equates to this.
Give this a try.

**Comment by miladkahsarialhadi** [comment]
Yeah, I knew that so I set the linker option to generate full debug information for the binary but nothing changed. I compiled my binary code with VS17 and VS19 but Ghidra could not load PDB file and generate the above error messages.

**Comment by ghizard** [comment]
Is there anything else you can tell us about the other XML file at the error location (line 72)?  If cannot gives us a few lines around there, then perhaps you can look at those lines yourself to see if anything looks suspect. Is there a forward slash in any of the strings? Or does it look like there is an illegal character that should have been escaped?

**Comment by ghizard** [comment]
@miladkahsarialhadi I'm closing this issue, as we have made improvements in the pdb.exe (#674 restructured and memory fixes; #182 escaping more strings, which is very possibly the source of the problem and you saw; and other fixes) and we now have the PDB Universal Analyzer and Loader, which no longer requires the MSDIA-based pdb.exe. If you still have an issue or new issue, please create a new ticket.
