### ISSUE TITLE
select a Language

### ISSUE THREAD

**Issue by dursun0007** [NationalSecurityAgency/ghidra#93]
**Describe the bug**

**To Reproduce**
Error creating class ghidra.app.plugin.processors.sleigh.SleighLanguageProvider when creating extension points for ghidra.program.model.lang.LanguageProvider
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at ghidra.util.classfinder.ClassSearcher.getInstances(ClassSearcher.java:140)
	at ghidra.util.classfinder.ClassSearcher.getInstances(ClassSearcher.java:126)
	at ghidra.program.util.DefaultLanguageService.searchForProviders(DefaultLanguageService.java:87)
	at ghidra.program.util.DefaultLanguageService.<init>(DefaultLanguageService.java:77)
	at ghidra.program.util.DefaultLanguageService.getLanguageService(DefaultLanguageService.java:49)
	at ghidra.app.util.opinion.AbstractProgramLoader.getLanguageService(AbstractProgramLoader.java:359)
	at ghidra.app.util.opinion.XmlLoader.findSupportedLoadSpecs(XmlLoader.java:75)
	at ghidra.app.util.opinion.LoaderService.getSupportedLoadSpecs(LoaderService.java:49)
	at ghidra.app.util.opinion.LoaderService.getAllSupportedLoadSpecs(LoaderService.java:76)
	at ghidra.plugin.importer.ImporterUtilities.lambda$importSingleFile$3(ImporterUtilities.java:273)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:93)
	at ghidra.util.task.Task.monitoredRun(Task.java:128)
	at ghidra.util.task.TaskLauncher.lambda$startBackgroundThread$2(TaskLauncher.java:315)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: No enum constant ghidra.program.model.lang.Endian.LİTTLE
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at ghidra.program.model.lang.Endian.valueOf(Endian.java:20)
	at ghidra.app.plugin.processors.sleigh.SleighLanguageProvider.read(SleighLanguageProvider.java:206)
	at ghidra.app.plugin.processors.sleigh.SleighLanguageProvider.createLanguageDescriptions(SleighLanguageProvider.java:174)
	at ghidra.app.plugin.processors.sleigh.SleighLanguageProvider.createLanguages(SleighLanguageProvider.java:83)
	at ghidra.app.plugin.processors.sleigh.SleighLanguageProvider.createLanguages(SleighLanguageProvider.java:76)
	at ghidra.app.plugin.processors.sleigh.SleighLanguageProvider.<init>(SleighLanguageProvider.java:66)
	... 18 more

---------------------------------------------------
Build Date: 2019-Feb-28 1236 EST
Ghidra Version: 9.0
Java Home: C:\Users\Dima\Desktop\ghidra_9.0_PUBLIC_20190228\jdk-11.0.2
JVM Version: Oracle Corporation 11.0.2
OS: Windows 10 10.0 amd64
Workstation: DESKTOP-TECH
 Ghidra : language does not work empty

**Comment by afk** [comment]
Can reproduce on Ubuntu 18.04. I think that this is caused by system language being Turkish because it is caused by not `ghidra.program.model.lang.Endian.LİTTLE` not being found and İ character is a Turkish uppercase i.

**Comment by ryanmkurtz** [comment]
Not reproducible on our end...closing.
