### ISSUE TITLE
Bunch of unit tests failing

### ISSUE THREAD

**Issue by kant2002** [NationalSecurityAgency/ghidra#941]
I have bunch of unit tests which are not working on the latest master in the CI and non-CI environment.

## Linux/Mac
This one test appear to be related to latest changes.

- testAssembly_AND_mRBP_n0x8m_0xffff0000
```
ghidra.app.plugin.assembler.sleigh.AbstractAssemblyTest$DisassemblyMismatchException: Desired instruction bytes do not disassemble to a desired string: [AND qword ptr [RBP + -0x8],0xffff0000]; found instead: AND qword ptr [RBP + -0x8],-0x10000
```

# Mac only
This one I suppose related to the UI.

- testCancelExecution
```
java.lang.AssertionError
	at generic.concurrent.ConcurrentQTest.testCancelExecution(ConcurrentQTest.java:337)
	at generic.test.TestThread.run(TestThread.java:106)
```
- testWaitForLimitedTime
```
java.lang.AssertionError
	at generic.concurrent.ConcurrentQTest.testWaitForLimitedTime(ConcurrentQTest.java:219)
	at generic.test.TestThread.run(TestThread.java:106)
```
- testCheckOut_MixOfVersionedFilesThatDoAndDontFailCheckout
```
junit.framework.AssertionFailedError: Timed-out waiting for window with title 'Confirm Bulk Checkout'
	at docking.test.AbstractDockingTest.waitForWindow(AbstractDockingTest.java:338)
	at docking.test.AbstractDockingTest.waitForDialogComponent(AbstractDockingTest.java:625)
	at ghidra.framework.main.projectdata.actions.VersionControlCheckOutActionTest.confirmCheckout(VersionControlCheckOutActionTest.java:188)
	at ghidra.framework.main.projectdata.actions.VersionControlCheckOutActionTest.testCheckOut_MixOfVersionedFilesThatDoAndDontFailCheckout(VersionControlCheckOutActionTest.java:158)
	at generic.test.TestThread.run(TestThread.java:106)
```
- testCheckOut_SingleVersionedAndNotCheckedOutFile
```
junit.framework.AssertionFailedError: Time expired waiting for tasks to complete.
	at generic.test.AbstractGenericTest.doWaitForTasks(AbstractGenericTest.java:437)
	at generic.test.AbstractGenericTest.waitForTasks(AbstractGenericTest.java:426)
	at ghidra.framework.main.projectdata.actions.VersionControlCheckOutActionTest.testCheckOut_SingleVersionedAndNotCheckedOutFile(VersionControlCheckOutActionTest.java:177)
	at generic.test.TestThread.run(TestThread.java:106)
```
- testCheckOut_OnlyVersionedAndNotCheckedOutFiles_ConfirmCheckout
```
junit.framework.AssertionFailedError: Time expired waiting for tasks to complete.
	at generic.test.AbstractGenericTest.doWaitForTasks(AbstractGenericTest.java:437)
	at generic.test.AbstractGenericTest.waitForTasks(AbstractGenericTest.java:426)
	at ghidra.framework.main.projectdata.actions.VersionControlCheckOutActionTest.testCheckOut_OnlyVersionedAndNotCheckedOutFiles_ConfirmCheckout(VersionControlCheckOutActionTest.java:88)
	at generic.test.TestThread.run(TestThread.java:106)
```
- testCheckOut_OnlyVersionedAndNotCheckedOutFiles_CancelCheckout
```
junit.framework.AssertionFailedError: Time expired waiting for tasks to complete.
	at generic.test.AbstractGenericTest.doWaitForTasks(AbstractGenericTest.java:437)
	at generic.test.AbstractGenericTest.waitForTasks(AbstractGenericTest.java:426)
	at ghidra.framework.main.projectdata.actions.VersionControlCheckOutActionTest.testCheckOut_OnlyVersionedAndNotCheckedOutFiles_CancelCheckout(VersionControlCheckOutActionTest.java:105)
	at generic.test.TestThread.run(TestThread.java:106)
```
- testCheckOut_OnlyVersionedFilesThatFailCheckout
```
junit.framework.AssertionFailedError: Time expired waiting for tasks to complete.
	at generic.test.AbstractGenericTest.doWaitForTasks(AbstractGenericTest.java:437)
	at generic.test.AbstractGenericTest.waitForTasks(AbstractGenericTest.java:426)
	at ghidra.framework.main.projectdata.actions.VersionControlCheckOutActionTest.testCheckOut_OnlyVersionedFilesThatFailCheckout(VersionControlCheckOutActionTest.java:138)
	at generic.test.TestThread.run(TestThread.java:106)
```

If you have any ideas how I can make it work in CI I would be grateful

**Comment by kant2002** [comment]
Thanks.

**Comment by ryanmkurtz** [comment]
We are fixing tests on a daily basis with the goal of getting them all passing before a 9.1 release.  Make sure to pull the latest master to check our progress on that...the tests are in a very active state of development right now.
