### ISSUE TITLE
A lot of Integration tests fails >100

### ISSUE THREAD

**Issue by kant2002** [NationalSecurityAgency/ghidra#942]
The test `testRunAutoVT_moreCautious` from integrationTests does not working.
it fails with 
```
java.lang.NullPointerException
	at ghidra.feature.vt.api.db.VTSessionDB.initializePrograms(VTSessionDB.java:138)
	at ghidra.feature.vt.api.db.VTSessionDB.createVTSession(VTSessionDB.java:87)
	at ghidra.feature.vt.gui.VTTestEnv.createAndOpenVTSession(VTTestEnv.java:115)
	at ghidra.feature.vt.gui.VTTestEnv.createSession(VTTestEnv.java:111)
	at ghidra.feature.vt.api.VTAutoVersionTrackingTest.testRunAutoVT_moreCautious(VTAutoVersionTrackingTest.java:85)
	at generic.test.TestThread.run(TestThread.java:106)
```

Which on my examination related to missing `VersionTracking/WallaceSrc` and possible `VersionTracking/WallaceSrc2` files/folders. This fails at least 100 tests.

Not only this one tests, but bunch of others related to VersionTracking

- BasicSelfSimilarCorrelatorTest.testExactInstructions
This one also expect to have file `pe/w2krtm/NOTEPAD.EXE.analyzed.dont.edit`.

- testLD_NoWith
This one fails with 
```
java.lang.NullPointerException
	at ghidra.app.plugin.processors.sleigh.SleighLanguage.initialize(SleighLanguage.java:107)
	at ghidra.app.plugin.processors.sleigh.SleighLanguage.<init>(SleighLanguage.java:100)
	at ghidra.app.plugin.processors.sleigh.SleighLanguageProvider.getNewSleigh(SleighLanguageProvider.java:112)
	at ghidra.app.plugin.processors.sleigh.SleighLanguageProvider.getLanguage(SleighLanguageProvider.java:99)
	at ghidra.pcodeCPort.slgh_compile.WithBlockTest.setUp(WithBlockTest.java:47)
	at generic.test.TestThread.run(TestThread.java:106)
```

due to missing "TestWith:BE:32:default". Does I need to perform additional steps in addition to `gradle buildGhidra`

- testWinmineNormalCases
This one fails when accessing "Winmine__XP.exe.gzf"

- testDecompiler_CopyFromSymbolWithoutSelection
This one accessing "ghidra/app/extension/datatype/finder/functions_with_structure_usage.gzf"

- testAddNameDiffOnSubOperandPickLatestMy
failing with 
```
org.junit.ComparisonFailure: expected:<[NADA]> but was:<[FOUR]>
	at ghidra.app.merge.listing.EquateMergeManager1Test.testAddNameDiffOnSubOperandPickLatestMy(EquateMergeManager1Test.java:607)
	at generic.test.TestThread.run(TestThread.java:106)
```

Not sure what this is means.

- testSaveButtonEnablement
Fails with 
```
java.lang.AssertionError
	at ghidra.app.plugin.core.script.AbstractGhidraScriptMgrPluginTest.assertSaveButtonEnabled(AbstractGhidraScriptMgrPluginTest.java:1074)
	at ghidra.app.plugin.core.script.GhidraScriptMgrPlugin2Test.testSaveButtonEnablement(GhidraScriptMgrPlugin2Test.java:475)
	at generic.test.TestThread.run(TestThread.java:106)
```

Have no idea.

I will stop at that point, since I likely generate not very actionable list of things and it is boring to look for some omissions. You can take a look at list of failed tests [here, in my build](https://codevision.visualstudio.com/Ghidra/_build/results?buildId=11358&view=ms.vss-test-web.build-test-results-tab&runId=1015410&resultId=108767&paneView=debug)

**Comment by kant2002** [comment]
And one more set of tests which are failing in Mac/Linux
- testEdgeFocusMode_SCOPED_REVERSE
```
java.lang.AssertionError: Edge was not selected: [1, 2]
	at ghidra.graph.viewer.edge.VisualGraphPathHighlighterTest.assertInFocusedPath(VisualGraphPathHighlighterTest.java:668)
	at ghidra.graph.viewer.edge.VisualGraphPathHighlighterTest.assertAllEdgesInFocusedPath(VisualGraphPathHighlighterTest.java:718)
	at ghidra.graph.viewer.edge.VisualGraphPathHighlighterTest.testEdgeFocusMode_SCOPED_REVERSE(VisualGraphPathHighlighterTest.java:299)
	at generic.test.TestThread.run(TestThread.java:106)
```

**Comment by kant2002** [comment]
Indeed. That's clear all that issues. I have other more interesting tests. but this one is closed I believe.

**Comment by kant2002** [comment]
Actually I was a bit in hurry to close, since I check on build which run regular tests, but when I run build with integration tests it exhibit same amount of failing tests. Most of them due to to missing `VersionTracking/WallaceSrc` and possible `VersionTracking/WallaceSrc2` files

**Comment by kant2002** [comment]
I finally add copying of the files to build definition, and hopefully it helps
Build where I expect some reduction in failing tests 
https://codevision.visualstudio.com/Ghidra/_build/results?buildId=12981&view=results

**Comment by kant2002** [comment]
Still `testLD_NoWith` does not working and fails with NPE. 
```
java.lang.NullPointerException
	at ghidra.app.plugin.processors.sleigh.SleighLanguage.initialize(SleighLanguage.java:115)
	at ghidra.app.plugin.processors.sleigh.SleighLanguage.<init>(SleighLanguage.java:101)
	at ghidra.app.plugin.processors.sleigh.SleighLanguageProvider.getNewSleigh(SleighLanguageProvider.java:112)
	at ghidra.app.plugin.processors.sleigh.SleighLanguageProvider.getLanguage(SleighLanguageProvider.java:99)
	at ghidra.pcodeCPort.slgh_compile.WithBlockTest.setUp(WithBlockTest.java:47)
	at generic.test.TestThread.run(TestThread.java:106)
```

I copy `GhidraDocs/GhidraClass/ExerciseFiles/VersionTracking/WallaceSrc.exe` to `Ghidra/Test/TestResources/data/VersionTracking/WallaceSrc.exe`, but in the test code I do not see `.exe` prefix. Should I drop .exe when copy files?

**Comment by kant2002** [comment]
@ryanmkurtz can I ping you to answer my last question, I may push this forward.

**Comment by rgov** [comment]
These are missing from the Decompiler integration test suite:

```
elf/CentOS/32bit/decomp.gzf
ghidra/app/extension/datatype/finder/functions_with_structure_usage.gzf
Winmine__XP.exe.gzf
```

I assume that only small sections of these projects files/executables are needed, so perhaps it would be possible to create alternatives that are permissible to add to version control so that open source contributors can run the test suite.

**Comment by dragonmacher** [comment]
Unfortunately, it was a mistake (oversight, really) on our part to release that do not have the test data available.

I haven't looked, but in theory we should be able to create a `ProgramBuilder` from the test data that can be used programmatically by the tests.  Then we would not need binary test data.
