### ISSUE TITLE
"Bad OMF data" when importing library

### ISSUE THREAD

**Issue by carlreinke** [NationalSecurityAgency/ghidra#965]
**Describe the bug**
The importer throws `java.io.IOException` with a message saying "Bad OMF data" when importing LIBH.LIB, the "General helper library" included with Microsoft C Compiler v6.00A.

**To Reproduce**
1. Import LIBH.LIB
2. Choose "Batch"
4. See exception:
```
Error importing file: affaldiv
java.io.IOException: Bad OMF data
	at ghidra.app.util.bin.format.omf.OmfSegmentHeader$SectionStream.establishNextBuffer(OmfSegmentHeader.java:406)
	at ghidra.app.util.bin.format.omf.OmfSegmentHeader$SectionStream.read(OmfSegmentHeader.java:428)
	at java.base/java.io.InputStream.read(InputStream.java:279)
	at ghidra.util.MonitoredInputStream.read(MonitoredInputStream.java:124)
	at db.ChainedBuffer.fill(ChainedBuffer.java:1167)
	at db.DBBuffer.fill(DBBuffer.java:162)
	at ghidra.program.database.mem.MemoryMapDBAdapterV2.createBuffer(MemoryMapDBAdapterV2.java:214)
	at ghidra.program.database.mem.MemoryMapDBAdapterV2.createInitializedBlock(MemoryMapDBAdapterV2.java:157)
	at ghidra.program.database.mem.MemoryMapDB.createInitializedBlock(MemoryMapDB.java:471)
	at ghidra.app.util.MemoryBlockUtil.createInitializedBlock(MemoryBlockUtil.java:249)
	at ghidra.app.util.opinion.OmfLoader.processSegmentHeaders(OmfLoader.java:323)
	at ghidra.app.util.opinion.OmfLoader.load(OmfLoader.java:132)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:346)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:114)
	at ghidra.plugin.importer.ImporterUtilities.doSingleImport(ImporterUtilities.java:360)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$6(ImporterDialog.java:363)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:93)
	at ghidra.util.task.Task.monitoredRun(Task.java:128)
	at ghidra.util.task.TaskLauncher.lambda$startBackgroundThread$2(TaskLauncher.java:315)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Expected behavior**
Import imports file and does not throw exception.

**Attachments**
[LIBH.zip](https://github.com/NationalSecurityAgency/ghidra/files/3564667/LIBH.zip)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Java Version: Java 12.0.2
 - Ghidra Version: 9.0.4

**Comment by ryanmkurtz** [comment]
I don't know OMF but I'm taking a shot at this.

**Comment by ryanmkurtz** [comment]
I ended up just changing how the error gets reported because I couldn't find anything we were doing wrong while parsing it.  As far as I can tell, there are some offsets that just don't appear to be following the spec.  Anyway, your batch import should now succeed.
