### ISSUE TITLE
How to open an embedded .gdt file from a Ghidra Extension?

### ISSUE THREAD

**Issue by Ayrx** [NationalSecurityAgency/ghidra#976]
In my Extension, I have a `.gdt` archive in the `src/main/resources` directory that I want to import when a script is run.

This is the code I am currently using:

```java
private DataTypeManager getDataTypeManageFromArchiveFile() throws IOException, DuplicateIdException {
	PluginTool tool = this.state.getTool();
	DataTypeManagerService service = tool.getService(DataTypeManagerService.class);

	URL jniArchiveURL = ClassLoader.getSystemClassLoader().getResource("jni_all.gdt");
		File jniArchiveFile = new File(jniArchiveURL.getFile());

	Archive jniArchive = service.openArchive(jniArchiveFile, false);
	return jniArchive.getDataTypeManager();
}
```

However, this fails to run because it tries to acquire a write lock in a non-existent directory even when `service.openArchive` has `acquireWriteLock` set to `false`. The stack trace of the failure is as follows:

```
Unable to write to lock file: /home/ayrx/tools/ghidra_9.0.4/file:/home/ayrx/tools/ghidra_9.0.4/Ghidra/Extensions/JNIAnalyzer/lib/JNIAnalyzer.jar!/jni__all.gdt.lock
java.io.IOException: No such file or directory
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(File.java:1024)
	at ghidra.framework.store.local.LockFile.createLockFileNoWait(LockFile.java:449)
	at ghidra.framework.store.local.LockFile.createLock(LockFile.java:381)
	at ghidra.framework.store.db.PackedDatabase.lock(PackedDatabase.java:456)
	at ghidra.framework.store.db.PackedDatabase.readContentTypeAndName(PackedDatabase.java:474)
	at ghidra.framework.store.db.PackedDatabase.<init>(PackedDatabase.java:96)
	at ghidra.framework.store.db.PackedDatabase.getPackedDatabase(PackedDatabase.java:289)
	at ghidra.program.database.data.DataTypeManagerDB.<init>(DataTypeManagerDB.java:176)
	at ghidra.program.model.data.StandAloneDataTypeManager.<init>(StandAloneDataTypeManager.java:55)
	at ghidra.program.model.data.FileDataTypeManager.<init>(FileDataTypeManager.java:56)
	at ghidra.program.model.data.FileDataTypeManager.openFileArchive(FileDataTypeManager.java:101)
	at ghidra.app.plugin.core.datamgr.archive.FileArchive.<init>(FileArchive.java:54)
	at ghidra.app.plugin.core.datamgr.archive.DataTypeManagerHandler.openArchive(DataTypeManagerHandler.java:429)
	at ghidra.app.plugin.core.datamgr.archive.DataTypeManagerHandler.openArchive(DataTypeManagerHandler.java:419)
	at ghidra.app.plugin.core.datamgr.DataTypeManagerPlugin.openArchive(DataTypeManagerPlugin.java:715)
	at JNIAnalyzer.getDataTypeManageFromArchiveFile(JNIAnalyzer.java:146)
	at JNIAnalyzer.run(JNIAnalyzer.java:53)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:370)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:222)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:200)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:57)
	at ghidra.util.task.Task.monitoredRun(Task.java:128)
	at ghidra.util.task.TaskLauncher.lambda$startBackgroundThread$2(TaskLauncher.java:315)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

How do I accomplish this task?

**Comment by ryanmkurtz** [comment]
You could try sticking the gdt file in the data directory, and then use `Application.getModuleDataFile()` to access it.

**Comment by Ayrx** [comment]
That did the trick. Thanks! For reference, the code used is:

```java
ResourceFile jniArchiveFile = Application.getModuleDataFile("JNIAnalyzer", "jni_all.gdt");
Archive jniArchive = service.openArchive(jniArchiveFile.getFile(true), false);
```
